### ISSUE TITLE
[BUG]Recipe conflict

### ISSUE THREAD

**Issue by ThatGravyboat** [Darkosto/SevTech-Ages#1]
stick bundle and ladder has the same recipe so you can make a stick bundle

~Gravy

**Comment by Darkosto** [comment]
That's strange, ladder is not craftable until a later stage and stick bundles requires twine. They shouldn't be overwriting. Hmm

**Comment by Darkosto** [comment]
![image](https://user-images.githubusercontent.com/10309699/29903421-cf502586-8dd1-11e7-893c-9c0afd4f08fe.png)

**Comment by Darkosto** [comment]
Ahh, I take that back. I see the issue. Ladder grabbed the stick bundle recipe for some reason. Weird

**Comment by Darkosto** [comment]
All fixed up!
