### ISSUE TITLE
Update 3.03 seems to have broken my Antique Atlas

### ISSUE THREAD

**Issue by DerpityDoo** [Darkosto/SevTech-Ages#1001]
After update 3.03, generating new chunks causes a mismatch with my atlas graphic.  Giving myself a new atlas (i.e Antique Atlas #1 vs Antique Atlas #0) does not solve the issue. Chunks generated in the previous version are still accurate, while any chunks generated in the new version are not accurately represented

**Comment by justinrusso** [comment]
Can you try a new world for testing this? Sounds like your biome IDs shifted.

**Comment by K3ll06s** [comment]
Same issue for me, new chunks generated in my "old" world appear as ocean. Atlas in new world works fine.

**Comment by justinrusso** [comment]
Sounds like a Biome ID shift, and nothing can be done about this unfortunately. This has been an issue for quite a while: https://github.com/AntiqueAtlasTeam/AntiqueAtlas/issues/159.

Not sure *why* your worlds' biome IDs shifted though...

**Comment by Jandakast** [comment]
This shouldn't happen with a pack update. I have tried updating several worlds created in 3.0.0, 3.0.1, and 3.0.2 to the 3.0.3 and 3.0.4 version on Windows and Ubuntu without being able to reproduce this.

Was this Single Player or Servers worlds? Was anything about the pack changed. IE mods added/removed, configs changed, or running on a Sponge server?
