### ISSUE TITLE
Framed Drawer XRAY

### ISSUE THREAD

**Issue by MyApolloGees** [Darkosto/SevTech-Ages#1003]
## Issue / Bug
Framed drawer lets you see through the map when on the floor.

![2018-03-28_14 31 07](https://user-images.githubusercontent.com/37778378/38032404-70dda442-3295-11e8-8793-b5779d10b866.png)

**Comment by artdude543** [comment]
This is a quirk with the mod tbh; if you used all the slots the create the draw you won't have this issue ;)
