### ISSUE TITLE
Conversion Wand is more powerful than hammers or pickaxes as a mining tool

### ISSUE THREAD

**Issue by Vyraal1** [Darkosto/SevTech-Ages#1005]
## Issue / Bug
Conversion Wand (available in Stage 2) when combined with flowers, is a much better mining tool than any other tool available at the moment.

## Possible Solution
Not sure, don't think there's a whitelist/blacklist for this wand, only did a quick scan.

## Steps to Reproduce (for bugs)
https://streamable.com/uqsg5

## Your Environment
Pack Version 3.03

**Comment by artdude543** [comment]
Yeah okay, this is something; to negate this I guess we could change this config @Darkosto?

```
# Sets the max. hardness the exchange wand can swap !from!. If the block you're trying to "mine" with the conversion wand is higher than this number, it won't work. (-1 to disable this check) [range: -1.0 ~ 50000.0, default: -1.0]
S:exchange_wand_max_hardness=-1.0
```
