### ISSUE TITLE
Coal to coal piece recipe not working

### ISSUE THREAD

**Issue by Syltann** [Darkosto/SevTech-Ages#1006]
If the recipe is supposed to be there It is currently not working in any crafting table I've tried. I'm on the latest version and on stage 2.

![2018-03-28_07 20 31](https://user-images.githubusercontent.com/30686588/38035192-b3b48d54-3258-11e8-9a73-b280b90117a9.png)

**Comment by Ryzelf** [comment]
I am sure this is a visual bug i think that you are only suppose to use the grindstone to obtain coal pieces

**Comment by artdude543** [comment]
I found the issue it's a recipe conflict with another mod. This will be fixed in the next version :)

**Comment by VallenFrostweaver** [comment]
@artdude543  I don't think this was finished being fixed. I'm in Stage 1 and can place coal in my inventory and get 8 invisible coal pieces (and they work fine - just no texture). See image:
![coal piece](https://user-images.githubusercontent.com/13642054/39048087-317bb31e-4494-11e8-89e0-b19c76e9e16c.png)

**Comment by artdude543** [comment]
The texture issue is another issue altogether; one is open somewhere for it (along with other items with missing textures)

**Comment by VallenFrostweaver** [comment]
Ah. Sorry, got lost with all the posts. I must've overlooked it. Thank you.
