### ISSUE TITLE
Game Crash in Nether

### ISSUE THREAD

**Issue by kugamer** [Darkosto/SevTech-Ages#1007]
Issue / Bug
Game crashed when I was attacking a mob in the nether. It was a spinning saw mob. 
https://pastebin.com/ugt2npj

Current Behavior
 Game crashed in nether when attacking mob

Possible Solution
I am not sure

 Steps to Reproduce (for bugs)
1. I have not been able to reproduce yet
2.
 add more if needed 

Context
 I was mining netherrack with tinkers hammer a chunk away from portal and spinning saw blade mobs attacked me, I attacked back and game crashed. 

Your Environment
Modpack Version:3.0.3
Java Version:1.8.0_161
Launcher Used:Twitch app
Resourcepack Enabled?:faithfull
Optifine Installed?:no

**Comment by artdude543** [comment]
That PasteBin is not valid can you re-upload please, thanks?

**Comment by kugamer** [comment]
https://pastebin.com/imbBSRkU

**Comment by justinrusso** [comment]
This resulted in the same issue as https://github.com/Darkosto/SevTech-Ages/issues/1209
