### ISSUE TITLE
[3.0.2] Silicon item is stage five, but silicon ore is unlocked in stage four

### ISSUE THREAD

**Issue by Pandemoneus** [Darkosto/SevTech-Ages#1008]
^ Title

**Comment by artdude543** [comment]
Their both stage 4? Unless I'm missing something 
![](https://i.artdude.uk/xI5BexRU.png)

**Comment by Pandemoneus** [comment]
After a restart I can now access the item too. The bug was present when I went from stage three to stage four. I wondered about that, because when I mined surface samples I immediately dropped the raw silicon from my hand saying that I don't have access to stage five yet.

**Comment by Pandemoneus** [comment]
Did some advancements in age 4, now it's bugged again:
https://imgur.com/a/0Q8Up

**Comment by davqvist** [comment]
I am having the same issue. It is stage 5 for me too.

**Comment by kylertoll** [comment]
Same issue here, Silicon is stage 5.
