### ISSUE TITLE
Progression stuck in MP

### ISSUE THREAD

**Issue by veryhasted** [Darkosto/SevTech-Ages#1009]
Issue / Bug
Advancements sometimes finish but most of the time gets stuck at 1/2 even though they should be completed. (We're two people in a tf group)

Current Behavior
Trying to progress, can't. It shows 1/2 and won't finish it, no matter what we do (drop it, make another one, forcesync etc.) We had to cheat our way to Age 1 as we had completed all Age 0 quests but still didn't unlock.

Possible Solution
I am not sure

Steps to Reproduce (for bugs)

Make a tf group and progress. Once Age 1 doesn't unlock cheat it and you'll have to cheat almost every quest for it to unlock.

Your Environment
Modpack Version: 3.0.3
Java Version: 1.8.0_25
Launcher Used: Twitch app
Resourcepack Enabled?: no
Optifine Installed?: no

**Comment by majiktek** [comment]
I am also experiencing this issue in Age 1 on my server.  I play with three other players.  None of us are in teams.  The two other players are getting advancements just fine, but I am stuck at 1/2 on many of them.  I haven't tried cheating any of them yet.

**Comment by justinrusso** [comment]
Can you specify what advancements? Were these advancements you already saw on the screen, or are they new ones you just discovered?

**Comment by veryhasted** [comment]
All the early Age 1 ones. So yeah they were on the screen, for example Wooden basin, chest, furnace, aqueduct etc. etc.

**Comment by majiktek** [comment]
In my case so far, they are the Upgrade your chest, Plumb Line, Anvil, and Weak Dowsing Rod.

**Comment by veryhasted** [comment]
After reading around a bit more it seems it is due to me updating the pack mid progression.

**Comment by justinrusso** [comment]
Correct, but that is not your fault. we want you to be updating! We have a fix in the work for 3.0.4

**Comment by veryhasted** [comment]
Sounds good, thanks a lot!
