### ISSUE TITLE
Jared keeps stealing my items!

### ISSUE THREAD

**Issue by darkhax** [Darkosto/SevTech-Ages#101]
### Issue / bug
I was playing with Jared on a server, and he kept stealing my items 🙁 Could you look into getting the chopping block and work stump to change how it gives items to the player? If they made it so the player crafting the item was set as the owner in the item tag, that player would have a grace period where only they can pick it up, similarly to when you drop an item on the ground.

**Comment by Drullkus** [comment]
jared is mean, go teach him a lesson 😛

**Comment by vadis365** [comment]
Make a sword, hit Jared with it a few times and you will get your items back and more.

**Comment by jaredlll08** [comment]
The issue just got worse! @darkhax is now stealing my items! ;,,;

**Comment by Darkosto** [comment]
You should tell Jared that he is not allowed to play and kick him out of the clubhouse! NO GIRLS ALLOWED!

**Comment by Drullkus** [comment]
Rood.

**Comment by darkhax** [comment]
Seriously though, has this been fixed, or reported to the relevant mods? X)
