### ISSUE TITLE
Luminous Crafting Table ritual ate items and didn't Infuse when placing book on energy pedestal before ritual finished.

### ISSUE THREAD

**Issue by MrBirk** [Darkosto/SevTech-Ages#1010]
## Issue / Bug

I went to craft a Luminous Crafting table and started the ritual and put the book back on the charging pedestal before it finished. Lightning struck and it ate all my items except the crafting table in the middle which was still a vanilla table. It did not use up the charged I had stored in my Necronomicon. Not sure if this is a mod bug I have not done much Abyssalcraft before.

## Possible Solution

Replacing items and keeping the necronomicon in my inventory allowed me to properly craft it the second time but I feel it is a bug that it ate the items the first time when I placed it back in the pedestal before it finished. It doesn't state you shouldn't do that it merely states you should shift right click to start it.

## Steps to Reproduce (for bugs)

1. Start infusion ritual for Luminous Crafting table.
2. Put Necronomicon on energy pedestal before ritual finishes

## Your Environment

* Modpack Version: 3.0.3
* Java Version: 1.8.0.161
* Launcher Used: Twitch/Jar
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by artdude543** [comment]
Seems like a random glitch. And/Or could be fixed in later versions of the modpack. If this is still an issue please open a new issue (when using the latest version) and supply updated information.
