### ISSUE TITLE
Age 2 Advancment issue

### ISSUE THREAD

**Issue by frogger35** [Darkosto/SevTech-Ages#1011]
## Issue / Bug
After crafting and placing the Weirding Gadget the advancement didn't trigger
After crafting the Resonating wand from Astral Sorcery the advancement didn't' trigger

You can see in my hotbar (kinda it's a little dark) that I have the resonating wand and weirding gadget.

![2018-03-28_10 43 16](https://user-images.githubusercontent.com/5314324/38040586-70a37d5a-3275-11e8-875c-7de18967d898.png)

Edit: Not shown is that when hovering over both of those achievements it says 1 of 2.

## Your Environment

* Modpack Version: 3.0.3
* Java Version: 1.8.0_144
* Launcher Used: twitch
* Resourcepack Enabled?: no
* Optifine Installed?: yes

**Comment by artdude543** [comment]
These just triggered fine for me in a test world. And this was reported on an old version so the issue could have been fixed a long the way. Please update and try again 🙂
