### ISSUE TITLE
Mipmap texture Glitch & Render Issue

### ISSUE THREAD

**Issue by Tophenator** [Darkosto/SevTech-Ages#1013]
If you change the Mipmap from the default 4 that it is set at to 0 it changes the lids on the render for the ImmersiveCraft chests. I then restored it back to 4 and it did not fix the issue. It would render: ingots, clocks, and other items for the lid of the chest. Also if you try to break objects the render on the cracked object is random items.  

I was using the  Sev Tech- Ages: 3.0.2 update.

**Comment by artdude543** [comment]
If you change any kind of resource setting you **have** to reboot the game. This is an issue with Vanilla itself and nothing we can do to fix it. Also please update to 3.0.3 .2 is really buggy.

**Comment by Tophenator** [comment]
Thank you
