### ISSUE TITLE
Issue Template Feedback

### ISSUE THREAD

**Issue by ArbitraryHubris** [Darkosto/SevTech-Ages#1016]
I know every development team has their own vernacular, but the point of this template is to elicit better issue descriptions from people not on this development team.  

`Issue/Bug` should describe the current behavior - this is what is wrong.  Your description text under Issue / Bug asks for what should happen, not what happened.
> ## Issue / Bug 

I think Current Behavior should be re-written to ask for `Expected Behavior`.  This is what the reporter thinks should have happened if there were not an issue
> ## Current Behavior

**Comment by artdude543** [comment]
Yeah, I'm still working on the template but I'll take your changes into account! 😄 (And I prefer the re-wording)
