### ISSUE TITLE
Bug Report / config change suggestion regarding infinite water within the beach and deep ocean biomes

### ISSUE THREAD

**Issue by BerryRJ** [Darkosto/SevTech-Ages#1017]
## Issue / Bug
According to the watercontrolextreme.cfg file, water should be infinite within the beach biome but it is not.

## Current Behavior
Water is infinite in the river and ocean biomes, but not the beach biome.

## Possible Solution
The problem seems to be with the mod so I have placed a bug report in the comments of the Curse page

As for the config change, while testing to see if the problem was with the mod or the pack I found that the deep ocean biome also doesn't have infinite water. So maybe minecraft:deep_ocean could be added to the config file?

**Comment by artdude543** [comment]
The missing ocean/beaches have been added in 3.0.5 😄
