### ISSUE TITLE
Leaf bed spawn point?

### ISSUE THREAD

**Issue by ScorchSter** [Darkosto/SevTech-Ages#1018]
## Issue / Bug
leaf bed not setting spawn in Age 1.

## Current Behavior
Died with leaf bed used for sleeping without a teepee.
Spawned at spawn point instead of leaf bed.

## Steps to Reproduce (for bugs)

1.  use leaf bed for spawn
2.  have no tipi active

## Your Environment

* Modpack Version: 3.0.3
* Java Version:  8  build 161
* Launcher Used: twitch/curse
* Resourcepack Enabled?: no
* Optifine Installed?: no

**Comment by vadis365** [comment]
I can't duplicate this bug. Pack testers please confirm this is a thing and not a random weird event.

**Comment by ScorchSter** [comment]
I've recreated this bug twice now intentionally. Both times I got the error in chat which stated "home bed missing or obstructed".   I moved my bed to a different location and intentionally died again. I received same error "Home bed missing or obstructed".  Both times, my bed was not near any walls or have anything above it.

**Comment by Darkosto** [comment]
I personally cannot reproduce. But, I've had people on dedicated servers confirm it works correctly and a few people test on LAN with no trouble. Maybe recraft the bed, place it down, sleep in it again to see if it was a bugged block?
