### ISSUE TITLE
Striped dark oak

### ISSUE THREAD

**Issue by Superslammer** [Darkosto/SevTech-Ages#1019]
## Issue / Bug
The striped dark oak log loks like this
![udklip](https://user-images.githubusercontent.com/29737567/38044042-eea0f050-32b8-11e8-802e-b3b5d61cb4fd.PNG)

## Current Behavior
It tells what it is but in a strange way

## Possible Solution
Don't know

## Steps to Reproduce (for bugs)
https://streamable.com/vjoet

## Context
It is not game changing but it would look nicer if it were fixed

## Your Environment

* Modpack Version: 3.0.1
* Java Version: Java 8 build 1.8.0_161-b12
* Launcher Used: Twitch launcher
* Resourcepack Enabled?: Yes
* Optifine Installed?: No

**Comment by Darkosto** [comment]
Shared with the dev of PrimalCore. Hopefully, he can localize this block.

**Comment by An-Sar** [comment]
this has now been fixed in dev, will be in the next (0.6.44) release

**Comment by artdude543** [comment]
This is fixed in 3.0.5 :)
