### ISSUE TITLE
IC Rock breaking vs Hidden surface sample breaking

### ISSUE THREAD

**Issue by BigAl607** [Darkosto/SevTech-Ages#1020]
Breaking the Immersive Craft rocks makes the correct sound, and breaks almost instantly. When breaking a hidden surface sample that looks like the IC stone, it takes longer to break (with bare hand) and sounds like you're digging sand/dirt. While you do only get the IC stone when harvested, it also allows the player to know that there's a sample there, and they should probably not break any more samples in that area.

## Steps to Reproduce (for bugs)
1. Spawn a world and start breaking samples. When you find a sample that takes longer to break and sounds different, increase the player's stage and give everything and you'll see samples instead of te rocks.

## Your Environment

* Modpack Version: 3.0.3
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by Saereth** [comment]
to add to this, if you dig the block below the hidden surface rock it will drop an actual sample not the immersive rock, confirmed this with silicon sample in stage 2 at least.

**Comment by justinrusso** [comment]
This is currently a limitation with the mod. Would need some forge changes to make this work.

**Comment by artdude543** [comment]
This is something we won't ever get changes into Forge to work _right_. Closing this out for now as it's something we can't do/offer. Up to the mod developer to explore this avenue.
