### ISSUE TITLE
Client crash on respawn near Water Wheel

### ISSUE THREAD

**Issue by mtimyself** [Darkosto/SevTech-Ages#1021]
## Issue / Bug
After dying the client decides to die as well.

## Steps to Reproduce (for bugs)
1. Die
2. Respawn near a water wheel
3. Crash

## Crashlog
https://pastebin.com/veCEw6Lk

## Environment
* Modpack Version: 3.0.3
* Java Version: 1.8.0_25
* Launcher Used: Twitch
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by artdude543** [comment]
Known will be fixed in the next version; you can update Better with Mods manually if you want to get around the issue.
