### ISSUE TITLE
Sitting bald eagles start chasing after breaking blocks

### ISSUE THREAD

**Issue by bearY0** [Darkosto/SevTech-Ages#1022]
So the game has this behaviour for mobs where they get scared when you place or break a block near them. My problem is a have a lot of tamed bald eagles and everytime i break something in my base they get up from their Sitting stance and start following me which is annoying to say the least.

**Comment by wyndman** [comment]
They also have a nasty habit of standing in the way and getting themselves killed.

**Comment by Darkosto** [comment]
This behavior was removed in update 3.0.2 I believe. Let me know if this issue persists after you update.

**Comment by bearY0** [comment]
Ya sorry I totally forgot to update. Keep up the awesome work with the mod pack!
