### ISSUE TITLE
Water Powered Saw & Server file updates

### ISSUE THREAD

**Issue by sinistar26** [Darkosto/SevTech-Ages#1023]
Water Saw causes game crash when clicked with an ax.  ( I already know this is not the way to pick it up ) And server file update ??  Can I just replace the updated files on my server with the new ones in the DL??

**Comment by artdude543** [comment]
You'll have to wait for 3.0.4 to fully fix this issue; You can manually update the Better with Mods, however, to get around the issue until then.

With the server download from Curse delete all the folders listing in the server download on your actual server and then upload the new folders. We'll have a more detailed guide soon.
