### ISSUE TITLE
Geolosys ore generation not working correctly for gold (and possibly other ores) or showing on /oredistribution [3.0.3]

### ISSUE THREAD

**Issue by Electrofried** [Darkosto/SevTech-Ages#1026]
## Issue / Bug

Geolosys ore or samples are flat out not generating for some ore types (gold, rock crystal, maybe iron samples) except under very rare circumstances.  
As noted in  #996 ore samples for some ores are not spawning correctly. However I have been doing some testing in regards to gold spawning. In new worlds created with version 3.0.3 I searched many chunks (10000+) and found zero gold/rock crystal samples

On two existing server worlds created in version 3.0.1 I have done the same search over a much larger area and found one single gold sample and one rock crystal. So it does spawn, it is just incredibly rare.

(These worlds were pregenerated using chunk pregenerator mod. However single player testing was done with this disabled to make sure it is not a pregen issue)

I then went and edited the geolosys_ores.json with these changes:

`"goldSize": 60,
"goldChance": 90,
"goldMinY": 5,
"goldMaxY": 90`

This resulted in some gold ore sample generation (2 sample groups found in a 3000x3000 chunk area) using visual scanning. However /oredistribution does not show gold ore on its list as seen in the following picture, this was done using ore distribution command searching 250 radius  from 0 to 100.

![fc734cfd1cdcb1ebbba58fba373a862a](https://user-images.githubusercontent.com/27886155/38052257-fcb7438c-3313-11e8-87ec-4ad73facf53d.png)
(That is gold ore in the background)

## Current Behavior

Ore spawn or samples, (gold and rock crystal ore) are not spawning in world except under very rare circumstances and /oredistabution does not show gold/rock crystal ore. 
 
## Possible Solution
\o/

## Steps to Reproduce (for bugs)
1. create new world using default config/world type
2. generate a ton of chunks
3. look for gold with /oredistribution or visually
4. cry

## Context

Running public servers, everyone is yelling at me because no one can advance through age 2 because of lack of gold/rock crystal and iron. 

## Your Environment

* Modpack Version: 3.0.3
* Java Version: yes
* Launcher Used: twitch / multimc
* Resourcepack Enabled?: no
* Optifine Installed?: no

**Comment by Electrofried** [comment]
Further investigation has revealed that this is an issue with samples not spawning in. I used world stripper to confirm.  Multiple veins were uncovered with no sample above them for gold. /oredistribution still does not show certain ores.

**Comment by Darkosto** [comment]
Hey @oitsjustjose is this something you've covered in the latest update?

**Comment by oitsjustjose** [comment]
So I'll look at the configs later to verify what's up, but I've noticed that (and as far as I'm aware this is a *vanilla* MC bug) if you say "X ore generate from y=10 to y=20", and then you say "Y ore generate from y=10 to y=20", only Y will generate (or whichever was *last* registered).

This is just a weird thing that happens. I will look into it though, I wonder if I can control it on my end by using less / none of Vanilla's nonsense (like I've been slacking on).

**Comment by RobbeSchepens** [comment]
Hi, I wanted to add to the conversation as I googled and this page showed up. A friend and I were struggling with gold as well. After a long search, I managed to find a gold sample in a large 'flat' snow biome where pinguins and polar bears sometimes spawn. Same issue with Lapis, which actually spawned pretty close to it. It's cool to add some exploration to the game, but I feel like it's a bit too much searching for randomly generated ores. 

Also, can confirm /oredistribution does not work for gold nor lapis.

**Comment by oitsjustjose** [comment]
![img_0241](https://user-images.githubusercontent.com/3887324/38280977-540f0046-3776-11e8-8eb1-4941a6a2a66c.JPG)

**Comment by kadman04** [comment]
Having this same issue although I have found TONS of gold spawns on ground level there is 0 gold in the chunks of the samples cant continue until this is fixed.

**Comment by Darkosto** [comment]
This issue has been fixed 2 versions ago. There's no need to continue to pile onto an old issue. I've confirmed from multiple users that gold and other ores are spawning normally.
