### ISSUE TITLE
Silk Touching Limonite Ore Drops Vanilla Minecraft ore

### ISSUE THREAD

**Issue by Vyraal1** [Darkosto/SevTech-Ages#1027]
## Issue / Bug
- Silk touching a limonite ore drops vanilla minecraft iron ore, which is an overall worse output for Nickel than just mining it naturally. 

- My Suggestion:
According to [this class](https://github.com/oitsjustjose/Geolosys/blob/98d88036c23c13f94d6df84b01cfd10e67ea47d8/src/main/java/com/oitsjustjose/geolosys/blocks/BlockOre.java#L75), mining Limonite has a 20% chance to drop nickel cluster instead of iron cluster, but silk touching Limonite successfully in NEI shows that you can get nickel clusters as a 50% byproduct from processing Limonite Ore in an IE crusher.

However vanilla minecraft iron ore has only a 10% chance to produce nickel, so silk touching is pretty much a downgrade if you need Nickel (which is the main reason you want Limonite in the first place). **Would it be possible to have Limonite Ore successfully drop itself?**

At the very least, if 50% of nickel from limonite ore sounds too powerful, you can always tweak it to 20% byproduct change assuming Immersive Engineering has the crafttweaker support.

## Steps to Reproduce (for bugs)
https://streamable.com/sskrg

## Your Environment
* Modpack Version: 3.03

**Comment by Darkosto** [comment]
Correct, that is intended Geolosys behavior. Silk touching ore is not meant to be more profitable. That's how the pack is setup. 

If I'm understanding you correctly, you expect it to give more? That's not how any of the pack is setup to be. It's all based around clusters.

**Comment by MrHrulgin** [comment]
Speaking as someone who doesn't yet have a crusher to get nickel grit, it's counter intuitive that a silk touch pick is explicitly worse than a regular one for this purpose. 

My expectation would be that silk touching a block of limonite ore would do one of the following:

- Have a chance of dropping either iron or nickel ore blocks.
- Give the limonite ore block, which could be smashed on the stone anvil to get iron & nickel clusters.

I'm not attached to silk touch improving the production, but I do not like silk touching a vein of limonite and getting 0 nickel from it.
