### ISSUE TITLE
Friend unable to connect to Sevtech 3.0.1 Server

### ISSUE THREAD

**Issue by BetaCascade** [Darkosto/SevTech-Ages#1028]
## Issue / Bug
Good day, I've been trying to set up a Sevtech Ages server for a few hours now, and after finally being able to set up and connect to the server running on my own machine, my friend is unable to join and being present with this error https://cdn.discordapp.com/attachments/245261086482366465/428641707219746826/unknown.png

I'm not particularly well-versed in using forge or anything java-related in general so forgive me for being dumb

## Your Environment

* Modpack Version: 3.0.1
* Java Version: Java 8 Update 162
* Launcher Used: Twitch
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by Saereth** [comment]
that's a time out error pretty common in 1.10+ packs, for your server and your friend increase the timeout in your jvm arguments by adding -Dfml.readTimeout=90
that will increase the time out to compensate for slower computers.

**Comment by BetaCascade** [comment]
How would I go about adding/changing jvm arguments? Like I said I'm a total noob when it comes to this stuff sadly, thank you for your help!

**Comment by BetaCascade** [comment]
Alright, my friend has the jva arguments set on their client, and I _believe_ the same jva argument set on the server (I'll provide a picture at the bottom), but they still seem to timeout at ~30 seconds.  Another thing I've noticed is that when I connect it reads "logging in" but it reads "connecting to server" for my friend, though I'm not sure if that means anything.

afforementioned link:

https://cdn.discordapp.com/attachments/245261086482366465/428703052409864193/unknown.png

**Comment by BetaCascade** [comment]
Working now! I was just dumb and forgot to forward the server port
