### ISSUE TITLE
Books not craftable

### ISSUE THREAD

**Issue by mtimyself** [Darkosto/SevTech-Ages#1029]
## Issue / Bug

The recipe for vanilla books does not seem to be working. The vanilla recipe is listed in Stage 2.

http://prntscr.com/ixprrv
http://prntscr.com/ixpv4i

## Your Environment
Modpack Version: 3.0.3
Java Version: 1.8.0_25
Launcher Used: Twitch
Resourcepack Enabled?: No
Optifine Installed?: No

**Comment by sharkykh** [comment]
Not sure if that's the issue,
but I can't find `<minecraft:book>` staged in stage 2's `recipes.set.zs`.

**Comment by justinrusso** [comment]
@sharkykh right, because its in `recipes.remove.zs` and `recipes.add.shapeless.zs` :P

**Comment by sharkykh** [comment]
@justinrusso And I was wrong because I'm not a Modded Minecraft modpack dev :P

**Comment by Darkosto** [comment]
I've fixed this in dev. Should be out when 3.0.4 releases.
