### ISSUE TITLE
Client crash when connected to the server and opening advancements menu

### ISSUE THREAD

**Issue by VideoN0mad** [Darkosto/SevTech-Ages#1031]
## Issue / Bug
I've created a server from ATLauncher and set it up for correct worldgen. When I connect through localhost - everything is fine and advancements menu shows correctly. When I try to connect using my laptop (through LAN), it first times me out a few times and after successful login, it lets me into the game. Everything is fine until I try to open advancements menu. As soon as I press L, client crashes. Everything is fine in single player for both computers.

Crash Log:
https://pastebin.com/MyKfW5xq
Server Log
https://pastebin.com/zcXgpiTk

## Current Behavior
Client crash when connected to the server and opening advancements menu

## Steps to Reproduce
1. Create the server with quark worldgen options (level-type=quark_realistic)
2. Connect from a different computer through LAN (not localhost)
3. Try to open advancements menu (L button)

## Context
This laptop is quite old but it runs this modpack in single player without any problems (not 60fps though, no surprise here). I have a nice Wi-Fi network, so this shouldn't be a problem. We already played like this before (on other modpacks) and everything was fine.

## Environment
* Modpack Version: 3.0.3
* Java Version: jre-8u161-windows-x64
* Launcher Used: Twitch for Client and ATLauncher for Server
* Resourcepack Enabled: Faithful x32 modded edition
* Optifine Installed: Yes, on both clients

**Comment by artdude543** [comment]
This was fixed in later versions of the pack please update and try again! 😄
