### ISSUE TITLE
Celestial altar small issue

### ISSUE THREAD

**Issue by Gremilcar** [Darkosto/SevTech-Ages#1032]
## Issue 

Astral Sorcery requires it's own "raw" marble block for Celestial Altar while ore-gen spawns Chisel marble first

## Current Behavior

When building a structure around the Celestial altar using "Marble" block mined in the world will not form a proper structure. Currently player has to change it into "Marble" block through the chisel menu.

## Possible Solution

* Add a note in advancement to remind players that correct block is needed. 
* Allow chisel marble block be used
* Make Astral marble drop instead of chisel when mined
* spawn astral marble as ore instead of chisel marble,

## Your Environment

* Modpack Version: 3.0.3
* Java Version: 1.8.0. 161 (64)
* Launcher Used: Native

**Comment by Darkosto** [comment]
Right, this is why the player should have access to the chisel to change to the version that you need.

**Comment by artdude543** [comment]
Yep, this works as intended with the need for the chisel to convert blocks from one to another. The book does also state about using its own marble; so there is sufficient documentation in the game.
