### ISSUE TITLE
Unable to load pack - StitcherException

### ISSUE THREAD

**Issue by steffie9810** [Darkosto/SevTech-Ages#1033]
Issue / Bug
Cannot get past startup. Crashes every time and does not generate a crash log.
The crash message changed after reinstalling the pack multiple times. It was originally said that it was a chisle block that was causing the issue. Also i do not have ant resourcepacks.
https://prnt.sc/ixqihs

 Your Environment
 I have reinstalled the pack multiple times on each version. I checked all of my drivers and checked my java version. Everything is up to date. I have tried the native launcher and the Jar launcher and can't get anything to work.

**Comment by justinrusso** [comment]
https://github.com/Darkosto/SevTech-Ages/issues/924
