### ISSUE TITLE
Parchment/Astral Journal achievements not triggering

### ISSUE THREAD

**Issue by Mr-B-l-a-c-k** [Darkosto/SevTech-Ages#1034]
## Instruction on how to do issues like your boy darkosto

![2018-03-28_14 12 54](https://user-images.githubusercontent.com/37883978/38057056-1302b81e-3293-11e8-9281-cbbd8646d4bc.png)
![2018-03-28_14 12 58](https://user-images.githubusercontent.com/37883978/38057057-131bc99e-3293-11e8-9baf-d3f49d84b48c.png)
![2018-03-28_14 14 09](https://user-images.githubusercontent.com/37883978/38057058-13373daa-3293-11e8-89e2-242aa3a8caa4.png)

 
## Current Behavior
We crafted a piece of parchment and then the astral journal but the achievement didnt trigger for anyone on our team. We've tried relogging, forcing syncs, so far nada. 

## Steps to Reproduce (for bugs)

1.
2.

## Your Environment

* Modpack Version: 3.03
* Java Version: 1.8.0_161-b12
* Launcher Used: MMC
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by cheesealmighty** [comment]
I tried cheating in 4 pieces of parchment (could work with less) and it triggered. But don't know what the exact trigger is. Maybe try crafting a bit more parchment?

**Comment by Mr-B-l-a-c-k** [comment]
we're working on crafting more parchment now- I think we were the first ones since updating to 3.03 to get parchment and wasnt sure if it was bugged.

**Comment by Dystilled** [comment]
Did this in SP on 0.3 last night and it worked fine, may be to do with MP

**Comment by artdude543** [comment]
Yeah, I did this fine in my world a few days ago on 3.0.6 so this is not an issue with the pack itself.
