### ISSUE TITLE
[Improvement] Entitlement Request (Leather)

### ISSUE THREAD

**Issue by Notawallplan** [Darkosto/SevTech-Ages#1035]
## Issue
Making leather in stage 0 is tedious and is a turn-off point for many players.

## Current Behavior
Crafting leather first requires shaving the hide, then salting the hide (takes a full bucket and doesn't make multiple), then drying the salted hide, and _then_ smearing ground bark on it (requiring another bucket of water, and doesn't make multiple ether), then _finally_ drying it to make the actual leather.

## Context
It may be realistic, but oh hell is it boring and a turn off. Making *anything* related to leather requires 2 crafting operations (with a bucket-like item no less) and 2 processing operations per piece of leather.

## Possible Solution
I suggest ether reducing the liquid cost for it if possible, or come up with an in-world replacement solution. Like tossing salt and hide into water in order to make salted hide after a few seconds and ditto for the smeared hide.

## Your Environment
* Modpack Version: 3.0.3
* Java Version: 1.8.1.151
* Launcher Used: Java
* Resourcepack Enabled?: Proprietary
* Optifine Installed?: No.
* Mods Removed?: Smooth Text.

**Comment by justinrusso** [comment]
But it gets easier... Thats the whole point of the pack.

**Comment by cheesealmighty** [comment]
I think TFC really handles this one better. Manual crafting is frankly annoying, and I know that's the point. But a barrel system similar to TFC would be great. Like how the tinkers' construct drying racks are being utilized (thank god) instead of those terrible, terrible primal core ones.

**Comment by Darkosto** [comment]
I'd like to point out that when you attempt to persuade someone who has spent 1 year on making a customized modpack that you do not name your issue "Boredom Removal". Just a thought.

Secondly, just to let you know you actually only need 1 single leather to complete stage 0 which opens a pathway to crafting 3 at a time. 

Leather can also be traded from a villager. I would exhaust all of your options before coming to a tracker and telling me you're bored and expecting a result. 

Thanks! :)

**Comment by Notawallplan** [comment]
"Boredom removal" was the best title I could come up with at the time.
Maybe changing it to "gripes about manual microcrafting" would be great.

Also, there is literally no indication that there is an alternative recipe
for leather once you create the first one. This issue was born from that
fact and that there should be something like "new recipes have been
unlocked" or something akin to that when you progress. Advancements don't
cut it since not all of them unlock recipes, though I would like to
congratulate darkasto for using a vanilla way to implement a quest line.

**Comment by Posivated** [comment]
This pack is clearly not for you if you can't take the time to make 1 single leather to get out of stage 0...

**Comment by Notawallplan** [comment]
https://www.youtube.com/watch?v=lyFSbm79uBY

Relevant.

**Comment by cheesealmighty** [comment]
@Notawallplan  If you're singleplayer, you could just add a recipe for both those steps, without the water bucket.

**Comment by vadis365** [comment]
Closing, because this is just clutter.
