### ISSUE TITLE
Every time i die and start messing with better with mods it keeps giving me the book over and over.

### ISSUE THREAD

**Issue by Spaz86** [Darkosto/SevTech-Ages#1036]
### Before anything else, use the *search* feature!
 * Maybe someone already reported the issue you're experiencing?
 * Maybe you can find the answer to your question by looking at older or closed issues?
 * Have a go at it and see!
 * Please search on the [issue track](../) before creating one.
 
## Steps to Reproduce (for bugs)

1.
2.

## Your Environment

* Modpack Version:
* Java Version:
* Launcher Used:
* Resourcepack Enabled?:
* Optifine Installed?:

**Comment by artdude543** [comment]
This should have been fixed in 3.0.3 are you on the latest version? (As I don't get the issue anymore) Also, the issues template does ask for this and filling this information in will speed up us being able to help you.

**Comment by artdude543** [comment]
Closing due to no updates and this was fixed a while back now.
