### ISSUE TITLE
Resonation Quest Completion

### ISSUE THREAD

**Issue by djnifos** [Darkosto/SevTech-Ages#1037]
## Issue / Bug
Can't complete the Resonation quest in Age 2.  I've made two via the regular crafting recipe, and one via the Astral table, using one of the previous resonating wands.  

* Modpack Version:3.03
* Java Version:161
* Launcher Used:Twitch-Jar
* Resourcepack Enabled?:Soartex
* Optifine Installed?:Yes

**Comment by Diltyrr** [comment]
Can confirm, same issue.

- Modpack Version: 3.0.3
- Java Version : 1.8.0.161
- Launcher Used : Twitch Jar
- Resourcepack Enabled ? : No
- Optifine Installed ? : No

**Comment by swestrup** [comment]
I'm having the same issue. I've even used the fosic resonator to find a good place to put a table. Is there anything else needed to complete the quest?
