### ISSUE TITLE
Waterwheel crash 3.0.3

### ISSUE THREAD

**Issue by steinjorn** [Darkosto/SevTech-Ages#1039]
Saw this was an issue that was supposedly fixed with patch 3.0.3, but my game just crash upon breaking a water wheel, Had no water under it.

**Comment by cheesealmighty** [comment]
#988 
It's fixed in dev, so it should be fixed in the next version. If you'd like a temporary fix, you could unlock the profile and update the "better with mods". Fixed the issue for me.

**Comment by steinjorn** [comment]
Well, ive tried putting it back and taking it down a few times now and cant recreate so gonna say it was a random crash and close this.
