### ISSUE TITLE
Cant revert properly to tutorial after using advancement grant everything command

### ISSUE THREAD

**Issue by VoxelVixen** [Darkosto/SevTech-Ages#1041]
Issue

We used the /advancement grant name everything command to get acces to all the material to make a spawn building on our server.
Now after using revoke everything , L shows we are in tutorial stage but we still see all the blocks in JEI and block names when looking at it.

packversion: 3.0.3
java: twitch launcher version
launcher: twitch app
resourcepack: none
optifine: yes

**Comment by scerion** [comment]
Fixed in stream :) 
Darko suggested the following for each player advancement granting was done to:

/advancement revoke name everything
/gamestages clear @p
/gamestages add @p tutorial

This will reset players back to the beginning like just starting  the pack again.

**Comment by VoxelVixen** [comment]
yep its cleared it for me, issue can be closed :)
