### ISSUE TITLE
Squid not spawning under normal conditions (confirmed not server vs singleplayer related)

### ISSUE THREAD

**Issue by Githubaccountlol** [Darkosto/SevTech-Ages#1045]
## Issue / Bug
Zero squid exist on server.  None.
/kill @e[type=squid] returns none in various regions.

Copying world from server to client instance and loading in client results in squid!

## Steps to Reproduce (for bugs)
Unknown.

## Context
Has occurred in more than one world.  My first world was affected by the server files not including server.properties and thus didn't have the correct worldgen type.  I thought this was likely the problem so I started completely fresh in 3.0.3 with the realistic gen from the start.  The new world produced sharks, which was new, but no squid.  Seeing your response to another person having squid troubles led be to believe that not finding any squid was due to not finding the right worldgen (despite the fact that both of my worlds have been 95% water), so I persisted.  Another day of play resulted in no squid found via command, ever.  Copied to client and loaded singleplayer produced squid around my home island immediately, so here we are.

## Your Environment
Separate client and server instances installed by MultiMC.  Server is vanilla MC instance -> manual forge install via forge installer -> pack's server file unzipped into the instance,   Same process for every pack I've played recently.  Server config is mostly unchanged.

I see that some people are clearly finding squid on multiplayer, so if this is due to something configurable and I screwed it up, I don't know what it is.

**Comment by Targren** [comment]
I actually had the same problem in single player on my first world.  Rolling a new world fixed the problem. Which isn't to suggest you should reroll your world, just that it doesn't seem to be a server-specific issue.

**Comment by Ragestrike** [comment]
I have this problem on my Server for the first day, we searched for miles, none. the next morning, i logged in, and there was tons and tons of squid everywhere, even in the small puddle i had in my base, you could try restarting the server or something.

**Comment by Githubaccountlol** [comment]
This is not an RNG issue.

Further testing today on a new world on server has revealed that squid CAN spawn, but are being blocked by the existence of other creatures, suggesting the mob caps are being taken up by other things which presumably spawn sooner and choke them out.

Behavior:

/kill @[type=squid] results in nothing.

/kill @e[type=!player] slays stuff.

/kill @e[type=squid] shortly after slays numerous squid!

further /kill @e[type=squid] return nothing, forever.

Repeating the cycle results in squid spawning to be slain after everything else is genocided, usually.

At one point I couldn't get ANY squid spawning at all after multiple attemps, but flying a couple chunks over allowed the process to spawn squid again.  Don't know what that was about, but ignoring it for now.  I mention it in case someone else has squid not spawn after killing entities as well.


To summarize: it's not the worlds, or the biomes (my worlds are 95% water, which I assume is intentional), or even the multiplayer/singleplayer gap as I was led to believe earlier.  It's likely the spawning behavior and interaction with other entities.

I can't postulate as to why they spawn successfully after a full genocide, but have trouble succeeding during routine exploration, which should, in theory, emulate the death of old entities which are no longer loaded.  Actually, I'll take a shot at it: a kill command wipes the entire slate clean, whereas piecemeal removal of existing entities through wandering may result in entities sustaining numbers at or in excess of any limits, preventing those with less priority from getting a chance.  This would likely enable different results among people with varying terrain and view distances: smaller or larger numbers of chunks activating at a time may be beneficial or detrimental to your chances of seeing lesser priority creatures.  I also don't know how many of these entities are saved to the world (guessing most), meaning only NEW chunks explored under favorable conditions would have a chance of success.  Someone like me who tends to running a circuit of familiar locations when searching for supposedly random spawns would never succeed under this scenario.

Anyway, no reason to treat the symptom as a part of intended results.  Squid technically CAN spawn in these locations, precluding the "it's luck" excuse, but in practice they are not being allowed to spawn unless the world is genocided.  I checked often during a day's course of play.  Zero hits on squid in normal play.

**Comment by Githubaccountlol** [comment]
More testing results: starting server with test world: genocide method spawns squid repeatedly (/kill @e[type=!squid,rm=2] works great), but eventually stops working when moving to new areas.  Returning to original location still resulted in no squid spawns at all.  Restarting server allowed method to spawn squid once again.  Further testing in progress.

**Comment by Targren** [comment]
Hey, @Githubaccountlol , since you seem to be able to fairly reliably reproduce the problem, would you consider testing a hunch for me? Instead of genociding every entity in the world, just try cod/salmon?  

I got the idea from using LagGoggles to try and nail down a slowdown and noticed that there were hundreds of fish bogging me down. I thought it might be connected.

**Comment by Githubaccountlol** [comment]
I wanted to, but I don't have a way to kill off a specific subset of critters in one go.  Vanilla commands can kill one thing, or everything BUT one thing, but not lists of things, and respawns happen too fast.  I could try emulating it by just using the coordinates of a water region, but squid weren't continuing to spawn after full genocides for very long, so I would constantly be under the specter of false negatives.  I did kill off cod in my live server and didn't get anything.

The fact that the devs aren't taking this seriously and would rather mock me with dumb tags makes me not very interested in putting forth any more effort.  I have shown beyond any doubt that there is a problem, and there have still been ZERO squid in my live environment, despite showing that these areas are perfectly capable of spawning squid, in the same world.  What do I get? A mocking meme-face and silence.

**Comment by Targren** [comment]
Thanks for trying. If I ever have the problem manifest on my end, the first thing I'll try is disabling JAFF.  I'd hate to lose spear-fishing, but hate to lose squid even more. :D

**Comment by justinrusso** [comment]
Convinced this isnt an issue, but we're adding changes anyways.

This should be in for 3.0.5.
