### ISSUE TITLE
Mobs will stop spawning after a bit of time

### ISSUE THREAD

**Issue by leggm97** [Darkosto/SevTech-Ages#1047]
Issue / Bug:
Mobs will occasionally stop spawning. I have noticed this whenever I have been playing for a bit.
Possible Solution:
Could be an issue with having 6GB of RAM allocated and it using ALL of it. Reloading the world will cause them to spawn again
Steps to Reproduce (for bugs):
Just play the game for a bit and more and more mobs will stop spawning and after that, reload the world and they will spawn again.

Your Environment
Modpack Version: 3.0.3
Java Version: Java 8 Ver 161
RAM: 6GB Allocated (6372MB)
Launcher Used: Twitch/Vanilla
Resourcepack Enabled?: Vanilla
Optifine Installed?: Nope

**Comment by artdude543** [comment]
If this is still an issue in the latest version of the pack can you re-open the issue? Alternative you can enter the hunting dimension to get a tonne of mobs to kill if you're after them.
