### ISSUE TITLE
Orb from Blood Magic problem

### ISSUE THREAD

**Issue by tapegreen** [Darkosto/SevTech-Ages#1051]
The Incense altar requires an in-registered orb to use. What I'm saying is that once I made the orb "Mine" it won't allow me to craft objects that use it, instead I had to make a new orb and use that one.

**Comment by lawl281** [comment]
What version are you on and did you try manually dropping items in crafting grid?  You have never been able to shift-click a recipe into grid from JEI with a claimed orb.  The recipe worked fine for me in 3.0.1 and I just tested in 3.0.3.

**Comment by tapegreen** [comment]
That's strange as I am running the latest version and I still couldn't make the incense altar with a claimed orb. I even tried the apprentice orb and still no luck. I am not Shift-clicking the recipes in and I tried manual, still no luck.

**Comment by 3jlowes** [comment]
I crafted incense altar just fine. orb registered to me

**Comment by artdude543** [comment]
Yep, confirmed that that recipe is working and registering is fine. Going to assume user error on this one.
