### ISSUE TITLE
Rock crystal ore is impossibly rare. v3.0.3

### ISSUE THREAD

**Issue by Ambaire** [Darkosto/SevTech-Ages#1053]
## Issue / Bug
Rock crystal ore is impossibly rare to the point of nonexistent.

## Current Behavior
After a few hours of pointless random searching for rock crystal samples (early age 2), I started messing around with /oredistribution 256 0 128 and ended up covering roughly a 1500 by 1000 block area. Didn't see a single rock crystal ore, but I saw lots of stuff like platinum and uranium ore.

## Possible Solution
Maybe make rock crystal ore spawn slightly more frequently and/or let the vanilla method of looking for particles in the ocean at night still work?

## Context
I think I'm done with this pack. It was an interesting experience to begin with, but after two ages of "oh hey, random plain rocks are now new ore samples", exploring previously explored areas for this purpose has been getting really tiring / old.

**Comment by Ambaire** [comment]
And I say this in the context of someone who stuck with Per Fabrica Ad Astra (terrafirmacraft with tech and space travel) long enough to get a steam turbine going and in the process traveling tens of thousands of blocks to find the right rock type for ore spawns or biome for horses/cows/etc.
Not doing that kind of exploration again.

**Comment by cheesealmighty** [comment]
#1026 From what I gathered, something off is going on with the ore generation currently.  I feel the same thing with you, and I come from the same place. Copper, tin and coal seems to be working alright for me, but rest of the ores seem to be almost nonexistent(unless I'm doing something terribly wrong). Also, coralium. Coralium is everywhere.

**Comment by Dystilled** [comment]
Yep, 6 hrs of combing a huge chunk area and I havent found a single Rock Crystal Sample.

**Comment by Electrofried** [comment]
/oredistribution will not work with certain ores, notably gold and rock crystal ore. You can be standing beside an ore vein and run the command and it will not show up. 

![fc734cfd1cdcb1ebbba58fba373a862a](https://user-images.githubusercontent.com/27886155/38086036-4334cff0-3396-11e8-851d-16dc2d81e904.png)
that is gold ore in the background, but I tested with rock crystal ore also.
 
And yes this is probably related to the same issue that all ore gen is having. You will just have to wait a day or so more till the next update comes out as this is being worked on currently.

**Comment by Darkosto** [comment]
I spent many hours yesterday with the developer of the ore generation mod and we've discovered some strange generation issues. The percentages are not quite where they need to be, especially ones that are at the lower of the threshold. I'm going to wrap up my testing to day and get something with more ore.

Basically, out of 5,000 chunks generated 337 ore veins generated. Then the ores were distributed among that. What's I'm looking to do is up that number to around 700. You'll see double the ore veins and more chance for the ones you're specifically looking for.

I will most likely have this available for 3.0.4.

**Comment by cheesealmighty** [comment]
I've discovered something else, just now. I'm currently in stage 2, and the "./oredistribution 1" shows about 50-100 blocks of hematite around me. Dug around the chunk for half and hour or so, nada. I tried blasting what seemed to be just stone with TNT, and the number of hematite just dropped by 50, suddenly. Is it possible the trigger is not working, somehow? (Maybe I should've opened a new ticket for this?)

**Comment by cheesealmighty** [comment]
@Ambaire  If you're in a singleplayer world, you could change it (I did). It looks... Eh. A bit too obvious. But with the damn sharks prowling around and the ocean being quite deep, it's still a challenge. And ore patches have 100-200 blocks in between them, so it's not that much of a ballpark.

Yeah, I'm a bit disappointed by the prospecting _thing_ as well. I'm guessing it was added because it's quite configurable for which ore to detect and inform the player of. Even after boosting its range to 128, the dimensions of it really make it a rudimentary tool at best. Although I did see Scannable mod in the list, I think it's supposed to replace the damn dowsing rod in the late game.

**Comment by DerpityDoo** [comment]
Sooooo will we get some sort of retro-gen? I already have a 5,000 block square very thoroughly explored, and a 10,000 block square randomly explored, and I don't want to have to go much further, as it just becomes an inconvenience. Still, haven't found rock crystal ore even with the hours spent looking for samples *:(

**Comment by Electrofried** [comment]
if you identify the region that contains your base, you can simply delete the other regions and re-explore them again. Darko has confirmed there will be no retrogen and you will have to regen manually as I described or generate new chunks.

**Comment by Tommassino** [comment]
Beware, rock sample does not show up on /oredistribution

![image](https://user-images.githubusercontent.com/698950/38174679-733a706e-35d1-11e8-9cc8-5ddc74915186.png)

**Comment by Darkosto** [comment]
Ore Veins have been increased to 750-850 on average per 5k chunks. This should double every vein (since the ratios of ore types were not altered too drastically). This should, in theory, allow you to find particular ore much more easily. Remember, RNG will always play a factor. I've added all the rare ore types to the betweenlands, too. Meaning, if you want to find diamond, emerald, rock crystal, etc. without having to see other ore types you can head to that dimension if you choose. 

And correct, that ore distribution chart isn't 100% accurate.

**Comment by Tommassino** [comment]
Im still not sure what is actually on the /oredistribution, i find a chunk in which it says coal, but there are rocks everywhere, no samples, so it cant be coal. Then there is way too much hematite overall. It has 5% spawn rate, but usually its in a 100 radius oredistribution, so there must be quite a lot of ores that the command assigns incorrect names.

**Comment by Darkosto** [comment]
@Tommassino Are you running that command with coal hidden behind a stage? 

Anyways, I've gotten confirmations the ore is much easier to find and we should be good.
