### ISSUE TITLE
[issue] BWM Kiln not working

### ISSUE THREAD

**Issue by jaredtrask41** [Darkosto/SevTech-Ages#1055]
## Issue / Bug
https://i.imgur.com/jzvFr0r.png

It seems to not be working properly.
It's not just the soul urn, happens to the crucible as well.

## Your Environment

* Modpack Version: 3.0.3
* Java Version: 1.8.0_161 64bit
* Launcher Used: twitch
* Resourcepack Enabled?: yes soartex
* Optifine Installed?: yes

**Comment by DaedalusGame** [comment]
need to stoke the fire with bellows

**Comment by Darkosto** [comment]
Yes, as @DaedalusGame just mentioned. You need to stoke the fire. Make sure to consult BWM information to make sure you're correctly using some of the block :)

**Comment by youngclout** [comment]
how to do you make the kiln to fire up my unfired crucible?
