### ISSUE TITLE
not getting credit for space suit accomplishment

### ISSUE THREAD

**Issue by Saereth** [Darkosto/SevTech-Ages#1056]
## Issue / Bug

https://imgur.com/a/xlBvR

## Current Behavior

crafting/equipping the tier 1 space suit only gives 1/5 on the advacement

## Possible Solution

I suppose I could grant myself the advancement

## Steps to Reproduce (for bugs)

1. Make space suit
2. Fail to profit

## Your Environment

* Modpack Version: 3.0.3
* Java Version:
* Launcher Used: Twitch
* Resourcepack Enabled?: no
* Optifine Installed?: no

**Comment by artdude543** [comment]
All the space suit parts need of been in your main inventory for the advancement to trigger. I've tested this now it's working as intended.

```
//Criteria
criteria1 = addCriteria("hasRock1", "minecraft:inventory_changed")
criteria1.setItem("extraplanets:tier1_space_suit_helmet")

criteria2 = addCriteria("hasRock2", "minecraft:inventory_changed")
criteria2.setItem("extraplanets:tier1_space_suit_chest")

criteria3 = addCriteria("hasRock3", "minecraft:inventory_changed")
criteria3.setItem("extraplanets:tier1_space_suit_legings")

criteria4 = addCriteria("hasRock4", "minecraft:inventory_changed")
criteria4.setItem("extraplanets:tier1_space_suit_boots")
```
