### ISSUE TITLE
Tough dowsing rod is not picking up magnetite ore? 

### ISSUE THREAD

**Issue by cheesealmighty** [Darkosto/SevTech-Ages#1057]
## Issue / Bug
I'm currently in stage 2, found an exposed vein of magnetite. After right clicking on it with tough dowsing rod, it did not "see" the ore. Tried right clicking after putting a block over and around it, to check if it only didn't work when right clicked directly on the ore block itself, still nothing. Is this intended behavior? If not, it would explain why I can't seem to find the ores. 

## Your Environment

* Modpack Version: 3.0.3
* Java Version: Ver8. build 161
* Launcher Used: Twitch
* Resourcepack Enabled?: None
* Optifine Installed?: No

**Comment by cheesealmighty** [comment]
Just realized it's not equivalent to iron in this modpack.

**Comment by Darkosto** [comment]
Ehh, it should have been turned off. Not sure why it's on. I'll make sure it is off from now on. Thanks for the report!
