### ISSUE TITLE
Cannot make fuel

### ISSUE THREAD

**Issue by Saereth** [Darkosto/SevTech-Ages#1059]
### Before anything else, use the *search* feature!
 * Maybe someone already reported the issue you're experiencing?
 * Maybe you can find the answer to your question by looking at older or closed issues?
 * Have a go at it and see!
 * Please search on the [issue track](../) before creating one.
 
## Issue / Bug

I'm as far as I can seem to progress in age four but I am stuck behind fuel for the rocket. The GC refinery is disabled, not shown in jei/no recipe, the other fuel I could make it a combination of kerosene from Pnumaticraft and mekanism liquid oxygen in the IE refinery, they oxygen I assume is interchangeable with gc oxygen so no problem there but jei show no method of creating the kerosene. Previously with Pneumaticraft you'd use their refinery which is also unavaialble in jei.
https://imgur.com/a/egpKX

 I do see it has a buy order on the amadron was this supposed to be a sell order?
![image](https://user-images.githubusercontent.com/9200909/38091220-e3dba2e4-3332-11e8-82e9-ebb163479ac2.png)

## Steps to Reproduce (for bugs)

1.
2.

## Your Environment

* Modpack Version: 3.0.3
* Java Version:
* Launcher Used: twitch
* Resourcepack Enabled?: no
* Optifine Installed?: no

**Comment by Darkosto** [comment]
Showing the recipe for Galacticraft Fuel brings up how to make it:

![image](https://user-images.githubusercontent.com/10309699/38117962-e5777e5e-3385-11e8-8333-0540ac18de86.png)

You're already producing Diesel, you need to distill it into Kerosone

![image](https://user-images.githubusercontent.com/10309699/38117966-f01a98dc-3385-11e8-8361-3cdd94181fc4.png)

**Comment by Saereth** [comment]
oh weird ok I guess JEI just isnt showing the kerosone production, will give that a shot

**Comment by Darkosto** [comment]
I've gone ahead and added an advancement to let the player know what's up and how to get those liquids.
