### ISSUE TITLE
Excavator Modifier not ore dict'd to accept asCrystals (only Rock Crystal)

### ISSUE THREAD

**Issue by Vyraal1** [Darkosto/SevTech-Ages#1061]
## Current Behavior
- Excavator Modifier for Tinkers Tools only accepts rock crystals and isn't ore dictionaried to asCrystal, as is the theme with all other recipes that currently use rock crystals

## Context
![image](https://user-images.githubusercontent.com/26587049/38096287-7f13b23a-3340-11e8-89e3-4a0867b4cc8b.png)

## Your Environment
* Modpack Version: 3.03

**Comment by justinrusso** [comment]
@Darkosto Not sure if this was an intended decision
