### ISSUE TITLE
Hematite is invisible in stage 2.

### ISSUE THREAD

**Issue by cheesealmighty** [Darkosto/SevTech-Ages#1062]
## Issue / Bug
I couldn't find any hematite for the longest time, and I was testing around with oredistribution command. And found out 50-100 blocks of it spawned with ./oredistribution 1 near me. I dug around, with no success. I tried blasting off what seemed to be just stone with TNT, and suddenly it dropped by 50 blocks. I've also tested by just breaking the blocks, and it seems to be invisible indeed.

## Current Behavior
Video proof (starts after 22nd second): https://puu.sh/zRZFB/6673bf7a86.mp4

## Your Environment

* Modpack Version: 3.0.3
* Java Version: V8-b161
* Launcher Used: Twitch
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by Darkosto** [comment]
I'm in a world looking at Hematite Ore and it's sample with no issues. I'm not really sure what's going on in your world. When did you create your world (what version of the pack?)? Also what OS are you running?

**Comment by cheesealmighty** [comment]
The day pack was released, I think it was 3.0.0? Windows. 

I would also like to point out that, I was able to place down an hematite ore in creative. And it was quite visible indeed. So I have no idea what's going on either. I could cheat in iron clusters, was able to melt and use it. Again, no clue.

**Comment by cheesealmighty** [comment]
Let me try a clean modpack install and try again in the same world. (If I can find the same damn chunk again)

**Comment by Darkosto** [comment]
I think with 3.0.0 a weird issue caused ore issues like you had. Fresh worlds would fix it. Also, you SHOULD be able to update with your current world (make sure to delete all scripts/config folders so they are definitely the newer versions). Then, new chunks should have hematite. 

This is all speculation though. Let me know what you find out.

**Comment by ArbitraryHubris** [comment]
I have found hematite in new chunks on a world created on version 3.0.1.  Found samples and the ore below.

**Comment by cheesealmighty** [comment]
Pruning in mcedit doesn't seem to work. I guess it **has** to be a new chunk.

**Comment by cheesealmighty** [comment]
Found the issue, what ./oredistribution marks as "Hematite" is actually limonite. I've found this out after disabling orestaging.
