### ISSUE TITLE
Unbreaking table *cheat*

### ISSUE THREAD

**Issue by Gremilcar** [Darkosto/SevTech-Ages#1063]
## Issue / Bug

The unbreaking table allows the player to completely bypass nether brick advancement chain at least

## Current Behavior

https://gyazo.com/448e18a7aca55d4bc72d62685b9e7396

## Possible Solution

v0v

## Steps to Reproduce (for bugs)

Make the Uncrafting table
Put in Nether brick block
???
Profit (receive 4 nether bricks)

## Your Environment
* Modpack Version: 3.0.3

**Comment by Darkosto** [comment]
Got this fixed up in dev, thanks!

**Comment by Gremilcar** [comment]
The new recipe in 3.0.4 requires 4 nether bricks....which are still found in large quantities at nether fortresses. 

the current fix doesn't fix anything.

**Comment by artdude543** [comment]
This was fixed and changed to the following :)

![image](https://user-images.githubusercontent.com/1885466/38466958-32cddcf2-3b29-11e8-88c9-6000c649f567.png)
