### ISSUE TITLE
Advancements and JEI bugged

### ISSUE THREAD

**Issue by flyingwaffle101** [Darkosto/SevTech-Ages#1067]
My game crashed along with the server now my JEI only shows mechanism liquids and wont let me go tutorial advancements. I've tried updating to 3.0.3 and my together forever mod but nothing is working. If I go onto another world however it works. Also unrelated but my items disappeared when the world crashed too but I'd rather fix the bigger issue.

**Comment by artdude543** [comment]
This is an old issue, and a lot has changed in regards to some of the major mods at play here. So if the issue is still happening on 3.0.6 please re-log the issue and follow the issue template.
