### ISSUE TITLE
Squid do not spawn in singleplayer

### ISSUE THREAD

**Issue by rage487** [Darkosto/SevTech-Ages#1068]
Squid/Shark are not spawning in my world. I only get Piranhas and other small fish no matter what time of day, difficulty setting, or biome I am in. 

I have not progressed very far, but I have still put in several hours of playtime and I cannot create water bladders because I cannot find squid to get ink sacs from. I'm not sure if there is a downside to sharks not spawning, but if there is, I'm sure I will eventually run into that problem as well. 

I have re-created my world multiple times using the button in the world selection menu and I get multiple shark/squid spawns along with all the other regular fish spawns in the water around my spawn point instantly. This is an exact copy of my original world using the exact same seed, but I can't just switch worlds because I would lose all my current progress. 

As a temporary fix, I had to revert my pack back to 3.0.1 so that I could create an ink sac from grinding a black lotus, but I would like to be able to update my pack to the latest version and I would also like to not have to restart my entire world if possible. 

Before I downgraded my pack version, I was using version 3.0.3. I am now using 3.0.1 and am still having the same issue. I am using Java 1.8.0.161 64bit with the Jar launcher using the Twitch app. I am using the Soartex Fanver - Modded resource pack with the Sildur's Vibrant Shaders v1.163 Lite shaderpack. I am also using Optifine 1.12.2 HD U D1.

**Comment by Sydonell** [comment]
I actually had the same issue, also only effecting the first world made on the pack. Starting a new one fixed it.

No shaders or resource packs on mine, just the pack as downloaded from the Twitch launcher.

**Comment by crocman** [comment]
Also having the same issues, spent 3 hours looking for squid and nothing

**Comment by PandaPaw** [comment]
Same here, 2h looking for squid and nothing. 
Pack Version: 3,0,3

**Comment by SuohKami** [comment]
Although rare, I get squids. No sharks or piranha here though, my waters are safe. Tons of little fish though.

**Comment by LordZardeck** [comment]
Same here, no squids, can't progress. v3.0.3

**Comment by Synliss** [comment]
I was also having the same problem. But it seems to have worked when I got into a raft and moved around on water resetting the entities in the world. Lots of little fish and the like. The squid population exploded.

**Comment by Deamun** [comment]
I have been having the same problem for a few hours now, generating a new world seems to result in squid spawns (didn't check sharks) but this did force me to review vanilla squid spawning mechanics. Perhaps squid aren't spawning because the oceans are too deep? If the spawn block is less than y46 they just can't spawn. Do the fish from JAFF count towards water mob cap?

**Comment by ryankhart** [comment]
I can't find any squid either, and seemingly right after I found a cartographer villager who wants ink for a trade.

**Comment by justinrusso** [comment]
Convinced this isnt an issue, but we're adding changes anyways.

#1045

**Comment by ryankhart** [comment]
Turns out that this isn't an issue after all with the existence of the Survivalist's Strainer. You can get ink sacs from that instead of killing squid. I noticed that in the latest update, crafting a strainer was added to the advancements page in Age 0.
