### ISSUE TITLE
iron item pipes can be made in age two

### ISSUE THREAD

**Issue by OranHexthief** [Darkosto/SevTech-Ages#1069]
### Before anything else, use the *search* feature!
 * Maybe someone already reported the issue you're experiencing?
 * Maybe you can find the answer to your question by looking at older or closed issues?
 * Have a go at it and see!
 * Please search on the [issue track](../) before creating one.
 
## Issue / Bug
the colored iron item pipes from BC are not in NEI but if you look in the recipes using iron you can find the colored pipe recipe there and it can be made in age 2. unsure if this was intentional

## Steps to Reproduce (for bugs)

1.
2.

## Your Environment

* Modpack Version:
* Java Version:
* Launcher Used:
* Resourcepack Enabled?:
* Optifine Installed?:

**Comment by Darkosto** [comment]
Should all be staged properly in 3.0.4
