### ISSUE TITLE
Piranha through slabs

### ISSUE THREAD

**Issue by TheLemein** [Darkosto/SevTech-Ages#107]
Could be as intended, but when using slabs, to build a bridge, to get across water for example, if the slab is the lower half of a normal block, but on top of the water (floating but not disturbing), piranhas will still attack you through the slab.

**Comment by Darkosto** [comment]
Yep! They do! Right, Vadis? xD

**Comment by vadis365** [comment]
sure - will take a look - should be simple enough to fixy

**Comment by Darkosto** [comment]
Should be good now, let me know if it still happens.
