### ISSUE TITLE
Take a look at Mulberry tree rarity

### ISSUE THREAD

**Issue by Darkosto** [Darkosto/SevTech-Ages#1070]

**Comment by Ozzymud** [comment]
Was beginning to think is was just me after following the JEI tip that they rarely spawn in most biomes. Been out 1000 in each direction and nothing. I did however read the manual for Better with Addons, it says you can only obtain them from the Ancestral Infuser(stage 3). Anyhow, thought I'd comment here.

**Comment by royalcw** [comment]
I've been over 2000 in every direction in SevTech Ages and havn't found one yet.  I've had my friends search on their characters too.  We are all stuck on the Mulberry wood quest step.  Mulberry is rare...non-existant.
