### ISSUE TITLE
[Suggestion]JourneyMap Token needs too many charms of keeping

### ISSUE THREAD

**Issue by AmishInvader** [Darkosto/SevTech-Ages#1071]
The JourneyMap Token in Age 2 requires 32 charm of keeping 1s.  I barely had half of that after completing the entire Twilight.  I would suggest lowering it by half or requiring charm of keeping 2s instead of 3s.

**Comment by Darkosto** [comment]
This quest opens up Journey Map early. If you do not want to do, you do not have to. It unlocks for free in stage 4.

If you notice, the "main quest" advancements are shown differently in the advancement window.

I will add more notification to the side quests to allow the player more visibility on what is optional.

**Comment by AmishInvader** [comment]
Didn't know it unlocked for free at age 4, thanks.

**Comment by Darkosto** [comment]
Information was added to tooltip in 3.0.4, should be much clearer now.
