### ISSUE TITLE
Don't have permission of opening a chest in age 1

### ISSUE THREAD

**Issue by PrinceChaotic** [Darkosto/SevTech-Ages#1072]
I'm currently playing on a server, and just got to age 1. When I made the chest and placed it down, it says I don't have permission to open the chest. I've tired re-logging and still didn't work. In singleplayer its fine, Do you think its a server bug or the mod itself?

**Comment by DingoX3** [comment]
Is it possible that the server your on has some kind of protections? If so i would ask a server admin to look at your issue. Is it saying you dont have the right stage to access it or is it just saying you dont have permission to access this chest. If its the later then its a server issue.

**Comment by artdude543** [comment]
Nothing in the pack adds this functionality this is server side. Or you have "modded" pack.
