### ISSUE TITLE
when mining blocks, the target block 'flashes' different states.

### ISSUE THREAD

**Issue by SteseDav** [Darkosto/SevTech-Ages#1073]
### Before anything else, use the *search* feature!
not sure how to describe the nature of the bug. Searched for 'Mining' & 'Flashing'
 
## Issue / Bug
When mining a block (tree leaves, or dirt so far), the block flashes through different states, rather than showing the 'breaking' images as normal

https://youtu.be/FApChyWLJWI

## Current Behavior
as above

## Possible Solution
no idea...

## Steps to Reproduce (for bugs)
Mine a block at tutorial

## Context
just doing normal mining actions... nothing special

## Your Environment

* Modpack Version: 3.0.3
* Java Version: 1.8.0_161
* Launcher Used: Twitch
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by Darkosto** [comment]
Correct, that is why the pack has a window telling you once you change resource packs to restart your client.
