### ISSUE TITLE
[Staging] Blood Magic Stage 1

### ISSUE THREAD

**Issue by iffonox** [Darkosto/SevTech-Ages#1075]
I noticed a few staging inconsistencies with Blood Magic:

* The Elemental Inscription Tool: Dusk is currently staged in stage one, but requires a tier 4 Blood Altar, which isn't available until later.

* The Efficency Rune shows up in JEI in stage one, but doesn't have a recipe

~~The Lesser Tataric Gem isn't marked as unfamiliar item, but doens't show up in JEI and isn't craftable (#1128 is probably the cause)~~ (fixed in 3.0.4)

~~If the Lesser Tataric Gem isn't supposed to be craftable in stage one, then the Sigils of the Green Grove, Blood Lamp, Elasticity and Winter's Breath and their reagents should be moved to a later stage, as the Petty Tataric Gem can't hold enough will to craft them. (sorry for the torturous sentence)~~ (fixed in 3.0.4)

SevTech Version: 3.0.4

(Updated the issue to reflect the changes in 3.0.4 )

**Comment by artdude543** [comment]
- Efficency Rune does not have a recipe as of yet in the mod due to not being finished. So once it's enabled again it will have a recipe. We are going to hide it from JEI for the time being.
