### ISSUE TITLE
Filling Clay buckets causes the client to crash version: 3.0.3 

### ISSUE THREAD

**Issue by beng934** [Darkosto/SevTech-Ages#1076]
As soon as you fill up clay buckets and then for some reason when you turn around it causes a crash, this has happened to 3 of my friends who did the exact same thing. 

Please can someone look into this for next patch?

**Comment by beng934** [comment]
As in, when you fill it up with water and you turn around 180 degrees the game crashes.

**Comment by beng934** [comment]
The game crashed whilst unexpected error
The game crashed whilst unexpected error
Error: java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=axis, clazz=class net.minecraft.util.EnumFacing$Axis, values=[x, y, z]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}

**Comment by beng934** [comment]
This is the log, we tried a few things. the main source of why it is crashing is the water wheel. It crashes when you go to fill buckets up whilst the waterwheel is working. We then destroyed the waterwheel and filled the buckets up from a river and it didn't crash. I then tried plugging the waterwheel back in and yet again it has crashed.

**Comment by cheesealmighty** [comment]
@beng934  Please go to the game folder, open crash-reports folder, then open the latest text file. Then copy everything in it to here: [https://paste.ubuntu.com/](url) 
Then copy the link here.

But it seems like the waterwheel bug due to better with mods. It's fixed in the new version of better with mods, which -I assume- will be included with the next version of the modpack.

**Comment by beng934** [comment]
The link is not working sorry

**Comment by beng934** [comment]
https://paste.ubuntu.com/p/b6n7p8kfpP/

**Comment by liquidsystem** [comment]
This is a problem with the water wheel from "Better with Mods", my friend and I have reported this issue, it is unrelated to getting milk it appears from your crash-log. Here is the issue thread for it: #1104

**Comment by justinrusso** [comment]
https://github.com/Darkosto/SevTech-Ages/issues/988
