### ISSUE TITLE
Work stump can't place items

### ISSUE THREAD

**Issue by ErdanThren** [Darkosto/SevTech-Ages#1080]
Bug

When playing on a lan server, the connected player cannot place items on a work stump

Current behaviour

the correct noise that accompanies items being placed is heard but nothing is placed on the crafting grid

possible solution

unknown

Environment

* Modpack Version: 3.0.2
* Java Version: 1.8.0_161-b12
* Launcher Used: Twitch
* Resourcepack Enabled?: no
* Optifine Installed?: no

**Comment by OriginalSuperGumby** [comment]
Had a similar issue. Somehow an invisible block was placed on top of my table. I caught sight of the edges depending on my position relative to the table. I used a pick axe on the 'space' above the table. Heard the sound of a block breaking and then I could place items again.

**Comment by vadis365** [comment]
I have no idea what is causing this and it's a rare thing by the sounds of it - could be due to other mod's interactions or could be a specific lan issue that I can't find or fix.
Closing due to the age of the pack version being outdated and newer versions may not have the issue anymore.
