### ISSUE TITLE
Coal spawning in Y23

### ISSUE THREAD

**Issue by mylbp2ps3** [Darkosto/SevTech-Ages#1082]
Found coal around Y23.
https://i.imgur.com/8723Pa9.png

Custom mods I've installed are just cosmetic mods like a sound mod, better sky etc. I installed these mods after world gen too.

**Comment by Darkosto** [comment]
What version of the pack are you playing?

**Comment by mylbp2ps3** [comment]
Version 3.0.3. Found Copper now, and it is in the correct Y range

**Comment by DerpityDoo** [comment]
If the chunk was generated before 3.03 then the coal would still be in the old Y range which is like Y8

**Comment by mylbp2ps3** [comment]
Aaah okay. That makes sense.
