### ISSUE TITLE
Game crashing on instillation. 

### ISSUE THREAD

**Issue by amatyi** [Darkosto/SevTech-Ages#1083]
Mod pack v. 3.0.3 keeps crashing when loading in. It hits 3/7 on the bar right below Mojang and then crashes. It won't load a bug report but this is all that I can see.

The game crashed whilst initializing game
The game crashed whilst initializing game
Error: com.google.common.util.concurrent.ExecutionError: java.lang.OutOfMemoryError: GC overhead limit exceeded

**Comment by Darkosto** [comment]
That log actually tells you why it's crashing. You're running out of memory (RAM). Increase the amount of RAM you dedicate to the pack and load again.

**Comment by hunting97** [comment]
How much ram should I allocate

**Comment by amatyi** [comment]
I did 4g and it runs great now!
