### ISSUE TITLE
Wild Dogs - No Wolf Drops

### ISSUE THREAD

**Issue by Targren** [Darkosto/SevTech-Ages#1086]
Similar to #153: 

No meat, pelts, etc.. drop from Wild Dogs, though their behavior is slightly different so they may not be considered to be "wolves" at all; if that's the case, feel free to ignore. :)

**Comment by Ambaire** [comment]
Can confirm. I know there's a recipe that uses 4 wild dog pelts and I've never seen a wild dog pelt drop. Never thought to bug report it.

**Comment by vadis365** [comment]
Pelts do drop, albeit not every time. Wild dogs are not wolves.

**Comment by Targren** [comment]
Yep. Go and make a liar out of me. After killing a few dozen of those annoying SOBs, number "a few dozen plus two" drops a pelt.
