### ISSUE TITLE
skeletons spawn with a bow on act 0

### ISSUE THREAD

**Issue by Thill199** [Darkosto/SevTech-Ages#1087]
had a spider jockey spawn and skeleton had a a bow

**Comment by justinrusso** [comment]
🤔 I wonder what the mob  is in these situations....

**Comment by vadis365** [comment]
Spiders call the code to spawn Jockeys in their onInitialSpawn method, you would need to prevent them from spawning the vanilla skeles and replace them with the doots. There is no hook in the code to replace the mob directly as it's hardcoded by vanilla to be a skele.  You could also make an event that when a vanilla spider is spawned in age 0 and it has a riding skele, the skele is removed from the spider and a doot is spawned and set to be the rider. Don't know if the doot's mod maker would want to do this - I mean it's easy to do, and I don't think it warrants yet another mod being made for the pack.

**Comment by justinrusso** [comment]
got it, so its not another mob, but the skele mob is being spawned differently so it breaks Buuz's code that lets us modify the armor.

**Comment by vadis365** [comment]
It's not hard to implement at all. Does this need doing external or do you want to ask the doot's dev?

**Comment by justinrusso** [comment]
I'd like to see if @Buuz135 can add support before anything. We his armoreable mod to handle armor and weapons on mobs in each stage. We're fine with bows existing, just not in stage 0.

**Comment by justinrusso** [comment]
This is fixed in https://minecraft.curseforge.com/projects/armoreablemobs/files/2546621 @Darkosto

**Comment by Buuz135** [comment]
![eyes_1f440](https://user-images.githubusercontent.com/3874674/38222014-cbd639d0-36e2-11e8-83c8-2a6a4e1a4913.png)

**Comment by justinrusso** [comment]
Updated

Will be in 3.0.5
