### ISSUE TITLE
Cooking Barley Flour on Fire Pit yields Barley.

### ISSUE THREAD

**Issue by BurgerLord** [Darkosto/SevTech-Ages#109]
When I was playing the alpha 2 version of SevTech I ground up some barley that I found in the wild on a grindstone from Horse Power, once I got the barley I cooked it on a fire pit from Primal Tech and it yielded the barley that I started with. This happens every time I do this. (btw this is Diddles25 from Twitch).

**Comment by Darkosto** [comment]
Should be all fixed up! Thanks!
