### ISSUE TITLE
/help 11 causing crash to menu

### ISSUE THREAD

**Issue by james3126** [Darkosto/SevTech-Ages#1090]
THIS MAY BE WHILE USING SERVER ONLY. _Untested on single player._

When typing `/help 11` , a crash to game menu will happen. This is consistent and will happen every time.

**Steps to reproduce:**
In a game. Type `/help 11` and press enter.

**Error produced:**
`Internal Exception: io.netty.handler.codec.DecoderException: com.google.gson.JsonParseException: Don't know how to turn {"clickEvent":{"action":"suggest_command","value":"/vtt"}} into a Component`

**Screenshot of error:**
https://jamdrive.jammyworld.com/dl.php?file=DLh-oILNkiMd1LIG3fu4ogY7KcYx7yEs

* Modpack Version: 3.0.3
* Java Version: Java 8
* Launcher Used: Twitch
* Resourcepack Enabled?: Yes, Soartex Fanver
* Optifine Installed?: Yes

**Comment by Aedda** [comment]
Can probably be resolved by installing HelpFixer on the server and clients. Would recommend adding it to the pack for future benefit.

**Comment by artdude543** [comment]
We will install HelpFixer and try to find the mod at fault to resolve the issue. But as it's not pack breaking I'm going to close the issue.
