### ISSUE TITLE
Weak dowsing rod not registering on Aquamarine ore.

### ISSUE THREAD

**Issue by TrisanaShadows** [Darkosto/SevTech-Ages#1091]
(Similar to #714)
![2018-03-30_15 23 55](https://user-images.githubusercontent.com/17152787/38121998-005bf516-342f-11e8-89bb-a573a0878e45.png)
Should the weak dowsing rod be displaying data about the ContentTweaker aquamarine ore, as it is a a Stage One Ore?
Modpack Version: 3.0.3
Launcher Used: Twitch Launcher
Resourcepack Enabled?: Soartex Fanver
Optifine Installed?: Yes

**Comment by justinrusso** [comment]
This seems to be the same issue as the one you referenced?

**Comment by justinrusso** [comment]
Oops.. didnt realize that was BETA 3...

**Comment by 630R63** [comment]
I think this was fixed in dev during yesterday's stream.

**Comment by Darkosto** [comment]
Should be fixed in 3.0.4
