### ISSUE TITLE
[Suggestion] add Diet hoppers?

### ISSUE THREAD

**Issue by Trinsdar** [Darkosto/SevTech-Ages#1092]
it basically just slims the hit box of the hopper so you can click past the hopper.

**Comment by vadis365** [comment]
The mod also causes issues with other modded hoppers (specifically 2 of my mods already in the pack) in my personal experience.
I would like to say no.

**Comment by Darkosto** [comment]
I'd like to not add this mod because of the issues it will cause with other hoppers in the game. Thanks for the suggestion though!
