### ISSUE TITLE
Zaphkiel Waltz

### ISSUE THREAD

**Issue by extrenix** [Darkosto/SevTech-Ages#1093]
Any reason why I stop gaining progress during the song?
I play the rattle and drum and the counter always stops at about 3/4 of the progress bar

Version 3.0.3

**Comment by Ambaire** [comment]
You need more instruments to complete the song. Per the Totemic guidebook, each instrument will only give a certain amount of progress to the song. I was able to complete it with plenty of time to spare with a rattle, drum, flute and wind chimes.

**Comment by extrenix** [comment]
it doesn't work. Only using a rattle on the drum will register progress and it always stops at around 3/4.
I've been trying to use the flute and chime as well more than once

**Comment by Dystilled** [comment]
Youre probably just spamming the drum, you have to occassionally look away from the drum to use other stuff. 
Equip the Flute in your offhand once you start the ceremony. 
Do the Flute Imbuement ceremony for your flute, its easy.

**Comment by extrenix** [comment]
ok this seemed to have worked.
thanks guys
