### ISSUE TITLE
[3.0.3] Better With addons cauldron cooked fish don't have nutrition values

### ISSUE THREAD

**Issue by Marioluigi7896** [Darkosto/SevTech-Ages#1094]
## Issue / Bug

When a fish is cooked in a BWM cauldron it gives cooked fish, which has no nutrition vales (protein)
## Current Behavior

Cooking a fish in a cauldron does the above stated issue
## Possible Solution

Add the cooked fish to the config
## Steps to Reproduce (for bugs)

1. Put fish in a cauldron
2. Look at tooltip

## Context

I wanted to eat the fish for a protein benefit
## Your Environment

* Modpack Version: 3.0.3
* Java Version: 1.8.0_144
* Launcher Used: MultiMC
* Resourcepack Enabled?: Soartex_Fanver_Modded_Universal(4.1.2)
* Optifine Installed?: No

**Comment by Marioluigi7896** [comment]
Also possibly add them to the listAllmeatcooked oredictionary to use in tasty sandwiches?

**Comment by DaedalusGame** [comment]
oops

**Comment by artdude543** [comment]
Resolved in later updates of the pack/mod.
