### ISSUE TITLE
[Mod Request][Suggestion][Low Priority]ExtraUtilities/Search Nearby Inventories Key

### ISSUE THREAD

**Issue by Dystilled** [Darkosto/SevTech-Ages#1095]
Probably one of the most useful quality of life functions to a mod I can think of. 

When you hover over an item and press T (default) it shows particle effects on inventories that contain that item allowing you to locate that item rather than sifting through multiple inventories. 

Even if everything else in the mod is disabled, that function would be great.

**Comment by ryankhart** [comment]
I agree. I wouldn't even mind if this mod was added and everything else but the "Search Nearby Inventories" feature was disabled. In fact, that's something even I can learn how to do myself, that I just might do it on my own local game.

**Comment by ryankhart** [comment]
Better yet, add it in as an early game progression unlock, the ability to auto search for an item in nearby inventories.

**Comment by Dystilled** [comment]
Its actually such a great feature im not sure why noone else has coded it as a standalone mod. 

Could call it "Where is My?" or something

**Comment by Dystilled** [comment]
Yes!

**Comment by ryankhart** [comment]
Yes!! I wondered at first why that mod didn't come up in all of my Google searching, then I realized this is a brand new mod just released days ago. I'll for sure be downloading that mod.

It's probably a client side mode, so you can install it yourself and not worry about it affecting the balance of the progression.

**Comment by lawl281** [comment]
would also like to see this added to modpack.  This feature almost feels required when you have as many items available as we have but have to wait to unlock ae or refined storage

**Comment by justinrusso** [comment]
There are other mods in the pack besides just AE and RS that are available sooner as well

**Comment by ryankhart** [comment]
Honestly, since FindMe seems like such a modular mod with that standalone feature, I wouldn't mind just dropping it into my own local installation of the modpack. It's a feature I got so used to in 1.7.10 modpacks, that it might as well be a vanilla feature for me.

**Comment by lawl281** [comment]
I tried adding it on my server but ti requires every user to have it.  what mods to make item managment more feasable. yes I know about drawers

**Comment by justinrusso** [comment]
Theres more mods than just drawers as well. :)

**Comment by artdude543** [comment]
Added in 3.0.7
