### ISSUE TITLE
Betweenlands effects strip Nutrition's gold hearts

### ISSUE THREAD

**Issue by MrHrulgin** [Darkosto/SevTech-Ages#1096]
In 3.0.3:

With absorption hearts from good nutrition, stand in the swamp water in the Betweenlands. Occasionally, your gold hearts will vanish. It can happen similarly when eating a sap ball. I think there's a bad interaction between the two effects changing max health, in large part because when you eat a sap ball, your health drops to what should be your max health under the decay rules.

**Comment by TheCyberBrick** [comment]
https://github.com/Angry-Pixel/The-Betweenlands/commit/e2cc7241153202918e42872bf5aabbe1d881f942
Should be fixed with that, new update will be released soon

**Comment by justinrusso** [comment]
Updated to https://minecraft.curseforge.com/projects/angry-pixel-the-betweenlands-mod/files/2548656

Will be in 3.0.5
