### ISSUE TITLE
Melon Pie uncraftable

### ISSUE THREAD

**Issue by lawl281** [Darkosto/SevTech-Ages#1097]
## Instruction on how to do issues like your boy darkosto

Can't craft melon pie in stage 2 recipe shown is:
https://i.imgur.com/Pkq9Edw.png

crafting output: 
https://i.imgur.com/Bo60roE.png

## Your Environment

* Modpack Version: 3.0.3
* Java Version:
* Launcher Used: twitch
* Resourcepack Enabled?: no
* Optifine Installed?: yes

**Comment by DaedalusGame** [comment]
ok i hope that isn't on my end

**Comment by artdude543** [comment]
Resolved in 3.0.7

![image](https://user-images.githubusercontent.com/1885466/39196949-43043e54-47db-11e8-94c7-e5cb7e76893c.png)
