### ISSUE TITLE
Betweenlands torch bug

### ISSUE THREAD

**Issue by MrHrulgin** [Darkosto/SevTech-Ages#1098]
Lit fiber torches will convert to damp torches when placed in the betweenlands, but will not trigger the Dimwitted advancement.

You can also convert fiber torches to regular ones for free using this method plus a grill, but it's more of a slog than just mining coal, so whatever.

**Comment by TheCyberBrick** [comment]
https://github.com/Angry-Pixel/The-Betweenlands/commit/f39246e93838bbd81f0d054073bbd7fda20c918b

Should be fixed in the next update

**Comment by justinrusso** [comment]
Updated to https://minecraft.curseforge.com/projects/angry-pixel-the-betweenlands-mod/files/2548656

Will be in 3.0.5
