### ISSUE TITLE
Mirrored Recipes

### ISSUE THREAD

**Issue by Dawenzel** [Darkosto/SevTech-Ages#110]
It can be annoying if you need to redo the recipe in the workstump because it isn't mirrored so I'll update this issue if I find recipes that could be changed from Shaped to ShapedMirrored.

pickletweaks:mesh
progressiontweaks:spear (this recipe already was mirrored with 2 different recipes)

**Comment by Darkosto** [comment]
Added, I will find a number of recipes to add this onto for QoL improvements. Thanks!
