### ISSUE TITLE
All advancements have been reset to zero after computer crash.

### ISSUE THREAD

**Issue by TWJedi** [Darkosto/SevTech-Ages#1101]
My computer froze during a play session, I had to reboot. Right before the freeze, I had transferred a few items to a chest. When I loaded up my game again, I noticed two things:

1) Those items that I recently transferred were duped in my inventory.
2) All my advancements, with the exception of two, were reset to zero.

Pic: https://imgur.com/a/P03dn

I was in Age 2, about half way through the Twilight Forest progression. 

Now, I realize my computer freezing is a separate issue. Is there anything I can do about the advancements resetting? I immediately tried to restore a backup, but it does't look like the pack comes with a backup mod?

If there is no backup option, I strongly recommend adding one to the pack. And if there isn't one, are there any commands I can use to quickly grant myself all of my lost advancements?

**Update:** According to "/gamestage info", it says "zero, two_mob, one, baykok, tutorial, two", but the game seems to have erased all of the individual advancements that I've completed?

Any help is greatly appreciated.

Minecraft version 1.12.2
Forge version 14.23.2.2638
Pack version 3.0.3
Java version 8 update 161

**Comment by justinrusso** [comment]
You can also set up your own backup mod... Microsoft doesn't enforce backups either.

**Comment by esmecat** [comment]
i seem to be having a similar issue. 

my computer crashed while playing. i had just updated to 3.0.6 about 10 mins before. i was in stage 1. at the time, i had been placing a sign on a crate that i had just filled. when i restarted, the crate in question and the one i had filled just previous to it were empty and the items lost and all my advancements seem to have been reset. i still have access to all the unlocked recipes in jei and items that were unknown in stage 0 are still known. mobs, however, seem to have reverted to stage 0 mobs. 

/gamestage info says: zero, one_mob, one, tutorial

any info on how to potentially restore advancement progress without restarting on a new world?

**Comment by GirafiStudios** [comment]
If you use the Twitch Launcher that does running backups of your whole instance.
Should be located in your Twitch Launcher install path, and then Minecraft/Backups/SevTech Ages

**Comment by artdude543** [comment]
This is something out of our control and sadly something we can't always fix. We are looking into providing a backup mod for 3.0.7 but that's still in talks.

But apart from that these things do happen it's the way MC handles saving things can/will be lost 😞
