### ISSUE TITLE
Shoggoth's no longer spawning

### ISSUE THREAD

**Issue by Alexrule44** [Darkosto/SevTech-Ages#1103]
After dieing to a couple shoggoths I came back to the cave with no shoggoth around. Went to a couple other shoggoth caves that I had already found and none were in them either. Decided that I should just explore some new chunks and hope that I find another one. Found another cave in a freshly loaded chunk and no shoggoth had spawned there either. 

I have the game set to normal difficulty and have already reset it to peaceful -> easy -> normal with no luck on them spawning back. 

Kinda sucks as you need them to progress in age 1.

* Modpack Version: 3.0.3
* Java Version: current
* Launcher Used: Twitch
* Resourcepack Enabled?: no
* Optifine Installed?: no

**Comment by SuohKami** [comment]
Are your lairs missing the Shoggoth Biomass block that is supposed to spawn in that circular hole in the ground? If so, you should creative mode it in to get them to spawn again. I spent several hours looking for a 2nd lair and found this is what was missing from the lair near my base.

**Comment by OriginalSuperGumby** [comment]
Not a cool dynamic. How about permanent biomass?

**Comment by Phantum** [comment]
Talk to the mod author.

**Comment by artdude543** [comment]
There were some tweaks to the mod included in 3.0.7 in regards to spawning but they are working just fine in 3.0.6. But I don't find this an issue as players and testers are not facing the same issue.
