### ISSUE TITLE
Non-hosting client crashes when better with addons waterwheel broken while playing LAN world.

### ISSUE THREAD

**Issue by LogicEngineer** [Darkosto/SevTech-Ages#1104]
## Instruction on how to do issues like your boy darkosto
[crash-2018-03-30_00.49.04-client.txt](https://github.com/Darkosto/SevTech-Ages/files/1862781/crash-2018-03-30_00.49.04-client.txt)
 
## Issue / Bug
Non Client crashes when better with addons waterwheel is broken 

## Possible Solution
No clue as far as a fix.

## Steps to Reproduce (for bugs)

1. Open singleplayer and open to LAN
2. Connect with second account
3. Place and break water wheel in survival (i think it may also crash on shift-right-click)
4. Crash second player. (doesn't even have to be looking at water wheel

## Context

My friend and I are playing in a LAN world because it is less stressful on his computer than running a server. Placing a waterwheel is fine but breaking it seems to only crash me and not him. Very annoying.

## Your Environment

* Modpack Version: 3.0.3
* Java Version: v8 161
* Launcher Used: Twitch
* Resourcepack Enabled?: no
* Optifine Installed?: no

**Comment by liquidsystem** [comment]
I am the host when this occurs, to add onto this, you can also SHIFT+RIGHT-CLICK to pick up the water wheel, which results in it being "air" with the texture of a nether portal, this also results in a crash.

**Comment by justinrusso** [comment]
https://github.com/Darkosto/SevTech-Ages/issues/988
