### ISSUE TITLE
Crash, looking for fix

### ISSUE THREAD

**Issue by DerpityDoo** [Darkosto/SevTech-Ages#1105]
I opened up a Betweenlands portal a little too close to my old horsepower setup and I think the portal might have overlapped 1 or more of the machines. Can't load into the world anymore, and I really don't want to lose 15 hours worth of play. You should really give people a better idea about how large these portals are, like an approximate dimension. Thanks beforehand for any help I receive! 

Crash Report: https://pastebin.com/DkZs2MCi

**Comment by DerpityDoo** [comment]
I just removed horsepower, loaded the world, then re-added horsepower and that fixed it. I really hope you add something to the advancement like "put it at least 15 blocks away from anything you don't want turned into a tree"

**Comment by Shock2k** [comment]
Same thing happened to me... same crashing problem.  (Spawned the portal into my base, and as original poster stated, my base stuff turned into tree stuff, basically putting me back to the stone age).  (Posted bug)

Update:
I did as DerpityDoo did and removed horsepower and reloaded.  Gives you an error about missing registry entries, (ignored and continued).  World loaded without issue.  Shut down game (save and exit, then quit SevTech Ages title screen).  Re-added horsepower mod and reloaded.  (WORKED!) Thank god that would have been like 60 hours lost.

Well to all those who just go their base blown up to the Troll tree... I salute you! .... Never forget, never surrender...

Shock2k

**Comment by TheCyberBrick** [comment]
I'll let Gory know. I think this is on Horsepower's side

**Comment by GoryMoon** [comment]
2.5.13.60 should have this fixed

**Comment by justinrusso** [comment]
Updated.

Will be in 3.0.5
