### ISSUE TITLE
Random crash walking around terrain.

### ISSUE THREAD

**Issue by Ryzelf** [Darkosto/SevTech-Ages#1106]
Random crash. It is maybe my side i thought i would just report in case its major.

**Crash Report:**

https://pastebin.com/x3aEBMrT

**Comment by liquidsystem** [comment]
This is a known issue with Better with Mods, it's a problem with the bounding box of the water wheel drawing incorrectly. It looks like it's already been fixed in the newest version of BwM, hopefully next version of SevTech Ages will include it.

**Comment by justinrusso** [comment]
https://github.com/Darkosto/SevTech-Ages/issues/988
