### ISSUE TITLE
Worms disappeared after reloading

### ISSUE THREAD

**Issue by borg286** [Darkosto/SevTech-Ages#1107]
## Issue / Bug
Worms[Actually Additions] placed in farm disappeared after reload.

## Current Behavior
I planted some worms on grass to make a farm area. Saved a quit Minecraft. Upon reload the worms are gone.

## Your Environment

* Modpack Version: 3.0.3
* Java Version: 1.8.0_25
* Launcher Used: Twitch
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by Buuz135** [comment]
Worms die after a while

**Comment by Darkosto** [comment]
They do not last forever.

**Comment by borg286** [comment]
Ok. Feel free to close. Seems balanced with the rest of the mod pack
