### ISSUE TITLE
Game crashes when I try to break blocks from the "Chisel" mod

### ISSUE THREAD

**Issue by DispenserBro** [Darkosto/SevTech-Ages#1108]
## Issue / Bug
Game crashes when I try to break blocks from the "Chisel" mod
Crash log here: https://pastebin.com/i0ag1TBp

## Possible Solution
I don't know

## Context
I had faced with this issue when i was trying to break a marble block after rerunning the game. Later I had tried to break limestone and other "raw" blocks from the "Chisel" mod and game continued to crash.

## Your Environment

* Modpack Version:3.0.3
* Java Version:1.8.0_161-b12
* Launcher Used:Twitch app(Native Minecraft launcher)
* Resourcepack Enabled?:No
* Optifine Installed?:Yes

**Comment by justinrusso** [comment]
Are you on a server? A duplicate issue was - just seeing if theres a similarity.

**Comment by artdude543** [comment]
Linking the issue reported so we have easier tracking https://github.com/Chisel-Team/Chisel/issues/676

**Comment by artdude543** [comment]
This will be fixed in 3.0.7
