### ISSUE TITLE
Mod Logs not triggering the Cavemen hate trees achievement

### ISSUE THREAD

**Issue by TieMonkey** [Darkosto/SevTech-Ages#111]
- Explain the issue / bug as understandably as possible.

When breaking IronWood (Both Rustic and PrimalCore), Yew, Olive, Eucalyptus, Sakura, Ghostwood, Fusewood, Alicio, Mulberry, Red Cedar, Fir, All Twilight Forest Trees, Darklands Oak, Dreadlands Wood, and Tea Saplings They won’t  trigger the “Cavemen Hate Tree’s” achievement. There might be more trees that don’t work cause I couldn’t get them to grow as well. 

Yes granted I know not all of these trees should be able to trigger the achievement, Just wanted to list all of the available options just in case.

 - If possible add minecraft, forge, java and modpack version numbers for debugging (mod authors might need these).

Minecraft Version = 1.12.1
Forge Version = 
Java Version = 
Mod pack Version = Alpha 3

**Comment by Darkosto** [comment]
This should be fixed,  let me know if this is still the case in the new version coming out soon.
