### ISSUE TITLE
Cyan Hyacinth can't be turned into dye powder in stage one

### ISSUE THREAD

**Issue by iffonox** [Darkosto/SevTech-Ages#1110]
Just as the title says. It's the only flower I encountered so far, that can't be turned into dye powder.

SevTech version: 3.03

**Comment by oOMitchOo** [comment]
Here is a list of (Ferdinand's) flowers which are missing a dye recipe in SevTech 3.0.3 for the Immersive Engineering (i) Crusher, The Better With Mods (ii) Millstone and the Horse Power (iii) Grindstone and (iv) Horse Grindstone.

- **Cyan Hyacinth:** ferdinandsflowers:block_cff_flowersd with meta 10
into **Cyan Dye Powder:** pickletweaks:dye_powder with meta 9

- **Cloud Blue Corydalis:** ferdinandsflowers:block_cff_flowersd with meta 11
into **Light Blue Dye Powder:** pickletweaks:dye_powder with meta 3

- **Light Blue Forget Me Not:** ferdinandsflowers:block_cff_flowersd with meta 12
into **Light Blue Dye Powder:** pickletweaks:dye_powder with meta 3

- **Commelina:** ferdinandsflowers:block_cff_flowersd with meta 13
into **Light Blue Dye Powder:** pickletweaks:dye_powder with meta 3

- **Morning Glory:** ferdinandsflowers:block_cff_flowersd with meta 14
into **Blue Dye Powder:** pickletweaks:dye_powder with meta 11

- **Magenta Orchid:** ferdinandsflowers:block_cff_flowersd with meta 15
into **Magenta Dye Powder:** pickletweaks:dye_powder with meta 2

**Comment by Darkosto** [comment]
I've done the BWM and HP scripts I'll @justinrusso do the IE crusher recipes since he has that setup in a different place.

**Comment by justinrusso** [comment]
All 3 machines get added at once. I've added the missing ones. I just need to remember to remove what you added in BWM + HP
