### ISSUE TITLE
Dying to Baykok causes CTD

### ISSUE THREAD

**Issue by PragmaticThoth** [Darkosto/SevTech-Ages#1111]
Running Version 3.0.3 with no additional mods or texture packs

1. Summoned Baykok and died pretty fast.
2. Tried to respawn and crashed to desktop.
3. Reloaded, and Baykok was waiting outside my door.
4. Another death and another CTD when trying to respawn.

I'm guessing that his proximity to my respawn point is causing some sort of issue.
Bed is 2-3 chunks away from where he was spawned. But likely he was in the same chunk after first death. 

Crashlog - https://pastebin.com/tRbDZAXK

**Comment by 630R63** [comment]
It's the old Water Wheel issue from BwM.. I think this will be fixed in the new update of the pack. If you'd like a temporary fix, you could unlock the profile and update the "better with mods".

**Comment by PragmaticThoth** [comment]
Yeah, looks like it is definitely the water wheel issue. Thanks for the reply :D
