### ISSUE TITLE
Server wont start (log included)

### ISSUE THREAD

**Issue by Esconomics** [Darkosto/SevTech-Ages#1112]
I'm not sure if this is the right place but after searching for a few days I am desperate. I am trying to set up a server. I've done everything as I normally would have. I have not changed anything except renaming the forge jar to custom.jar as my server host makes me do. Here is my log:

[https://pastebin.com/MDieGc7c](https://pastebin.com/MDieGc7c)

**Comment by mmagoo13** [comment]
I am also having this same issue when my server loads to that exact point. However i have my server jar as the default name i have not changed it to custom.jar

**Comment by Esconomics** [comment]
Can someone please help with this?

**Comment by Esconomics** [comment]
OMG spoke to Darkosto today on his stream. He looked at it and said the server should be running. Sure enough, even though my control panel says it is offline, the server was up and running! Please check yours, mmagoo13! I use theminecrafthosting for mine. Maybe thats your host too and their thing is just messed up

**Comment by artdude543** [comment]
Closing as this seems to be an issue with server providers not working "right".
