### ISSUE TITLE
java.lang.OutOfMemoryError: GC overhead limit exceeded

### ISSUE THREAD

**Issue by Okiraishi** [Darkosto/SevTech-Ages#1116]
When the game is at the loading screen it crashes after like 2/3 minutes, i tried to downgrade the version, but the same error occurred.
Here's what it says after crash:

> The game crashed whilst initializing game
Error: com.google.common.util.concurrent.ExecutionError: java.lang.OutOfMemoryError: GC overhead limit exceeded

I took a screenshot 5 seconds before crash:
https://puu.sh/zRVkS/d235669735.png

Any ideas ?

**Comment by DerpityDoo** [comment]
you only have like 3GB of ram allocated to this pack, you will want 6-8GB to even try to run it

**Comment by Okiraishi** [comment]
Can you tell me how can i do that ?

**Comment by SephirothWS** [comment]
In the Twitchapp if that's what you're using, click on your name on the top right corner for a menu, select Settings from that menu. Once you have the settings pane open, flip to the Minecraft section and then scroll down towards the bottom. You'll find your RAM allocation there. 1 GB = 1024 MB. ... I personally use 8,192 MB (8 GB) but I'm sure you can get away with 6,144 MB (6 GB)

If you're running AT Launcher, similar thing, Flip to the settings tab, then the Java/Minecraft tab and set both Initial Memory/Ram and Maximum Memory/Ram to one of the values above.

**Comment by DerpityDoo** [comment]
Twitch Launcher > Mods > Sevtech > The thee dots button in the top right > Profile options > untick "Use system settings" box if its ticked > choose amount of ram you want

**Comment by Okiraishi** [comment]
Thanks you very much guys, i've set it to 8,206 and now it works :D
