### ISSUE TITLE
No squids or sharks spawning in singleplayer

### ISSUE THREAD

**Issue by Bobiwobi** [Darkosto/SevTech-Ages#1117]
I've been searching for hours in waters in my singleplayer world and I have not been able to find a single squid or shark. I don't know if this is intended or I am just having bad luck. My pack is the latest version (3.0.3) and I've made multiple minecraft worlds that all have the same issue. 
I have allocated 8GB of RAM to Sevtech:Ages so I doubt it because of any internal server lagg.
Anyway I hope there will be a fix for this in the future.

**Comment by SuohKami** [comment]
Same with sharks, but not squids for me. Instead of squids I don't have piranha spawns. Squids are also fairly uncommon I had to search quite a bit.

**Comment by Synliss** [comment]
I was also having the same problem. But it seems to have worked when I got into a raft and moved around on water resetting the entities in the world. Lots of little fish and the like. The squid population exploded.

**Comment by knoxz** [comment]
same here. No sharks no squids...

**Comment by Doeyhead** [comment]
Have we gotten an answer on this problem? I have stopped being able to progress because i can't get ink

**Comment by justinrusso** [comment]
Convinced this isnt an issue, but we're adding changes anyways.

#1045
