### ISSUE TITLE
Server properties

### ISSUE THREAD

**Issue by Piotrekblue** [Darkosto/SevTech-Ages#1119]
Hi, I'm starting new server and I don't know how to set up realistic way to create a world. Also we could use some tutorial for that :)

**Comment by Mrbysco** [comment]
Starting from the 3.0.3 server files the proper server.properties comes with the server files. You don't need to change the world type.

**Comment by artdude543** [comment]
All you need to change in the server probs is the following: `level-type=quark_realistic`

**Comment by BryanBoru** [comment]
@artdude543 I am curious if the banding effects of biome placement will still occur with quark realistic world type?
