### ISSUE TITLE
Immersive tech machines (boiler and solar tower) wont allow me to interact them

### ISSUE THREAD

**Issue by BananaLord12** [Darkosto/SevTech-Ages#1120]
## Issue / Bug
I am currently near the end of age 3, and i was asked by the advancements to create a boiler or a solar tower. When i made the machines, i was not able to interact with them and i though that you should be able to open them to create steam for plastic later on.

## Steps to Reproduce (for bugs)
1. Create a machine from immersive tech mainly boiler or solar tower
2. Try interacting with it

## Context
This issue has affected really me and possible the people who will get to the point that i am, badly because i am not able to progress though the pack.

## Your Environment

* Modpack Version: 3.0.3
* Java Version: 8u162 (current latests)
* Launcher Used: Twitch
* Resourcepack Enabled?: No resourcepack used
* Optifine Installed?: 1.12.2_HD_U_C9

**Comment by justinrusso** [comment]
https://github.com/FerroO2000/Immersive-Tech/issues/48 has been reported

**Comment by kugamer** [comment]
I also ran into this as well. The boiler does not have gui. It does produce steam, you are just blind and have no idea how much water/diesel/steam is in the machine.

**Comment by BananaLord12** [comment]
really? Cause the water and diesel stays the same in the tank but it might be the tanks, any recommendations?

**Comment by artdude543** [comment]
Fixed in 3.0.7
