### ISSUE TITLE
Modular Machine Shift Clicking causes crash

### ISSUE THREAD

**Issue by kugamer** [Darkosto/SevTech-Ages#1121]
When in the fluid input or output of a modular machine, attempting to shit click an item in the machine causes a crash. 
I was trying to move a buildcraft tank, I broke it and pieces of the material in the tank went everywhere. I tried picking the material up, which was molten propene, and shift clicking it into the fluid input of the machine. This caused a game crash. I eventually figure out you can just put it back in the tank. Not knowing the mod I tried to shift click a bucket in the fluid output side and it crashed that way as well. 

To reproduce just build any of the modular machines and go into the fluid gui and try to shift click an item in. It crashes everytime for me. 

Modpack Version: 3.0.3
Java Version: 8u162 (current latests)
Launcher Used: Twitch
Resourcepack Enabled?: faithful
Optifine Installed?:no

**Comment by artdude543** [comment]
This is fixed in both 3.0.6/7. Please update to the latest and also try on the next update when it lands.
