### ISSUE TITLE
Cyclic automatic fishing net doesn't work because fishing loot table is empty(?) - Fishing mechanics

### ISSUE THREAD

**Issue by cheesealmighty** [Darkosto/SevTech-Ages#1122]
Cyclic automatic fishing doesn't seem to work currently, since it draws fish from the loot table (as it is stated in the cyclic book). And I believe the loot table has been emptied to favor JAFF fishing mechanics (Wasn't able to get fish, or anything). 

Yet, JAFF fish doesn't spawn as often. Hampering fish production, even if player want to dedicate time for it, making it a very bad alternative compared to other food methods (farming, breeding animals, trading). (Also see other posts about sharks/squids not spawning, might be that something off is going on with mobcontrol)

Currently only good way of getting fish is the strainers. Which are fine, except troweling dirt blocks over and over again isn't exactly stimulating.

Possible fixes:
1- Reenable fishing loot table
2- Disable cyclic auto fishing net (Subsequently remove it from the fisherman villager as well)
3- Fish for gold trading opportunities (Either through market, or villagers)

## Your Environment

* Modpack Version: 3.0.3
* Java Version: Ver8-B161
* Launcher Used: Twitch
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by DaedalusGame** [comment]
is Hardcore Fishing enabled in the BWM config?

**Comment by justinrusso** [comment]
Duplicated issue got closed with the fix. Closing this one since it was missed
