### ISSUE TITLE
PneumaticCraft wrench is not shown in JEI

### ISSUE THREAD

**Issue by Pandemoneus** [Darkosto/SevTech-Ages#1123]
## Issue / Bug
The PneumaticCraft wrench is hidden from JEI in stage 4, you can only find it if you use the 'usage' key on one of the components needed for the wrench.

[edit]
Looks like other PneumaticCraft items with a "durability" (pressure) bar are not shown either.
These include: Amadron Tablet, Vortex Cannon, Manometer, Camouflage Applicator, Pneumatic Wrench, Logistics Configurator

## Steps to Reproduce (for bugs)
1. Search 'wrench' or '@PneumaticCraft'
2. The pneumatic wrench is not listed

## Context
The assembly IO arm can only be rotated or the modes switched with the pneumatic wrench (wrenches from other mods do not work). Can't use any programs if I can't switch any IO to input mode.

## Your Environment
* Modpack Version: 3.0.3
* Java Version: 8u160
* Launcher Used: Minecraft Jar Launcher (via Twitch)
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by kylertoll** [comment]
Same issue. Went into a test world and the only other wrench that is compatible with the IO unit is the RFTools Smart Wrench which is gated behind stage 5. So no options to configure IO unit in stage 4.

**Comment by Darkosto** [comment]
Okay, I think I've got this figured out. Hopefully, it will be back in 3.0.5. For the meantime, you can use the usage key on Compressed Iron to see the recipes for the items you need.

**Comment by justinrusso** [comment]
Can confirm this is showing now
