### ISSUE TITLE
Tough dowsing rod recognizes bauxite ore which I cannot see in age 2

### ISSUE THREAD

**Issue by Tayba3** [Darkosto/SevTech-Ages#1124]
Simple, it tells me it's there but I can't see it or get anything when I mine it but stone.

* Modpack Version: 3.0.3 (also on server if that matters)
* Java Version: 8 161
* Launcher Used: twitch
* Resourcepack Enabled?: soartex
* Optifine Installed?: yes

**Comment by Darkosto** [comment]
I removed this from the list of blocks it's able to pickup. Thanks!
