### ISSUE TITLE
Totem torch can be used to block lava flow w/o burning

### ISSUE THREAD

**Issue by tehMorag** [Darkosto/SevTech-Ages#1126]
Super low priority bug

## Issue / Bug
Totem torch can be used to block Lava flow with out burning -> [Example image](https://pbs.twimg.com/media/DZisjZXVwAEYtXi.jpg)

## Your Environment
* Modpack Version: 3.0.3
* Java Version: 1.8.0.161 (64bit)
* Launcher Used: Twitch (Using "Launch Method" -> "Jar Launcher")
* Resourcepack Enabled?: no
* Optifine Installed?: yes (for shaders)

**Comment by artdude543** [comment]
https://github.com/TeamTotemic/Totemic/issues/80

**Comment by artdude543** [comment]
This will be fixed in 3.0.7
