### ISSUE TITLE
Slabs uncraftable

### ISSUE THREAD

**Issue by Viba** [Darkosto/SevTech-Ages#1127]
Trying to craft slabs with the work stump is not working, I've tried placing the wooden/cobble slab recipe in the work stump (all possible directions/placements) but it fails to craft. Not sure how to reproduce, as I watched videos of other players crafting them without problems.

Might be related, I can craft planks and sticks like in vanilla through the 2x2 crafting grid. JEI is not showing any recipe for said slabs.

latest.log https://puu.sh/zSJJW/17633947a3.log
https://i.imgur.com/7yR37kK.png
https://i.imgur.com/HekkfM7.png

* Modpack Version: 3.0.3
* Java Version: 1.8.0.161 (64-bit)
* Launcher Used: Twitch/Curse
* Resourcepack Enabled?: No
* Optifine Installed?: No

**EDIT:**
Works with Java 1.8.025 and no launch commands.

**Comment by Darkosto** [comment]
It sounds like some files may be missing if you're able to craft the sticks/planks in your 2x2. I would suggest reinstalling the pack and responding back to let me know if this fixed it.

**Comment by Viba** [comment]
Sorry forgot to update this, so as it turned out ImprovedBackpacks errors out during launch if you have mouse thumb buttons in your keybindings. I disabled that mod and that in turn caused the crafting problems, before the button issue was discovered. Can probably close this.

**Comment by artdude543** [comment]
Going to use https://github.com/Darkosto/SevTech-Ages/issues/705 as the master for tracking this issue as it's all related.
