### ISSUE TITLE
Block Placer Doesn't Appear in JEI Despite Being Unlocked in Stage 3

### ISSUE THREAD

**Issue by Vyraal1** [Darkosto/SevTech-Ages#1129]
## Issue / Bug
1) Checking the uses of Platinum Plates shows Cyclic Block Placer recipe available in Stage 3
2) It does not show up in JEI, this screenshot was taken with Item Hiding Mode True

![image](https://user-images.githubusercontent.com/26587049/38145766-fd735eea-3418-11e8-9029-f16643f638f1.png)

## Possible Solution
- not really sure, don't think it's a staging issue since the recipes and JEI should be linked, maybe it was just hidden via CraftTweaker script?

## Context
- this could trick players into thinking they don't have any way to automate the saw or automatically place blocks in Stage 3 when they look up placers, etc.

## Your Environment
* Modpack Version: 3.0.3
Optifine is installed

**Comment by Gremilcar** [comment]
This would've solved so many problems I had at age 3...

**Comment by Darkosto** [comment]
Seems it was incorrectly added to the hiding scripts. This will be fixed 3.0.5. Thank you and sorry for the inconvenience.
