### ISSUE TITLE
Pelt not dropping

### ISSUE THREAD

**Issue by Dawenzel** [Darkosto/SevTech-Ages#113]
## Bug/Suggestion
Some of the animania animals are not dropping their assiociated pelts when killed. This applies to:
- Hog and Sow (pig pelt)
- Buck and Doe "rabbit variant"(Rabit hide/Animal pelt)
- Ram and Ewe (Sheep pelt)
- Buck and Doe "goat variant"(Sheep or Animal Pelt)

## Versions
- Sevtech Alpha4 MultiMC
- Minecraft 1.12.1
- Forge 14.22.1.2485
- Java x64 8u144
- Animania 0.3.4

**Comment by Darkosto** [comment]
The pig variants are the only mobs on this list that are not turned off, and they should now drop pelts. Thank you!
