### ISSUE TITLE
Endermen and Blaze aren't affected by looting

### ISSUE THREAD

**Issue by Gremilcar** [Darkosto/SevTech-Ages#1132]
## Issue / Bug
Both endermen and blazes don't seem to drop more loot or drop it more often no matter if you are killing them with a weapon with Looting enchantment or not.

## Current Behavior
For testing purposes spawned 10 blazes for each weapon:
nothing      - 4 drops
Looting III  - 4 drops
Looting X   - 6 drops

## Possible Solution
A possible reason is somehow linked to the fact that both these mobs have modified loot drops from their vanilla variants.

## Your Environment
* Modpack Version: 3.0.3 (observed as early as 3.0.1)
* Java Version: 161
* Launcher Used: native
* Resourcepack Enabled?:
* Optifine Installed?:

**Comment by vadis365** [comment]
IIRC this has been fixed now and can be closed.
