### ISSUE TITLE
Flaked Flint

### ISSUE THREAD

**Issue by varadinn** [Darkosto/SevTech-Ages#1133]
When making anything along the lines of flaked flint/flaked flint points or something like that. Instead of it dropping nearby it floats all the way to the surface and you have to go look for it no matter how deep you go

**Comment by BryanBoru** [comment]
underwater?

**Comment by varadinn** [comment]
No on land like i made a mineshaft. I went down to make flaked Flint used all my Flint no flaked Flint. I went to surface and they they were next to a tree. I was 30 block below the tree

**Comment by varadinn** [comment]
Or so i dig deep mine shafts lol

**Comment by Darkosto** [comment]
This is a bug the author has not made a priority to fix in PrimalCore. I've already reported it multiple times and it seems he'll take a look when he's finished on some other content.
