### ISSUE TITLE
game crash on start up 

### ISSUE THREAD

**Issue by abbiethecat** [Darkosto/SevTech-Ages#1135]
### Before anything else, use the *search* feature!
 * Maybe someone already reported the issue you're experiencing?
 * Maybe you can find the answer to your question by looking at older or closed issues?
 * Have a go at it and see!
 * Please search on the [issue track](../) before creating one.
 
## Issue / Bug

https://pastebin.com/kNR1v2BU

## Steps to Reproduce (for bugs)

1.
2.

## Your Environment

* Modpack Version:3.0.3
* Java Version:1.8.0.161 64bit
* Launcher Used:minecraft launcher 1.6.84
* Resourcepack Enabled?:none
* Optifine Installed?:no

**Comment by justinrusso** [comment]
I already directed you to an issue. This is a duplicate. We do not have a fix for this, and is a minecraft issue as well.

https://github.com/Darkosto/SevTech-Ages/issues/924
