### ISSUE TITLE
Bladder holds lava

### ISSUE THREAD

**Issue by Godvil** [Darkosto/SevTech-Ages#1137]
Bladder can hold lava. Is a bit unrealistic IMO

**Comment by justinrusso** [comment]
Yeah.. I dont like the idea of that either

**Comment by vadis365** [comment]
I love the idea - and it was never requested for it not to, no matter 'whomever' tells you different :P 
I have added a config to disable lava being picked up - will push a new release.

**Comment by justinrusso** [comment]
@vadis365 YEAH OK.
