### ISSUE TITLE
[3.0.3] Can use Farmland, Vanilla Chest, cauldron and other things in Stage 0

### ISSUE THREAD

**Issue by Fireztonez** [Darkosto/SevTech-Ages#1138]
Hello Darkosto,
I don't know if is normal, but in stage 0, before go to village, I can craft and use Farmland.
Other thing, I see in the server I play, alway's is stage 0 I can use Vanilla Chest, Cauldron, Smeltery and other thing's unknown... So look like I can pass trough lot a advancements and probably can use machinery, AE or RS system and everything in the first stage, before know how to build and use that!!

For sure, is still impossible to use unlocked tool's and item's or place a block not unlocked in the stage...

Fireztonez

**Comment by Ambaire** [comment]
well yeah, none of the stages affect what you can interact with in the world. it's just a crafting/placing restriction.

**Comment by Darkosto** [comment]
Not a bug.
