### ISSUE TITLE
Food bug maybe

### ISSUE THREAD

**Issue by Jakrippr** [Darkosto/SevTech-Ages#1139]
The cooked shark meat can be consumed even past full hunger. Not sure if intended but that makes protein very easy to keep at 100.

**Comment by Targren** [comment]
Same for Wolf Meat.

**Comment by muskabeatz** [comment]
Same with Rice Bread.

**Comment by Darkosto** [comment]
This doesn't bother me, I'm going to close this because I'm not worried about changing it.
