### ISSUE TITLE
Animania wool

### ISSUE THREAD

**Issue by Dawenzel** [Darkosto/SevTech-Ages#114]
## Bug
The animania sheep and goats are dropping animania wool or vanilla wool instead of fleece after it is shorn.

Credit goes to Serolar on Discord.

## Versions
- Sevtech Alpha4 MultiMC
- Minecraft 1.12.1
- Forge 14.22.1.2485
- Java x64 8u144
- Animania 0.3.4

**Comment by Darkosto** [comment]
Should be fixed up now that Vanilla Sheep are SUPPOSED to be spawning.
