### ISSUE TITLE
Field manual is impossible to craft

### ISSUE THREAD

**Issue by Gremilcar** [Darkosto/SevTech-Ages#1140]
## Issue / Bug
Not only it requires a book to craft (which is locked in early ages. It also needs wooden pickaxe which is not possible to obtain anyway. 

## Possible Solution
Change the recipe similar to other books.

## Context
This manual contains important info on ore spawn ranges - accidentally losing it in age 0 would be extremely annoying

## Your Environment
* Modpack Version: 303
* Java Version: 161
* Launcher Used: native
* Resourcepack Enabled?:
* Optifine Installed?:

**Comment by xCDJ** [comment]
For now maybe just change to cheat mode and give yourself one?

**Comment by Gremilcar** [comment]
wasn't me - was someone else on discord

**Comment by Darkosto** [comment]
Added a recipe for it in 3.0.4.
