### ISSUE TITLE
Glitch to craft Crafting Table early.

### ISSUE THREAD

**Issue by SirCB85** [Darkosto/SevTech-Ages#1141]
Hi, we just discovered a way to make a crafting Table out of Birch Wood right at the beginning, using the Flint Hatchet.
https://clips.twitch.tv/PuzzledAliveScorpionBCWarrior
---------------------------
Modpack Version: 303
Java Version: 161
Launcher Used: native
Resourcepack Enabled?:
Optifine Installed?:

**Comment by justinrusso** [comment]
What is the server on?  Can you provide the crafttweaker.log of the server

**Comment by legendblade** [comment]
The server is running on 3.0.3.  I'm currently troubleshooting other issues, or I would provide the crafttweaker.log file - though it is 3.6MB.

**Comment by justinrusso** [comment]
gist.github.com

**Comment by Jandakast** [comment]
Cannot reproduce. Create a new issue with the crafttweaker.log if this is still an issue for you.
