### ISSUE TITLE
Betweenlands portal not working

### ISSUE THREAD

**Issue by JBrittenham** [Darkosto/SevTech-Ages#1142]
## Issue / Bug
You can kill druids before age 2 and pick up talisman pieces which opens up the Betweenlands achievement tab. While this is not a problem, I believe it is causing an issue once you actually get to age 2 and try to use the Betweenlands portal, it won't actually teleport you. 

## Steps to Reproduce
1. Before age 2, kill a druid and get a talisman piece.
2. Progress to age 2 and create the Betweenlands portal
3. Try to use the portal (in my case, the portal is created but it never actually takes me anywhere)

## Context
I'm unable to progress through the Betweenlands portions of the achievement tree

## Your Environment
* Modpack Version: 3.0.3 / Created world with 3.0.0
* Java Version: 1.8.0.161
* Launcher Used: Curse
* Resourcepack Enabled?: Lithos: Core 32x
* Optifine Installed?: Yes

**Comment by daddy77gaming** [comment]
how do you try to teleport? are you standing inside the tree.. cause that wont work, go stand inside te portal frame and just wait

**Comment by JBrittenham** [comment]
That was it, I feel silly! Thanks
