### ISSUE TITLE
No Mobs Entering Stage 1

### ISSUE THREAD

**Issue by SuohKami** [Darkosto/SevTech-Ages#1145]
Almost unable to get any mobs to spawn at all in Easy, Normal or Hard difficulty. This all started as soon as I entered Stage 1. I think I've seen maybe 4 creepers, 1 spider and 1 skeleton in total. And only 1 abyssal zombie which I've finally found one and got Coralium Gems to drop from which is needed to get the Coralium Pearl to continue the pack. I've sat in the Darklands biome for 4 full Minecraft days and only seen 1 creeper and 1 abyssal zombie.

I also tried a large dark room in the middle of the biome with no luck. (This Darklands biome is huge, can barely see the edges with 32 view distance from the middle, also a fairly nice one since there is less trees.)

At this point I can only cheat to continue.

I'm on version 3.0.3, no optifine, no textures, no shaders, 8gigs ram allocated, Java 1.8.0.161 (64 bit)
I also removed smooth text and better foliage.
Am playing singleplayer.

**Comment by SuohKami** [comment]
I found that this issue seems to be caused by view distance, I changed from 32 to 12 and all of a sudden I have spawns again.

**Comment by artdude543** [comment]
This is not an issue with the pack from the sounds, and that no one else on the pack is having the same issue. Going to close this due to the old version but if you still have the issue please re-file following the template.
