### ISSUE TITLE
Betweenlands Death Loop

### ISSUE THREAD

**Issue by lawl281** [Darkosto/SevTech-Ages#1146]
## Issue / Bug
When you die in the between lands you should either respawn in portal tree or back in overworld.

## Current Behavior
You currently respawn at a random location and then hostile mobs start spawning arround you.  You no longer have anyway to navigate if you haven't unlocked journey maps.  You are now stuck in a death loop because the swamp forces you to swim to travel.

## Possible Solution
force spawn to overworld or portal tree.  If neither of these are possible make a journey map waypoint on entering betweenlands.

## Steps to Reproduce (for bugs)
1. Make portal tree not at spawn.
2. Die in betweenlands..
3. Have fun finding portal in a swamp.

## Context
I am stuck in a death loop with only solution getting server owner to tp me to spawn when they are on.

## Your Environment

* Modpack Version:3.0.3
* Java Version:
* Launcher Used: twitch
* Resourcepack Enabled?: no
* Optifine Installed?: yes

**Comment by TheCyberBrick** [comment]
https://github.com/Angry-Pixel/The-Betweenlands/commit/315c7e0ffe4d5e49dee19442dfcc80cd6fd02bed

Should be fixed with that, next update will be soon

**Comment by lawl281** [comment]
that will make dieing a little less scary

**Comment by TheCyberBrick** [comment]
Yeah, it was supposed to always respawn you near the portal but there was a small oversight

**Comment by justinrusso** [comment]
Updated to https://minecraft.curseforge.com/projects/angry-pixel-the-betweenlands-mod/files/2548656

Will be in 3.0.5
