### ISSUE TITLE
Shaders - Requesting input

### ISSUE THREAD

**Issue by extrenix** [Darkosto/SevTech-Ages#1147]
Anybody using shaders?
I tried running SEUS shaders and experienced a little bit of lag

7700k
16gb RAM (12 dedicated to MC)
970GTX

what kind of settings are you guys using with your shaders pack ?

**Comment by 630R63** [comment]
I am using shaders without any issues at 12 chunks view distance. 

7700k
32gb RAM (10 dedicated to MC)
1080 Ti

I leave the shader at the default settings. The sun already burns my eyes enough.
Were you referring to Minecraft settings or Shader settings?

**Comment by daddy77gaming** [comment]
I'm using SEUS, running around on a fast horse sometimes causes a lag spike, tho even without shaders this pack with all the entities being generated can cause lag ( see other issues). 

What i use is about the same as 630r63 settings apart from a 1070 vc 1080, however if you have 16 dedicating 12 to MC can cause issues with JAVA. 
My golden rule is never to use more then HALF your available ram for java as java can overextend itself (ergo use more then dedicated) and in that way leave your system out of mem.

**Comment by artdude543** [comment]
Closing this issue as it's neither a bug or suggestion but this information can be added to the Wiki to help others and/or Discord :)
