### ISSUE TITLE
Arc furnace steel recipe

### ISSUE THREAD

**Issue by Gremilcar** [Darkosto/SevTech-Ages#1148]
## Issue / Bug

Similarly to porcelain bug, the arc furnace prioritizes making iron out of iron grit even if there is coke dust present

## Current Behavior
When iron grit and coke dust are placed into arc furnace the wrong recipe is prioritized

## Possible Solution

Whatever you did to porcelain?

## Context

Minor issue but a bit annoying.

## Your Environment
* Modpack Version: 202
* Java Version: 161
* Launcher Used: native
* Resourcepack Enabled?:
* Optifine Installed?:

**Comment by Numorphan** [comment]
This seems to apply to any kind of grit + additive recipe. Trying gold grit + silver grit gives a gold ingot with the silver untouched. Trying gold ingot + silver grit works though.

**Comment by artdude543** [comment]
We have removed the recipe using the Iron Dust in favor of Iron Ingot.
