### ISSUE TITLE
Unintended Spawn Chunk Behavior

### ISSUE THREAD

**Issue by luckyscharms23** [Darkosto/SevTech-Ages#115]
Issue:
Upon normal world creation, spawn chunk(s) are spawning with a different biome than its neighboring chunks. In addition, these (corrupted?) chunks are spawning in at the incorrect height.
This issue is not occurring in every new world I create, but I would say it is happening more than 50% of the time.

Here is a link to an imgur album with a few examples of this occurring in the world.
https://imgur.com/a/c5RQy
I can provide more screenshots of this if you would like.

Minecraft Version: 1.12.1 (modded)
Modpack: SevTech Ages Alpha 4
Forge Version: 14.22.1.2485

**Comment by Blargerist** [comment]
Any chance of a seed or two and some coordinates? May help with debugging.

**Comment by Blargerist** [comment]
Found one in -5740726882396191707 at chunk -14,15

Removed Astral Sorcery, biome mapping in the area completely changed and no errors in sight. Was told of a similar issue another pack dev found with Astral Sorcery. Blaming Astral Sorcery. Supposedly fixed next version. /tearsHairOut

**Comment by luckyscharms23** [comment]
10/4/2017
Updated the imgur gallery with some more examples of chunk corruptions.
Suppose we should tag @HellFirePvP ?

**Comment by HellFirePvP** [comment]
It's already fixed, just not released yet due to other things.

**Comment by luckyscharms23** [comment]
Great! 👍

**Comment by Darkosto** [comment]
Yep! should be all good for now in the newest update!
