### ISSUE TITLE
[3.0.3] Right clicking the beneath portal with an item gives the "You dropped unfamiliar item" text

### ISSUE THREAD

**Issue by Marioluigi7896** [Darkosto/SevTech-Ages#1150]
## Issue / Bug

Clicking the beneath portal with an item has strange behavior
[Clip of bug](https://streamable.com/sv8n5)
## Current Behavior

When right clicking the beneath portal with an item in your main hand, when you load the ""You dropped the unfimiliar item" text appears and the item disappears. The item isn't deleted but is just unavailable even after a relog (server).
## Possible Solution

unknown
## Steps to Reproduce (for bugs)

1. Put item in main hand (possibly with offhand empty)
2. right click beneath portal
3. Load in and see no item in your hand

## Context

Saw the portal ate my torches and then they randomly appeared later.
## Your Environment

* Modpack Version: 3.0.3
* Java Version: 1.8_161
* Launcher Used: MultiMC
* Resourcepack Enabled?: Yes
* Optifine Installed?: No

**Comment by artdude543** [comment]
This is a side effect with the game staging when it re-syncs when you move dimension. This is not an easy thing to fix but it's not game breaking.
