### ISSUE TITLE
Steam bucket age locked

### ISSUE THREAD

**Issue by Gremilcar** [Darkosto/SevTech-Ages#1151]
## Issue / Bug

Steam bucket you need to make to unlock advancement in age 3 is locked as the age 5 item

## Current Behavior
as soon as I make a bucket of steam from a steam container I immediately drop said bucket.

## Possible Solution

Change the age restriction

## Context
minor issue but very glaring. 

## Your Environment
* Modpack Version: 3.0.3
* Java Version: 161
* Launcher Used: native
* Resourcepack Enabled?:
* Optifine Installed?:

**Comment by justinrusso** [comment]
https://github.com/Darkosto/SevTech-Ages/issues/796
