### ISSUE TITLE
Crash on world load?

### ISSUE THREAD

**Issue by ItsYaBoiMoose** [Darkosto/SevTech-Ages#1152]
## Issue / Bug
I can't log into my minecraft world, otherwise my screen flashes black for about 10 seconds, goes white, then about 5-8 seconds later it freezes and forces me to close minecraft. It just says the regular "Your game crashed, we're sorry for the inconvience" or something like that, without giving me a log or crash report or anything like such.
## Current Behavior
Still won't let me log into my world

## Context
This issue is affecting me majorly, as I am not able to play at all

## Your Environment
Crashed inside a darklands biome, hiding in a 3 block deep hole (call me a scrub)
* Modpack Version: 3.0.4
* Java Version: Java 8 64-bit
* Launcher Used: Twitch Launcher
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by artdude543** [comment]
We need logs to help with this; logs are **always** created. If you look in the install folder for the pack you'll see a `logs` folder. Please pastebin the latest client/fml log. Thanks.

**Comment by artdude543** [comment]
Closing this as we've not had any responses back in regards to the issue.
