### ISSUE TITLE
Coal coke 4x torch recipe conflict.

### ISSUE THREAD

**Issue by Gremilcar** [Darkosto/SevTech-Ages#1156]
## Issue / Bug

MM Chem mixer blueprint has an identical recipe to 4x torch recipe.

## Current Behavior

![](https://i.gyazo.com/517c0b6f4f917003cecd199d4048d5f2.png)

## Possible Solution

Change recipe

## Your Environment

* Modpack Version: 303
* Java Version: 161
* Launcher Used: native
* Resourcepack Enabled?:
* Optifine Installed?:

**Comment by Darkosto** [comment]
I've added blue dye to every blueprint recipe to stop the conflicts. Will be out in 3.0.4.
