### ISSUE TITLE
End dimension ore CTD

### ISSUE THREAD

**Issue by Gremilcar** [Darkosto/SevTech-Ages#1158]
## Issue / Bug

CTD while trying to look at an ore without texture in End dimension

## Current Behavior

- Entered age 4
- found fortress and entered the End (first time in this world (currently 3.0.3))
- found some blocks without textures spawned on the bottom of the end island
- when trying to take a closer look to identify CTD as soon as I got close enough to the block.

[CTD pastebin (WAILA NPE)](https://pastebin.com/jtG2GAuw)

## what causes actual CTD when looking at it up close

![](https://i.gyazo.com/372ee3645a47363b59eea1595f24362a.png)

## this is also present upon new terrain generation:

![](https://i.gyazo.com/ca07261043cae44c8a8b5aa5ea323973.png)

## Possible Solution

v0v

## Steps to Reproduce (for bugs)
check the underside of recently generated end islands?

## Your Environment

* Modpack Version: 3.0.3
* Java Version: 161
* Launcher Used: native
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by Gremilcar** [comment]
Update: when I logged back in, it appears that missing ores are now gone possibly defaulted to air.

**Comment by Gremilcar** [comment]
Additional info:

The newly generated terrain starts off with "no texture" blocks (pic1) as well as air gaps that were clearly solid blocks during some stage (pic2)

Upon relog, all (pic1) blocks turn into air and leave holes.

Biotite appears to be spawning only on the main island and all other large islands are only end stone for me at age 4. (unless that is intentional)


This is pure "vanilla Sevtech" 3.0.3 from Curse launcher.

**Comment by Gremilcar** [comment]
I can't comment whether (pic2) were present on the first island because I crashed as soon as I entered the End and saw the (pic1) which i decided to investigate

**Comment by Gremilcar** [comment]
Another update: - (pic2) are actually not air if you walk into them you start to jitter as if client sees it as air while server sees it as solid.

**Comment by Pandemoneus** [comment]
Had this happen in 3.0.2. However, I did not crash when looking at the blocks. I crashed when right-clicking them.

**Comment by Darkosto** [comment]
Looks like the cyclic update fixed this up. 3.0.5 will have this version, open up a new issue if you still experience it.

Thanks!
