### ISSUE TITLE
Can't launch class not found (Forge issue on Mac)

### ISSUE THREAD

**Issue by DrunkOctopus** [Darkosto/SevTech-Ages#1163]
My friend is on a Mac and he couldn't launch from the Minecraft launcher. I had him allocate more RAM (4-6gb), launch through Java, update java to 10.0 reinstall, repair, and reinstall the twitch launcher. No matter what we did this happened.
https://cdn.discordapp.com/attachments/160854612839104513/429472137317974026/Screen_Shot_2018-03-30_at_10.48.39_PM.png

He always crashes to this screen without a crash log. Any ideas are welcome!

* Modpack Version: 3.0.3
* Java Version: 9.0.4.4.0 x64 or 10.0 x64
* Launcher Used: Java or Native
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by artdude543** [comment]
Don't use Java 9 or 10 at all.  Back down to the latest version of 8 and try again.

**Comment by Darkosto** [comment]
Do not use java 9.
