### ISSUE TITLE
Wooden basin no longer functions

### ISSUE THREAD

**Issue by IWriteAnarchy** [Darkosto/SevTech-Ages#1164]
No matter what recipe I try to do in the wooden basin it does not work.
* Modpack Version: v3.0.3
* Java Version:1.80_25 64bit
* Launcher Used: Twitch/Native
* Resourcepack Enabled?:no
* Optifine Installed?:no
![issue](https://user-images.githubusercontent.com/37946862/38159142-858b9232-3470-11e8-9e44-c9d91e2028f0.png)

**Comment by muskabeatz** [comment]
Are you sure you have enough water for the recipe?

**Comment by IWriteAnarchy** [comment]
Yes I've both of these things. I even made a new basin as well.

**Comment by Ambaire** [comment]
Are you r-clicking it with an empty hand?

**Comment by IWriteAnarchy** [comment]
yes

**Comment by IWriteAnarchy** [comment]
I even reinstalled the pack and went into a single player creative world and tried the basin and it won't work their either.

**Comment by IWriteAnarchy** [comment]
Well it is working now. I am not sure why but it is. Thank you all for the help.
