### ISSUE TITLE
Crashed when shift-clicking an owl egg from inventory to hotbar

### ISSUE THREAD

**Issue by bherrington** [Darkosto/SevTech-Ages#1165]
Moved owl egg from inventory to hotbar. Was a shift-click to auto move it. Game immediately crashed. This happened during Age 0.

Pastebin crash log: https://pastebin.com/tbymu404

## Your Environment

* iMac 1.6 GHz i5; 8gb memory, 6gb assigned for Minecraft
* Modpack Version: 3.0.3
* Java Version: 8.161
* Launcher Used: Curse
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by Darkosto** [comment]
Have you been able to reproduce this? This looks like a java crash and not specifically a pack crash?

I tested it out and cannot reproduce the crash.
