### ISSUE TITLE
Blood does not show up on JEI in Age 1

### ISSUE THREAD

**Issue by tehMorag** [Darkosto/SevTech-Ages#1168]
## Issue / Bug
Blood does not show up on JEI in Age 1
It does show up in Age 2, 3, & 4

It can be used to get "Weak Blood Orb"
Rotten Flesh (x16 @40mb/each) -> Blood (via Melter) -> Congealed Blood Slime Block (via Casting Basin) -> Coagulated Blood (via shapeless crafting) -> Weak Blood Orb (via Blood Altar)

## Your Environment
* Modpack Version: 3.0.3

**Comment by Skullywag** [comment]
Im seeing all the blood stuff in JEI on Stage 1. On 3.0.3. Im doing all the blood magic/Abyssal starting stuff now.

**Comment by WonkyWobbler** [comment]
I can't find it either, I only have the option of a red block that I havn't discovered yet.
