### ISSUE TITLE
Player crafting dosent work

### ISSUE THREAD

**Issue by slendeboy88** [Darkosto/SevTech-Ages#1169]
### Before anything else, use the *search* feature!
 * Maybe someone already reported the issue you're experiencing?
 * Maybe you can find the answer to your question by looking at older or closed issues?
 * Have a go at it and see!
 * Please search on the [issue track](../) before creating one.
 
## Steps to Reproduce (for bugs)

1.
2.

## Your Environment

* Modpack Version:
* Java Version:
* Launcher Used:
* Resourcepack Enabled?:
* Optifine Installed?:

**Comment by Dystilled** [comment]
You need to actually put something in the info, you're providing literally nothing here.
