### ISSUE TITLE
Can not craft grass fiber mesh

### ISSUE THREAD

**Issue by slendeboy88** [Darkosto/SevTech-Ages#1170]
when I try to craft the grass mesh or making flint the player crafting grid doesn't work so am wondering is the crafting table not working with the fiber mod or whatever or was there an update I missed?

**Comment by justinrusso** [comment]
Working fine for me. What version of the pack are you in? What OS?
![image](https://user-images.githubusercontent.com/25138621/38163427-f7424406-34c1-11e8-9bd9-1fb106e65b84.png)

**Comment by mindofaprodigy** [comment]
im having the same issue on version 3.0.3 windows 10

**Comment by Drake0x** [comment]
Same issue, I have even tried downgrading the versions and a fresh install from the base release version upgrading to the latest; I am also on windows 10

**Comment by Drake0x** [comment]
Had the same issue but i seem to have gotten it working, I did a fresh install of the modpack from its base version than when it still never worked I updated it directly to the latest version, tried it again and it had started to work. 

I than tested on my original save and a new seed and it worked both times.

**Comment by Kuktar** [comment]
You have exceeded the maximum paste size of 512 kilobytes per paste.

i got that error using pastebin. the craftweaker log exceeds the max free limit by ten times almost :P just thought i would let you know.

**Comment by Kuktar** [comment]
https://pastebin.com/iQ8k3txZ

that is the pastebin. i just ended up setting up an account wich let me paste more than 512 kilobytes

**Comment by justinrusso** [comment]
Awesome.. thats useful. Do you have tombmanygraves installed and enabled?

**Comment by Kuktar** [comment]
ok so i just did a clean install and it installed version 3.0.3 i noticed thats not the latest. so i removed that and installed 3.0.4 and now everything is working. and i do have tombmanygraves installed :P. i am so exctied! yay flint lol. i hope others are enjoying this pack its flipping awesome! do yall have patreons?

**Comment by justinrusso** [comment]
Yeah.. Im not too sure why but it seems like the mod was missing or something odd happened. I would suggest anyone having this issue reinstall the modpack

**Comment by justinrusso** [comment]
@Kuktar I do not. Darkosto streams the development on twitch though. https://www.twitch.tv/darkosto

**Comment by slendeboy88** [comment]
thankyou people all had todo was reinstall the pack:D
