### ISSUE TITLE
Death Crash at respawn

### ISSUE THREAD

**Issue by Rene211** [Darkosto/SevTech-Ages#1171]
Hey i get a Crash every time i die after i click Respawn.

Crash Report: 

[crash-2018-03-31_11.34.46-client.txt](https://github.com/Darkosto/SevTech-Ages/files/1865337/crash-2018-03-31_11.34.46-client.txt)

**Comment by billybricker** [comment]
I had that as well when I was trying to fix a hunger issue. Apparently BWM water wheels don't like players dying near them for some reason. Supposedly it's fixed in the next version.

**Comment by artdude543** [comment]
This is fixed in 3.0.4 please update! 😄
