### ISSUE TITLE
Stabilized Metal Arc Furnace Recipe doesn't work

### ISSUE THREAD

**Issue by davqvist** [Darkosto/SevTech-Ages#1172]
## Issue / Bug
https://cdn.discordapp.com/attachments/329447198452482049/429600896201261068/2018-03-31_13.19.31.png

Not sure if I am doing something wrong here, but I can't make Stabilized Metal in an Arc Furnace. The Hardener doesn't go into the left side.

## Current Behavior
Nothing happens

## Steps to Reproduce (for bugs)
1.) Build an Arc Furnace
2.) Add 3 Graphite Rods
3.) Provide it with power
4.) Add in the recipe ingredients
5.) NO Profit

## Context
Needing the Stabilized Metal to order the Laser Program

## Your Environment

* Modpack Version: 3.0.3
* Java Version: 8 144
* Launcher Used: Jar Launcher
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by davqvist** [comment]
Iron Ingot has to go on the right side as well. Nvm

**Comment by DerpityDoo** [comment]
Lol thanks for this I was just as confused as you were
