### ISSUE TITLE
Tinkers Sharpening Kit

### ISSUE THREAD

**Issue by Burzi86** [Darkosto/SevTech-Ages#1174]
## Issue / Bug
I'm not sure if it is a bug, but it seems overpowered.
I have made a Tinkershammer:
Head = Iron
Plates = Copper + Stone
Handle = Wood

I thought you could only repair the tool with the material the head was made of.
But in this version I can use a stone sharpening kit to repair the hammer

## Your Environment

* Modpack Version: 3.0.3
* Java Version: v8 u161 (Build 1.8.0_161-b12)
* Launcher Used: MultiMC
* Resourcepack Enabled?: Soartex

**Comment by kragnoth** [comment]
No, that is correct.  Can repair with any head materials.  The plates are head parts.  One of your plates is stone.

**Comment by Burzi86** [comment]
Oh ok, then never mind =)
