### ISSUE TITLE
Completed Advancement without doing it. 

### ISSUE THREAD

**Issue by Snappiestjack** [Darkosto/SevTech-Ages#1177]
## Issue / Bug
Entering Age 2 auto completed 'Papers Please' advancement.

It's also a different colour, which means? This may be the intended behaviour if the colour is significant, however I' haven't found anything informing me of this.

![Auto Completed Advancement](https://imgur.com/JwA7iBD.png "Auto Completed Advancement")

## Environment
* Modpack Version: 3.03
* Java Version: 8 Update 144
* Launcher Used: Export from Twitch to MultiMC
* Resourcepack Enabled?: No.
* Optifine Installed?: Yes latest, this is the only mod change.

**Comment by artdude543** [comment]
Going to close this as it's an older issue. If you encounter the issue again please re-file an issue 🙂
