### ISSUE TITLE
Better With Mods Siding etc. rotation key conflict with Carry On pickup

### ISSUE THREAD

**Issue by benstrathdee** [Darkosto/SevTech-Ages#1178]
## Issue / Bug

Siding and Moulding from Better with Mods uses Shift + Right Click to rotate upon placement, but currently that results in the Siding/Moulding being carried if you're withing carry range

## Possible Solution

betterwithmods:wood_siding
betterwithmods:stone_siding
betterwithmods:wood_moulding 
betterwithmods:stone_moulding 

to be added to Carry On's block blacklist, fixes issue

**Comment by DaedalusGame** [comment]
i think axles, gearboxes, screwpumps and bellows have/had the same problem
detector blocks and lenses can also be rotated this way but i don't think you can make them in this pack

**Comment by random51** [comment]
Seems best to simply use a different key for Carry On. You can bind it to whatever you like in options.

**Comment by DaedalusGame** [comment]
unironically it should've been middleclick all along but apparently it's not possible

**Comment by Darkosto** [comment]
I added these to the blacklist, thank you for the report! Should be good for 3.0.5!
