### ISSUE TITLE
Disable Auto Fisher Since Fishing Loot Tables are Removed

### ISSUE THREAD

**Issue by Vyraal1** [Darkosto/SevTech-Ages#1179]
## Issue / Bug
- fishing loot tables are removed via a LootTableTweaker script making the Cyclic fishing net (and other auto fishers useless)

## Your Environment

* Modpack Version: 3.0.3

**Comment by cheesealmighty** [comment]
Duplicate of #1122

**Comment by Darkosto** [comment]
Removed, thanks!
