### ISSUE TITLE
No iron ore? cant find iron ore in age 2

### ISSUE THREAD

**Issue by Ultimaheart4** [Darkosto/SevTech-Ages#1183]
i have been having issues finding iron ore so i can continue in age 2. so far ive found rock crystal and gold. actually if found 8 gold veins, 3 lapis veins and 3 rock crystal veins. but i can not find any iron deposits on the surface. ive tried digging at iron lvl with regular strip mining techniques. maybe there is a bug were i just cant see iron deposits? but again ive had no luck finding iron even that way. i also have 2 other people playing on the server with me. neither of them can find iron ore or while following me they havnt seen any iron deposits. they are at the same age and progression as me. maybe im just missing something for the age?
![image](https://user-images.githubusercontent.com/29152256/38165009-3980bc62-34db-11e8-86a8-68ad67c93f7b.png) this is a screen shot of my map. all of the red marks are ore deposits ive confirmed. ive also found a lot of copper, tin, and coal. wondering if its because this world is from before 3.0.3? or if there is another issue? i was also able to detect bauxite with the dowsing rod for age 2? but havnt been able to see said ore. only a lot of salt in the location for bauxite. 

![image](https://user-images.githubusercontent.com/29152256/38165104-57fcf614-34dc-11e8-9ce5-a28f1cc09364.png)

this is a picture of my age tab for age 2 and what ive completed. if i understand the mechanics of this pack i should be able to see iron deposits from the start of age 2? well i hope this is being worked on but ive heard mentions that i shouldve found iron by now if i have already found gold and rock crystal. (cant even mine rock crystal with stone pick.)

**Comment by MyApolloGees** [comment]
Ore is known to be a little off and not spawning correctly in 3.0.3 and has been adjusted for 3.0.4 (Hopefully today). Although by the sounds of it you just got unlucky with RNG i spent hours trying to find Rock Crystal but found iron within 10 mins.

**Comment by Ultimaheart4** [comment]
wow thats completely backwards to me. XD i might have to make a new world with next update
hopefully today

**Comment by MyApolloGees** [comment]
You wont need too if you have chunks that havens been loaded those chunks will have the new ore gen. For me i will be generating the new chunks in the Twilight forest.

**Comment by Ultimaheart4** [comment]
well i have traveled much farther then id like to walk for normal iron ore... so im not so sure keeping this world would help XD

**Comment by MyApolloGees** [comment]
You could also delete the region files that arent your base this would cause all the other chunks to reload and the new chunks would be of the new ore gen although im not entirely sure how you locate the files that are youre base.

**Comment by Targren** [comment]
I found myself in exactly the same boat. I finally found iron after about 5 hours/50k chunks of wandering, about 3km away. Instead of rolling an entirely new world, I used "MCEdit" to prune everything except for my base and the village next door. Once the update drops, I'll be able to load it up and start generating fresh chunks. If you try make sure you make a world backup first.

**Comment by Ultimaheart4** [comment]
wow yeah 3km away isnt prime for the server ^^' especially if i want others to join and not be deterred from getting iron later on. so do i have to generate new chunks every time i unlock new ores? copper and tin and coal didnt seem like i needed to do it for them.
i even found gold near my copper mine.

**Comment by MyApolloGees** [comment]
No you wont the ores are just hidden until they update because of achievements

**Comment by Targren** [comment]
It's not very good for single-player, either! By the time I found it,  I'd been wandering so long looking for it that my pack was full of other ores from surface samples, wolf meat and pelts, and a pile of other stuff, so I would have had to mark the area, go home, dump my loot, and hoof it all the way back. Decided I needed a break before the rage one, and that's where I saw the comment about the broken oregen.

You shouldn't have to do it more than the one time after the update, unless something else changes in the worldgen.

**Comment by Ultimaheart4** [comment]
well for the distance they currently are if i do find iron at the edges of my current world gen borders i might aswell reset world/mc edit the crap out of it. but iron will most likely be required for a lot of things going forward. and new groups would have horrible times.

**Comment by daddy77gaming** [comment]
you just need a few hematite tbh.. as in twilight regular iron ore spawns (as does redstone,lapis gold etc..) keep a few at hand for special crafting recipies, also you can smelt the iron armor from mobdrops ( mobfarm)

**Comment by Ultimaheart4** [comment]
hmmm that is interesting idea. and i figured with twilight it would be regular spawns. since most modpacks are unable to change ore gen in twilight. including greg. XD

**Comment by Lyriox** [comment]
Does anyone know when the update will drop i have axactly the same problem i traveld in every direction about 5k block its so frustrating xd

**Comment by justinrusso** [comment]
3.0.4 is out. If you are still having an issue, you are blind or have really really bad luck :P
