### ISSUE TITLE
Recipe Conflict for Smelting Soul Sand

### ISSUE THREAD

**Issue by davqvist** [Darkosto/SevTech-Ages#1184]
## Issue / Bug
https://i.imgur.com/L5dbA2l.png

Smelting Soul Sand has two results. I am getting the Primal Core one but need the Natura one for Quartz Glass

## Current Behavior
I am getting the wrong Soul Glass.

## Possible Solution
Delete the Primal Core Soul Glass recipe

## Steps to Reproduce (for bugs)
1.) Smelt Soul Sand
2.) Get the wrong Soul Glass

## Context
I want Quartz Glass to make an ME Terminal but I can't

## Your Environment

* Modpack Version: 3.0.3
* Java Version: 8 144
* Launcher Used: Jar
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by Targren** [comment]
Could also make the quartz glass recipe accept either soul glass, no?

**Comment by Darkosto** [comment]
This was assigned the incorrect type of glass. It's meant to take all ore:blockGlass but is set to ore:glass instead. Will be fixed in 3.0.4.
