### ISSUE TITLE
Flint dropped upon breaking gravel

### ISSUE THREAD

**Issue by psrcek** [Darkosto/SevTech-Ages#1185]
## Issue / Bug
I remember reading somewhere that flint shouldn't drop when you break gravel in this pack.

## Current Behavior
Gravel sometimes gets converted to flint.

## Steps to Reproduce (for bugs)
Break gravel.

## Your Environment
* Modpack Version: 3.0.3
* Java Version: Server: 1.8.0_144, Client: 1.8.0_162
* Launcher Used: MultiMC 5 (0.6.1)
* Resourcepack Enabled?: The font is changed, but no resourcepacks are visible in the options.
* Optifine Installed?: false
* Client: Anarchy Linux - 4.15.11-1 - Intel Core I7 8700K (OC @ 4.7 GHz)
* Server: Arch linux - 4.15.2-2 - Intel Xeon X5690 (@ 3.47GHz)

**Comment by Darkosto** [comment]
It does drop from blocks but it's inconsistent. It's not really a bug that it drops, it's just annoying that you can't do it every time. That's the reason the player is given a different method.

**Comment by psrcek** [comment]
![image](https://user-images.githubusercontent.com/13370323/38166689-532e67ca-3528-11e8-89cb-142096e00ba7.png)
What's this nonsence then?

**Comment by Darkosto** [comment]
"What's this nonsence then?" 

Again, it's literally done to provide the player with a consistent way not a way based on RNG. Not a bug, just a way to let the player know where they can get it every single time. 

I don't care that it drops from some blocks.

**Comment by psrcek** [comment]
It literally says "Flint **WON'T** drop" in the popup, the text is misleading. I understood the first time what the reason was that flint was dropped.
