### ISSUE TITLE
Can't open chest in 1 age

### ISSUE THREAD

**Issue by Nili06** [Darkosto/SevTech-Ages#1189]
When i trying open the chest nothing happens

**Comment by Targren** [comment]
You don't have a solid block above the chest, do you? 

Silly question, maybe, but after playing so many modpacks with tweaks to bypass that restriction, that one bit me, too.

**Comment by justinrusso** [comment]
Are you on a server?

**Comment by Troxa2005** [comment]
i have the same Issue and i'm playing in Single Player

**Comment by Nili06** [comment]
In singleplayer

**Comment by Troxa2005** [comment]
i had Optifine in the pack, i removed that and updated to latest Version of the pack and now it works again...

**Comment by Nili06** [comment]
Thanks Troxa2005
I delete Optifine. Then i could open the chest
