### ISSUE TITLE
Other player on server crashing from windmill

### ISSUE THREAD

**Issue by randomlypickedname** [Darkosto/SevTech-Ages#1190]
## Issue / Bug
I have had a windmill attached to a gearbox attached both correctly and incorrectly (to disable it in act 1) and another player on our server repeatedly crashes with [this crash report](https://pastebin.com/mgHNxPZZ). He has tried both with and without Optifine, and has tried reinstalling the modpack. I haven't had any issues with the windmill either.

## Current Behavior
Player will be near my area and will sporadically crash after a random length of time.

## Your Environment

* Modpack Version: 3.0.3
* Java Version: 8u161
* Launcher Used: ATLauncher for both parties
* Resourcepack Enabled?: N
* Optifine Installed?: Y/N

**Comment by jasondm** [comment]
I see Java 1.8.0_101, can you make sure the player has the latest version of java (1.8.0_161) installed and the launcher is set to use it?

**Comment by randomlypickedname** [comment]
Had him update his version, skipped right over that. However, he still crashes: https://pastebin.com/ARrKRseG

**Comment by jasondm** [comment]
Is he still in age 0? Could you try breaking the gearbox and having him rejoin, and see if replacing it causes the issue again? Possibly restart the server in between breaking and replacing it.

**Comment by ArbitraryHubris** [comment]
In 3.0.4 there is an updated version of Better with Mods that is supposed to resolve this.  I updated my server and had the community update their clients and we haven't had the windmill/waterwheel rendering crashes since.

**Comment by randomlypickedname** [comment]
Noted, I'll update the server and reopen this issue if the problem returns. Thanks, both of you.
