### ISSUE TITLE
Weedwood bucket burn time issue

### ISSUE THREAD

**Issue by vallre** [Darkosto/SevTech-Ages#1191]
In the version 3.0.3, weedwood bucket has 75000 burn time and can be used to generate infinite amount of RF in coal generator from Actually Additions and generator from Integrated Dynamics. When it placed in the fuel slot, the generator starts generating power, but the bucket is not consumed and can be pulled out for reuse. Also can be used to infinitely fuel a vanilla furnace and any other solid fuel furnace (also works in heaters from Tinkers). The bucket only consumed in dual and single sulfur furnace from the Betweenlands, petrified fuel generator from Industrial Foregoing, simple combustion generator from Simple Generators, and fuelwood heater from Mekanism, but still provides an enormous amount of burn time.

**Comment by justinrusso** [comment]
Nice find 👍

**Comment by benstrathdee** [comment]
To add, the Syrmorite bucket seems to have the same issue.

**Comment by justinrusso** [comment]
Yeah. Both buckets from betweenlands have this issue.

**Comment by TheCyberBrick** [comment]
New update is now available that should fix this

**Comment by justinrusso** [comment]
Updated to https://minecraft.curseforge.com/projects/angry-pixel-the-betweenlands-mod/files/2548656

Will be in 3.0.5

**Comment by justinrusso** [comment]
This seems to be an issue still

**Comment by justinrusso** [comment]
Looks like pre-existing buckets just need to be `updated` either with being taken out of the furnace or used as a bucket. Afterwards it doesnt get used as fuel
