### ISSUE TITLE
Game randomly crashs on occasion

### ISSUE THREAD

**Issue by lbjodom** [Darkosto/SevTech-Ages#1195]
[crash-2018-03-31_18.00.35-client.txt](https://github.com/Darkosto/SevTech-Ages/files/1865974/crash-2018-03-31_18.00.35-client.txt)
### Before anything else, use the *search* feature!
 * Maybe someone already reported the issue you're experiencing?
 * Maybe you can find the answer to your question by looking at older or closed issues?
 * Have a go at it and see!
 * Please search on the [issue track](../) before creating one.
 
## Steps to Reproduce (for bugs)

1.
2.

## Your Environment

* Modpack Version:
* Java Version:
* Launcher Used:
* Resourcepack Enabled?:
* Optifine Installed?:

**Comment by sarcastic6** [comment]
That looks like the Better With Mods water wheel crash; 3.0.4 is supposed to resolve that.

**Comment by justinrusso** [comment]
As @sarcastic6 said, please update to 3.0.4.
