### ISSUE TITLE
World crashed after a death, now i cant even load the world.

### ISSUE THREAD

**Issue by Ebullio** [Darkosto/SevTech-Ages#1197]
So had a crash right after i died, dont remember from what, but when i spawned back in my spawn chunk for some reason wasnt loaded, so it put me half way into the dirt and crashed, giving me this crash report https://pastebin.com/gvRxLmX2 .

now i cant load it up at all, it crashes before anything pops into existence, it loads me in but all i see is the initial chat log text from mods and such and then it crashes, leaving me with this crashreport https://pastebin.com/rXP2TqS1 . 

and yea i dont know what im looking for in those crash reports so i have no idea how to fix it, ive tried to reduce as much graphics and effects as possible before loading the world to reduce stress.

i have the minecraft crash log open but there is around 15k line, and i dont know what to look for.

**Comment by justinrusso** [comment]
This should be fixed in 3.0.4.
