### ISSUE TITLE
Cant open the betweenlands mortars gui

### ISSUE THREAD

**Issue by Diabiendo** [Darkosto/SevTech-Ages#1198]
Issue / Bug
The between-lands mortar GUI can't be opened

Current Behavior
the mortar is beeing picked up by the player because of the carry on mod

Possible Solution
Adding the between-lands mortar to the carry-on mods black list fixes it

Context
I was after the achievement "Freebies" in the "Craftman" tab as i wanted to complete all the achievements in the pack

Environment

* Modpack Version: 3.0.3, 3.0.4

**Comment by random51** [comment]
Keybind conflict with the mod that lets you pick up and move chests/neutrals. Change the keybind and you'll be able to shift-click into the mortar.

**Comment by TheCyberBrick** [comment]
I've changed opening the GUI to right-click and grinding to a simple left-click, so this won't be necessary anymore once we release the next update

**Comment by justinrusso** [comment]
Updated to https://minecraft.curseforge.com/projects/angry-pixel-the-betweenlands-mod/files/2548656

Will be in 3.0.5
