### ISSUE TITLE
[suggestion]A different way to get blue dye

### ISSUE THREAD

**Issue by ThatGravyboat** [Darkosto/SevTech-Ages#12]
can there be a different way to get blue dye so you can make cyan dye without needing lapis 
btw the cyan dye is needed to make the tea pot to make tea.
~Gravy

**Comment by Darkosto** [comment]
Yep! Gonna use Ferdinand's Flowers to do this, I just haven't gotten around to it yet.

**Comment by Darkosto** [comment]
Added some Ferdinand Flowers to be ground up into dye!
