### ISSUE TITLE
Wopper mk2 not inserting

### ISSUE THREAD

**Issue by Dawenzel** [Darkosto/SevTech-Ages#120]
## Bug
When using a "Primal_Tech" Wopper MK2 to input items through the top of a "Horse Power" horse grindstone/press/chopping block it won't let it through. Inserting through the side does work. It also pulls out the items correctly.

## Versions
- Sevtech Alpha4 MultiMC
- Minecraft 1.12.1
- Forge 14.22.1.2485
- Java x64 8u144
- HorsePower 2.5.7.51
- Primal_Tech 0.5.12.1

**Comment by vadis365** [comment]
Hello, I'm not sure if this a Primal Tech thing or a Horse Power thing, The Wopper Mk2 seems to work OK with other inventories from above, so I'll hazard a guess at HP's blocks perhaps not having the slots accessible from the top - Maybe something GoryMoon could check :)

**Comment by GoryMoon** [comment]
This is an issue with the wopper trying to input into the bottom of the blocks where you only can output.
The hasCapability and getCapability gets the EnumFacing Down when it's on the top, @vadis365

**Comment by vadis365** [comment]
fixed in next mod update.
