### ISSUE TITLE
Main quest lines not colored in 3.0.4

### ISSUE THREAD

**Issue by unclekakarot** [Darkosto/SevTech-Ages#1200]
Not a big issue but wanted to address it, in the new version 3.0.4 it reads
     * Colored the main quest lines to help players find the quest to unlock new stages

Updated the server I play on with friends and none of our main quest lines are colored any differently than the others. 

https://imgur.com/a/Fga40

**Comment by Darkosto** [comment]
I have confirmed updating a world does work and have seen multiple others with their advancements colored. Please confirm you've correctly updated your files.

**Comment by CrypticDivide** [comment]
What do you mean by colored the quest lines? Do you mean the names of the advancements, or the actual images on the advancement?

**Comment by sarcastic6** [comment]
I'm seeing the same issue on the server I run for a group of friends.  In SP, the colors are changed for both new and updated worlds.  On our server, the colors haven't changed for our updated world.  I haven't tried a new world on the server side yet, but I could if that would be helpful.

**Comment by ChunkierDrew** [comment]
Changed colors to the suggested colors in the server config and this is what i get on the server. https://imgur.com/a/jdER4

**Comment by LadyEloquent** [comment]
Here are the pictures I said I would provide

https://i.imgur.com/PITuOYj.png
https://i.imgur.com/AukxPQl.png

**Comment by LadyEloquent** [comment]
this was also taken from another person on the server.  it came up purple in chat but not in achievements.

https://i.imgur.com/CE3Uy3e.png

**Comment by unclekakarot** [comment]
I have just updated the server to the most recent server files that are on the AT Launcher and the main quest line still isn't colored in. I tested on the old world and a brand new world. The problem might be either something with multiplayer or it might just be the server files the AT Launcher give are messed up somehow.

Image of the old world: https://imgur.com/a/KVOGd
Image of making a brand new world on the server: https://imgur.com/a/CAHoA

**Comment by ArbitraryHubris** [comment]
I have the same issue with lack of new coloration of advancements on my upgraded world.  I followed the pinned instructions for upgrade in the pack discord server discussions channel.  @Darkosto

**Comment by Jandakast** [comment]
Can confirm this is an issue. Not sure if this is an issue with Better Advancements or Triumph though. Reported as issue to Better Advancements Dev(s) since they use github. Will look into making a bitbucket account to report the issue to the Triumph dev(s) as well.

**Comment by way2muchnoise** [comment]
As an FYI, I have talked to @Blargerist about this issue and we have a solution in mind for this.

**Comment by Blargerist** [comment]
Fixed with Triumph v1.10.2 and BnBGamingCore v0.7.0.

**Comment by unclekakarot** [comment]
Fixed in 3.0.5
