### ISSUE TITLE
Galaticraft Tin Canister has no recipe?

### ISSUE THREAD

**Issue by Pandemoneus** [Darkosto/SevTech-Ages#1201]
## Issue / Bug
I'm in stage four and I need the tin canister for several recipes, but it has no recipe itself.

## Improvements
If there is a hidden recipe for the tin canister, please describe it in the advancements.

## Context
I'm trying to craft the fuel loader, rocket engines or the oxygen concentrator, but all need the uncraftable tin canister.

## Your Environment
* Modpack Version: 3.0.4
* Java Version: 8u161
* Launcher Used: Minecraft Jar Launcher (via Twitch)
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by DearDeathDay** [comment]
Can confirm this is an issue preventing progression... Don't want to cheat anything in so please fix it soon. 
:<

**Comment by justinrusso** [comment]
The canister is indeed a default recipe, the stage for the recipe is just incorrect.

For this case, you can just trade the materials. 
![image](https://user-images.githubusercontent.com/25138621/38174328-8bf6fa92-3599-11e8-89b7-5ac6d1460951.png)
