### ISSUE TITLE
Ember Root Zoo - Mob Spawn Gating

### ISSUE THREAD

**Issue by Aethix1** [Darkosto/SevTech-Ages#1203]
## Issue / Bug

Ember Root Zoo mobs appear to be no longer gated and spawn in tutorial gate. 

Golems (Ice, Gem, Etc...) 
Dire Wolf
Cursed Creeper

Additionally - Karate Zombie spawning in Tutorial.  Not sure what mod this is from. 

## Possible Solution

Restore mob gating

## Steps to Reproduce (for bugs)

Created new world in 3.0.4 - wait for night & thunder storms. 

## Context

Not a game breaking issue and mobs are easy enough. Just not working as intended (unless changed on purpose but not in recent update logs) 

## Your Environment
* Modpack Version: 3.0.4
* Java Version: 1.8.0_161
* Launcher Used: Twitch (Default) 
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by Aethix1** [comment]
Here is a screen shot that I think has to do with the gating issue as well. 

https://i.imgur.com/a0uDR2J.png

Five shadow beast spawns right next to each other in the tutorial.

**Comment by Darkosto** [comment]
It wasn't announced in the changelog because those mobs have always spawned in the beginning of the game. There is no restoration to be done because the mobs you see are correctly spawning. I'm not sure what version you may be thinking of, but everything seems to be working as intended.
