### ISSUE TITLE
Water

### ISSUE THREAD

**Issue by steinjorn** [Darkosto/SevTech-Ages#1204]
Are oceans no longer infinite water sources? because the ocean in my world is no longer filling where i take buckets from.

**Comment by steinjorn** [comment]
The problem seems to be with deep oceans. Cant see it well, but i just grabbed a bucket and waited 20 seconds before screenshot.
![2018-03-31_21 35 37](https://user-images.githubusercontent.com/27919048/38168998-98e4f8d0-352b-11e8-8827-c8b6b07269d5.png)

**Comment by justinrusso** [comment]
👍 Hm, that seems like it would be an oversight. Will look into this

**Comment by Darkosto** [comment]
Edited the config to have the correct name for beaches and added a few more water type biomes. This should be fixed in 3.0.5.
