### ISSUE TITLE
[3.0.4] [Advancements] "Iron Sights" text lists incorrect Hematite Spawn Range

### ISSUE THREAD

**Issue by Targren** [Darkosto/SevTech-Ages#1206]
## Issue / Bug

According to the "Field Manual" in-game book, Hematite can be found between y=32 and y=60. The "Iron Sights" Advancement text says between y=42 and y=58.

## Current Behavior

Since I'm looking at the top of a hematite vein at y=34, (and because I peeked into the config file), I'm confident in saying that the Field manual is correct

## Possible Solution

Modify the advancement text. 

## Context

Players who don't think to point the divining rod downward might conclude the ore didn't generate if they go down to minimum y and don't find any. 

## Your Environment
* Modpack Version: 3.0.4

**Comment by Darkosto** [comment]
Fixed to 30-60 in the advancement text. Thanks!
