### ISSUE TITLE
[3.0.4] Nether ore issue

### ISSUE THREAD

**Issue by Gremilcar** [Darkosto/SevTech-Ages#1209]
## Issue / Bug

![](https://i.gyazo.com/4ab4400ae829fb670edf3e58a655c360.png)

## Current Behavior

It appears as possibly similar behavior as some of the ores in End #1158 

## Context

This was generated before but I will try to generate new terrain and see if it is actually air or invisible solid blocks.

## Your Environment
* Modpack Version: 3.0.4
* Java Version: 161
* Launcher Used: native
* Resourcepack Enabled?:
* Optifine Installed?:

**Comment by Gremilcar** [comment]
Confirmed - newly generated terrain has "fake air" ores that you can't walk into

**Comment by Darkosto** [comment]
This should be resolved using the latest Cyclic update. If it happens when 3.0.5 comes out please open up a new issue. Thanks!
