### ISSUE TITLE
Weird Iron Problems

### ISSUE THREAD

**Issue by tapegreen** [Darkosto/SevTech-Ages#1214]
On any of my pre-generated areas their is no iron or gold, but lapis is their. When ever I generate a new area the iron and gold seem to be present then.

**Comment by Dystilled** [comment]
May be due to the ore spawn issues of previous builds, have you tried regenning your world in MCEdit?

**Comment by justinrusso** [comment]
You are just having bad luck then. 3.0.4 increased these frequencies as well, so you may have more luck in newly generated chunks
