### ISSUE TITLE
Stardust Acheivement

### ISSUE THREAD

**Issue by tapegreen** [Darkosto/SevTech-Ages#1215]
The Stardust achievement doesn't specify that the samples can only be found in the desert. I only found them their but if its at other places as well then maybe the RNG needs to be increased, as their very rare, and only 1 at each spot.

**Comment by Dystilled** [comment]
They aren't only found in the desert. 

Pretty sure frequency was tuned in the update last night also. They're a rare ore.

**Comment by justinrusso** [comment]
1. They can be found anywhere
2. 3.0.4 increased the rate at which they will be generated
