### ISSUE TITLE
Improved Backpacks - No Tooltips with an open backpack

### ISSUE THREAD

**Issue by Dystilled** [Darkosto/SevTech-Ages#1217]
## Issue / Bug
No tooltips for items when you have an IB Backpack open- My backpack is Tier1 Brown

## Current Behavior
No Tooltips. 

## Possible Solution
Mod Issue/Conflict?

## Steps to Reproduce (for bugs)
Have a IB Backpack and items in your inventory, open IB Backpack - No tooltips

## Context
Can't tell what items are when working out what to move to backpack or to try and find an item in backpack. 

## Your Environment

* Modpack Version: 0.4
* Java Version: 8.2
* Launcher Used: Twitch
* Resourcepack Enabled?: Soartex Fanver
* Optifine Installed?: Yes

**Comment by justinrusso** [comment]
https://github.com/Darkosto/SevTech-Ages/issues/604
