### ISSUE TITLE
Blood Magic  - Master Routing Node recipe broken

### ISSUE THREAD

**Issue by 3jlowes** [Darkosto/SevTech-Ages#1218]
## Issue / Bug

I am currently using SevTech version 3.0.4 and the master routing node is uncraftable. I have enough minimum will and the items are incorrect slots. Nothing happens.

https://gyazo.com/d8de002b8e3f99a644969bd32d8e4205

## Current Behavior

Nothing happens instead of crafting the master routing node

## Steps to Reproduce (for bugs)

1. Use hellfire forge with recipe
2. Nothing

## Context

I am trying to accomplish an automated blood altar for slate production

## Your Environment

* Modpack Version: 3.0.4
* Java Version: 1.8.0_25
* Launcher Used: Twitch
* Resourcepack Enabled?: no
* Optifine Installed?: yes

**Comment by gekkobear** [comment]
Verified, in age 3 on 3.0.5,
Master routing node uncraftable with platinum ingot, even with sufficient will in a gem.

I happened to have a diamond (Astral Sorcery Aevitas Attunement makes ores spawn in stone).
And it did craft when I shift-clicked a diamond into place.

So it can be crafted in Age 3, but not with the platinum ingot as listed.

**Comment by artdude543** [comment]
Seems this working in 3.0.7 maybe with an update to BloodMagic so looks like this will be resolved!

![image](https://user-images.githubusercontent.com/1885466/39142139-abaa9ecc-4721-11e8-9192-d46561898fd6.png)
