### ISSUE TITLE
Drilling for Oil - I cannot seem to bucket oil

### ISSUE THREAD

**Issue by 3jlowes** [Darkosto/SevTech-Ages#1219]
## Current Behavior

I cannot bucket oil, instead of producing oil from immersive petroleum I get a pink liquid (I assume its filler texture for missing texture) and I cannot take a bucket of it from any tank
https://gyazo.com/76ed3994cd52af912154fec571b0eb5b

## Possible Solution

Not really sure

## Steps to Reproduce (for bugs)

Reproduction for me was just creating a freshly generated world on 3.0.4 and unlocking all advancements and the Drilling for Oil advancement still shows pink fluid.

## Context

This issue has affected me because I cannot progress farther in the modpack and or seek better power options than water wheels and windmills.

## Your Environment

* Modpack Version: 3.0.0 - 3.0.4
* Java Version: 1.8.0_25
* Launcher Used: Twitch
* Resourcepack Enabled?: no 
* Optifine Installed?: yes

**Comment by justinrusso** [comment]
Very odd. No one else has reported this issue, and as long as the world was made in 3.0.0, it should have been fine.

**Comment by Darkosto** [comment]
When did you start your world? After release? or before official release?

**Comment by justinrusso** [comment]
![image](https://user-images.githubusercontent.com/25138621/38176303-6ab0c54a-35ba-11e8-858c-580dae4acc2d.png)
