### ISSUE TITLE
visual bug with item interaction with skill mod

### ISSUE THREAD

**Issue by sunsetwhiskey** [Darkosto/SevTech-Ages#122]
just loaded up alpha 4 , started new world. when i went to place vanilla seeds in ic chest it gave me visual error of not meeting level requirements to use item. but item does get placed.  did a little more playing around and any item that you dont meet the requirements to use it flashes on screen when you put in world inventory chest or work stump.  couldnt find any other issue reporting this.

ie putting minecraft seeds in imersive craft chest or putting iron pickaxe in work stump and or chest

**Comment by Darkosto** [comment]
Should be good by now :)
