### ISSUE TITLE
betweenlands portal glitch 

### ISSUE THREAD

**Issue by DesertfoxAlpha** [Darkosto/SevTech-Ages#1221]
### Before anything else, use the *search* feature!
 * Maybe someone already reported the issue you're experiencing?
 * Maybe you can find the answer to your question by looking at older or closed issues?
 * Have a go at it and see!
 * Please search on the [issue track](../) before creating one.
 
## Steps to Reproduce (for bugs)

1.
2.

## Your Environment

* Modpack Version:
* Java Version:
* Launcher Used:
* Resourcepack Enabled?:
* Optifine Installed?:

**Comment by DesertfoxAlpha** [comment]
on the achievement (the betweenlands) it states to go to a druid circle get the parts make the swamp talisman then use that talisman on a placed sapling ive dont these steps and did not recieve the achevemnt nor dose the portal work but i did get the portal tree to spawn there for im lost on what to do or is this a glitch in the pack

**Comment by justinrusso** [comment]
You have ignored the issue template and given us zero information...
