### ISSUE TITLE
[3.0.3] Cannot excavate geoloysis ores

### ISSUE THREAD

**Issue by togreglove** [Darkosto/SevTech-Ages#1222]
## Issue / Bug
Cannot Ore Excavate ores.
Added Ore Excavation Modifiers (x25) to Iron Headed Tinker's pick.
Attempted to Excavate a Malachite vein.
Mined one ore. (Yes, I used the modifier key)
Turned to a piece of stone, attempted to excavate, got tons of stone.
Tried Malachite again, got one ore.
Tried setting to 3x3 and 5x5, still got one ore.

Should excavate large amounts of ore.

**Comment by justinrusso** [comment]
Ive tried this with and without silk touch and cannot replicate this

**Comment by Darkosto** [comment]
It does and I've tested this along with watching multiple people also excavate ore. 

This sounds like you are not correctly using the mod. We also need confirmation.

**Comment by togreglove** [comment]
Tried after update to 3.0.4 and it works now. Must have been an incidental fix of rsomething wrong with my session. Thanks for your attention.
