### ISSUE TITLE
Recipie for Torches using Coal Coke not working(conflicting)

### ISSUE THREAD

**Issue by MCEventHorizon** [Darkosto/SevTech-Ages#1225]
Recipe for torch:
![2018-04-01_12 11 20](https://user-images.githubusercontent.com/15619786/38172150-2194ab14-35a7-11e8-9169-b236bc38d570.png)
What I get:
![2018-04-01_12 11 26](https://user-images.githubusercontent.com/15619786/38172155-333decae-35a7-11e8-8f72-ae0c4e0ebabd.png)

* Modpack Version: 3.0.4
* Java Version: 1.8.0_161
* Launcher Used: Twitch
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by justinrusso** [comment]
https://github.com/Darkosto/SevTech-Ages/issues/1156
