### ISSUE TITLE
Coralium not spawning.

### ISSUE THREAD

**Issue by WonkyWobbler** [Darkosto/SevTech-Ages#1226]
## Issue / Bug
 Coralium ore should spawn when reaching the correct advancement.

## Current Behavior
 Coralium ore doesn't spawn/render in when the reaching the appropriate advancement. We're a group of 10 players that I have mined out 5 different biomes (Swamp, Ocean and infested swamp), 3 of the biomes were rendered into the server AFTER we unlocked it.

## Steps to Reproduce (for bugs)
1. Complete the Abyssal Trophy Case advancement, which unlocks "The Beneath", "Pedestalling for Time", and "I can't find a jungle?" where Coralium is meant to start rendering in/become visible for the players ( as it is needed for the next advancements)
2. Coralium doesn't spawn

**Comment by Ultimaheart4** [comment]
i believe you have to find that bight swampy area(?) they only spawn in those biomes under the ground.

**Comment by Darkosto** [comment]
I can confirm with absolute certainty it does spawn. The best place to look is in an ocean biome. This pack has even doubled the default generation and I have tested whether or not it works multiple times. Whether or not biomes were generated after reaching the correct stage does not matter, the ore always exists whether you can see it or not.

Also, not @Ultimaheart4 that's not the modpack causing those texture issues you see that would be Minecraft's April Fools textures. It has nothing to do with us.

**Comment by Ultimaheart4** [comment]
yeah sorry i wasnt sure untill i realized its also april fools. i wish there was an easy way to turn off holiday events just for days like today though.

**Comment by Dystilled** [comment]
Coralium also seems to spawn quite commonly in the twilight forest. Ended up with over a stack of it when exploring a Minotaur Maze
