### ISSUE TITLE
Gast sound in overworld

### ISSUE THREAD

**Issue by crocman** [Darkosto/SevTech-Ages#1228]
Hi

I am currently playing a map where I am getting the sound of a gast shooting its ball at me even though I am in the overworld. Its constant and only happens at my base. 

Still on 3.03 because server company has not updated the server yet. 

* Modpack Version: 3.03
* Java Version: 1.8.0_161
* Launcher Used: Twitch
* Resourcepack Enabled?: SEUS Shaders
* Optifine Installed?: Yes

### Before anything else, use the *search* feature!
 * Maybe someone already reported the issue you're experiencing?
 * Maybe you can find the answer to your question by looking at older or closed issues?
 * Have a go at it and see!
 * Please search on the [issue track](../) before creating one.
 
## Steps to Reproduce (for bugs)

1.
2.

## Your Environment

* Modpack Version:
* Java Version:
* Launcher Used:
* Resourcepack Enabled?:
* Optifine Installed?:

**Comment by Rixxaw** [comment]
Do you have a Filtered Hopper my man?  Cuz it generates that sound when you throw stuff into it with soul sand.

**Comment by crocman** [comment]
No, I havent even done hoppers yet, just started.

**Comment by Targren** [comment]
I have a similar experience with random sounds. Usually its a ghast fireball like you hear, or the locomotive sound that turned out to be the noise the millstone makes. Not sure if it's some sort of ambient sound to mess with us, or what.

**Comment by artdude543** [comment]
This is intended with some the mods (mainly Better with Mods) but this is intended so it's not an issue/bug.
