### ISSUE TITLE
Game crashing randomly

### ISSUE THREAD

**Issue by Imperiex** [Darkosto/SevTech-Ages#1229]
Game is crashing at random times. Screen goes grey/blue/solid color then crashes.

The game crashed whilst unexpected error
The game crashed whilst unexpected error
Error: java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=axis, clazz=class net.minecraft.util.EnumFacing$Axis, values=[x, y, z]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}

[Crash Log](https://github.com/Darkosto/SevTech-Ages/files/1866310/crash-2018-03-28_22.39.07-client.txt)

**Comment by muskabeatz** [comment]
How much RAM did you have allocated to minecraft?

**Comment by HighlanderSteve** [comment]
I've been having the same problem - 10GB allocated.

**Comment by justinrusso** [comment]
3.0.4 fixes this issue.
