### ISSUE TITLE
fire pit cooks faster the more burnable material is in it

### ISSUE THREAD

**Issue by sunsetwhiskey** [Darkosto/SevTech-Ages#123]
when cooking in just the fire pit. if you spam click fuel in it, it reduces cook time to almost nothing.

things i did.

placed two fire pits a few blocks away, put raw mutton in each one, clicked coal on fire pit #1, clicked coal on fire pit #2, 3 times. Can cook mutton in about a second on fire pit 2, fire pit 1 takes 10 seconds.  Tried with coal and the more you click the faster the meat cooks.
tried with chicken, mutton, fish, porkchop.
when only clicking once you can cook multiple meat on a single coal, when you add 2 or more coal it goes out after you get cooked meat off

**Comment by sunsetwhiskey** [comment]
after putting grill on top found this is related to issue #47 
if you spam fuel in fire pit the meat cooks faster in pit (not on grill that timing is correct). 
fuel usage is increased so if you put 10 blocks of coal, the fire goes out before anything is cooked on grill (but items in fire pit cook instantly)

**Comment by vadis365** [comment]
#BlameTurkey

**Comment by Darkosto** [comment]
Hey @turkey2349, does the firepit just add on top of the previous values when inserting more and more stuffs?

**Comment by Turkey2349** [comment]
I will find out!

**Comment by Turkey2349** [comment]
Look into the new build of the mod and let me know if that has fixed it

**Comment by justinrusso** [comment]
@Darkosto This seems fixed. I've tried 1 or 64 coal, and the speed of the cooking does not change. Thanks @Turkey2349 ! 👍
