### ISSUE TITLE
Diesel Generator missing GUI (bug)

### ISSUE THREAD

**Issue by kugamer** [Darkosto/SevTech-Ages#1230]
The diesel generator is missing gui, you cannot interact with it to see how much fuel is in it. The gui's for the steam generator and distilation tower works now! Thankyou

Modpack Version:3.0.4
Java Version:1.8.0_ 161
Launcher Used:twitch
Resourcepack Enabled?: faithul
Optifine Installed?: no

**Comment by justinrusso** [comment]
Did this ever have a GUI?

**Comment by justinrusso** [comment]
Yeah, I dont think it did.
