### ISSUE TITLE
is this normal? 

### ISSUE THREAD

**Issue by Ultimaheart4** [Darkosto/SevTech-Ages#1231]
i logged into server today and this is how my screen looked like. no video settings were changed. 
![image](https://user-images.githubusercontent.com/29152256/38173255-13e9c45e-3589-11e8-9659-df2ede01ce0b.png)

still in version 3.0.3

hmm and this happens when going between the between dimension and overworld. 
![image](https://user-images.githubusercontent.com/29152256/38173292-cb2a6362-3589-11e8-979c-952d7999d147.png)
whats more interesting about this is its just vanilla minecraft textures that now look like crap.

**Comment by syrun97** [comment]
That is "April Fool" of vanilla minecraft.

**Comment by Ultimaheart4** [comment]
well thats nice but the fences turning into blocks was a thing yesterday and it may be a bug since it only happens to some fences... but also how do i change my textures back. its quite annoying...

**Comment by muskabeatz** [comment]
Get a resource pack?! How can you play with vanilla minecraft textures? Low pc/ram?

**Comment by Ultimaheart4** [comment]
32gb ram, i7 4.2ghz. just dont like mixing textures with modded minecraft. and most dont work if i wanted to do realistic "textures"
this pack is quite a lot for any computer. lol

**Comment by muskabeatz** [comment]
Eh... i can run this modpack on my laptop. i7 7700HQ, 16GB RAM, NVidia 1050 Ti, and it runs in 60 fps with Soartex Fanver + Soartex Fanver Modded, Optifine, with Sildurs Vibrant Shaders v1.17 High. It gets quite hot, and it's a bit sad.. but if you are on PC... then thermals shouldn't be a problem.
