### ISSUE TITLE
weird movement of hands on 3rd person mode

### ISSUE THREAD

**Issue by syrun97** [Darkosto/SevTech-Ages#1232]
## Issue / Bug

Is this intended vanilla prank or glitch?
## Current Behavior

legs and arms goes mad on 3rd person mode, when view bobbing is on, screen goes mad when move.
https://youtu.be/cg6v3b7ObNs (blaming my potato PC (for using bandicam) and github doesnt supporting mp4)
## Possible Solution

disable veiw bobbing to partially fix problem, but can't fix legs and arms.
## Steps to Reproduce (for bugs)

1.what
2.made
3.this?

## Your Environment

* Modpack Version:RECENT(3.0.3) w/o AESTHETIC mods(Better foliage, fancy block particle, Mo'Bend, player skin mobs, smooth font)
* Java Version:1.8.0_161 x64
* Launcher Used:vanilla launcher jvm: -Xmx5G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -Dminecraft.applet.TargetDirectory="MINECRAFT DIRECTORY(not real derectory)" -Dfml.ignorePatchDiscrepancies=true -Dfml.ignoreInvalidMinecraftCertificates=true -Duser.language=en -Duser.country=US
* Resourcepack Enabled?:vanilla resoecepack(with mojang's prank)
* Optifine Installed?:no optifine

**Comment by Darkosto** [comment]
Disabled better fps.

**Comment by RealCaptainindia** [comment]
You don't have to disable better fps just change the algorithm to Riven's Algorithm
