### ISSUE TITLE
Galacticraft Air Fan has no recipe

### ISSUE THREAD

**Issue by davqvist** [Darkosto/SevTech-Ages#1233]
## Issue / Bug
Unless I am missing something to make fuel you need oxygen. To make oxygen you need an Oxygen Collector. But the Oxygen Collector needs a Tin Canister which has no recipe (see https://github.com/Darkosto/SevTech-Ages/issues/1201) and an Air Fan which also has no recipe.

## Current Behavior
Air Fan which is required for the Oxygen Collector has no recipe.

## Possible Solution
Give the Air Fan a recipe or stage the current recipe to stage 4. Looking up the usual recipe from the Galacticraft wiki the latter is probably not possible as it needs a Wafer which needs the Circuit Processor which is gated to stage 5.

## Your Environment

* Modpack Version: 3.0.4
* Java Version: 8 144
* Launcher Used: Jar
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by Vyraal1** [comment]
Similar to the Tin Canister, on Line 589 of the `recipes.set.zs` is where the air fan is staged in Stage 5, where it should be available in Stage 4 in order to craft the GC components that use the air fan.

**Comment by Darkosto** [comment]
Alright, so. Here's what I did:

MOVeD the fan recipe back to stage 4 and created a I.E. refinery processing recipe using GC oxygen to make Rocket Fuel. This should fix the issue and let you make oxygen in stage 4 and also let's you fill oxygen tanks before going to the moon.

As an added bonus, I moved the Fluid Pipes from GC into stage 4. YOU ARE WELCOME!

**Comment by Vyraal1** [comment]
Hey just checking in this, is the wafer used for the oxygen fan also going to be moved to Stage 4 as well? Because moving the recipe to Stage 4 (assuming if it's the standard GC recipe) won't be enough, as the wafer is made from a Circuit Fabricator (also Stage 5) from Diamonds (also Stage 5).

Maybe have it use something else in Stage 4 instead of a wafer?
