### ISSUE TITLE
Sevtech : Ages Server Issue (Console Spam)

### ISSUE THREAD

**Issue by PebbyBoi** [Darkosto/SevTech-Ages#1234]
Hello, sorry to bother you all on Easter, but we just started to run this on our network as our newest mod-pack and the server is having some lag issues every now and again. It is a dedicated server and is definitely receiving enough ram, so I don't think that's the issue. However, we have been getting this message. Is there a chance that this might be causing it? I'm not too sure of it myself so I thought I'd ask here! Thank you for your time on reading this. I really appreciate it.

Console being spammed with:
[FML]: PrimalCore loaded a new chunk (-17, 210  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
Geolosys loaded a new chunk (-44, 202  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.

Anyone have any idea? :)

**Comment by Carmondai** [comment]
The lag you experience is worldgeneration based, I had the same problem on the network I do the server work for. You should consider pregenerating your worlds before launching a server to prevent these issues.

**Comment by Darkosto** [comment]
As @Carmondai commented: If you're running a server then using pregen is a good idea. That console information shows when you are generating chunks and some mods will cause that to show up.

**Comment by PebbyBoi** [comment]
Thank you guys for your help! :D

**Comment by artdude543** [comment]
This is intended logging from Forge and can be disabled in the Forge Config if you find it annoying :)

**Comment by Dan-Ross** [comment]
Apparently the latest version of PrimalCore addresses this lag (0.6.58). I'm going to try it tonight, as our server is hit really hard with the worldgen lag.

Maybe it'll make the cut into the next update for SevTech?

**Comment by ScottyPcGuy-03** [comment]
Did that help? I'm running in to the same issue.

**Comment by Dan-Ross** [comment]
Never wound up trying it, trying to get the players to update their pack manually was way too much of a pain. We stopped played the pack for the time being until it updates.

**Comment by ScottyPcGuy-03** [comment]
After updating Geolosys to v2.0 and PrimalCore to v0.6.58 the logspam has disappeared (I used Chunk-Pregenerator to test). It remains to be seen whether the updates will have any effect on the pack progression.
