### ISSUE TITLE
Can't use Glass to build Tinker Tank

### ISSUE THREAD

**Issue by Shock2k** [Darkosto/SevTech-Ages#1235]
![2018-04-01_06 45 58](https://user-images.githubusercontent.com/37946010/38173854-ff90bf78-35b3-11e8-909f-a98d94a1668c.png)
### Before anything else, use the *search* feature!
 * Maybe someone already reported the issue you're experiencing?
 * Maybe you can find the answer to your question by looking at older or closed issues?
 * Have a go at it and see!
 * Please search on the [issue track](../) before creating one.
 
## Issue / Bug
Constructed a 5x5x4 Tank (with glass) but it won't initialize.

## Current Behavior
When using glass to build any size Tinker Tank the tank won't initialize. (See .png attached... the right side is the tank I was attempting to build.  I also tried glass on the smaller tank to the left, and it would not initialize.)

## Possible Solution
Using all Seared Brick|Drains|Controller works. (See .png attached)

## Steps to Reproduce (for bugs)
Just build a tank with glass.

1.
2.

## Your Environment

* Modpack Version: 3.0.3
* Java Version: 1.8
* Launcher Used: Twitch
* Resourcepack Enabled?: Yes
* Optifine Installed?: Yes

**Comment by justinrusso** [comment]
There is a seared glass.. you have to use that

**Comment by Shock2k** [comment]
That resolved it.  Thanks for letting me know!
