### ISSUE TITLE
Chest Carrying

### ISSUE THREAD

**Issue by merciless571** [Darkosto/SevTech-Ages#1236]
### Before anything else, use the *search* feature!
 * Maybe someone already reported the issue you're experiencing?
 * Maybe you can find the answer to your question by looking at older or closed issues?
 * Have a go at it and see!
 * Please search on the [issue track](../) before creating one.
 
## Issue / Bug
When trying to open a chest when next to it, you pick it up instead of opening it. The chest can be opened if far enough away though.

## Steps to Reproduce (for bugs)
1. Stand one or two blocks away from the chest
2. Right click the chest

## Your Environment

* Modpack Version: 3.0.4
* Java Version:
* Launcher Used: Twitch
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by justinrusso** [comment]
Shift + Right click is opening a chest. You may have the shift key stuck for some reason.
