### ISSUE TITLE
BUG Betweenlands Mod Tar Minion duplicate

### ISSUE THREAD

**Issue by Rene211** [Darkosto/SevTech-Ages#1237]
If you push a Tarminion into the Betweenlands Portal it dies and drops as inanimate Tarminion. On the other side its alive and you can push him again and so on. 
So you can duplicate Inanimate Tarminons.

Would be kinda nice if you could pick them up again somehow....

Rene

**Comment by TheCyberBrick** [comment]
https://github.com/Angry-Pixel/The-Betweenlands/commit/901c546a7d6a44c1a99b2b5abfc14905dd338bd9

**Comment by justinrusso** [comment]
Updated to https://minecraft.curseforge.com/projects/angry-pixel-the-betweenlands-mod/files/2548656

Will be in 3.0.5
