### ISSUE TITLE
[Staging] Blood Magic Stage 2

### ISSUE THREAD

**Issue by iffonox** [Darkosto/SevTech-Ages#1238]
The following items are staged in stage 2, but requrire at least a tier 4 altar (I'm still in stage 2, so I can't check which tier exactly):

Rune of the Orb, Acceleration Rune, Worn Stone Brick Path, Tiled Worn Stone Brick Path, Sigil of Haste and Haste Reagent

SevTech version: 3.0.6

**Comment by ssinden** [comment]
Apparently the Tier 3 alter can be made with Sea Lanterns instead of Glowstone.  That makes it available in Stage 2.

**Comment by iffonox** [comment]
Yes, I saw it own Darkosto's stream yesterday.

This still leaves the items, that require an tier4 or higher altar.

**Comment by artdude543** [comment]
- Rune of the Orb: Fixed.
- Acceleration Rune: Fixed.
- Worn Stone Brick Path: Fixed.
- Tiled Worn Stone Brick Path: Fixed.
- Sigil of Haste: Fixed.
- Haste Reagent: Fixed.
