### ISSUE TITLE
Double Achievement

### ISSUE THREAD

**Issue by TheLemein** [Darkosto/SevTech-Ages#124]
Made the spear, and upon creation it gave me both "Spearmint" and "Spear Fishing"

**Comment by Crackerhead22** [comment]
Did you happen to kill a fish sometime before making the spear?  If so, the advancement system knows that you did part of the advancement, and was waiting for the parent advancement, Spearmint, to be completed.

**Comment by TheLemein** [comment]
It was a new map, and dont recall killing a fish prior as I never went into the water.

**Comment by TheLemein** [comment]
But I do remember finding a fish ground item in a cave for some reason, was not killed by me.

**Comment by Darkosto** [comment]
This SHOULD only complete the second one if the fish is killed before hand. But, I'll look into this some more.

**Comment by TheLemein** [comment]
Yeah, new map, made spear, got it again, never touched a fish, or even picked one up. glad I am not going too crazy

**Comment by Dawenzel** [comment]
Alright, I'm gonna close this issue for now because of 2 reasons.
1. Nobody has reported this bug again since +- Oct 10th 
2. After having not been able to reproduce the issue with multiple brand new worlds in Alpha 9
I'll reopen the issue if it's found again.

**Comment by VallenFrostweaver** [comment]
Not sure if it's even worth while but I got the "Spear Fishing" achieve by killing a fish with a flint work blade. It may be because I had the spear on my hotbar at the time. I figured it should be reported none-the-less if only for reference.
