### ISSUE TITLE
Astral Sorcery Mineralis and Aevitas Ritual provide later-game ores

### ISSUE THREAD

**Issue by Vyraal1** [Darkosto/SevTech-Ages#1240]
## Issue / Bug
- Not sure if this was intended or not, but the Astral Sorcery Mineralis ritual converts Stone to Ores similar to the Botania Orechid, which provides an renewable quarry for players (as early as Stage 2 to make the ritual, and automatable in Stage 3 with block breakers and placers)
![2018-04-01_00 08 46](https://user-images.githubusercontent.com/26587049/38174184-a4437c80-3597-11e8-9da1-826cca249c02.png)

-Staging still prevents the use of certain metals and ores, but these ores can still be gathered long before they are used
- There are config files in the astralsorcery configs folder under `mineralis_ritual.cfg`, a copy of that file is linked here: https://hastebin.com/uhexiviwoq.coffeescript

## Current Behavior
- I'm not sure what the expected behavior should be since I'm not sure on what the intentions are on having this ritual available

## Possible Solution
- You can either edit the ore dictionary entries in the configs so that only certain ores can be available, nerfing its use as a form of automatic quarry be culling the variety
- don't think there is a way to gate this ritual exclusively without also gating all of the other less powerful Astral Sorcery rituals

## Steps to Reproduce (for bugs)
- Make an Astral Sorcery Mineralis Ritual, the speed of the ritual is nearly uncapped, its only limited by how much starlight you can feed it

## Context
- It provides an early game quarry, if you're okay with this solution for ores, no need to do anything else.

## Your Environment
* Modpack Version: 3.0.4

Late Edit:
Blood Magic's Mark of the Falling Tower ritual also spawns in ores similar to Mineralis as well if you wanted to change that as well.

**Comment by justinrusso** [comment]
Yeah this is not intended...

**Comment by Waisse** [comment]
Aevitas attunement give players the same effect btw

**Comment by justinrusso** [comment]
From a dupe report: "In the astral sorcery config, line 161, you can control what ores spawn from this perk."

**Comment by talonos2** [comment]
In my defense, I DID search for Aevitas before filing the report. : P

Anyway, relevant config section from  astralsorcery.cfg:

`# List any number of modid's here and the aevitas perk & mineralis ritual will not spawn ores that originate from any of the mods listed here. [default: [techreborn]]
    S:oreGenBlacklist <
        techreborn
     >`

I see that in the astralsorcery/aevitas_ore_perk.cfg, you _did_ try to say what ores should/should not spawn, but I think it's pulling from the oredict instead of taking specific blocks, and galacticraft adds a bunch of oreDiamond entries, so AS is spawning those.

**Comment by justinrusso** [comment]
All good, thats why I adjusted the title 😃  Appreciate you looking into this!

**Comment by MechaDom** [comment]
I'd like to add, when mined with an autosmelting pickaxe the Galacticraft ores generated this way it gives you Galacticraft Ingots.  Since it's not intended I imagine this is a minor thing.
