### ISSUE TITLE
Cant get "Past the Thorns" advancement

### ISSUE THREAD

**Issue by DerpityDoo** [Darkosto/SevTech-Ages#1243]
I unlocked what I assume to be *the* door to the castle, but I didnt get the achievement. Perhaps I am missing something, if so please correct me, but otherwise it looks like a bug.

Image of door: https://imgur.com/a/TqccE

**Comment by DerpityDoo** [comment]
I also went to the top of the main boss tower and went through 1 mini-boss. Dunno if that matters

**Comment by Darkosto** [comment]
It's not a bug, the mod isn't finished and you can't complete the last few achievements for TF.
