### ISSUE TITLE
cave bug?

### ISSUE THREAD

**Issue by bozzDK** [Darkosto/SevTech-Ages#1245]
![cave](https://user-images.githubusercontent.com/34946254/38174655-ec13e930-35d0-11e8-9bc5-4d39bac62828.png)

When i am in a cave my game looks like this. It happened after i updated to 3.0.4 is is this a new feature?

**Comment by Darkosto** [comment]
What's the issue you're experiencing? I'm not seeing it.

**Comment by bozzDK** [comment]
The screen is getting darker in every circle after the center one.

**Comment by Darkosto** [comment]
Did you alter your video settings for shadows/light smoothing?

**Comment by bozzDK** [comment]
Nvm. found out its a April Fools prank from mojang :D 
https://www.minecraftforum.net/forums/minecraft-java-edition/recent-updates-and-snapshots/2897275-new-default-textures
