### ISSUE TITLE
Small charcoal to get to age 1?

### ISSUE THREAD

**Issue by Cstanley3752017** [Darkosto/SevTech-Ages#1248]
## Issue / Bug
The recipe to get crushed charcoal gives small charcoal from the manual millstone and the horse powered millstone for the final wooden hopper to get to age one and you need age one to use the crank to use the grinder so was not able to check if it was usable to get the crushed charcoal.
  
## Current Behavior
   The grindstone recipes give small charcoal (cant be used till after age 1) instead of crushed charcoal needed to complete the (flame grill wopper?) quest
## Possible Solution
 Make small charcoal usable in age 0 as the component to be ground down into pulverized charcoal 

## Steps to Reproduce (for bugs)

1.
2.

## Your Environment

* Modpack Version:
* Java Version:
* Launcher Used:
* Resourcepack Enabled?:
* Optifine Installed?:

**Comment by daddy77gaming** [comment]
What version are you using, cause is see manual millstone work fine to produce crushed charcoal.. The horse millstone is intended to produce small charcoals

**Comment by dmsaxon** [comment]
Appears to be an issue in 3.0.4 - gives 8 unfamiliar items, not the crushed charcoal I'd expect (and that is shown in JEI)

**Comment by daddy77gaming** [comment]
Just did manual millstone in both 3.0.3 and 3.0.4 and both give me crushed charcoal as a result, also JEI displaying correct recipe in both

**Comment by dmsaxon** [comment]
I stand corrected - I used the grindstone, not the mill stone.  Whilst I can't speak the original poster, this was my mistake - now going to find buffalo for the crank!  Apologies for the confusion!

**Comment by Cstanley3752017** [comment]
I am running 3.0.4 and you need stage 1 to use the hand crank and you need the crushed charcoal to get to stage 1

**Comment by Cstanley3752017** [comment]
Both the manual and the horse powered millstones is giving me tiny coal I am currently in 3.0.4

**Comment by ArcheKnight** [comment]
I have the same issue. I need charcoal dust to get to stage 1, but I can't craft the hand crank until I have a crafting table. Am I missing something?

**Comment by 3ygun** [comment]
Can confirm this JEI UI bug is present when trying to craft charcoal dust on `SevTech 3.0.6`. Shows the dust can be gotten from horse grind stone **but** that produces Charcoal pieces.

**For the age 0 Player**: Craft the mill stone and handle to get around (basically get buffalo) and send the charcoal through that.

**Comment by ArcheKnight** [comment]
The handle requires a wooden gear which can't be crafted without a crafting table as far as I can tell. That is what is preventing me from moving forward.

**Comment by 3ygun** [comment]
@ArcheKnight interesting. I was able to make one and only had access to the primal crafting table so maybe another UI bug?

**Comment by artdude543** [comment]
You need to use the BWM Mill Stone to get the dust in that age. (Until you unlock tech) Getting the tiny pieces from the Horse Power Mill is intended.

But I have fixed the staging for tiny charcoal.
