### ISSUE TITLE
Suggestion for 'Learning to Read' advancement

### ISSUE THREAD

**Issue by Crackerhead22** [Darkosto/SevTech-Ages#125]
In the description, it might be a good idea to mention that a Birchbark Tome is the book needed.

So instead of
`Use this book to trade with villagers or writing`

Change to
`Make a Birchbark Tome to trade with villagers.`

Also I from what I can tell, you can only use the Tome for crafting, you can't write in it like a normal Minecraft Book.

**Comment by Darkosto** [comment]
All done! Thank you :D
