### ISSUE TITLE
Immersive Tech Boiler Crash Loop

### ISSUE THREAD

**Issue by FantomBoGI** [Darkosto/SevTech-Ages#1250]
Whenever i load up my world it crashes.

I'm in age 3 and have done almost everything up to getting propene.

https://pastebin.com/F9pQ9QGv

**Comment by falloutfan576** [comment]
have you tried allocating more ram?

**Comment by CrypticDivide** [comment]
It is not a RAM issue.

From the linked crash report...
`Memory: 2222482888 bytes (2119 MB) / 4771020800 bytes (4550 MB) up to 8392802304 bytes (8004 MB)`

**Comment by falloutfan576** [comment]
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.5-1.12.2-anarchy.jar) it might be a problem with FoamFixAPI then  from this line in the crash report

**Comment by CrypticDivide** [comment]
@falloutfan576 That is always generated in the crash report. That does not always mean that that is the underlying issue.

**Comment by sarcastic6** [comment]
This looks a lot like this issue: https://github.com/FerroO2000/Immersive-Tech/issues/42

**Comment by artdude543** [comment]
Yeah, this is an ongoing issue with the mod. I've asked them to try and look into it as it's showing up a lot more now.

**Comment by artdude543** [comment]
There was a commit to fix the issue; awaiting that release (but from testing of a compiled build) it seems to fix the issue.

**Comment by justinrusso** [comment]
This will be in the release for 3.0.7. Let us know if this fixes the issue

**Comment by justinrusso** [comment]
If this issue persists in the next update, please submit a new issue. In testing this seems OK, but we were not able to replicate it initially.
