### ISSUE TITLE
No server download for 3.0.4

### ISSUE THREAD

**Issue by Quezler** [Darkosto/SevTech-Ages#1252]
https://minecraft.curseforge.com/projects/sevtech-ages/files

**Comment by Quezler** [comment]
@falloutfan576 The clients ultimately use the curse api, which does not have a download for 3.0.4.

**Comment by lawl281** [comment]
The server files will be out when they are done. Server files always take longer than the regular release.

**Comment by justinrusso** [comment]
The server files use the same mods, configs, etc as the client. If you cant do it manually, you msut wait. They will come.

**Comment by Quezler** [comment]
The issue is not for me, i have it working, it is for the others with the same question + a way to bring it into general attention.
