### ISSUE TITLE
Dense Net crafting recipe displaying incorrectly?

### ISSUE THREAD

**Issue by mwy885** [Darkosto/SevTech-Ages#1256]
## Issue / Bug
 6 stacks of 8 string required to make currently displaying; in JEI

## Current Behavior
recipe displays 6 stacks of 8 string required but crafts with 6 pieces of string

## Possible Solution
no suggestions, because I don't know which recipe is correct.

## Steps to Reproduce (for bugs)
1. be in stage 0 post crafting stump creation
2. look up recipe in JEI

## Context
Recipe in JEI makes crafting the Dense net confusing.

## Your Environment

* Modpack Version: 3.0.4
* Java Version: Version 8 Update 151
* Launcher Used: Twitch
* Resourcepack Enabled?: Faithful 32
* Optifine Installed?: No

**Comment by justinrusso** [comment]
https://github.com/Darkosto/SevTech-Ages/issues/1440
