### ISSUE TITLE
bugy ui and ingame graphic

### ISSUE THREAD

**Issue by FehZu** [Darkosto/SevTech-Ages#1258]
![2018-04-01_22 09 20](https://user-images.githubusercontent.com/37985750/38177023-c6d8d35a-35f9-11e8-8723-4ac8b02ab293.png)

 
## Issue / Bug

I have a problem  since today
## Steps to Reproduce (for bugs)

1.
2.

## Your Environment

* Modpack Version: 3.0.4
* Java Version: 8 update 161
* Launcher Used: Twitch/cruse? :D
* Resourcepack Enabled?:no
* Optifine Installed?:no

**Comment by Szethian** [comment]
I have the same problem starting today.  I initially experienced it in version 3.03.  The problem persists through re-loading the game and updating to version 3.04.

**Comment by neo130288** [comment]
i just started getting this bugg after updateing to 3.04

**Comment by Jandakast** [comment]
This is a Mojang April Fools joke. Use a texture/resource pack to fix this.
