### ISSUE TITLE
Vanilla Torch recipes

### ISSUE THREAD

**Issue by Dawenzel** [Darkosto/SevTech-Ages#126]
## Quality of Life / Bug
Not sure which recipe should be used but it could use some cleaning up.
![torch recipes](http://puu.sh/xQE4r/548025bf97.png)
## Versions
- Minecraft 1.12.1
- Forge 14.22.1.2485
- Java x64 8u144

**Comment by Dawenzel** [comment]
I think this is also what got mentioned in #13 not sure tho.

**Comment by Darkosto** [comment]
Should be all cleaned up, thank you!
