### ISSUE TITLE
[3.0.4] Redstone, Glowstone, Glass, Sand, & Ender Dust no longer Smelts 

### ISSUE THREAD

**Issue by Nicktropolis** [Darkosto/SevTech-Ages#1261]
## Issue / Bug
Redstone dust and glowstone dust will not smelt, have also tried the redstone block with same results. This happened after we updated from 3.01 to 3.04

EDIT: Glass, sand, ender dust as well will no longer smelt.

## Current Behavior
When placing the redstone or glowstone dust in the smelter it shows a small red progress bar, but then goes full silver and says "Item can't be molten." Currently in Age 4. 

## Possible Solution
Not sure on what the fix would be.

## Steps to Reproduce (for bugs)
https://media.giphy.com/media/jVEYy8uHDIEj0BiOfl/giphy.gif

## Context
We are running this on a windows server, with all the following environment.

## Your Environment

* Modpack Version:3.0.4
* Java Version:1.8.0.161
* Launcher Used: Forge 14.23.2.2651
* Resourcepack Enabled?:No
* Optifine Installed?:No

**Comment by kragnoth** [comment]
Dear lord, its a vanilla issue.  Mojang thought it would be witty to add trash textures for April 1st.
