### ISSUE TITLE
Can't put Wolf chop in Fire Pit

### ISSUE THREAD

**Issue by koulaw** [Darkosto/SevTech-Ages#1262]
## Issue / Bug
Hello, i'm currently in age zero and it appears that you can't cook any Wolf Chop (meat from Better with Mods) in Fire Pit. In contrary you can cook raw wolf (from primalCore) meat in it.

## Your Environment
* Modpack Version: 3.0.4

**Comment by alenori** [comment]
I'd like to confirm this:

Can do:
Cook Wolf Chop in Grill
Cook Wolf Meat(raw) in both Fire Pit and Grill

Cannot:
Cook Wolf Chop in Fire Pit.
