### ISSUE TITLE
Oregen seems very clustered into darkland biomes

### ISSUE THREAD

**Issue by daddy77gaming** [Darkosto/SevTech-Ages#1268]
currently on 3.0.4, generating new terrain..

came across a darklands biome ( first generated one past update ) that is full of deposits.. has double the ores compared to all neighbour biomes combined, is that intended or just luck? 

![2018-04-01_22 29 28](https://user-images.githubusercontent.com/31905330/38177710-97af64b6-3605-11e8-9d4f-f6e069257c23.png)

**Comment by 3jlowes** [comment]
Ore spawn was significantly increased in 3.0.4 so that is why it appears more ores are spawning in the darklands.

**Comment by Darkosto** [comment]
Oregen has nothing to do with biomes. This is just a case of RNG.
