### ISSUE TITLE
Platinum ore sample in stage 3 drops Osmium.

### ISSUE THREAD

**Issue by Syltann** [Darkosto/SevTech-Ages#1269]
After I mined out a vein of platinum in stage 3 I realized that it also dropped osmium which can't be used until a later stage.

Running version 3.0.4

**Comment by Syltann** [comment]
![2018-04-01_14 53 12](https://user-images.githubusercontent.com/30686588/38177951-56a63b22-35bd-11e8-8c07-8886ea151c67.png)

**Comment by Darkosto** [comment]
I've tried and cannot reproduce, do you have any more info?

**Comment by daddy77gaming** [comment]
mined about 400 platinum ores, didnt get any osmium drops in 3.0.4, thought it might be from the clusters, but about 14 i did dint drop it as well

**Comment by Syltann** [comment]
I've installed a new instance of the pack and moved my save over. Didn't have the issue anymore. I think my pack got screwed up somewhere, maybe in update?

**Comment by Syltann** [comment]
I think this is actually a non issue for everyone so I'm gonna close the issue. If anything comes up I'm sure someone will say something.
