### ISSUE TITLE
[Reminder] Debarking logs through crafting

### ISSUE THREAD

**Issue by Dawenzel** [Darkosto/SevTech-Ages#127]
When debarking logs through crafting with a workblade only bark is returned to the player. This worked and was tested. Someone suggested that the return and give functions got removed.

**Comment by Darkosto** [comment]
I'll catch up with @jaredlll08 and see if he was able to find out info about this.

**Comment by justinrusso** [comment]
@Darkosto This seems to be fixed. Just gave it a try on Alpha 8

**Comment by Darkosto** [comment]
Just tried again and I can't seem to get .giveback working. Maybe @jaredlll08 can take a look when he's not too busy.

**Comment by Darkosto** [comment]
Upon checking this out, I'm not getting 2 items back instead of one. So giveback is working twice as good?

**Comment by Darkosto** [comment]
.... Or not....
