### ISSUE TITLE
syrmorite hopper can feed more than 16 items into a grill

### ISSUE THREAD

**Issue by OranHexthief** [Darkosto/SevTech-Ages#1270]
## Issue / Bug
thought i would mention this since up until now the grill could only hold a max of 16 items but when i put the syrmorite hopper above it, it was able to feed a lot more than that into it. added a png to show

## Steps to Reproduce (for bugs)

1.
2.

## Your Environment

* Modpack Version:3.0.4
* Java Version:
* Launcher Used:twitch/jar
* Resourcepack Enabled?:no
* Optifine Installed?:no
![2018-04-01_17 58 44](https://user-images.githubusercontent.com/37780925/38177967-d69960e8-35d6-11e8-887b-3573ab6fecd4.png)

**Comment by vadis365** [comment]
Yeah, confirmed all hoppers do this for the grill, am tempted to leave it in as an 'overclocked' feature, the output slot will still only accept 16 items, so you're not really gaining anything other than a bit more buffer space.

**Comment by vadis365** [comment]
Should be fixed in primal tech now - awaiting testing for confirmation on another issue before releasing an update. This particular thing is now all good though.
