### ISSUE TITLE
Age 2 Upgrade Your Prospects Tooltip has incorrect distance [3.0.4]

### ISSUE THREAD

**Issue by DefiantZombie** [Darkosto/SevTech-Ages#1273]
Greetings good person,

I regret to inform you that I have encountered a minor bug in this outstanding piece of art you call a mod pack.

Upon reviewing my tasks upon reaching Age 2 I couldn't help but notice that the advancement titled 'Upgrade Your Prospects' indicates that the new tool will have a range of 32 blocks. I found this quite odd as before upgrading to version 3.0.4 of this magnificent pack I was informed that the new range for these tools is to be 48.

In order to aid you in repairing this discrepancy I believe I have located the offending piece of text in the file 'config/triumph/script/stage2/dowsingrod.txt' on line 5.

I am very sorry to have troubled you on this fine day with such a trivial report. Please know that I write this with love and the best of intentions.

![javaw_201804010843](https://user-images.githubusercontent.com/2503225/38178036-d4342328-35be-11e8-8bda-73a7bd3d0b69.png)

**Comment by Darkosto** [comment]
Fixed up in dev. Thanks!
