### ISSUE TITLE
Can not craft grass fiber mesh

### ISSUE THREAD

**Issue by Kuktar** [Darkosto/SevTech-Ages#1279]
The first advancement before age zero. i need flint, to get flint i need grass fiber mesh. When i put the ingredents into craft grid its not doing anything.

**Comment by justinrusso** [comment]
See https://github.com/Darkosto/SevTech-Ages/issues/1170

Can you provide your crafttweaker.log file? you can upload it to pastebin or gist.github.com and paste it in the issue I referenced?
