### ISSUE TITLE
Eating a entire stack of hearty stew

### ISSUE THREAD

**Issue by Dawenzel** [Darkosto/SevTech-Ages#128]
## Bug
When eating hearty stew/chicken soup/ chowder from "Better with Mods" the entire stack of stew is consumed and only 1 bowl is returned.

## Versions
- Minecraft 1.12.1
- Forge 14.22.1.2485
- Java x64 8u144
- Better with Mods 2.0.11

**Comment by Darkosto** [comment]
Heya @primeToxinz Have you seen this one?

**Comment by primetoxinz** [comment]
Fixed in dev

**Comment by Darkosto** [comment]
Fixed in pack dev.
