### ISSUE TITLE
breaking blocks behind block

### ISSUE THREAD

**Issue by tryplot** [Darkosto/SevTech-Ages#1280]
try to break block (in my case I was destroying a villager house).

## Issue / Bug
https://youtu.be/7CY-ga5e2e8

## Current Behavior

breaks blocks behind the block aimed at

## Possible Solution
no idea. not even sure what mod would do it.

## Steps to Reproduce (for bugs)
1. get axe (I've only had access to flint and stone aces so far)
2. find villager house
3. break roof with axe

## Your Environment
most recent everything (as of march 31st). no resource packs, nor optifine.

**Comment by Turkey2349** [comment]
Not 100% sure about this (Will edit when I know more), but most likely what is happening is that a non full block (i.e. stairs or half slab) is being staged and hidden as the full block wood planks. However the block hitbox is not changing in relation to the wood plank and is instead keeping the old, non-full block, hitbox thus causing you to be able to "click through" the wood plank. Not sure if this is fixable though.

**Comment by Turkey2349** [comment]
See #803

**Comment by tryplot** [comment]
probably what's happening. makes sense and kinda glad that it's been noted before.
