### ISSUE TITLE
Textures are bugged and oversaturated

### ISSUE THREAD

**Issue by Kiwimaster76** [Darkosto/SevTech-Ages#1282]
So everything works fine so far in the modpack, the idea is great and what I've played of it is really fun. However I cant play for very long as I get headaches from what I can only assume is a glitch in the textures. I don't have any resource packs on so it should look like vanilla minecraft but instead I get this:

![2018-04-01_20 53 30](https://user-images.githubusercontent.com/37990364/38180221-7f07600e-35f0-11e8-8d9b-fb3ad4be3408.png)

I am using the Twitch launcher and this happens in every biome and every time I start it up. I have no idea how to fix this or even what is wrong, but id appreciate any help you can give me.
-Thanks!

**Comment by justinrusso** [comment]
https://twitter.com/DarkostoTV/status/980477968924409856
