### ISSUE TITLE
Game crashed and now cannot interact with world (Crash)

### ISSUE THREAD

**Issue by kugamer** [Darkosto/SevTech-Ages#1283]
Game crashed and now I cannot interact with my world
http://pastebin.com/bC77GQtM

I had placed a lens from astral sorcery that caused the game to crash. When I restarted the game immediatly crashed with report above. Now when I go into my world I cannot interact with anything. A dog attacked me in twighlight forest armor and killed me, my tinkers iron sword wouldn't do any damage to it. 

No idea how to reproduce this as I cannot get my world back to a playable state to try and reproduce. I was trying to turn magma blocks into obsidian using the lens from astral sorcery. 

Your Environment
* Modpack Version: 1.0.4
* Java Version: 1.8.0_161
* Launcher Used: twitch
* Resourcepack Enabled?: faithful
* Optifine Installed?:no

**Comment by MrWaterMan** [comment]
Well the crash report says that immersiveengineering:metal_device0 is the block being tesselated. I don't know much, but a block in immersive engineering seems to be causing the problem.

**Comment by MrWaterMan** [comment]
A temporary fix to this is to use MCEdit to remove the block from the world at 703,62,489. This happened in a different modpack and this seems to fix the problem temporarily.

**Comment by artdude543** [comment]
This is resolved in the 3.0.7 update.
