### ISSUE TITLE
Low FPS all of a sudden? Was getting 120+ yesterday.

### ISSUE THREAD

**Issue by chuchu4chu** [Darkosto/SevTech-Ages#1284]
Was playing fine yesterday with no issues at all at around 120+ FPS. Tried to play now and the world struggles to load and is now getting around 15 FPS. I've changed almost no settings since then and can't seem to figure out why this is happening aside from maybe the april fools joke textures bugging things out? I've attached a screenshot of my fps and hardware.
![lowfps](https://user-images.githubusercontent.com/34948072/38180352-d00175fe-35e0-11e8-9270-0a6dac658878.png)

**Comment by daddy77gaming** [comment]
I have had this FPS drop 2 times in a week.. nothing but close minecraft and relaunch fixed it for me

**Comment by chuchu4chu** [comment]
Dang... I've tried relaunching, restarting my pc, starting a new world and nothing seems to work. No clue what could be causing this and why it'd happen so suddenly.

**Comment by chuchu4chu** [comment]
Solved by copying world, deleting the entire profile in the Twitch launcher, redownloading and moving the world back into the file. Still no clue what could have cause it. But It's a solution! Hopefully it won't happen again.
