### ISSUE TITLE
Hunting Portal- Going back to overworld, spawn in ground, lose grave

### ISSUE THREAD

**Issue by Dystilled** [Darkosto/SevTech-Ages#1287]
## Issue / Bug
Set up a hunting portal, went in and came back out, "suffocated in a wall" 
Spawned with death compass, compass pointed to portal, Journeymap marker shows death under the portal. 

Dug under portal, no grave there. Lost all my stuff. 

## Current Behavior
Spawn under portal instead of next to portal

## Possible Solution
Change graves to replace blocks if required, have lost full inventory a number of times due to grave based bugs.

## Steps to Reproduce (for bugs)
As in Issue/Bug

## Context
Lost all my items. Died. 

## Your Environment

* Modpack Version: 0.4
* Java Version: 8.2
* Launcher Used: Twitch
* Resourcepack Enabled?: Soartex
* Optifine Installed?: Yes
![death](https://user-images.githubusercontent.com/36810196/38184719-f190ec0c-368c-11e8-97e2-fe6e11060a5a.jpg)

**Comment by poxun1** [comment]
I am also experiencing this however my grave is not lost - just misplaced.  These are my observations
Most (not all - 6 our of 8 so far) times I return from the hunting dimension I suffocate in a wall.
When I spawn correctly i do so at the portal
When I suffocate it is in around the same area in the nearby (but not the exact x/z) about y=64 which is nominally underground.
My grave is left underground somewhere (I think the first free air block downwards) but not the exact spot the death compass shows. once it was on the surface.
Portal is at Y=70

Screenshot: Cobble block is where i spawned last time
![image](https://user-images.githubusercontent.com/37996101/38185850-f08d2eaa-3647-11e8-8f3c-a815a0153099.png)

**Comment by Dystilled** [comment]
Im glad you posted this... I just went back and found my grave 40 blocks away down a cliff in a little alcove. 

So weird.

**Comment by poxun1** [comment]
Update: I dug out the area at the cobble block in my screenshot to Y=64 and I consistently spawn in the same place and no longer suffocate as there is no stone there any more.

**Comment by poxun1** [comment]
After some more experimentation it seems that if you go to the portal correctly or to the other location (which I guess might be x/y/z from the portal in the other dimension) is dependent on if you are standing fully in the portal or not

I have also now observed incorrect placement travelling the other way (overworld to dimension).  I spawned mid air at about the same but opposite displacement than dimension to overworld

**Comment by Kaffee81** [comment]
This happend also for me, but when I spawned in the ground, all my Items spilled ontop of the blocks, no grave.

**Comment by WibbersGIT** [comment]
I had this same issue as well. When returning from the hunting dimension to the overworld, I spawned about 5-6 blocks underground and about 5-6 block away from the portal (sorry, don't have exact coordinates). I was able to break a couple of blocks quickly and throw down a torch so I didn't die, so I cant comment on losing the grave.

**Comment by Shock2k** [comment]
This happened to me also.  Except it was going to the Betweenlands.  The "death" was in the middle of the swamp, so I have no idea how to locate my gear.  I'm assuming it's gone.  Interesting thing is, the death spawn was about 50 blocks from where I was actually warping in.

**Comment by darkhax** [comment]
Hello, I am the dev of Hunting Dimension. I am sorry for the issue this has caused all of you. A new release has been uploaded to Curse which should fix this issue. You can find it [here](https://minecraft.curseforge.com/projects/hunting-dimension/files/2548007). This fix will hopefully get added to SevTech soon enough.

**Comment by Dystilled** [comment]
Thanks Darkhax, appreciate the help

**Comment by Hebbu** [comment]
This seems to also happen with The Beneath portal.

**Comment by justinrusso** [comment]
Updated to https://minecraft.curseforge.com/projects/hunting-dimension/files/2548007

Will be in 3.0.5
