### ISSUE TITLE
PrimalCore corn grow's too slow

### ISSUE THREAD

**Issue by ComaCanadian** [Darkosto/SevTech-Ages#1293]
## Issue / Bug
PrimalCore corn plant doesn't grow with bone meal or Actually Additions fertilizer. Using a watering can on it for over a minute decided to go up a growth stage. Previously this corn seed was world gen'd in. and had been chunk loaded since patch launch (because its right outside my base). It had not started to grow until I had used the watering can on it. 

unsure if the growth ticks are set correctly. a newly planted seed hasn't responded to any watering can action. 

possibly can only grow if the farmland is hydrated, which could be why i never see it grow in the world gen'd nodes.

## Steps to Reproduce (for bugs)
1. plant corn seeds / find it generated in the world
2. watering can
3. wait forever.

## Your Environment
* Modpack Version: 3.0.4
* Java Version: 1.8.0 161 64bit
* Launcher Used: jar
* Resourcepack Enabled?: no
* Optifine Installed?: yes
* Current Stage: 3

**Comment by ComaCanadian** [comment]
So I decided to test Actually Additions fertilizer. the corn i was testing on had grown. Before this I even tested with a cheated in seed and a stack of bone meal. unsure if its just a really weird bug with world gen from a previous version. This particular crop that had grown was in spawn chunks and been there since world creation since pack launch.

unsure if this is an issue with growth ticks being insanely low. and the crop not responding to bone meal effects.

**Comment by artdude543** [comment]
This is an intended thing for the mod tbh all the plants grow slow. So just plant a load and you'll have plenty in no time! 😄

**Comment by kragnoth** [comment]
Just to let you know, I have corn that has been there since last week, and the stalks still haven't grown.

It looks quite bugged.

**Comment by Thiana** [comment]
It seems the problem only effects worldgen corn. I planted a corn seed next to a worldgen one and came back an hour later to find the planted one fully grown. @artdude543 is there supposed to be a way of getting corn seeds without harvesting the worldgen ones?

![2018-04-09_16 30 24](https://user-images.githubusercontent.com/405832/38522338-42e858b8-3c16-11e8-90c2-d600c970b7f3.png)

**Comment by xt9** [comment]
Even with the Totemic Zaphkiel Waltz nothing happen to these in worldgen, maybe it's time to get rid of the RNG label?

**Comment by Lykrast** [comment]
I confirm none of the worldgen ones I encountered ever grew, and I currently don't know where to find seeds.
