### ISSUE TITLE
The game crashed whilst initializing game

### ISSUE THREAD

**Issue by YakenChan** [Darkosto/SevTech-Ages#1294]
On intializing the game it randomly crashes since the last pack update

The game crashed whilst initializing game
The game crashed whilst initializing game
Error: net.minecraft.client.renderer.StitcherException: Unable to fit: chisel:blocks/concrete/weathered-half-side - size: 16x16 - Maybe try a lowerresolution resourcepack?

does anyone has an idea how I can fix it?

(I'm testing to reverse to earlier versions right now)
Edit : Does not work

**Comment by justinrusso** [comment]
https://github.com/Darkosto/SevTech-Ages/issues/924 try restarting your pc
