### ISSUE TITLE
holding chicken while Looting Grave will bug UI

### ISSUE THREAD

**Issue by Sickenedtv** [Darkosto/SevTech-Ages#1295]
If you die, run back, Pick up a chicken and then try to loot your grave. It will bug the UI thinking you still have the chicken but it has dropped it.

Current Behavior

Possible Solution: Not sure, Its a coding issue I'm sure. It would have to be added so that it understands that the chicken has been dropped.

Steps to Reproduce (for bugs) As stated above just die hold a chicken and try to loot grave

Modpack Version: 3.0.4 latest
Launcher Used: Twitch
Resourcepack Enabled?: faithful 32 and modded 32

**Comment by artdude543** [comment]
First of all, why would you pick up a chicken when running back to your grave? Like. I don't even. I won't call this a bug just because how the mod works and it's not actually breaking anything is it? Just don't pick up anything and you'll be fine!
