### ISSUE TITLE
Advanced generators won't output power to any type of power transfer

### ISSUE THREAD

**Issue by BananaLord12** [Darkosto/SevTech-Ages#1296]
## Bug
So i have decided to create an advance generator, i made my syngas gen and my gas turbine gen with 6 gold turbines, when i placed a flux generator which is how you output power from the generator, i was not able to extract it from it, i tried with a connector from IE, it wont work, i tried BC it wont even connect and i tried cyclic but the same thing.
What it should happen is, the advance generator will give power to either the pipe or any other method of transporting power.

## Current Behavior
Well at the moment, my only way of creating power is water mills even though i wanted an advanced generator and for that i cant produce enough power for my machines

## Possible Solution
A possible solution is to either has an pipe that will be able to interact with the method of transporting OR make the generator to output power directly to a Capacitor from Immersive engineering.

## Steps to Reproduce (for bugs)
1.  Create a Gas Turbine multiple block
2.  Create a Syngas producer multiple block
3.  Add syngas to the Gas Turbine
4.  Add a Flux Generator
5.  Add the method of power transfer (IE connectors)

## Your Environment
* Modpack Version: 3.0.4
* Java Version: 1.8.2_25
* Launcher Used: Twitch
* Optifine Installed?: 1.12.2_HD_U_C9

**Comment by Darkosto** [comment]
Using the Energy Adapter block will let you convert power to the mods you need :)
