### ISSUE TITLE
Unable to convert Salted Leather to Dried hide on Drying rack in 3.0.4

### ISSUE THREAD

**Issue by Slychocobo** [Darkosto/SevTech-Ages#1297]
Unable to convert Salted Leather to Dried hide on Tinkers Drying Rack.

Recpipe exists in JEI but after leaving item for an hour (real time) has not converted.
Have confirmed item is "Drying Rack" (not a item frame) and Salted hide as defined in JEI.

Have used different wood-types for Drying rack but makes no difference.

Screenshots of setup - https://imgur.com/a/WaAlB

**Comment by Dystilled** [comment]
Have you tried breaking and re-placing the drying racks? 

I did this recipe half hr ago with no issues.

**Comment by Slychocobo** [comment]
Resolved,  Issue seems to have been caused by an incomplete/corrupted server package, reinstall fixed it.

**Comment by DrunkOctopus** [comment]
I created this again in 3.0.6 after my world was corrupted by (I think) pneumaticcraft
