### ISSUE TITLE
Unable to Load mod pack after updating to 3.0.4

### ISSUE THREAD

**Issue by WillCubed** [Darkosto/SevTech-Ages#1298]
## Issue / Bug
On launch game consistently crashes even if I install on a new instance. 
I receive this error each time. 

https://pastebin.com/QcWQEPQ3

* Modpack Version: 3.0.4
* Java Version: 1.8.0.161
* Launcher Used: Twitch/Curse
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by artdude543** [comment]
Your install is broken; on the SevTech Menu click the `...` button and then hit "Repair Minecraft" this should fix the issue.

**Comment by WillCubed** [comment]
Thank you for the reply, have done that and still no fix.

**Comment by artdude543** [comment]
Okay, the second step a mod could be conflicting here with the Font Renderer. Could you try disabling Smooth Font for me and then try to boot the game?

**Comment by WillCubed** [comment]
That worked - and it told me that mod pack had numerous duplicated Jars...I think twitch client derped and caused this error!

**Comment by artdude543** [comment]
Okay so in that case maybe trying with re-installing the profile will fix the main issue here and thus allowing you to use the smooth font as It seems with dupes being loaded up it's breaking things as you've experienced. Unless it's already done the fixing for you? If so trying re-enabling the mod and try 😄
