### ISSUE TITLE
You added some custom recipes but forgot to remove the standard easier ones

### ISSUE THREAD

**Issue by davqvist** [Darkosto/SevTech-Ages#13]
1.) Cotton to String: The easier 3 Cotton to 1 String recipe needs to be removed as the custom one needs the blade.
2.) The Immersive Craft has 3 recipes of different difficulty, pretty sure the one requiring the Grill is the intended one, so the other ones need to be removed.

**Comment by davqvist** [comment]
3.) Torch has several recipes. Not sure which one is the correct one, I suppose the one that only gives 1.

**Comment by davqvist** [comment]
4.) Tinkers Patterns, I think at least. There is a much harder recipe requiring Bark and a sawed plank which needs the saw which needs Bronze. So I think Tinkers is supposed to be gated behind bronze, so I assume the easier recipe needs to be disabled.

**Comment by Darkosto** [comment]
Should all be in the correct stages and the extra recipes should be gone now.
