### ISSUE TITLE
Stone Hoe recipe incorrect in JEI

### ISSUE THREAD

**Issue by MongoTheElder** [Darkosto/SevTech-Ages#130]
Crafting a Stone Hoe in Stage One uses the vanilla recipe:
![2017-10-07_22 58 23](https://user-images.githubusercontent.com/29290246/31313516-46167130-abb3-11e7-9841-c13d3dee27dd.png)

but JEI shows an alternate (unusable) recipe:
![2017-10-07_22 58 30](https://user-images.githubusercontent.com/29290246/31313519-4da38dca-abb3-11e7-9304-97db01ebb2d2.png)

Alpha 4
Minecraft 1.12.2
Forge 14.22.1.2485
JEI 4.7.11.102

**Comment by Darkosto** [comment]
Yeah, I need to talk to @jaredlll08 and see what he might be able to do about this one :P

**Comment by Grauldon** [comment]
I'm in stage0 and this is what JEI shows me:

![2017-10-12_17 21 42](https://user-images.githubusercontent.com/17791090/31519896-ffd0cc30-af71-11e7-9e89-7e2e4131639c.png)

**Minecraft** _1.12.1_
**Forge** _14.22.1.2485_
**MCP** _9.41_
**Java** is version _1.8.0_144_, using 64-bit architecture.
**Alpha** _4_

**JEI** _4.7.11.1102_
**CraftTweaker2** _1.12-4.0.7_
**Mod Tweaker** _4.0.2_
**Client Tweaks** _3.1.2_
**ContentTweaker** _1.12-4.1.0_
**CraftTweaker JEI Support** _2.0.0_
