### ISSUE TITLE
Infinite Blaze Powder and Rods (Recipe Bug?)

### ISSUE THREAD

**Issue by kugamer** [Darkosto/SevTech-Ages#1300]
The mechanical squeezer by integrated dynamics takes 1 blaze rod and creates 5 blaze powder. The rod press from immersive takes 4 powder and makes 1 rod. This creates an infinite loop for blaze powder, is this intended?

Your Environment
* Modpack Version: 3.0.4
* Java Version: 8_162
* Launcher Used: Twitch
* Resourcepack Enabled?: faithful
* Optifine Installed?: no

**Comment by Dystilled** [comment]
Shhhhhhhhhhhhhhhhhh >_>

**Comment by Boomflex** [comment]
Darkosto/Necron,

If you change `/config/integrateddynamics/_override/mechanical_squeezer_convenience.xml` to the below, that will change the recipe to only squeeze down to 4 powder.

```<recipe type="integrateddynamics:mechanical_squeezer">
<tag>ores</tag>
<condition type="config">mechanical_squeezer</condition>
<input>
<item>minecraft:blaze_rod</item>
</input>
<output>
<item amount="4">minecraft:blaze_powder</item>
</output>
<properties>
<duration>40</duration>
</properties>
</recipe>```

We had the same on our pack.
