### ISSUE TITLE
"Nether Brick - BWM Kiln documentation absent

### ISSUE THREAD

**Issue by Dystilled** [Darkosto/SevTech-Ages#1301]
## Issue / Bug
Quest instructs to use Book of Single to find out how to use BWM Kiln. However Book of Single doesn't appear to include documentation on the kiln. 

## Current Behavior
Incorrect text for quest

## Steps to Reproduce (for bugs)
Stage 3 quest "Nether Brick"

## Context
Misleading text, causes confusion.

**Comment by daddy77gaming** [comment]
As the manual states report to BWM github..

which someone did recently ;)

https://github.com/BetterWithMods/BetterWithMods/issues/835

**Comment by daddy77gaming** [comment]
the addon stuff is in there.. the basic stuff isnt atm (sidenote older versions do work) so if someone needs to know they can convert back to an earlier version of BWM

**Comment by daddy77gaming** [comment]
in case you wonder:

grindstone netherrack drop that into filtered hopper (soulsand) gets you hellfire dust
in a stoked cauldron wood planks gets you potash
potash and hellfire 1:3 gets you nether sludge in a cauldron 
which in a stoked kiln gets you nether brick.

**Comment by daddy77gaming** [comment]
watch out with the filtered hopper tho.. it occasianally breaks and spawns a ghast ;) which can be a pain if your base is still mostly wood ( experienced the hard way in the past)

**Comment by artdude543** [comment]
This was reported to the mod dev and fixed but they do have a web version of the Manual which you can view here: https://betterwithmods.github.io/Documentation/en_us/
