### ISSUE TITLE
Twilight progression issues

### ISSUE THREAD

**Issue by auryssurys** [Darkosto/SevTech-Ages#1302]
## Issue / Bug
The hydra spawned and instantly disappeared https://imgur.com/a/b3JpG
Playing in a server so I asked for help to see if completion did anything after advancement was completed found another hydra but it was still the same. 
I did complete the next step in the advancement of progressing until i arrived at ur-ghast. At the top of the tower the ur-ghast flashed and disappeared. And thats where my progression ended.

## Context
 Cant progress without getting drops from bosses

## Your Environment

* Modpack Version: 3.0.4 +ftb utilities and ftb libraries
* Java Version: 1.8.0.25 64bit
* Launcher Used: twitch
* Resourcepack Enabled?: no
* Optifine Installed?: No

**Comment by Darkosto** [comment]
Does this server use Sponge? I can confirm the Hydra is able to be spawned and fought on multiplayer.

**Comment by artdude543** [comment]
Using a Sponge server which is not supported for pack support. See above for a possible fix. But we don't offer support for **any** server running Sponge.
