### ISSUE TITLE
Blank Teleporter only accepts unbound blood orb

### ISSUE THREAD

**Issue by AquaXV** [Darkosto/SevTech-Ages#1304]
## Issue / Bug
When crafting the blank teleporter the recipe only accepts an unbound apprentice blood orb

## Current Behavior
When you bind the apprentice blood orb to a player it can't be used to craft the blank teleporter

## Possible Solution
This is NBT related; unbound orbs have only 1 tag; {orb:"bloodmagic:apprentice"}, bound orbs have 2 tags; {binding:{Name:"PLAYERNAME",L:"01234567...L",M:"01234567...L"},orb:"bloodmagic:apprentice"}
Allowing the recipe to use bound tags should fix this issue (recipe appears to be NBT exact)

## Steps to Reproduce (for bugs)
1. Create an apprentice blood orb (or via '/give <player> bloodmagic:blood_orb 1 0 {orb:"bloodmagic:apprentice"}') 
2. Bind orb to player
3. Try to craft the blank teleporter

## Context
To progress into the Beneath we need the blank teleporter, which I wasn't able to create, after getting a new orb which I did not bind I was able to craft the blank teleporter (you do keep the orb after crafting)

## Your Environment
* Modpack Version: 3.0.4
* Version: 1.8.0_162
* Launcher Used: Twitch -> Jar Launcher
* Resourcepack Enabled?: No
* Optifine Installed?: Yes (1.12.2_HD_U_D1)

**Comment by Ambaire** [comment]
This is interesting, considering I think I was able to craft the teleporter after binding the blood orb, in 3.0.4. True, JEI won't let you shift-click the ingredients in, but they can be manually inserted just fine.

Let's see. Loaded up the game, gave myself the materials for another teleporter... 
And the recipe seems to work fine. Using a crafting station, 3.0.4, bound blood orb. Maybe give it another try?
https://i.imgur.com/WAcgbmw.png

**Comment by AquaXV** [comment]
Ah yes, I only tried via JEI. I should have tried by manually putting the items in. My bad!

**Comment by artdude543** [comment]
Works as intended and JEI auto insert will be iffy with this. But manual inserting works fine/intended.

**Comment by Shoulon** [comment]
Issue still persist as i couldn't use my Bound Apprentice Orb in the recipe manually
