### ISSUE TITLE
Eucalyptus stairs recipe

### ISSUE THREAD

**Issue by Tayba3** [Darkosto/SevTech-Ages#1307]
When making eucalyptus stairs backwards, it gives you slabs instead of stairs:
x 
x x
x x x

## Your Environment

* Modpack Version: 3.0.4
* Java Version: 8 161
* Launcher Used: twitch
* Resourcepack Enabled?: soartex
* Optifine Installed?: yes

**Comment by daddy77gaming** [comment]
Adding to that, you can take away some blocks.. and more weird things happen ;)
Its not only affecting eucalyptus, its all woods that can be used in crafting
![2018-04-02_17 44 47](https://user-images.githubusercontent.com/31905330/38205218-0e3b3c7c-36a6-11e8-887c-471489e6d184.png)

![2018-04-02_17 44 51](https://user-images.githubusercontent.com/31905330/38205211-072109c6-36a6-11e8-9f89-e10bd9b2a972.png)

![2018-04-02_17 41 58](https://user-images.githubusercontent.com/31905330/38205148-c9134662-36a5-11e8-8278-d96ccd7a1bf0.png)

![2018-04-02_17 42 48](https://user-images.githubusercontent.com/31905330/38205144-c6ade594-36a5-11e8-9b2b-7b284922592d.png)

![2018-04-02_17 42 07](https://user-images.githubusercontent.com/31905330/38205125-bb9b70c2-36a5-11e8-87b3-2142244aca10.png)

![2018-04-02_17 42 22](https://user-images.githubusercontent.com/31905330/38205122-b88ed5b8-36a5-11e8-94ed-e9bab7f1b9f0.png)

**Comment by artdude543** [comment]
Going to use https://github.com/Darkosto/SevTech-Ages/issues/705 as the master for tracking this issue as it's all related.
