### ISSUE TITLE
[3.0.4] Viescrafts won't accept upgrades [Ages 3 and 4]

### ISSUE THREAD

**Issue by togreglove** [Darkosto/SevTech-Ages#1308]
## Issue / Bug
Crafted the tier 1 balloon upgrade for my airship and when I put it in the balloon upgrade slot and click the accept button underneath, nothing happens. The upgrade stays where I put it and can be removed from the slot. The upgrades are staged so I can get to them, so I was wondering if upgrading was a Stage 5 thing?

## Current Behavior
Accept buttons for adding balloon upgrade to airship doesn't work

## Steps to Reproduce (for bugs)
1. Craft the V1 airship
2. Craft the Tier 1 Balloon Upgrade
3. Get in ship
4. Hit hotkey to bring up gui
5. Click upgrade tab
6. Put Upgrade into Balloon upgrade slot
7. Click Accept button beneath upgrade slot
8. Nothing happens, button appears dead.

**Comment by JonathanLowe1** [comment]
You need to upgrade the viescraft core first before you can add upgrades
ie: tier 1 core allows for only tier one upgrades, tier 2 core allows for teir 2 upgrades and teir 1. etc.
This is not an issue / bug

**Comment by togreglove** [comment]
Thank you. That wasn't made clear in the manual.

**Comment by JonathanLowe1** [comment]
Does viescraft have a manual?
