### ISSUE TITLE
Clear Glass recipe conflict w/ Glass Chunks

### ISSUE THREAD

**Issue by randomlypickedname** [Darkosto/SevTech-Ages#1310]
## Issue / Bug
Attempting to put glass in the center of a 3x3 crafting grid to craft clear glass gives glass chunks instead.

## Context
Not a major bug, but something I noticed when attempting to craft it for aesthetics.

## Your Environment

* Modpack Version: 3.0.4
* Java Version:
* Launcher Used:
* Resourcepack Enabled?:
* Optifine Installed?:

**Comment by artdude543** [comment]
This is fixed in dev :)
