### ISSUE TITLE
Advancements not Updating

### ISSUE THREAD

**Issue by Subby1337** [Darkosto/SevTech-Ages#1311]
## Issue / Bug
Advancements are not Updating.
E.g. in the Image below.
The Iron Ingot and the Porcelain Tank advancement are both not triggered,
even though i got both.
![Problem](https://i.gyazo.com/73dc35df89a19d4bfb405b6917a4083b.png)

## Context
I updated my Server recently from 3.0.1 up to 3.0.4.
After the Update some Advancements where changed from 2/2 to 1/2 like the Chest Adv.  or the Apple of Lofty sature from Age 1.
The Milestone Coloring isn't updated and "some" Advancements aren't Updating.
Recently traveled to the Betweenlands Advancement was triggered but after that nothing worked anymore.

Edit: I Downloaded the MP Map and tested it in Singleplayer and the Advancements work fine.
So i guess it's a server issue i am not aware of.

Edit 2: I tried leaving my TogetherForever Party reconnected and did the Advancement again or picked up the item and it worked. Maybe a bug.

Edit3: 
I've found a Workaround which works for me but is pretty unsatisfying.
1. Leave TogetherForever Party because the ADv. wouldn't Trigger
2. Reconnect to the Server
3. Break Hemtite for the Iron Chunk or pick up Item for Adv. 
4. Advancement will trigger
5. Profit

## Your Environment

* Modpack Version: 3.0.4
* Java Version: 1.8.0
* Launcher Used: Twitch Launcher
* Resourcepack Enabled?: No
* Optifine Installed?: Yes
#

**Comment by Emendio** [comment]
This is also happening after a certain point in 3.0.1, me and my group of three other people are the most advanced on the server and this is happening across the server to everyone.

**Comment by RealLith** [comment]
You made a little mistake. For the advancement u need Porcelain Tank, what you have is Porcelain Basin. 
Just wanted to point that out. But the iron ye its true. It has happened to me multiple times in 3.0.1 and 3.0.3.

**Comment by Subby1337** [comment]
Whoops my bad but i got the Tank as well and it still won't trigger the Event. But thanks for the Clarification.

**Comment by Emendio** [comment]
I used ./tf forcesync and it worked for my group, it lagged for a few secs and then all the advancements we did were done

**Comment by Subby1337** [comment]
I tried that several times and it didn't change a thing.I think that only the case if at least one member of your group made the Advancement.

**Comment by tjsd** [comment]
Upgraded from 3.0.2 to 3.04. Clients updated with twitch launcher and server upgraded with 3.0.4 server zip file. Some people are not able to proceed with advancements and the color scheme is not updated to reflect the changes done with purple for main quest.

**Comment by SWATr** [comment]
I have this issue on 3.0.6

**Comment by artdude543** [comment]
This is an older issue and 3.0.6 contains fixes for the mods. Please update to the latest version of the pack 🙂
