### ISSUE TITLE
Hopper under Mill Stone

### ISSUE THREAD

**Issue by extrenix** [Darkosto/SevTech-Ages#1312]
Is there any way to make this work?
My Mill Stone is connected via gearbox and axle so it runs on its own.
Got a hopper mk2 and chest system underneath the mill, but as soon as I put something in the mill stone for processing, the hopper sucks it out before the mill stone gets to work

**Comment by Targren** [comment]
I went oldschool: put the millstone in the middle of a a 3x3 hole of its own. Put a water block in one corner, and a hopper into a chest in the opposite corner.  Kind of like what MyApolloGees does, but gets away with using just one hopper

**Comment by MyApolloGees** [comment]
Smart man ^ Wish i thought of that.

**Comment by daddy77gaming** [comment]
That should cause trouble with the new water mechanic where items flow up, But it does not.. I sort of hope they fix that, cause imo that new mechanic is there for a reason.

**Comment by Targren** [comment]
I don't think it's a problem. Hoppers pull items through lower half-slabs, too. The floating items are definitely convenient, but I don't think "the reason" is to screw with hoppers.

**Comment by Jandakast** [comment]
Surrounding the Millstone with hoppers or using a water/canal system is the way to do this.
