### ISSUE TITLE
Infinite oak wood siding by placing oak door under saw

### ISSUE THREAD

**Issue by daRussianman** [Darkosto/SevTech-Ages#1316]
By placing an oak wood door under a saw it breaks the door and drops 2 oak wood siding as well as the door placed. The saw probably thinks that i'm placing an oak plank and breaks the top half of the door which drops the door in addition to the oak siding. 
Below is the setup i used to discover this dupe bug

https://imgur.com/a/YAeAk

Modpack Version: 3.0.4
Launcher Used: Twitch

**Comment by daRussianman** [comment]
Only works when the saw breaks the top half of the door works correctly when breaking the bottom half of the door.

**Comment by artdude543** [comment]
This was fixed in 3.0.6 can you update please :)
