### ISSUE TITLE
Boiler not creating steam

### ISSUE THREAD

**Issue by BlameMateo** [Darkosto/SevTech-Ages#1318]
## Issue / Bug
Boiler should be creating steam from water and diesel

## Current Behavior
The boiler doesn't do anything

## Context
Trying to create steam for advancement and i'm stuck. I could just be doing something wrong though.

## Your Environment

* Modpack Version: 3.0.4
* Java Version: 1.8.0_161
* Launcher Used: Twitch
* Resourcepack Enabled?: Soartex
* Optifine Installed?: Yes

**Comment by kylertoll** [comment]
I had this issue, it's because you need to input the two fluids in their correct input sides. Just shift clicking a bucket into the GUI puts them in the wrong spots.

**Comment by BlameMateo** [comment]
You sir are the real MVP. :D
