### ISSUE TITLE
Between Lands sticks uncraftable, ungettable

### ISSUE THREAD

**Issue by borg286** [Darkosto/SevTech-Ages#1320]
## Issue / Bug
Between lands planks don't make betweenlands sticks.

## Current Behavior
When breaking leaves, vanilla sticks drop. When chopping weedwood planks, vanila sticks drop. There is no way to make Weedwood sticks, a core ingredient for progressing through the world.

## Possible Solution
Make weedwood sticks an oredict for vanilla sticks.
Have weedwood leaves drop weedwood sticks.
Make a recipe for weedwood planks to craft into weedwood sticks.

## Your Environment
* Modpack Version: 3.0.4
* Java Version: 1.8
* Launcher Used: Twitch
* Resourcepack Enabled?: no
* Optifine Installed?: yes

**Comment by MyApolloGees** [comment]
bushes in the betweenlands drop sticks they are on the ground usually in clusters.

**Comment by justinrusso** [comment]
^

**Comment by SoundslikeLogic** [comment]
The bushes are nonrenewable and if you're unlucky like I am, nowhere remotely close to your spawn. I've traveled hundreds of blocks in every direction and haven't found my first bush.

**Comment by mtjohnson47** [comment]
What about a recipe to convert weedwood leaves + weedwood sticks into bushes?  Then, it's renewable, but still gated until you get the first 1.

Recipe:
LSL
SLS
LSL

Yields 8 bushes from 4 sticks and 5 leaves.
