### ISSUE TITLE
Tin Canister recipe missing

### ISSUE THREAD

**Issue by amezh** [Darkosto/SevTech-Ages#1325]
## Issue / Bug
No recipe for galacticraft Tin Canister (stage 4 ) which is required for fuel loader and for rocket itself.

## Your Environment

* Modpack Version: 3.0.4
* Java Version:1.8.0_161 x64
* Launcher Used:Twitch
* Resourcepack Enabled?:Yes
* Optifine Installed?:Yes

**Comment by justinrusso** [comment]
https://github.com/Darkosto/SevTech-Ages/issues/1201
