### ISSUE TITLE
Tape measure in JEI but no recipe

### ISSUE THREAD

**Issue by slimofthejimz** [Darkosto/SevTech-Ages#1327]
## Issue / Bug
When in Stage One, the tape measure from Chisels & Bits shows up in JEI but has no crafting recipe.
https://imgur.com/skPw7ec

## Possible Solution
* If the tape measure *should* be in Stage One, then a recipe should be available.
* If the tape measure *should not* be in Stage One, it should be removed from sight in JEI.

## Your Environment
* Modpack Version: 3.0.4
* Java Version: 1.8.0.161
* Launcher Used: Twitch
* Resourcepack Enabled?: Soartex Modded Universal
* Optifine Installed?: Yes

**Comment by Darkosto** [comment]
Fixed in dev.
