### ISSUE TITLE
[Question] Vanilla Ores in Hollow Hills

### ISSUE THREAD

**Issue by iffonox** [Darkosto/SevTech-Ages#1329]
I just found vanilla ores (iron, coal and redstone) in a Holow Hill. Are they supposed to spawn in there?

## Your Environment
* Modpack Version: 3.0.4
* Java Version: 1.8.0_101
* Launcher Used: Twitch
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by Darkosto** [comment]
Yes, this is intended.
