### ISSUE TITLE
Stage 1 advancement Bottom Of The Barrel triggers from Clay Barrel Extensions

### ISSUE THREAD

**Issue by MongoTheElder** [Darkosto/SevTech-Ages#133]
Stage 1 advancement Bottom Of The Barrel triggers from Clay Barrel Extensions that are a component of the Porcelain Heater. The config for the advancement (stage1/claybarrel.txt) doesn't include the metadata that separates the Clay Barrel (0) from Clay Barrel Extension (1).

```
setIcon("ceramics:clay_barrel")

setTitle("Bottom of the Barrel")

setDescription("Clay barrels can hold fluids, such as water or liquid metals")

setParent("triumph:stage1/emitter")
setRequiresParent(true)

criteria = addCriteria("hasRock", "minecraft:inventory_changed")

criteria.setItem("ceramics:clay_barrel")

setRewardExperience(4)

//By not setting anything about requirements here, all criteria are automatically required
```
I believe setting:
`criteria.setItem("ceramics:clay_barrel:0")`
fixes the problem

Alpha 4

**Comment by Darkosto** [comment]
Whoops! I'll get this fixed up! Thank you :)

**Comment by Darkosto** [comment]
Should be all good!
