### ISSUE TITLE
Recipe for Cardboard Box isn't staged

### ISSUE THREAD

**Issue by SephirothWS** [Darkosto/SevTech-Ages#1330]
## Issue / Bug
Recipe for the Cardboard Box from Mekanism isn't staged. The Cardboard Box itself is set to Stage 5.
![Image](https://i.imgur.com/CvPfSa3.png)

## Current Behavior
Cardboard Box can be crafted starting in Stage 1 when you get access to sawdust from Better With Mods.
![Image](https://i.imgur.com/XPRmQdX.png)

## Possible Solution
Stage the Cardboard Box recipe to Stage 5.

## Steps to Reproduce (for bugs)

1. Get Better With Mods Saw
2. Saw Logs into Planks
3. Use Byproduct Sawdust to craft the Cardboard Box.

## Your Environment

* Modpack Version: 3.0.4
* Java Version: Java 8 Update 161
* Launcher Used: Twitch
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by artdude543** [comment]
Fixed in dev :)
