### ISSUE TITLE
Inconsistent breaking with nether brick stairs

### ISSUE THREAD

**Issue by djnifos** [Darkosto/SevTech-Ages#1331]
## Issue / Bug
The 4 different orientations of a stair placed on the ground, not tested inverted, break differently in Age 3 with a tinker's iron pickaxe.  

## Current Behavior
![image](https://user-images.githubusercontent.com/2243466/38218611-fc49337e-3697-11e8-9afa-5b6d9abbed21.png)

The stair which is crudely circled is unbreakable.  The other three break normally.

## Possible Solution
Unify them, so that whatever the intended behavior is, it happens consistently.  I get the feeling that the one that isn't breaking is the one with the meta data to match a script.

## Steps to Reproduce (for bugs)

1.  Be Age 3
2. Find/place nether brick stairs in different orientations.  
3. Break them with a diamond level tool.   The one that you could walk up when walking **east** will be unbreakable.

## Your Environment

* Modpack Version: 3.04
* Java Version: 161
* Launcher Used: Jar
* Resourcepack Enabled?: Soartex Fanver
* Optifine Installed?: Yes

**Comment by Jandakast** [comment]
This appears to only impact Tinkers tools and only impacts nether_brick_stairs with a Meta value of 0. This is a pack script issue most likely because it does not happen in custom pack with only Tinkers, Tinkers Compliment, Tinkers Tool Leveling, and Tinkers stages. 

Currently testing some changes to attempt to fix this.

**Comment by djnifos** [comment]
I'll confirm that I was using a Tinker's tool.

**Comment by Jandakast** [comment]
Found a fix and added to configs.

- remove minecraft:nether_brick_stairs (line 25) from the "scripts\item_modifiers\hardness.zs" 
- update "config\pickletweaks.cfg" (line 258) to "minecraft:nether_brick_stairs:-1=2-pickaxe"
