### ISSUE TITLE
Are Geolysis ores allowed to overwrite Sandstone? No Coal ore in a desert chunk

### ISSUE THREAD

**Issue by Ambaire** [Darkosto/SevTech-Ages#1333]
## Issue / Bug
Coal ore is seemingly nonexistent in deserts

## Current Behavior
I found 4 coal samples in a desert chunk. I dug down to y50, crosshatched it and dug a tunnel around the edges and checked both top and bottom every 2 blocks. Zero coal ore detected. By 'crosshatching', I mean I dug a centered X across the chunk and a tunnel around the edge. I went back and dug another 4 X's in the 4 quadrants, no coal ore detected either. As well as at least 50 checks on the desert surface.

I ended up doing /oredistribution 30 0 80 and it didn't detect any coal ore, either.

Also, earlier I found a very miserly coal deposit of maybe 20 ore that was scattered around a bit of sandstone in the desert in a caved in area on the surface.

## Possible Solution
Unknown

## Steps to Reproduce (for bugs)
Try looking for coal in a desert.

## Context
Been trying to find coal ore in a desert and it seems like it has inconsistent spawning.

## Your Environment
* Modpack Version: 3.0.4

**Comment by Darkosto** [comment]
It's added now, should be fixed in 3.0.5! Thank you :D I'm also going to add blocks from Mesa biomes just incase.
