### ISSUE TITLE
Betweenlands Life Crystal ore is invisible/missing texture

### ISSUE THREAD

**Issue by bearY0** [Darkosto/SevTech-Ages#1335]
As you can see in the screenshots, life crystal ore is missing its texture.

![2018-04-03_01 18 31](https://user-images.githubusercontent.com/13459228/38220936-41d474cc-36dd-11e8-81e5-ee570efda483.png)
![2018-04-03_01 18 33](https://user-images.githubusercontent.com/13459228/38220938-45d9ca7c-36dd-11e8-9390-fd5066e9d4e1.png)
![2018-04-03_01 18 36](https://user-images.githubusercontent.com/13459228/38220941-48909138-36dd-11e8-9ecd-3b4baa948311.png)

* Modpack Version: 3.0.4
* Java Version: 1.8.0_25
* Launcher Used: Twitch
* Resourcepack Enabled?: No
* Optifine Installed?: Yes - OptiFine_1.12.2_HD_U_D1

**Comment by GoryMoon** [comment]
Related issue and possible fix Angry-Pixel/The-Betweenlands#441

**Comment by TheCyberBrick** [comment]
Yep, that's because Optifine. Should be fixed by setting fullbright blocks to false in the Betweenlands config.

**Comment by justinrusso** [comment]
Updated to https://minecraft.curseforge.com/projects/angry-pixel-the-betweenlands-mod/files/2548656

Will be in 3.0.5
