### ISSUE TITLE
Dowsing Rod Not Detecting Ores

### ISSUE THREAD

**Issue by marmot3k** [Darkosto/SevTech-Ages#1337]
## Issue / Bug
Just updated to 3.0.4 today hoping to find more gold and rock crystal samples, found out that the prospecting tool (Weak and Tough Dowsing Rod) does not detect any ores. Even when attempting to click on a known chunk, or even an Azurite ore itself with either rod it displays "nothing of interest up to 32". One weird thing happened at one point I saw a message stating "nothing of interest up to 48" before a restart, then back to 32 after the restart.

## Current Behavior
Attempting to use the dowsing rod displays no ores, even when directly using the rod on an ore. What should happen is it will list the amount and type of ore available underneath the player.

## Possible Solution
Unsure, maybe an issue with the prospector mod itself or a prospector/geolysis interaction.

## Steps to Reproduce (for bugs)
Not sure how to reproduce, issue started when I updated the pack to 3.0.4

## Your Environment

* Modpack Version: 3.0.4
* Java Version: 8
* Launcher Used: Twitch
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by TuCaNDmAn** [comment]
Not updated correctly? In 3.0.4 It should can upto 48 blocks per click.

**Comment by lolorz13** [comment]
I too get this issue with a fresh install in a chunk that has azurite samples

**Comment by 3jlowes** [comment]
Well "clicking on a known chunk" won't do anything if the ore is not in range. The example with Copper not being detected is weird.

**Comment by marmot3k** [comment]
Sorry what I meant was that Azurite was under me I know this because I've dug down to it and made sure I was in the same area of the ore. It had previously shown up in other versions but this time not so much.

**Comment by lolorz13** [comment]
Same, I was able to find it by digging down in the chunk but the rod was ineffective at locating it.  I checked a few channels on youtube to see if any youtubers talked about this and found this: [ChosenArchitect's channel](https://youtu.be/nB9JOC-8MpU?t=29m20s )

**Comment by Darkosto** [comment]
I just tested and cannot reproduce. Ores show just fine for me using any of the 5 prospectors.

**Comment by marmot3k** [comment]
![what happens](https://user-images.githubusercontent.com/8000218/38330214-cfa3087c-3804-11e8-9873-14ed1ae143ad.jpg)
![what also happens](https://user-images.githubusercontent.com/8000218/38330217-d12aeb88-3804-11e8-9136-f809028891d2.jpg)

I'm not sure how to reproduce but this is what it looks like when attempting to use the weak or tough dowsing rod if that helps.

**Comment by marmot3k** [comment]
Deleted the old install, and started a new map. The prospector now works and can detect ores below me. 
[Configs.zip](https://github.com/Darkosto/SevTech-Ages/files/1882558/Configs.zip)
I have included the configs to the previous and the new prospectors there is a bit of difference in formatting and I believe some options are different but I'm not sure if these will alter anything.
I believe this issue can be closed now.

**Comment by TalimK7** [comment]
I had something similar to this. Other aspects of the install were glitching, like tethers disappearing and horses and bison just being gone when I turned around, but the ore problem is what made me do a fresh install. My dousing rod could only detect coralium and coal, but none of the others. When I would find samples of tin or copper (with either of the names), I would just occasionally find coralium in spades but nothing else. It was like the ore deposits never spawned in.
