### ISSUE TITLE
Sawdust > 3x Plant Fiber Pulp

### ISSUE THREAD

**Issue by randomlypickedname** [Darkosto/SevTech-Ages#1339]
## Issue / Bug
One sawdust, one glue, and one water container (bladder, bucket, etc) recipe gives three plant fiber pulps, where all other recipes are one sawdust per plant fiber pulp.

## Possible Solution
Change output to 1x plant fiber pulp.

Modpack version: 3.0.4

**Comment by artdude543** [comment]
What recipe are you looking at here?

The main "crafting" recipe is the following: 

![image](https://user-images.githubusercontent.com/1885466/38245114-cd5ed512-3734-11e8-8d18-c0094dddcbb8.png)

And the machines give out 4 per craft and the basin is 3 per craft. Which are all balanced. All the recipes are 1 to 1 in regards to the saw dust.

**Comment by randomlypickedname** [comment]
The basin is 3x sawdust + 1x glue + 1 bucket water -> 3x Pulp, whereas the recipe is 1x sawdust + 1x glue + 1 bucket water -> 3x Pulp. Why would anyone bother with the basin here?

![2018-04-03_06 47 31](https://user-images.githubusercontent.com/37277745/38253409-6d5f31c6-370b-11e8-94bb-7c436c11e92e.png)
![2018-04-03_06 47 43](https://user-images.githubusercontent.com/37277745/38253411-6da2826e-370b-11e8-8f82-34b92b861552.png)

**Comment by justinrusso** [comment]
`"Why would anyone bother with the basin here?"`
Because its a stage 2 recipe while the basin is a stage 1 item. I'll leave it to @Darkosto to decide but to me, this was the reasoning why its like that.

**Comment by randomlypickedname** [comment]
Ahhh, that makes sense. My only counter point there is how it's only used for paper, which is in stage 2.

**Comment by artdude543** [comment]
This is going to be left as is; it's designed to be how it is we may overlook this again. But in terms of how the progression goes and such, this is an intentional design for the recipe.
