### ISSUE TITLE
White wool converts to oak planks

### ISSUE THREAD

**Issue by Grauldon** [Darkosto/SevTech-Ages#134]
> - Explain the issue / bug as understandably as possible.

Anytime I placed down a white wool block in the world, it is converted to oak planks.  When I break the block, the wool sound is used.  But, I still use the hatchet to break the block.  Furthermore, when I place the oak planks block in the world, it remains an oak planks block and uses the oak planks sound when breaking.

> - If possible add minecraft, forge, java and modpack version numbers for debugging (mod authors might need these).

Minecraft 1.12.1
Forge Mod Loader version 14.22.1.2485
Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_144 C:\Program Files\Java\jre1.8.0_144
Alpha 4

> - If the issue/bug is recurring explain how it can be recreated (helps darkosto!).

Kill sheep to obtain white wool.  Place wool block anywhere in the world.

>  - If possible add error/crash log to [Pastebin](https://pastebin.com/) and link it here (if you dislike pastebin any other similar site is fine too).

https://pastebin.com/W1Xzhkpx - Client Log
https://pastebin.com/BBgSbPJB - Launcher Log

**Comment by Crackerhead22** [comment]
Currently in Alpha4 the Animania goats are turned on.  They give wool blocks which they are not supposed to I believe.  I'm also assuming you are in Stage0, as the wool will turn into planks when place, and give planks when harvested.  This is normal, you don't access the wool blocks until Stage1.

**Comment by Grauldon** [comment]
Aha.  OK. I see.

Yes, I am in Stage0, and the wool blocks become available in Stage1.  Dawenzel pointed me to the oretiers.zs file and provided a similar explanation.

Thank you both, @Crackerhead22 and @Dawenzel, for helping me.

I'm closing the issue.
