### ISSUE TITLE
Looting Enchantment not working

### ISSUE THREAD

**Issue by unclekakarot** [Darkosto/SevTech-Ages#1343]
Not sure if intended or not but using the looting enchantment to get more loot from mobs doesn't work on certain drops/mobs. So far from what I can tell the Enderman and Blaze aren't affected. It may be intended but if not it's probably got something to do with having set mobs drop loot they don't usually drop.

**Comment by Gremilcar** [comment]
#1132

**Comment by unclekakarot** [comment]
Ok ok, weird searched for a looting issue and nothing came up, thanks for that,
