### ISSUE TITLE
Skillable Configs File is Still in Configs Folder

### ISSUE THREAD

**Issue by Vyraal1** [Darkosto/SevTech-Ages#1344]
## Issue / Bug
![image](https://user-images.githubusercontent.com/26587049/38226272-ad050aac-36c6-11e8-8d0b-a1ceb2ad13c1.png)

## Possible Solution
- deleting it

## Your Environment

* Modpack Version: 3.0.4

**Comment by artdude543** [comment]
Not really a bug or anything to be fair. We could be keeping it for if/when we add the mod back.
