### ISSUE TITLE
Magic map recipe doesn't match craftable

### ISSUE THREAD

**Issue by Hillage** [Darkosto/SevTech-Ages#1346]
Recipe for Twilight Forest map shows 8 paper in each slot
Crafts OK with single paper in each slot

Unsure if recipe is displaying incorrectly or if it let us craft in error.

* Modpack Version: 3.0.4
* Java Version: 1.8.0_161
* Launcher Used: Twitch Launcher
* Resourcepack Enabled?: Yes, Faithful, restarted client since enabling
* Optifine Installed?: No
![2018-04-02_21 00 14](https://user-images.githubusercontent.com/26056548/38228655-7427c3da-36b9-11e8-9acf-4bcad1aa9869.png)

**Comment by artdude543** [comment]
This looks like a visual bug/recipe bug but the recipe should only use "1" paper per slot anyway. So you're good 😄

**Comment by Targren** [comment]
Oh, good. I thought a whole stack of PITA-to-make paper just to make a map was a wee bit excessive. The Charms of Keeping for Journeymap was bad enough. :D

**Comment by artdude543** [comment]
Fixed in 3.0.6
