### ISSUE TITLE
Valus melon pirmal core does not show in JEI

### ISSUE THREAD

**Issue by daddy77gaming** [Darkosto/SevTech-Ages#1349]
Valus melon primal core does not show in JEI, version 3.0.4

![2018-04-03_09 45 20](https://user-images.githubusercontent.com/31905330/38239158-3f03723a-372c-11e8-9689-73c02860f460.png)

**Comment by justinrusso** [comment]
Where did you get this item from?

**Comment by Mack1410** [comment]
they are acquired by growing valus seeds on nether earth

**Comment by artdude543** [comment]
This will be fixed in 3.0.7. I've re-added the melon to JEI under S3 but the bread recipe has been disabled/removed. So it's only used is food as a melon. (This should be added to nutrition, but that's another issue) but in regards to this issue, it is resolved 🙂
