### ISSUE TITLE
savtech world keeps crashing

### ISSUE THREAD

**Issue by kiwimeister13** [Darkosto/SevTech-Ages#1350]
## Issue / Bug
my world keeps crashing when trying to load in
here is the crash report in parts
part 1
https://pastebin.com/Uw93HDLd
part 2
https://pastebin.com/NW6HadUF
part 3
https://pastebin.com/ff4XSt5z

## Steps to Reproduce (for bugs)
everyrime i create a world it crashes when it loads in the world

## Context
i cant start up a world so cant play this modpack for now

## Your Environment

* Modpack Version: 3.0.4
* Java Version: 1.8.0.161 (64 bit)
* Launcher Used: twitch
* Resourcepack Enabled?: no
* Optifine Installed?: no

**Comment by artdude543** [comment]
One your configs are broken; can you reinstall the pack/profile and I don't see any other logs relating to an "actual" crash, other than the normal errors (which are non-crashing) If your game did crash you should have a `crash-reports` folder if so can you pastebin the latest one (or delete all, load game) and then post that one.

Thank!

**Comment by kiwimeister13** [comment]
sorry i looked in the wrong file for the crash report but here is the actual crash report
https://pastebin.com/qWcYKcwK

**Comment by artdude543** [comment]
Can you disable foam fix for me and try again? (Note: Load up time may increase but we need to test this)

**Comment by kiwimeister13** [comment]
i disabled it but now it just exits my game and i get no crash reports

**Comment by kiwimeister13** [comment]
but i have the game output from the launcher if that helps?
https://pastebin.com/MCGU8tQX

**Comment by kiwimeister13** [comment]
i have changed from the jar launcher to the native launcher, and it seems to be working for now if anything happens i will let you know. thank you for al the help.

**Comment by kiwimeister13** [comment]
i could play for like an half hour and then it crshed my computer and now when i try to load a world it crashes my computer again

**Comment by artdude543** [comment]
tbh with you, the last log was a Java JVM crash so either doesn't have enough memory allocated to the game or even your entire PC. As your stating it's fine for so long and then crashes with a JVM crash like that I would assume you ran out of memory and/or your Java install is "broken" so maybe try re-installing Java and try again. But from a modpack perspective, this is a user error than the pack. So I'm going to close this for now. But feel free to update in the comments and I'll chime in when I can 😄

**Comment by kiwimeister13** [comment]
hey just got another crash with this rapport
https://pastebin.com/zcbNMr8b

**Comment by kiwimeister13** [comment]
i think i posted the wrong report again this should be the good one
https://pastebin.com/W55AAUAw
