### ISSUE TITLE
[3.0.4] [Age 4] Silicon samples and ore spawns, but silicon itself is unfamiliar item.

### ISSUE THREAD

**Issue by togreglove** [Darkosto/SevTech-Ages#1351]
## Issue / Bug
Age 4
Many small silicon ore veins are all over, but when you mine the silicon, the item itself is an unfamiliar item.
I assume it's supposed to be in age 4 since it's required for the RS controller, which is also age 4.

**Comment by justinrusso** [comment]
https://github.com/Darkosto/SevTech-Ages/issues/1008
