### ISSUE TITLE
Millstone Unfired Porcelain (3.0.3)

### ISSUE THREAD

**Issue by PebbyBoi** [Darkosto/SevTech-Ages#1353]
Hello!
I was just wondering if y'all could help me with this little issue we're having.
We updated our server to 3.0.3 last night and we're still not able to use the millstone to create unfired porcelain! Not completely sure what to do at this point. We updated all files, making sure that no old file wasn't replaced by a new one. Any idea as to why this might be happening?
Thank you for your time reading this in advanced. :)

**Comment by Jandakast** [comment]
I am able to create unfired porcelain using a Mill Stone on a server and in single player in version 3.0.4. I recommend updating to 3.0.4 and make sure you are powering the Mill Stone with a Hand Crank.

![image](https://user-images.githubusercontent.com/19498789/38247786-69361818-3714-11e8-8fd0-34c77c78a4ef.png)

**Comment by artdude543** [comment]
Update to 3.0.4 this solves the issue. Please check the tracker before posting bugs if it's already been fixed along with checking on the latest version :)
