### ISSUE TITLE
Duplicating Necronomicon 

### ISSUE THREAD

**Issue by PsyberMind** [Darkosto/SevTech-Ages#1355]
As if one evil book of the dead wasn't enough

## Current Behavior
Duplicating Necronomicon when breaking T1 Pedestal while book is on it

## Possible Solution
Not a major issue, just something that I noticed the other day, Self repair by replacing the pedestal, then placing both books on it, they recombine to one

## Steps to Reproduce (for bugs)
Haven't been able to reproduce yet, as I am still new to Abyssalcraft, and was unaware of the lightning strike, which.. destroyed most of my setup after converting it to Dark Plains land -_-

However, if you place the Necronomicon on top of the First Tier pedestal, and then break the pedestal, you get 2 copies of the book back. Simply replacing the pedestal, and then the book on it will remove the dupe, and life goes on

* Modpack Version: 3.0.4
* Java Version: 1.8
* Launcher Used: Twitch Launcher files, copied over to a MultiMC Instance
* Resourcepack Enabled?:  Soartex Fanver Modded Universal
* Optifine Installed?: No

**Comment by justinrusso** [comment]
Curious if its just client side. Would relogging make it disappear?

**Comment by PsyberMind** [comment]
Get out of my head.. I had just tried it again, it didn't dupe this time.. can close
