### ISSUE TITLE
Black Quartz Sword Disappearing When Tp to Beneath

### ISSUE THREAD

**Issue by IWriteAnarchy** [Darkosto/SevTech-Ages#1356]
When teleporting to the beneath with a black quartz sword in hand causes it to disappear, when sorting inventory with middle mouse button it reappears.  

![issue](https://user-images.githubusercontent.com/37946862/38262367-07b004f6-373b-11e8-8adb-591502ae0313.gif)

* Modpack Version: v3.0.4
* Java Version: 1.8.0_25
* Launcher Used: Twitch/native
* Resourcepack Enabled?:Yes (Faithful+1.12.2-rv4)
* Optifine Installed?:No

**Comment by ragehugs** [comment]
This issue exists with any dimension change and equipped gear it seems. Might not only be visual as it disables rubber boots jump portion from working (you do not take fall damage - just no longer bounce). Clicking empty gear slot pops the item on your cursor.

**Comment by 3jlowes** [comment]
#1150 this bug has already been reported

**Comment by IWriteAnarchy** [comment]
Alrighty.
