### ISSUE TITLE
Hunger Bar no longer works after latest update. It remains full at all times.

### ISSUE THREAD

**Issue by MsTaz25** [Darkosto/SevTech-Ages#1358]
After updating to the latest version of the pack, my hunger bar no longer goes down and therefore I can't eat to keep my nutrition up.  I tried running around, jumping, fighting mobs letting them hit me, etc., but nothing makes the hunger bar go down.  I also used the millstone with the hand crank attached and the bar still doesn't go down.

I deleted my player data thinking that may help, but it did not.  When I hold food it shows the possible saturation for it, but it does not allow me to eat it.  The hunger bar remains full but with no saturation.  I ate rice bread (I think that was the one).  It gave me full saturation, but once the saturation went back down to 0, the hunger bar still stayed full.

Is there something I need to check to see if it is causing this or is there something that I should delete?  It is the same way in more than one world.  I created 2 others just to see if maybe it was that one world in particular but it is not.

Any help would be greatly appreciated.

Ms Taz

## Your Environment

* Modpack Version:  Latest
* Java Version:  Latest
* Launcher Used:  Twitch
* Resourcepack Enabled?:  None
* Optifine Installed?:  No

**Comment by 3jlowes** [comment]
Make sure you are not playing on peaceful. Hunger not going down is a peaceful mechanic.

**Comment by MsTaz25** [comment]
@3jlowes I checked that and even switched it from normal to hard, but it is still stuck.

**Comment by 3jlowes** [comment]
Weird. if it is not just the world you are playing in, try moving your save to a new instance of the pack. Maybe something in your current instance is wrong if it happens in every world you create.

**Comment by MsTaz25** [comment]
@3jlowes Would switching into Creative and back cause something to break?  I did that once but the hunger bar still worked after.  I loaded up the world again after shutting things down for the night, and then the bar was broken.  Maybe I should uninstall and reinstall everything and start a new world after that.  I don't want to have to start over again though :-(

**Comment by ComaCanadian** [comment]
do you have the vicio attunement from astral sorcery?

**Comment by MsTaz25** [comment]
No I haven't gotten that far yet. Still at the start of Age 1.


Sent from my Galaxy Tab® S2
-------- Original message --------From: ComaCanadian <notifications@github.com> Date: 4/4/18  8:25 AM  (GMT-05:00) To: Darkosto/SevTech-Ages <SevTech-Ages@noreply.github.com> Cc: MsTaz25 <msnewby1974@gmail.com>, Author <author@noreply.github.com> Subject: Re: [Darkosto/SevTech-Ages] Hunger Bar no longer works after latest update. It remains full at all times. (#1358) 
do you have the vicio attunement from astral sorcery?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Darkosto/SevTech-Ages","title":"Darkosto/SevTech-Ages","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Darkosto/SevTech-Ages"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ComaCanadian in #1358: do you have the vicio attunement from astral sorcery?"}],"action":{"name":"View Issue","url":"https://github.com/Darkosto/SevTech-Ages/issues/1358#issuecomment-378581639"}}}

**Comment by lurch9229** [comment]
I also have the same problem, have tried all sorts to fix it but no luck, really is a game breaking bug, might have to disable the config for nutrition until a fix has been found, hopefully in the next update.

**Comment by artdude543** [comment]
This issue has never been reproducible with "fresh" worlds and players not using/holding items which allow you to feed "less". Based on the testing we have done this issue is not an issue with the pack itself but an issue on the users end. Either world game rules change or servers with custom settings etc... along with you using an item which gives you free food etc...

All I can suggest it make sure you don't have anything custom installed, game rules are the default and if playing on servers that the owner has not changed any gameplay settings.

But this is point blank not a vanilla pack issue. There is nothing much more we can do to help.

**Comment by lordammon** [comment]
I too am having this same issue. It is sad that people are just dismissing it. This is not a user end issue, please reopen this and continue to do testing. If needed I can send you a copy of our server files for testing.
