### ISSUE TITLE
Betweenlands Advancement "You are what you eat" cannot be obtained

### ISSUE THREAD

**Issue by andrew1815** [Darkosto/SevTech-Ages#1359]
## Issue / Bug

The advancement "Mr. compost" on the farmer page and the advancement "you are what you eat" on the survivalist page, are not activating.
## Current Behavior

 when I compost in the compost bin and get compost nothing happens and I have tried multiple items, and I cant get normal food to turn into rotten food when I'm in the betweenlands.

## Your Environment

* Modpack Version: 3.0.4
* Java Version:1.8.0.161
* Launcher Used:twitch
* Resourcepack Enabled?:no
* Optifine Installed?:no

**Comment by GoryMoon** [comment]
To get the "Mr. Compost" you need to use the compost on a "dug dirt" and regarding the "You are what you eat" food rotting have been disabled for all food items in the pack.

**Comment by andrew1815** [comment]
so is it possible to get "You are what you eat" or should I just ignore it

**Comment by justinrusso** [comment]
Since food rotting is disabled, the player cannot obtain  the "You are what you eat" advancement. Should we remove this advancement?

**Comment by Jandakast** [comment]
This looks to be a default Betweenlands advancement. Not sure we can remove it without having to recreate the entire Survivalist Section. Could we just give the player a piece of rotten food when the player crafts the Weedwood Sword or maybe add the rotten food as a rare drop to the Betweenlands Frog mob using incontrol?

**Comment by GoryMoon** [comment]
The advancement is triggered when the player eats the rotten food, so just making the player get the item and making them understand to eat it would be enough.
Another way would be to have some specific food not work and instruct the player those don't work in BL.
I think the first option and what Jandakast said would be the best one.

**Comment by justinrusso** [comment]
I agree. If we cant modify it, which I’m realizing we cant, we should make it somehow available to be completed. If we keep those advancements in, we should try our best to make them still complete-able

**Comment by Stormfirebird** [comment]
Wildberries are the thing you're looking for, they definitely turned to rotten food in 3.04 for me.

**Comment by oOMitchOo** [comment]
Two people already replied with (working) solutions to your problem.

I still want to emphasize: **Those advancements are from the mod, not from SevTech!**
Only the advancement pages "SevTech: Ages Tutorial", "Welcome to Age 1", "Age 2" and so on are from the modpack.

I think this issue is closed.

**Comment by Darkosto** [comment]
Added Rotten Food to most mob's drop lists when killed so you can still acquire it.
