### ISSUE TITLE
Hydra can break the grave 

### ISSUE THREAD

**Issue by saqrion** [Darkosto/SevTech-Ages#1361]
Hey Darkosto, 
When I fight with Hydra I was killed. My friends saw that grave had spawn. But when I came, I could not find grave. Then I get know that Hydra breaks the blocks (including the grave) that prevent it.
I hope you can do something (make grave unbreakable or something else).
And thanks for fabulous modpack ❤️  

Modpack Version:3.0.4
Java Version: 1.8.0_161-b12
Launcher Used: Native
Resourcepack Enabled?: Yes
Optifine Installed?:No

**Comment by Ogini** [comment]
See #1144 as well
