### ISSUE TITLE
World reset, inventory and backpack items, unlocked items in JEI and advancements have remained.

### ISSUE THREAD

**Issue by tlbrierley** [Darkosto/SevTech-Ages#1366]
## Issue / Bug
Updated Java to play pack in first place (Not sure if relevant). Updated pack yesterday and played for a few hours with no issues. logged in today to find myself buried in terrain and world has reset to origional state but left all items and progress intact.

## Possible Solution
Thought it was worth making this a known issue. seems more of an unlucky but unrepeatable problem.

## Steps to Reproduce (for bugs)
Unsure.
1. Updated through curse launcher with no issues.
2. played and saved at end of night.
3. reloaded following day to see world reset.

## Context
Couldn't find anyone else mentioning the issue, thought it may be worth being the first in case any others fail to mention and assume no one else has it as i did at first.

## Your Environment

* Modpack Version: 3.0.4
* Java Version: 1.0.8.20 64bit
* Launcher Used: Twitch launcher (7.5.6659.42546)
* Resourcepack Enabled?: N/A
* Optifine Installed?: No

**Comment by justinrusso** [comment]
Your java version is extremely outdated. The current is 1.0.8.162.

Sounds like a computer kinda issue. Your pc couldnt write the data for some reason. Will leave open for a bit to see if anyone else has some input.

**Comment by artdude543** [comment]
Closing this as it's an old issue and to me sounds like a user error/issue. The pack won't randomly remove things from the world or move players.
