### ISSUE TITLE
After updating to 3.0.4 i am unable to progress in the pack, none of the quests in the ages will complete

### ISSUE THREAD

**Issue by Tidalsniper** [Darkosto/SevTech-Ages#1367]
## Issue / Bug

The quest log on the ages won't progress further after i recently updated to 3.0.4, nothing else is having issues expect for the quest page not progressing when i finish what it asks of me. I'm not crashing or anything it simply won't continue.

Here's the imgur link with pictures of the issue: https://imgur.com/a/VQn2C

## Steps to Reproduce (for bugs)
All i did was update my server to 3.0.4 i've had no errors or crashes

## Your Environment
* Modpack Version: 3.0.4
* Launcher Used: Twitch App
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by pmotaPT1971** [comment]
Same happens to me in 3.0.4.
I've also started a new server, same problem.
Also I get a mod error, server pack has Geolosys-1.12.2-1.8.8c.jar while client has .10b . I've replaced client with the older one. I have NOT tried the other way round, changing the server mod. Just FYI, no idea if it is related to the no progression issue. (I can't even collect fibers from grass: no achievements and when I pick them they get dropped back as unfamiliar items).
nope this helps.
Also:
    Modpack Version: 3.0.4 (server pack and client pack; except for 1 mod as stated above)
    Launcher Used: Twitch App
    Resourcepack Enabled?: No
    Optifine Installed?: No

**Comment by Jandakast** [comment]
@Tidalsniper What version did you upgrade from? Your advancements screenshot has things in a different position/order than a fresh 3.0.4 download and world for me. I've attached a screenshot of my Stage 1 Advancements from my fresh 3.0.4 instance. You may need to reset your player data and advancements or restart a world.

@pmotaPT1971 It sounds like your client, server, or both did not update correctly. I would suggest downloading the pack to a new instance and trying again. 

![image](https://user-images.githubusercontent.com/19498789/38281686-d65c5046-3779-11e8-8f12-8c9b2a48aeee.png)

**Comment by artdude543** [comment]
Closing as we asked for information nearly over a month ago. If this is an issue still in 3.0.7 _(when released)_ please make a new issue following the template and providing as much detail as you can.
