### ISSUE TITLE
Mending Enchantment

### ISSUE THREAD

**Issue by unclekakarot** [Darkosto/SevTech-Ages#1369]
Been spawning and trading with multiple villagers in a creative world to see if they sold the mending enchantment but after about an hour of doing so haven't found a single one. Wondering if the enchantment is disabled or just not in the pack.

**Comment by Jandakast** [comment]
Fishing loot tables have been cleared and Villagers all have custom trades. I am not sure this enchantment is attainable currently.

**Comment by SuohKami** [comment]
I've enchanted over 200 books haven't gotten it, re-checked my nearby villagers for possible trade reset in Age 3, but no go. Will try new chunks to see if I can find it as a trade.

Unfortunately I've had to cheat mending books in since I got tired of my gear breaking constantly.

**Comment by unclekakarot** [comment]
Yea the only way to get it was villagers and fishing and since fishing loot tables are cleared and villagers have custom trades, i'm guessing it's not attainable.

**Comment by Decompress** [comment]
Use Astral Sorcerys stellar refraction table for this enchant in Age 2

**Comment by unclekakarot** [comment]
Can confirm this works ^
