### ISSUE TITLE
Advancements setRequiresParent(true)

### ISSUE THREAD

**Issue by Dawenzel** [Darkosto/SevTech-Ages#137]
## Bug
There are multiple advancements missing the `setRequiresParent(true)` line in their script. This allows these advancements to be completed before getting to that stage. 
These are the advancements that I found:
### Stage 0 
- 
### Stage 1

- Plumbing the Depths(plumbline.txt)
- Pedestalling for Time(pedestal.txt)

### Stage 2

- Defeat the Endermenace!(enderman.txt)

## Possible Solution
Adding the `setRequiresParent(true)` line should fixes most problems. The pedestal advancement could use a different block as it's criteria like a crafted `<abyssalcraft:energypedestal>`.

## Versions
- Minecraft 1.12.1
- Forge 14.23.0.2512
- Java x64 8u144
- Sevtech-Ages Alpha 5

**Comment by Darkosto** [comment]
All fixed, thanks!
