### ISSUE TITLE
Radial Equipment menu broken 

### ISSUE THREAD

**Issue by Gridoverflow** [Darkosto/SevTech-Ages#1370]
The radial equipment menu does not work in sevtech. It is bound to LMENU on default however it does nothing, when rebinding it doesn't work either.

**Comment by Jandakast** [comment]
I am assuming you are talking about Chisel and Bits Radial Menu? If so I cannot reproduce this issue. I am running 3.0.4 in SP and on a server. I am able to use left ALT (LMENU) or a custom keybind. The Radial Menu only appears if you are holding a Chisel, Bit, Tape Measure, or Design item from the Chisel and Bits mod.

**Comment by justinrusso** [comment]
Closing as a stale issue
