### ISSUE TITLE
Cant get totem ceremonies to work

### ISSUE THREAD

**Issue by Drummerboyno** [Darkosto/SevTech-Ages#1371]
I am unable to complete any of the totem ceremonies, the bar that shows the compliment will stop and no longer continue to fill. I have tried different ways of playing the instruments but it still dost work, is their a trick to doing this? Of is it something else?

**Comment by daddy77gaming** [comment]
once selected the type.. you can use any and all different available insturments! the more the better even. no need to stick with only the ones to be selected for the ritual. Also look into the jingle dress place multiple drums, chimes.. and then flute while hopping around hitting the drums.. all will go well ;)
