### ISSUE TITLE
Shift + S makes you go forward in the air

### ISSUE THREAD

**Issue by N00byEdge** [Darkosto/SevTech-Ages#1372]
## Issue / Bug
If you're in the air, crouch + walking backwards makes you go forward
Video: https://youtu.be/5dEqqeYkTDE
In the video I'm holding down S and shift and pressing space regularly.

## Steps to Reproduce (for bugs)
1. Enter any world
2. Hold down and keep holding crouch and move backwards keys.
3. Press space.
4. In your jump, you will go forward.

## Your Environment

* Modpack Version: 3.0.4
* Java Version: 1.8.0_161
* Launcher Used: AT Launcher
* Resourcepack Enabled?: Yes, Faithful32
* Optifine Installed?: No

**Comment by Jandakast** [comment]
This is caused by the Totem Bat buff effect. This is not an actual issue.
