### ISSUE TITLE
advice needed : Lava

### ISSUE THREAD

**Issue by extrenix** [Darkosto/SevTech-Ages#1375]
is it possible to make a lava source in my base with this modpack or do I need to fill 56000 buckets from a distance source ?

**Comment by daddy77gaming** [comment]
you can find lava samples with IE.. use a pumpjack to pump into a tank

**Comment by extrenix** [comment]
this must be age 3 or above?

**Comment by daddy77gaming** [comment]
Yes IE is age 3

**Comment by extrenix** [comment]
ok thanks

**Comment by justinrusso** [comment]
This place is used for suggestions and issues.

Discussion can be found here: https://discord.gg/darkosto
