### ISSUE TITLE
save and exit crashes when open to LAN

### ISSUE THREAD

**Issue by crazydud24** [Darkosto/SevTech-Ages#1376]
## Issue / Bug

when exiting a single player that has been opened to LAN the game will freeze and become unresponsive forcing me to close the window where it gives me a crash report that I am unable to open. 

## Current Behavior

after opening a world to LAN and eventually deciding to log off more often than not minecraft will become unresponsive and I've waited 10 minutes without it coming back so I always have to close the window.

## Possible Solution

I have no idea what a solution may be but I have a few notes that may help
1.  I hightly doubt its a ram problem considering I am allowing it to use 10 gigs of the stuff.
2. Even when immediately closing the game after opening to LAN with no players joining it will still crash
3. Its not a guarantee chance for it to crash. It seems to crash around 80% of the time and I cannot find any way to noticeably change the odds.

## Steps to Reproduce (for bugs)

1. open a minecraft world
2. open to lan
3. press the save and exit

## Context

the main world I play on has cheats turned off but on occasion something like the hydra destroying the gravestone that another report mentioned I will open to LAN and turn on cheats so that I dont have to deal with some of the glitches or various other annoying things that I dont wish to deal with.

## Your Environment

* Modpack Version: 3.04
* Java Version: 1.8.0_131
* Launcher Used: twitch
* Resourcepack Enabled?: no
* Optifine Installed?: No, I have not touched the files beyond creating the occasional world backup

**Comment by artdude543** [comment]
Please, can you give us your logs! The template does tell you to provide them. Even the normal client logs will help us understand what's going on.

**Comment by crazydud24** [comment]
And of course this happens. Last night I filled out the bug report and went to bed, in the morning I saw artdude543's request for the logs and now I cant replicate the crash. If I can get it to happen ill post the log but its been about an hour and I have failed to replicate it.

**Comment by artdude543** [comment]
Looks like your MC install has a broken launch wrapper. Try a fresh install on the Twitch launcher or repair your Minecraft by clicking the `Repair` button under the `...` options for the modpack. But I don't see anything relating to a pack issue. But maybe something in 3.0.7 will help but I have doubts it was the pack.
