### ISSUE TITLE
Crash with steams and farseek

### ISSUE THREAD

**Issue by redparry** [Darkosto/SevTech-Ages#1377]
## Issue / Bug
Crash on world gen when flying around in creative mode.
https://pastebin.com/P7mtCYBC

## Current Behavior
Crashes when generating rivers.

## Possible Solution
Issue has been raised with developer, https://github.com/delvr/Farseek/issues/37 the suggesting is rolling back forge version. A fix to farseek is being developed.

## Steps to Reproduce (for bugs)
I don't really know the best way with a fresh world. I can send the world if that would help.

## Context
Trying to find copper during phase 1

## Your Environment
* Modpack Version:3.0.4
* Java Version:1.8.0_161
* Launcher Used:Twitch
* Resourcepack Enabled?:Nope
* Optifine Installed?:No added

**Comment by justinrusso** [comment]
Updated! Should be in 3.0.5
