### ISSUE TITLE
Unable to fire "Unfired Crucible"

### ISSUE THREAD

**Issue by Shock2k** [Darkosto/SevTech-Ages#1378]
## Issue / Bug
Have tried to fire the unfired crucible with:
1) Small Kiln
2) Large Kiln
3) Grill
4) Seared Furnace
5) Double Furnace (from Beetweenlands)

None work.

## Current Behavior
Can't fire this item in Age 2.

## Possible Solution
Not sure

## Steps to Reproduce (for bugs)
Just attempt to fire it in anything in Age 2.

## Context
Is this useable in age 2?

## Your Environment

* Modpack Version: 3.0.4
* Java Version: 1.8
* Launcher Used: Twitch
* Resourcepack Enabled?: Yes (Soartex)
* Optifine Installed?: Yes

**Comment by daddy77gaming** [comment]
you will need the multiblock kiln from better with mods :)
with a hibachi underneath and a bellow causing it to burn blue. 
I suggest watching some YT tutorials on it.. if you never build a setup you wont get it to work without

![2018-04-04_00 44 22](https://user-images.githubusercontent.com/31905330/38281204-b8cc0d98-37a9-11e8-8a84-b649d885e5eb.png)

**Comment by daddy77gaming** [comment]
sidenote.. a kiln is already valid with a couple brick blocks
block above the flame place your item on that block and have that air block (where you place your items) covered on minimum 2 sides and the top

sidenote 2.. you are going to need to set it up for progression anyways cause you will not be able to get netherbrick any other way

**Comment by Shock2k** [comment]
Cheers, I really appreciate the reply.  This obviously is not a bug. :)

This is my first time doing mod'd Minecraft.  I usually do a youtube lookup, which I should have done here.  

Much appreciated, thanks!

**Comment by artdude543** [comment]
Closing as this is resolved.
