### ISSUE TITLE
[Issue] Nausea is so evil it hurt you irl.

### ISSUE THREAD

**Issue by Leosky** [Darkosto/SevTech-Ages#1379]
## Issue
* The visual effect of the nausea buff is provoking retinal migraine quite quickly if i look my screen few second during the visual. I usually watch away when it happen but it's quite hard when you try to survive. There is no big health danger but its quite annoying to have to stop every few hour of game when you meet those nasty creepers...

## Context
* I'm currently sensible to Retinal migraine. It cause visual and audition aura (difficult to explain), right or left side of body insensibility and big lost of mental capabilities (speaking, focus and memory difficulties).
* I also encounter that in ARK that have a similar hallucination effect with chromatic alteration (and it's worst).

## Your Environment
* Modpack Version:3.0.4
* Java Version: 1.8.0_161
* Launcher Used: meh
* Resourcepack Enabled?:no
* Optifine Installed?:no

**Comment by Leosky** [comment]
It wasn't a troll btw. I really experience that and make the pack pretty unplayable for me. Idk if there is a way to disable or to tweak it down.

**Comment by justinrusso** [comment]
This is default minecraft behavior... We dont make the nausea effect any different

**Comment by Leosky** [comment]
wait, what give that in minecraft vanilla ?

**Comment by artdude543** [comment]
The Nausea Effect is default in [Vanilla](https://minecraft.gamepedia.com/Status_effect#Nausea) and we can't change that at all. I don't think there is a mod which does changes to help with your symptoms. But you could try logging an issue on the Mojang Tracker or send a support email. But other than that we can't do anything on our side. Unless a mod is created/provided and we looked into it more.

**Comment by Jandakast** [comment]
There are Nausea effects in Vanilla that you get from Nausea potions. More of a PvP thing in Vanilla IMO. This pack doesn't modify the effect, but it does introduce more ways of getting nausea. 

There is a Mod called nonausea on Curse that you could potentially add that could fix this for you. Although if you add a mod and run into any issues/bugs you will need to remove the mod and test before reporting the bug.
