### ISSUE TITLE
Golem advancement

### ISSUE THREAD

**Issue by Dawenzel** [Darkosto/SevTech-Ages#138]
## Issue
The spawn chance of the `ancient_golem` has been significantly lowered by the addition of the `rainbow_golem`  from emberroot Zoo(I guess). This makes it very hard to actually kill the right type of golem for the advancement.
(Apparently Incontrol also denies the spawn of `ancient_golem` entirely)

## Possible Solution
Adding the `emberroot:rainbow_golem` as a 2nd criterion to the advancement would fix this issue.

## Versions
- Sevtech-Ages Alpha 5

**Comment by Darkosto** [comment]
The issue lies in only the advancement, Embers golems are severely broken and meant to be removed from the game. Thanks for the issue.
