### ISSUE TITLE
Ring of Ascent causes EXP Dupe

### ISSUE THREAD

**Issue by SuohKami** [Darkosto/SevTech-Ages#1380]
EXP resets back to original higher EXP after double tapping space to use the Ring of Ascent. So far I've only encountered this after using the Enchantment Table and Anvil to reset my EXP and continue on enchanting. 

Example: I have 93 levels, I enchant books until I have 29 and lose the level 30 enchant. I exit the table and double tap space to levitate with the Ring of Ascent and boom, full 93 levels again. Repeat as needed to enchant all the gear

Not sure if this is purely a Betweenlands issue or a combo of mods.

## Your Environment

* Modpack Version: 3..0.4
* Java Version: 1.8.0.161
* Launcher Used: Twitch
* Resourcepack Enabled?: Faithful 32x and Faithful Modded 32x
* Optifine Installed?: No

**Comment by GoryMoon** [comment]
Should be fixed with https://github.com/Angry-Pixel/The-Betweenlands/commit/63320a3434d32be74a9425a325f045f32456e8e2

**Comment by justinrusso** [comment]
Updated to https://minecraft.curseforge.com/projects/angry-pixel-the-betweenlands-mod/files/2548656

Will be in 3.0.5
