### ISSUE TITLE
Build craft pipes not staged correctly.

### ISSUE THREAD

**Issue by MyApolloGees** [Darkosto/SevTech-Ages#1381]
in stage 3 you can craft sandstone fluid pipes but not sandstone transport pipes

![image](https://user-images.githubusercontent.com/37778378/38282753-b507df48-37a9-11e8-944b-a8d30c45bb98.png)
![image](https://user-images.githubusercontent.com/37778378/38282761-c0b9656e-37a9-11e8-9688-10d2a35e8085.png)

**Comment by artdude543** [comment]
Fixed for the next release.
