### ISSUE TITLE
Crash when loading the Betweenlands

### ISSUE THREAD

**Issue by PasoLeaute** [Darkosto/SevTech-Ages#1385]
## Issue / Bug
The pack is crashing any time I try to load into the Betweenlands dimension with a 'An unexpected error has occurred and the game has crashed.  We're sorry for the inconvenience' message.  I'm not seeing any crash logs generated or errors in the log. It's happening in both my single player world and on the server I'm playing on.  On the single player world when I reload it puts me back in the overworld just before I went through the portal.  I'm not able to load the multiplayer instance at all.  On the server instance I am able to get the dimension to load for a short period after multiple tries, but it crashes again in just a few minutes.  Attached latest log.
[latest.log](https://github.com/Darkosto/SevTech-Ages/files/1874189/latest.log)

## Your Environment

* Modpack Version: 3.0.4
* Java Version:  1.8.0_25
* Launcher Used:  Twitch
* Server/LAN/Single Player: Both
* Resourcepack Enabled?:  No
* Optifine Installed?:  No

**Comment by justinrusso** [comment]
Try updating your Java version. 

Go to settings > Minecraft and select "Jar Launcher" as the Launcher and "Latest Java Version" as the Java version. Check what version of Java you have installed on your pc - the latest version is 1.8.0_162

**Comment by PasoLeaute** [comment]
Updated to 1.8.0_161.  Was the version the updater picked.  Still crashing, but got a better error log.  See attached. 
[hs_err_pid8056.log](https://github.com/Darkosto/SevTech-Ages/files/1874294/hs_err_pid8056.log)

**Comment by vadis365** [comment]
Hello,
This issue could possibly be if you are running an integrated Intel GPU, we have had similar reports in the Betweenlands issue tracker due to out dated drivers. Could you possibly update your graphics drivers and report back if it fixes the problem for you?
Cheers,
Me.

**Comment by TheCyberBrick** [comment]
Yeah, that's an Intel driver crash and not necessarily a fault in the code.
Since I don't have the hardware to reproduce this I'll need your help to test out some workarounds. I'll let you know once a build is ready to test.

**Comment by PasoLeaute** [comment]
I updated my display drivers and that seems to have fixed it!  Thanks for the help guys!
