### ISSUE TITLE
endless island generation 

### ISSUE THREAD

**Issue by MasterKairi0** [Darkosto/SevTech-Ages#1386]
every single time i generate a map in sevtech pack it creates a bunch of endless islands.....this is annoying ive tried 45 plus times  it doesnt do it in regular minecraft though so it has to be the pack

**Comment by oOMitchOo** [comment]
What do you mean by endless islands?

The modpack has some presets for the world generation. Before you start a new world, you can click on the button "More World Options..." and change it from realistic to default, but I would recommend you not doing this. The modpack is intended to be played this way. You can always play vanilla Minecraft for an authentic experience.

Also: You're not giving very much information. The "Instructions on how to do issues..." are there for a reason.

**Comment by MissPotato** [comment]
This modpack isn't a skyblock, or ocean-block modpack. The default terrain gen is closer to what you should be expecting.

**Comment by MasterKairi0** [comment]
yea ill keep trying i might be unlucky
but yea islands that go on forever  little islands
thats what it makes for me
