### ISSUE TITLE
Witch in Age 1?

### ISSUE THREAD

**Issue by JackRuby1** [Darkosto/SevTech-Ages#1389]
I just encountered and killed a witch in Age 1, inside of an infected swamp, she proceeded to drop me glowstone, and sugar.  I've never seen a witch before in Age 1, so putting up an issue encase it's a bug.

* Modpack Version: 3.0.4
* Java Version: Latest 8 version
* Launcher Used: Jar
* Server/LAN/Single Player: server
* Resourcepack Enabled?: Soartex Fanver Modded
* Optifine Installed?: no

**Comment by artdude543** [comment]
This is intentional for them to be at the stages. As they part of the world and/or other mods use them for structures.
