### ISSUE TITLE
Crash when right clicking a npc from the caravan

### ISSUE THREAD

**Issue by TieMonkey** [Darkosto/SevTech-Ages#139]
### Issue / bug
Hard to say what happened, Caravan showed up and I was living under ground, I dug a stairway up and one of them fell in so I right clicked him to see what he had and the game crashed.

Crash Log here https://pastebin.com/mxTpY9yn

**Comment by Darkosto** [comment]
Caravans ended up being removed from the pack due to a number of issues, thank you for the report though! :D
