### ISSUE TITLE
Etching acid

### ISSUE THREAD

**Issue by steinjorn** [Darkosto/SevTech-Ages#1390]
Etching acid bucket doesnt show when searched for in jei.
 
* Modpack Version:3.0.4
* Launcher Used: Twitch
* Server/LAN/Single Player: SP
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by oOMitchOo** [comment]
I can confirm this.

You can find the recipe by looking at pressure chamber recipes, but the etching acid bucket itself isn't listed in JEI.

**Comment by Darkosto** [comment]
This SHOULD be good in 3.0.5, but I need to do some beta testing before-hand to confirm.
