### ISSUE TITLE
[3.0.4] Pneumatic Drill should be tier 4?

### ISSUE THREAD

**Issue by togreglove** [Darkosto/SevTech-Ages#1394]
Putting together my pneumaticraft laser etching system and need to set one of the io units to output. As far as I know, this is done with the pneumatic wrench, which is not in this age it seems.

**Comment by oOMitchOo** [comment]
If there is more information in the title than in the text itself, you're doing it wrong.

Do you mean this pneumatic wrench?

![](https://i.imgur.com/3S8Ohzb.png)

It's in stage four in SevTech 3.0.4!

**Comment by ArcticWhiteFox** [comment]
The wrench itself is in-fact in stage four. The problem is that the recipe itself is invisible. If you place the correct items in the crafting table it'll work per usual.

**Comment by togreglove** [comment]
I can't find it in JEI, how do you get the recipe?

**Comment by oOMitchOo** [comment]
I searched for **"@pneu wrench"** in JEI and found it. It wasn't invisible to me.

**Comment by togreglove** [comment]
Many thanks! I still think this should be fixed, but that solves it for me.

**Comment by artdude543** [comment]
This issue is resolved in a newer version of the modpack.
