### ISSUE TITLE
Rock crystal sample not spawning

### ISSUE THREAD

**Issue by pambo3** [Darkosto/SevTech-Ages#1395]
## Issue / Bug
To get started with astral sorcery I desperatly searched an area of ~1500x1500 blocks for the rock crystal sample and then even flew around for another hour to generate new terrain but i couldnt find a single sample. Are they that rare? I found plenty of gold/iron/copper/... The rock crystal sample is the only one not shown in JEI so im wondering if its still locked and i just cant see it. Is there a way to check whats locked and whats not?

## Possible Solution
Tell me to keep searching because it sure will be around the next corner. 

## Your Environment

* Modpack Version: 3.0.4
* Java Version: 8
* Launcher Used: Twitch App
* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: No
* Optifine Installed?: Yes

**Comment by therodet** [comment]
I am also stuck at this point.

**Comment by oOMitchOo** [comment]
At least two crucial information bits are missing:
* With which modpack version did you start your world? Did you explore much of your world beforehand?
* In which stage are you right now? What are the latest purple advancements you did complete?

_Sorry, for my english... I'm not a native speaker._

**Comment by pambo3** [comment]
I believe I started my playthrough in 3.0.2 and updated to 3.0.3 at some point during age 1. I recently went to age 2 and updated to 3.0.4 right after unlocking the new age 2 advancements (but havent completed any). I explored a fair bit of my world before 3.0.4/age 2 but that didnt seem to be a problem for gold/lapis/iron veins since i found them in already generated chunks.

**Comment by therodet** [comment]
I started with 3.0.3, and updated to 3.0.4 during Age 1. No purple advancements made yet in Age 2, as the only one available is 'Filling the Gaps', which requires Constellation Paper, which requires the rock crystals (unless I've missed something there)

**Comment by oOMitchOo** [comment]
I'm citing the 3.0.4 patch notes of the modpack here:
* Ore samples now spawn underwater
* Geolosys updated to significantly improve their generation so it does not get overwritten by another block or feature and remove the ore. Also, more stone has been properly added to the config to allow veins to spawn in other types of stones (1.12.2-1.8.10b)

This means every chunk which gets newly generated in your world should have a significant higher chance to contain rock crystal ore.
I would recommend to make sure you're exploring in new chunks and maybe use a boat to get around quickly. Try looking at samples under water from time to time.
It took me a long time to find my first rock crystal sample and later on I found to by accident. Minecraft RNG is playing you with this one.

**Comment by pambo3** [comment]
Yes, i noticed the new underwater samples as well. 
I just created a new world (3.0.4) and completed all the necessary advancements until the rock crystal sample. I found one within 5 minutes... Now I know at least what they look like :D guess i just have to keep searching.. sucks that i have to travel so far though

**Comment by Shock2k** [comment]
I had done a bunch of exploring during 3.0.1 - 3.0.3 Age 1 (5k to 10k in every direction) so I was still on the old ore generation algorithm (rock crystals much rarer) for generating those regions.  I ended up having to look up my regions here (https://dinnerbone.com/minecraft/tools/coordinates/) (to avoid killing my base) and removing a bunch of them so they would re-generate with the new ore algorithm (in 3.0.4).  After that I was able to find rock samples (and other ore) with more frequency (after resetting where I had already been).

**Comment by pambo3** [comment]
Thats a really neat idea! thanks for mentioning that :)

**Comment by Jandakast** [comment]
This has been resolved in 3.0.4. Regenerating Regions or traveling to new chunks will be required for the new generation to take effect. If you decide to regenerate regions I highly suggest backing up your world before deleting any region files in case you accidentally remove the wrong files.
