### ISSUE TITLE
Farmland Recipe too early?

### ISSUE THREAD

**Issue by oOMitchOo** [Darkosto/SevTech-Ages#1397]
## Issue / Bug

There is a Farmland recipe, which unlocks in stage zero (after getting the Work Stump).

![](https://i.imgur.com/afEaU40.png)

So, you can build farmland without ever trading with a villager or building a plow. I don't think this is intended.

![](https://i.imgur.com/ghrEUAx.png)

## Possible Solution

I would suggest to disable the Farmland Recipe alltogether.

Alternatively push the recipe into stage 1.

## Steps to Reproduce (for bugs)

1. Unlock stage zero. (The Work Stump advancement)
2. Craft Farmland with Dirt and Bone Meal.

## Your Environment

* Modpack Version: 3.0.4
* Launcher Used: Twitch Launcher
* Server/LAN/Single Player: Singleplayer

**Comment by oOMitchOo** [comment]
> Are you able to actually craft it?

Yes!

**Comment by MissPotato** [comment]
This, however, does not complete the achievement, you still have to trade to get the achievement.

**Comment by PsyberMind** [comment]
Right, but that's not a progression point.. You can easily skip it

**Comment by Darkosto** [comment]
This is not a bug. The farmland advancement is simply there remind players to approach making farmland in a different way and it also teaches the player to talk to villagers instead of ignoring them like they do in most other situations.
