### ISSUE TITLE
Some things that are probably supposed to be disabled

### ISSUE THREAD

**Issue by davqvist** [Darkosto/SevTech-Ages#14]
1.) Trapdoors
2.) Doors
3.) Hoes as Farmland is craftable (even though Hoes make Aqua Munda Farmland, so I'm not confident)
4.) Wooden Shears as the Bone and Flint Shears otherwise are most likely useless
5.) Piggybackpack as Leads and/or carrying animals are kinda useless

**Comment by Darkosto** [comment]
1. Trapdoors are now in the correct stage
2. Doors should be good!
3. Hoes should be in their correct stages
4. Bone durability has been raised and am leaving the others in for players to choose which they would like to use
5. Moved the piggyback to stage 2 in the meantime
