### ISSUE TITLE
Ground tannin grindstone

### ISSUE THREAD

**Issue by Dawenzel** [Darkosto/SevTech-Ages#140]
## Issue
To progress with the children advancements of the "Leather, Rinse, Repeat" advancement **_ground tannin_** is needed. This item is gated behind the hand_grindstone and grindstone from Horse_Power, but these machines both have the requirement of the "You'll Make a Great Lead-er" advancement to be completed before they can be placed. This makes it so you can't progress further into the pack. 

## Possible Solution
Changing the requirement for the hand_grindstone to be "Leather, Rinse, Repeat" would allow access to the machine and still prevent the player to get bone_meal somewhat early. (The player also needs to still craft the mortal&pestle combo from pickletweaks.)
Also for the sake of consistency, the Horse_power press should also make use of the requirement "You'll Make a Great Lead-er".

## Versions
- Sevtech-Ages Alpha 5

**Comment by Darkosto** [comment]
Got this fixed up today, I'll put out another update to hotfix this so people can continue playing. Thanks for getting this reported!
