### ISSUE TITLE
Dedicated Linux Server, Has issues logs attached

### ISSUE THREAD

**Issue by marlburg** [Darkosto/SevTech-Ages#1407]
These logs will tell you way more then I can. It has problems
with a few mods for sure and world gen is not so hot in a few
spots. 

I had a 1.12.2 starter spawn, just a simple spawn building with
no explored area outside the spawn protection 300x300 there
are some gen issues. but the logs can help more then I can.

Hope they are not too big to attach.
[debug.log](https://github.com/Darkosto/SevTech-Ages/files/1876629/debug.log)
[latest.log](https://github.com/Darkosto/SevTech-Ages/files/1876630/latest.log)

thanks, i'm having fun with the pack and would like to get more
people on the server, but making sure gen and server issues
are gone before doing so. have a nice day.

marl :)

**Comment by marlburg** [comment]
There are some badly generated chunks though and you can see the gen lines around spawn protection. I thought the world gen was going to be smooth transition, The world i'm loading
is with a simple spawn building in 1.12.2  which looks bit off since no one understands the 
blocks when they first join, since they have not learned what a ladder etc is. But the spawn
is decent enough to give a safe haven starting out. This is hardmode sevtech too.

spawn protection is 300x300

I have found a few junks that just stick high out of the ground, stone walls in  a few spots.

This is a 3.0.4 fresh with all the current mods and I used my 1.12.2 starter spawn world, nothing
outside outside of the spawn building and a bit around it has been ganerated until opened with
the 3.0.4 and poking around is when I noticed the gen lines.

**Comment by artdude543** [comment]
Are you using the realistic generator on the server? This would be classified as a user error as we test updates before pushing and I play around on a few servers and we've not found any chunk generation issues. Same for SP no one has reported issues with the generation.

Wait? You're using a world that's already been generated? This would be the issue then. You can't generally expect a world to work with two types of generators MC will get confused and/or will just generate what ever.

**Comment by artdude543** [comment]
This is your issue and not a pack issue. The world was generated in Vanilla when you move that to a modded instance with mods which change the generator and/or how the game handles the generation. Yes, 1.12 does have better "smooth" transitions. But you're missing the point I already made; you can't expect it to be the same from Vanilla to Modded. It's literally impossible for it to work unless you use mods that don't change the generation.

I'm not sure when you asked Darkosto about this but I can confirm (from handling servers/worlds for years) your generation **won't** be smooth. If you did this on a world with the pack then obvs it would be fine and smooth. But as your using a world from Vanilla it won't be smooth as the data in the world file would not have known about the new generation added in the pack.

The last resort you would try is to mcedit the building to a schematic and import that into a new world generated with the pack. But this is 100%, not a pack bug or modding. This is just a limitation of how the world system works.

Sorry.
