### ISSUE TITLE
Caravans trader no trade goods

### ISSUE THREAD

**Issue by Dawenzel** [Darkosto/SevTech-Ages#141]
## Bug
The caravans trader by the name of "His Name Is Robert Paulsen" doesn't have any trades assigned. There are some commented out in the caravans script, but these look more like test trades.

## Versions
- Sevtech-Ages Alpha 5

**Comment by Darkosto** [comment]
Yep, like the villager trades, not all trades have been completed yet. It's a work in progress.

**Comment by Darkosto** [comment]
I'm still on the fence of whether or not I want to use caravans. It's been a lot more trouble than it's worth lately.

**Comment by Darkosto** [comment]
Removed caravans so this should be fine now :P
