### ISSUE TITLE
No gold spawning in 3.0.4, even in new chunks.

### ISSUE THREAD

**Issue by tritechnik** [Darkosto/SevTech-Ages#1410]
## Issue / Bug

No gold spawning in 3.0.4, even in new chunks.

## Current Behavior
Upgraded a 3.0.3 server to 3.0.4 when we were all still in the tutorial age. We've reached the second age and can not find gold. We've found a single surface sample in the Betweenlands but nothing in the chunk below. I then went into creative and travelled about 10000 blocks NSEW and ran "/oredistribution 200 0 100" every few hundred blocks and there is ZERO gold.

## Your Environment

* Modpack Version: 3.0.4 upgraded from 3.0.3
* Java Version:
* Launcher Used:  twitch launcher for clients
* Server/LAN/Single Player:  windows 10 server
* Resourcepack Enabled?: no
* Optifine Installed?:no

**Comment by Zarathaen** [comment]
Can confirm, I've seen one sample in the Betweenlands with no vein below (checked in creative), and no samples in the overworld (also flew around a lot).

**Comment by Jandakast** [comment]
I think this is a legit issue. Brand new World in a freshly downloaded instance. Generated 10000 chunks then ran `/oredistribution 500 0 200` 

![image](https://user-images.githubusercontent.com/19498789/38332905-142ca280-3825-11e8-8722-d29928d4c2f7.png)

**Comment by rtitan1** [comment]
\oredistribution does not work on gold, so you need other methods to search for it

**Comment by Darkosto** [comment]
To clarify things, OreDistribution is not the proper tool to use so please do not reference it when trying to report issues since it is incomplete. Prior to 3.0.4 I ran a more comprehensive ore generation tool and found gold to spawn correctly on many worlds.

**Comment by Jandakast** [comment]
Ok did a search using scannable scanner and found 4 gold samples/veins in 3 minutes.

**Comment by Darkosto** [comment]
I've also double checked and found gold in my world, it most definitely spawns.
