### ISSUE TITLE
Ilmenite Ore -> Titanium Ingot is only processible manually via Quartz Grindstone

### ISSUE THREAD

**Issue by Vyraal1** [Darkosto/SevTech-Ages#1411]
## Current Behavior
- Ilmenite Ore (as far as I know the only way to obtain Titanium) cannot get crushed by the IE Crusher or AA Crusher, or any other modded form of ore processing

Only Titanium Ingot can be processed
![image](https://user-images.githubusercontent.com/26587049/38322453-76d4a3be-3808-11e8-9b78-92f7da3bcc2a.png)

Same in the AA Crusher
![image](https://user-images.githubusercontent.com/26587049/38322487-8eff3a12-3808-11e8-8d1b-3f704f1426dc.png)

Quartz Grindstone works from AE2.... I'm not sure if this is the only intended way.
![image](https://user-images.githubusercontent.com/26587049/38322525-a5a52420-3808-11e8-9930-9e9a48f34204.png)

- Ignore if there is another way to process / obtain titanium, I'm only going by what I'm seeing in JEI at the moment

## Possible Solution
- add in processing system for Titanium
- GalaticCraft has it the ore dictionary set as oreIlmenite instead of oreTitanium, same with dustIlmenite(which might break the crafttweaker scripts if they were looking for oreTitanium/dustTitanium)

## Context
- There's no way to automate titanium fully with this, if the plan was for titanium to never be fully automatable (actually this might still be automatable by automatic users clicking on the grindstone)
- However it's also a bit weird to play the pack and get past the midgame only to find out that to process a high level ore, you need to do it manually a la elbow grease, it kind of breaks continuity / semblance of progression in the pack

## Your Environment
* Modpack Version: 3.0.4

**Comment by justinrusso** [comment]
Weird.. Thought I had added this.
