### ISSUE TITLE
Suggestion: Shark Tooth:Grind:Bonemeal

### ISSUE THREAD

**Issue by Arisonius** [Darkosto/SevTech-Ages#1414]
Hey Darkosto, this is not a bug but this is a suggestion: Can we possibly be able to grind shark teeth into bonemeal?

## Your Environment

* Modpack Version: 3.0.4
* Java Version: 8
* Launcher Used: Twitch / Old Launcher setting
* Server/LAN/Single Player: Serer
* Resourcepack Enabled?: F32
* Optifine Installed?: No

**Comment by Darkosto** [comment]
Yep! @justinrusso can do that tonight! Thanks for the suggestion!
