### ISSUE TITLE
[Suggestion] Black Iron Ingot Recipe in Arc Furnace

### ISSUE THREAD

**Issue by Vyraal1** [Darkosto/SevTech-Ages#1416]
## Issue / Bug
No way to automate black iron except at stack at a time since it's only made in the IE Alloy Kiln, which does not interface with any form of piping or automation as far as I'm aware. There is no other way to make it, would it be possible to add in an Arc Furnace recipe so at least it can be made easier? Or Mekanism metallurgic Infuser (Coal + Steel or some other ingot)? 

## Possible Solution
Add in an alloying recipe with iron ingot as a primary and crushed quartz dust as the secondary ingredient in the Arc furnace.

## Context
- Black iron is used somewhat extensively in a lot of Stage Five recipes and even earlier, making it at a stack at a time just seems kind of tedious and not in line with what the pack wants the player to do

## Your Environment
* Modpack Version: 3.0.4

**Comment by Waisse** [comment]
Didn't made the cut for 3.0.5. Bronze alloying is also missing from the arc furnace, making the kiln the only way to make it.
