### ISSUE TITLE
Pouring Molten Clay onto a ClayBucket to make a casting creates a broken item

### ISSUE THREAD

**Issue by Isuress** [Darkosto/SevTech-Ages#1418]
## Issue / Bug
I ran across a bug last night on stream; I put a clay bucket into a casting table, then melted clay in the melter, and then tried to pour a clay casting of the clay bucket. Instead it created a Clay Clay Bucket. When I tried to pickup lava with it, it corrupted the lava and make it molten clay and replaced/destroyed a ton of lava blocks around it.

## Current Behavior
Pouring molten clay on top of a clay bucket to make a bucket casting makes a Clay Clay Bucket.
It then converts lava blocks when interacting with them.

## Possible Solution
Pouring molten clay on top of a stone bucket doesn't work.
Potentially allow stone bucket to make a clay casting?
(might be locked behind Tinker's compliment?)

## Steps to Reproduce (for bugs)
(Prefer not to watch on stream - watch on other monitor?)
Video sources:
*Making casting
https://clips.twitch.tv/CuteQuaintCasetteRedCoat
*Attempting to pickup lava
https://clips.twitch.tv/FlirtyBovineReubenPoooound

## Your Environment
* Modpack Version: v3.0.4
* Java Version: Java 8 build 164
* Launcher Used: Twitch
* Server/LAN/Single Player: Server
* Resourcepack Enabled?: Yes
* Optifine Installed?: Yes

**Comment by daddy77gaming** [comment]
you cant make a bucket cast with a clay bucket.. you need the stone bucket which is designed for making the cast (JEI will also tell you that if you look at how to make the bucket cast)

one tip in this pack dont assume things to work as your used to, USE jei to look at almost everything you want to make!

**Comment by artdude543** [comment]
Use JEI to make sure you're using the correct item. We changed a lot :P
