### ISSUE TITLE
Wood planks available via vanilla recipe

### ISSUE THREAD

**Issue by MongoTheElder** [Darkosto/SevTech-Ages#142]
![2017-10-14_09 43 24](https://user-images.githubusercontent.com/29290246/31576209-3b9e5464-b0c4-11e7-8e38-5be2fa6980f1.png)

This conflicts with the one log->chopping block recipe as well.

![2017-10-14_09 46 37](https://user-images.githubusercontent.com/29290246/31576236-9adfe78a-b0c4-11e7-9626-221a9a96280d.png)

Alpha 5
Twitch App Version 7.6.6494.39113 Beta

**Comment by Darkosto** [comment]
What log is that?

**Comment by MongoTheElder** [comment]
Oak

**Comment by Darkosto** [comment]
Okay, then that's a bad import. I've checked today and it looks like your scripts are, for some reason, way out of date. The new update should hopefully fix that. I assume you used the Twitch Export?

**Comment by MongoTheElder** [comment]
Yes, Twitch App Version 7.6.6494.39113 Beta
