### ISSUE TITLE
AGE 1 not working

### ISSUE THREAD

**Issue by rdc122999** [Darkosto/SevTech-Ages#1422]
## Your Environment

* Modpack Version: 3.0.4
* Java Version: don't know 
* Launcher Used: ATLauncher
* Server/LAN/Single Player: singleplayer
* Resourcepack Enabled?: no 
* Optifine Installed?: no

I just got to age 1 and started looking at recipes to go through advancement and one of the age 1 recipes work

**Comment by justinrusso** [comment]
What is the output when you type `/gamestage info @p`

**Comment by rdc122999** [comment]
Hey sorry forgot to post it here I did a fresh install and it fixed itself
