### ISSUE TITLE
Tin canister does not have a recipe in JEI

### ISSUE THREAD

**Issue by BananaLord12** [Darkosto/SevTech-Ages#1423]
## Issue / Bug
I am in age 4 and i cannot craft the recipe for the tin canister, i was able to see it in JEI but it wont let me see the recipe, i have also tried to use the default recipe and the same thing happened, i cannot craft it.

https://prnt.sc/j0xphe - Link for the item shown in JEI but wont be able to see the actual recipe

https://prnt.sc/j0xpvf - Link that shows me crafting the default recipe for tin canister

## Current Behavior
well this recipe is currently disabling me from crafting the engine to continue my progress in age 4.

## Steps to Reproduce (for bugs)
1. Check recipe in JEI
2. Create the default recipe which is 7 tin in a cauldron shape

## Your Environment
* Modpack Version: 3.0.4
* Java Version: 1.8.0_24
* Launcher Used: Twitch Launcher
* Server/LAN/Single Player: Server
* Resourcepack Enabled?: not used
* Optifine Installed?: 1.12.2_HD_U_C9

**Comment by justinrusso** [comment]
Fixed for 3.0.5 https://github.com/Darkosto/SevTech-Ages/issues/1201
