### ISSUE TITLE
Missing texture, not correct recipe.

### ISSUE THREAD

**Issue by CxDrwalxC** [Darkosto/SevTech-Ages#1424]
## Issue / Bug
1)"Hearthgrove log" doesn't has texture in "Low grade charcoal" recipe using "Clay Kiln" (Age 0)
2)Recipe for bone/flint arrows after killing Totemic Boss shows that need 2x 8x strings, but need only 2x 1x string to craft it.

## Your Environment
* Modpack Version: 3.04
* Java Version: recommended by You
* Launcher Used: 1.12.2
* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: No
* Optifine Installed?: Yes

**Comment by artdude543** [comment]
Recipe issue is fixing on the next version; the texture issue I'll look into but it's not really a bug per say. Just a small "glitch" :) But the main issue here is resolved on the next update.
