### ISSUE TITLE
Torch thrower places regular torches in between lands

### ISSUE THREAD

**Issue by lawl281** [Darkosto/SevTech-Ages#1426]
## Issue / Bug
Using the torch thrower in the betweenlands lets you place normal torches and they dont turn damp.

## Current Behavior
Torches should pop off and turn damp.

## Steps to Reproduce (for bugs)
1. Craft torchthrower
2. Use in betweenlands for easy time.

## Context
this bug allows people to not craft sulfer torches

## Your Environment

* Modpack Version:3.0.4
* Java Version:
* Launcher Used:twitch
* Server/LAN/Single Player: server
* Resourcepack Enabled?:no
* Optifine Installed?:yes

**Comment by Darkosto** [comment]
This is a duplicate issue. Torch launcher in the betweenlands has been deemed fine.

**Comment by justinrusso** [comment]
https://github.com/Darkosto/SevTech-Ages/issues/759
