### ISSUE TITLE
Mekanism ore processing issue

### ISSUE THREAD

**Issue by amezh** [Darkosto/SevTech-Ages#1427]
## Issue / Bug
Mekanism dirty dusts can be processed into Mekanism ore dusts and there are no way to make ingots from it. 

## Possible Solution
Would be nice for Mekanism to produce IE dusts same as everything else, so we can benefit from factories and Age 5 tech

## Your Environment

* Modpack Version:3.0.4

**Comment by WildFTW** [comment]
Should be fixable.

**Comment by justinrusso** [comment]
Haven't gotten a fix for it yet, but I knew of this for the past day or two. Somehow it never turned into an issue report. thanks!
