### ISSUE TITLE
Squid/Sharks don't spawn in already generated chunks.

### ISSUE THREAD

**Issue by dazema** [Darkosto/SevTech-Ages#1428]
## Issue / Bug
Squid/Sharks don't spawn in already generated chunks after updating from 3.0.3 to 3.0.4.

## Possible Solution
If normal generation of squids/sharks can't be solved, add a totemic ritual to transform JAFF fish into squid/sharks.

## Steps to Reproduce
1. Pre-Generate a large amount of chunks with forge.
2. Despawn/Kill already generated squid.

## Context
• Can't Progress due to not having ink sacs / shark teeth

## Your Environment
* Modpack Version: 3.0.4
* Java Version: 1.8.0.161 (64 Bit)
* Launcher Used: Curse; Jar Launcher
* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: Faithful 32x
* Optifine Installed?: Yes

**Comment by justinrusso** [comment]
Convinced this isnt an issue, but we're adding changes anyways.

https://github.com/Darkosto/SevTech-Ages/issues/1045

**Comment by dazema** [comment]
Probably because it hasn't been tested correctly.

**Comment by dazema** [comment]
If I load a brand new fresh world I can find squid/sharks at the intended spawn rate, If I generate a large amount of chunks and then despawn said squid/sharks they will not respawn in the already generated chunks. 

This would explain why there's such a large split in the people who find and don't find squid.

**Comment by Jandakast** [comment]
This isn't an issue and it's been tested relentlessly by multiple people. But because people keep crying about it I've updated some configs to double their spawn checking anyway. No need to insult people and make claims that are unfounded. It's RNG...
