### ISSUE TITLE
Ore Clusters visible at Stage 0

### ISSUE THREAD

**Issue by MongoTheElder** [Darkosto/SevTech-Ages#143]
Geolosys ore clusters are rendering in Stage 0. So far I have found:
Aluminum
Redstone
Platnum
Silver

**Comment by TieMonkey** [comment]
I also had some Ore blocks showing in stage 0, not sure which it was tho

**Comment by Darkosto** [comment]
This is another instance of ores that are hidden showing up when the player opens the pack up the first time @darkhax

**Comment by darkhax** [comment]
Please include the craftweaker log file.

**Comment by MongoTheElder** [comment]
Looks like Alpha 6 has remediated this issue. No longer seeing ores in Stage 0.
