### ISSUE TITLE
Waterbarrels and Rain

### ISSUE THREAD

**Issue by LucieTwi** [Darkosto/SevTech-Ages#1431]
More a question than a real issue... Is it on purpose that two ingame-days worth of rain hardly make the bottom of those first water barrels wet? I have three of them next to each other on a patch of grass - nothing overhead. And it just rained for two ingame days and they arent even filled to a quarter. Just seems really little if you have to settle somewhere with no ocean or river nearby.

**Comment by WildFTW** [comment]
I'm guessing yes because finding water shouldn't be very hard to do

**Comment by Jandakast** [comment]
Seems correct. Just make more barrels and use a Fluid Bladder to collect partial buckets of water from all of them.

**Comment by LucieTwi** [comment]
Okay. If it's intenden, then I can live with it. Just wanted to make sure, that it's not a bug. Thanks :-)

**Comment by artdude543** [comment]
It's intended to be slow; it also gives time for you to perform other tasks while you wait as it's all part of the RNG theme. But placing a load of barrels helps to make it "faster" and still give you pondering time to craft other items and/or explore advancements. 😄
