### ISSUE TITLE
Mining Marble Crash

### ISSUE THREAD

**Issue by angelid1** [Darkosto/SevTech-Ages#1432]
-- Issue 
I am playing on a friend's privately run server.
Client crashes when I try to mine a block of Marble (from chizel's mod) in a specific area/chunk/vein. 

--Crashlog: 
https://pastebin.com/dFrDHdZQ

I am currently able to circumvent the marble vein, and be on my way, but a fix for the next person would be great.

-- Possible Solution
Temp solution: Avoid all the pretty marble. :C

-- Steps to Reproduce
1. Go to this specific vein of marble. (Going to test if it's just this vein or not, I'll get back to this.)
2. Mine it.
3. Upon it breaking and dropping into the world, the game crashes. 

-- Context
I was mining down to a specific depth to start looking for quartz. Not that it's terribly relevant to this, but I have been able to mine Marble before... We'll see if it's just this one vein or not.

-- Your Environment
I will add to this if it's needed, as far as I can tell it's not terribly important (Unless it's a lighting issue somehow; I am using fibre torches to light my way at the moment).

* Modpack Version: 3.0.3
* Java Version: Version 8 Update 161 (build 1.8.0_161-b12)
* Launcher Used: Twitch Launcher
* Server/LAN/Single Player: Private-Run Server, server files downloaded from github.
* Resourcepack Enabled?: No
* Optifine Installed?: Unless it was in the modpack, no.

**Comment by justinrusso** [comment]
https://github.com/Darkosto/SevTech-Ages/issues/1108
