### ISSUE TITLE
Siding bug

### ISSUE THREAD

**Issue by extrenix** [Darkosto/SevTech-Ages#1433]
Wood sidings (and probably any kind of sidings) cannot be put on wall facing sunset
Scrolling through the positions, it would appear "ground" position is there twice.
every other positions are available.

* Modpack Version:3.0.4
* Java Version:1.8_161
* Launcher Used:twitch app
* Server/LAN/Single Player:SP
* Resourcepack Enabled?:yes
* Optifine Installed?:yes

**Comment by Jandakast** [comment]
This is an issue with Better with Mods version 0.32 not with the pack. Once Darkosto updates Better with Mods to 0.33 or newer this will be resolved.
