### ISSUE TITLE
Question: Removal of unecessary cosmetic stuff

### ISSUE THREAD

**Issue by NKWiewior** [Darkosto/SevTech-Ages#1435]
How I can remove all the cosmetic stuff like items "realistically" dropping on the groud, tiny grass on grass blocks etc. ?

**Comment by Ellindofu** [comment]
Press F8 and turn off better foliage.

**Comment by Jandakast** [comment]
Realistic item drops is the mod. 

Better Foliage can be disabled to get rid of the small grass and "fuzzy" leaf blocks.
