### ISSUE TITLE
Oven Ready Melon Pie (and maybe others) can't be cooked.

### ISSUE THREAD

**Issue by rikai** [Darkosto/SevTech-Ages#1438]
## Issue / Bug
Oven Ready Melon Pie doesn't seem to be able to be cooked at all, and therefore is an unusable item.

Craft an Oven Ready Melon Pie, toss it in the kiln, nothing happens.

![image](https://user-images.githubusercontent.com/515221/38339860-509a32aa-3825-11e8-8502-d60608cf4081.png)

![image](https://user-images.githubusercontent.com/515221/38339832-2e9cb06a-3825-11e8-9dc0-73034792f345.png)

## Current Behavior

The pies aren't cooked. Not sure if this applies to the other ready-made pies as well.

## Steps to Reproduce (for bugs)
1. Made a ready-made melon pie in age 2
2. Stick it in a kiln.
3. Nothing happens.

## Context
Creating melon pies in a more efficient way to raise my fruit nutrition.

## Your Environment
* Modpack Version: 3.0.4
* Mod Version: Better With Addons 0.34
* Java Version: 1.8.0_73
* Launcher Used: Atlauncher.
* Server/LAN/Single Player: Server
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by Lewdicolo** [comment]
You are using the wrong kiln. The one you need is from Better With Mods. There are also easier ways to make Melon Pie in the pack

**Comment by rikai** [comment]
I know there are other ways to make it. I didn't realize there was another kiln though, thanks.
