### ISSUE TITLE
Olive wood won't burn...

### ISSUE THREAD

**Issue by TieMonkey** [Darkosto/SevTech-Ages#144]
It would seem when trying to get low grade charcoal, the Rustic Olive tree (and maybe others) do not burn down to charcoal.

Also I've found that Ironwood isn't seen as a fuel source for the fire pit

**Comment by Darkosto** [comment]
I'll need to have a list of everything that you've found so they can be added, thanks :)

**Comment by Darkosto** [comment]
Should be all good now, thanks!
