### ISSUE TITLE
[3.0.4] 'Net' crafting recipe shows up wrongly

### ISSUE THREAD

**Issue by 0xb00b** [Darkosto/SevTech-Ages#1440]
## Issue / Bug
https://i.imgur.com/eOu1cCX.png

As you can see here, the recipe for 'net' (needed for a strainer) shows as needing 8+8+8 string, but it only actually needs 1+1+1.

## Possible Solution
¯\_(ツ)_/¯

## Your Environment
* Modpack Version: 3.0.4
* Java Version: OpenJDK Runtime Environment (build 1.8.0_162-8u162-b12-0ubuntu0.16.04.2-b12)
* Launcher Used: MultiMC
* Server/LAN/Single Player: SP
* Resourcepack Enabled?: SoarTex
* Optifine Installed?: Yes, no shaders.

**Comment by justinrusso** [comment]
Fixed in https://minecraft.curseforge.com/projects/better-with-addons/files/2547997

Updated in Dev. Should be out for 3.0.5
