### ISSUE TITLE
"Better With Mods Manual" Home page missing tekst.

### ISSUE THREAD

**Issue by Steve-Asgardian** [Darkosto/SevTech-Ages#1442]
If i open the book and look at the home page its saying: "Document not found: en_us/index.md please report this to here" i don't know if the issue can be fixed by you ( Darkosto) or by the mod owner.

**Comment by DaedalusGame** [comment]
issue count on BWM bug tracker: 2
issue count on Sevtech bug tracker: probably 4 or 5

**Comment by Steve-Asgardian** [comment]
Oke i do not understant enny thing of this. sorry im a noob at this.

**Comment by ljbingley** [comment]
can someone just link the file and tell me how to add it to my pack and server?
