### ISSUE TITLE
UI Overlap with Info Accessories and Blood Magic

### ISSUE THREAD

**Issue by iffonox** [Darkosto/SevTech-Ages#1443]
## Issue / Bug
The UIs of the  Info Accessories items and the Divination Sigil from Blood Magic overlap in the upper left corner of the screen.

![2018-04-05_01 50 26](https://user-images.githubusercontent.com/4130675/38340467-ea5e8014-3873-11e8-96bb-16658e6f8b01.png)

## Possible Solution
Move one of the UI overlays to a different position

## Steps to Reproduce (for bugs)
Look at the Blood altar with a Divination Sigil in hand while having any Info Accessories items in your inventory

## Your Environment
* Modpack Version: 3.0.4
* Java Version: 1.8.0_101
* Launcher Used: Twitch
* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by WildFTW** [comment]
Easy fix dont use them at the same time.

**Comment by artdude543** [comment]
These can't be changed. That and just don't use them at the same time 🙂
