### ISSUE TITLE
Tooltip on inventory items not working when backpack (improved backpacks) is open

### ISSUE THREAD

**Issue by scottcher** [Darkosto/SevTech-Ages#1444]
## Issue / Bug
With a backpack (first tier from Improved Backpacks) open from my toolbelt, mouse-over of items doesn't show mouse-over information (tooltip info) for the items in the backpack or my inventory.  when I close the backpack, tooltips are normal on my inventory.

MINOR ISSUE - annoying though.

## Your Environment
* Modpack Version:  3.0.4, Minecraft 1.12,2, Forge 14.23.2.2635
* Java Version: 1.8.0.161
* Launcher Used: Twitch
* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: Soartex Fanver
* Optifine Installed?: No
>6gb allocated
Windows 10

**Comment by justinrusso** [comment]
https://github.com/Darkosto/SevTech-Ages/issues/604
