### ISSUE TITLE
Astral Sorcery Starmetal Ore transfusion not working

### ISSUE THREAD

**Issue by unclekakarot** [Darkosto/SevTech-Ages#1445]
## Issue / Bug
Trying to turn the iron ore into starmetal ore using a collector crystal but nothing I have tried seems to work. Have tried linking the crystal straight too the ore, tried linking the crystal to a lens and linking the lens to the ore. Nothing has worked. Anyone have any clue why it isn't working or is it just bugged?

https://imgur.com/a/5b4pb
https://imgur.com/a/X6kLI

## Possible Solution
No idea if there is a solution or not

## Steps to Reproduce (for bugs)
Link collector crystal to ore directly or link crystal to lens then to ore

## Your Environment
Modpack Version: 3.0.4
Java Version: 1.8.0_101
Launcher Used: ATLauncher
Server/LAN/Single Player: Server
Resourcepack Enabled?: No
Optifine Installed?: No

**Comment by Jandakast** [comment]
The way to get starmetal ore has been changed in this pack. Look up the ore in JEI and check it's recipe

**Comment by SephirothWS** [comment]
Takes 2 starmetal dust to make a single starmetal ore. Very lossy and makes getting more starmetal next to impossible without transmutation.
