### ISSUE TITLE
Workstump Mk2 voiding Logs

### ISSUE THREAD

**Issue by Dragon87tamer** [Darkosto/SevTech-Ages#1447]
The issue is if you use the work stump mk2 and craft multiple bark at the same time, it voids the rest of the logs (ie put in 4,it uses 1, u lose the rest)
if u watch the gif...u will see (already had 1 bark in inventory as already done this once before) this was to show the issue, items in use are the Work stump MK2 (crafting table) the flint work blade (top left) and oak logs ...
![2018-04-05_00-28-54](https://user-images.githubusercontent.com/38088863/38341178-1723d4dc-386f-11e8-8b7b-99499e92959e.gif)

**Comment by vadis365** [comment]
I'll fix it.

**Comment by vadis365** [comment]
Fixed in dev now. Maybe. Hopefully. Perhaps.

**Comment by WildFTW** [comment]
i love that maybe hopefully perhaps if it works we dont know

**Comment by vadis365** [comment]
works \o/
