### ISSUE TITLE
Seeds can not be placed in a chest if you have not completed the prereq advancement

### ISSUE THREAD

**Issue by MongoTheElder** [Darkosto/SevTech-Ages#145]
To use vanilla seeds requires "Teach a Man to Farm". It seems that attempting to place seeds in a chest constitutes "use" and is blocked if you have not completed the advancement.

Same for items you acquire (unintentionally) before they are unlocked. I looted an Iron Sword from a mob in Stage 0 but I can't put it into storage.

Other items that have an unfulfilled Skill requirement show an error when placing the items but still can be put into a chest.

**Comment by Darkosto** [comment]
Are you clicking or shift-clicking into the storage?

**Comment by Darkosto** [comment]
I changed the requirements for seeds/farmland so it should be fixed up for you.
