### ISSUE TITLE
Singleplayer goes to multi

### ISSUE THREAD

**Issue by Girfan3198** [Darkosto/SevTech-Ages#1450]
# **Issue (possibly client side)**
I click the singleplayer game mode button, and it takes a while to load up then crashes and gives me some java code then it tells me that it can't find a server in my area.

**Update** I'll try again tomorrow and if that error pops up again I'll screenshot it and post it up here. Sorry I don't have any other information, its just after trying to get the game to work after 2 days and it not working, just for a hour when you first downloaded it, makes you regret living. but its a good mod pack and an amazing game with just what I've seen, its like terrafirmacraft but only with a sort of a guideline kinda thing which I actually like. survival games sorta need to have some way to "Nudge" the player into the next "phase" and you've done it here.

**Comment by artdude543** [comment]
You've completely ignored the issue template. Please re-file an issue using the template provided. We need all the information/logs to help you with the problem. It's the reason we have the template in the first place.

**Comment by Girfan3198** [comment]
I would use the template if i knew how to get twitch crash logs.
