### ISSUE TITLE
[3.0.4] Cyclic allows you to place carry-on 'items' in your inventory. 

### ISSUE THREAD

**Issue by 0xb00b** [Darkosto/SevTech-Ages#1451]
## Issue / Bug
Cyclic + carry-on allows you to place any carried items into your inventory, this includes animals and chests.. so you could create infinite inventory space by placing filled chests in your inventory etc. (or us it to carry more than one item at a time) 

## Current Behavior
Cyclic adds a feature to shift hotbar items to your inventory and vice-versa (through the 'z' hotkey or through 'y' for shift-up/ H for shift-down. Carry-on seems to block/disable normal interaction with your inventory while you are carrying something, and doesnt allow you to open your inventory while carrying. 

## Possible Solution
Not sure exactly what is going on but im assuming this bug is due to cyclic being able to manipulate your inventory and carry-on not accounting for that. So either carry-on needs additional checks/disable certain functionality (cyclic, but possibly also other mods) 

## Steps to Reproduce (for bugs)
1. Carry an item with the default shift-right click.
2. Press Z to open up the hotbar swapping menu and select a row from your inventory (so the carried item thats on the hotbar gets placed in your inventory) 
3. you can now see a blank / hidden item in your inventory that represents the carried item.

https://imgur.com/a/sOgxv https://imgur.com/a/WvDT7  (pick up item + shift inventory)
https://imgur.com/a/DaGc8 https://imgur.com/a/KiDZv (place item anywhere you like)

https://clips.twitch.tv/ShinyManlyRavenGingerPower clip of soaryn trying it out :p 

## Context
It's a pretty big cheese to be able to have full chests in your inventory or carry multiple animals/items at all imho

## Your Environment
* Modpack Version: 3.0.4
* Java Version: OpenJDK Runtime Environment (build 1.8.0_162-8u162-b12-0ubuntu0.16.04.2-b12)
* Launcher Used: MultiMC
* Server/LAN/Single Player: SP
* Resourcepack Enabled?: SoarTex
* Optifine Installed?: Yes, no shaders.

**Comment by 0xb00b** [comment]
Looked into the code from CarryOn, seems like it could be an easy fix by updating this code https://github.com/Tschipp/CarryOn/blob/master/src/main/java/tschipp/carryon/client/event/RenderEvents.java#L123-L133

not just check if the Carry-On item is in the current hand / main hand but if its in the inventory at all

**Comment by Tschipp** [comment]
@0xb00b yeah this is a check that I can implement

**Comment by Darkosto** [comment]
I've, for more than 1 reason, disabled the ability to shift inventory rows/slots. That should take care of not only this but another issue that has been reported. I'll make sure to update Carry-on when you're able to push it live :) Thanks!
