### ISSUE TITLE
pneumaticraft plastic mixer can't put dye's in

### ISSUE THREAD

**Issue by daddy77gaming** [Darkosto/SevTech-Ages#1454]
3.0.4 Whatever i try i cant get the dye's into the mixer..

tried most all ways i could imagine: click them in, drag drop them in, hopper them in, pipe them in.. what am i missing here? restarted and reloaded the pack.. i'm lost what i can do more

**Comment by daddy77gaming** [comment]
![2018-04-05_07 18 00](https://user-images.githubusercontent.com/31905330/38350055-f824c2b8-38a9-11e8-861a-31f8a0ad4c1f.png)
![2018-04-05_07 19 01](https://user-images.githubusercontent.com/31905330/38350064-032abece-38aa-11e8-90e2-b6b0c64b3a1d.png)

**Comment by justinrusso** [comment]
Thats because you need to use a dye, not minecraft's items which are not a dye in this pack

**Comment by MrBirk** [comment]
That is not intuitive at all. The JEI recipe shows you using normal minecraft dyes and the advancement makes no mention of using ground dyes under the plastic mixer. Why aren't the recipes changed or a mention made about it.
