### ISSUE TITLE
Shards from Galacticraft

### ISSUE THREAD

**Issue by uglyduck2k4** [Darkosto/SevTech-Ages#1455]
## Issue / Bug

Mined the Ilmenite Ore from Asteroid Belt. Got some Titanium and Iron Shards from this. Iron Shards i can use with Mekanism. Should these shards exist?
## Your Environment

* Modpack Version: 3.0.4
* Java Version: 1.8.0.161 (64bit)
* Launcher Used: Twitch
* Server/LAN/Single Player: Server
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by justinrusso** [comment]
Removed part related to https://github.com/Darkosto/SevTech-Ages/issues/1411

**Comment by justinrusso** [comment]
We're going to have to go check over GC/EP ores and confirm which ones break into shards and figure out how to handle these.

**Comment by justinrusso** [comment]
I think for modifying the drops we are going to have to add another mod https://minecraft.curseforge.com/projects/dropt

**Comment by artdude543** [comment]
This is sorted in the next update by changing the drops of the block along with other tweaks.  🙂
