### ISSUE TITLE
PneumaticCraft recipes missing

### ISSUE THREAD

**Issue by daddy77gaming** [Darkosto/SevTech-Ages#1457]
3.0.4

some items from Pneumaticraft are not showing up in JEI (amadron tablet, pneumatic wrench, air canister)
some of which are impossible to progress in the pack without.
here are the recipe's (find them searching base components from pneumaticraft to craft with)

--Removed--

Some recipes in JEI are blank 

![2018-04-05_07 35 20](https://user-images.githubusercontent.com/31905330/38350644-7751ede8-38ac-11e8-82a9-acd22f8197c5.png)

**Comment by justinrusso** [comment]
Removed part of issue related to https://github.com/Darkosto/SevTech-Ages/issues/1123

**Comment by Darkosto** [comment]
@justinrusso Can you add these removals via recipe name:

"color_drone"
"logistic_to_drone"
