### ISSUE TITLE
Can't craft grass mesh

### ISSUE THREAD

**Issue by NKWiewior** [Darkosto/SevTech-Ages#1458]
When i tried to craft grass mesh it just didn't let me to do it despite that the recipe was there showed by NEI and it was unlocked.

**Comment by Mrbysco** [comment]
I'd like to ask why you got rid of the issue format? Without the proper info how is anyone able to reproduce the issue?

**Comment by NKWiewior** [comment]
Well since it's a issue with a recipe you just try to craft it in the player's inventory / crafting table sorry for trouble i didn't paid attention.

**Comment by justinrusso** [comment]
This is confirmed working for other users and I cannot reproduce.

Try reinstalling your pack. You cant expect much help without providing us with the information we need.
