### ISSUE TITLE
Breaking block under vanilla torch

### ISSUE THREAD

**Issue by Dawenzel** [Darkosto/SevTech-Ages#146]
## Bug
When breaking the block upon which a vanilla torch is placed the block drops but instead of the vanilla torch dropping a un-lit fiber torch is dropped instead.

## Versions
- Minecraft 1.12.1
- Forge 14.23.0.2512
- Java x64 8u144
- Sevtech-Ages Alpha 6

**Comment by Crackerhead22** [comment]
Known bug if I recall. I can't remember the reason behind it exactly, something about the ore hiding thing and the torch not being broken by the player.

**Comment by Dawenzel** [comment]
It might be the same thing as what happened to the workstump issue. As the workstump doesn't get assigned to stage 1 it can't craft those recipes(The player technically doesn't craft the item). This would probably also count for the world breaking the torch in this case and because it isn't stage 1 it drops the un-lit fiber torch instead of the torch...

**Comment by Darkosto** [comment]
Yep, already a known bug and nothing can be done about it since only players can unlock stages. 

I'm not sure anything can be done to rectify that or the fact that the work stump cannot craft recipes in later stages. @darkhax

**Comment by justinrusso** [comment]
Fixed in Darkosto/SevTechAgesConfigs@df17c11cb48ff0abcd98e4e8c746379fc4f2f289
