### ISSUE TITLE
Crusher Grit Issue Age 3

### ISSUE THREAD

**Issue by YalinHawk** [Darkosto/SevTech-Ages#1464]
I tried searching for this and found nothing, it may even be a desired feature.
 
## Issue / Bug
Age 3 Immersive Engineering unlocked. Grit from the IE crusher can't be turned into ingots without access to an Arc furnace at minimal.

## Current Behavior
Current Age 3 progression unlocks:

![sevtechage3](https://user-images.githubusercontent.com/10606516/38373494-6ca7a4ba-38bf-11e8-9af7-c58da6b19c10.PNG)

No smelting/TiC/etc recipe to make grits usable. Only way to turn Grits into Ingots at Age 3 is with IE Arc Furnace, which could be a huge roadblock for people who don't notice this behavior and end up with chests of processed grits they can't use.

## Possible Solution
Either restore Grit -> Ingot recipe on certain smelting apparatus (Kiln maybe? Or some other sufficiently higher level furnace) or gate the Crusher to prevent accidentally using your entire ore stockpile to make useless grits. 

## Steps to Reproduce (for bugs)

Proceed to Age 3

Unlock tiers shown in picture above

Build crusher multiblock, activate it with Engineer hammer

Put ores through crusher, obtain grit, cry.

Cry a lot.

## Context

I can understand if this is desired behavior to prevent ore doubling quite this early, but if so, it needs to be gated. Frustrating to toss all of my ores through my fancy new crusher only to end up wasting all of them and unable to progress due to an apparent lack of resources. 

## Your Environment
Pack version 3.0.4

**Comment by Darkosto** [comment]
That's correct behavior. It's meant that you need the Arc Furnace to grind and double ore output.
