### ISSUE TITLE
Constellation paper

### ISSUE THREAD

**Issue by steinjorn** [Darkosto/SevTech-Ages#1465]
When crafting the recipe for constellation paper using the iridescent altar, I am only recieving 
discidia papers, 4 out of 4 times.
* Modpack Version:3.0.4
* Launcher Used:twitch
* Server/LAN/Single Player:SP
* Resourcepack Enabled?:no
* Optifine Installed?:no

**Comment by Stormfirebird** [comment]
Just to be sure, you didn't just craft the same recipe 4 times because JEI brings you to the first (wrong) one regardless of which one you click.
There's a specific recipe for each constellation,
