### ISSUE TITLE
ReAuth

### ISSUE THREAD

**Issue by mcwnuq** [Darkosto/SevTech-Ages#1468]
Can you add ReAuth mod at the next update?
https://minecraft.curseforge.com/projects/reauth

**Comment by ArbitraryHubris** [comment]
I add it myself, would be useful for everyone because of the load time of this pack.

**Comment by mcwnuq** [comment]
I don't this that this mod could have impact on pack load time.

**Comment by ArbitraryHubris** [comment]
it keeps your login from timing out, @mcwnuq , obviating the need to close the pack, login, and relaunch.  Esp important when there are regular server restarts.

**Comment by mcwnuq** [comment]
I'm have 2-3 Minecraft opened at the same time, if I launch new one i must restart the SevTech couse almost every pack contain ReAuth except SevTech.

**Comment by artdude543** [comment]
This has been added in the next update.
