### ISSUE TITLE
Not Bug, looking for texture help for Content Tweaker

### ISSUE THREAD

**Issue by BonaireDreams** [Darkosto/SevTech-Ages#1469]
Issue / Bug
Not a bug, looking for community help. Tried searching all wikis and was unable to find answer.

Current Behavior
Content Tweaker textures (gears, plates) ugly low res, makes me sad.

Possible Solution
1)update textures via, resourcepack
2) Profit

Steps to Reproduce (for bugs)
1. Look at ugly textures
2. *shudder*

Context
Hi Folks, Looking for some help to update textures for ContentTweaker recipes. I have a good 75% of Sevtech looking pretty with Sphax but can not for the life of me find the location for contenttweakers gears and plates (etc). All the wiki's for minetweaker/crafttweaker/contentweaker indicate that the pngs should be in resources/textures/items etc. But all I can find is .json files in the models which reference base:textures/items.

Looking for help on finding 
1) location to put the new textures (do they go in resourcepacks/texturepack.zip under assets/contenttweaker/items   /blocks etc , or do my updated textures go in resources/contenttweaker/textures/items   /blocks

2) where can I find the correct filenames for the items, ie gear_copper.png, gearCopper.png or whetever it may be.

Your Environment
* Modpack Version: 3.0.4
* Java Version:
* Launcher Used: Twitch
* Server/LAN/Single Player: Server
* Resourcepack Enabled?: BDCRAFT/Sphax
* Optifine Installed?: No

**Comment by artdude543** [comment]
This is not an issue tracker/wiki for Content Tweaker if you would like support for the mod please visit their own tracker thanks https://github.com/The-Acronym-Coders/ContentTweaker/issues
