### ISSUE TITLE
F7 and F9 light level and chunk boundary overlays not showing (no optifine installed)

### ISSUE THREAD

**Issue by Huginn-Odinbro** [Darkosto/SevTech-Ages#1470]
## Issue / Bug
Pressing F7 and F9 won't show the respective overlays for light and chunk boundaries
## Current Behavior
Nothing happens when I press the keys. I haven't remapped any keys either.
## Possible Solution
I'm not sure if it's the mod conflicting with some PC setups or not, I've only seen one other person with this issue though. Perhaps another overlay mod could be a fix.
## Steps to Reproduce (for bugs)
I can't reproduce it, but I can get it to work for a while again by reinstalling the pack. Then as the pack progresses it seems to lose functionality randomly for me. Restarting the game, launcher, and pc don't seem to fix it.

## Context
I'm trying to see the light levels and chunk boundaries for mining ore and stopping mob spawns.
## Your Environment

* Modpack Version: 3.0.4
* Java Version: Java 8 update 161 (64 bit)
* Launcher Used: Twitch launcher
* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: Soartex modded Fanver
* Optifine Installed?: No

## More Info
PC Specs: CPU- AMD Ryzen 1600
               Video card- GTX 1070 driver version 391.01
               16 Gig DDR3 RAM
If I can provide any more info please let me know.

**Comment by Huginn-Odinbro** [comment]
Yeah I can't quite remember but I think I had this happen on another 1.12 modpack leading me to believe it's not a pack problem either, but wanted to check to make sure. Thanks for the reply though, I'll just do your suggestion everytime it happens.

**Comment by Jandakast** [comment]
Going to close this issue. Hopefully it doesn't happen too often!

**Comment by Kuperus** [comment]
can it be that NEI was disabled in your inventory options? i have mine disabled cause NEI causes problems for me...

**Comment by Huginn-Odinbro** [comment]
Kuperus that was EXACTLY what my problem was. Totally forgot i disabled it because of the awful stutters I would get opening inventories sometimes. That also explains why it seemed to work with a  new pack install but would seem to randomly stop working after. I'd play until it started stuttering, then I'd disable NEI to fix it, thereby turning off my overlays as well. I'm such a derp, thank you!

**Comment by Kuperus** [comment]
No worries Huginn-Odinbro, i had exactly the same troubles the night before... so i knew your frustration :)
