### ISSUE TITLE
Farming with Blockheads Market can be used to get infinite blood in the Tinkers Smeltry 

### ISSUE THREAD

**Issue by Jandakast** [Darkosto/SevTech-Ages#1471]
1. Place Farming with Blockheads market so the villager falls in the tinkers smeltry.
2. Break the Market and replace so a new villager falls.
3. Repeat steps and get infinite blood.

**Comment by WildFTW** [comment]
Um we will live with it :)

**Comment by justinrusso** [comment]
Though this was created first, https://github.com/Darkosto/SevTech-Ages/issues/1487 has a lot of useful info so I'm going to close this one instead.
