### ISSUE TITLE
Bug?  Wheat and hemp are unplanting and farmland becoming untilled randomly

### ISSUE THREAD

**Issue by ArbitraryHubris** [Darkosto/SevTech-Ages#1472]
## Issue / Bug
Farmland is randomly coming untilled like someone has been jumping on them.  I have a hemp farm that is in full sunlight, over a river biome, and fully hydrated - randomly a few blocks will become untilled and the seeds and hemp dropped on the ground.  Multiple people on my server have had this issue, some with wheat as well.  This may be a feature of BWM, but I'm reporting it in case it's an issue.

[Untilled Farm](https://www.screencast.com/t/gQKNFf3bYG5S)

## Your Environment
* Modpack Version: 3.0.4 Server

**Comment by Jandakast** [comment]
This looks very similar to the issue Darkosto had with tumbleweeds bouncing through his farms all the time. Are you in/near a hot biome by chance? Or have you seen Tumbleweeds bouncing around near you?

**Comment by ArbitraryHubris** [comment]
Actually, we are mostly in red rock mountains, red desert and savannah, so lots of tumbleweeds.  I think you're on to something

**Comment by ArbitraryHubris** [comment]
is there any reason to keep the tumbleweed mod on my server?

**Comment by tofof** [comment]
@eyekantspel Probably light level (hemp uproots if under 12, while vanilla plants don't do that until like 7 or so). That's what it was for my identical-sounding issue to yours.

**Comment by ArbitraryHubris** [comment]
Also, hemp has to have view to the sky.

**Comment by tofof** [comment]
Well, the instant-uprooting behavior is not caused by not having a view of the sky, it's caused by light level. I know because I had the hemp completely sealed within a 3x3 tunnel for testing light level.

**Comment by ArbitraryHubris** [comment]
I guess that's changed.  In BWM docs it says "

   - Direct access to sunlight <http://minecraft.gamepedia.com/Sun#Sunlight>
    (The hemp crop must be able to see the sky but does not require
   lighting at night time if growing outdoors)."
