### ISSUE TITLE
[3.0.4] Tin Canister missing recipe

### ISSUE THREAD

**Issue by togreglove** [Darkosto/SevTech-Ages#1475]
## Issue / Bug
Tin Canister required for some galacticraft recipes in age 4, has no recipe. Is it a drop from something?

## Current Behavior
Click R while hover over tin canister, see no recipe

## Possible Solution
Add recipe for tin canister

## Steps to Reproduce (for bugs)
See "Current Behavior" above

## Context
Trying to make the Oxygen Concentrator as part of the space suit.

## Your Environment

* Modpack Version: 3.0.4
* Java Version: Latest
* Launcher Used: MultiMC
* Server/LAN/Single Player: Server
* Resourcepack Enabled?: Faithful 32
* Optifine Installed?: No

**Comment by justinrusso** [comment]
https://github.com/Darkosto/SevTech-Ages/issues/1201

**Comment by togreglove** [comment]
Thanks, I searched in open issues, but neglected to check closed issues. Will not repeat the error.
