### ISSUE TITLE
Crystallized Obsidian Chestplate staged in 3 not craftable until 5

### ISSUE THREAD

**Issue by djnifos** [Darkosto/SevTech-Ages#1477]
![image](https://user-images.githubusercontent.com/2243466/38391293-71f0c1e8-38e9-11e8-88ee-4b8630901314.png)

Change recipe or restage.

## Your Environment

* Modpack Version: 3.0.4
* Java Version: 161
* Launcher Used: Jar
* Server/LAN/Single Player: SSP
* Resourcepack Enabled?: Soartex
* Optifine Installed?: Yes

**Comment by ComaCanadian** [comment]
Want to add that the boots, and helm also are staged to three, and should be five. for the same reason (requiring diamond). version 3.0.6 still has this issue.
