### ISSUE TITLE
Enchantment table stages recipe

### ISSUE THREAD

**Issue by Tayba3** [Darkosto/SevTech-Ages#1478]
2 recipes are displayed as stage 3 and the default vanilla recipe is 1 of them but it says stage 5 is required for the diamonds

## Your Environment

* Modpack Version: 3.0.4
* Java Version: 8 161
* Launcher Used: twitch
* Server/LAN/Single Player: server
* Resourcepack Enabled?: soartex
* Optifine Installed?: yes

**Comment by artdude543** [comment]
Fixed in 3.0.7
