### ISSUE TITLE
Crusher (Immersive Enginerring) stage are missing

### ISSUE THREAD

**Issue by kahlier** [Darkosto/SevTech-Ages#1479]
Can you please add some text to crusher I cant see the age
[Crusher](https://i.imgur.com/GGLjuFQ.jpg)

## Your Environment
* Modpack Version: 3.0.4
* Java Version: 1.8.0_161-b12
* Launcher Used: twitch
* Server/LAN/Single Player: single
* Resourcepack Enabled?: no
* Optifine Installed?: no

**Comment by artdude543** [comment]
Age 3 is when you can use it. It's on the advancements screen when you unlock it. If you look at the components which build multi blocks you'll see what stage they will usable in.

**Comment by kahlier** [comment]
did you see the picture?

**Comment by artdude543** [comment]
Ideally your not meant to see what recipes work on what machine; but this is a limitation of JEI so you'll see them. We also _can't at this time_ edit the naming/tooltips on the JEI menu.

All you can do the end of the day is either make a creative world and see when things unlock or look forward to finding out when you can use an item or machine.

**Comment by kahlier** [comment]
I know I cant see it and it fine the only thing I wanted was the red text but if it cant happen it fine
there are a picture of the red text [Imgur](https://i.imgur.com/GGLjuFQ.jpg)
