### ISSUE TITLE
[Reminder]BWM removing saw recipes

### ISSUE THREAD

**Issue by Dawenzel** [Darkosto/SevTech-Ages#148]
## Issue
The recipes for gears needed to return 1 instead of 2. Also when sawing a bmw:saw it returns iron. Of this moment not yet fixable as the .remove function is broken for the betterwithmods saw.

## Versions
- Minecraft 1.12.1
- Forge 14.23.0.2512
- Java x64 8u144
- Sevtech-Ages Alpha 6

**Comment by Darkosto** [comment]
This SHOULD be good to go on the next update. Thanks for reporting it!
