### ISSUE TITLE
Very low FPS

### ISSUE THREAD

**Issue by DMGGREEN** [Darkosto/SevTech-Ages#1480]
Ok, so I have very low FPS using this mod pack. I have already installed optifine, set alwaysSetupTerrainOffThread to true, disabled BetterFoilage, set settings to low and I still have low FPS (I will post scr of F3, sorry for that but I accidentally clicked Enter)

**Comment by WildFTW** [comment]
?

**Comment by artdude543** [comment]
Please, can you relog the issue using the provided template, please? Don't wipe it out and give no information about your pack install; you won't get any kind of help otherwise. Also client logs!
