### ISSUE TITLE
Very low FPS

### ISSUE THREAD

**Issue by DMGGREEN** [Darkosto/SevTech-Ages#1481]
Issue
I have very low FPS after trying everything I could find like: setting alwaysSetupTerrainOffThread to true, instaling optifine, allocating RAM, disabling BetterFoliage. Here you have my specs and java version I am using and I have 16GB of RAM (Sorry for my previous post I accidentally clicked enter)

![fps](https://user-images.githubusercontent.com/38116772/38393882-a615857e-392c-11e8-9b11-e90c2527d321.png)

Modpack Version: 3.0.4 
Single Player
Resourcepack Enabled?:No

**Comment by extrenix** [comment]
how much ram allocated ?

**Comment by DMGGREEN** [comment]
Disabled all animations and now I hava 200+ FPS
