### ISSUE TITLE
Achievement - The Betweenlands - " Do The Wave " 

### ISSUE THREAD

**Issue by Dwyer79** [Darkosto/SevTech-Ages#1482]
While using the shockwave sword there is an achievement called "do the wave"
"kill 3 enemies with the shockwave sword" 

The kills are not registering in the achievement 

* Modpack Version: 3.0.4
* Server/LAN/Single Player: Server
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by GoryMoon** [comment]
You need to us the shockwave ability of the shockwave sword.
The info of the advancements say "Slay three enemies using a shockwave".
Tested in the pack and this works as intended.

**Comment by GoryMoon** [comment]
Np
