### ISSUE TITLE
Moss Stone turns into cobblestone when placed (Age 1)

### ISSUE THREAD

**Issue by Kiyaku** [Darkosto/SevTech-Ages#1484]
## Issue / Bug
I'm in age 1 and am able to craft moss stone (using vine + cobblestone). However, if i place said block in the world, it turns into cobblestone. Moss stone walls work fine.

## Context
![Recipe](https://i.imgur.com/xwdeewV.png)
![Placed in world](https://i.imgur.com/qIwhsP6.png)

## Your Environment
* Modpack Version: 3.0.4
* Java Version: 1.8.0_161
* Launcher Used: Twitch / Jar
* Server/LAN/Single Player: Server
* Resourcepack Enabled?: New vanilla textures, but also happens without
* Optifine Installed?: Yes, also confirmed without

**Comment by Hebbu** [comment]
probably because all moss stone will appear as cobblestone in age 1

**Comment by Kiyaku** [comment]
Gotcha, that makes sense then, was just confusing that i was able to place it and it's not marked as "unfamiliar item".
