### ISSUE TITLE
Tin canister not craftable in age 4, but required for progression

### ISSUE THREAD

**Issue by masonpinder** [Darkosto/SevTech-Ages#1486]
I MAY have missed something, but I'm pretty sure there's no way to craft the canister, since no recipe will show up.

**Comment by ChipmunkCraft** [comment]
I believe Darkosto has this fixed for 3.0.5

**Comment by justinrusso** [comment]
Dupe #4! https://github.com/Darkosto/SevTech-Ages/issues/1201
