### ISSUE TITLE
Translocators and Carry On don't like each other

### ISSUE THREAD

**Issue by AlphaWarrior987** [Darkosto/SevTech-Ages#1489]
## Issue / Bug
Translocator if picked up by Carry On, (shift right clicking) the other edge it will pick it and when trying to replace it will destroy it instead

## Possible Solution
black list Translocators from CarryOn
## Steps to Reproduce (for bugs)
1. Item/Fluid Translocator on a Tank or Chest
2. Shift right click the edge of the Translocator to trigger 'CarryOn' and then when placing it back it destroys item

## Your Environment
* Modpack Version: 3.0.4
* Java Version:
* Launcher Used: twitch
* Server/LAN/Single Player: SP
* Resourcepack Enabled?: Sortex 
* Optifine Installed?: no

**Comment by Darkosto** [comment]
Added these to the carry-on blacklist. Thank you!
