### ISSUE TITLE
Iron grit.

### ISSUE THREAD

**Issue by MyApolloGees** [Darkosto/SevTech-Ages#1490]
## Issue / Bug
Not an a bug or an issue but would like to suggest a change to iron grit. Currently to make iron grit in stage 3 you need a crusher from immersive engineering or NORMAL iron or to create Iron grit because of the way people progress through like me it would be better if we could use the iron cluster to create iron grit just like copper copper grit can be made using copper clusters.

![image](https://user-images.githubusercontent.com/37778378/38396423-f06b2c2a-392f-11e8-9771-7b4cc3ab6cdf.png)
![image](https://user-images.githubusercontent.com/37778378/38396432-fa6aac46-392f-11e8-8c6d-ec591afe34f1.png)

## Context
I haven't created a crusher yet but wanted to make Redstone Engines from BC. This meant i had to go to the Twilight to get iron ore from a hollow hill which I'm not a fan of doing as i wanted to get my ore only from the veins from exploring. 

## My Environment
* Modpack Version: 3.0.4
* Java Version: Unsure
* Launcher Used: Jar (twitch)
* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: Unity
* Optifine Installed?: Yes

(PS. template should say "My Environment" instead of "Your Environment" Kappa)

**Comment by Darkosto** [comment]
This is actually a bug with the AE2 grindstone handling Iron Ore to make Grit. That should not happen. We need to make it consistent with how the Iron Cluster is handled.

**Comment by MyApolloGees** [comment]
Okay, just with the way you could make iron grit from normal ore seemed like you intended it to be this way and wanted a second way to create the grit. Sorry for how awfully i wrote that btw should really proof read more often.

**Comment by justinrusso** [comment]
@Darkosto Im confused on what you want me to do for this one.
1. If I'm understanding, you want the grindstone to give dust for ores
2. If so.. how much dust? Should there be chances of more?
3. Should *all* ores be the same?

**Comment by MyApolloGees** [comment]
@justinrusso I believe he just wants the normal iron ore removed from the grindstone so that you have to use the crusher

**Comment by justinrusso** [comment]
Ahhh right. You are correct. I thought the crusher was in stage 4 for some reason.

**Comment by iskorp** [comment]
To add to this, Is the inability to smelt Grit in the TC smeltery intended? It just doesn't make sense how a purified version of ore can't be smelted, While raw clusters can...

**Comment by sherkas** [comment]
My natural progression was getting silk touch for my pick... then heading to twilight caves and getting iron ore. Then i built a quartz grindstone and got iron grit. 

I think it was actually a nice progression however you should be able to grind the iron ore in a millstone so you can save the quartz grindstone later.

**Comment by artdude543** [comment]
This is resolved in 3.0.7 with a mass refactor on ore handling.
