### ISSUE TITLE
Game crashes when loading the chunks

### ISSUE THREAD

**Issue by manuelbarbosa** [Darkosto/SevTech-Ages#1492]
## Issue / Bug
Game crashes when loading the chunks
https://pastebin.com/cpnLgcDa

## Steps to Reproduce (for bugs)
I was just exploring around the map (singleplayer) (you can see the coordinates of my player in the log) when the game sudently crashed... every time I try to load my single player workd the game crashes when loading chunks.

## Your Environment
* Modpack Version: 3.0.4
* Java Version: 1.8.0_25
* Launcher Used: Twitch -> default
* Server/LAN/Single Player: single player
* Resourcepack Enabled: yes, using faithful 1.9.4
* Optifine Installed: yes, using the seus renewed 1.0.0

## Solved
* I solved the loading issue by teleporting my player somewhere else. So I assume it is some kind of world generated block/entity that is causing this since I was in a place far away from my constructions

**Comment by justinrusso** [comment]
1377

**Comment by justinrusso** [comment]
In addition, I'd recommend you update your Java. In twitch go to settings > minecraft and find "Jar Launcher" and make sure java version is "Use latest". Then make sure your java installed is up to date. Java 8 162 I believe is the latest.
