### ISSUE TITLE
Minecraft Crashes while loading mods

### ISSUE THREAD

**Issue by DrCraven** [Darkosto/SevTech-Ages#1493]
## Issue / Bug
Minecraft crashes while loading
https://pastebin.com/ZQBtL6Yc

## Possible Solution
Probably have to update a mod

## Your Environment

* Modpack Version: 3.0.4
* Java Version: newest
* Launcher Used: twitch
* Server/LAN/Single Player: single player
* Resourcepack Enabled?: no
* Optifine Installed?: no

**Comment by DrCraven** [comment]
According to both the 'remove older Java' and the Java version checker, Java 161 is installed. I don't know how its detecting java version 25, the computer isnt even 3 months old.

**Comment by DrCraven** [comment]
I see it in the crash file, but I don't know how to change it. I uninstalled and reinstalled Java and its the same problem.

**Comment by DrCraven** [comment]
Here's the paste bin of the crash after uninstalling and reinstalling java version 161 (64 bit)
https://pastebin.com/bkNcKyWJ

it still says java version 25 in the same location

**Comment by DrCraven** [comment]
Also, sevtech was fine yesterday and several other modpacks work. Just keeps on crashing today for some reason. Thank you for you help.

**Comment by ChipmunkCraft** [comment]
Twitch Launcher defaults to "Native Launcher" which forces Java 1.8.0_25

You can either go into Settings->MineCraft in Twitch app and change the "Launch Method" to Jar and then you can tell it to always use the latest Java. (This method will revert to the older Minecraft launcher; which is fine, but it asks you confirm that you want to do that and you might have to manually add the "Profiles back in")

Or (Use this method at your own risk, I am not responsible for any issues this may lead to)

Find out where Minecraft installed the bundled JRE in the "Runtime" folder.  Copy the contents of inside jre1.8.0_161 folder (latest Java) into the 1.8.0_25 folder (Don't change the folder name)
This method makes Minecraft think its version 25 but is actually the latest.  You'll need to manually update this each time Java is updated.

**Comment by justinrusso** [comment]
Looks like your config file corrupted. Redownload the pack

**Comment by DrCraven** [comment]
Alrighty then, Thank you for the help everyone!
