### ISSUE TITLE
Recipe conflict: Clear Glass vs Glass Chunks

### ISSUE THREAD

**Issue by IChris2698I** [Darkosto/SevTech-Ages#1495]
## Issue / Bug
In stage two, crafting one glass by itself makes 4x Glass Chunks, not Clear Glass. As far as I can tell, this makes it impossible to make Clear Glass. I haven't checked if more recipes for it open up in later stages.

## Possible Solution
Maybe add a Work Blade for the Glass Chunks recipe?
Maybe require cooking glass in a furnace to get Clear Glass?
Maybe remove the Clear Glass recipe and add it to chiseling? This would lock Clear Glass behind getting 1 iron ingot, but that's probably not a big deal.

## Steps to Reproduce (for bugs)
1. Get to stage two
2. Cast some glass
3. Craft one piece of glass by itself in the center of the crafting table

## Context
I wanted to make some connected texture glass windows for my house. I'm not sure if Clear Glass would accomplish that, but I wanted to give it a try.

## Your Environment
* Modpack Version: 3.0.4
* Java Version: 1.8.0_91
* Launcher Used: Twitch
* Server/LAN/Single Player: Server
* Resourcepack Enabled?: None
* Optifine Installed?: No

**Comment by artdude543** [comment]
If you searched the tracker before posting (as the template tells you) https://github.com/Darkosto/SevTech-Ages/issues/1310

**Comment by IChris2698I** [comment]
I did search. I didn't see the small "# Closed" link. Thank you.
