### ISSUE TITLE
[Suggestion] Add 'does not consume in recipes' to Blood Orb tooltips from Blood Magic

### ISSUE THREAD

**Issue by 0xb00b** [Darkosto/SevTech-Ages#1497]
Just a random suggestion, feel free to insta-close if this is just me being salty about spending some time crafting multiple Blood Orbs untill i found out they are not consumed when you craft a recipe with them. Can't really find anything about it in the necromonicon either.

**Comment by MyApolloGees** [comment]
blood orbs are blood magic nothing to do with abysalcraft and i see where you are coming from but its always been like that for blood orbs/blood magic so most people know about it and most usually use the orb to craft one thing and see that it doesn't consume. So you're just in the minority for this I've personally never had this problem and even if it does its only gonna happen once in a persons modded career or at least I'd hope.

**Comment by 0xb00b** [comment]
Yeah exactly, i just remember seeing other items before that clearly stated 'not consumed in recipe' so its more a quality of life thingy for people that know nothing about the mod but at the same time like you mentioned and as i experienced, you'll figure it out pretty fast anyways. my 2 cents :paintbrush:

**Comment by artdude543** [comment]
It's not really something I see the need to add a tooltip for as the majority already know about the multi-use for the orbs.
