### ISSUE TITLE
Some sorta singleplayer to multiplayer type bug thing I dunno.

### ISSUE THREAD

**Issue by Girfan3198** [Darkosto/SevTech-Ages#1498]
## Issue / Bug
I try to load the game up in single player, then it doesn't load up in single player and it gives me some sorta java error and then it says couldn't find a server in your area or something to that effect and when I go to try to go back into the world i'm on the server page. I clicked on the singleplayer game mode. Could it have anything to do with the insane load time I have? cause it takes like three or four hours for the game alone to load up.

## Context
I'm trying to play the game.

## Your Environment
* Modpack Version: 3.0.4
* Java Version: 8 update 161
* Launcher Used: Twitch
* Server/LAN/Single Player: Single player
* Resourcepack Enabled?: Default settings
* Optifine Installed?: Uhm?

There I followed your template guide, can I get an answer now? also I don't know how to access crash logs on twitch.

**Comment by justinrusso** [comment]
https://github.com/Darkosto/SevTech-Ages/issues/1518
