### ISSUE TITLE
[3.0.4] The 'raft' from Just A Raft Mod works on land and is negating fall damage.

### ISSUE THREAD

**Issue by 0xb00b** [Darkosto/SevTech-Ages#1499]
## Issue / Bug
The raft from Just A Raft Mod works on land, if you place it down before falling a huge distance you can ''mount" it, fall and negate any fall damage 

## Possible Solution
¯\\_(ツ)_/¯

## Steps to Reproduce (for bugs)
https://cdn.discordapp.com/attachments/329447198452482049/431660020015300609/raft.mp4 (i hope this discord link works)

1. get a raft
2. get yourself up there with a 1x1 dirt tower
3. place raft on tower
4. 'row' off the tower
5. no fall damage $$$ profit 

## Context
i died in the beneath by digging almost straight down and falling like 50 blocks down, spend like an hour making slime boots from rice slimes to negate the fall damage to get back to my grave (which i didnt really mind, stupid mistake costs me 30 min of making slime boots etc) then i got rekt again and didnt want to spend another 30 min making new slime boots so i got mad and remembered vanilla boats can negate fall damage in some way so i messed around with the raft. true story.

## Your Environment
* Modpack Version: 3.0.4
* Java Version: OpenJDK Runtime Environment (build 1.8.0_162-8u162-b12-0ubuntu0.16.04.2-b12)
* Launcher Used: MultiMC
* Server/LAN/Single Player: SP
* Resourcepack Enabled?: SoarTex
* Optifine Installed?: Yes, no shaders.

**Comment by Darkosto** [comment]
You mean like Vanilla boats do? This is a vanilla bug and can't be fixed by the pack.
