### ISSUE TITLE
Tomahawk requires 3x3

### ISSUE THREAD

**Issue by davqvist** [Darkosto/SevTech-Ages#15]
The Tomahawk you required a 3x3 crafting by adding additional null values. Not sure if you want it to be 3x3 crafting. If you want it to be 3x3 crafting, I suggest changing the recipe to make it obvious (like distributing the items differently) as people will come and complain, if it's intended 2x2 you should remove the null values in the recipe.

**Comment by Darkosto** [comment]
Made into 2x2, forgot the reason it was meant for a crafting table.
