### ISSUE TITLE
Embers stage 2 removing recipes

### ISSUE THREAD

**Issue by Dawenzel** [Darkosto/SevTech-Ages#150]
## Issue
There are multiple items/blocks from the mod embers that have 2 recipes assigned to them. These are both the original recipe and a recipe added by crafttweaker. In the script all embers recipes are added to stage 2 by `mods.recipestages.Recipes.setRecipeStage("two", item);` in a for loop (using the ModID) and later individually removed with `recipes.remove(item);`.

When embers is removed from the for loop to add all the recipes to the stage, the recipes are removed just fine. I also tried to place the setRecipeStage line underneath the removal line, but this didn't make a difference from what I could tell.

## Versions
- Minecraft 1.12.1
- Forge 14.23.0.2512
- Java x64 8u144
- Sevtech-Ages Alpha 6

**Comment by Darkosto** [comment]
Yep, this is a known issue at the moment as I'm working my way through the mod still. I'll end up making them all custom and removing the one from the array afterwards :)

**Comment by justinrusso** [comment]
The files have changed drastically since. Closing
