### ISSUE TITLE
diamonds in age 4

### ISSUE THREAD

**Issue by steinjorn** [Darkosto/SevTech-Ages#1502]
diamonds can be crafted in age 4 with the pneumaticraft pressure chamber but seem staged in 5.  Allows crafting of crystalize obsidian chest, helm, boots in age 4 along with some baubles.

* Modpack Version: 3.0.4
* Launcher Used: twitch
* Server/LAN/Single Player: SP
* Resourcepack Enabled?: no
* Optifine Installed?: no

**Comment by artdude543** [comment]
Fixed in 3.0.7.
