### ISSUE TITLE
MC Crashed after I load my world

### ISSUE THREAD

**Issue by Terrahorn** [Darkosto/SevTech-Ages#1506]
## Issue
MC Crashed after I load my world; other worls are working fine
error code: https://pastebin.com/Rduygh8a

## Steps to Reproduce (for bugs)
idk why its crashing, i was doing some blood magic beginning last time I played

## Your Environment

* Modpack Version: started 3.0.3 now 3.0.4
* Java Version: 1.8.0_25, Oracle Corporation
* Launcher Used: twitch
* Server/LAN/Single Player: SP
* Resourcepack Enabled?: no
* Optifine Installed?: no

**Comment by justinrusso** [comment]
Try updating your java and see if this still happens.

Make sure you have Java 161 or 162 installed, then go to the twitch launcher > settings > minecraft.

Once there, look for "Launcher" and chose "Jar Launcher".
Scroll down further and make sure "Java Version" is set to "Latest version"

**Comment by artdude543** [comment]
This _should_ be fixed in 3.0.7 with major updates to BM. If not please make a new issue after the fact.
