### ISSUE TITLE
Spaghetti can be eaten at full saturation/hunger

### ISSUE THREAD

**Issue by Dystilled** [Darkosto/SevTech-Ages#1507]
## Issue / Bug
Spaghetti can be eaten at any time, even at full hunger and saturation 

## Current Behavior
Spaghetti is edible at times it shouldn't be

## Possible Solution
Change to be in line with other foods. 

## Steps to Reproduce (for bugs)
Eat sketti! A lot

## Context
Not in line with other foods 

## Your Environment
* Modpack Version: 0.4
* Java Version: Most Recent
* Launcher Used: Twitch 
* Server/LAN/Single Player: SP
* Resourcepack Enabled?: Soartex
* Optifine Installed?: Yes

**Comment by Darkosto** [comment]
There's a number of foods that allow this, and as I've commented on many duplicate issues before: I am fine with it.
