### ISSUE TITLE
Blood Magic Clay issue (not crafting)

### ISSUE THREAD

**Issue by gekkobear** [Darkosto/SevTech-Ages#1509]
## Issue / Bug

Blood Magic Alchemy Table crafting seems to have issues, initially identified with clay.

https://imgur.com/QisqHwW

Master Blood Orb, bound to me, over 100,000 LP in network.  Nothing happens here.
I tried the 3 carrots + 1 bonemeal for plant oil just to check, that recipe also fails.

Gravel + flint to 2 flint does work (takes no LP, that might be the difference)?

## Current Behavior

Craft doesn't go/start, no LP is consumed.

## Possible Solution

This might be a 1.12 Blood magic issue; I'm unclear on where the problem lies.

## Steps to Reproduce (for bugs)

1. Progress in Blood Magic to get at least  Tier 2 (Apprentice Blood Orb).
2. Bind Blood orb and get LP in network (50 minimum, which binding to yourself should do).
3. Get Blood Magic Alchemical Table.
4. Place Blood Orb, Bucket of Water, and Sand in Alchemical Table, 
5. Craft does not occur

## Context

Wanted an easier source of clay than hunting/digging; have run a bit low, seemed a good choice.
Minimal impact really, comparable (minimal) impact with obsidian or dust doubling; other options exist.

## Your Environment

* Modpack Version: 3.0.4
* Java Version: 1.8.0_161-b12
* Launcher Used: Twitch
* Server/LAN/Single Player: Server
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by artdude543** [comment]
This will be fixed in 3.0.7

**Comment by sathh1** [comment]
I was unable to craft both the nuero toxin and the plant oil using the academical table. Had the correct resources in there and the craft would not start.
