### ISSUE TITLE
[Qol] Skillable requirments

### ISSUE THREAD

**Issue by Dawenzel** [Darkosto/SevTech-Ages#151]
## Issue
There are some requirments assigned by skillable that reference to the incorrent advancement. 

## Solution
**item current advancement -> proposed advancement**
_Porcelain Heater_                stage1/flamehopper -> stage0/flamehopper
_Porcelain Melter_                stage1/flamehopper -> stage0/flamehopper
_Flint Workblade_                 stage1/flint -> stage0/flintknapp (Not sure about this one!)
_Oak Raft_                            stage1/workstump -> stage0/workstump
_Spruce Raft_                       stage1/workstump -> stage0/workstump
_Birch Raft_                          stage1/workstump -> stage0/workstump
_Jungle Raft_                        stage1/workstump -> stage0/workstump
_Acacia Raft_                        stage1/workstump -> stage0/workstump
_Dark Oak Raft_                   stage1/workstump -> stage0/workstump
_Iron Chisel_                         stage1/root -> stage2/root

## Versions
- Minecraft 1.12.1
- Forge 14.23.0.2512
- Java x64 8u144
- Sevtech-Ages Alpha 6

**Comment by Darkosto** [comment]
I think I got them all fixed up! Thanks :D
