### ISSUE TITLE
Bauxite samples appearing in Twilight Forest, most of the dimension is below ore population

### ISSUE THREAD

**Issue by Lewdicolo** [Darkosto/SevTech-Ages#1510]
I can find bauxite samples in the Twilight forest, but the average surface Y level in the dimension is below the range at which bauxite is found

![image](https://i.imgur.com/RDmLiHq.jpg)
![image](https://user-images.githubusercontent.com/19986227/38417332-886acca6-395d-11e8-8b21-24a9481a3d03.png)

Suggested Fix: Removing Bauxite from the Twilight Forest or lowering the Y level for the ore in that dimension

**Comment by daddy77gaming** [comment]
all those ores do spawn, just not at the overworld Y levels

**Comment by Darkosto** [comment]
The ores do spawn and they are moved down to account for the Y-level change. This is not a bug it's a feature created to fix the issue of ores spawning above ground.
