### ISSUE TITLE
immersive engineering Windmill not giving out power

### ISSUE THREAD

**Issue by Dwyer79** [Darkosto/SevTech-Ages#1511]
When hooking up the windmill for immersive engineering, the windmill does not seem to give out any power what so ever. 

![2018-04-06_07 31 26](https://user-images.githubusercontent.com/38117304/38417611-599561ae-396f-11e8-9819-e9f94130c1bb.png)
![2018-04-06_07 31 29](https://user-images.githubusercontent.com/38117304/38417612-59aae09c-396f-11e8-8ff2-04962a479acb.png)

## Client Information

* Modpack Version: 3.0.4
* Server/LAN/Single Player: Server
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by daddy77gaming** [comment]
Just making sure, but you have the windmill plugged into the hole right :)

![2018-04-06_12 32 08](https://user-images.githubusercontent.com/31905330/38419171-ac963c22-399f-11e8-9b6f-272cc9a6929e.png)

sidenote, you do not power a bellow with energy like that.. you want the other windmill or water wheel for that ( the better with mods ones with the axles and gears )

**Comment by dariumz** [comment]
Pretty sure the bellows need the energy produced by the generators from the same mod as themselves, so thru the gear boxes and axles, thing its called ME mechanical energy. Atleast thats what works for me.

**Comment by Dwyer79** [comment]
@dariumz you are correct, that was my bad on reading badly.  @daddy77gaming Although I have hooked the windmill correctly, there is no power going into the capacitor

**Comment by Dwyer79** [comment]
I edited the report to remove an error on my part

**Comment by daddy77gaming** [comment]
only thing i might see it maybe you use RELAY instead of connectors.. but its hard to see the color in those dark pictures

**Comment by dariumz** [comment]
You tried rightclicking the sides of the capacitor to changed it from input/output? :)

**Comment by Hebbu** [comment]
Use connectors instead of relays :/
