### ISSUE TITLE
IllegalStateException: Keyboard must be created before you can query key state

### ISSUE THREAD

**Issue by Girfan3198** [Darkosto/SevTech-Ages#1518]
## Issue / Bug
I try to load the game up in single player, then it doesn't load up in single player and it gives me some sorta java error and then it says couldn't find a server in your area or something to that effect and when I go to try to go back into the world i'm on the server page. I clicked on the singleplayer game mode. Could it have anything to do with the insane load time I have? cause it takes like three or four hours for the game alone to load up.

## Context
I'm trying to play the game.

## Log
https://pastebin.com/0PhsmDxr

## Your Environment
* Modpack Version: 3.0.4
* Java Version: 8 update 161
* Launcher Used: Twitch
* Server/LAN/Single Player: Single player
* Resourcepack Enabled?: Default settings
* Optifine Installed?: Not sure

**Comment by 0xb00b** [comment]
How are you supposed to expect people to fix an issue if you only give a vague description like this? 

Anyways, you can easily provide more information like what operating system are you using (windows/linux/mac), what launcher are you using, what version of the modpack etc etc those are all questions in the template that anyone should be able to answer.

**Comment by Girfan3198** [comment]
Oh yea the last issue I had up had that on it, sorry I just posted that yesterday and it was deleted last night must have forgot to put it up Modpack Version: 3.0.4
Java Version: 8 update 161
Launcher Used: Twitch
Server/LAN/Single Player: Single player
Resourcepack Enabled?: Default settings
Optifine Installed?: Uhm?

**Comment by 0xb00b** [comment]
You can find the twitch app crash log location within the Twitch App settings. Just click on the settings cog wheel in the bottom left and then navigate to the tab on the left, near the bottom called Minecraft. You should be able to locate the default pathway there, and change it, if need be. There should be some crash logs there, please upload them to github as a gist or to pastebin.com or whatever.

**Comment by Girfan3198** [comment]
[crash-2018-04-03_20.20.37-client.txt](https://github.com/Darkosto/SevTech-Ages/files/1885109/crash-2018-04-03_20.20.37-client.txt)

**Comment by 0xb00b** [comment]
Yep, thats it!

**Comment by Girfan3198** [comment]
Internal Exception: Java.nio.channels.closedchannelexception thats the error I get, it says connection lost and back to server list when i had clicked singleplayer.

**Comment by 0xb00b** [comment]
@Girfan3198 are you sure the twitch launcher is set-up to use the right java version when launching minecraft? There should be an option somewhere where you can select native launcher or jar launcher, make sure you use the jar launcher. I have a feeling (especially when you now mention extremely long load-times) that it might be your java version. Either way wouldnt hurt to check/try

**Comment by Girfan3198** [comment]
What should it be set to?

**Comment by 0xb00b** [comment]
>make sure you use the jar launcher.

**Comment by Girfan3198** [comment]
Yesterday I was looking around on the issues page and saw someone say that to someone and when I did that it messed up a different mod pack called projectozone, and even then I tried getting back into sevtech but it didn't work and gave me the same error I can try again if you would like me to.

**Comment by 0xb00b** [comment]
I dont think that will resolve the issue to be completely honest, but just to rule that out you know.. doesnt hurt to try, so i guess its up to you.

**Comment by Girfan3198** [comment]
I'll try it because I love survival packs like this.

**Comment by Girfan3198** [comment]
So now I get an error that says the jar launcher is outdated. is this true the build says 1.6.84

**Comment by 0xb00b** [comment]
No idea, the only other thing that i can think of to suggest is try another launcher, maybe try installing  MultiMC, then download the zip file from curseforge for the pack ( from https://minecraft.curseforge.com/projects/sevtech-ages/files/2547152 ) and create a new instance / import the zip file in MultiMC

**Comment by Girfan3198** [comment]
Well I just so happen to have atlauncher, should I try it on there and then try that multimc thing?

**Comment by 0xb00b** [comment]
Sure, sounds like a good plan.

**Comment by Girfan3198** [comment]
well this launcher is loading the game a hell of a lot faster, alright loading up the game itself we will see if it works AHHHH IT LOADED!! thanks I never thought of loading it on atlauncher. If I have another issue I'll gladly post it and any suggestions I'll post as well.

**Comment by Girfan3198** [comment]
Might be some sorta incompat with Curse/twitch.

**Comment by Girfan3198** [comment]
Now it stutters cause it seems like its constantly saving the game state

**Comment by Girfan3198** [comment]
In the at launcher log it constantly says its saving the game and saving this and saving that is there a way to turn that off?

**Comment by justinrusso** [comment]
https://github.com/Darkosto/SevTech-Ages/issues/1671
