### ISSUE TITLE
Betweenstone slabs - unremovable and duping

### ISSUE THREAD

**Issue by SingleM4lt** [Darkosto/SevTech-Ages#1519]
## Issue / Bug
Slabs of Betweenstone will not break, instead they will reappear while you get a duped slab back. If hit from below or the sides the reappearing slab will switch upper/lower placements, and if hit from above they will stay or switch to lower. The durability of a pickaxe doing this does not seem to be deminished, so with a autohotkey script or a simple weight on your mouse button you can get infinite slabs.

The slabs will not even break, or STAY broken, in creative mode.
It does not matter if the slab is placed in the normal world or in the Betweenlands dimension.

## Expected Behavior
I'd expect the slab to come off and not be duped.

## Steps to Reproduce (for bugs)
1. Place a Betweenstone slab.
2. Whack said slab with a pickaxe at different angles of attack.
3. Watch the slab reappear.
4. Observe the amount of slabs in your inventory grow.
5. Notice that the durability of your pickaxe stays the same.

## Context
The bug, or at least unexpected behavior was encountered when trying to build a secure shelter in the Betweenlands. Now I have slabs that I can't break in my shelter :)

## Client Information
* Modpack Version: 3.0.4
* Java Version: 1.8.0_25
* Launcher Used: Twitch launcher
* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: Yes, Soartex
* Optifine Installed?: Yes

**Comment by ItalianCGP** [comment]
does the pick exp get higher?

**Comment by GreatBanoose** [comment]
Yep, you indeed get exp on tinker tools

**Comment by Mack1410** [comment]
If I may add, when you move the tinker's tools to another slot in your inventory all gained XP from breaking slabs is removed and durability restored

**Comment by Jandakast** [comment]
This is a bug with the integration of KleeSlabs and The Betweenlands. It has been reported to the KleeSlabs dev. 

https://github.com/blay09/KleeSlabs/issues/17

**Comment by blay09** [comment]
Fixed in latest KleeSlabs version.
