### ISSUE TITLE
Crash on Stage Advancing Attempt

### ISSUE THREAD

**Issue by Daturix** [Darkosto/SevTech-Ages#1520]
So I am running a 3.0.3 server with same version clients, I myself was in stage 1 and have cooked a clay bucket and upon retrieval of the bucket from the kiln my client crashed. I have been getting crashes within the past hour, most likely due to java and memory so I thought it was due to reloading the world due to the next stage doing its thing so I ignored it. I load the client back up and in my advancements I have it finished, yet I have stage 2 locked still. Dropping and remaking another bucket does not fix this.

The issue prevents advancement, I searched the issues for anything similar to this yet found nothing.
Will be able to provide any additional information thats needed that I can provide.

**Comment by justinrusso** [comment]
"Next time you have a crash, check your latest.log file, create a pastebin of it and put the link here."

Before doing this, make sure you are running the latest version.
