### ISSUE TITLE
Game crashes when opening the Astral tome

### ISSUE THREAD

**Issue by Antiquadoh** [Darkosto/SevTech-Ages#1522]
Hello.

I have a standard installation of SevTech, I tried a clean installation, same problem 

 
## Issue / Bug

I have set my controls so that i move forward with my right mouse button due to a mental problem (people always ask me, if I am retarded)
When doing so, everytime I open the Astral Tome the game crashes ...
If I change my move forward key, to any key on the keyboard, it works fine, but like I said, im retarded and HAVE to move forward using right mouse button.

I am guessing that the crash has something to do with the fact that you are able to zoom in and out of the discovery page in the Astral Tome with your "Walk forward" and "Walk backwards" keys, and that does not support mouse buttons?

Is it possible to change the astralsorcery mod so I can move forward again ?

Crash log : https://pastebin.com/QJHvVQtr

## Steps to Reproduce (for bugs)

1.set the move forward key to a mouse button
2.try and open the Astral Tome

## Client Information

* Modpack Version: Itried both 3.0.3 and 3.0.4
* Java Version: Version 8 Update 161 (build 1.8.0_161-b12)
* Launcher Used: the new one

* Server/LAN/Single Player: Single player
* Resourcepack Enabled?: none
* Optifine Installed?: Don't think so

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Soultion:
* Sponge (Non-Vanilla Forge) Server?:

* Additional Content Installed?:

**Comment by Darkosto** [comment]
This would be on @HellfirePvP 's end but I don't know when he'll be able to come back to modding to take a look at it.

I can tell you I was able to use this mod and the book with no issues along with many other players. Will look into it.

**Comment by Antiquadoh** [comment]
So you or others did not crash the game, when using right mouse button to move forward, while opening the book ?

**Comment by HellFirePvP** [comment]
> 1.set the move forward key to a mouse button
2.try and open the Astral Tome

That is precisely what crashes. GL handles mousebuttons and keyboard buttons differently for querying their state and thus it can't find the appropiate key for a "mouse button". I'll add a workaround for v1.9 for which i don't have an ETA yet, except "soon-ish"

**Comment by Antiquadoh** [comment]
@HellFirePvP Hell yeah ! Sounds good :) then I can stop walking around like a crab

**Comment by justinrusso** [comment]
Appears to be fixed in https://minecraft.curseforge.com/projects/astral-sorcery/files/2555339
