### ISSUE TITLE
Plastic Mixer interface is misleading

### ISSUE THREAD

**Issue by 3jlowes** [Darkosto/SevTech-Ages#1523]
## Issue / Bug

I can not insert Rose red, Lapis, or cactus green into the plastic melter

## Expected Behavior

Upon left clicking item to put it in the slot it should go in.

## Possible Solution

Not sure

## Steps to Reproduce (for bugs)

1. Attempt to dyes in the plastic mixer
2. See that it does not work

## Context

Im just trying to complete some advancements

## Client Information

* Modpack Version: 3.0.4
* Java Version: 1.8.0_161
* Launcher Used: Twitch

* Server/LAN/Single Player:
* Resourcepack Enabled?:
* Optifine Installed?:

## Server Information
* Java Version: 1.8.0_161
* Operating System: Windows 10
* Hoster/Hosting Soultion: Dedicated Server
* Sponge (Non-Vanilla Forge) Server?: Vanilla

* Additional Content Installed?: None

**Comment by Stormfirebird** [comment]
You need to convert them do dye powder.
JEI definitely needs to be fixed for this.

**Comment by justinrusso** [comment]
As storm said, you need to use the dyes, not minecrafts "dye" items which are not a dye in this pack.

**Comment by justinrusso** [comment]
https://github.com/TeamPneumatic/pnc-repressurized/issues/159

**Comment by desht** [comment]
Just to note the newly released PneumaticCraft 0.6.4 fixes this issue.

**Comment by justinrusso** [comment]
https://minecraft.curseforge.com/projects/pneumaticcraft-repressurized/files/2558025

**Comment by artdude543** [comment]
Added to the update for 3.0.7 😄 thanks again to @desht !
