### ISSUE TITLE
V3.04 , Age 0: Arrow recipie shows wrong ammount of string

### ISSUE THREAD

**Issue by ReveralX** [Darkosto/SevTech-Ages#1524]
I tested on flint arrow. (did not test on bone arrow, call me lazy)
Recipie shows flint arrow should have 8 + 8 string (total 16) and make 6 arrows.
BUT during crafting it takes only 1+1 string, leaving 7+7 on table. Still It gives 6 arrows as by recipie.

TL:DR: Flint arrow recipie shows wrong ammount of string needed. 

TL:TL:DR: bug

System specs: Computer

**Comment by justinrusso** [comment]
https://github.com/Darkosto/SevTech-Ages/issues/1440
