### ISSUE TITLE
Stone tools destroying certain objects, intentional?

### ISSUE THREAD

**Issue by Posivated** [Darkosto/SevTech-Ages#1525]
I just destroyed my Starlight crafting altar by trying to pick it up with a stone pick, is this supposed to happen? I can pick up other things like blood altar, beneath portal, astral sorcery light well, the luminous crafting table, and every  thing else I have made by using my stone pick. If this is intention can we please get something to indicate what is required to use on certain objects?

**Comment by justinrusso** [comment]
The Astral Sorcery tables were fixed in https://github.com/Darkosto/SevTechAgesConfigs/commit/65a6e377ba9ad8dcab29ce61f7a2f599134c826b.

Will need to look into the Blood Altar and Beneath Portal.

**Comment by Posivated** [comment]
So it is intentional? Are we going to have any indication of what is required to break what?

**Comment by Darkosto** [comment]
No, he's saying it is not intentional and that the known blocks are being fixed.
