### ISSUE TITLE
Crash Loop after Starting Age 3

### ISSUE THREAD

**Issue by Shock2k** [Darkosto/SevTech-Ages#1527]
Issue / Bug
Pretty close after unlocking Age 3. (Did not happen immediately after completing the steam engine.  
The last action I took was building the manual (book and lever) and building the engineering hammer.  The one weird thing was that the achievement didn't kick in after I created the hammer.)

Within 10 or 120 seconds of loading in, the world crashes.  

Crash Reports:
It's not generating a crash report.

A replay report is generated...

Initial Crash:
[hs_err_pid9160.log](https://github.com/Darkosto/SevTech-Ages/files/1885624/hs_err_pid9160.log)
[replay_pid9160.log](https://github.com/Darkosto/SevTech-Ages/files/1885625/replay_pid9160.log)

Crash after attempting to reload and re-login:
[replay_pid13476.log](https://github.com/Darkosto/SevTech-Ages/files/1885628/replay_pid13476.log)
[hs_err_pid13476.log](https://github.com/Darkosto/SevTech-Ages/files/1885629/hs_err_pid13476.log)

Is this a Java issue?  What specific version do you recommend?
Initial Crash

## Client Information

* Modpack Version: 3.0.4
* Java Version: 1.8u25
* Launcher Used: Twitch
* Resourcepack Enabled?: Soartex
* Optifine Installed?: Yes

**Comment by Shock2k** [comment]
So I RTFM'd a little and realized I was launching with u25 and you are looking for 161 or higher.  Went and installed 161 then changed my launcher settings to point towards the new install: c:\Program Files\Java\jre1.8.0_162\bin\java.exe

Fixed the problem.

By the way issues:open is a tag in the search bar dynamically.  You may want to clear it out or include closed for searching so newbs like me find the closed tickets that would address the issue.  (I know you have it on the load screen also, no excuses from me.)

**Comment by justinrusso** [comment]
Thats a default of github. We cant change that.

Glad that you got it fixed!
