### ISSUE TITLE
Is the chisel suppose to bypass all the marble making recipes for Astral Sorcery?

### ISSUE THREAD

**Issue by Ragestrike** [Darkosto/SevTech-Ages#1528]
## Issue 
There is all these recipes for marble for Astral Sorcery to make for example runic marble, but you can bypass all these with a chisel. In fact some recipes for the luminous crafting table require you to chisel raw marble from Chisel into Marble from astral sorcery just so you can make runic marble, or you can just use the chisel to make runic marble and bypass that step. 

## Possible Solution
remove non chisel marbles from chisel list until stage 3, and change some of the recipes such as the one for runic marble so that you can use anyblock:marble instead of just Marble from astral sorcery. so you dont need a chisel. since chisel raw marble is what spawns natually.

or just remove the Astral Sorcery recipes.

Or add some quest for a chisel  on the same line as the lightwell.

## Context
Not high priority or game breaking, but it forced me to make a chisel because my raw marble wasnt good enough for it. and shrines are disabled so there was no way for my to get it that way.

## Client Information

* Modpack Version: 3.0.4
* Java Version: 161
* Launcher Used: Jar

* Server/LAN/Single Player: Server
* Resourcepack Enabled?: no
* Optifine Installed?: no

**Comment by Vyraal1** [comment]
Yes, this is pretty much the intended way to get the AS marble.

**Comment by artdude543** [comment]
This is intended and oreDict to be supported this way.
