### ISSUE TITLE
Direwolves Drops

### ISSUE THREAD

**Issue by chiefklondog** [Darkosto/SevTech-Ages#153]
Direwolves do not seem to drop anything wolf related (pelts/head). I killed about 10 with only bones and meat dropping.

Also, the drop rate for pelts from Steppe wolves seems to be about 1 per but they spawn rarely so its hard to farm them. The drop rate for wolf heads is very close so I ended up with almost as many wolf heads as I did pelts after farming for them.

Pack Version 6

**Comment by Darkosto** [comment]
All added :) Should be good now!
