### ISSUE TITLE
Opening inventory while a Mk2 Crafting stump is placed causes lag spike

### ISSUE THREAD

**Issue by Crazy-San** [Darkosto/SevTech-Ages#1531]
## Issue / Bug
After Placing a crafting stump MK2 in the world the game freezes for several seconds each time the inventory is opened.

## Client Information

* Modpack Version: 3.0.4
* Java Version: 1.8.0_25
* Launcher Used: Twitch

* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?:Pack Default
* Optifine Installed?: No

**Comment by vadis365** [comment]
sounds like this duplicates #778
pretty sure this isn't a workstump related bug.
