### ISSUE TITLE
SevTech Ages Keeps Crashing Shortly After Loadup

### ISSUE THREAD

**Issue by Sleepingbadgr** [Darkosto/SevTech-Ages#1533]
## Issue / Bug
 Shortly after a world is created the game crashes abruptly, no prior signs of issues.
 https://pastebin.com/V5BZ9iQ4

## Expected Behavior
 The first couple of times it happened a few moments into the pack. More recently it happens within a minute of world load. From what I gather from the crash log, it is an "out of memory" issue, yet I have over 5gb of memory allocated to it. This does not happen with any other minecraft packs I run.

## Context
 I am unable to play the game at all with this issue.

## Client Information

* Modpack Version: 3.0.5
* Java Version: Version 8 Update 161 (build 1.8.0_161-b12)
* Launcher Used: Twitch Launcher (Native Launcher)
* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by artdude543** [comment]
`java.lang.OutOfMemoryError: Batching chunks` <-- This is the issue.

Allocate more memory and you'll be good! :)
