### ISSUE TITLE
IE MetalPress Issue in Age 3

### ISSUE THREAD

**Issue by pgriff83** [Darkosto/SevTech-Ages#1534]
Sirnotappearinginthisfilm:
From watching Soaryn's stream

built multiblock for IE metal press (current age: 3).  Upon trying to form multiblock was informed in game that the multiblock could not be formed and further progression was required.  Continuous clicking, however, formed the multblock.
(sorry for the secondhand minimal info report, best I could do as I wasn't the one actually playing)

**Comment by mtimyself** [comment]
Could be useful to link the VoD + timestamp. You need to form the IE machines by clicking the correct block with the hammer. But since I am pretty sure he would know that there might be an actual issue here.

**Comment by sherkas** [comment]
Second this. Was fully completed up to oil processing (past boiler) and could not form the metal press. Same error.

After reading this and spam building... 40+ times it finally created.

**Comment by ragehugs** [comment]
You gotta click the piston to form it, hitting the belts causes this message.
