### ISSUE TITLE
Bug: Glass vial on empty Barrel causes crash

### ISSUE THREAD

**Issue by Ritsuna** [Darkosto/SevTech-Ages#1537]
When using a empty vial on a empty lidded barrel from primal core it causes a full game crash.
Would be nice for it to just not cause a crash given how long the load time takes.
https://pastebin.com/0ULfLVK1

## Steps to Reproduce (for bugs)
1. right click vanilla empty vial on empty lidded barrel
2. Crash

## Context
Accidentally clicked it rather then barrel i wanted. repeated the test to be sure it was not a one off.

**Comment by An-Sar** [comment]
this is fixed in dev and will shortly be released as part of 0.6.49

**Comment by justinrusso** [comment]
https://minecraft.curseforge.com/projects/primalcore/files/2558012

**Comment by artdude543** [comment]
Added for 3.0.7
