### ISSUE TITLE
Advancement order - Bark

### ISSUE THREAD

**Issue by chiefklondog** [Darkosto/SevTech-Ages#154]
[Bug] In order to unlock the advancement to be able to use a knife to get bark off a tree you need to craft an item (birchbark tome) which requires bark to make. (Unless I am missing another way to get it)

There are 2 other ways to get back, with a saw and with a stage 1 recipe. Both of these are not possible at this early stage when trying to do the advancement.

[Feedback] The hopper upgrade advancement takes bark to complete however you cannot get bark without completing another advancement in a completely different path that you might not even have uncovered yet. It can be confusing since the trees are so separate.

Pack Version 6

**Comment by Dawenzel** [comment]
You can use the flint workblade (which is also a advancement) to get bark from logs. When using the workblade shift-right click a straight up log multiple times until the bark comes off. I think the stage 1 recipe you mentioned is the continuation from this as you can then debark the log inside a crafting grid using the same workblade.

**Comment by Darkosto** [comment]
I think this boils down to making things a bit more clear to the player ahead of time so they know what they can/can't do at any given moment. I'll note this as an enhancement and make things a bit easier to follow.
