### ISSUE TITLE
Age 3: Coke/Creosote/Treated Wood Planks Enhancement Request

### ISSUE THREAD

**Issue by Shock2k** [Darkosto/SevTech-Ages#1540]
Enhancement Request:
Starting Age 3 is really confusing.  To build the engineering workstation you need "Treated Wood".  To get Treated wood you need Creosote.  To get Creosote you need a Coke Oven.  To get a coke oven you need a projector that requires Treated Wood (which you can't get... because start this paragraph over again).

So basically, you can't build the chicken without the egg (Treated Wood).  Also, there is no way to tell how the heck you are supposed to make, get, pray for Coal Coke.

Some objective for (Make treated wood) or (Get Cole Coke from... your mama) would be really helpful in getting the age started out right.

Thanks!

**Comment by ragehugs** [comment]
You do not need a projector to make a coke oven. Just make 3x3x3 coke bricks and hit it with engineer's hammer. Coal coke is made by putting coal into the coke oven (this will also produce creosote). This is all detailed in the Engineer's book.

**Comment by Shock2k** [comment]
Really appreciate the response.  How do I make coke bricks without coke?

**Comment by Shock2k** [comment]
Never mind.  There is a recipe for making coke bricks.  That dam is broken, I'm moving again.  Cheers!

By the way I did read the manual.  It doesn't discuss how to make coke bricks.  All it says on the matter is to use 27 coke brick slabs (to create the bricks).  I still think the original enhancement request stands.  A simple note that says "Create Coke Bricks" probably would have helped me avoid the problem above.
