### ISSUE TITLE
Totempedia missing most entries

### ISSUE THREAD

**Issue by timmit99** [Darkosto/SevTech-Ages#1543]
Version 3.0.4
 
## Issue / Bug
Totempedia only has 2 entries
[Screenshot here](https://gyazo.com/9d40befc2f0d79d2f4766267fb3361af)

## Expected Behavior
Should have ALL the entries.

## Context
I cannot progress further without doing research outside of the game because i need Cedar for the 3rd tier hopper and i have no information about how to do the ritual.

**Comment by Darkosto** [comment]
That looks like you're on a bookmark. Doesn't the arrow at the bottom of the book bring you to the main page? 

I don't have this issue and cannot reproduce only having access to two pages.

**Comment by ZhuriaJ** [comment]
For what it's worth, I was having this issue too. I had to do a reinstall as well (thanks timmit!). Might be related to me clicking too fast when I first opened the totempedia and accidentally made a bookmark? Even after deleting it, I could not get back to the index; no matter how many times I hit the back button, it just shuffled between Buffalo and Red Cedar.
