### ISSUE TITLE
[v3.0.5] Blood Magic - Some recipes in Hellfire Forge are broken.

### ISSUE THREAD

**Issue by MiniKatalyst** [Darkosto/SevTech-Ages#1546]
## Issue / Bug
Attempting to craft Blood Lamp Reagent and Holding Reagents, hit a wall when the lesser gem would not craft, then later the holding reagent wouldnt craft as well.

I've tried breaking/ replacing the forge, as well as using different gems.

**To make the Blood Lamp Reagent you require the lesser gem, which apparently others have had no problem making in age 2 prior to the 3.0.5 update, but the lesser gem doesnt work:**
Lesser Gem:
![image](https://user-images.githubusercontent.com/37491065/38453149-610b0cd8-3a94-11e8-8ea7-0c1a6912f45a.png)

![image](https://user-images.githubusercontent.com/37491065/38453154-73f926ea-3a94-11e8-9d51-ccab5f756bf4.png)

Blood Lamp Reagent:
![image](https://user-images.githubusercontent.com/37491065/38453134-24883eac-3a94-11e8-8e0f-c4a5f21e5111.png)

Holding Reagent:
![image](https://user-images.githubusercontent.com/37491065/38453141-4b3022c2-3a94-11e8-9d88-90afe812606d.png)

![image](https://user-images.githubusercontent.com/37491065/38453178-bebf1054-3a94-11e8-9a33-4a6c87179242.png)

## Context
Through preparing myself for the Twilight Forest, I decided to make the Blood Lamp Sigil, as I've seen streamers use this. When going through this, a streamer walked me through what to do, but hit a wall when the lesser gem wouldn't craft, had to cheat in the reagent and keep moving along.

## Client Information
* Currently in Stage 2
* Modpack Version: 3.0.5
* Java Version: 
* Launcher Used: Twitch

* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: Faithful + Faithful modded
* Optifine Installed?: No

**Comment by unclekakarot** [comment]
This is not a bug. To use the Hellfire Forge you need a minimum amount of will to start the crafting. The amount needed for the lesser gem is 60 and most demonic will's don't have that much, so you have to fill up a petty gem to get it to work. As for the blood lamp reagent you need a minimum of 200 so you need to get the petty gem and then fill that up to be able to craft the reagent. Make sure you hover over the arrow when looking at the recipe to see the minimum amount needed to craft things.

**Comment by SummitSummit** [comment]
The OP may have been trying to craft w/o Will, but I can't even make the Petty Tartaric gem.  I have a 2.39 Demonic Will in the right slot and Ash, Blue Dye, Shadow Fragment, and Bronze ingot on the left, but it does nothing. 
Also on version 3.0.5
I would try the alternate (original) recipe but I don't have redstone yet.

**Comment by SummitSummit** [comment]
Aha!  I figured it out!  The Hellfire Forge recipes are supposed to be shapeless, but they are not.  You must put the ingredients in the same spots shown in JEI or it will not craft.

**Comment by artdude543** [comment]
There was fixes and tweaks done in the mod and to our scripts which look like have fixed the recipes for 3.0.7
