### ISSUE TITLE
Rustic Pot will lose it's inventory when trying to carry it

### ISSUE THREAD

**Issue by Rikshy** [Darkosto/SevTech-Ages#1547]
Modpack Version: 3.0.5
Java Version: 8.0.162
Launcher Used: Twitch / Jar Launcher
Server/LAN/Single Player: Server
Resourcepack Enabled?: Default
Optifine Installed?: yes

Well, basically what the title says. Tried to pick up a Rustic Pot with Carry On it yielded "Error detected. Cannot pick up Block" in chat.
I can't provide the error log (if there is one) right now because the admin is sleeping.
There is no client or server crash just the loss of the inventory.
Breaking the Pot will not drop the inventory.

**Comment by ZephyrWindSpirit** [comment]
I've encountered a similar error trying to carry the brewing barrel, liquid barrel and crushing tub from rustic. Lose the inventory and receive an error.

**Comment by justinrusso** [comment]
The issue that references this one has some extra detail, so I'll close this one out. 👍
