### ISSUE TITLE
Improved Backpack and Blood Magic Living Armor issue

### ISSUE THREAD

**Issue by gekkobear** [Darkosto/SevTech-Ages#1549]
## Issue / Bug

When wearing a full set of living armor, the Improved Backpack will open for half a second, then close.
If I remove my Living Chestplate (or boots, any piece of the set), I can access the backpack.

## Expected Behavior

Access backpack regardless of armor sets.

## Possible Solution

I'm not sure if this is a problem with Blood Magic handling something (possible, as Alpha) or the backpack reading something the armor is doing?

## Steps to Reproduce (for bugs)

1. Progress Blood Magic to get a full set of living armor.
2. Wear full set of armor.
3. Try to open an improved backpack.
4. Remove one piece of armor for it to work as expected.

## Context

Nuisance, not game-breaking under normal circumstances.

## Client Information

* Modpack Version: 3.0.4
* Java Version:  1.8.0_181-b12
* Launcher Used: Twitch

* Server/LAN/Single Player: Server
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by unclekakarot** [comment]
Can confirm this is an issue

**Comment by MonkeyPrime** [comment]
A little more info, I found that removing the living chest plate causes the issue to resolve itself.  While wearing the living chest plate the description flips between the shortened description and the detailed version.

**Comment by gekkobear** [comment]
tha worked to resolve the issue; and with 3.0.5 after donig that once (even after a server restart) the issue has not recurred.

Closing the issue assuming that 3.0.5 changes corrected it, or it was a one-time thing carried over from 3.0.4.
