### ISSUE TITLE
Keeps crashing

### ISSUE THREAD

**Issue by Xetard** [Darkosto/SevTech-Ages#1550]
Since 3.0.5 i keep crashing after a few minutes of gameplay. i've crashed 3 times within last 30minutes and i have been doing different things everytime.

Soartex texture pack
Latest java
no optifine
Single player

https://pastebin.com/hxE246eR

**Comment by Boomflex** [comment]
Try pressing F8 in game and disabling Better Foliage.

Try that and feedback what you find.

**Comment by Xetard** [comment]
Crashed again..
https://pastebin.com/UaNKDvsM

**Comment by Arisonius** [comment]
How much RAM are you giving the pack?

**Comment by Xetard** [comment]
8GB, i have tried lowering it and no change to the crashes
