### ISSUE TITLE
save wiped upon update to 3.0.5

### ISSUE THREAD

**Issue by Infinitea-and-Biscuits** [Darkosto/SevTech-Ages#1553]
## Issue / Bug
After updating from 3.0.4 to 3.0.5 using the twitch launcher my saves seem to have been wiped, I assume this is a bug with the twitch launcher rather than the mod-pack but figured i would report in case it was relevant.

The folder structure within the instance\saves folder is still intact but there are no files located in any of them, also the twitch launcher's backups folder seems to only have the TombManyGraves files backed up, not the full saves.

## Expected Behavior
I would expect to maintain my save between updates

## Possible Solution
In future I obviously need to take periodic manual updates as the twitch launcher neither did it's own backups or kept the old files intact.

## Steps to Reproduce (for bugs)
n/a

## Context
loading up for first time today, saw there was a changelog for a new version so told twitch app to update, it seemed to do so without issue but upon loading the game I saw my saves were missing.

Upon checking the files, saw that both the saves and backup folders were empty.

## Client Information
* Modpack Version: 3.0.4>3.0.5
* Java Version: 1.8.0_25
* Launcher Used: Twitch

* Additional Content Installed?: No

**Comment by Darkosto** [comment]
This is not a pack issue, this is a twitch app issue. There's actually nothing I can do about this on my end.

It's up to you to backup before you update the pack in any way you see fit. 

Sorry for the inconvenience.
