### ISSUE TITLE
Bear Claw textures missing

### ISSUE THREAD

**Issue by HietsoM** [Darkosto/SevTech-Ages#1554]
## Issue / Bug

My Bear claw textures are missing, after I update to 3.0.5. 

https://imgur.com/a/3bqJR

## Client Information
* Modpack Version: 3.0.5
* Launcher Used: Twitch Launcher
* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by macrosblackd** [comment]
Can confirm as well.

**Comment by BonaireDreams** [comment]
Confirmed same issue in 3.0.6.

**Comment by BullBoy85** [comment]
Confirm, same issue here - Invisible bear claw on version 3.0.6. I don't use any resource packs, but I do use Optifine.

**Comment by madkat5** [comment]
I'm seeing it in 3.0.6, without optifine.

**Comment by artdude543** [comment]
This appears to be fixed in 3.0.7
