### ISSUE TITLE
Primal Core Storage Crates giving items from OP mode

### ISSUE THREAD

**Issue by garlicinyoureye** [Darkosto/SevTech-Ages#1555]
Pack Version 3.0.4
Forge 14.23.2.2635
Mod in question: Primal Core

When on a server with op rights but in SURVIVAL mode trying to shift +CTRL up arrow to input all of one item into the crate will give you the 1 stack of that item and the command will populate in console.  This interaction happened on our server with an oak storage crate.  When I removed the op rights it would no longer work.

**Comment by artdude543** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

Thanks again for reporting, and we hope you enjoy the pack!
