### ISSUE TITLE
Gold samples, but no gold ore in the chunk

### ISSUE THREAD

**Issue by Turmfalke2** [Darkosto/SevTech-Ages#1556]
## Issue / Bug
I have found a chunk with several surface gold samples:  

![2018-04-07_15 29 21](https://user-images.githubusercontent.com/5174562/38455484-42aae63e-3a79-11e8-94ba-f883d171b923.png)

plenty of digging later I have found 0 gold ore, while carving out all blocks in the chunk between y 32 and y 5.

![2018-04-07_15 22 47](https://user-images.githubusercontent.com/5174562/38455460-b0e0cd4a-3a78-11e8-89df-f4ec19ea038f.png)

## Expected Behavior
Chunks with gold surface gold samples should contain gold deposits.

## Steps to Reproduce (for bugs)

1. Search for gold samples
2. dig down and carve out the chunk between y 32 and y 5.

## Context
I am trying to progress in age 2, without gold is this challenging. 

## Client Information
* Modpack Version: 3.0.5
* Java Version: 1.8
* Launcher Used: MMC

* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: yes
* Optifine Installed?: no

**Comment by iDarper** [comment]
Keep in mind,  veins can also generate into the surrounding chunks it's not always going to be directly under the sample

**Comment by daddy77gaming** [comment]
betweenlands right .. seems betweenland terrain gen makes it so overworld ores cant spawn bc they have no blocks to replace

from an earlier post: #1286

**Comment by justinrusso** [comment]
@iDarper there will at least be a single block in the chunk. This is clearly not the case in this image, and thus shows an issue.

As @daddy77gaming stated, this appears to be the same issue as #1286.
