### ISSUE TITLE
Nether Imp Spawn Rate Too High

### ISSUE THREAD

**Issue by Aphenro** [Darkosto/SevTech-Ages#1558]
Imps are spawning in the nether at a high rate causing the game to lag out and freeze.  I did notice this occurring to a lesser degree in age 3 but now that I'm in age 4 the nether is almost unplayable.  I've attached a screenshot. 
![2018-04-07_09 41 33](https://user-images.githubusercontent.com/38159477/38455609-90272692-3a48-11e8-81f6-25d0e3e617fc.png)

Possible solution:  Add saltpeter blocks to the nether to lower the imps' reproduction rate. ;)

**Comment by Darkosto** [comment]
I've only ever witnessed this in peaceful. What difficulty are you playing on?

**Comment by Aphenro** [comment]
I am on Normal.  But its just in this one spot for some reason.  I go out further in the nether and it's more normal. I'd mark this as unreproducable and close for now.  If I see it occurring again I'll re-open.

**Comment by Narzil** [comment]
Hi, 

Currently having the same issue on our server, huge spawns of Imp's and it's creating heavy lag. 
![2018-04-17_05 34 51](https://user-images.githubusercontent.com/38449630/38847475-15737d94-4202-11e8-9469-0758e4e575d0.png)

Any suggestion on what to do here? Currently running sevtech 3.0.6 everything is up to date. I don't see any uses for the Imps (yet) in recipes etc, so removing them would not do any harm?
