### ISSUE TITLE
Placing Workstump Mk2

### ISSUE THREAD

**Issue by chiefklondog** [Darkosto/SevTech-Ages#156]
Placing workstump Mk2 without having the requirement (its saying I need the requirement of "I won't get stumped again" however I do not have that on my advancements page atm) to use it makes it disappear. If i put an item back in the spot it use to by in my inventory then it appears again

Additionally, I can't put the workstump mk2 in a chest because it also claims I need that requirement just to place it in the chest. I imagine this will happen with any other place-able items that are blocks by advancements.

**Comment by Darkosto** [comment]
Did you try making it before the MK1 work stump?

**Comment by chiefklondog** [comment]
No, it was made after.

**Comment by Darkosto** [comment]
I fixed this up by removing the skillable requirement. Thank you!
