### ISSUE TITLE
Tough fabric shows wrong recipe

### ISSUE THREAD

**Issue by FlorisXll** [Darkosto/SevTech-Ages#1561]
## Issue / Bug

The current recipe for Tough Fabric (Stage 3) is 
| 9x Industrial Hemp Fibers | 9x Industrial Hemp Fibers | 9x Industrial Hemp Fibers |
| 9x Industrial Hemp Fibers | 1x stick | 9x Industrial Hemp Fibers |
| 9x Industrial Hemp Fibers | 9x Industrial Hemp Fibers | 9x Industrial Hemp Fibers |

## Expected Behavior

Real recipe:
| 1x Industrial Hemp Fibers | 1x Industrial Hemp Fibers | 1x Industrial Hemp Fibers |
| 1x Industrial Hemp Fibers | 1x stick | 9x Industrial Hemp Fibers |
| 1x Industrial Hemp Fibers | 1x Industrial Hemp Fibers | 1x Industrial Hemp Fibers |

## Context

Possibly also holds with normal hemp fibers. Note: same also holds for Insulated LV Wire core!! Maybe more?!

## Client Information

* Modpack Version: 3.0.4
* Java Version: 1.8.0.162
* Launcher Used: Twitch 

* Server/LAN/Single Player: Server
* Resourcepack Enabled?: - 
* Optifine Installed?: -

**Comment by justinrusso** [comment]
Update your pack
