### ISSUE TITLE
Ironwood bark, Stage 0

### ISSUE THREAD

**Issue by Nooska** [Darkosto/SevTech-Ages#1565]
## Issue / Bug
Ironwood bark recipe (crafting log with workblade) seems to be missing.

## Expected Behavior
Expected to craft ironwood log with workblade to get bark, like oak, birch, yew...

## Possible Solution
Implement Ironwood bark recipe

## Steps to Reproduce (for bugs)
1. Place ironwood log with workblade in crafting table or inventory
2. No resulting bark

## Context
In stage 0 trying to make bark, only log available at my spawn that is listed with bark, is Ironwood.
Will have to search for other trees that have a recipe for now.

## Client Information
* Modpack Version: 3.0.5
* Java Version: 161
* Launcher Used: Twitch launcer

**Comment by justinrusso** [comment]
Curious - what mod is the ironwood log from?

**Comment by Targren** [comment]
Can confirm: There are two types of "Ironwood Log"; one from PrimalCore (the one that grows with a 2x2 trunk), which works as expected when carving bark in-world, and one from Rustic, which does not.  Neither makes bark when placing the log and the workblade in the crafting grid.

**Comment by Nooska** [comment]
The ironwood is indeed from Rustic. The bark showing in JEI is PrimalCore (with no recipe on click). The Logs that DO have a recipe are:
Vanilla Logs (Oak, Spruce, Birch, Jungle, Acacia, Dark Oak)
Yew Log (PrimalCore)

**Comment by justinrusso** [comment]
Well, since these are technically two different logs with two different textures, I feel like it would be a little odd if they turned into the same bark that looked different. Will leave this as-is
