### ISSUE TITLE
Making Chocolate dupes Bucket

### ISSUE THREAD

**Issue by rtitan1** [Darkosto/SevTech-Ages#1566]
## Issue / Bug

Making chocolate in the cauldron gives you two buckets. So you can dupe buckets with a bit of milk, cocoa powder and sugar. JEI is showing the correct recipe though.

## Expected Behavior

Obviously chocolate shouldn't dupe buckets.

## Steps to Reproduce (for bugs)

1.
![unbenannt](https://user-images.githubusercontent.com/25640757/38456579-48f166dc-3a86-11e8-8715-cc53cc240f76.PNG)
2.
![unbenannt2](https://user-images.githubusercontent.com/25640757/38456581-4b3d3a60-3a86-11e8-94fe-4975cac71567.PNG)

## Client Information

* Modpack Version: 3.0.5
* Java Version: 1.8.0_161 64bit
* Launcher Used: Twitch

* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by DaedalusGame** [comment]
another one for the no-return recipe
until you update, remove the recipe and readd it without the iron bucket output
