### ISSUE TITLE
Mod version differences between Curse and ATLauncher in 3.0.5

### ISSUE THREAD

**Issue by RTHauke** [Darkosto/SevTech-Ages#1567]
Storage drawers is a different version on ATLauncher and Curse:

ATLauncher - StorageDrawers-1.12.2-5.3.5.jar
Curse             StorageDrawers-1.12.2-5.3.6.jar

Will cause issues with Curse clients trying to connect to servers created with ATLauncher (and vice versa)

**Comment by Darkosto** [comment]
Fixed as of 20 minutes ago. Thank you
