### ISSUE TITLE
Game Crash while starting up from Twitch

### ISSUE THREAD

**Issue by PrototypeBagel** [Darkosto/SevTech-Ages#1568]
**Preface:** I always launch the game through Twitch. I also always remove the Better Foliage mod, as it causes a lot of lag for my computer. This has never cause me any issues in game. I have never had a crashing issue before now while starting up. Besides the crash log, the only extra thing it tells me is that the crash is related to Content Tweaker. 

**Note:** I have also tried using the bundled version of Java (I believe that would be jre1.8.0_25) and my older version of Java (jre1.8.0_40) and am still getting the same crash.

**Pastebin:** https://pastebin.com/wVBgjYK4

**EDIT:** I swapped so that my Minecraft launched with the jar launcher instead, using Java v8 161, and now I do not even get the Forge Mod Loader screen, it just says
"Error: Could not create the Java Virtual Machine. Error: a fatal exception has occurred. The program will now exit."

## Client Information

* Modpack Version: **3.0.5**
* Java Version: **jre1.8.0_161**
* Launcher Used: **Curse/Twitch launch**
* Resourcepack Enabled?: **Yes, Faithful 32**
* Optifine Installed?: **No**

**Comment by justinrusso** [comment]
Try re-installing the pack

**Comment by PrototypeBagel** [comment]
Just did, getting the same error message as in the edit

**Comment by PrototypeBagel** [comment]
Final Edit: Re-installing for a second time seems to have fixed the issue for some unknown issue. This can be closed!

**Comment by MJRLegends** [comment]
@PrototypeBagel I believe you can close it yourself should be at the bottom below my comment
