### ISSUE TITLE
v3.0.5 No Darklands biomes

### ISSUE THREAD

**Issue by Aalandriel** [Darkosto/SevTech-Ages#1569]
## Issue / Bug

Unable to find a single Darklands biome in new worlds. Individual biomes also feel like they've grown in size, but that could just be me.

## Expected Behavior

In v3.0.4 I would be able to find a darklands biome with minimal travelling. I don't mind them being rare but it feels like they are not generating at all.
## Steps to Reproduce (for bugs)

1. Launch Sevtech v 3.0.5
2. Start new world with either default or sevtech_v2 preset
3. Run/fly around the generated world and look for biomes

## Context

I presume that progressing through Age 0 will be impossible without a darklands biome from where to get the gem for the hopper advancement line.
## Client Information

* Modpack Version: 3.0.5
* Java Version: 1.8.161
* Launcher Used: Curse > Jar Launcher

**Comment by Darkosto** [comment]
They do generate, in fact they generate in cold climates. I've confirmed this through many worlds.

![image](https://user-images.githubusercontent.com/10309699/38457101-15395934-3a5a-11e8-9e03-3d3d743c856d.png)


Biomes are not larger, since each temprature band has less biomes in it you will notice some of the same biomes more often. Just travel North or South to see the rest of the biomes.

**Comment by Darkosto** [comment]
To add to this, they are easier to find since their temperature band contains less biomes than previous updates.

**Comment by Aalandriel** [comment]
Right RNG gods must be dislinking me. Now at least I know where to look

**Comment by Darkosto** [comment]
Keep in mind, the advancement text actually gives you this info:

![image](https://user-images.githubusercontent.com/10309699/38457263-f2fc14ea-3a5b-11e8-9c9e-a50fb90e6cc1.png)

**Comment by zapl** [comment]
This is just frustrating. Please don't put that kind of worldgen in any map ever again.

How can I turn off stage restrictions for a while so I can pack up in creative mode and move or NBT edit / chunk delete myself into a sane world? Not going to travel 1000s of blocks.
