### ISSUE TITLE
Tiny Husk/Zombie Drops Iron Sword

### ISSUE THREAD

**Issue by chiefklondog** [Darkosto/SevTech-Ages#157]
Got an iron sword from a drop after killing a tiny Husk/Zombie (Not sure which). Do they have different loot tables? (Stage 0)

Pack Version 6

**Comment by Crackerhead22** [comment]
If I recall there was currently nothing that can be done about that,

**Comment by Darkosto** [comment]
Actually, Buuz135 just made a mod that might let me fix this now. I'll see what I can do.
