### ISSUE TITLE
3.0.5 mushroom pie uncraftable

### ISSUE THREAD

**Issue by jwmwebdev** [Darkosto/SevTech-Ages#1570]
## Issue / Bug
Mushroom Pie (from Better with Addons) can be crafted in stage 1 (or stage 0, not sure), but requires some sort of pie from stage 2 before it can be cooked. 
Both red and brown mushroom are affected.

## Expected Behavior
Red and Brown Mushroom Pie to be cooked in a kiln

## Possible Solution
Stage either the mushroom pie, or it's ingredients to be in the same stage

## Steps to Reproduce (for bugs)
1. Look up Mushroom Pie in JEI
2. Check Recipe
3. Look for the Kiln recipe
4. Check staging on both sides of recipe
5. ???
6. FOOD!!!

## Context
I was checking food that gave Vegetable nutrition and noticed that it is bugged

## Client Information
* Modpack Version:    3.0.5
* Java Version: 1.8.0_161_64bit
* Launcher Used: Twitch
* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: Faithful and Modded Faithful
* Optifine Installed?: NO

**Comment by artdude543** [comment]
This is resolved in 3.0.7
