### ISSUE TITLE
[Structure Gen Error] Iron ore spawns in rubble clumps above ground. 3.0.5

### ISSUE THREAD

**Issue by CannibalKon** [Darkosto/SevTech-Ages#1573]
Just running a basic server, all I have to say is in the picture below. I updated to 3.0.5 and I found iron ore when generating new chunks on a 3.0.3+ world.

I don't really think there's anything else to say.
![2018-04-07_13 35 54](https://user-images.githubusercontent.com/35207251/38458185-401f421c-3a69-11e8-9153-8b9df580496f.png)

**Comment by CannibalKon** [comment]
I'm in Age 2, if that is important.

**Comment by darkphan** [comment]
Did you copy the structures folder on the server? I do not believe those structures should spawn if you did.

**Comment by justinrusso** [comment]
See `Update.txt` - it shows what files you should be copying over.

**Comment by Matryoshika** [comment]
@justinrusso Experiencing the same issue, and yes, I did copy the structure folder to the server.
I looked into it and the [3.0.5 server file on curse](https://minecraft.curseforge.com/projects/sevtech-ages/files/2549311) contains empty "active", "inactive" & "schematics" folders.
For now I've copied over the structures-folder from the client to the server.

**Comment by justinrusso** [comment]
Indeed. Thanks for finding this @Matryoshika . We've uploaded new server files for 3.0.6.
