### ISSUE TITLE
Stage 3 Enchanting Table recipe

### ISSUE THREAD

**Issue by MechaDom** [Darkosto/SevTech-Ages#1574]
* Modpack Version:3.0.5
* Java Version: 
* Launcher Used: Twitch App Native

In age 3 the enchanting table recipe shows the vanilla recipe even though diamonds are age 5.  It still shows the normal Age 3 recipe which works fine.

https://i.imgur.com/1EW6aec.jpg?1

**Comment by artdude543** [comment]
This is fixed in 3.0.7
