### ISSUE TITLE
Can't seem to make steam/distilled water.

### ISSUE THREAD

**Issue by MyApolloGees** [Darkosto/SevTech-Ages#1577]
## Issue / Bug
Okay so i have a boiler, i have placed water and diesel into it nothing happens. 
![image](https://user-images.githubusercontent.com/37778378/38458383-b532851a-3a95-11e8-830f-6af5d4d4d75d.png)

realized it could be distilled water but i can't seem to make distilled water. i made the distiller (this says you add water and it creates distilled water)  yet i can't seem to add water into it ive tried piping water into the inlet given too.

![image](https://user-images.githubusercontent.com/37778378/38458451-6f337276-3a96-11e8-8adb-7aa124b87bf2.png)

## Context
cannot progress!!!

## Client Information
* Modpack Version:3.0.5
* Java Version: unsure (latest)
* Launcher Used: twitch
* Server/LAN/Single Player: SP
* Resourcepack Enabled?: Unity
* Optifine Installed?: Yes

**Comment by Stormfirebird** [comment]
I believe the liquids are in the wrong slot in the boiler, for why that is possible I dont know, made the same mistake the first time around though :)

**Comment by MyApolloGees** [comment]
i noticed that seems like a mod fix not a pack fix

**Comment by Ambaire** [comment]
Diesel goes in the far left slot, water goes in the middle slot. The machine does not seem to have any white/blacklists preventing the wrong fluids in the wrong slots, as I discovered yesterday.

**Comment by sherkas** [comment]
What was said above. There is no liquid restrictions so they are commonly placed in the wrong spots.

Diesel then water.

**Comment by artdude543** [comment]
- Boiler: Diesel (Left), Water (Right)
- Distil: You need to pipe water into it for the time being. Until the mod dev fixes the GUI's.
