### ISSUE TITLE
Bear Claw Missing Texture

### ISSUE THREAD

**Issue by Jctn1** [Darkosto/SevTech-Ages#1578]
## Issue / Bug

Bear Claws are invisible/have no texture

## Steps to Reproduce (for bugs)

1.
2.

## Client Information

* Modpack Version: 3.0.5
* Java Version: 1.8.0_25
* Launcher Used: twitch

* Server/LAN/Single Player: single
* Resourcepack Enabled?: no
* Optifine Installed?: no

**Comment by SummitSummit** [comment]
I wasn't going to say anything because I installed a resource pack when I updated to 3.0.5 but my Bearclaws are invisible too.  Charcoal Pieces are also invisible.

**Comment by Mrbysco** [comment]
Doesn't the default issue info tell you to search for the issue before making it? the issue has already been posted 6 hours ago #1554

**Comment by Darkosto** [comment]
Duplicate post. Please check before posting an issue.
