### ISSUE TITLE
Storage Drawers Version Results In Inability to Connect to Server

### ISSUE THREAD

**Issue by Arisonius** [Darkosto/SevTech-Ages#1579]
## Issue / Bug
Server rejecting client due to storage drawers update.

## Expected Behavior
client and server have same versions of the mod and client is allowed to connect to server

## Possible Solution
update server pack to the correct version of storage drawers or downgrade the client to match the servers version of storage drawers

## Steps to Reproduce (for bugs)
1. Install sevtech 3.0.5 on server
2. Install sevtech 3.0.5 on client
3. attempt to connect to server
4. see related pics

![client side](https://user-images.githubusercontent.com/25127175/38458687-8e08ebb6-3a66-11e8-8e01-750911c55a1b.PNG)
![server error](https://user-images.githubusercontent.com/25127175/38458690-97bc8b40-3a66-11e8-9fe9-72ed6dcfe700.PNG)
![server side](https://user-images.githubusercontent.com/25127175/38458691-9a1d5f54-3a66-11e8-92b3-e11788fdcf94.PNG)

## Client Information

* Modpack Version: 3.0.5
* Java Version: 8
* Launcher Used: Twitch

* Server/LAN/Single Player: Server
* Resourcepack Enabled?: No
* Optifine Installed?: No

## Server Information
* Java Version: 8
* Operating System: Windows 
* Hoster/Hosting Soultion: mcprohosting
* Sponge (Non-Vanilla Forge) Server?: No, Forge.

* Additional Content Installed?: No

**Comment by Arisonius** [comment]
This is possibly an issue with the host not having the correct mods installed to the server, I resolved the issue by installing the updated mod to the server side.

**Comment by Darkosto** [comment]
This was fixed about 6 hours ago. Please update to fix.
