### ISSUE TITLE
Crash when trying to create clay bucket on turntable

### ISSUE THREAD

**Issue by PokerusBreeder** [Darkosto/SevTech-Ages#1580]
No additional mods installed. Running most recent version of the pack at this time (3.0.5). World was created during 3.0.3 but has been updated to most recent version. 

## Issue / Bug
When crafting a clay bucket on the turntable, game crashes prior to completion. When logging back in, game crashed before world loads and am unable to log back in successfully. 

Pastebin with both crash reports:
https://pastebin.com/9iS5GRfw

## Expected Behavior
Finishes clay bucket crafting. Instead, game crashes prior to finishing crafting the clay bucket

## Steps to Reproduce (for bugs)
1. Turntable connected to shaft connected to gearbox connected to shaft connected to gearbox connected to watermill. 
2. Clay block is placed on already moving turntable. 
3. While table is turning, adjust which settings the turntable is using to craft.
4. Prior to completion, pack crashes and creates above listed crash log.
5. Unable to log into game to finish crafting bucket

## Context
I was trying to create the clay bucket in order to then create the cast. Without the clay bucket, I am unable to progress through the pack

## Client Information
I am in, what I assume to be, a river biome. I set up a base out on the river for the infinite water resources. 
* Modpack Version: 3.0.5
* Java Version: Java 8 Update 161
* Launcher Used: Twitch App
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by Mrbysco** [comment]
Try 3.0.6 that got released 1 hour ago. It "Fixed a Better With Mods Turntable crash"

**Comment by Darkosto** [comment]
Already fixed in 3.0.6, please update your instance.
