### ISSUE TITLE
Squids are not spawning for me.

### ISSUE THREAD

**Issue by KingCodyBear** [Darkosto/SevTech-Ages#1581]
## Steps to Reproduce (for bugs)

1.
2.

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:

* Server/LAN/Single Player:
* Resourcepack Enabled?:
* Optifine Installed?:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Soultion:
* Sponge (Non-Vanilla Forge) Server?:

* Additional Content Installed?:

**Comment by Mrbysco** [comment]
Did you forget to fill in the info?
