### ISSUE TITLE
Quick death on exiting hunting dimension

### ISSUE THREAD

**Issue by dawk42** [Darkosto/SevTech-Ages#1582]
## Issue / Bug
When exiting the hunting dimension player is spawned below ground ending in a quick death. 

Also when testing on the super flat world entering the hunting dimension has the same effect

## Expected Behavior
Player should spawn above ground unless this is an intended feature.

## Thoughts
As with the nether portal, portal Y-level is key in the superflat  world portals at Y=4   suffocated players when entering hunting dimension,  portals created at y=60 seemed to work on entering.

in my actual play world the portal is at y=72 and i get suffocated coming back to the overworld

## Steps to Reproduce (for bugs)
1. enter hunting dimension
2. exit hunting dimension 

## Client Information

* Modpack Version:  3.0.4
* Java Version: Twitch built in..  8.0.25.18
* Launcher Used:  2.0.1003

* Server/LAN/Single Player: 
* Resourcepack Enabled?:
* Optifine Installed?:

**Comment by Darkosto** [comment]
This issue was already fixed in 3.0.5. Please update you instance.
