### ISSUE TITLE
Some GalacticCraft Ores Smelt into Unusable Ingots / misc GalacticCraft processing

### ISSUE THREAD

**Issue by Vyraal1** [Darkosto/SevTech-Ages#1583]
## Issue / Bug
- every single day this template seems to keep growing lol
- so the following ores in GalacticCraft smelt into ingots that currently do nothing:
**Mars** - Copper, Tin
**Venus** - Aluminium, Copper, Galena (smelts directly into unusuable Lead, Tin

- this list is not comprehensive, but this is only what I really found so far, I'm guessing you can look up the extra Planets ores as well and see if they have any processing issues as well

- these ores smelt into the GalacticCraft variants of various ingots that aren't ore dictd to ingotCopper, ingotTin, etc. making them pretty much useless:
![image](https://user-images.githubusercontent.com/26587049/38459840-200285c0-3a7d-11e8-9064-c99bbedb4859.png)

- as a solution, you can have them just smelt directly into the Immersive Engineering Copper Ingot, Mekanism Tin Ingot, etc.

## Client Information
* Modpack Version: 3.0.6

**Comment by justinrusso** [comment]
Oh... https://github.com/micdoodle8/Galacticraft/blob/b6fec74c13a8094a430c10fc0d7ae4dd66eb8243/src/main/java/micdoodle8/mods/galacticraft/core/GalacticraftCore.java#L376

**Comment by justinrusso** [comment]
Ok.. so everything is in postInit, which makes it odd how most of removals work. Im assuming something is moving GC in front of Crafttweaker, but the GC planets mod is loaded later as its just an additional addon.

Either way, registering recipes in postInit is odd.

**Comment by artdude543** [comment]
This is resolved in 3.0.7
