### ISSUE TITLE
Using valonite shield charge on either some enemies or another player causes crash

### ISSUE THREAD

**Issue by Skullywag** [Darkosto/SevTech-Ages#1584]
## Issue / Bug
Not sure if certain mobs cause it but deffo can reproduce by having 2 players charge into each other using valonite (possibly other betweenlands shields). Have had it happen multiple times now on my server, the latest was fighting the armour ghosts boss in the twilight forest goblin stronghold. It crashes out the whole client, server sometimes stays up ok, sometimes error spams the console where not even a stop command will work and you have to forcibly kill it.

## Expected Behavior
For it not to crash.

## Possible Solution
couldnt find any mention of it on the mod pages or betweenlands.

## Steps to Reproduce (for bugs)
1. Have 2 players
2. Both have Valonite shields
3. Charge attack into each other
4. It should crash.

## Client Information
* Modpack Version: 3.0.4
* Java Version: 8
* Launcher Used: ATLauncher
* Server/LAN/Single Player: Multiplayer
* Resourcepack Enabled?: nope
* Optifine Installed?: nope

## Server Information
* Java Version: 8
* Operating System: Windows
* Hoster/Hosting Soultion: Own server
* Sponge (Non-Vanilla Forge) Server?: nope

**Comment by justinrusso** [comment]
Can you provide crash logs?

**Comment by djnifos** [comment]
I just crashed with the shield.  I was underwater, SSP.

https://pastebin.com/S9v3AQAX

**Comment by Skullywag** [comment]
I didnt get the logs, ill grab em next time it occurs just incase its different from the above crash.

**Comment by TheCyberBrick** [comment]
New update is out that fixes djnifos' crash. Not sure if it's the same as Skullywag's crash though

**Comment by TheCyberBrick** [comment]
The other crash should now also be fixed in dev. I'll probably make a build later today

**Comment by TheCyberBrick** [comment]
3.3.8 is now on curse

**Comment by artdude543** [comment]
Will be included in 3.0.7 of the pack 😄
