### ISSUE TITLE
sunflower textures bugged

### ISSUE THREAD

**Issue by poMONKey** [Darkosto/SevTech-Ages#1585]
## Steps to Reproduce (for bugs)

1.
2.

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:

* Server/LAN/Single Player:
* Resourcepack Enabled?:
* Optifine Installed?:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Soultion:
* Sponge (Non-Vanilla Forge) Server?:

* Additional Content Installed?:

**Comment by Darkosto** [comment]
"sunflower textures bugged"

Please properly report bugs instead of giving a vague piece of information in the title. Share an image or something else. This is being closed. report properly next time.

**Comment by poMONKey** [comment]
sorry man ... hit the publish button by accident
