### ISSUE TITLE
Sunflower textures bugged

### ISSUE THREAD

**Issue by poMONKey** [Darkosto/SevTech-Ages#1586]
## Issue / Bug

Sunflower tops appear on other flowers

https://imgur.com/a/oBJ3M

## Expected Behavior
Dont get the sunflower when breaking plant

## Client Information

* Modpack Version: 3.0.5
* Java Version: 8
* Launcher Used: Twitch

* Server/LAN/Single Player: SP
* Resourcepack Enabled?: YES (SOARTEX MODDED)
* Optifine Installed?:  YES

**Comment by poMONKey** [comment]
sorry to post again Dark ... I hit the publish button, before filling in the details, by accident last time.

Thanks for this awesome pack btw :)

**Comment by justinrusso** [comment]
Have you tried without textures? After changing textures, did you try reloading the game?

**Comment by poMONKey** [comment]
@justinrusso ... Thanks for the reply. I did try removing textures, and reloaded the game, didnt  seem to make a diff. They all seem to spawn that way, sunflower on top, some other plant below. When I break the sunflower block, I get nothing. When I break the plant below, I get that plant. Havent found a "regular" sunflower plant yet. Wouldnt care, if I didnt need it for the Totemic Staff ... cheatmode activated :)

**Comment by artdude543** [comment]
Closing this as it's an odd issue with generation but it's not game breaking but a fun thing to laugh at when you see them 😉
