### ISSUE TITLE
Ctrl-Click on item while in Advanced Primal Chest gives player items

### ISSUE THREAD

**Issue by TIGwelder-42** [Darkosto/SevTech-Ages#1588]
## Issue / Bug
Ctrl clicking items in player inventory while you have an Advanced Primal Chest open dupes items by giving player items like they are not in survival mode.

Given [Item] * X to Player

## Steps to Reproduce (for bugs)
1) Open Advanced Primal Chest
2) Choose Item in player inventory
3) Hold CRTL and click item
4) First click will fill stack to 64, next click will give another stack of 64

Seems to work with any items while in tutorial

## Client Information
* Modpack Version: 3.0.4
* Java Version:Ber 8 Update 171  -- 1.8.0_161.b-12
* Launcher Used: Twitch -Minecraft launcher- jar version

* Server/LAN/Single Player: Single player SURVIVAL mode
* Resourcepack Enabled?: no
* Optifine Installed?: no

**Comment by sarcastic6** [comment]
Just as another reference point; I'm on 3.0.5.

On a server, I can duplicate this is a player is opped and cannot duplicate this is the player is not opped.

In single player, I cannot duplicate this regardless of whether cheats are turned on or off.

**Comment by TIGwelder-42** [comment]
Checked my save in NBTExplorer:
Under “Level.dat”

Allowcomamnds 0 (false)
Difficulty 2 (normal)
Game Type 0 (survival)

Yet it seems cheats work and I can also do this in regular chests.  What am I missing?

**Comment by 3jlowes** [comment]
Are you in NEI / JEI cheat mode?

**Comment by 3jlowes** [comment]
Try disabling NEI cheat mode (not jei)

**Comment by TIGwelder-42** [comment]
RESOLVED


NEI was in cheat mode. Now disabled in options.
Buttons and giving items now disabled.

NEI config had lockmode set to -1

Changed config to:
Lockmode=0   
#Recipe, no spawning

Now shows in config
Cheatmode=0

**Comment by squarism** [comment]
I had the same issue as TIGwelder (thank you for the solution!).  So the config that comes with SevTech sets it to -1.  Is this a bug?  Wouldn't it be best to just set this to 0 in the config that ships with SevTech?
