### ISSUE TITLE
TC controller advancement

### ISSUE THREAD

**Issue by Dawenzel** [Darkosto/SevTech-Ages#159]
## Issue
The "Controlling"(controller.txt) advancement in stage 2 asks to place a `<tconstruct:smeltery_controller>` with metadata 0. When the controller is in your inventory it has metadata 0, but when placed the metadata ranges from 2 to 5(changes with direction placed). So currently it is impossible to complete this advancement as you can't place the controller with it retaining metadata 0.

## Possible solution
Removing the metadata from the block should make it so that whatever direction it is placed it still triggers the advancement.

## Versions
- Minecraft 1.12.1
- Forge 14.23.0.2512
- Java x64 8u144
- Sevtech-Ages Alpha 6

**Comment by Darkosto** [comment]
Should be good now! Thanks!
