### ISSUE TITLE
[bug] pressing volume down while galacticraft map key is unbound will open unquitable map

### ISSUE THREAD

**Issue by troye888** [Darkosto/SevTech-Ages#1593]
## Issue / Bug
When I press volume down while the galacticraft map button is unbound (normally M) then it opens a "working" space map without the exit button. So you are basically stuck in said map without any way of quiting it, forcing you to quit the game.

## Expected Behavior
It should only decrease the volume(which it still does)

## Possible Solution
this only happens when the map button is unbound. So an easy fix is just to bind the map key to anything.

## Context
I just started thsi modpack andentered age 0, after a restart everything is still all right so it isn't that big of a deal

## logs
https://pastebin.com/FKa189Jp

##client information
modpack Version 3.0.6 no extra mods
java version 8
using twitch launcher

I looked at the logs but they don't seem to have any information about this at all.

**Comment by justinrusso** [comment]
https://github.com/micdoodle8/Galacticraft/issues/3389

**Comment by EhGneissGuy** [comment]
Encountered this yesterday - had to kick myself through the server console. Was extremely confused what happened.

**Comment by justinrusso** [comment]
https://github.com/Darkosto/SevTech-Ages/issues/2204
