### ISSUE TITLE
v3.05 Hunters Dimension (happened only once, could not reproduce )

### ISSUE THREAD

**Issue by ReveralX** [Darkosto/SevTech-Ages#1595]
## First entry to Hunters Dimension - generating hunters dimension world for the first time
While I trieingended to enter portal for the **first time**, in full armor (wolf armor), it took around half a minute to enter transfer-loading screen (while sneekinenging) . After "loading screen" it just dropped me out in overworld. Which in turn resulted in all pieces of equipped armor to vanish. 

## Second entry to Hunters Dimension
Reentering hunters dimension again, results in normal transfer to hunter dimension, and returning back from that dimension, returns the equipped armor to where it suppose to be.  

After first entry, havent been able to reproduce.

System: Super Nintendo
OptiNotFine: installed
World type: Single Player

**Comment by artdude543** [comment]
This sounds like a rare case/derp when the world was loading. Nothing on the pack side that can help with this.
