### ISSUE TITLE
Scannable not showing some ores

### ISSUE THREAD

**Issue by steinjorn** [Darkosto/SevTech-Ages#1596]
The scanner from scannable is not picking up galacticraft silicon nor will it pick up geolosys beryl. not sure if intended or not but reporting.
![2018-04-07_22 05 02](https://user-images.githubusercontent.com/27919048/38462150-bcf67792-3aaf-11e8-8c73-783f1d104be2.png)

* Modpack Version:3.0.5
* Java Version:1.8
* Launcher Used:twitch

**Comment by justinrusso** [comment]
If you have any information as to what ores need to be added, please comment on the  issue here: https://github.com/Darkosto/SevTech-Ages/issues/908
