### ISSUE TITLE
tinker's constuct, pig iron-stage unlock

### ISSUE THREAD

**Issue by csg1995** [Darkosto/SevTech-Ages#1598]
## Issue / Bug
pig iron can be made in stage 2 in the tinkers smeltery with iron+blood+clay, dispite this it is marked as an unkown item

## Possible Solution
if pig iron is intended to be obtained it should be marked as unlocked in stage 2, if not the recipie should be locked/removed

## Steps to Reproduce (for bugs)
add iron, blood and clay to smeltery in stage 2, watch them alloy, cast into tool part, be disappointed you can't use it

## Context
tried to upgrade sword blade from bronze to pig iron for more damage

## Client Information
sevtech 3.5

**Comment by artdude543** [comment]
We can't stage alloying as it's a limitation of how we can stage things. But you can't create use the tool parts until you unlock it
