### ISSUE TITLE
Cannot Trigger the Saturn Advancement

### ISSUE THREAD

**Issue by Vyraal1** [Darkosto/SevTech-Ages#1599]
## Issue / Bug
- Made a tier 5 rocket, flew to Saturn, landed, did not get the achievement
![image](https://user-images.githubusercontent.com/26587049/38463077-76d69ad4-3abf-11e8-875e-2a10177b4376.png)

- https://streamable.com/osad4
- Apologize as my computer froze for a bit right after tp'ing into Saturn with the rocket.

## Expected Behavior
- Unlocks the achievement

## Possible Solution
- This is the first time we're traveling to an Extra Planets dimension for the advancement? Maybe it does teleportation differently than other mods?
- Maybe the dimension has a different id other than "Saturn"? Even using an RfTools Advanced Charged Porter to teleport back to the planet has no success of triggering the advancement
- Would it be reasonable to unlock the achievement creatively once getting to Saturn to temporarily progress?

## Context
- Can't progress further with advancements

## Client Information
* Modpack Version: 3.0.6
* Launcher Used: Twitch
* Optifine: Yes

**Comment by Vyraal1** [comment]
Whoops should've clarified this was multiplayer.

**Comment by Vyraal1** [comment]
Another update, this was also broken for Neptune as well.

**Comment by justinrusso** [comment]
This is still not working. What we believed was a fix was actually the advancement triggering for ANY dimension the player traveled to, not the specific one.

Extra Planets is currently looking into this.

**Comment by justinrusso** [comment]
Altered the advancement so now the player has to mine a the surface to get the advancement.
