### ISSUE TITLE
[Suggestion] Oredict Roots Bark

### ISSUE THREAD

**Issue by davqvist** [Darkosto/SevTech-Ages#16]
There exist 3 different versions of bark. Not sure how to get the Better with Mods Bark, but it's already oredict with the bark you get from the blade. Not sure if it would be balanced, that is for you to decide, but it's strange that those 2 barks are oredict but not the Roots bark.

**Comment by Darkosto** [comment]
Added back the OreDict tags to these barks. Thank you!
