### ISSUE TITLE
Just a Charcoal Block...

### ISSUE THREAD

**Issue by Serolar** [Darkosto/SevTech-Ages#160]
[Recipe Issue]
The Charcoal Block from [A Block of Charcoal] can be made with 9 charcoal.
That Charcoal Block cannot be turned back into charcoal. 
Could it turn back into 9 Charcoal?

SevTech Test Pack Version 6

Thank you for your time,
Serolar

**Comment by Darkosto** [comment]
I worked this into the pack, should be good!
