### ISSUE TITLE
Liquid shards in Distillation tower

### ISSUE THREAD

**Issue by danielskipper** [Darkosto/SevTech-Ages#1602]
## Issue / Bug
Putting a liquid shard such as a Fragile Oil Shard inside of the distillation tower will fill the entire internal buffer of liquid instead of the 500 mb the shard is said to contain
## Expected Behavior
The shard fill only 500 mb of a buffer, instead of up to 24000 mb
## Possible Solution
Attempt to make the shard fill the value of the shard
## Steps to Reproduce (for bugs)

1. Get a Fragile Oil Shard from breaking a buildcraft factory mod tank with at least 1 bucket of liquid in it.
2. Place the Oil Shard into the distillation tower from immersive engineering

## Context
It accidentally gave me an additional 24 buckets of oil in early age 3.

## Client Information

* Modpack Version: 3.0.6
* Java Version: 8.0
* Launcher Used: Twitch Launcher

* Server/LAN/Single Player: LAN
* Resourcepack Enabled?: Default
* Optifine Installed?: No

## Server Information
* Java Version: 8.0
* Operating System: windows 10
* Hoster/Hosting Soultion:
* Sponge (Non-Vanilla Forge) Server?:

* Additional Content Installed?: no

**Comment by SuohKami** [comment]
I happened to do this, but at 100mb left on the shard it didn't consume it and instead is giving me infinite oil without the pump needing to run.

**Comment by MrHrulgin** [comment]
The same issue occurs using other fluid shards in other Immersive Engineering devices. It works identically using diesel in the distillation tower, and similarly using water in the solar tower, though there it requires a 40mb shard to obtain infinite water. Presumably it will also work similarly in the Refinery with liquid oxygen and kerosene.

**Comment by AlexIIL** [comment]
Does this happen with any other non Buildcraft container (perhaps only others which can be partially consumed)? Also, does this happen with any other machines from mods other than immersive engineering?

**Comment by justinrusso** [comment]
@AlexIIL You seem to always be around here on issues regarding Buildcraft, greatly appreciate it! This seems to be specific to IE/addon ones currently. I've tested this with another block (PneumaticCraft Liquid Hopper) and it gave 500 mb.

**Comment by justinrusso** [comment]
This appears to be a bug with Immersive Petroleum specifically. Ive tested the Immersive Engineering tank as well as PneumaticCraft's liquid hopper and both handle it fine.

**Comment by justinrusso** [comment]
Will disable the shards, and revisit it potentially when the issue is fixed.
