### ISSUE TITLE
Sevtech Server

### ISSUE THREAD

**Issue by Occuvite** [Darkosto/SevTech-Ages#1607]
[Server thread/ERROR] [FML]: The mod elevatorid appears to have an invalid event annotation EventHandler. This annotation can only apply to methods with recognized event arguments - it will not be called
 [Server thread/WARN] [teslacorelib]: Annotated class 'net.ndrei.teslacorelib.blocks.multipart.MultiPartBlockEvents' not found!

I have problems with Minecraft Sevtech Server, when i open forge-1.12.2-14.23.2.2654-universal.jar

**Comment by sarcastic6** [comment]
That little snippet isn't helpful.  You'll need to provide the entire log as well as:

* Modpack Version:
* Java Version:
* Operating System:
* Hoster/Hosting Soultion:
* Sponge (Non-Vanilla Forge) Server?:
* Additional Content Installed?:

**Comment by justinrusso** [comment]
The current forge distributed with the pack is 1.12.2-14.23.2.2651.
