### ISSUE TITLE
[3.0.6] No recipe for Marble Slab (Astral Sorcery)

### ISSUE THREAD

**Issue by Targren** [Darkosto/SevTech-Ages#1608]
JEI says that AS marble slabs are stage one, but don't have a recipe for it. Contrast with AS Marble stairs which have a LCT recipe. 

Added all stages up to stage five with /gamestage, so it doesn't seem that the recipe is gated off. 

## Possible Solution

Add a recipe for marble slabs 

## Client Information
* Modpack Version: 3.0.6
* Java Version: 1.8.0_161
* Launcher Used: MultiMC 5 0.6.1

**Comment by Vyraal1** [comment]
As far as I know these were only added as creative-only for Astral Sorcery, they break immediately, have no hardness/harvest, etc. For what it's worth Astral Dev did not intend for these to be obtainable yet until AS 1.9

**Comment by SephirothWS** [comment]
In stage 1 you can make the Chisels & Bits Stone Chisel with a stick and a Stone Ingot. You can use Chisels and Bits to "emulate" marble slabs.

![Image](https://i.imgur.com/TtTLuoQ.png)

**Comment by Targren** [comment]
@SephirothWS  Maybe I'll try that. I don't know how to use C&B to do anything other than make a bloody great mess with nanoblocks all over the place. :)
