### ISSUE TITLE
Rocks dropping hidden items...

### ISSUE THREAD

**Issue by LRCK** [Darkosto/SevTech-Ages#1609]
Not sure if this is a bug, but when I break certain rocks (not ore samples) sometimes I get a hidden ore... I just got an ore sample from a rock that isn't unlocked until stage 5... is this a bug or an unavoidable feature of the hiding process and I just got really lucky?

Thanks!

**Comment by artdude543** [comment]
This is an unavoidable feature of how we hide things and how other mods interact with it. There is only so much we can do w/o the need for mods changing things which won't happen 🙂
