### ISSUE TITLE
Starlight advancement syntax

### ISSUE THREAD

**Issue by Dawenzel** [Darkosto/SevTech-Ages#161]
## Issue
The syntax for the "Starlight Geolocation"(skywave.txt) advancement in stage 2 is incorrect as the item still has <> around it. This makes it complete this advancement on acquiring the parent.

## Possible solution
Removing the <> should fix this.

## Versions
- Minecraft 1.12.1
- Forge 14.23.0.2512
- Java x64 8u144
- Sevtech-Ages Alpha 6

**Comment by Darkosto** [comment]
Yep! Actually fixed this up a few days ago off stream. Thanks for the report :)
