### ISSUE TITLE
3.0.5 server files

### ISSUE THREAD

**Issue by tjd46** [Darkosto/SevTech-Ages#1613]
## Issue / Bug
sever file mismatch on version 3.0.5 https://i.imgur.com/HLAYghM.png
server jar is 1.12.2-14.23.2.2654
yet client is 1.12.2-14.23.2.2651

## Possible Solution
swap out for correct version

## Steps to Reproduce (for bugs)

1.Download server folder from [curseforge](https://minecraft.curseforge.com/projects/sevtech-ages/files/2549302#additional-files)
2.open folder check ver

## Context
minor issue as its now a outdated pack version just pointing it out

**Comment by artdude543** [comment]
.5 did use another version of forge but it was dropped in .6 this will be fixed when an update server pack is uploaded.
