### ISSUE TITLE
[3.0.6] Rotten Food added as monster drop has unusual localized tooltip text

### ISSUE THREAD

**Issue by MongoTheElder** [Darkosto/SevTech-Ages#1622]
## Issue / Bug
The tooltip for rotten food in The Betweenlands that was added to monster drops shows a format string "(%s)" instead of the source food (since this has no source but is rotten food by default)
![2018-04-08_13 23 56](https://user-images.githubusercontent.com/29290246/38470395-1cd25520-3b30-11e8-9e46-4738dc46f8d0.png)

## Expected Behavior
The tool tip would normally show what food was changed to rotten food. Since rotten food was added to monster drops and not a transformed food from outside the Betweenlands, the tool tip has no food type to display in the tool tip and shows the format string instead.

## Client Information

* Modpack Version: 3.0.6
* Java Version: 1.8.0_25
* Launcher Used: Vanilla (Twitch App build)

* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?:None
* Optifine Installed?:No

**Comment by TheCyberBrick** [comment]
https://github.com/Angry-Pixel/The-Betweenlands/commit/6ff1d88853ecc4f8a9d9390010d0d093a0b7c3b4

**Comment by TheCyberBrick** [comment]
New update is out

**Comment by vadis365** [comment]
Closing - another brick victory.
