### ISSUE TITLE
[3.0.6] Quark hotbar swap still lets you put Carry On entities in your inventory

### ISSUE THREAD

**Issue by Marioluigi7896** [Darkosto/SevTech-Ages#1623]
## Issue / Bug

Pushing "Z"(default) shifts your hotbar and causes the same issue that the cyclic buttons caused.
## Expected Behavior

You shouldn't be able to do that
## Possible Solution

Disable the quark hotbar swap if possible
## Steps to Reproduce (for bugs)

1. pick up entity
2. push z then a number 1-3
3. see the entity in your inventory

## Context

Noticed that the cyclic one was turned off according to the change logs and thought to check the quark swap. And sure enough it does the same thing.
## Client Information

* Modpack Version: 3.0.6
* Java Version: 1.8.0_161
* Launcher Used: MultiMC

* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: Soartex
* Optifine Installed?: No

**Comment by justinrusso** [comment]
-________________-

Thanks.
