### ISSUE TITLE
FPS problems 

### ISSUE THREAD

**Issue by 92slavik** [Darkosto/SevTech-Ages#1624]
After play for several minutes, my FPS drops to 0 whenever i open my inventory.. after closing my inventory, my FPS goes back to normal 100+

**Comment by LycanBlackpaw** [comment]
I've heard this is an issue with Smooth Font redrawing JEI, removing the mod usually solves the issue

**Comment by Joewiibox** [comment]
I had the same problem, all I had to do was open my inventory, go to options in the bottom left, then inventory and click on the NEI enabled to change it to NEI disabled and it fixed it for me

**Comment by PetrAnonym** [comment]
For me upgrading to the right Java (the one ending in 161) fixed this problem.

**Comment by 92slavik** [comment]
Disabling NEI helped me, thanks :)
