### ISSUE TITLE
Beneath portal causing backpacks not to be available. 3.06

### ISSUE THREAD

**Issue by Scodigy** [Darkosto/SevTech-Ages#1628]
Placed the beneath portal. Shift clicked into it and I am surrounded by stone in every direction entombed with only a 9 by 9 for room. Right click to open anything no longer functions except doors. Doors open and close but I  cannot pass thru the door. Backpacks go to a naming menu, I name the backpack, click the done button, try again, same, it goes to naming gui. 

Cannot access porcelain smelter to insert or check inventory after entering the beneath.
I've replicated this on 2 installs. 
Once I exit out and go back into the game it's fine until I once again visit the beneath and then it's the same from then on. The last time I tried it allowed me to access my backpack when I first got to the beneath but once I mined a cobble block and it went into my inventory the backpack quit working again.

**Comment by LycanBlackpaw** [comment]
You don't shift click into the Beneath

**Comment by Scodigy** [comment]
@LycanBlackpaw, I'm not understanding so if you could help me. I'm right shift-clicking to enter the portal. For me it was the only way it would activate. If there is a proper alternative i would really be grateful for the help because this has stopped my progression.

**Comment by LycanBlackpaw** [comment]
@Scodigy The Beneath portal should only require a normal right click-that's how it's always activated for me. I haven't gone in since the update, however, so it is entirely possible it was changed and I don't know about it

**Comment by justinrusso** [comment]
Making a master thread. This will cover any of these type of issues as they are all related.

https://github.com/Darkosto/SevTech-Ages/issues/1634
