### ISSUE TITLE
Pedistal from Abyss Age 2 Bug report

### ISSUE THREAD

**Issue by Steve-Asgardian** [Darkosto/SevTech-Ages#1630]
The Pedastal with the Necronomicon on it to charge and 2 statues (left and right 1)  to charge it.
Shift -right click it to take it in your hand. and then you can do noting els enny more.
I can not place it or go in to my inventory (e) or even change to my pickaxe or sometying els in my inventory. The /kill comand helps but i just lost my pedestal and the Necronomicon that has about +400 power in it.

**Comment by LycanBlackpaw** [comment]
That's from Carry On, but you don't need to shift click it to retrieve your book.

**Comment by justinrusso** [comment]
@LycanBlackpaw is correct. But so this doesnt happen anymore, I'm going to just disable carry on for the pedestal

**Comment by Steve-Asgardian** [comment]
I know it happend by mistake.

**Comment by Steve-Asgardian** [comment]
@justinrusso Thx
