### ISSUE TITLE
Add smelting for dusts to Mekanism's Furnaces

### ISSUE THREAD

**Issue by justinrusso** [Darkosto/SevTech-Ages#1632]
http://crafttweaker.readthedocs.io/en/latest/#Mods/Mekanism/Energized_Smelter/

**Comment by justinrusso** [comment]
While attempting to add recipes, it appears as though the integration is broken and I am unable to add recipes currently to the energized smelter.

Reference: https://github.com/aidancbrady/Mekanism/issues/5010

**Comment by Tidalsniper** [comment]
Likewise DerpityDoo, the fact that in Age 5 I have no better way of smelting ores from dust is a bit silly.
