### ISSUE TITLE
Age 5 - Reborn Storage storage parts require RS processors

### ISSUE THREAD

**Issue by TWJedi** [Darkosto/SevTech-Ages#1635]
The Reborn Storage storage disks are not craftable because they require Refined Storage processors instead of AE2 processors. 

https://imgur.com/a/L1h0l

Solution: Change the recipe to require AE2 processors instead of RS processors.

Modpack version 3.0.5

**Comment by justinrusso** [comment]
This was said to be fixed in https://github.com/Darkosto/SevTech-Ages/issues/1401 but maybe @artdude543 missed something.

**Comment by Vyraal1** [comment]
Specifically it looks like artdude got the Crafting Frame, Heat Conductor, Crafting CPU, and Crafting Storages fixed, which are for the crafting multiblock, I guess the disk themselves got missed.

**Comment by artdude543** [comment]
Going to fix that shortly and that will be apart of the next update 😄
