### ISSUE TITLE
Riding horses freezes game

### ISSUE THREAD

**Issue by BradenCradock** [Darkosto/SevTech-Ages#1637]
## Issue / Bug

If a player(me) is on a horse while it is moving the game appears to freeze. However the game does not actually stop running as I have died many times while it is "frozen". This happens reliably within 5 seconds of getting on a horse. I don't even have to have a saddle on the horse.

This freeze also occurred when I approached a Fallen Knight riding a horse.

## Expected Behavior

Expected the game to continue to respond to inputs like moving, opening inventory etc. However it does not respond to any inputs and does not appear to be running. Window opens indicating the program is not responding

## Steps to Reproduce (for bugs)

1. Right click on a horse to ride it (Saddle or no saddle does not matter)
2. Move the horse (or wait for it to move if it has no saddle)
3. Within 5 seconds game freezes

https://gfycat.com/LightSpiffyFreshwatereel

## Context
I cant ride horses for exploration, and whenever I encounter a Fallen Knight riding a horse the game freezes and I die :(

## Logs

https://gist.github.com/BradenCradock/8e7e064ee03085f5abb5f372580acf2c

## Client Information
* Modpack Version: 3.0.6
* Java Version: 1.8.0_25
* Launcher Used: Twitch

**Comment by artdude543** [comment]
Please update your java and use the Jar launcher and try again. https://docs.google.com/document/d/e/2PACX-1vR5muyi1m7Zy_qSwrzeb9e3tbbRlksguNUb_Pvm3pn9eDpsIkUj5qQUq6WFPPdEoVWZq91WvvH57KzC/pub If the issue is still happening please re-log an issue thanks!
