### ISSUE TITLE
Server Files

### ISSUE THREAD

**Issue by Jobob57** [Darkosto/SevTech-Ages#1639]
Very simple question where do I get the server files? Can I get a link Please and Thank you.

**Comment by justinrusso** [comment]
Every submission can be found on https://minecraft.curseforge.com/projects/sevtech-ages/files. Click names (the latest version is better of course) Then scroll down to "Additional Files"

![image](https://user-images.githubusercontent.com/25138621/38475742-0805add4-3b78-11e8-91f8-798623cf28d8.png)
