### ISSUE TITLE
Using Sleeping Mat on a horse causes issues

### ISSUE THREAD

**Issue by ryankhart** [Darkosto/SevTech-Ages#1641]
## Issue / Bug

When I use my sleeping mat while mounted on a horse, I wake up next to the horse unable to get back on or interact with any blocks until I quit to title and reload the world.

## Expected Behavior

I don't necessarily expect to use my sleeping mat on a horse. It's not realistic, but attempting to do so shouldn't make me have to exit and re-enter the world to fix the issue.

## Possible Solution

It should either prevent me from sleeping on the horse or allow me to wake up and get back on the horse and/or interact with the world.

## Steps to Reproduce (for bugs)

1. Wait until night.
2. Mount a horse.
3. Use a sleeping mat while mounted on the horse.

## Context

It's only a minor annoyance. Fixing this issue would accomplish making the pack feel even more polished.

## Client Information

* Modpack Version: 3.0.6
* Java Version: 1.8.0 161 64bit
* Launcher Used: Twitch app using the Jar Launcher

* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: Faithful 32 Modded
* Optifine Installed?: Yes

**Comment by 0xb00b** [comment]
https://github.com/PrinceOfAmber/Cyclic/issues/772

has been fixed, so issue can be closed if cyclic is updated.

**Comment by artdude543** [comment]
Fixed in 3.0.7
