### ISSUE TITLE
Ore in the Hunting Dimension?

### ISSUE THREAD

**Issue by ifschwartz** [Darkosto/SevTech-Ages#1642]
It may be intended but I thought only mobs were supposed to be in the hunting dimension.  I found a jackpot of rock crystals (the Astral Sorcery crystals) in my hunting dimension.  I am attaching a screenshot but am not sure you can tell what dimension I am in.  I am on version 3.06.  This was just after about 5 minutes of running around killing mobs so I am assuming there is much more but do not have time to look right now.
![2018-04-08_21 17 43](https://user-images.githubusercontent.com/28758051/38476542-e81af0e6-3b73-11e8-9568-1db2f3e5b035.png)

Sorry if this is intended, I wasn't aware.

Thanks,
Ruprect1

**Comment by ifschwartz** [comment]
I should add I created the hunting dimension in 3.04 but have not used it until now (3.06).

**Comment by justinrusso** [comment]
Thats fine. Thanks for the concern though!
