### ISSUE TITLE
Villagers wandering away

### ISSUE THREAD

**Issue by OriginalSuperGumby** [Darkosto/SevTech-Ages#1644]
## Issue / Bug

The villagers of a dark lands village are just wandering away from the village.
## Expected Behavior

They should be staying close to the village and going indoors at night.
## Possible Solution

The houses may not qualify as houses due to a lack of doors. Light sources inside may also be necessary. To prevent adding doors too soon, perhaps animal hide flaps could be used as a substitute?
Could 'Minecraft Comes Alive' be part of this pack? Various functions would need to be clipped but it provides a lot of good features.
## Steps to Reproduce (for bugs)

1.
2.

## Context

Makes it difficult to track down the cartographer and farmer for advancing.
## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:

* Server/LAN/Single Player:
* Resourcepack Enabled?:
* Optifine Installed?:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Soultion:
* Sponge (Non-Vanilla Forge) Server?:

* Additional Content Installed?:
Java 161 (most current as of April 8), Windows 10

**Comment by Darkosto** [comment]
This is functionality we do not have access to add. You'll have to keep them in the villages on your own using what blocks you have available.
