### ISSUE TITLE
Blood Magic Living Armor Upgrade Soft Fall not working

### ISSUE THREAD

**Issue by gekkobear** [Darkosto/SevTech-Ages#1646]
## Issue / Bug

using Blood Magic Living Armor, working upgrades, most are working correctly (Healthy, Tough Palms, etc.), but Soft Fall is having no effect.
It had 5 levels and should reduce fall damage at each level by 20, 40 , 60, 80 or 100%.

I had some trouble getting it from 4 to 5, but you can do 1 a bunch and combine tomes to get a level 5 tome and apply that.
I applied the level 5 tome, and relogged to see armor updates and verified I had Level 5 Soft Fall on my armor.

I then jumped off my base and took 2.5 hearts of damage, the same damage I take without any levels of Soft Fall.
This is likely a problem in Blood Magic and not with Sevtech; but I'm unsure on that point.
Either Blood Magic isn't triggering to reduce damage, or something else is catching the same event before Blood Magic.

## Expected Behavior

Reduced fall damage from Soft Fall Living Armor upgrade.
Per the Blood Magic updates from 1.9.2.0.0-31 update notes:
"- Soft Fall decreases all fall damage, up to 100% at level 5."

## Possible Solution

This might need a Blood Magic change, or something in how it's reading/affecting fall damage, I'm not sure.

## Steps to Reproduce (for bugs)

1. Get Living Armor 
2. Get Soft Fall (Level 5 should be easiest to test, Living Armor Upgrade Tome could be cheated in I think).
3. Fall to take damage.
4. Optional (verify with Healthy or something clear that other updates do apply to that armor)

## Context

Still needing to keep/use bounce Sigil to avoid fall damage while wearing Living Armor; at a cost of LP.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 3.0.5
* Java Version: Version 8 update 181
* Launcher Used: Twtich

* Server/LAN/Single Player: Server
* Resourcepack Enabled?: No
* Optifine Installed?: No

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Soultion:
* Sponge (Non-Vanilla Forge) Server?:

* Additional Content Installed?:

**Comment by justinrusso** [comment]
https://github.com/Darkosto/SevTech-Ages/issues/1383

**Comment by gekkobear** [comment]
This isn't a duplicate issue. 
The linked issue has to do with updates not showing on the armor properly without a reset.

This issue has to do with an upgrade on the armor not working regardless if the armor shows it or not, and restarting has no effect.

**Comment by gekkobear** [comment]
This is not a duplicate of #1383.
Retesting in 3.0.6 single player still has the issue.

Get to age 3.
Get a full set of living armor.
Get the living armor upgrade tome for Soft Fall (level 5).
Jump to survival.
Wear the armor and use the tome to apply soft fall (using 25/100 points on the armor).
You still take fall damage, no damage was reduced or mitigated (and 100% should be at that level).

This isn't a visual issue with armor display flashing, it's an armor upgrade simply not working.

**Comment by gekkobear** [comment]
This wasn't a duplicate, this was a separate issue.
It had to so with Safe Fall not applying, ever.
Not the graphical issue linked in 1383.

However it's fixed in Blood Magic with 2.2.8 (if I download and install that version over 2.2.7 it';s all good).
So leave it closed I guess, next patch should correct it anyhow.
