### ISSUE TITLE
Recipe for Melon pie missing

### ISSUE THREAD

**Issue by Arphahat** [Darkosto/SevTech-Ages#1647]
## Issue / Bug

In version 3.0.5, only melon pie recipe now available in age 2 is with the Better with Mods kiln which is not usable until when the hibachi is available in a later age, making them uncraftable.
## Expected Behavior

Should be able to make as before, maybe on grill or oven or other kiln.
## Possible Solution

Add the furnace / grill recipes back in. Or, remove melon pie from appearing craftable in Age 2 and earlier.

**Comment by Arphahat** [comment]
Sorry for poor formatting. Was doing this on phone and didn't realize how it would look.

**Comment by Digital-Storm** [comment]
Yep, same experience here. Noticed in a video by SystemCollapse where he had half a stack of melon pies but was only in age 2, so he must have cheated them in. I wasted too much time trying to get the kiln and other stuff to make these pies.

**Comment by ChylerBH** [comment]
@Digital-Storm Melon Pies had been craftable in the hand (2x2 grid) prior to 3.04 and Stage 2 so they were definitely not 'cheated in'.  I just checked my game and I still have half a stack left :)  I had been using these with the Hearty Stew to cover all 4 of the Nutrition mod requirements.  Obviously now the new recipe requires the kiln as @Arphahat suggests this is now a new staging issue or a bug.

**Comment by MooseAteJack** [comment]
Yup,
I was crafting them up to 3.04. Just upgraded to 3.06 and no more melon pies. Have crafted the Oven ready ones but can't seem to work out how to cook them...

**Comment by DaedalusGame** [comment]
hey i'm a broken record on this one, but this is my fault, i adjusted the module it checks for to correctly check HCCooking instead of HCHunger to enable the handcrafting recipe. This leads to the handcrafting recipe disappearing as HCCooking is enabled and the smelting recipes never existed in the first place (when they should have, sorry about that) I already added the smelting recipes back in dev.

**Comment by elmatador316** [comment]
Does this mean we should expect the additional cooking recipies in the next update?

**Comment by artdude543** [comment]
This is resolved in 3.0.7
