### ISSUE TITLE
Crash after making too many firesticks.

### ISSUE THREAD

**Issue by darkmdbeener** [Darkosto/SevTech-Ages#165]
## Instruction on how to do issues like your boy darkosto
 have a full inv and make more fire sticks then your inventory can handle. If you delete playerdata folder it will not fix the issue because the playerdata folder will be recreated with the same inventory. 

 ### Issue / bug
 - Explain the issue / bug as understandably as possible.
the game will crash and will not able to load back in 

 - If possible add minecraft, forge, java and modpack version numbers for debugging (mod authors might need these).
SevTech Alpha 6 Twitch App Export:

 - If the issue/bug is recurring explain how it can be recreated (helps darkosto!).
Make more fire sticks then can fit in your inventory 

 - If possible add error/crash log to [Pastebin](https://pastebin.com/) and link it here (if you dislike pastebin any other similar site is fine too).
https://pastebin.com/uy7EHQzL

**Comment by darkmdbeener** [comment]
SevTech Alpha 7 does not fix the issue. figured I would try it just to be safe.

**Comment by justinrusso** [comment]
Just to add some more detail, https://gyazo.com/1db1c468531d3f6592751d8a77128d64 This was similar to what dark had done. There were other items  in the inventory, but essentially he spam shift+click on the item to craft it, and caused a crash. As seen in my GIF, I wasn't able to cause a crash.

**Comment by darkmdbeener** [comment]
https://lh3.googleusercontent.com/-IioxbUi0LI4/We6oBryHfuI/AAAAAAAATTU/yvjZb9Oi1qwfmfMalOvyrJDLhvDHQXnawCHMYCw/s0/NBTExplorer_2017-10-23_22-40-02.png

this might be the issue.

**Comment by darkmdbeener** [comment]
In order to fix this you need to install nbtexplorer. From this you want to open the instance from twitches install location. You are going to search for playerdata and open it up  search through these (should be near the bottom) for one that has a negative value for slot. Then go to level.dat and expand that one. From there you want to expand Player, then inventory, and search for that exact same item. remove  these two and save. 

Restart the client and minecraft game and you should be able to enter the world.

**Comment by vadis365** [comment]
This issue should now be fixed - it was an issue with the items needing NBT on crafting before the item updated.
