### ISSUE TITLE
Charcoal Piece has no texture (anymore)

### ISSUE THREAD

**Issue by Namerian** [Darkosto/SevTech-Ages#1650]
## Issue / Bug

"Charcoal Piece" from "Pickle Tweaks" has no texture (in inventory and on the ground).

## Steps to Reproduce (for bugs)

1.
2.

## Context

The texture disappeared after I transferred the save from my 3.0.4 instance to my 3.0.6 instance (MultiMC).

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:3.0.6
* Java Version:8
* Launcher Used:MultiMC

* Server/LAN/Single Player:SP
* Resourcepack Enabled?:no
* Optifine Installed?:no

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Soultion:
* Sponge (Non-Vanilla Forge) Server?:

* Additional Content Installed?:

**Comment by artdude543** [comment]
Closing as dupe follow 1653 for updates.
