### ISSUE TITLE
Shearing Block gives wool instead of fleece.

### ISSUE THREAD

**Issue by togreglove** [Darkosto/SevTech-Ages#1651]
Searched...found bug about kama, but not shearing block
 
## Issue / Bug
Shearing block, when sheep brush up against it, gives wool, not fleece

## Expected Behavior
Expect to get fleece

## Possible Solution
Change behavior of block to give fleece instead of wool

## Steps to Reproduce (for bugs)
spawn sheep
place shearing block
push sheep against block
get wool

## Context
Makes it much easier to mass produce wool

## Client Information

* Modpack Version: 3.0.6
* Java Version: Latest
* Launcher Used: MultiMC

* Server/LAN/Single Player: Server
* Resourcepack Enabled?: Faithful 32
* Optifine Installed?: No

**Comment by Targren** [comment]
I thought this was a "progression" on getting wool, kind of like the wooden basin->mixer + drying units etc... for getting leather.

**Comment by MrBirk** [comment]
It's pretty cheap.
       I was a bit surprised the industrial loom from modular machines wasn't actually used to make wool from fleece at a cheaper amount 2 fleece over 4 or something and without the wicker as wool being made by a loom makes more sense to me than string. I'd expect string to be made on the spinning wheel from Better with Addons with cotton or hemp etc.

**Comment by justinrusso** [comment]
The block is with us no longer
