### ISSUE TITLE
Modular Machines inventory crash

### ISSUE THREAD

**Issue by DerpityDoo** [Darkosto/SevTech-Ages#1652]
Shift+r-clicking an empty bucket in inventory while in Modular Machinery's "Tiny Fluid Output Hatch" causes Minecraft to be unresponsive, leaving me with no crash report. Happened twice, figured I should tell someone. <3

Pack Version: 3.0.6
Optifine Is Installed
Java is up-to-date and forced in launcher

**Comment by DerpityDoo** [comment]
lol it happened again, but this time with a bucket of naptha.

**Comment by artdude543** [comment]
Will be fixed in 3.0.7
