### ISSUE TITLE
Missing textures 

### ISSUE THREAD

**Issue by TomKing1** [Darkosto/SevTech-Ages#1653]
So far i found the (block and chain) is blank so is the (charcoal piece) and (bear claw)

**Comment by JustHeyo** [comment]
I confirm bear claws - was about to report that myself.  Thanks!

**Comment by KosmosPrime** [comment]
Some testing seems to have fixed this for me when setting foamfix's "dynamicItemModels" to false.
It might have something to do with the display attribute, as all 3 items that have been mentioned have it and other "nearby" items do not (and are bug-free). It's not just that though, maybe a specific attribute or lack thereof causes foamfix to cache or render the model incorrectly.
>Questionable "performance improvements" that are not in Forge for probably very good reasons.

**Comment by artdude543** [comment]
This appears to be fixed in 3.0.7
