### ISSUE TITLE
Tier II Starlight Crafting Altar having a red bar, even though the structure is proper

### ISSUE THREAD

**Issue by 100in33** [Darkosto/SevTech-Ages#1654]
I built the structure for the tier II Starlight Altar upgrade, did the ritual, the altar upgraded, but it had a red meter in it for the starlight, so I couldn't craft anything. Checked and triple checked the structure around it, everything was proper. When I googled the issue, I saw that many people had the issue, but no one provided answers. I finally figured it out, but wanted to make a suggestion to prevent this from happening in this mudpack. 

The issue is that the marble bricks cannot be the Chisel ones, they have to be crafted. But it is so easy to screw up on this, because you chisel ALL other parts of that structure (except the black marble blocks) without any issue. So the suggestion would be to make the Chisel output the Astral Sorcery Marble Brick, instead of the Chisel - Marble | Bricks.

**Comment by daddy77gaming** [comment]
you can defo chisel into the astral sorcery bricks,
the whole bottom row when marble is in the chisel are all the astral sorcery marble variants you will need.
![2018-04-09_13 27 18](https://user-images.githubusercontent.com/31905330/38497665-27cc3d06-3c02-11e8-8dec-bafb25bd5c0e.png)

**Comment by Hebbu** [comment]
You probably used the wrong Marble blocks in the build

**Comment by Phantum** [comment]
^ This, I had no issues with mine (other than not enough starlight, but that's my own issue)

**Comment by Avendir** [comment]
Use your chisel to change the marble from (Marble, raw, Chisel) to (Marble, Astral Sorcery.

**Comment by Sunr4ven** [comment]
I had the same problem but found a different solution. I took an existing shrine as location for my astral sorcery project and placed the altar in the middle on top. Then i changed the structure the way it should be according to the astral tome and the red meter was still showing. For me it didnt matter if i chiseld the bricks or any other block. What did the trick was to look at the blocks beneath the pillars. They were bricks but should be chiseld marble. After changing them it worked ;-)
