### ISSUE TITLE
Tin clusters

### ISSUE THREAD

**Issue by LickitySplit74** [Darkosto/SevTech-Ages#1658]
Tin clusters turn into Primal Core Tin dust in the quartz grindstone and no use for primal core tin dust. Not sure if this was intentional.

**Comment by artdude543** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

Thanks again for reporting, and we hope you enjoy the pack!
