### ISSUE TITLE
Crash on loading a new world / pack not working

### ISSUE THREAD

**Issue by MoldyCarrot** [Darkosto/SevTech-Ages#1659]
## Issue / Bug 
When starting up a new world on a clean save / client / modpack (yes I tried all) all of my new worlds seem to immediately crash when they are loaded and they put me back into the multiplayer search menu while it was started up as a single player world.

## Expected Behavior
my world to just load and being able to even play the modpack.

## Possible Solution
ive run out tbh

## Steps to Reproduce (for bugs)

1. Just installing the modpack and creating a new world will cause the crash for me.
2.

## Context 
trying to start playing the modpack with a clean world.

## Logs

* Client/Server Log: https://pastebin.com/f3iU9FQU
* Crash Log: https://pastebin.com/HW47EsAB

## Client Information

* Modpack Version: 3.0.6
* Java Version: Latest
* Launcher Used: Twitch Launcher

* Server/LAN/Single Player: Single player
* Resourcepack Enabled?: nope
* Optifine Installed?: nope

## Server Information
* Java Version: /
* Operating System: /
* Hoster/Hosting Soultion: /
* Sponge (Non-Vanilla Forge) Server?: /

* Additional Content Installed?: /

**Comment by SteseDav** [comment]
Line 28 is your issue >  java.lang.OutOfMemoryError: GC overhead limit exceeded

You need to allocate more RAM to the modpack, as you only are allocating 2GB currently ( JVM Flags: 3 total; -Xmx2048m -Xms2048m -XX:PermSize=256m)
