### ISSUE TITLE
Cheese Mold causes strange effects when replaced by other tile-entities

### ISSUE THREAD

**Issue by Rynloh** [Darkosto/SevTech-Ages#166]
If a Cheese Mold block is placed and then broken, the location it occupied causes various issues when blocks that have tile-entities are placed there.

## Effects
When a chest is placed where the Cheese Mold was, it does not render, though the inventory interaction still works as expected.
I actually found this issue when placing a Stone Grill where I previously had my Cheese Mold while rearranging my base, which caused the game to crash.

The issues caused by this bug persist after placing and removing a block at the affected location.

[Game Log](https://pastebin.com/NvvA4AjK)
Pack Version:  SevTech Alpha 7
MC Version:    1.12.2
Forge Version: forge-14.23.0.2515

**Comment by Rynloh** [comment]
From what I can tell from the log, it seems that the Cheese Mold isn't deleting the attached tile-entity when the block is broken.
When another block that has a tile-entity is placed in that location, it tries to access the tile-entity at those coordinates which is the one from the Cheese Mold.
The Stone Grill tries to access this tile-entity as one of its own, which causes Java to throw an invalid cast error.

**Comment by Rynloh** [comment]
I've been doing a bit more investigation.

If you reload the world between breaking the Cheese Mold and placing the Stone Grill, there is no crash.

**Comment by Darkosto** [comment]
Sent over to the dev, thank you very much for this report!
 
Crash when I tested: https://pastebin.com/jdiEFvpY

@capnkirok

**Comment by vadis365** [comment]
Sounds like he is not invoking the breakBlock method for the block, as this will remove old TE's from the world when the block is broken. Maybe.

**Comment by capnkirok** [comment]
Working on it, will try to have release this weekend with the cart udpate

**Comment by capnkirok** [comment]
Yay 👯
