### ISSUE TITLE
[ BUG ] Hunger bar stops working

### ISSUE THREAD

**Issue by lurch9229** [Darkosto/SevTech-Ages#1660]
## Steps to Reproduce (for bugs)

1.
2.

## Client Information

* Modpack Version:3.0.6
* Java Version:java 8
* Launcher Used:twitch

After reaching the 1st age, my hunger bar stopped decreasing, normally I would not complain about a  bug such as this, but seeing as there is the mechanics of eating different foods, I now have multiple negative effects such as mining fatigue and weakness, which is obviously ruining my gameplay. I decided to try killing myself which fixed it at first but then it happened again. I have tried many things to force it down, such as purposefully taking damage, running and jumping around and using the hand crank/mill stone but it still won't go down. Sometimes dying doesn't even fix it.

I wish I could pinpoint what the cause of this is, as it is quiet game breaking.

**Comment by smisch** [comment]
Did you double-check that you were not on peaceful mode? If load up a creative test world in peaceful mode and then switch back to your regular world, the difficulty will carry over and disable hunger.

**Comment by lurch9229** [comment]
I'm not in peaceful mode, I went into creative mode once and its been a problem since then. Now its habit to start hitting the hand crank as soon as I respawn to see if the hunger wants to work properly. If it does it will be fine for maybe half hour but then it will just suddenly stay full again, meaning I can never get my nutrition up for too long and not benefit from having the buffs. The saturation disappears but not the ham hocks.

**Comment by artdude543** [comment]
This is not a pack issue seems like a user error in regards to the difficulty setting. As I can't reproduce this issue at all. But if you get the issue again please re-file a new issue.
