### ISSUE TITLE
Missing Charcoal Piece Texture - Pickle Tweaks

### ISSUE THREAD

**Issue by OriginalSuperGumby** [Darkosto/SevTech-Ages#1662]
## Issue / Bug

Charcoal dust has no texture; it's invisible. Also charcoal dust is needed for the third hopper recipe so maybe it should be a stage 0 item?
## Expected Behavior

See the item.
## Steps to Reproduce (for bugs)

1. Grind charcoal with a grindstone and the resulting item has no texture. I am presuming it is charcoal dust but it is currently an unfamiliar item. 
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 3.0.6
* Java Version: -161
* Launcher Used: Twitch

* Server/LAN/Single Player: Single
* Resourcepack Enabled?: No 
* Optifine Installed?: No

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Soultion:
* Sponge (Non-Vanilla Forge) Server?:

* Additional Content Installed?:

**Comment by SteseDav** [comment]
repeated report #1554 #1591 #1650....

**Comment by OriginalSuperGumby** [comment]
It's not the charcoal dust that has no texture as I have now made that. Still can't see it whatever it is. Perhaps moving into the next age will reveal the name.

**Comment by OriginalSuperGumby** [comment]
Ok Level 1 reveals the item to be a charcoal piece from Pickle Tweaks. The JEIO dictionary is also missing this texture as well as the 'coal piece'.

**Comment by OriginalSuperGumby** [comment]
Repeat of existing issue.
