### ISSUE TITLE
Mandan Buffalo Dance Stopped Working

### ISSUE THREAD

**Issue by OriginalSuperGumby** [Darkosto/SevTech-Ages#1663]
## Issue / Bug

Second and Third attempts at the Buffalo Dance failed to convert any cows. Cannot even start a fourth dance. Other dances (Imbue Flute and War Dance) still work - multiple times in a row.
## Possible Solution

Perhaps the issue lies with the auto-ringing of the chimes? They may be interfering with the initiation of the dance.
## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:3.0.6
* Java Version:-161
* Launcher Used:Twitch

* Server/LAN/Single Player:Single
* Resourcepack Enabled?: No
* Optifine Installed?: No

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Soultion:
* Sponge (Non-Vanilla Forge) Server?:

* Additional Content Installed?:

**Comment by 0xb00b** [comment]
have you tried re-placing the totem base?

**Comment by OriginalSuperGumby** [comment]
Gave that a try no joy but I did figure it out. I have three chimes hanging. The one chime I kept hitting would not trigger the ceremony but I chose a different chime and it started. I suspect the first chime may be one square too far away.
