### ISSUE TITLE
Compacting Drawer Question

### ISSUE THREAD

**Issue by Nikolos67** [Darkosto/SevTech-Ages#1664]
## Issue / Bug
Not anything game breaking, but just wondering if compacting drawers were meant to only compact certain items. Lapis compact like normal, but redstone, quartz, diamond does not (metals not compacting was expected because of the "packing/unpacking"). Just wanted to know if redstone was meant to compact or not. If this was intended, sorry for opening an issue, I just wanted to check.

## Expected Behavior
Redstone/other non-metals compacts into blocks with the compacting drawer

## Client Information
* Modpack Version: 3.0.6
* Java Version: 8
* Launcher Used: Twitch

* Server/LAN/Single Player: Server
* Resourcepack Enabled?: No
* Optifine Installed?: No

## Server Information
* Java Version: 8
* Operating System: Windows Server Edition 2008
* Hoster/Hosting Soultion: Hoster
* Sponge (Non-Vanilla Forge) Server?: No

**Comment by Vyraal1** [comment]
Compacting Drawers check if an item can be compressed into a 3x3 crafting pattern in the crafting grid, if it can, then it will compact automatically. The items you listed above should all have a 3x3 crafting grid compression recipe.

**Comment by Nikolos67** [comment]
Thats what I thought, but redstone and diamonds do not compress in the drawer. I get that metals wont, but shouldn't redstone, diamonds, emeralds, quartz, and things like litherite all become blocks.

**Comment by Darkosto** [comment]
The recipes are working as intended.
