### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by djnifos** [Darkosto/SevTech-Ages#1679]
https://pastebin.com/AL6eWGpW

## Issue / Bug
Crash when closing door.  Maybe something to do with BwA?

161
3.0.6
optifine
ssp

**Comment by SteseDav** [comment]
Does this happen without optifine added?

**Comment by artdude543** [comment]
This was fixed (according to the mods commit history) in the version we are using in 3.0.6. Can you double confirm you're on that version?

**Comment by artdude543** [comment]
@DaedalusGame can you confirm that this was fixed? Or this a new CME?

**Comment by djnifos** [comment]
I'm on 3.0.6 for sure.  I don't know how to replicate it exactly, I do that exact action all the time.  I could remove optifine and test again if you could tell me how to replicate.

**Comment by DaedalusGame** [comment]
ok how many more synchronized collections will it be please stop causing CMEs i don't know how to solve them anymore

**Comment by DaedalusGame** [comment]
i hope it won't resurface this time :p

**Comment by djnifos** [comment]
Thanks @DaedalusGame you rock!!

**Comment by artdude543** [comment]
@DaedalusGame tag me when the fix is included with a mod update if you could :)

**Comment by DaedalusGame** [comment]
@artdude543 i've pushed a fix for the CME to curseforge now

**Comment by artdude543** [comment]
Thank again! darkoHeart
