### ISSUE TITLE
Tinkers construct gem cast uses gear

### ISSUE THREAD

**Issue by Dawenzel** [Darkosto/SevTech-Ages#168]
## Issue
The tinkers construct gem cast `<tconstruct:cast_custom:2>` is able to be cast with the stone gear `<teslacorelib:gear_stone>` as an ingredient.

## Possible Solution
This issue is caused by the `<tconstruct:cast_custom>` having a metadata of 2 which means it makes a gem cast. Changing this to 4 should make this a gear cast.

## Versions
- Sevtech-Ages Alpha 7

**Comment by Darkosto** [comment]
Fixed! :D Thank you!
