### ISSUE TITLE
Server Sevtech

### ISSUE THREAD

**Issue by Occuvite** [Darkosto/SevTech-Ages#1683]
I have error when i opened forge-1.12.2-14.23.2.2651-universal.jar

[logs.zip](https://github.com/Darkosto/SevTech-Ages/files/1892901/logs.zip) 
Modpack version: 3.0.6
Java 8 Update 161 
Hosting https://www.myarena.ru/
sponge server forge-1.12.2-14.23.2.2651-universal.jar

**Comment by sarcastic6** [comment]
This isn't a bug, it's a misconfiguration on your side:

`[10:57:15] [Server thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.OutOfMemoryError: Java heap space`

Check your parameters for launching the server; you haven't allocated enough memory to it.

**Comment by SteseDav** [comment]
@Occuvite  : Have you got a server from your provider with enough RAM? I beleive the minimum SevTech will start with is 4GB (4096MB). I'd consult with them for more information on how they allocate RAM to java in their setup.

**Comment by Occuvite** [comment]
In my computer i have 8 GB RAM

**Comment by SteseDav** [comment]
Ok, you need to be clear where the issue is here. Is the server not starting, or is it the client on your machine not starting?

**Comment by Occuvite** [comment]
The server not starting

**Comment by SteseDav** [comment]
OK, in that case the RAM in your computer isn't relevant. How much RAM is available on the server? You'd probably need to check with the control panel.

**Comment by artdude543** [comment]
As the error suggests there is not enough memory given to the server. You need to allocate more as the server needs a fair amount of fun efficiently. If you're on the low-end package that host seems to offer you won't have a great time trying to run a SevTech Server based on their specs.

But the error is there and is self-explanatory and not a pack issue. So please consult with your host/server owner to continue debugging.
