### ISSUE TITLE
[Server] Some players not going to next age (3.0.6)

### ISSUE THREAD

**Issue by broeredaan** [Darkosto/SevTech-Ages#1688]
## Issue / Bug

So I cant find any logs about it but some players are experiencing an issue where the next age is not unlocked when they finish the last quest on the previous age. Which means that they are stuck in the age because the next one doesnt unlock.
I'm just here in the hopes that someone has experience this aswell and has since been able to fix it.
## Expected Behavior

For advancement to properly initialize the next age for everyone if last quest is reached.
## Possible Solution

Force the advancement no matter what happens when a person completes the last advancement of a stage. Perhaps that will solve it.
## Steps to Reproduce (for bugs)

I wish I could provide steps. Now one thing I can think of is that I removed weirdinggadet from my server because I dont want people to chunkload. This however made all the recipes crash and maybe also the advancements? I've since re-added the mod to fix the recipe errors, but maybe in that time something went wrong with players data.

## Server Information
* Java Version: 8
* Operating System: Ubuntu
* Hoster/Hosting Soultion: Dedicated Server
* Sponge (Non-Vanilla Forge) Server?: Sponge 3006

**Comment by artdude543** [comment]
Can you change your server back to Vanilla Forge and try to reproduce the issue. Using a Sponge server voids **all** support from us as Sponge is known to break more things than solve. Thanks.

**Comment by broeredaan** [comment]
There multiple people playing on it and it would not be easy to test very quickly without people getting mad :/. It was working just fine for 3.0.4 without any problems until I updated to 3.0.6. But I'll see what I can do and for now will use `/gamestage add` and `/advancement add`

**Comment by artdude543** [comment]
Yeah sadly as Sponge breaks too much; we don't offer any support for it. Sponge has a major issue with breaking the advancement system which our mods rely on. We don't recommend anyone for using it but we can't stop you. You will just have to deal with the issues it throws at you.

As the commands would your way around the issue I'm going to close the issue; But you manage to get it not working on a Vanilla Forge install be my guest and open a new issue :)
