### ISSUE TITLE
(Suggestion) - Add advancement for Oxygen Collector to smooth direction of Stage 4. 

### ISSUE THREAD

**Issue by Dystilled** [Darkosto/SevTech-Ages#1689]
Would suggest adding creating an Oxygen collector as an advancement in between the advancements for "Advanced Ender Alloy" and "Fill her up". 

Seems to be little direction at this point of the stage and nothing in JEI points to the fact that the Oxygen Collector is intended to be used with the IE refinery for creating Fuel. 

Possibly also worth mentioning how the Fuel Canisters are intended to be created once you have the fuel or whether you are expected to do it another way, as this too is not overly clear.

**Comment by artdude543** [comment]
We had got an advancement for the collector. And the JEI issue is just something we can't avoid.
