### ISSUE TITLE
Factory Tech ores visible and mineable with stone tools in Stage 0

### ISSUE THREAD

**Issue by MongoTheElder** [Darkosto/SevTech-Ages#169]
![2017-11-04_10 12 46](https://user-images.githubusercontent.com/29290246/32406117-e0b1f142-c148-11e7-8c84-a183bf0e31c8.png)

Found Nickel and Native Copper ores.

SevTech: Ages Alpha 7

**Comment by Darkosto** [comment]
Looks to be all fixed up in my version :D
