### ISSUE TITLE
Blood magic potion flask recipe incorrect and uncraftable

### ISSUE THREAD

**Issue by neitherine** [Darkosto/SevTech-Ages#1690]
## Issue / Bug

Blood magic potion flask recipe in the JEI is listed as requiring an "uncraftable potion" to craft, 
## Expected Behavior

I believe it should list a filled water bottle as the item required

## Context

Unable to craft blood magic flasks to make blood magic potions

## Client Information

* Modpack Version: 3.04
* Java Version: 
* Launcher Used: twitch

* Server/LAN/Single Player:
* Resourcepack Enabled?:
* Optifine Installed?:

**Comment by kragnoth** [comment]
you can make uncraftable potions by using an empty glass bottle on water.  It seems to randomly create either a water bottle, or an uncraftable potion.

Which in of itself might be a bug due to the non-infinite water mod?

**Comment by boldenburg** [comment]
Also: if you cheat in a Potion Flask and attempt to "enchant" it in the Alchemy Table, nothing happens (tried with Magician Blood Orb + 28k network LP + ghast tear / golden carrot / magma cream).

**Comment by artdude543** [comment]
This is intended with the mod changing the water. We need to add a better "tier" recipe to put water into a bottle. So this will be looked into. But if you travel out to a larger body of water you can get the water bottles that way.
