### ISSUE TITLE
Wild dogs do not drop their pelts

### ISSUE THREAD

**Issue by 100in33** [Darkosto/SevTech-Ages#1691]
I have killed over 30 wild dogs as of the latest version, without any of them dropping a single pelt. I used Tinkers swords and I used the Twilight swords. Is this intended? Do they only have a chance to drop pelts if killed with vanilla swords? If so, is that intentional and did I miss it saying that somewhere?

**Comment by artdude543** [comment]
This is not an issue it's a chance based also. I got a few from one and none from another and one from another etc... this works as intended.

**Comment by 100in33** [comment]
38 now, with 0? That's not chance. I am unsure why some of you are still able to get a pelt, but it took me 2 RL days to kill a total of 38 now without a single drop. This happened when I updated to the 3.0.6. If it is "chance", it is WAY too low IMO. Or something is definitely wrong with my game.
