### ISSUE TITLE
my game Crashes in startup. seems issue with Chisel.

### ISSUE THREAD

**Issue by deanec64** [Darkosto/SevTech-Ages#1693]
https://pastebin.com/8516Gh2D
Default install 

it seems that theres an error with 1 of the files for chisel. unsure what to do. 

specifically, it seems that its this error that shows the issue. 

"net.minecraft.client.renderer.StitcherException: Unable to fit: chisel:blocks/cobblestone/layers - size: 16x16 - Maybe try a lowerresolution resourcepack?"

**Comment by artdude543** [comment]
Dupe of #924

**Comment by justinrusso** [comment]
That .. doesnt change a thing. this isnt related to the launcher.
