### ISSUE TITLE
Toxic Witch does not regenerate health

### ISSUE THREAD

**Issue by IQnQ** [Darkosto/SevTech-Ages#1696]
## Issue / Bug
When you damage a Toxic Witch from EmberRootZoo, it whips out the potion its supposed to use and just stops with the potion in hand. Tested it single player and on a server.

## Expected Behavior
Witch should drink the potion.

## Steps to Reproduce (for bugs)
Unlock Toxic Witch (age 2+ I believe) and damage it a bit.

## Context
I was planning to harvest some LP from these but they just die w/o regen.

## Client Information
Modpack Version:3.0.6

**Comment by artdude543** [comment]
Intended.
