### ISSUE TITLE
Do not run SevTech

### ISSUE THREAD

**Issue by NickleOfficial** [Darkosto/SevTech-Ages#1697]
## Steps to Reproduce (for bugs)

1.Do not run SevTech
2.

## Logs

* Client/Server Log:
* Crash Log: 
[latest.log](https://github.com/Darkosto/SevTech-Ages/files/1895571/latest.log)

## Client Information

* Modpack Version: 3.0.6
* Java Version: 8
* Launcher Used: twich app

* Server/LAN/Single Player: -
* Resourcepack Enabled?:no
* Optifine Installed?: no

## Server Information
* Java Version: 8
* Operating System: win7 64 max
* Hoster/Hosting Soultion: -
* Sponge (Non-Vanilla Forge) Server?: -
 -
* Additional Content Installed?:
-

**Comment by artdude543** [comment]
Please re-log this issue with actual content and a valid title. From the log, it's all normal so really I have nothing to go on other than you not understanding how to make an issue correctly.
