### ISSUE TITLE
Hangs on loading and crashes

### ISSUE THREAD

**Issue by NickleOfficial** [Darkosto/SevTech-Ages#1699]
## Steps to Reproduce (for bugs)

1.Hangs on 6/7 and crashes out(SevTech reinstalled)
2.

## Logs

* Client/Server Log:
* Crash Log:
[latest.log](https://github.com/Darkosto/SevTech-Ages/files/1895683/latest.log)

## Client Information

* Modpack Version: 3.0.6
* Java Version: 8
* Launcher Used: twich app

* Server/LAN/Single Player: -
* Resourcepack Enabled?: no
* Optifine Installed?: no

## Server Information
* Java Version: 8
* Operating System: win7 max
* Hoster/Hosting Soultion: -
* Sponge (Non-Vanilla Forge) Server?: -
 
* Additional Content Installed?:
-

**Comment by sarcastic6** [comment]
`Memory: 643744256 bytes (613 MB) / 1072168960 bytes (1022 MB) up to 2863661056 bytes (2731 MB)`
You'll need to give the pack more memory than that.

**Comment by daddy77gaming** [comment]
at least double

**Comment by Low-Gravity** [comment]
I give mine 4.352GB (4,352MB) and it actually takes up over 9GB, the twilight forest is the worst so far.

You need a bare minimum of 16GB of RAM to play this pack and it will still over fill it and you'll need to re-log to clean the RAM.

**Comment by artdude543** [comment]
Closing due to this being a user side error and not a pack. Ensure all your drivers/java is up to date and to not over allocate memory as you'll only make it worse.
