### ISSUE TITLE
Easy Leather recipe

### ISSUE THREAD

**Issue by davqvist** [Darkosto/SevTech-Ages#17]
By putting cooked food on a Drying Rack you can get Leather way easier, that's probably not intended.

**Comment by CrossMyDNA** [comment]
You can also get a lot of leather from villagers for animal pelts—kind of makes the whole leather process useless.

**Comment by Darkosto** [comment]
It's not intended and currently not possible to edit until ModTweaker has the ability to remove TCon recipes. Before I left for PAX we were waiting on TCon to add the ability for modtweaker to hook into this.

@jaredlll08

**Comment by Darkosto** [comment]
All fixed up! Thanks!
