### ISSUE TITLE
Marble and Limestone require Stage 1 to use

### ISSUE THREAD

**Issue by MongoTheElder** [Darkosto/SevTech-Ages#170]
Marble and Limestone are visible in Stage 0 and mineable with stone tools but require Stage 1 to use. This makes it difficult to manage inventory since the only thing that can be done with the blocks is drop them.

Is there a need to restrict these to Stage 1?

**Comment by Darkosto** [comment]
I went through and made sure most of Chisel is not available until the correct stage and left those blocks. Thanks!
