### ISSUE TITLE
Power adapter generates infinite power when converting RF to RF

### ISSUE THREAD

**Issue by futileohm** [Darkosto/SevTech-Ages#1701]
## Issue / Bug
Power adapter generates infinite RF when converting from RF to RF (not tested with other power types), even after the input side goes to 0 rf/t.

Video: https://imgur.com/a/HIW4s

## Expected Behavior
Non-infinite power from an adapter block.

## Steps to Reproduce (for bugs)
1. Place a power adapter on some sort of RF generating block
2. Put a RF consumer on another side of the adapter (tested with PowerCells and IE wire connectors)
3. Apply power to the RF generating block
4. Let it run out of fuel or otherwise stop generating power
5. Enjoy the infinite power from the adapter

## Logs
* Client/Server Log: https://gist.github.com/futileohm/fc7735a496e77a8aa4ab8397f28e4887

## Client Information
* Modpack Version: 3.0.6
* Java Version: 1.8.0_162
* Launcher Used: MultiMC
* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by artdude543** [comment]
Fixed in next version!
