### ISSUE TITLE
Game crashing when trying to enter a new world.

### ISSUE THREAD

**Issue by Matvanbeer** [Darkosto/SevTech-Ages#1702]
## Issue / Bug

I open the game via the twitch launcher, it starts up fine. I can create a world, but when I try to enter it my game crashes.

## Expected Behavior

The game crashes instead of loading the world.

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log: [hs_err_pid1076.log](https://github.com/Darkosto/SevTech-Ages/files/1896095/hs_err_pid1076.log)

## Client Information

* Modpack Version: 3.0.6
* Java Version: Java 1.8.0.162 (64-bit)
* Launcher Used: Twitch launcher

* Memory Allocated: 5120

* Server/LAN/Single Player: Single player
* Resourcepack Enabled?: No

* Optifine Installed?: No

**Comment by MJRLegends** [comment]
This isn't a mod pack crash, its a java thing that will happen with any java application

**Comment by Matvanbeer** [comment]
Thanks for the reply. By downloading the new java update it automatically reverted to my intel graphics card, instead of my NVIDIA graphics card. I fixed it by letting java run on my NVIDIA card so everything works now.
