### ISSUE TITLE
Age 5 ore processing analysis 

### ISSUE THREAD

**Issue by Waisse** [Darkosto/SevTech-Ages#1703]
Sevtech 3.0.6

Just a review of ore processing at Age 5. There's some inconsistencies/balancing issues. I only kept output superior than 2. Some processing recipes are missing, useless, or output directly smeltable dust. Mekanism enrichment chamber is the weirdest because most outputs are different from its ore tripling and beyond chain.

- Coal/redstone/lapis lazuli/diamond/emerald
Mechanical squeezer trump everything by a large margin. Starlight infusion allow emerald and diamond quadrupling but can't be automated.

- Nether Quartz Ore
Mekanism enrichment chamber : 6 nether quartz
IE crusher : 3 nether quartz + 1 sulfur dust at 15% chance

- Certus quartz ore
IE crusher : 3 certus quartz crystal
AA crusher : 2 certus quartz dust
has no Mekanism ore processing
has no mechanical squeezer processing

- Black Quartz ore
IE crusher : 2 black quartz
AA Crusher : 2 crushed black quartz
has no Mekanism ore processing
has no mechanical squeezer processing

- Dimensional shard ore
No processing recipe

- Sulfur ore
has no Mekanism ore processing
has no mechanical squeezer processing

- Cobalt/Ardite ore
no processing except the smeltery

- Gold cluster
Mekanism enrichment chamber : gold dust (useless)
Mekanism ore tripling and beyond : gold grit (arc furnace)
Mechanical squeezer : 2 gold grit + 1 at 50% chance

- Silver cluster
Mekanism enrichment chamber : silver dust (can be smelted)
Mekanism ore tripling and beyond : silver grit (arc furnace)
Mechanical squeezer : 2 silver grit + 1 at 50% chance
IE crusher : 2 silver grit + 1 lead grit at 10% chance

- Lead cluster
Mekanism enrichment chamber : lead dust (can be smelted)
Mekanism ore tripling and beyond : lead grit (arc furnace)
mechanical squeezer : 2 lead grit + 1 at 50% chance
IE crusher : 2 lead grit + 1 silver grit at 10% chance

- Iron cluster
Mekanism enrichment chamber : iron dust (useless)
Mekanism ore tripling and beyond : iron grit (arc furnace)
Mechanical squeezer : 2 iron grit + 1 at 50% chance
AA crusher : 2 iron grit + 1 gold grit at 20% chance
IE crusher : 2 iron grit + 1 nickel grit at 10% chance

- Copper cluster
Mekanism enrichment chamber : copper dust (useless)
Mekanism ore tripling and beyond : copper grit (arc furnace)
Mechanical squeezer : 2 copper grit + 1 at 50% chance
IE crusher : 2 copper grit + 1 gold grit at 10% chance

- Tin cluster
Mekanism ore processing : tin dust (arc furnace)
Mechanical squeezer : 2 tin dust from PrimalCore (useless) + 1 at 50% chance 

- Aluminum cluster
Mekanism enrichment chamber : aluminum grit (arc furnace)
has no Mekanism ore tripling and beyond
has no mechanical squeezer processing

- Nickel cluster
Mekanism enrichment chamber : nickel grit (arc furnace)
has no Mekanism ore tripling and beyond
Mechanical squeezer : 2 nickel grit + 1 at 50% chance
AA crusher : 2 nickel grit + 1 platinum dust at 15% chance
IE crusher : 2 nickel grit + 1 platinum dust at 10% chance

- Platinum cluster
Mekanism enrichment chamber : platinum dust (arc furnace)
has no Mekanism ore tripling and beyond
Mechanical squeezer : 2 platinum dust + 1 at 50% chance
IE crusher : 2 platinum dust + 1 nickel grit at 10% chance

- Uranium cluster
Mekanism enrichment chamber : uranium grit (arc furnace)
IE crusher : 2 uranium grit + 1 lead grit at 10% chance
has no Mekanism ore tripling and beyond
has no mechanical squeezer processing

- Osmium cluster
Mekanism ore processing : osmium dust (arc furnace)
has no mechanical squeezer processing

**Comment by mtjohnson47** [comment]
It does make sense each ore would have a different best method.  That's how it is in the real world.

**Comment by codewarrior0** [comment]
It's arguably a bug that Iron, Copper, and Gold clusters produce a useless dust in the Enrichment Chamber.

**Comment by Rixxaw** [comment]
Nice write-up I came here to post a bug about Iron Ore turning into an un-usable Mekanism Iron Dust and you have already covered it... However I would like to emphasize the confusion from players when they grind ore into 2 dust and then can't do anything with it, using the Mechanism standard ore doubling method.

So Suggestion would be to remove the Mechanism Energized Smelter recipe so players don't accidentally make it.  And to change the Enrichment chamber output to Immersive Engineering Iron / Gold / Copper / dust so that it is usable.

As a balance note.. The crusher has hardly any upgrades and by Age 5 we should possibly be able to upgrade our crusher to an Enrichment Chamber.  Mechanism requires multiple machines to do its ore processing so the Mutli-block concept of the pack isn't really broken IMHO.

**Comment by artdude543** [comment]
Upcoming changes in regards to this issue.

- Mechanical squeezer has **all** ore recipes removed from it and will eventually have no uses.
- All metal ores _(including clusters)_ recipes have been re-done to follow a tech tree. Follow the in-game recipes to see the changes/new machines.
- Resource Ores will be looked at on 3.0.8 and won't have changes in 3.0.7.
- Dimensional Shard now has an IE processing recipe _(temp till 3.0.8)_
- Sulfur Ore has processing recipes.
- Cobalt/Ardite Ore will be looked at later on _(post 3.0.7)_
