### ISSUE TITLE
Torches?

### ISSUE THREAD

**Issue by 92slavik** [Darkosto/SevTech-Ages#1705]
Just a suggestion, can you add torches or tiki torches to the achivements in age 1 or 0? Thanks

**Comment by mtjohnson47** [comment]
Why do you need an achievement for torches?

**Comment by 92slavik** [comment]
Because it didn’t even know I could make torches

**Comment by artdude543** [comment]
I don't feel the need for adding an advancement for torches... You can view all the items you can make/use in JEI as you progress. Once in a blue moon take a second to view it and be amazed at what you can find like torches! 😲
