### ISSUE TITLE
Bug when try to plant something and don't know how to do...

### ISSUE THREAD

**Issue by Fireztonez** [Darkosto/SevTech-Ages#171]
How to reproduce:
Easy, I found a Wild Crop, I remove the plant present (By example carrots), now I have a blank Farm land at front of me, so i right click whit a seed for plant-it... The seed is removed from the shown inventory and I see a message tell me "You don't meet requirement to farm -- [Teach A Man To Farm]". So the crop is not places and the seed is not shown in my inventory...
Where is my seed :o, I pass over 30 sec to find that beautifle seed :'( `!!??`
The answer,......... after the break.. :o sorry I'm not on a TV show....
So the seed is still in the inventory, but is buggy and not visible. For debug the seed we need to go on the inventory window and click on the empty slot and now the seed  is there...

We run on SevTech Alpha 7,
Minecraft v.1.12.2
Forge v.14.23.0.2515

:o and I forgot, Happy Birthday Darkosto!!

FireZtoneZ

**Comment by Darkosto** [comment]
This is actually just a visual bug, you need to update your inventory by opening a chest to see the item again.
