### ISSUE TITLE
Connection Lost

### ISSUE THREAD

**Issue by JC2x** [Darkosto/SevTech-Ages#1710]
## Context
not trying to accomplish anything other then to connect to server.

## Logs

* Client/Server Log:
* Crash Log:

https://gist.github.com/JC2x/b685ae08f7c94dc405251724cf8040ce

## Client Information

* Modpack Version: 3.0.6
* Java Version: 8.161
* Launcher Used: Twitch

* Memory Allocated: 6,400

* Server/LAN/Single Player: _**Editors Note: We don't need IP addresses**_
* Resourcepack Enabled?: no packs
* Optifine Installed?: no

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Soultion:
* Sponge (Non-Vanilla Forge) Server?:

* Additional Content Installed?:

**Comment by PsyberMind** [comment]
I'm getting the same thing in SP as well.. On initial load I get a Connection Closed message..

**Comment by artdude543** [comment]
Try adding `-Dfml.readTimeout=180` to your Java Args and see if that helps.

**Comment by ArbitraryHubris** [comment]
@artdude543 I have this problem every time I log in for the first time to my server.  I'm trying your setting and will let you know.

**Comment by ArbitraryHubris** [comment]
Hmm.  First login, I get the world building around me, and get disconnection (forcibly closed by the remote host with only a player disconnected on server log).  I still have the problem with the new setting.  but it's not that much of an issue, because second join attempt always works

**Comment by ArbitraryHubris** [comment]
do you think it could be gamestages caching?  the point at which it freezes is loading in the world with journeymap deathpoints (which I don't have the stages for yet) and then the world doesn't finish drawing.  The second join flies through this stage and the world redraws without journeymap deathpoints.

**Comment by JMeisterDesign** [comment]
I'm having the exact issue as above with a 2 player server. The first time we login we can see journeymap death beacons and can even walk around in world but not interact with anything. Shortly after joining we both get disconnected. Most of the time we can log back in and have no issues.

Today I'm stuck in a Connection Lost: Disconnected loop where I was able to login the first time, got disconnected like normal, but now no matter when I try afterwards, I don't get a world load at all and just the Connection Lost notice.

**Comment by Flow86** [comment]
happens to me too here on my server. Only happens when no one was connected for a while and the game "needs to wake up" the sleeping chunks? login again always worked.

**Comment by JMeisterDesign** [comment]
I've noticed that the first time logging in, when you expect the disconnect you can mess with your inventory but items beyond stage 0 are shown as "unknown item". Once you log back in you're back to the stage you were at.

**Comment by artdude543** [comment]
We believe we have this solved in 3.0.7. If the issue persists on the next update please re-file an issue (or comment on one which is already open at the time)
