### ISSUE TITLE
Soulforged Steel staged in Age 3, requires End Stone to craft from Age 4.

### ISSUE THREAD

**Issue by SephirothWS** [Darkosto/SevTech-Ages#1711]
## Issue / Bug
Soulforged Steel, and all of its crafting recipes and the likes, are currently staged in Age 3. However, one crucial piece necessary to craft Soulforged Steel in a stoked crucible is Soul Flux, of which can _ONLY_ be obtained using an _Unfamiliar Item_ from Stage 4. That unfamiliar item is obtained by placing End Stone in a Better With Mods Kiln. As End Stone is not accessible at this time, the unfamiliar item is unobtainable. Even so, said unfamiliar item is staged to Age 4.

![Image](https://i.imgur.com/1vGa18G.png)
![Image](https://i.imgur.com/CZrwg2Q.png)
![Image](https://i.imgur.com/OFQzFvj.png)

![Image](https://i.imgur.com/5dCK4jM.png)

## Expected Behavior
Current behavior is due to this staging problem, Soulforged Steel cannot be crafted until Stage 4 despite all of Soulforged Steel and what it can be crafted in to being staged in Stage 3.

## Possible Solution
Create a new method of creating Soul Flux (which is correctly staged to stage 3) which can later on be made "easier" when End Stone is available.

## Steps to Reproduce (for bugs)

1. Unlock Stage 3.
2. Check Recipe for Soulforged Steel.
3. Check what you need for the Soul Flux in the Stoked Crucible tab of JEI.
4. ¯\\\_(ツ)_/¯

## Context
I was wanting to make the Refined Pickaxe (Which has a mining level of Cobalt) so that I can mine and collect Nether Quartz and Obsidian, so that I may use them to continue progressing in the pack.

## Logs

* Client/Server Log: ¯\\\_(ツ)_/¯
* Crash Log: ¯\\\_(ツ)_/¯

## Client Information

* Modpack Version: 3.0.6
* Java Version: Java 8 Update 161
* Launcher Used: TwitchApp

* Memory Allocated: 8GB

* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: Nope
* Optifine Installed?: Nope

**Comment by Skullywag** [comment]
This has changed from 3.0.4 where you needed a soul urn, which you get from having an urn under a filtered hopper and sifting netherrack dust.

**Comment by SephirothWS** [comment]
@Skullywag The soul urn is still part of the recipe.

![Image](https://i.imgur.com/AUMH9dl.png)
![Image](https://i.imgur.com/buC0Ps3.png)
![Image](https://i.imgur.com/Zdl7ASr.png)
![Image](https://i.imgur.com/JS3uK3F.png)

**Comment by Skullywag** [comment]
Ah right you are. My bad.

**Comment by artdude543** [comment]
Soul Flux was removed from the recipe current recipe as of 3.0.7 will be the following 

![image](https://user-images.githubusercontent.com/1885466/39197371-349c8c80-47dc-11e8-8caa-3319267d97a2.png)

Thus making the steel craftable in the age :)

**Comment by Graeter2** [comment]
![2018-06-01_18 39 35](https://user-images.githubusercontent.com/29971130/40870466-8cc76b16-65cb-11e8-87db-071599adb982.png)
![2018-06-01_18 39 50](https://user-images.githubusercontent.com/29971130/40870467-8ce6982e-65cb-11e8-8ef9-e79e5e2ad026.png)

Unable to produce soulforged steel, tried charcoal dust and coal dust as JEI shows, using version 3.0.7, is this related to this fix?

a 3x3 Hibachi setup and a T shaped hibachi setup (in ss) would not work.
