### ISSUE TITLE
[Request] Processing options for PrimalCore salt blocks?

### ISSUE THREAD

**Issue by MrHrulgin** [Darkosto/SevTech-Ages#1717]
## Issue / Bug
Silk touching Netjry, Halite or Fire Salt blocks gives the block, but Netjry salt can only be broken down to usable salt in the horse grindstone, and the other two are only breakable by hand.
 
## Expected Behavior
I would expect that the salt blocks would be able to be converted into usable salt using at least some of the existing methods that other ores are crushed.

## Possible Solution
Add processing recipes for all salt blocks into the crusher, and other mod structures as possible.

## Context
I was mining out a salt flat to prepare for brine manufacturing, and found that the blocks were unusable.

**Comment by artdude543** [comment]
I've added IE Crusher recipes for the time being for the blocks. This will be included in the next release. 🙂
