### ISSUE TITLE
[Bug] Losing AbyssalCraft Knowledge Upon Leaving End

### ISSUE THREAD

**Issue by TibbersTeaParty** [Darkosto/SevTech-Ages#1718]
**## Issue / Bug**
Whenever you enter the end and then leave; you lose the knowledge that you have obtained through Abyssalcraft. It makes items throughout Abyssalcraft have the "Runic" text.  This issue makes it rather difficult to traverse further into the AbyssalCraft mod itself. 

**## Expected Behavior**
Keeping the progression and knowledge of your progression through the AbyssalCraft mod

**## Steps to Reproduce (for bugs)**
1. Enter the End
2. Leave the End either through death or portal
3. Look at items in AbyssalCraft ie. Shadow Gems, Staff Of Rending

**## Context**
Effects the progression through Abyssalcraft as when the knowledge of items is completely wiped it makes the progression through the mod rather difficult. 

**## Client Information**

* Modpack Version: 3.0.6
* Java Version: 1.8.0.162
* Launcher Used: Native Launcher

* Memory Allocated: 8GB

* Server/LAN/Single Player: Server
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by FaustyTheRager** [comment]
I am having the same issue, please fix this soon.

**Comment by thedoo** [comment]
FYI, I believe this is fixed in the latest Abyssalcraft release, 1.9.4.9
