### ISSUE TITLE
Clay Kiln disappeared

### ISSUE THREAD

**Issue by Fireztonez** [Darkosto/SevTech-Ages#172]
I try to make a Fired Klay Kiln, to strat to cook a things, and when I try to start fire under the Clay Kiln disappeared completly. I didn't get back clay or anything else.

What I do, is exacly the setup on that image:
![clay-kiln fire-stick](https://user-images.githubusercontent.com/19277301/32408663-694d1bde-c172-11e7-8807-e920cca90908.jpg)

I hae a stick bundle in the flore 1 block bellow the kiln and I try to turn the stick bundle in fire... I hear the sound like if the fire start, but I see no fire, and the kiln disappeared... I try a secound time to try to reproduce the bug and that look to do every time...

SevTech: Alpha 7
Minecraft: 1.12.2
Forge: 14.23.0.2515

FireZtoneZ

**Comment by Darkosto** [comment]
Confirmed, is a bug. It looks like the fire overwrites the kiln 

@vadis365

**Comment by vadis365** [comment]
never intended to be used with the block you are trying to set fire to - it is a half block and you are not leaving a 1 block gap between it and the kiln.

**Comment by vadis365** [comment]
re-opened because Dark is a baby

**Comment by Darkosto** [comment]
![image](https://user-images.githubusercontent.com/10309699/32634923-0369a4c8-c57c-11e7-9b7f-9d435b508a0f.png)

**Comment by vadis365** [comment]
![baby santa](https://user-images.githubusercontent.com/6518708/32635139-e3164c96-c5a6-11e7-95d7-52131c3c00ff.png)

**Comment by Darkosto** [comment]
THIS GUY

**Comment by DaedalusGame** [comment]
![thisguy2](https://user-images.githubusercontent.com/9559216/32635300-0095851c-c5b0-11e7-90da-4277c574c5f0.png)

**Comment by Fireztonez** [comment]
So, that bug will be fixed??
