### ISSUE TITLE
Using Inventory sort with RS Grid open also moves hotbar items. 

### ISSUE THREAD

**Issue by Dystilled** [Darkosto/SevTech-Ages#1721]
## Issue / Bug
When you have an RS Grid open and use the sort inventory key (i.e middle mouse) it will sort your inventory but also change items on your hotbar

## Expected Behavior
Should not change hotbar items. 

## Possible Solution
???

## Steps to Reproduce (for bugs)
Open RS Grid with items on hotbar and in inventory. 
Sort Inventory. 
Hotbar items will switch

## Context
Disrupts game play. 

## Client Information

* Modpack Version: 0.6
* Java Version: Latest
* Launcher Used: Twitch Java

* Memory Allocated: 12gb

* Server/LAN/Single Player: SP
* Resourcepack Enabled?: Soartex
* Optifine Installed?: Yes

**Comment by artdude543** [comment]
This is not a pack bug but a mod interaction issue. If feel it should be fixed please log an issue with the RS guys 😄
