### ISSUE TITLE
Better with mods manual awarded randomly for no reason

### ISSUE THREAD

**Issue by Dystilled** [Darkosto/SevTech-Ages#1724]
#981 - Closed as fixed but isn't
 
## Issue / Bug
Randomly awarded BWM manual when crafting BWM items. Doesn't happen all the time but I've received at least 6 of them since 0.3

## Expected Behavior
Should only ever be awarded 1 

## Possible Solution
???

## Steps to Reproduce (for bugs)
Craft BWM item such as thatch, random chance of being awarded the manual. 

## Context
Annoyance. 

## Client Information

* Modpack Version: 0.6
* Java Version: Latest
* Launcher Used: Twitch Java

* Memory Allocated: 12gb

* Server/LAN/Single Player: SP
* Resourcepack Enabled?: Soartex
* Optifine Installed?: Yes

**Comment by artdude543** [comment]
Yeah, I noticed this last night while playing. @DaedalusGame it seems this is still an issue in version 2.0.34 I got a book after my first craft and then after using the cauldron to make glue. Same with the OP getting multiple books.

**Comment by JustHeyo** [comment]
I've seen this myself in my 3.06 server play.  I currently have three copies of the book; it's possible that you get one when making the cauldron as well as the other 'first machine' blocks from the mod; it should likely detect if you've already 'achieved a free copy' before awarding another.

**Comment by DaedalusGame** [comment]
It does, but in 3.0.6 it reset when you changed dimensions, now it should only reset if a portal is implemented poorly.

**Comment by artdude543** [comment]
We have disabled the manual being given to the player via the config. You will get a manual for an advancement instead.
