### ISSUE TITLE
Hellfire Forge - not crafting Sigils. Since the update to 3.0.6 it appears that we cant craft at least theSigil of Holding, and The Sigil of Fast mining in the Hellfire Forge.

### ISSUE THREAD

**Issue by 0Chameleon0** [Darkosto/SevTech-Ages#1725]
## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:

* Memory Allocated:

* Server/LAN/Single Player:
* Resourcepack Enabled?:
* Optifine Installed?:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Soultion:
* Sponge (Non-Vanilla Forge) Server?:

* Additional Content Installed?:

**Comment by artdude543** [comment]
Right as you blatantly ignore the template I'm closing this. If you want to report an issue use the template we provide and fill **all** the relevant information!
