### ISSUE TITLE
[Advancement] Coal Engine Progress Mishap

### ISSUE THREAD

**Issue by Serolar** [Darkosto/SevTech-Ages#173]
The Steve's Carts part needed to progress to stage 3 is called Tiny Coal Engine(Incorrect) has a meta data of 44, while the Coal Engine(Correct) has a metadata of 0. 

Simply changing the requirement ("stevescarts:cartmodule", 44) to ("stevescarts:cartmodule", 0) should solve it.

Thanks for spotting this,
Serolar

**Comment by Darkosto** [comment]
All fixed up! Thanks!
