### ISSUE TITLE
Block breaking animation using wrong textures

### ISSUE THREAD

**Issue by Xephyrious** [Darkosto/SevTech-Ages#1730]
## Issue / Bug

Loaded a new world, went to break a block of dirt and noticed the usual "cracking" textures were replaced by a bunch of what seem like block textures overlayed across the block instead (the same strange textures appear in the same order everytime). Problem persists after reloading the world or reloading Minecraft. Happens with every block.
## Expected Behavior

Normal "cracking" block breaking textures
## Steps to Reproduce (for bugs)

1. Launch SevTech Ages via Twitch Launcher
2. Open New/Existing World
3. Break Block
4. ???
5. Profit

## Context

This occurs with every block I try to break. It's very distracting.
## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 3.0.6
* Java Version: Java 8 ver. 161
* Launcher Used: Twitch

* Memory Allocated: 4096 MB

* Server/LAN/Single Player:
* Resourcepack Enabled?:
* Optifine Installed?:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Soultion:
* Sponge (Non-Vanilla Forge) Server?:

* Additional Content Installed?:

**Comment by artdude543** [comment]
If you enabled/disable an RP or Shaders you need to reload the entire game which causes this issue. Any kind of change to the loaded resources in the game causes this bug. It's not fixable as current but performing a reboot after making a change will fix the issue you are getting.

It's also mentioned in the in-game guide about the pack.
