### ISSUE TITLE
Eating Canned Food (Galacticraft) eating last of stack causing crash

### ISSUE THREAD

**Issue by Dystilled** [Darkosto/SevTech-Ages#1732]
## Issue / Bug
Eating canned food, if it is the last of a stack and it auto pulls a new type to the bar, can cause a crash. 

## Expected Behavior
Game Crashes to desktop

## Steps to Reproduce (for bugs)
Have 2 type of canned food, one in hot bar one in inventory
Eat last of a stack 
Crash may occur. 

## Context
Disruptive, Annoying 

## Logs
https://pastebin.com/cTS9uuLE

## Client Information

* Modpack Version: 0.6
* Java Version: latest
* Launcher Used: Twitch Java

* Memory Allocated: 12gb

* Server/LAN/Single Player: SP
* Resourcepack Enabled?: Soartex
* Optifine Installed?: Yes

**Comment by artdude543** [comment]
Fixed in next version 3.0.7
