### ISSUE TITLE
Quarries do not recognize ores

### ISSUE THREAD

**Issue by TWJedi** [Darkosto/SevTech-Ages#1733]
The RFTools Builder with a quarry card does not recognize most ores. It simply sees them as cobblestone (if in the overworld) or low-grade charcoal (if in the nether). This is true for both the default and silk touch quarry cards. I also briefly tested the Buildcraft quarry, same results.

I tested all Geolysis ores, AA Black Quartz, Contenttweaker Aquamarine, and various Galacticraft/Extra Planet ores (Silicon and a handful of other planets).

The only ores that the builder recognizes are the NetherEx ores (Amethyst and Quartz variants) and Galactricraft ores (it does NOT recognize Silicon, however). 

The quarries do **not** recognize any of the following:

- Geolysis ores
- Galacticraft Silicon (it does recognize ores from other planets)
- AA Black Quartz
- Contenttweaker Aquamarine
- Tinkers Construct Cobalt or Ardite
- Nether Quartz (it does recognize the NetherEx variants)

I'm guessing that the issue is with the mod that "hides" ores in earlier ages.

Screenshots: https://imgur.com/a/Rsuc5

This was all tested in version 3.0.6 in age 5.

**Comment by togreglove** [comment]
Aren't the quarries set to only work in space?

**Comment by Vyraal1** [comment]
This is intended, quarries are fake players that don't have the correct stage, so any staged ore cannot be quarried, the most notable exception to these are the galaticcraft and extra planet ores, as they aren't staged.

**Comment by afdw** [comment]
Apparently BuildCraft blocks use fake player with GameProfile set to one of the player who placed this block for breaking blocks. So it should be possible to detect that in mod that provides staged ores.

**Comment by Jandakast** [comment]
This is intended behavior. Quarries are used to clear areas in the Overworld or gather resources in harsh environments like on the moon. Although some Fake Players have a GameProfile they do not grab/have any game stage data and thus cannot see or mine any resources that are hidden behind stages. 

Should we add a tool-tip that states "Only mines ores on planets other than Earth" to the Build Craft Quarry and all of the RFtools Quarry cards?

**Comment by TWJedi** [comment]
I guess I'm more relieved than anything that this is intentional and not a bug, although a bit disappointed as well. We have access to the Void Ore Miner in the same age, which is far more powerful, in my opinion. But if it is simply a technical impossibility, I understand.

> Should we add a tool-tip that states "Only mines ores on planets other than Earth" to the Build Craft Quarry and all of the RFtools Quarry cards?

That sounds fine.

**Comment by AlexIIL** [comment]
> @Jandakast: Although some Fake Players have a GameProfile they do not grab/have any game stage data and thus cannot see or mine any resources that are hidden behind stages.

How would BuildCraft get game stage data? Would it be possible for the game stage mod to grab the relevant data from wherever it stores the real player data with the fake player's UUID?

**Comment by justinrusso** [comment]
@darkhax Do you have any suggestion on this for @AlexIIL ?

**Comment by justinrusso** [comment]
Cant do anything about this
