### ISSUE TITLE
[Request] Mid game Clay block recipe

### ISSUE THREAD

**Issue by theawfullwaffle** [Darkosto/SevTech-Ages#1734]
## Request
Currently the options for creating Clay blocks consist of using the Press from Horse Power, Starlight Infuser or Lens transmutation from Astral Sorcery, Silk Touch tools, or tech that is too advanced for ages 3 and 4. As the level of Technology/Magic increases I would imagine there should be an easier way to obtain blocks of clay without having to resort to Silk Touch.

## Possible Solution
Consider adding a recipe to the Immersive Engineering Metal Press using the 2x2 packing plate and inserting 4 clay balls. This would fill a gap in ages 3 and 4 for producing Clay blocks through higher technological means before you would have access to Environmental Tech mining or Mekanism Chemical Injection Chambers in age 5.

Thanks for your consideration

**Comment by Targren** [comment]
Age 3 also has the Compacting Drawer from Storage Drawers.

**Comment by artdude543** [comment]
I've added a Metal Press recipe for the clay block just as a QOL. Will be in the next release.
