### ISSUE TITLE
No sound.  I tried reloading game a couple times, and i tried reloading with F3 T a couple times.  Neither worked 

### ISSUE THREAD

**Issue by gaudet21** [Darkosto/SevTech-Ages#1735]
## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:

* Memory Allocated:

* Server/LAN/Single Player:
* Resourcepack Enabled?:
* Optifine Installed?:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Soultion:
* Sponge (Non-Vanilla Forge) Server?:

* Additional Content Installed?:

**Comment by artdude543** [comment]
Closing as you ignore the entire issue template. If you want to send us an actual bug report use the template. Otherwise, you'll be ignored, thanks!
