### ISSUE TITLE
Low Priority Issue: Chisel Marble is found when mining, but astral sorcery structures require astral marble

### ISSUE THREAD

**Issue by ArbitraryHubris** [Darkosto/SevTech-Ages#1737]
I made my Celestial Altar according to instructions and received a red bar when looking at the altar.  Turns out that I was using 12 chisel marble, instead of 12 astral marble.  Should the pack only generate astral marble, should the advancements be modified to warn about this, or should an issue be filed with Astral Sorcery devs to ask them to use oredict marble?

This was very frustrating, but not necessarily a pack issue.

**Comment by tomm2000** [comment]
Use chisel to convert chisel marble to astral marble

**Comment by ArbitraryHubris** [comment]
Definitely, @tomm2000.  I reported it as an "issue" because I think this will be a stumping point for people.  It's a non-obvious problem when you think you're following directions in the astral guide and using the plain marble that you dug up.

**Comment by Jandakast** [comment]
This is how the mod works. Astral Sorcery depends on their different types of marble in specific arrangements to detect the structures and only accepts Astral Sorcery marble. I think it is reasonable to require players to process all marble that will be used for Astral Sorcery structures. 

Adding a tool-tip to marble from the Chisel Mod may be more confusing and the Astral Sorcery advancements already have a lot of text attached to them. Adding more information will need to be evaluated. Personally I think it is fine the way it is.

**Comment by ArbitraryHubris** [comment]
I don't feel strongly about it.  The main issue is that you have ZERO idea why it's not working.  I obviously have it figured now so it no longer impacts me.
