### ISSUE TITLE
Gunpowder insertion into Embers Exchange Table has a strange behavior

### ISSUE THREAD

**Issue by MongoTheElder** [Darkosto/SevTech-Ages#174]
When inserting gunpowder into the side of an Embers Exchange Table to make Ember Crystal Clusters, the gunpowder is placed on the ground next to the table instead of being placed in the table.
To get gunpowder into the table, something must be placed next to the table to block gunpowder from being placed on the ground.

Alpha 7

**Comment by Darkosto** [comment]
I just tried this, but couldn't replicate. It might have been fixed between updates. Can you check again with Alpha 8 and let me know if it still happens? :)

**Comment by Darkosto** [comment]
Unless I'm not replicating correctly, this looks good on my end. Let me know if this is still happening.
