### ISSUE TITLE
Dupe bug with filtered hopper from better with mods

### ISSUE THREAD

**Issue by daRussianman** [Darkosto/SevTech-Ages#1740]
Happens when you do not have a urn below the hopper and the hopper breaks while having the inventory open. Hopper drops items that were in side while you are able to pull from the inventory of the block which dupes whatever items were in the hopper.

Below is an example of it in practice.
https://imgur.com/a/WVvVQ

* Modpack Version: 3.0.6
* Java Version: 1.8.0.161
* Launcher Used: Twitch

**Comment by DaedalusGame** [comment]
fixed in dev on our side

**Comment by artdude543** [comment]
Fixed on next update 3.0.7
