### ISSUE TITLE
Are EmberRoot Zoo Golems supposed to spawn?

### ISSUE THREAD

**Issue by taiyoko** [Darkosto/SevTech-Ages#1746]
## Issue / Bug
I'm unsure if the golems from EmberRoot Zoo are intended to be spawning, as they are not on the lists in the various configs. They're especially painful when you're still in Age Zero/One and don't have much armor or damage output and their magical attack goes right through the stone shield.

## Possible Solution
Possibly change to have them unlock in later stages or blacklist entirely.

## Client Information
* Modpack Version: 3.0.6
* Java Version: 8 build 161
* Launcher Used: Twitch
* Memory Allocated: 4 GB
* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: None
* Optifine Installed?: No

**Comment by Dystilled** [comment]
Just as advice for dealing with them. 
Their ranged attack is veeeeeeery easily avoidable. 
Strafe and hit them and they're no issue.

**Comment by Darkosto** [comment]
Yes, they are 100% intended to spawn. Their attacks are easily avoidable if you don't try and brute force them or use the worldgen to your advantage.
