### ISSUE TITLE
Stuck on Lightwell quest due to stage 3 pan cast requirement

### ISSUE THREAD

**Issue by hossumquat** [Darkosto/SevTech-Ages#1747]
Lightwell is crafted in Luminus crafting table, but to do that I need a resonating wand, which requires an ender pearl, which requires casting molten ender pearl into a pan cast, but the pan pattern is an "unrecognized item" requiring stage 3.  I can make a stone pan with it but it is also an unrecognized item and as such I can't put it in the casting table to make a cast.  So with no way to make an ender pearl, I cannot advanced past this quest to get to age 3.  Am I missing something here or is this a bug?

**Comment by Zarathaen** [comment]
There are two patterns that look like a pan - one is a part for the yoyo, which requires stage 3 to use. I had an issue because I didn't realize this during stage 2. This could be what you're seeing.

**Comment by Vyraal1** [comment]
![image](https://user-images.githubusercontent.com/26587049/38653451-d4b6a542-3dd8-11e8-9157-30faaf1583e5.png)
Pan cast is in Stage two

**Comment by Phantum** [comment]
pan cast is the bigger one, I did the same thing, even went as far as to use a hopper to put the cast in the casting table XD

**Comment by hossumquat** [comment]
Wow, ya, I got the yoyo pattern confused with the pan pattern.  Now I feel stupid.  Thanks for straightening that out for me.
