### ISSUE TITLE
Backpack Crafting in Age 0

### ISSUE THREAD

**Issue by Sannestia** [Darkosto/SevTech-Ages#1748]
I am currently in age 0. I have mk1 and mk2 crafting tables in the game. I looked up the backpack which is the starter with 7 leather, 1 chest, and 1 leather cordage and tried to craft it in the mk2 crafting grid. I wasn't able to actually craft it it just didn't work. I then switched and put the recipe in the mk1 crafting grid and it crafted immediately.

I figure this is a bug in general, but I didn't see anyone else report it. I just wanted to let you know even though it is a super minor bug. 

Thank you for your time! 
Sannestia

**Comment by Toksyuryel** [comment]
Did you have the recipe oriented correctly? Keep in mind that the side of the work stump with the crafting rock storage is the "front" of the table.

**Comment by Sannestia** [comment]
Yes I did have it oriented correctly and was at the front of the table when putting the recipe in.

**Comment by artdude543** [comment]
I had this work just fine. The orientation does matter with the tables and I managed to craft using both tables. I'm going to close this as you managed to craft one and that the issue can't be reproduced.
