### ISSUE TITLE
Suggestion: Add more advancements between Exchange Rate and Clustered in Stage 2

### ISSUE THREAD

**Issue by MongoTheElder** [Darkosto/SevTech-Ages#175]
There is a large progression gap between making an Exchange Table and all the components needed to make Ember Crystal Clusters. For example, a Stamper to make Ash Piles and Aspecti, the Beam Cannon, and Alchemy Pedestals to hold the reactants. It took a lot of research to find how these items were to be used in conjunction with each other to make clusters. Combined with all the experimentation necessary to identify the correct levels of ash made this a very frustrating progression line. The Cinder Plinth is not available yet to manufacture ash piles at a decent rate so you are left with stamping alchemical waste and you need a lot of ash to successfully make the cluster needed for the smeltery controller.

From the recipes for the Stamper and Stamper Base, it looks like these were intended to be part of Stage 1 progression.

Alpha 7

**Comment by Darkosto** [comment]
Sure! I can add these :) Thank you.

**Comment by Darkosto** [comment]
Added in, thank you!
