### ISSUE TITLE
Galacticraft Machine Recipes- Nonsensical recipe limitations. 

### ISSUE THREAD

**Issue by Dystilled** [Darkosto/SevTech-Ages#1750]
## Issue / Bug
Colour variants of the heavy tank do not work for the recipes

## Expected Behavior
Makes no sense, they're exactly the same items, any colour should work. 

## Possible Solution
Make colour variants also work. 

## Context
Nonsensical recipe limitation, items are identical.

**Comment by MJRLegends** [comment]
The texture colour are different, so the recipe should use dye related to the texture colour

**Comment by justinrusso** [comment]
This seems to be fine in dev. Please submit a new issue if the issue persists in 3.0.7.
