### ISSUE TITLE
Creating a single person creative game doesn't give all item access

### ISSUE THREAD

**Issue by Sorbe** [Darkosto/SevTech-Ages#1752]
I created a series of recurrent complex structures in a new creative mode world.

While creative was indeed set, the ages mechanism was still limiting access to most items.
To get around this I gave myself all achievements -- this took a long time to complete (minutes),
It also crashed at least once trying to complete this update/notification process.

Surely this must be a better way to harmonize creative mode games and ages?

**Comment by iskorp** [comment]
There is a command to give all advancements...

**Comment by artdude543** [comment]
The command above will give you all the advancements. It will also crash/close the game to menu due to how much you are running at once. This is something which would never be fixable due to the Minecraft Vanilla logic.

**Comment by Iorce** [comment]
Some items are staged behind "creative_unused" and cannot be found in JEI (for example the Blood Magic Creative Activation Crystal). Is there a way to unlock these items, too?
