### ISSUE TITLE
Suggestion: Add cedar wood slabs and stairs etc. [Totemic Mod]

### ISSUE THREAD

**Issue by TheCaptainClown** [Darkosto/SevTech-Ages#1754]
"Suggestion: Add cedar wood slabs and stairs etc. [Totemic Mod]"

**Comment by Darkosto** [comment]
This would be an issue to go on the Totemic issue tracker, this is not something we can just add in the pack without the mod adding it. As much as I would love to relay every idea brought up in this tracker, I do not have the time. Feel free to request it here: https://github.com/TeamTotemic/Totemic/issues
