### ISSUE TITLE
[Recipes] Crystalline Ember "Duplication"

### ISSUE THREAD

**Issue by Serolar** [Darkosto/SevTech-Ages#176]
Problems: 9 Ember Shards can be pressed into an Ember Crystal, while 6 Shards can be crafted into an Ember Crystal. An Ember Crystal can be ground into 9 Shards, and crafted into 6 Shards.
This can be a vicious cycle of duplication, or nullification. 
Solutions: Either A. The press, grindstone, and mill stone need to produce or require 6, or B. The crafting recipe needs removed, or C. Both, to stay true to the pack and the mod. 
These are just the options I came up with.

Thank you for your time,
Serolar

**Comment by Darkosto** [comment]
Fixed, they shouldn't have grid recipes anyways. Thanks!
