### ISSUE TITLE
3.0.5 Abyssalnite Dust processing

### ISSUE THREAD

**Issue by sqwizzlnoots** [Darkosto/SevTech-Ages#1761]
I'm not sure if it is intentional, but the Abyssalcraft abyssalnite dust cannot be smelted in a smeltery.

**Comment by iskorp** [comment]
None of the dusts can, use arc furnace.

**Comment by justinrusso** [comment]
As @iskorp said, dusts are not to be meant to be turned into an ingot until the arc furnace. Until then, the item is intended to exist for recipes that may require a dust.
