### ISSUE TITLE
Cyclic Block Placer not placing nether sludge

### ISSUE THREAD

**Issue by romiro** [Darkosto/SevTech-Ages#1763]
## Issue / Bug
When using the block placer doesn't work with nether sludge in a couple of observed ways: 
You can't manually add it to the placer via dragging it to the inventory via mouse; the inventory slot won't accept it. Confirmed that it accepts oak planks and regular cobble.
If you force the sludge in via hopper, it still won't place. Feeding cobble and planks into the placer will place those blocks, as long as sludge is not in a slot before them.

## Expected Behavior
Block placer places the sludge for nether brick automation in the BWM kiln

## Steps to Reproduce (for bugs)
(see above)

## Context
This was an attempt to automate nether brick creation after an hour of poring over what's available through JEI. As this isn't working, I believe I'm stuck with either resorting to a click-script to right click in the sludge while I AFK, or another placer method that I'm not aware of.

## Client Information

* Modpack Version: 3.0.6
* Java Version: 8, Windows, manually updated yesterday for IE manual bug
* Launcher Used: Twitch

* Memory Allocated: 8gb

**Comment by Lewdicolo** [comment]
I've been told that the BWM Block Dispenser can automate nether bricks/sludge. Haven't tried it out yet though

**Comment by artdude543** [comment]
Fixed in 3.0.7
