### ISSUE TITLE
Sigil of Magnetism Crash/Can't log back into "Server"

### ISSUE THREAD

**Issue by Critek86** [Darkosto/SevTech-Ages#1764]
## Issue / Bug
Created a Sigil of Magnetism. On use, booted from the game. Unable to log back into the server.
First time I had this issue, I was using the Sigil of Magnetism from within a Sigil of Holding. Also crashes when just using the Sigil of Magnetism by it's self.

## Possible Solution
I had to remove the Blood Magic mod and load the server/log in. Then re-add the mod in order to be able to play again. This is not a fix, but may help "let you play" if anyone else is currently having the issue for now. You do lose all progess made in Blood Magic ofcourse. =( 

## Steps to Reproduce (for bugs)

1. Create a Sigil of Magnetism
2. Shift + Right Click to activate the Sigil
3. Crash and can no longer join server

## Logs

* Client/Server Log:
* Crash Log: https://pastebin.com/LGwwCgm9

## Client Information

* Modpack Version: 3.0.6
* Java Version: 1.8.0_161
* Launcher Used: Twitch Launcher

* Memory Allocated: 8G

* Server/LAN/Single Player: Server
* Resourcepack Enabled?: Yes
* Optifine Installed?: Yes

## Server Information
* Java Version: 1.8.0_161
* Operating System: Windows 10
* Hoster/Hosting Soultion: Self Hosted
* Sponge (Non-Vanilla Forge) Server?: No

* Additional Content Installed?: No

**Comment by artdude543** [comment]
This is related to #1557 and fixed in dev.
