### ISSUE TITLE
[SUGGESTION/REQUEST] PLEASE, for the love of everything you hold dear

### ISSUE THREAD

**Issue by 100in33** [Darkosto/SevTech-Ages#1765]
I plead, PLEASE disable the horrible sounds that come out of Better With Mods Mill Stone when it grinds Netherrack. There is just no good reason why it should be there. I literally just scared my entire family half to death, but even if that didn't happen, the FIRST thing I did was wanted to just close Minecraft. And I rarely have that feeling. Thanks for your consideration.

**Comment by Jandakast** [comment]
This is a request that needs to be made to the Better With Mods developer. However, as 3jlowes suggested you can use a sound muffler. The Super Sound Muffler can be crafted in Stage two and allows you to whitelist/blacklist specific sounds. Also can be turned into a bauble to blacklist sounds while you are on the move.
