### ISSUE TITLE
Mod request/addition/sugestion

### ISSUE THREAD

**Issue by gbusrt** [Darkosto/SevTech-Ages#1769]
daerkosto though of a mod request, could we get grass paths/roads "builder" to make getting around easer, you know build road crew (block) then feed it and you get 100 to 1000 blocks strait road built
built
i had a devil of a time finding wild dogs for the boots and had to build a path over 1000 blocks to get to a iron deposit

**Comment by 3jlowes** [comment]
Why did you build a path to an iron deposit?

**Comment by gbusrt** [comment]
i was exploring and the deposits were 20 to 100+ chunks away

**Comment by gbusrt** [comment]
t
