### ISSUE TITLE
Clay Duplication

### ISSUE THREAD

**Issue by Kaelthalon** [Darkosto/SevTech-Ages#177]
Right-clicking the ground with clay in hand creates a clay brick-like block on the ground, but consumes no clay doing so. Breaking it returns 1 clay. I posted a gif in the Discord showing the bug. I'm not entirely sure which mod is causing the issue, but I would assume ImmersiveCraft?

I am on SevTech version Alpha7Twitch
Minecraft Version 1.12.2
Forge Version 14.23.0.2515

**Comment by ALongStringOfNumbers** [comment]
Better with Mods I believe

**Comment by Darkosto** [comment]
This was fixed up in a version after Alpha 7, shouldn't be a problem any more! Thanks!
