### ISSUE TITLE
Better With Mods Bellows conflicting with Carry On

### ISSUE THREAD

**Issue by Dutchs** [Darkosto/SevTech-Ages#1770]
## Issue / Bug
Better With Mods Bellows rotate with empty hand conflicts with Carry On pickup block.
Same issue as #1178 but seems it was overlooked.

## Possible Solution
Add to Carry On blacklist: betterwithmods:bellows

## Client Information
* Modpack Version: 3.0.6

**Comment by Ozzymud** [comment]
As a workaround until then, any block you need to shift right click on you can just step back and be out of range for carry-on but still in range of the block to interact.

**Comment by esotericist** [comment]
Why not just bind carryon to right shift instead of left shift? It solves a lot of these problems.
