### ISSUE TITLE
Starmetal Ore from Iron Ore

### ISSUE THREAD

**Issue by Rixxaw** [Darkosto/SevTech-Ages#1771]
I have been building up my Astral Sorcery to get to a point where I could convert Iron Ore to Star metal, but have been told that it is disabled.  I feel the infrastructure required to convert Iron Ore to Star Metal is quite exhaustive, and would like to know where to change the setting in the config.  Maybe I'm just doing it incorrectly, but as you can see it takes a lot of infrastructure to be able to link a crafted floating crystal to iron ore.

![2018-04-12_14 17 05](https://user-images.githubusercontent.com/17864718/38700105-9ac50716-3e5f-11e8-9909-824981cef992.png)
![2018-04-12_14 16 32](https://user-images.githubusercontent.com/17864718/38700112-a0812f40-3e5f-11e8-81c6-358d20858a81.png)

**Comment by iskorp** [comment]
It’s probably because you only need bare minimum for astral to proceed the quest line. Some of the tools you can get with astral is OP and should be gated even further imo..

**Comment by Rixxaw** [comment]
Yeah I suppose there could be reasons, that is why I have posted this here.  If there are reasons to disable it then thats fine, can someone show me where to re-enable it?  I feel that for my own playthrough I have definitely put forth enough effort to be rewarded with the ability to create star metal.  And I already have the infused crystal sword, with evorcio perks and 1 shot most mobs, so its not like this will make me more deadly.  I simply want to explore Astral Sorcery and a large portion of the mod is about creating a collector crystal Where you want it so you don't have to run to the temple to use the in world generated ones.  So I have done the necessary things to be able to do this and its not working.  So its either a bug or disabled.  IF its a bug lets fix it.  If its disabled then how can I re-enable it or might I suggest an enhancement to the modpack to allow players to explore the mod as it was intended.

**Comment by Wipperwill** [comment]
I get that, but why is the Stardust, starmetal ingot, and starmetal ore so damn hard to get?

The only way to get Ore takes 2 Stardust.
The only way (in stage 2) to get stardust takes either Ore or and ingot.
The only way to get an ingot uses Ore.

The only place in the world i can find any of these are the samples for Rock crystals give 1 Stardust.

Am I missing a recipe somehow?

**Comment by Rixxaw** [comment]
I saw the same thing @Wipperwill and I assumed that I was supposed to advance in Astral enough to make a Collector crystal.  I hadn't needed to do that before because you have the in world ones, and you don't need that much metal.  However in this pack I felt that the lack of easy progression into much more powerful mods like Redstone Arsenal and the like would give me a great opportunity to really play with Astral and see what it can do.  You often discover great hidden nuggets when you fully explore a mod.  However in its current state I'm concerned that I will progress to some recipe that requires a decent amount of star metal and there would be no easy way to get it so I'm hesitant to proceed in building Astral with the mod essentially stunted at this somewhat important point of needing a resource that can take days to find.  I understand some people find it rather easily and that Darkosto has modified the tables so it will be more abundant in generation.  That being said I spent 8 hours looking yesterday and found zero new chunks with rock crystal, so thats why I posted it.

**Comment by Rixxaw** [comment]
Its a balance issue.  I'm only in Age 3 so I can't really say if later on there are things that would be made easier by allowing collector crystal crafting.  Darkosto did add a new recipe for starmetal dust today in the upcoming version to somewhat address these issues.  I have worked around the dust issue myself by converting all my rock crystals into celestial and getting doubles of my dust from it.

**Comment by Wipperwill** [comment]
Thank you

**Comment by TWJedi** [comment]
You can create new starmetal dust by transforming your regular rock crystals into celestial crystals. The transformation itself requires 1 dust, but if you mine the celestial crystal when it is fully mature, it will always return at least 2 dust.

You can also infuse Quartz dust into Starmetal dust.

**Comment by Jandakast** [comment]
I personally don't see an issue with the way things are currently configured. You have ways of "generating" the Stardust that is used to get Starmetal Ore. You also get a ton of rock crystals in a single vein. Like most things, as you progress in stages you unlock better ways of crafting/finding the items you need.

**Comment by Rixxaw** [comment]
Yeah I think I just found one reason it is gated.  Celestial Gateways.  If we have easy access to Star Metal and Dust then fast travel with gateways would remove the need to craft the flying machines and such.  I have never used a celestial gateway but I normally have super powerful jetpacks.  I might go ahead and create some to use as elevators around my base however.

![image](https://user-images.githubusercontent.com/17864718/38735184-b328b2ce-3eed-11e8-8d22-b95294a283af.png)

**Comment by justinrusso** [comment]
Didn't see there was another issue about this. Fixed in dev.

Reference https://github.com/Darkosto/SevTech-Ages/issues/1792 as well about this issue.
