### ISSUE TITLE
Fallen Meteors

### ISSUE THREAD

**Issue by pennyvise1** [Darkosto/SevTech-Ages#1772]
I managed to grind the required meteoric iron out to craft the tier 2 rocket in 3.0.5 then after a rocket explosion I went back to the moon in 3.0.6 and spent 2 hours trying to locate another fallen meteor with no luck, I dont know if aqcuiring meteoric iron was changed but meteors were no longer spawning.

**Comment by Dystilled** [comment]
Definitely spawning in 0.6, mined all mine since the update. 

The spawn rate as has always been the case with Galacticraft is inconsistent and crap

**Comment by justinrusso** [comment]
Tested and we can't reproduce.
