### ISSUE TITLE
Server console spam

### ISSUE THREAD

**Issue by JoramD0** [Darkosto/SevTech-Ages#1774]
## Issue / Bug
Server seems to be spamming "0.0" continuously but does not show it in logs. If trying to type it will just remove the text (as if executed and moved down the log). It seems to be coming and going at times (no clue what I do).

## Steps to Reproduce (for bugs)

I do not know what is causing the issue.

## Context
Trying to use console commands (OP someone and close the server)

## Logs

* Client/Server Log: https://gist.github.com/JoramD0/6b92374897256070568a8c006fba456d
* Crash Log: No crash.

## Client Information

* Modpack Version: 3.0.6
* Java Version:  Build 1.8.0_161-b12
* Launcher Used: Twitch
* Memory Allocated: 8gb
* Server/LAN/Single Player: Server
* Resourcepack Enabled?: Yes
* Optifine Installed?: No

## Server Information
* Java Version: Build 1.8.0_161-b12
* Operating System: Windows 10 pro
* Hoster/Hosting Soultion: Local
* Sponge (Non-Vanilla Forge) Server?: No
* Additional Content Installed?: No

**Comment by Mrbysco** [comment]
This is my fault. This is a bug with Just A Raft. I accidentally left in some debug code.

**Comment by JoramD0** [comment]
Is there any quick way of fixing/changing this?

**Comment by Mrbysco** [comment]
It's fixed in v1.1.1 and higher. (which are up on curse)

**Comment by artdude543** [comment]
Resolved in the next pack update.
