### ISSUE TITLE
Game crashing (Can't enter my world)

### ISSUE THREAD

**Issue by AdmiralFugly** [Darkosto/SevTech-Ages#1775]
## Issue / Bug
Game started crashing after using pneumaticcraft, after that I can't enter my world!
## Possible Solution
N/A
## Steps to Reproduce (for bugs)
N/A

## Logs
https://pastebin.com/tphvkWYu

## Client Information

* Modpack Version: 3.0.6
* Java Version: 1.8.0.161
* Launcher Used: Twitch Launcher

* Memory Allocated: 6GB

* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: No
* Optifine Installed?: Yes

**Comment by 0xb00b** [comment]
From what i understand is theres a pneumaticcraft pressure tube bugging out somewhere, try removing it from the world with MCEdit and see if the world loads up again

**Comment by AdmiralFugly** [comment]
I don't know how to do that, kinda of confusing!

**Comment by 0xb00b** [comment]
I just checked the pneumaticcraft bug tracker. and found this https://github.com/TeamPneumatic/pnc-repressurized/issues/137

did you happen to connect a pressure tube to a refinery? If so, its a known bug and it should be fixed in the next release.

**Comment by AdmiralFugly** [comment]
Still cant fix my game! FeelsBadMan

**Comment by Jandakast** [comment]
@AdmiralFugly you can try the following. 

1. Exit Minecraft
2. Make a backup of your world
3. Open the \config\forge.cfg 
4. Change `B:removeErroringEntities` and `B:removeErroringTileEntities`  to `true`
5. Launch Minecraft and load your world
6. If your world loads save and exit
7. Exit Minecraft
8. Open the \config\forge.cfg 
9. Change `B:removeErroringEntities` and `B:removeErroringTileEntities`  to `false`
10. Launch Minecraft and load your world
11. Verify nothing major has been deleted

**Comment by Nitram450** [comment]
I cant enter my world either. Tried the config/forge thing, MCedit wont work, as it cant download MC. This is getting annoying.

**Comment by AdmiralFugly** [comment]
@Jandakast Tired that nothing changed! :(

**Comment by artdude543** [comment]
The block involved in this crash, will be fixed in 3.0.7
