### ISSUE TITLE
Fortune pickaxe duplicating seared type blocks

### ISSUE THREAD

**Issue by l337h4l** [Darkosto/SevTech-Ages#1777]
## Issue / Bug
When you break seared bricks with a fortune pickaxe it has a high chance for the fortune enchantment to trigger allowing someone to duplicate seared type blocks

## Steps to Reproduce (for bugs)
Break seared bricks with a fortune pickaxe, I had fortune 3 on mine

**Comment by justinrusso** [comment]
I can't seem to replicate this. Please submit a new issue if this persists in 3.0.7.
