### ISSUE TITLE
Drying Rack / Item Rack doesnt work

### ISSUE THREAD

**Issue by Battokage** [Darkosto/SevTech-Ages#1778]
I'm using the SevTech version form the twitch launcher and got stuck in age 0 now.
salted leather and any other use for both Drying Rack and Item Rack is not working. (like making monster jerky)
i put up both Drying Rack and Item Rack and tested the recipes form both but even after hours nothing is working. 
the issue previously addressed that the recipes are not showing up in weila is not the case here! i can look up everything just fine.

i will track this issue here so please tell me what logs you need and were i can find them

unfortunately i don't have any idea how to Reproduce this bug because it just is always there without exemption.

[2018-04-13-1.log.gz](https://github.com/Darkosto/SevTech-Ages/files/1905721/2018-04-13-1.log.gz)
[latest.log](https://github.com/Darkosto/SevTech-Ages/files/1905722/latest.log)

* Modpack Version: 3.0.6 Forge-14.23.2.2651 Mc 1.12.2
* Java Version: 1.8.0_25
* Launcher Used: Twitch Launcher
* Memory Allocated: -Xmx6144M -Xms4096M
  Single Player
* Resourcepack Enabled?: No
* Optifine Installed?: No
On Win 10 64x Home

**Comment by Battokage** [comment]
[crafttweaker.log](https://github.com/Darkosto/SevTech-Ages/files/1905839/crafttweaker.log)
![2018-04-13_06 47 12](https://user-images.githubusercontent.com/38339498/38717345-a8c98b0c-3ee6-11e8-8d04-2be6e73ce564.png)
![2018-04-13_06 47 24](https://user-images.githubusercontent.com/38339498/38717346-a919d972-3ee6-11e8-940d-0876249b4974.png)
![2018-04-13_06 47 28](https://user-images.githubusercontent.com/38339498/38717347-a967e04a-3ee6-11e8-8f48-ebd7c0f3e181.png)

**Comment by Battokage** [comment]
is that all you need? can i help with some more information?
heard last form you 5 days ago.
i didnt even get a "thank you that helps a lot, we work on the problem"

**Comment by justinrusso** [comment]
![image](https://user-images.githubusercontent.com/25138621/39088798-9cb057b4-4586-11e8-8df1-46943c32d8d3.png)

**Comment by justinrusso** [comment]
I cant reproduce this. Try updating your java? Make sure you are using the JAR version of the launcher in your twitch settings.

**Comment by Battokage** [comment]
Thanks for your reply
Java is the most up to date i could find because of a newly installed PC.
![2018-04-23_19 57 56](https://user-images.githubusercontent.com/38339498/39144403-fffb5fc0-4730-11e8-869c-4cc4031f373e.png)
![2018-04-23_19 59 51](https://user-images.githubusercontent.com/38339498/39144405-001cf716-4731-11e8-9cfc-5a33937555ce.png)

Found a problem with my java starting in a x32 version.
also changed to the JAR Launcher in the twitch settings like suggested.

![2018-04-23_20 33 10](https://user-images.githubusercontent.com/38339498/39145932-96f27f40-4735-11e8-9804-0f819e9922e0.png)

Works now! its still doesn't have the progress bar like in your screenshot but at least i can play now without cheating, THANK YOU
