### ISSUE TITLE
[suggestion] making ground netherrack

### ISSUE THREAD

**Issue by maverickx29** [Darkosto/SevTech-Ages#1783]
With netherEX installed, there are many types of netherrack. All make sense for use to obtain ground netherrack however only vanalla works. If possible, could the netherEX netherracks be added as options to grind down?

**Comment by Targren** [comment]
I think this is a JEI/recipe glitch. I just now confirmed that Gloomy and Fiery varieties (they're what I had handy) will grind down in the millstone, even though it doesn't show up in the recipe.

**Comment by justinrusso** [comment]
The netherrack alternates between 4 NetherEx variants of netherrack as well as the vanilla one. I'm not sure what else you believe is missing

**Comment by Targren** [comment]
@justinrusso  I mean that hitting "U" (or whatever key you have mapped to "uses" in JEI) on the NetherEx variants, there's no millstone tab

**Comment by justinrusso** [comment]
![image](https://user-images.githubusercontent.com/25138621/38755545-2153813e-3f34-11e8-952f-18c7d3b5c1f6.png)
