### ISSUE TITLE
[3.0.6] [Recipe] "Raw Pigman Hide"  can't be used

### ISSUE THREAD

**Issue by Targren** [Darkosto/SevTech-Ages#1787]
## Issue / Bug

Raw Pigman Hide cannot be combined with the work blade to create rawhide, as it can with most other "hide"/"pelt" drops.  It also will not render into glue in a cauldron.  In fact, it apparently has no use in recipes at all in JEI.

## Expected Behavior

That it would remain consistent with other vanilla mob hides or, at a minimum, have some use.

## Possible Solution

Add recipes for Raw Pigman hide

## Steps to Reproduce (for bugs)
1. Kill Pigman
2. Get Raw Pigman Hide
3. ???
4. Profit? 

## Context

Need to know what step 3 is. 

## Client Information
* Modpack Version: 3.0.6
* Java Version: 1.8_161
* Launcher Used: MultiMC 5 0.6.2
* Memory Allocated: 6GB
* Server/LAN/Single Player: SSP
* Resourcepack Enabled?: No
* Optifine Installed?: No

* Additional Content Installed?: LagGoggles
* Disabled Mods: Mo'Bends, Better Foliage, Smooth Font, Fancy Block Particles, Tips and Tricks

**Comment by artdude543** [comment]
Fixed in https://github.com/Darkosto/SevTechAgesConfigs/commit/b2fbfec5d6fd0990d5d492fe765dd0d0f257c07d
