### ISSUE TITLE
[A8] Roots 2 Thatch

### ISSUE THREAD

**Issue by Dawenzel** [Darkosto/SevTech-Ages#179]
## Bug/Issue
A recipe for Roots 2 "Thatch" blocks was added, but the original recipe was not removed.
![example](http://puu.sh/yo2uv/df5cafc095.png)

## Possible Solution
Adding `recipes.remove(<roots:thatch>);`  above the aforementioned recipe in shapedrecipemaster.zs at line 255 should fix this.

## Versions
- Minecraft 1.12.2
- Forge 14.23.0.2544
- Java x64 8u144
- Sevtech-Ages Alpha 8

**Comment by Darkosto** [comment]
Fixed in dev.
