### ISSUE TITLE
[Enhancement] Astral Sorcery Iron Ore Transumation (Unintentionally Disabled?)

### ISSUE THREAD

**Issue by gbattleson** [Darkosto/SevTech-Ages#1792]
## Issue / Bug
According to the stream Darkosto does not remember disabling Iron Ore Transmutation.
Star metal transmutation, check scripts/mod_integrations/astral_sorcery.zs in line 78

LightTransmutation.removeTransmutation(<astralsorcery:blockcustomore:1>, false);

The question/enhancement is this intended behavior? The modbook that you get in the world says it is possible but it does not appear to work.

## Possible Solution
 If it is disabled I would suggest re-enabling it so that stardust can be obtained by mod mechanics. You still have to make collector crystals in order to accomplish this since none spawn in the world. Which would require find at least 3 or 4 stardust crystal chunks

I think you would need to add the line 

LightTransmutation.addTransmutation with code for iron ore but not sure

## Client Information
Modpack Version: 3.0.6
* Launcher Used: Twitch
* Memory Allocated: 6.5GB

**Comment by Targren** [comment]
It's intentionally disabled in scripts/mod_integrations/astral_sorcery.zs

`
LightTransmutation.removeTransmutation(<astralsorcery:blockcustomore:1>, false);
`

**Comment by justinrusso** [comment]
After speaking with Darkosto, he would like to have this added back.
