### ISSUE TITLE
Lost gravestone in twilight forest after dying to Hydra Boss.

### ISSUE THREAD

**Issue by bozzDK** [Darkosto/SevTech-Ages#1799]
So i was fighting against the Hydra boss in the twilight forest. It killed me and when got back, my Gravestone was gone with all my stuff. 
I think it's a bug but not sure. 
![2018-04-14_00 13 55](https://user-images.githubusercontent.com/34946254/38760088-a86a50f4-3f79-11e8-9ddf-e682dd26ecc7.png)
![2018-04-14_00 14 15](https://user-images.githubusercontent.com/34946254/38760089-a8ac6070-3f79-11e8-8304-7bbcb557d938.png)

**Comment by justinrusso** [comment]
https://github.com/Darkosto/SevTech-Ages/issues/1144
