### ISSUE TITLE
PrimalCore Ironwood Planks getting assigned random metadata when chopped on the block

### ISSUE THREAD

**Issue by MongoTheElder** [Darkosto/SevTech-Ages#180]
![2017-11-17_16 05 00](https://user-images.githubusercontent.com/29290246/32969008-57c5e6b8-cbb1-11e7-83f9-53f08f827b0d.png)

I have Ironwood planks with ID's of 6675:6 and 6675:7
Alpha 8, Twitch Build

I was not able to get the MultiMC version to run (missing library) although I didn't spend a lot of time debugging the issue

**Comment by Darkosto** [comment]
Should be all fixed up now! Thank you :D
