### ISSUE TITLE
Unsure how or if the automatic crafter works (inductive logistics)

### ISSUE THREAD

**Issue by MyApolloGees** [Darkosto/SevTech-Ages#1802]
## Issue / Bug
Okay so I'm using the garden cloche to make melons but i wanted those melon blocks to be auto crafted into melon slices so i decided to make an automatic crafter from Inductive logistics but I'm sure how it works. I have the correct side in but it doesn't change the block into a melon i can't tell how it works or if I'm doing it right because the UI is super confusing.  Any help on this issue would be appreciated. 

* Modpack Version:3.0.5
* Java Version: latest
* Launcher Used: twitch

* Memory Allocated: 8gb
* Server/LAN/Single Player: Sp
* Resourcepack Enabled?: unity
* Optifine Installed?: Yes

**Comment by MyApolloGees** [comment]
Never mind this i had to put a chest next to it not just pipe it in

**Comment by MyApolloGees** [comment]
@didyouknow-aston you have to have an actual inventory such as a chest for it to pull from can't be pipes in

**Comment by DidYouKnow-Aston** [comment]
@MyApolloGees I tried that, I have a chest WEST full of melon (the cube one) and in the crafting grid I set the top left to take inputs from WEST, I would expect to see on the right of the crafting GUI the output of 9 slices but instead nothing

**Comment by MyApolloGees** [comment]
Has to also be pulled out

**Comment by DidYouKnow-Aston** [comment]
@MyApolloGees I just reloaded the test world I was using to try that and it started worked fine without me doing anything, thanks for the patience. :)
