### ISSUE TITLE
Suggestion- Add mod that automatically backs up world every xMinutes

### ISSUE THREAD

**Issue by Dystilled** [Darkosto/SevTech-Ages#1806]
After losing my stuff for about the 8th time due to a major bug, I feel it needs to be suggested that a mod be added that backs up your save every 30 minutes or so. 

I can't remember the last time I played a pack that DIDN'T have this functionality, yet SevTech seems to be the odd one out.

**Comment by SteseDav** [comment]
i've heard Darkosto mention that backup isn't the pack's job. I personally see no harm in adding this yourself.

**Comment by justinrusso** [comment]
https://github.com/Darkosto/SevTech-Ages/issues/1631

**Comment by Dystilled** [comment]
Seems a rather weak reply when theres conflicts in the game that have lost a tonne of progress for people.
