### ISSUE TITLE
Ore Dictionary Synonym for Ceramic / Weedwood / Syrmorite Buckets of X.

### ISSUE THREAD

**Issue by Sorbe** [Darkosto/SevTech-Ages#1809]
Creating certain Astral Sorcery items currently will not work if you offer up Weedwood Buckets of Liquid Starlight.  They require Ceramic Buckets of Liquid Starlight.

This could be made far more reasonable with a set of Ore Dict equivalencies for all the buckets of X.

**Comment by justinrusso** [comment]
Ore dict does not work on buckets, as they use NBT. The method we use is currently not supported for Astral Sorcery tables.

See https://github.com/HellFirePvP/AstralSorcery/issues/627
