### ISSUE TITLE
Starlight Crafting Altar breaks

### ISSUE THREAD

**Issue by Sorbe** [Darkosto/SevTech-Ages#1810]
Please consider making advanced items like this not be completely destroyed by breaking them.
This is especially true for the Starlight Crafting Altar since it was a "surprise" that it both consumed my "Luminous Crafting Table" as a non-obvious upgrade and then the resulting item was DESTROYED when I tried to break and reposition to the Starlight Crafting Altar to a suitable location.

**Comment by justinrusso** [comment]
## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:

* Memory Allocated:

* Server/LAN/Single Player:
* Resourcepack Enabled?:
* Optifine Installed?:

**Comment by PsyberMind** [comment]
Make sure you're using a Pickaxe other than Stone - I had this happen as well, had to craft a second one. My Bronze Pick will break it perfectly now

**Comment by justinrusso** [comment]
This should have been fixed. With the lack of information I cannot determine if this is something that was not actually fixed though we thought it was.
