### ISSUE TITLE
[3.0.6] Can't make Stabilized Metal in Arc Furnace

### ISSUE THREAD

**Issue by Syltann** [Darkosto/SevTech-Ages#1813]
Using the Arc Furnace from IE in stage 4 I haven't been able to make stabilized metal. Tried multiple different ways and it's still not working.
![2018-04-14_01 06 38](https://user-images.githubusercontent.com/30686588/38766094-e922669c-3f81-11e8-9080-a4d95c7fb84d.png)
![2018-04-14_01 09 46](https://user-images.githubusercontent.com/30686588/38766096-ed0679c4-3f81-11e8-99dc-6568d53384a4.png)

**Comment by Dystilled** [comment]
Iron goes on the right. Its an oxidiser.

**Comment by Syltann** [comment]
Thank you.
