### ISSUE TITLE
Carry on only works intermittently. 

### ISSUE THREAD

**Issue by Dystilled** [Darkosto/SevTech-Ages#1814]
## Issue / Bug
Accidentally pick up chests when crouching at times- so I know the mod is functioning at least part of the time. 
But sometimes it just turns off and no matter what you do or what block you try and Carry On, it just wont work. 

## Expected Behavior
Carry on to work when holding left shift. 
## Steps to Reproduce (for bugs)
Not sure if its reproducible. Just try and use carry on and sometimes it doesnt work. 

## Context
Unable to use Carry on

## Client Information

* Modpack Version: 0.6
* Java Version: Latest
* Launcher Used: Twitch Java

* Memory Allocated: 12gb
* Server/LAN/Single Player: SP 
* Resourcepack Enabled?: Soartex 
* Optifine Installed?: Yes

**Comment by 3jlowes** [comment]
Make sure you have no item in your offhand. Also make sure you are close enough.

**Comment by Dystilled** [comment]
Am aware how the mod works, its not an issue of execution.

**Comment by artdude543** [comment]
The mod has it's fair share of issues and "minor" issues with picking things up. Sadly it's a mod we are iffy about and the fact that 99% the mod works fine when trying pick up/down things. I'm going to close this as I don't validate this to be an issue when it works most of the time.
