### ISSUE TITLE
Crash with slime sling

### ISSUE THREAD

**Issue by Pimhazeveld** [Darkosto/SevTech-Ages#1817]
I tried using the slimesling but the game crashed instead. 

`Error: java.lang.LinkageError: loader (instance of net/minecraftforge/fml/common/eventhandler/ASMEventHandler$ASMClassLoader): attempted duplicate class definition for name: "net/minecraftforge/fml/common/eventhandler/ASMEventHandler_2609_SlimeBounceHandler_playerTickPost_PlayerTickEvent"
`

I got the newest version of sevtech (which is 3.0.6 I think)

Edit: No, apparantly I have 3.0.4, why is curse not giving me the newest version

my java version is 1.8.0_25 (the one that crashes with the engineers manual apparantly)

Here's a log https://www.dropbox.com/s/2zuz85p5h3q7ikt/crash-2018-04-14_13.37.51-client.txt?dl=0

**Comment by Pimhazeveld** [comment]
Also a different thing. The recipe fish n' chips and cooked ghast meat are stage 3 only but only require ingredients from stage 2

**Comment by SteseDav** [comment]
update the pack to 3.0.6 and also update your Java installation and force the Twitch launcher to use it. 

https://docs.google.com/document/d/e/2PACX-1vR5muyi1m7Zy_qSwrzeb9e3tbbRlksguNUb_Pvm3pn9eDpsIkUj5qQUq6WFPPdEoVWZq91WvvH57KzC/pub

**Comment by artdude543** [comment]
You need to update your Java using the guide linked above. This will fix your issue.
