### ISSUE TITLE
Advancement for Galacticraft Compressor has incorrect name

### ISSUE THREAD

**Issue by ADKaster** [Darkosto/SevTech-Ages#1819]
## Issue / Bug

Stage 4 Galacticraft compressor advancement is named "Advanced Ender Alloy", same as the parent advancement.

![sevtech_bug](https://user-images.githubusercontent.com/8388494/38768574-03b505c2-3fc4-11e8-9312-dd8cc9f82599.png)

## Client Information

* Modpack Version: 3.0.6
* Java Version: 8.161
* Launcher Used: Twitch

**Comment by justinrusso** [comment]
Already fixed in dev

https://github.com/Darkosto/SevTechAgesConfigs/commit/7c0252e0470b543870e3675b169f9708f5b92799
