### ISSUE TITLE
Clay Barrel Extensions required to make the Heater in Stage 0 are a Stage 1 item

### ISSUE THREAD

**Issue by MongoTheElder** [Darkosto/SevTech-Ages#182]
The clay extensions required to make the Heater for Stage 0 require Stage 1
![2017-11-18_01 27 39](https://user-images.githubusercontent.com/29290246/32977653-b76b3566-cbff-11e7-8edb-8e7c560dc47a.png)

Same for the unfired version
![2017-11-18_11 48 49](https://user-images.githubusercontent.com/29290246/32982696-99c7a7e0-cc56-11e7-8e2e-b7def83426bd.png)

From stage0recipes.zs:
recipes.addShaped(<tcomplement:porcelain_melter:8>, [[<ceramics:unfired_clay:5>, <**ceramics:clay_barrel:1**>, <ceramics:unfired_clay:5>], [<ceramics:unfired_clay:5>, <**ceramics:clay_barrel:1**>, <ceramics:unfired_clay:5>], [<ceramics:unfired_clay:5>, <primal_tech:stone_grill>, <ceramics:unfired_clay:5>]]);

From stage1items.zs:
mods.ItemStages.addItemStage("one", <**ceramics:clay_barrel:1**>); (Line 624)
mods.ItemStages.addItemStage("one", <**ceramics:clay_barrel_unfired:1**>); (Line 620)

From stage1recipes.zs
mods.recipestages.Recipes.setRecipeStage("one", <**ceramics:clay_barrel_unfired:1**>); (Line 731)

Commenting out these lines in stage1items.zs and stage1recipes.zs fixes the issue

Alpha 8, Twitch build

**Comment by Darkosto** [comment]
Commented out those three lines in scripts.
