### ISSUE TITLE
Starlight altar recipes not working

### ISSUE THREAD

**Issue by MCChiter** [Darkosto/SevTech-Ages#1820]
## Expected Behavior
According to JEI the recipe involves altar from astral sorcery, checked the inworld structure is all walid, the bar in the altar glows blue, but the recipe doesn't trigger with the resonating wand. since starmetal is a crucial step that causes lots of issues. 

## Steps to Reproduce (for bugs)

1. Input recipe in the altar
2. Trigger the crafting
3. groan because it doesn't work

## Client Information
Pack update 3.0.6 on windows, no additional mods
![2018-04-16_09 58 16](https://user-images.githubusercontent.com/7769849/38792193-7bf2a094-4154-11e8-98b2-1f876df2e078.png)
The setup somebody asked for, is located right in the starlight chunk
![2018-04-16_10 03 50](https://user-images.githubusercontent.com/7769849/38792324-1c21796e-4155-11e8-8191-3cedfae52022.png)
The recipe in the table
![2018-04-16_09 58 45](https://user-images.githubusercontent.com/7769849/38792240-ace0078c-4154-11e8-8e34-0a2ee62c13ff.png)
me struggling r-clicking the table with wand, was in the end of the night at this point but still enough starlight

**Comment by TexanMD** [comment]
It seems to be working fine for me.  Can you add screenshots of your setup?

**Comment by PsyberMind** [comment]
Is this specifically with Starmetal Ore? Or have you tried other recipes like nocturnal/illumination powder..

Since you are trying to make Starmetal Ore, it seems.. you would have had to upgrade your Luminous Crafting table to the alter, which means burnt quartz, so that recipe works, yea?

**Comment by MCChiter** [comment]
i had it with illumination powder too so i had to cheat it in to progress. to then see it not working. no idea, i will try it again after not touching the game for a week, i was not too interested in playing a broken mod

**Comment by LycanBlackpaw** [comment]
Your problem is not enough starlight. The item in question to be crafted will appear on the right side of the UI if craftable; if not, the starlight bar will have a glowing marker indicating how much starlight is still needed. It's *extremely* finicky, so you can be one pixel off and not be able to craft it.

Easy solution: Place down spectral relays.

**Comment by MCChiter** [comment]
Lycan... i said i was taking screenshots during the dawn so there was low starlight. when ritual needs more it shows a faint bar under it. 
REGARDLESS only fix was making the altar again from the basic table, which wasn't easy with how common are the crystals

**Comment by TexanMD** [comment]
I was able to recreate this by using console commands to spawn the starlight crafting altar instead of crafting it.   As soon as I crafted one things were fine.  

Astral Sorcery is a magic mod similar to thaumcraft and others in that some things have to be unlocked before they will work for you.
