### ISSUE TITLE
Rustic Clay Walls

### ISSUE THREAD

**Issue by Thiana** [Darkosto/SevTech-Ages#1822]
## Issue / Bug

Rustic's [Clay Walls](https://github.com/the-realest-stu/Rustic/wiki/Clay-Walls) are disabled.

Rustic.cfg:
```
        B:"Enable Clay Walls"=false
```

## Possible Solution

Enable them :) They have a unique look (wattle and daub) that doesn't appear to be supplied by any other block in the pack. They are only cosmetic blocks, so adding them should have no impact on progression.

Thanks.

**Comment by Dragonchampion** [comment]
Thanks for this! Enabled it on my end.

**Comment by Thiana** [comment]
Thank you :)
