### ISSUE TITLE
Metal Press does not accept Blaze Powder if fed by Hopper/Wopper

### ISSUE THREAD

**Issue by Dutchs** [Darkosto/SevTech-Ages#1823]
## Issue / Bug
A Hopper connected to the input of a Metal Press (Immersive Engineering) does not output Blaze Powder into the machine.
Wopper MK2 also has this issue.

However dropping the 4 Blaze Powder as item entities onto the Conveyor Belt of the machine does work.

## Possible Solution
The Metal Press seems to refuse the item if fed 1 at a time, possibly due to the requirement of 4 but only 1 supplied(at a time).
As a fix, allow for input even if the supplied item does not fulfill the recipe requirement by itself but is part of the recipe.

## Steps to Reproduce (for bugs)
1. Attach Hopper to input side of Metal Press
2. Input 4 Blaze Powder into Hopper

## Client Information
* Modpack Version: 3.0.6

**Comment by Shock2k** [comment]
Had this problem, I just added an extra belt in front then fed that with the hopper.
![2018-04-14_11 28 34](https://user-images.githubusercontent.com/37946010/38771379-bb2c5604-4011-11e8-95ee-06f63559330d.png)

**Comment by MyApolloGees** [comment]
its a problem with hoppers as the press wants 4 blaze powder but a hopper will only push one at a time, getting an item cable or extending the belt like Shock2k did will fix the problem. its actually a nice way to stop full automation until the next stage.
