### ISSUE TITLE
Dark/Shadow forest

### ISSUE THREAD

**Issue by Aquuil** [Darkosto/SevTech-Ages#1828]
Hello, I have question, is Dark/Shadow forest (dont know the name but i mean the one with shadow creatures) is very rare or common ? Because I made like 20 worlds already and was looking for about 30 minutes all the time and couldnt find any of them :/

**Comment by Dutchs** [comment]
Not rare, but perhaps somewhat uncommon.
In my sample size of 1(world), i had 2 each about 200/300 blocks from spawn.
But minecraft RNG can be a pain sometimes.

**Comment by Aquuil** [comment]
Could you send me seed of it ?  Maybe i have something broken with my sevtech.

**Comment by Dutchs** [comment]
![2018-04-14_20 42 54](https://user-images.githubusercontent.com/1423624/38771505-9071f302-4024-11e8-929e-39372d95cbb1.png)

**Comment by Aquuil** [comment]
Wow im creating with this seed and going to this x/z and nothing same as you have there ;d

**Comment by Aquuil** [comment]
Ok you can mark it as a bug, I just downgraded to 3.0.4 and put this seed and i found this place. So in 3.0.6 these mod biomes do now spawn :/
![2018-04-14_23 33 59](https://user-images.githubusercontent.com/38355248/38772656-7b0fe0e2-403c-11e8-8e10-078a7c2f2ac1.png)

**Comment by justinrusso** [comment]
The generation has changed, so you're not going to find it in the same place. This is not a bug

**Comment by LucieTwi** [comment]
Was the rarity of the dark forest increased? I've been making a bunch of worlds the whole day and flew over them in creative and couldn't find a single one... Since it's needed for the very first age, this is kind of annoying...

**Comment by justinrusso** [comment]
It is now in a specific band. It did not become more rare, it became more predictable.

**Comment by LucieTwi** [comment]
"specific band"? sorry, I'm not an english mother tongue... could you explain?

**Comment by justinrusso** [comment]
As stated in multiple locations, the generation is set up in temperature bands. These are horrizontal lines that go infinitely with generation. To change between temeraptures you head north and south. To change biomes in a band, you head east and west.

**Comment by LucieTwi** [comment]
ah, ok, thanks a lot :-)
