### ISSUE TITLE
Certain mod messing up rendering, player/npc's animations and player camera - not playable anymore

### ISSUE THREAD

**Issue by SomeRandomGuySRG** [Darkosto/SevTech-Ages#1829]
It happened after i closed the client for a few hours before playing again, the animation of the arms on the players character move heavily in all directions, the legs do the same when the player moves, the movements of mobs is completely messed up. When pressing WASD the players camera glitches out of the world, after a second or 2 it returns to the 1st person camera (This also happens in both 3rd person camera's). The only stable movement is jumping.

When reloading the world, i noticed in the first few seconds, the arms are stable short after they start accelerating in a centrifugal movement into the player's character and then glitch in all directions.

No other information known to this issue, i self suspect it's a mod that is supposed to enhance moving animations. But the most important is that it makes it unplayable.

**Comment by Tkabies** [comment]
I have the same problem installed the game for the first time with twitch and made 2 worlds and changed the conflict keys and still nothing cant play as soon as i move player go all over

**Comment by artdude543** [comment]
Ensure your Java and Graphics Drivers are up to date. This is not a modpack issue. This is an issue with your set-up/install.

**Comment by Tkabies** [comment]
Hi
I did a rollback from 3.0.6 to 3.0.4 and it fixed it i have not updated again but all my drivers are up to date.
