### ISSUE TITLE
3_0_6 Server Crash - Blood Magic Altar when zoning to Twilight Forest

### ISSUE THREAD

**Issue by ArbitraryHubris** [Darkosto/SevTech-Ages#1832]
Ignore if you like (I don't mean this in a passive-aggressive way.  I might ignore myself based on added mods) - I have FTBLib and FTB Utilities on my server - only modifications to 3.0.6.  

## Issue / Bug
Hard crash - .  Ticking block.

Player was zoning from home overworld base - location of the altar - to Twilight Forest.  has a Wopper (baby starter version) feeding into one side, and an Upper pulling out from the top of the altar.

We installed FTB Utils for team claims and chunkloading, but in this instance, the ticking altar was not chunkloaded so I it could be an issue with the altar unloading.   There was nothing going on in the altar at the time.

Was going to report on blood magic github but instructions there say to report to the modpack. 

## Logs
* Client/Server Log: https://pastebin.com/1puScbuy
* Crash Log: https://pastebin.com/XuQR7JMv

## Client Information
* Modpack Version: 3.0.6

## Server Information
* Modpack Version: 3.0.6
* +FTBLib
* +FTB Utilities
* -Tumbleweeds (breaks farmland)

**Comment by artdude543** [comment]
This _should_ be fixed in 3.0.7 if not please poke on here for it to be reopened. And then it would need reporting to the devs.
