### ISSUE TITLE
Astral Sorcery shrines not generating

### ISSUE THREAD

**Issue by kerenon** [Darkosto/SevTech-Ages#1838]
## Issue(?)
After days of tinkering with my server, reading logs, trying alternative configurations and looking through this issue tracker, I've decided it's time to give up and to open this ticket. I've tried everything I can think of, and I'm 99% sure Astral Sorcery shrines are not generating anywhere in the world. I've mapped out my world from -6000 to +6000 (took days), and nothing. Not a single one. Tried deleting / reinstalling server file, boosting shrine rarity all the way to 1, modifying map seed, generator (level.dat), tried pruning the map, tried a brand new map. No luck. I find it hard to believe that they are so rare, that there is not a single one of them in a 12km x 12km area.

I'd be thankful for any advice or pointer in the right direction. I _really_ like exploration, but this isn't fun anymore.

If I'm wrong and they are really that rare, i'm just going to have to cheat in something for my players.

## Expected Behavior
Populating the world with shrines

## Client Information
* Modpack Version: 3.0.4 upgraded to 3.0.6
* Java Version: build 1.8.0_161-b12
* Launcher Used: Twitch and/or MultiMC
* Memory Allocated: Minimum 2GB / Maximum 8GB
* Server/LAN/Single Player: Server
* Resourcepack Enabled?: No
* Optifine Installed?: No

## Server Information
* Java Version: build 1.8.0_161-b12
* Operating System: Linux
* Hoster/Hosting Soultion: Contabo VPS
* Sponge (Non-Vanilla Forge) Server?: No

**Comment by MyApolloGees** [comment]
Shrines do not spawn.

**Comment by PsyberMind** [comment]
The only way to get into AS is through a AbyssalCraft ritual to get the Luminous Crafting Table, and then build up from there

**Comment by kerenon** [comment]
Great. That’s what I get for listening for the complaints and trying to help...
I have a total of 9 players, 6 of them complained about the shrines.
Anyway, thanks for the pointers.

**Comment by BrownZFilmZ** [comment]
Same issue. We spent forever thinking they spawned. The advancements also are vague on that.
