### ISSUE TITLE
Weedwood bush farming broken

### ISSUE THREAD

**Issue by Kelmey** [Darkosto/SevTech-Ages#1843]
Weedwood bushes are not growing using the Betweenlands mod mechanics.

I'm following the instructions on the Betweenlands wiki ( http://the-betweenlands.wikia.com/wiki/Weedwood_Bush#Growing ) but after waiting for a couple of hours they won't spread.

**Comment by TheCyberBrick** [comment]
> Release 3.3.7: Can now be grown and farmed with composted blocks.

SevTech doesn't use the latest version 3.3.7 yet.

**Comment by Kelmey** [comment]
Oh. well nevermind then. Hope the pack updates to use 3.3.7 at some point. =)
