### ISSUE TITLE
Build Craft Transport is crashing my game

### ISSUE THREAD

**Issue by TuxedoHampster** [Darkosto/SevTech-Ages#1846]
## Issue / Bug
* When attempting to start the game, it crashes. I don't know if this has to do with the problems with Immersive Engineering or not.

## Expected Behavior
* I was expecting the game to finish loading in so I could play.

## Steps to Reproduce (for bugs)

1. I update any mod that's able to be updated before launching the game.
2. Run the launcher.
3. That's about it.

## Context
* This keeps me from playing SevTech Ages.

## Logs

* Client/Server Log:
* Crash Log: https://pastebin.com/jN5SE3vP

## Client Information

* Modpack Version: 3.0.6
* Java Version: 1.8.0_181-b12
* Launcher Used: Twitch Launcher

* Memory Allocated: 8,192 MB

* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: Default resources
* Optifine Installed?: OptiFine_1.12.2_HD_U_D1

**Comment by SeanLatimer** [comment]
Did you happen to have Buildcraft pipes adjacent to Bonsai pots by any chance?

Placing them side by side caused a crash for me.

**Comment by DeviousCrypto** [comment]
I too am having this crash! Hopping Bonsai Pot, put a cobblestone transport pipe under it that was going to connect to a chest, and then BAM brought the whole server down.

Report attached: https://pastebin.com/SSGWrke9

**Comment by TuxedoHampster** [comment]
I don't have any bonsai trees in my saves, I was doing stuff with pistons and the stoked utilities (ie; stoked cauldron, crucible and kiln). The tool changing worked fine for a couple tries but shortly afterwards the game crashed and I went to bed. I never had any buildcraft transportation blocks or items as far as I know.

**Comment by artdude543** [comment]
This will be resolved in 3.0.7
