### ISSUE TITLE
Abyssal Craft, Asorah

### ISSUE THREAD

**Issue by ellipsisxix** [Darkosto/SevTech-Ages#1847]
i have just killed Asorah (boss from the abbysal waste land)
i summoned him near to the portal, and then he appears - boss went the portal to over world (but ritual can be do only in abyssal) ... so all of his abilities doesnt work ( sorry for my english ^_^

**Comment by artdude543** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

Thanks again for reporting, and we hope you enjoy the pack!
