### ISSUE TITLE
(3.0.6) Loading the game freezes for a fresh install at Initialization 4\7 at AbyssalCraft Initialization

### ISSUE THREAD

**Issue by hellrage** [Darkosto/SevTech-Ages#1848]
## Issue / Bug
For a fresh installation of the pack (Fresh install of Twitch app, settings set up as per instructions in Discord pinned message, pack redownloaded) loading the game stops at this point:
![game window](https://user-images.githubusercontent.com/5305748/38778194-e2f69858-40b5-11e8-8f96-c2ac6a548446.png)

The client doesn't crash, there are no new messages in the log after a certain point, it's just frozen for an indeterminate amount of time. Running the game on an SSD. I have 10 days of playtime in my world, there were no changes to installed software or the pack immediately before the point where it stopped working. 

## Expected Behavior
Expecting the game to load normally at least up to the main menu.

## Possible Solution
I don't know what triggered it so I have no solution.

## Steps to Reproduce (for bugs)

1. Perform a clean install of the pack.
2. Launch the pack.
3. Have the loading process freeze and the window become unresponsive for 20+ minutes.

## Context
I have reproduced the issue multiple times using twitch app and multimc instances both with a freshly downloaded unmodified 3.0.6 client with identical results.
The pack has been loading fine for me since release throughout my 10 days of total playtime in my world, no idea what's causing the issue.

## Logs

* Client/Server Log: https://gist.github.com/hellrage/5b7f6c1f3d8e23244bdd04821eaa72f6
I manually closed the game at 14:05 after no visible changes in the log or the game window.
* Crash Log:

## Client Information

* Modpack Version: 3.0.6
* Java Version: 1.8.0_161
* Launcher Used: Twitch app's jar launcher.

* Memory Allocated: 8192 MB

* Server/LAN/Single Player: Single Player.
* Resourcepack Enabled?: No.
* Optifine Installed?: No.

**Comment by hellrage** [comment]
Same thing happens for 3.0.5 and 3.0.4 which also worked fine for me when they were released so the probles has to be with my system, closing the issue.

**Comment by hellrage** [comment]
After formatting my system drive and reinstalling the OS the issue is still there. Which, having as clean of an environment as possible, shouldn't happen, I'm lost.

**Comment by hellrage** [comment]
This appears to be completely random. Imported the twitch instance into multimc and set up a script that autokills and restarts the client when it hangs up. After a while the game does start up and works as expected from that point on (loaded my world and able to play normally so far). The client freezes at one of the tree points: Pre-Initialization AbyssalCraft, Initialization AbyssalCraft or PostInitialization Immersive Engineering.

**Comment by SteseDav** [comment]
Check your System event log for any issues with your storage... might explain why it's random, and also why its persisted between reinstalls of the OS.

**Comment by hellrage** [comment]
Issue resolved itself same way it appeared: with no additional actions on my part.
