### ISSUE TITLE
Primordial Malevolence Broken - Crashing the server, does not work properly

### ISSUE THREAD

**Issue by RealLith** [Darkosto/SevTech-Ages#1849]
## Issue / Bug
 when you spawn in the Primordial Malevolence (betweenlands Mod) it will.. kinda work as intendet. After few seconds-few min you will be trapped in the middle of the room and will not be able to move. Even if you are able to get out of it, The boss iwll just float aorund u. It will not shoot the green Bullets so you can not knock them back to him. + he will stop spawning Wights (and he should continue spawning them). After some time The server crashes. 

## Expected Behavior
 The boss should cintinue spawning  Wights and shoot green bullets so you could know them back to him to kill him.

## Steps to Reproduce (for bugs)

1. Complete the Wight Fortress
2. Summon the boss
3. Try to fight it
4. Crash The server

## Context
 I am trying to complete the advancement. since the advancement logo is a star, it means it unlocks something.

## Logs

* Client/Server Log: I am not the owner of the server. And the Owner does not give me the logs.
* Crash Log: 

## Client Information

* Modpack Version: 3.0.6
* Java Version: latest
* Launcher Used: twitch

* Memory Allocated: 10gb

* Server/LAN/Single Player: Server
* Resourcepack Enabled?: nope
* Optifine Installed?: no

## Server Information
* Java Version: Im not the owner
* Operating System:  Im not the owner
* Hoster/Hosting Soultion: Im not the owner
* Sponge (Non-Vanilla Forge) Server?: Sponge

* Additional Content Installed?: Im not the owner

**Comment by tjsd** [comment]
I run a 3.0.6 server with forge and have had this fight completed without issue. I suspect it might be sponge related.

**Comment by artdude543** [comment]
As your using a Sponge server you won't get support from us in regards to errors unless you can reproduce them in a standard Forge Server Environment. So I'll be closing the issue; if you manage to get the issue again with **only Forge** then please open a new issue.
