### ISSUE TITLE
[A8] Viescraft staging

### ISSUE THREAD

**Issue by Dawenzel** [Darkosto/SevTech-Ages#185]
## Issue
Multiple Viescraft items have been added to stage three, but their recipes haven't been. These items are:
`<vc:v1/item_airship_v1:29>
<vc:v2/item_airship_v2:29>
<vc:v3/item_airship_v3:29>
<vc:v4/item_airship_v4:29>
<vc:frames/airship_frame:29>
<vc:patterns/airship_balloon_pattern:26>
<vc:modules/airship_module:11>`

## Possible Solution
Adding the recipes for these items to stage3recipes.zs should fix this.

## Versions
- Minecraft 1.12.2
- Forge 14.23.0.2544
- Java x64 8u144
- Sevtech-Ages Alpha 8

**Comment by Darkosto** [comment]
Staged these items in stage3ecipes.zs with "mods.recipestages.Recipes.setRecipeStage("three"," tag
