### ISSUE TITLE
Betweenlands Bone Pickaxe Will not repair with Slimy Bones

### ISSUE THREAD

**Issue by jthe111** [Darkosto/SevTech-Ages#1850]
When Slimy Bone Pickaxe is on broken state the Pickaxe will not repair in the crafting grid (both on player and in Crafting table). 
Sevtech Ages Version 3.0.6
Current Age 2

**Comment by Rikshy** [comment]
Betweenlands tools can already be repaired in the animator.

**Comment by vadis365** [comment]
Indeed.
