### ISSUE TITLE
Immensely high booting time 

### ISSUE THREAD

**Issue by 88880** [Darkosto/SevTech-Ages#1855]
## Issue / Bug

Hello. Loading minecraft up takes around 15 minutes, and freezes for 10 seconds between every minute. I have allocated 6G of memory and installed Optifine, but the game crashed when I tried to tweak the Optifine settings at the in-game options menu, likely due to memory.
Thank you.

## Possible Solution

Should I remove a big mod? Should I try something with Java?
## Logs

* Client/Server Log: The log is 4mb large, should chop it up and provide it?
* Crash Log: Unfortunately cannot provide crash log because had to manually shut down computer.

## Client Information

* Modpack Version: 3.0.6
* Java Version: 161
* Launcher Used: yes

* Memory Allocated: first default, then 6G

* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: no
* Optifine Installed?: first no, then yes.

**Comment by Phantum** [comment]
15 minutes isn't too terrible, Try the performance suggestions in here:  https://docs.google.com/document/d/1HQGPm90MVyieiiEkTPyfXIDBAvSkOAAQOoicTzFpmt0/comment#heading=h.jtl67zz31b43

Ignore the "shouldn't need more than 4gb of ram thing"

**Comment by 88880** [comment]
I have 8gb of ram, how much should I allocate based on that?

**Comment by Phantum** [comment]
Probably can't allocate more than 6 if you're running win 10

**Comment by ObeliskofDeath** [comment]
So in 88880's case then we can assume he has a terrible processor? Like I mentioned, my brother is running an AMD Athlon, an ancient processor by todays standards, but yet he still has a quicker load time than 88880 states.

**Comment by Phantum** [comment]
There are too many factors. HD vs SSD, background processes, Ram speed, processor speed, java versions, OS versions, 

He never mentioned he has a current era processor. Not a lot of people have high end systems either.

**Comment by artdude543** [comment]
Sadly this pack is a beast to load. All we can suggest is make sure your Java/Drivers are up to date. The issue won't ever go away due to how large the pack is. Even people with really high-end systems still have long waiting times.

You can try also using Java Args to help a little but they can only do so much.
