### ISSUE TITLE
Crash on world load

### ISSUE THREAD

**Issue by oOMonkeytimeOo** [Darkosto/SevTech-Ages#1857]
## Issue / Bug
The game crashes when on world load. 

## Expected Behavior
No crash?

## Steps to Reproduce (for bugs)

1.
2.

## Context

I was building a frame for an Immersive Engineering water wheel using chiseled cobblestone when the game crashed and I can't get back in.

## Logs
[crash-2018-04-14_22.49.45-server.txt](https://github.com/Darkosto/SevTech-Ages/files/1913008/crash-2018-04-14_22.49.45-server.txt)

## Client Information

* Modpack Version: 3.0.6
* Java Version: 1.8.0.161 (64 Bit)
* Launcher Used: Jar Launcher

* Memory Allocated: 8.5GB

* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: 
* Optifine Installed?:

**Comment by SteseDav** [comment]
Ok, couple of basics to check 

1. Check your allocated RAM amount isn't more than half of your available RAM in the machine, as this can cause issues...

2. Update your Java Version to 1.8.0.162 and force Minecraft to use it. 

https://docs.google.com/document/d/e/2PACX-1vR5muyi1m7Zy_qSwrzeb9e3tbbRlksguNUb_Pvm3pn9eDpsIkUj5qQUq6WFPPdEoVWZq91WvvH57KzC/pub

Regards,

**Comment by oOMonkeytimeOo** [comment]
Thanks for replying. This is the version of Java I have now:
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)

This is the version after the update:

java version "1.8.0_162"
Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.162-b12, mixed mode)

[crash-2018-04-17_15.41.04-server.txt](https://github.com/Darkosto/SevTech-Ages/files/1921326/crash-2018-04-17_15.41.04-server.txt)

Same crash. I tried using mcedit to delete everything in that chunk that I has placed. but had the same result. Does the crash report tell you what block is causing the problem?

Thanks for your help.

**Comment by SteseDav** [comment]
Hi, 

It's not telling me specifically whats going on but it seems to be something to do with BloodMagic and your Soul Network... I think one of the pack devs will understand this better and maybe report it to the Mod Dev. 

I'm really just checking for basic issues, to help reduce the workload on the people that know better than I. ;)

Hope you get this sorted. 

Regards,

**Comment by oOMonkeytimeOo** [comment]
I appreciate your help anyway. I may try removing all the sigils and orb from my inventory and see if that helps. I was using a water sigil to place water for my water wheel.

**Comment by oOMonkeytimeOo** [comment]
I finally got back in by removing the blood magic mod and loading the game. I put it back and It's still working. Hopefully this doesn't break anything. Thanks for the help.
