### ISSUE TITLE
SUGGESTION

### ISSUE THREAD

**Issue by MyApolloGees** [Darkosto/SevTech-Ages#1858]
Okay so im in stage 5 and I STILL CAN'T MAKE GLASS ANY OTHER WAY OTHER THEN THE SMELTERY! yet i can refine and smelt ores in a complex system! Just let me smelt sand in the Arc Furnace please you'd think by the time you hit stage 5 you'd be smart enough to find a better way to smelt glass.

## Client Information

* Modpack Version: 3.0.6
* Java Version: 1.8.0_161
* Launcher Used: Twitch

* Memory Allocated: 8gb

* Server/LAN/Single Player: PS
* Resourcepack Enabled?: Unity
* Optifine Installed?: Affirmative

**Comment by tjsd** [comment]
Why not use the cauldron on a stoked fire? that is sand smelting into glass

**Comment by MyApolloGees** [comment]
Thats just as slow. and its annoying to set up i want to be able to use these things i spent hours building instead of just going back to where i began @tjsd

**Comment by JRiebling** [comment]
In the meantime, you could try smelting soul sand and then smelting that result. It doesn't actually get you glass, but it works as glass in most recipes and can be done in a vanilla furnace (I just started Age 3, so I can't say if it works with more advanced machines).

**Comment by artdude543** [comment]
Will be included in the next version :)

![image](https://user-images.githubusercontent.com/1885466/38870097-ac0739e8-4244-11e8-91c6-40db60eddc81.png)
