### ISSUE TITLE
Crash when starting up (could not find anything to help fix issue when I searched for it)

### ISSUE THREAD

**Issue by deathslilangel** [Darkosto/SevTech-Ages#1859]
## Possible Solution
I have tried to delete the pack and couldn't also, I have tried to repair the mod pack and it comes up with a message saying there is more then one error when trying to repair.

## Context
I cant launch the pack.

## Logs
* Crash Log :https://pastebin.com/vwKWNtkg

## Client Information
* Modpack Version: 3.0.6
* Java Version: Version 8 Update 161
* Launcher Used: twich app
* Memory Allocated: 5gb

**Comment by SteseDav** [comment]
while you have Java version 161 installed, you may not be using it.

Try forcing it to latest  with these instructions :- 

https://docs.google.com/document/d/e/2PACX-1vR5muyi1m7Zy_qSwrzeb9e3tbbRlksguNUb_Pvm3pn9eDpsIkUj5qQUq6WFPPdEoVWZq91WvvH57KzC/pub

**Comment by deathslilangel** [comment]
Thank you, I have done all the steps you have given me and I tried to launch it again and it seemed to have gone father while loading but then it crashes again. here is the new crash logs that it has given me https://pastebin.com/0MRELptN

**Comment by SteseDav** [comment]
I think you might want to try backing up your world, and then reinstalling the pack.

**Comment by deathslilangel** [comment]
I don't have a world at all, I haven't even gotten into the game. I have tried uninstalling and downloading it and got nowhere with it.

**Comment by SteseDav** [comment]
- Which launcher are you using, after twitch? (you should be using the OLD JAR launcher, not the new launcher

- How much RAM is available on your machine? 

Could you try removing the Modpack & twitch app from the machine and reinstalling. It may be an idea to do a 'Disk Cleanup' in between uninstalling and reinstalling to purge any temporary files.

**Comment by deathslilangel** [comment]
I am using the jar launcher
I have 16gb but I am using 5,632
I also did a disk clean up and it crashed again

**Comment by deathslilangel** [comment]
thanks for the tip it still crashed i had 8.5GB and didnt have any other windows open.

**Comment by deathslilangel** [comment]
I got it to work on the ATlauncher.

**Comment by SteseDav** [comment]
deathslilangel : You need to be using LESS than 8gb for it to properly behave. Minecraft has an issue when it is allocated more than half of your available RAM. For most users i've seen 6gb (6144mb) has been the sweet spot.

**Comment by artdude543** [comment]
Closing as this is resolved on the user side; going to guess this is a Java issue with the user. ATLauncher forces options and is smart when it comes to setting memory. So I have bets on yourself over allocating memory.
