### ISSUE TITLE
[A8] Firepit cooking fish XP

### ISSUE THREAD

**Issue by Dawenzel** [Darkosto/SevTech-Ages#186]
## Issue
Another one for the sake of consistency. Most of the vanilla items when cooked in the firepit give 5x more xp then the other items that are cookable in the firepit.

## Possible Solution
Changing the xp values to match the other items in the progressiontweaks config should "fix" this.

## Versions
- Minecraft 1.12.2
- Forge 14.23.0.2544
- Java x64 8u144
- Sevtech-Ages Alpha 8

**Comment by Darkosto** [comment]
Fish have been lowered to 2 to match with other foods.
