### ISSUE TITLE
Sevtech 3.0.6 log to plank recipes: few missing pages

### ISSUE THREAD

**Issue by kragnoth** [Darkosto/SevTech-Ages#1861]
The following pastebin contains the basic list of all logs that have planks, that don't have a way to convert into planks.

Honestly, don't really care about the kepler22b maple logs, but menril makes a great building material.

https://pastebin.com/SDVHNHXx

This is a general idea of missing ones, the ones with a * by them seem to have one type that is in the recipe list, but one or more of the rest of the meta tagged logs are missing (natura has one for meta 1, but not for the others)

**Comment by artdude543** [comment]
Okay so these are going to be the changes.

```
<thebetweenlands:log_herathgrove> - You shoudn't even get this normally
  - And the correct logs have recipes.
<extraplanets:kepler22b_maple_logs> - Seems to be a mod bug would need reporting to them.
<natura:redwood_logs> -> Is the bark which is only for Charcoal (As stated on the tooltip)
<betterwithaddons:log_luretree> - Does not have a plant variety.
<thebetweenlands:log_sap> - Are not designed to have plank recipes.
<thebetweenlands:giant_root> - Fixed.
<twilightforest:magic_log:*> - Are not designed to have plank recipes.
<thebetweenlands:log_nibbletwig> - Does not have a plant variety.
<betterwithaddons:log_luretree_face> - Does not have a plant variety. 
<thebetweenlands:log_rubber> - Fixed.
<integrateddynamics:menril_log> - Fixed.
<integrateddynamics:menril_log_filled> - Fixed.
```

**Comment by justinrusso** [comment]
Some things on this list do not seem to be added. @artdude543 please message me so we can sort this out

**Comment by artdude543** [comment]
I derped on the commit message so it actually relates to https://github.com/Darkosto/SevTechAgesConfigs/commit/20c3ec3ebce6c1a294a23a1f6bf4f69419fccfcc

We are also going to remove logs which don't have planks to avoid the issue of making a tonne of chopping blocks for no reason. Need issue for tracking on that here: https://github.com/Darkosto/SevTech-Ages/issues/2045
