### ISSUE TITLE
Lock when playing for a couple minutes

### ISSUE THREAD

**Issue by Butterlegz** [Darkosto/SevTech-Ages#1862]
## Issue / Bug
I've been playing for about 12-15 hours in a single player world with no issues.  Now when I play, I can play normally for about 2 minutes and then the game stops working in a peculiar way.  I can still move around in the immediate vicinity but no new chunks will load or render, I cannot eat (does the eating animation endlessly without actually consuming the item.  When I quit, the game completely locks up and doesn't return to the main menu.  When the game crashes, no crash log is generated (I've tried multiple times).  When I reload the game it doesn't load where I tried to quit, but rather back where the odd behavior began.  

## Possible Solution
Here is what I've tried with no change
1.  Repairing minecraft through the Twitch launcher
2.  Completely emptying my inventory in game
3.  Removing resource packs (I was using faithful 32).  I did this from the main menu before loading my world
4.  Uninstalling and reinstalling the modpack from the Twitch launcher

I don't know enough about the coding for minecraft to know for sure, but I think it's either a block or something in the world that is causing the pack to crash.  (I'm not near my base, so it's not a block I've placed) or something with my character or the save itself.

## Context
I was returning from a darklands biome to my base when the problems started.  Now I can't go back to either without the problem arising.

## Logs
Like I said no crash log but this is from the logs folder, just the part around the time of the error

https://pastebin.com/rkZKvCir

## Client Information
* Modpack Version: 3.0.6
* Java Version: build 1.8.0_161-b12
* Launcher Used: Twitch Launcher
* Memory Allocated: 8 GB
* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: Faithful 32 and none happens with both
* Optifine Installed?: No

**Comment by SteseDav** [comment]
Hi, 

You've got Java Version 161-b12 installed, but Minecraft isn't using it. You'll need to force it to use the newer version.

https://docs.google.com/document/d/e/2PACX-1vR5muyi1m7Zy_qSwrzeb9e3tbbRlksguNUb_Pvm3pn9eDpsIkUj5qQUq6WFPPdEoVWZq91WvvH57KzC/pub

The above will tell you how to do this. 

Give that a try and see how you get on. 

Regards,

**Comment by artdude543** [comment]
Over a week old and no update. Going to assume this is resolved. Also, 3.0.7 has some fixes and perf boosts.

If the issue is still happening please re-file a new issue (after the update) Thanks!
