### ISSUE TITLE
Storage Progression (Age 0 - The Tutorial Stage)

### ISSUE THREAD

**Issue by Quentalon** [Darkosto/SevTech-Ages#1863]
## Suggestion / Change
Make storage progress more uniformly through the stages.
a stage 0 chest should hold 12 stacks of 16, a shelf should be crafted:
[plank, &lt;immcraft:rock&gt;, plank],
[slab, slab, slab],
[plank, slab, plank]
and hold 16 stacks of 32. Primal chest should be reversed on recipe with advanced primal chest and use leather string in the blank crafting spots to keep effort vs reward even. I am only handling stage 0 storage progression in this thread or I would go on.

## Current Behavior
Currently when people find out that a primal chest holds 9 stacks of 64 vs a shelf holding 16 stacks of 64 they skip the primal chest entirely and avoid the headache for acquiring an essentially useless item.

## Current Work Around
Haven't tinkered with the actual storage capacities, nor adjusted shelf recipes, not on the project, just fixed a couple of things for me and my daughter, I did fix the chest recipes though, that was just silly.

Changed Alt_Scripts.Zs to read as:
`for item in loadedMods["primalchests"].items {
	recipes.remove(item);
}

recipes.remove(&lt;ceramics:unfired_clay:4&gt;);
recipes.remove(&lt;minecraft:dye:15&gt;);

recipes.addShaped(&lt;primalchests:primal_chest&gt;, [[&lt;primal:leather_strip&gt;, &lt;ore:barkWood&gt;, &lt;primal:leather_strip&gt;], [&lt;ore:barkWood&gt;, &lt;immcraft:chest&gt;, &lt;ore:barkWood&gt;], [&lt;primal:leather_strip&gt;, &lt;ore:barkWood&gt;, &lt;primal:leather_strip&gt;]]);
recipes.addShaped(&lt;primalchests:primal_chest_advanced&gt;, [[&lt;abyssalcraft:dltplank&gt;, plank, &lt;abyssalcraft:dltplank&gt;], [plank, &lt;primalchests:primal_chest&gt;, plank], [&lt;abyssalcraft:dltplank&gt;, plank, &lt;abyssalcraft:dltplank&gt;]]);`

## Steps to Reproduce
1. Craft any stage 0 chest/shelf vs primal chest.
2. Observe the capacities and difficulty of crafting.
3. Shake head and sigh.

## Context
Finding out that I would get normal chests in stage 1 made me disinclined to bother with the chests in stage 0.
There is no reason to WANT something from the abyssal plains, so players are "forced" to go there later for specific recipes, this suggestion would give them a reason to CHOOSE to go there.

## Client Information
* Modpack Version: 3.0.6
* Java Version: JDK 8
* Launcher Used: MultiMC 5
* Memory Allocated: 5Gb
* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: Yes (Soartex Fanver Modded Universal)
* Optifine Installed?: Yes

**Comment by artdude543** [comment]
The recipe is designed to point players to the biome as you need one later in the game anyway. I understand about your opinion on the choice. However, we would get complaints later down the line from users about "You never told us to go here or there" With the user base we are working with, and how the progression works we have certain recipes/advancements in place to encourage the player to move around the world and explore it.

Who knows you'll find other stuff along the way, like villages and/or dungeons or new trees/loot. These recipes have meaning behind them. They're not just random ones.
