### ISSUE TITLE
Airship, dismount continue to run forward

### ISSUE THREAD

**Issue by SirBinx** [Darkosto/SevTech-Ages#1864]
## Issue / Bug
Upon dismounting from an airship randomly my character will continue to run in a forward motion until i disconnect/reconnect to the game. 

## Expected Behavior
As listed above I have found my character stuck in a forward running motion after dismounting from an airship after landing.

## Possible Solution
Unknown

## Steps to Reproduce (for bugs)

1. Deploy a ship and fly for a short period
2. Land said ship and disembark it

## Client Information

* Modpack Version: 3.0.6
* Java Version: 9.0
* Launcher Used: Twitch

* Memory Allocated: 4GB

* Server/LAN/Single Player: Server
* Resourcepack Enabled?: Yes
* Optifine Installed?: Yes

## Server Information
* Java Version: 9.0
* Operating System: *NIX
* Hoster/Hosting Soultion: Akliz

**Comment by DeviousCrypto** [comment]
I think the X key which is being used to descend is also bound to auto-walk. You can just press X again to stop, or shift and press back to stop.

Assuming that this is the same issue as I think it is.

**Comment by SirBinx** [comment]
I will have a look at my bindings when I get home from work but this sounds very much feesible, I feel rather dumb for not looking at the the key binds in their entirety.
