### ISSUE TITLE
Symorite buckets lets you cheese past iron buckets

### ISSUE THREAD

**Issue by judicius** [Darkosto/SevTech-Ages#1866]
## Issue / Bug
You can create the Symorite bucket with 3 ingots in the between lands and move liquids with it (ie lava) without getting the iron bucket achievement.

## Possible Solution
Change the recipe so that it can not be made with ingots

## Client Information

* Modpack Version: 3.0.6
* Java Version: 1.8.0.161
* Launcher Used: Twitch

* Memory Allocated: 6 GB

* Server/LAN/Single Player: Server
* Resourcepack Enabled?: Soartex Fanver
* Optifine Installed?: yes

**Comment by lawl281** [comment]
Couldn't you just unlock the symorite bucket recipe after making iron bucket

**Comment by artdude543** [comment]
After talking about this; we are okay with this being a thing. To change the recipe or make it require TC melting would require making a new fluid, which is more things for the game to deal with.

We may go over this again. But for now, we are not going to change how this works.
