### ISSUE TITLE
Rustic's Trees not working for Better with Mod's barrel recipe

### ISSUE THREAD

**Issue by SpectorB** [Darkosto/SevTech-Ages#1867]
There are two instances of ironwood trees, and it would seem that rustics's ironwood spawns above Better with Mod's. Any of rustics blocks (sakura, eukaliptis, etc) do not work for the planks or slabs for the Better with Mods barrel. 

 no other mods or resources installed

 
## Issue / Bug

Rustic trees do not work with Better with Mods barrel crafting recipes.

## Possible Solution

expand of Better with Mods recipes to include rustic planks, ensure Better with Mods Ironwood trees spawn over rustic's.
Make a "bridging" recipe that will allow rustic planks to be converted into planks usable by Better with Mods recipes.

## Steps to Reproduce (for bugs)

1. Creative mode
2. Use a rustic Iron Wood Tree
3, Grow tree, chop log
4. Make logs into planks and slabs
5. attempt to make a barrel on the workstump. This also works with any of rustics trees. No barrel will be produced.

## Context

Cant make barrels without relocating for supported mod trees Q.Q
## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 3.0.6
* Java Version: 8.0.161
* Launcher Used: twitch

* Memory Allocated:

* Server/LAN/Single Player:
* Resourcepack Enabled?:
* Optifine Installed?:

## Server Information
This might be a server issue as well, but experiencing it in client

**Comment by artdude543** [comment]
Closing this due to no response back in a week. And I could not find the issue you were having.
