### ISSUE TITLE
Smelting Copper Clusters in melter yields IE copper blocks

### ISSUE THREAD

**Issue by MongoTheElder** [Darkosto/SevTech-Ages#187]
When smelting Copper Clusters in the melter and pouring into a TC porcelain casting basin you get back what looks like an Immersive Engineering copper block that is restricted until Stage 3 instead of the Embers copper block as intended.

![2017-11-18_20 42 44](https://user-images.githubusercontent.com/29290246/32986502-1b9b3a12-cca1-11e7-900c-171cc0c57389.png)
![2017-11-18_20 43 01](https://user-images.githubusercontent.com/29290246/32986503-2549a738-cca1-11e7-9cee-c853a9addb3e.png)
![2017-11-18_20 43 11](https://user-images.githubusercontent.com/29290246/32986505-27211a00-cca1-11e7-9d58-018d6f3a1a94.png)

Alpha 8, Twitch build

**Comment by Darkosto** [comment]
I've commented out the copper ingot and block lines but need to test. That should allow them to be accessible at any time in the pack instead of stage 3 and beyond.

**Comment by MongoTheElder** [comment]
Strangely, when I logged into my world this morning my Embers copper ingots were changed into a different variant (Vulpes library I think) that was also restricted to Stage 3. I cheated in some Embers copper ingots and they are not able to be hammered into plates.

**Comment by Darkosto** [comment]
That's probably due to Unidictionary attempting to unify items. Once I get everything staged properly it shouldn't be a problem any longer.

**Comment by Darkosto** [comment]
Should be good to go! Thanks!
