### ISSUE TITLE
Duping glitch with Cyclic

### ISSUE THREAD

**Issue by jthawkins95** [Darkosto/SevTech-Ages#1871]
## Issue / Bug
When a *damaged* Cyclic Garden Scythe is used with a Cyclic Automated User, Every crop the user would harvest also drops a copy of that Garden Scythe. Videos attached:
https://clips.twitch.tv/GoodProtectiveAlpacaFunRun
https://clips.twitch.tv/ClumsyHardGarageCeilingCat

## Possible Solution
Yell at the Cyclic mod author.

## Steps to Reproduce (for bugs)
Everything I know about how it was produced is in those two videos.
Damage a Cyclic scythe, somehow (I did it by using it on tomatoes). Use Scythe in Cyclic Automated User. Bam. Infinite blaze rods (via uncrafting table).

## Client Information

* Modpack Version: 3.0.6
* Java Version: 1.8.0.161
* Launcher Used:
Twitch lawnchair
* Memory Allocated:
7gb
* Server/LAN/Single Player: Single
* Resourcepack Enabled?: Nope
* Optifine Installed?: Nope

**Comment by artdude543** [comment]
Fixed in 3.0.7
