### ISSUE TITLE
Unable to craft Starlight Infuser

### ISSUE THREAD

**Issue by 100in33** [Darkosto/SevTech-Ages#1872]
I am attempting to craft Starlight Infuser. Re-checked the recipe countless times. Everything is EXACTLY as in JEI, even hovered over each item to make sure same tooltip comes up in the recipe and what I put in the table. But no output. Have full Starlight in the table, and the table is operational and of proper level. 

Using version 3.0.6

Here is the screenshot of the items in the table, but no output showing 

http://prntscr.com/j5pfh4

**Comment by togreglove** [comment]
Make sure the regular marble under the liquid starlight is Astral Sorcery marble and not chisel marble.

**Comment by 100in33** [comment]
It is Astral Sorcery marble. Re-checked EVERY item multiple times, and hovered over to see the tooltip pop up. Everything is exactly as it is in the JEI recipe.

**Comment by Flaugerxrg** [comment]
this isnt the only thing. I am having issues making starmetal ore in age 3 with update 3.0.6 double and triple checked recipe and made sure that we have enough starlight. it just isnt working. same thing in age 2 with update 3.0.6 making coal engine which i just cheated in and got rid of items.... i cant keep doing that..... it isnt any fun. i really appreciate everything darkosto and the team does but i have asked around and no one has a real answer for it...

**Comment by daddy77gaming** [comment]
A lot of these recipe bugs might have to do with a common Astral sorcery bug, where the starlight levels bug out and you cant craft anything anymore.. Usually fixed with a relaunch of the pack ( not reload of the save )

**Comment by Flaugerxrg** [comment]
Well in my case anyway it is for a server. we have tried restarting the server as well.

**Comment by justinrusso** [comment]
Be sure you have the knowledge to create it. I cannot replicate this issue.
![image](https://user-images.githubusercontent.com/25138621/39226258-43361a34-481f-11e8-8c5f-6bb13637c713.png)

**Comment by justinrusso** [comment]
Please submit another issue if you still have issues.
