### ISSUE TITLE
[3.0.6] Too many dimensions for Journeymap "Edit Waypoint" UI

### ISSUE THREAD

**Issue by Targren** [Darkosto/SevTech-Ages#1873]
## Steps to Reproduce (for bugs)
(0. Be in "Windowed" mode)
1. Create a Journeymap waypoint
2. Launch Journeymap Waypoint Manager (Ctrl-B by default)
3. Click "Edit" next to waypoint. 
4. Observe "Dimensions" list on the right. It goes from "Iapetus" to "Ganymede". There appears to be a scroll bar, but it doesn't function with clicking, dragging, or mouse wheeling?

**Comment by Targren** [comment]
It looks like it was already fixed there (https://github.com/TeamJM/journeymap/issues/4), but we're using an older version.

**Comment by justinrusso** [comment]
Ahh.. I see. Well, unfortunately the dev has taken some time away from modding and they removed those updates as it was kinda broken... Going to have to make this as a known limitation
