### ISSUE TITLE
Sigil of Holding (with sigils in it) is stopping player login

### ISSUE THREAD

**Issue by Sorbe** [Darkosto/SevTech-Ages#1874]
0. From an SMP client player
1. Create a Sigil of Holding using BloodMagic
2. Put other sigils inside of it
3. Log out and try to log back in again.
4. Client fails to log in to server.
5. Fixed by stopping server and, using NBT Explorer to delete the Sigil of Holding

## Client Information
SevTech 3.0.4
Java x64 8u162
Jar Launcher
6GB of Memory
Client to SMP Server

(Please advise if a known issue or this is strictly a Bloodmagic issue)

**Comment by artdude543** [comment]
This is known and will be fixed in 3.0.7 😄
