### ISSUE TITLE
Tinkers' Silk Touched Redstone Block does not work in Mechanical Squeezer

### ISSUE THREAD

**Issue by Fatthunder** [Darkosto/SevTech-Ages#1875]
## Issue / Bug

Mining a redstone block with a Tinkers' Construct pick that has the Silk touch modifier on it, will give back a block that can not be processed in the Mechanical Squeezer from Integrated Dynamics.

## Expected Behavior

Redstone blocks that are mined with a silk touch pick from Tinkers' construct should be able to be processed in the mechanical squeezer.

## Possible Solution

I don't really know what is causing this issue.  I have tested with spawned in blocks (creative) and silk touch enchant, and both work fine.

## Steps to Reproduce (for bugs)

1. Get a Tinker's pick with silk touch
2. Find some redstone ore
3. Mine redstone ore
    -Side note: If you are going to test this, ensure that you have no existing redstone blocks in your inventory, if the block stacks with a block that wasn't mined with the pick, it will process normally
4. Put in Mechanic Squeezer
5. Nothing happens

## Context

I am trying to process redstone ore that I have mined automatically using the mechanical squeezer

## Logs
N/A

## Client Information

* Modpack Version: 3.0.6
* Java Version: 1.8.0.161
* Launcher Used: Twitch

* Memory Allocated: 8GB

* Server/LAN/Single Player: Server
* Resourcepack Enabled?: Yes, Soartex Modded
* Optifine Installed?: Yes

## Server Information
* Java Version: 1.8.0.161
* Operating System: Windows Server 2016
* Hoster/Hosting Soultion: N/A
* Sponge (Non-Vanilla Forge) Server?: No

* Additional Content Installed?: N/A

**Comment by Fatthunder** [comment]
Further investigation shows that Tinkers' pick gives block with Code Name: mundaneredstone:redstone_ore instead of minecraft:redstone_ore.  It looks like the Mechanical Squeezer does is not using ore dictionary for Redstone Ore.

**Comment by justinrusso** [comment]
TIL They have integration with Crafttweaker, not just XML recipes.

1. Move overrided recipes XML file to crafttweaker script
    - This should just be the blaze powder recipe (was 5x, now 4x)
2. Add to unify scripts
3. Determine what should be added/removed

**Comment by DaedalusGame** [comment]
this is a problem in mundane redstone, it should override getSilktouchDrop but doesn't

**Comment by Jandakast** [comment]
SilkVanilla has been set to true for 3.0.7
