### ISSUE TITLE
Closed Channel Exception - Every dimension switch in a SP map.

### ISSUE THREAD

**Issue by SphynxLoL** [Darkosto/SevTech-Ages#1878]
## Issue / Bug

On initian load or between traveling to different dimensions I get a "Internal Exception: java.nio.channels.ClosedChannelException" crash and sent to the server select screen. This is a single player world so it doesn't make much sense. Happens EVERY time i go to ANY other dimension new or previously explored.

## Expected Behavior

Enter portal, spacecraft, or world without an immediate crash.

## Steps to Reproduce (for bugs)
Not sure if it's reproducable.

## Context

Traveling to dimensions is extremely important in this mod pack. Also, it forces me to the main menu so none of my areas can remain chunk loaded in different dimensions.

## Logs

* [Latest.log](https://gist.github.com/SphynxLoL/8f5c35644bf8b26100e04abe72e30309)
## Client Information

* Modpack Version: 3.0.6
* Java Version: jre1.8.0_162
* Launcher Used: Jar launcher (Twitch Settings)
* Memory Allocated: 8gb
* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: No
* Optifine Installed?: Yes "OptiFine_1.12.2_HD_U_D1"

**Comment by justinrusso** [comment]
Sorry for the frustration. We are actively trying to figure out the cause of this issue.

https://github.com/Darkosto/SevTech-Ages/issues/1671
