### ISSUE TITLE
[A8] Chicken passive feathers/eggs

### ISSUE THREAD

**Issue by Dawenzel** [Darkosto/SevTech-Ages#188]
## Issue/Suggestion
After just 3 in-game days I already collected over a stack of eggs and half a stack of feathers from just running around when collecting food. I think this is a bit much and the timers at which they drop these should be longer.

## Possible Solution
The drop rate at which they drop feathers can be altered in the quark.cfg, but I don't know where to alter as the only result when searching for egg/chicken that mentions drop rate is HCChicken from betterwithmods which is disabled.

## Versions
- Minecraft 1.12.2
- Forge 14.23.0.2544
- Java x64 8u144
- Sevtech-Ages Alpha 8

**Comment by Darkosto** [comment]
Lowered from 28000 to 36000 in the quark config.
