### ISSUE TITLE
Advancements Reset on Computer Crash

### ISSUE THREAD

**Issue by xXXStrykerXXx** [Darkosto/SevTech-Ages#1880]
## Issue / Bug
My breaker tripped while I was playing this pack, and once I had restarted the computer and reloaded it, my advancements were completely reset. I tried restoring my progress through the /gamestage commands but those did not work for me. It seems that it still registers me at my current stage, as I have the recipes unlocked up to where I had progressed, but in the advancements I can't access stage one quests anymore.

https://pastebin.com/rBTZKtt3

## Client Information
* Modpack Version: 3.06
* Java Version: 1.8.0_161-b12
* Launcher Used: Twitch Launcher
* Memory Allocated: 10GBs

* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: Faithful 32x
* Optifine Installed?: No

**Comment by justinrusso** [comment]
Gamestages and advancements are two different things. You will need to use the /advancement grant @p` command

**Comment by xXXStrykerXXx** [comment]
Okay thank you. At least I can continue where I left off. Any idea what is causing this reset on crashes? I've seen it's happened to some other people as well.

**Comment by justinrusso** [comment]
Corruption I'd assume? These issues from what I recall all involve a power outage or some other unexpected shut down of the computer which is out of our control.
