### ISSUE TITLE
(Kind of) invincible skeletons

### ISSUE THREAD

**Issue by xy795** [Darkosto/SevTech-Ages#1881]
## Issue / Bug
All sorts of skeletons take no damage of TC punji sicks / Cyclic Iron Spikes. They make sounds like they get damaged, but their health stays up if they are standing in range of the spikes.

![invincible_skeletons](https://user-images.githubusercontent.com/16350102/38788331-642504f0-4133-11e8-9649-39f2d8b33341.gif)

## Expected Behavior
Skeletons take damage/die if in range of punji sticks/iron spikes.

## Steps to Reproduce (for bugs)

1. Place punji sticks/iron spikes.
2. Push skeleton in range of them.

## Context
Trying to build a mob farm.

## Client Information

* Modpack Version: 3.0.6
* Java Version: 1.8.0_162
* Launcher Used: MultiMC

* Memory Allocated: 8192 MB

* Server/LAN/Single Player: Server
* Resourcepack Enabled?: No
* Optifine Installed?: Yes (not relevant)

## Server Information
* Java Version: 1.8.0_45
* Operating System: CentOS 7
* Hoster/Hosting Soultion: Own dedicated Server
* Sponge (Non-Vanilla Forge) Server?: No

* Additional Content Installed?: No

**Comment by Dutchs** [comment]
Looks like a duplicate of #1419

**Comment by xy795** [comment]
Whoops youre right, I apperently just searched for open issues.
Im sorry.
