### ISSUE TITLE
Creeping Moss turns to Ocean-Biome, and sets the chunk as Ocean

### ISSUE THREAD

**Issue by MrHrulgin** [Darkosto/SevTech-Ages#1883]
## Issue / Bug
Creeping Moss turns to Ocean-Biome, and sets the chunk as Ocean. I tested it with a legit-crafted end-biome moss, and then cheated in others to check.

## Expected Behavior
I expected the moss to not become tagged with the ocean biome, and the chunk to change to the appropriately tagged biome.

## Possible Solution
I'm not sure. It seems to be calling the ocean biome ID regardless of what biome it says it is.

## Steps to Reproduce (for bugs)
Cheat in or craft an End-biome creeping moss. Go to the hunting dimension. Use said moss. Get two notifications that "The biome of the chunk has been set to minecraft:ocean." See moss now have Ocean-biome.

## Context
I was hoping for a more consistent way to obtain ender pearls for the search for a stronghold, and spent a good bit of time building Astral Sorcery infrastructure to turn sandstone to endstone for this moss.

**Comment by artdude543** [comment]
I can't reproduce the issue you are having as below you can see that it did change to the correct biome.

![image](https://user-images.githubusercontent.com/1885466/39218727-045ff90c-481e-11e8-908f-75b4005f7a1f.png)

You also can't craft the biome you want per-say you need to visit the biome/dim and shift-right click to get the biome changed on the moss are holding. I have added a tooltip in 3.0.7 which should help with this.

**Comment by demosthien** [comment]
@artdude543 

I also encountered this issue using a coralium swamp moss.

The first use changed a chunk into the swamp and each subsequent use in different chunks produces a message saying the biome was set to ocean.

**Comment by Jandakast** [comment]
This isn't an issue. You sneak right click while you are in the biome you want, with the moss in hand. 

Then you use the moss in the hunting dimension.
