### ISSUE TITLE
Blood Magic's Lava Crystal is not draining LP.

### ISSUE THREAD

**Issue by JRiebling** [Darkosto/SevTech-Ages#1885]
## Issue / Bug
Blood Magic's Lava Crystal is not draining LP to perform smelting.

## Expected Behavior
Lava crystal uses 50LP (according to in-game Sanguine Scientiem) per smelting operation.

## Steps to Reproduce (for bugs)
1. Check personal blood network via Seer's Sigil.
2. Put Lava Crystal in regular Furnace.
3. Put something to smelt in Furnace. (I tried raw potatoes and soul sand.)
4. Wait for finished products (e.g. baked potatoes, soul glass).
5. Check personal blood network again with Seer's Sigil.
6. Realize that the LP hasn't changed. Infinite fuel!

## Context
I mean, I just finished my T4 Blood Altar to get easy LP, but not this easy... I checked that LP is being drained by turning on my Bound Sword, and I checked that none of my orbs are on my blood altar to replenish my LP instantly. Oh, and I'm not using Coat of Arms or Bloodletter's Pack (I forget which one gives you passive LP.)

## Client Information

* Modpack Version: 3.0.6
* Java Version: 1.8.0.160
* Launcher Used: Twitch
* Memory Allocated: 6192
* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by artdude543** [comment]
This is resolved in 3.0.7 if you still find this to be a bug please re-file the issue :)
