### ISSUE TITLE
3.0.6 Rock crystal ore not spawning at all

### ISSUE THREAD

**Issue by Flow86** [Darkosto/SevTech-Ages#1887]
Hi,

I'm using the 3.0.6 version of the modpack. Map was started with 3.0.5.
I now have progressed to Age 2 and try to find rock crystal ore. Ive found some very rare rock crystal samples, but can't find any veins. 
I also checked via /oredistribution command if there's any, but it seems it does not get generated at all? (I also went to very far away "new" chunks, no rock crystal ore anywhere.

**Comment by Fatthunder** [comment]
/oredistribution Does NOT work with rock crystal (along with some other ores).  The veins can be very small and mixed in with bedrock.

**Comment by Flow86** [comment]
okay thats weird then. I'll again try to find some
