### ISSUE TITLE
Impossible to pick back the uncooked item on grill

### ISSUE THREAD

**Issue by Fireztonez** [Darkosto/SevTech-Ages#189]
When youu right click with an item on the grill is put item for cooked, that is normal. But what's apen if you pub item can't be cooked or you simply whant to pick back the uncooked item?
On that case, you canot take the item, a right click whit empty hand doesn't work, a left click  doesn't work either. And a shift + Right click you pick-up the grill with carry-on.

So, the only way to get back your item, is broke the grill with a pick-axe and place back.

I think that will need to be fix!

**Comment by Darkosto** [comment]
It's actually setup to not pickup the block when you are 2.5 blocks further away, having said that, I removed the grill from being used with Carry-on completely.
