### ISSUE TITLE
Enhancement: Get 'Just the Tips' author to add stages support

### ISSUE THREAD

**Issue by Ozzymud** [Darkosto/SevTech-Ages#1891]
I know this would require an ask to the Just the Tips mod author, but it would be really cool to see tips related to the stage one is currently in. Figured I'd toss the idea here as I don't know where else to put it. 

Edit: Suggested over there now :)

**Comment by justinrusso** [comment]
I'm not sure the dev will be able to do this... Either way, if it does happen we can consider it then, but I'll close the issue here for the time being.
