### ISSUE TITLE
Random(?) crashes

### ISSUE THREAD

**Issue by lliinnkk10** [Darkosto/SevTech-Ages#1892]
## Issue / Bug
The crash seems to happen randomly, mostly when I change program and then switch back to minecraft, sometimes it crashes instantly when opening minecraft and sometimes only after I issue a command like opening or closing a gui.

## Steps to Reproduce (for bugs)

1. I can't seem to replicate it with success, it just happens randomly.

## Context
I can't really add any information at this point seeing as I have no idea what is actually causing the crash. It wasn't a problem in earlier versions.
I will try to answer any questions to the best of my ability, thanks in advance.

## Logs

* Client/Server Log: https://gist.github.com/lliinnkk10/06bb39eac800ca863c774d676ddb5039
* Crash Log: https://gist.github.com/lliinnkk10/8dc08714d671b32a3a7fd3c54d92819f
## Client Information

* Modpack Version: 3.0.6
* Java Version: jre1.8.0_161
* Launcher Used: Twitch

* Memory Allocated: 14096m

* Server/LAN/Single Player: Single player
* Resourcepack Enabled?: Yes
* Optifine Installed?: No

**Comment by SteseDav** [comment]
How much RAM is available to the machine? (I can see you are allocating 14GB to minecraft.) I'm seeing notes all over the place that allocating more than half your available RAM to minecraft causes all kinds of issues. 

I'm running the pack fine on 6GB, and I know others who've allocated 4GB with no issues. Why are you allocating so much?

**Comment by lliinnkk10** [comment]
I have 16 on my machine. Two reasons, everytime I start the minecraft launcher it resets to 4 and I'm lazy so I just put a 1 before 4 and I thought more = better. I'll try with 6.
Thank you for your reply.

**Comment by SteseDav** [comment]
@lliinnkk10  you can force the amount of ram in the twitch launcher, rather than having to do it in the minecraft launcher each time. 

"click the three dots and select "Profile Options". Under "Memory Settings", you can uncheck "Use System Setting", and set the memory usage per modpack"

**Comment by lliinnkk10** [comment]
Oh I didn't know that, thank you! :D

**Comment by SteseDav** [comment]
No worries.  Once you've tested with 6gb, please repost here if the issue can be closed.

**Comment by lliinnkk10** [comment]
It had been working fine all day long, but now it crashed totally randomly it seemed like.
https://gist.github.com/lliinnkk10/6311d42221fc2ed1cf36392936b59405 Here is the crash log, thanks in advance

**Comment by lliinnkk10** [comment]
And now it crashed when I pressed single player
https://gist.github.com/lliinnkk10/58bf656d78bb9ec95e686eff3dad8851
Should I try to install new again or?

**Comment by SteseDav** [comment]
Two things stick out in your recent log.

- Java Version: 1.8.0_25, Oracle Corporation < you seem to be using the packaged java rather than the installed one. Follow this guide to force to the latest. https://docs.google.com/document/d/e/2PACX-1vR5muyi1m7Zy_qSwrzeb9e3tbbRlksguNUb_Pvm3pn9eDpsIkUj5qQUq6WFPPdEoVWZq91WvvH57KzC/pub

- You are still allocating 14GB of ram to the pack. As you only have 16GB you are likely strangling the resources on the OS, which could cause all manner of issues. In you case, don't assign more than 8192 MB(8GB).

**Comment by lliinnkk10** [comment]
I did what you told me and it has been working a lot better, only crashed once today.
Thank you very much for taking your time.
