### ISSUE TITLE
Lack of information on Modular Machinery

### ISSUE THREAD

**Issue by 100in33** [Darkosto/SevTech-Ages#1893]
I am at the progression stage where I have to use Modular Machinery. I need to make a Chemical Mixer to be precise. I have never even heard of the mod, so I got to see if anyone has a tutorial on this or built the machine in an episode of their own on YouTube. This is what I get when I look up Modular Machinery Chemical Mixer:

http://prntscr.com/j5yw70

As much as I despise mods like Open Computers or any mod that has the word "Modular" in it (because I'm an old dog and unable to learn new tricks), I am willing to struggle through it, because I LOVE the pack and the concept of it. But there is simply no information on exactly how I build this machine, not in the quest description or the materials in the pack, nor could I find any on YouTube.

**Comment by 100in33** [comment]
Hello Ixanza. Thank you for the response. I have found this out so far, that this is fully customizable by pack maker. I know this is a "me" issue, that I have difficulties following processes like these. For example, it took me forever to realize that I can drag that structure with my mouse to turn and see other sides, which finally led to a successful completion of this machine (I then try to shift-click a capsule of Naphta into the input and crashed the pack). But I wonder how many more like me out there that find the lack of information on this mod in form of a video tutorial difficult to follow and complete. I can already feel that I will struggle greatly as I have no clue how to input fluids into this machine, as there are no conventional methods such as Fluid Conduits from Thermal Foundation that can just use servo filters to pull and push fluids from the tanks. I am sure I can use the pipes that are available, but I am unfamiliar with any of them. It seems that what I am asking here (more information on Modular Machinery) as an improbable request. Doubt anyone would sit down and record "how to" on machines designed specifically for this pack.

**Comment by daddy77gaming** [comment]
The blueprints have even more buttons you can use to see the structure layer by layer, its just something different then your used to, whenever you will play another pack with this in it, you wont have any problem :) 

on The import output system.. you can go a couple of ways, but I would go for the cyclic fluid extraction cable and fluid pipes ( as they are way cheaper and easier then BC )
For tanks I would go for inductive logic tanks, big and fairly cheap.

**Comment by 100in33** [comment]
I agree. There is just lack of instruction/information. I never heard of this mod, and I am a hardcore modem Minecraft player, who played ALL Darkosto's packs, all mainstream packs, and countless others. If I don't get it, there has to be tons of people who don't get it.

**Comment by justinrusso** [comment]
Honestly I'm not sure this is too much of an issue. This is really the first time hearing this complaint about it.

Either way, I'm not really sure what we could do about this. I would suggest leaving any feedback on https://github.com/HellFirePvP/ModularMachinery/issues if you'd like.
