### ISSUE TITLE
Zaphkiel Waltz issues

### ISSUE THREAD

**Issue by tonyvans** [Darkosto/SevTech-Ages#1894]
I apologies if I am just doing something wrong,  I with seem unable to start the Zaphkiel Waltz. so far I have managed to infuse the flute and get the buffalo but now are stuck in progression with the red cedar.

Followed the guide and used the drum and rattle to start it but the progression bar will not start. a couple of us tried for about 30 mins then gave up. Tried googling issues but found nothing.

Help, Thanks

**Comment by KovaiTwitch** [comment]
To start every ritual you need to use the instrument stated in the book with shift right click and then use any other instrument till the end

**Comment by tonyvans** [comment]
yea I painfully discovered that with the buffalo dance, but will try again, progression is interesting but I am also finding certain requirement tedious. I was mostly checking to see if anyone else has had issues.

**Comment by tonyvans** [comment]
apparently one of the other guys got it to work finally, thank you
