### ISSUE TITLE
Age 2: no advancement when starlight crafting altar is completed

### ISSUE THREAD

**Issue by FFwarrior** [Darkosto/SevTech-Ages#1896]
## Issue / Bug

Not able to get the advancement for creating the starlight crafting altar.

I installed the server by using the batch file included in the server download and installed the client with the Twitch launcher. No other modifications have been made.

## Expected Behavior

After the starlight crafting altar is triggered with the resonating wand, it should create the starlight crafting altar (which it does after a bit of a delay) and then give the achievement/advancement.

## Steps to Reproduce (for bugs)

1. Place all materials in exact positions and add materials to current table
2. Right click on new altar with resonating wand at night.
3. Wait for luminous crafting table to transform
4. Look for advancement (and see that it didn't work)

## Context

I cannot progress at all until I get this advancement achievement.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 3.0.6
* Java Version: Java 8 Update 161(x64)
* Launcher Used: Twitch

* Memory Allocated: 8GB

* Server/LAN/Single Player: Server (LAN)
* Resourcepack Enabled?: Soartex
* Optifine Installed?: No

## Server Information
* Java Version: Java 8 Update 161(x64)
* Operating System: Windows 10
* Hoster/Hosting Soultion: Self owned server
* Sponge (Non-Vanilla Forge) Server?:

* Additional Content Installed?: No

**Comment by BonaireDreams** [comment]
Use your Bronze (or better) pick. Not sure if Stone pick destroys it or not, but better to be safe. I had to look up this same thing last night and was able to pick it up with my bronze pick,

**Comment by FFwarrior** [comment]
It worked! thanks!
