### ISSUE TITLE
NEI Item ID's do not show up

### ISSUE THREAD

**Issue by 88880** [Darkosto/SevTech-Ages#1897]
## Issue / Bug

I am trying to find the ID's of blocks in my inventory with NEI. No information shows up. Is it locked in Age 1? Am I missing something obvious?

Also not really related but I am attempting to worldedit a wall with **_Ironwood Planks_** but the console cannot figure out what block I mean when I write **_4276:1_**. How can I use modded blocks in the console so that minecraft knows what I am talking about?

Thank you for reading

## Client Information

* Modpack Version: latest
* Java Version: latest
* Launcher Used: Native

* Memory Allocated: 6G

* Server/LAN/Single Player: Single
* Resourcepack Enabled?: N
* Optifine Installed?: Y

**Comment by TexanMD** [comment]
For your worldedit issue, try using the Minecraft id instead of a block id.   It should be something like twilightforest:planksironwood or similar.   You can enable block ID information in WAILA and point at a block in world to see what it is.

**Comment by artdude543** [comment]
This tracker is for modpack issues, not WorldEdit / User issues. As suggested above use an instance of the game to get the correct naming. Also, MC does not use front facing Id's anymore (only internally) so it's now `modid:item_block_entitiy`
