### ISSUE TITLE
[Blood Magic] Aura of Expulsion: Very Costly Pinball Glitch

### ISSUE THREAD

**Issue by DrunkOctopus** [Darkosto/SevTech-Ages#1898]
Sorry for the length of this..summary: making a grid of auras of expulsion teleports players between the auras until they typically end up underground and/or using a large portion of the 1,000,000 LP in the player's soul network for what looks like just a single teleport. 

Auras of Expulsion from Blood Magic are supposed to teleport players away from your base, but if you have multiple Auras of Expulsion linked together like a grid they act as a pinball machine before teleporting the victim into the ground
The unwhitelisted player will begin shuddering, their screen looking like a pokemon being slashed, and find themselves unable to anything except press the escape button. (They will appear to not be moving at this point). This is where they are being teleported between the (51x51x51 with no overlap some at varying heights) no entry grids. It sucks to ruin such a good troll, but unfortunately there is no function in the auras anymore. I can store up 1,000,000 LP (energy to power the auras) but just glitching the player out in say the central grid..could very well use up 150,000 LP without even teleporting the invader away (that's 150 teleports 1,000 LP per teleport btw)
Please, for the love of all things unholy, add a safeguard that checks if the player is being teleported into another aura of expulsion and tries again without using LP :D It'd be of great help.
I don't have any logs. I have 9 auras of expulsion and the closer you are to the center of the base the glitchier it gets.
I've noticed that most of the time you get teleported underground (which isn't that big an issue to me), but it is if someone wants to get their items back because the player may spawn under my base and their grave floats up to the surface. I've seen the player teleported underground near the borders between my aura grids before. Maybe some tiny fraction of space exists between my auras?

Expected Behavior
I was half expecting players to be teleported on the surface to a safe space that won't just teleport them again, part of me was also wishing this wouldn't happen.

Possible Solution
Adding some sort of variable for if ( player != teleportLocationunderground || teleportLocationInAuraZone ) then use 1,000 LP and teleport, else do not use 1,000LP and run another location. Lengthy variable names but you get the picture. You could also check if the aura zone is bordering another aura, thus saving time when you run the code by it skipping those zones all together. 

Possible Issues with that Solution
If you just airdropped into the center of my grid the only place the game could teleport you is above the grid. So one better solution would be to include the other auras in a no teleport zone and look for the nearest safe locations to the edge of the no teleport zone. 

This is a lot to ask over one feature, but in a multiplayer game I personally find a player's safety while offline is mission critical to retaining your supporters. The more ways that allow players to take breaks or relax the better because they won't burn out as quickly

Steps to Reproduce (for bugs)
1. Get blood magic and make 9 auras of expulsion some varying in height no more than 5 blocks with no overlap between the borders
2. Walk into one of the grids
NOTE: There is a chance the grid just teleports you away after the first try (almost always underground), however the chance of it using up thousands of LP raises if you are in the center of the aura grid. I will upload another video as soon as I can that shows that specific "pinball issue"

Context
I'm trying to make an expulsion-field grid to protect a city
(Video #1 coming soon)
(Video #2 coming soon tm lel)

Client Information
Modpack Version: 3.0.6
Java Version: Latest J8
Launcher Used: Native
Memory Allocated: 8.5gb
Server/LAN/Single Player: Server
Resourcepack Enabled?: No
Optifine Installed?: No

I'm not the server owner but I'll try to update this information when I get it
Server Information
Java Version:
Operating System: 
Hoster/Hosting Soultion:
Sponge (Non-Vanilla Forge) Server?: No, I wish
Additional Content Installed?: No

You guys are the best!
Many Thanks, 
- Darkathenes.

**Comment by TexanMD** [comment]
Is this a SevTech specific issue?  Or does this happen with only blood magic?

**Comment by DrunkOctopus** [comment]
Not sure, this is the first modpack I've ever played

**Comment by ParadoxBomb** [comment]
This sounds more like an issue to be taken up with BloodMagic, as it deals solely with that mod.

**Comment by DrunkOctopus** [comment]
Will do!
