### ISSUE TITLE
Immersive book crashes?

### ISSUE THREAD

**Issue by TheLemein** [Darkosto/SevTech-Ages#1899]
So I do not get any crash reports, just Minecraft closes and default crash pop up shows up.. But seems when I am looking in the immersive engineering book (watching the multiblock setups) I crash about 3 out of 5 times.. I know, not much to go by, just strange. I will try to snap a video of it, and upload if possible

**Comment by KitanaShaw** [comment]
make sure you have java update since one of the old versions causes a crash with immersive book

**Comment by BonaireDreams** [comment]
When you first log into your world hit "t" and scroll up. I bet you have the warning "You are running Java 1.8.25. This version is known to crash with Immersive engineering manual and we cant fix it. Please update your Java."   That said if you are using the native Twitch launcher it always uses the latest minecraft officially supported Java which happens to be 1.8.25. You would need to switch Twicth to use the Jar launcher to specify a different Java version.

**Comment by Chalmes** [comment]
I'm also getting the same error when reading the IE book.  I'm aware of the issue it has with older versions of Java, but i'm using the jar version of the launcher, and version 1.8.0_31-b13 of Java.

Relevant lines from hs_err_pid4768.log:

```
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x0000000058313aaa, pid=4768, tid=11712
#
# JRE version: Java(TM) SE Runtime Environment (8.0_31-b13) (build 1.8.0_31-b13)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.31-b07 mixed mode windows-amd64 compressed oops)
```

**Comment by justinrusso** [comment]
Update Java
