### ISSUE TITLE
How to light the ImmersiveCraft Furnace

### ISSUE THREAD

**Issue by davqvist** [Darkosto/SevTech-Ages#19]
As the ImmersiveCraft Furnace is an advancement, I suppose you should be able to use it, but I wasn't able to light it. I think per default you need Flint&Steel or a torch to do it, both you don't have access to. Neither Firesticks, the Roots Firestarter nor a Lit Twine Torch was able to do it.

**Comment by Darkosto** [comment]
This has been added as a feature request to Immersivecraft:

https://github.com/McJty/ImmersiveCraft/issues/32

**Comment by Darkosto** [comment]
I actually just removed this from existence. FIXED!
