### ISSUE TITLE
Flinty flint!! Drop of flint!!

### ISSUE THREAD

**Issue by Fireztonez** [Darkosto/SevTech-Ages#190]
Sevtech Alpha 8
Imported by MultiMC export ZIP
Forge 14.23.0.2515

I started shoveling earth, around my makeshift base on the seashore, and I got a piece of flint that was dropped by the earth.

I know that your goal was that the flint be accessible by the recepe with the mesh, so, I return the probable bug.

And, I always forgot, sorry, I know is your birthday today, so, Happy Birthday!!
I will bring you a good Pumkin Pie with a Death Wish Coffee grains at the top!!

Fireztonez

**Comment by Darkosto** [comment]
Yep, sometimes flint drops from other blocks and that's okay. The point was to allow for a consistent flint recipe and not relying on the RNG of breaking blocks.

**Comment by Fireztonez** [comment]
Oki, thank's for that information!
