### ISSUE TITLE
/forge gen command

### ISSUE THREAD

**Issue by KatharineRosewood** [Darkosto/SevTech-Ages#1900]
I'm rubberbanding really badly when i'm exploring but my CPU is fine, my RAM is fine and my GPU is fine. Which is why i wanted to use this command but i can't seem to figure out how it works. Can someone please help?

**Comment by justinrusso** [comment]
https://github.com/Darkosto/SevTech-Ages/wiki/Pre-Generate-Command

**Comment by TexanMD** [comment]
It'll be easier for someone to help if you could list how you've tried the command so far.

If I wanted to generate 100 chunks centered on 0 0 0, i'd try:
`/forge gen 0 0 0 100`

**Comment by KatharineRosewood** [comment]
Justin that doesn't help at all. I already checked that page but it's one fucking line. No explanation at all.

**Comment by TexanMD** [comment]
@KatharineRosewood did you try what I listed?  100 should be fine for a test of the command, but if you want to generate something useful in size, i'd probably do something like 5000.

**Comment by KatharineRosewood** [comment]
I figured it out because of your comment and now i used 10000
