### ISSUE TITLE
[3.0.6] [Abyssalcraft] [Stage 3] Cyclic requirements for Refining Coralium?

### ISSUE THREAD

**Issue by Targren** [Darkosto/SevTech-Ages#1901]
## Issue / Bug

From what I can gather from JEI, getting refined coralium is just a matter of feeding coralium chunks into the Abyssalcraft Transmutator, but the transmutator recipe requires 2 blocks of refined coralium?  

Tested in a Creative Test World with all advancements granted and all AC knwledge unlocked, and saw a grindstone recipe for Liquified Coralium Ore -> Refined Coralium Dust, but there doesn't seem to be a recipe for the ore, either. 

## Possible Solution

I don't know if this is a case of a recipe missing for an intermediate step or just something I'm overlooking. 

## Context

Trying to progress in Abyssalcraft

## Client Information
* Modpack Version: 3.6.0
* Java Version: 1.8.1_161
* Launcher Used: MultiMC 5 0.6.2
* Memory Allocated: 6GB
* Server/LAN/Single Player: SSP
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by LycanBlackpaw** [comment]
Okay so this is gonna be a little long: To progress in Abyssalcraft you have to create a Gateway Key. This allows you to create your first portal (nether portal shape) to the first Abyssal dimension-the Abyssal Wasteland. While here, you can find Liquified Coralium Ore down around vanilla diamond level; when smelted, this is what produces Refined Coralium. The transmutator is a later option to create the materials from other items, similar to the way Project E would work but more balanced.

To gain this knowledge, you need an item called the Staff of Rending; when held and right clicked when aimed at certain mobs (shadow creatures in any dimension, depths ghouls and abyssal zombies in the wasteland, and so on) you can gain special essences; these are used to create the upgrade material for your Necronomicon, which gives you the knowledge of that dimension.

**Comment by Targren** [comment]
I've gotten into the wasteland and generated my 2nd tier Necronomicon, mixed antimatter with coralium and got a pile of coralium stones. I went crazy with trying to find recipes around that; no luck there. The Necronomicon doesn't mention that Liquified Coralium ore spawns in-world. I found the Abyssal Coralium ore and thought it had to be modified to liquify it.  If I actually have to mine it out, that makes sense, though there could be a more straightforward way of informing the player than a wonderfully helpful commenter on the issue tracker. :) 

Thanks for the help!

**Comment by daddy77gaming** [comment]
A sidenote here:

In your necronomicon (for each dimension) you have a section materials, if you read thru that you will find a page about liquified coralium, where it does state it spawns at y22 and below.

Since abyssalcraft gates itself by hiding knowledge, reading what you can in abyssalcraft is what knowledge you need to progress.

**Comment by Targren** [comment]
@daddy77gaming You're right.  I think I clicked on the wrong arrow that made it jump several pages, skipping right over the pages for Liquified and Pearlescent Coralium ores. It went right from Fused Sand to the Dreadlands power stone.  

Weird UI, that, but yeah, that's on me.
