### ISSUE TITLE
Engineering manual CTD

### ISSUE THREAD

**Issue by extrenix** [Darkosto/SevTech-Ages#1903]
Having the manual opened when having the game Opened to LAN results in crash to desktop when the book is opened for several seconds.

replicable. happened 3 times now.

## Client Information

* Modpack Version: 3.0.6
* Java Version:1.8.161

* Memory Allocated:12gb

* Server/LAN/Single Player: LAN
* Resourcepack Enabled?: yes?
* Optifine Installed?: yes

<!--- Additional Information if you are using a server setup (DELETE THIS SECTION IF YOUR ISSUE IS

**Comment by justinrusso** [comment]
Are you sure you are using that java version? When you load into the game, does it show a warning in the chat?

**Comment by csg1995** [comment]
how to change your java version, might be worth pinning this somewhere
https://docs.google.com/document/d/e/2PACX-1vR5muyi1m7Zy_qSwrzeb9e3tbbRlksguNUb_Pvm3pn9eDpsIkUj5qQUq6WFPPdEoVWZq91WvvH57KzC/pub

**Comment by extrenix** [comment]
CSG1995, 
I do what it says in the docs. Then I hit play and it's running an older launcher for some reason.

**Comment by extrenix** [comment]
nvm. found how to fix it.
tnx
