### ISSUE TITLE
Uranium Ore has no use? What am I missing here?

### ISSUE THREAD

**Issue by Dragonchampion** [Darkosto/SevTech-Ages#1907]
So, I've been trying to do research, through every mod SevTech has, and every single thing I can do, but I cannot for the life of me figure out what use Uranium has! Is it useless?

**Comment by Targren** [comment]
According to Mischief of Mice's IE "Bit by Bit", it can be used next to thermomagnetic generators?

**Comment by artdude543** [comment]
The ore is made into the ingots/dusts which is used in a few recipes for progression purpose. We've added more recipes in 3.0.7 also for the ingots so it defo has a use!
