### ISSUE TITLE
venus tier 4 rocket schematic

### ISSUE THREAD

**Issue by Noxtralis** [Darkosto/SevTech-Ages#1908]
## Issue / Bug
 Tier 4 rocket schematic is insanely hard to find
 Add recipe as well on the rocket schematics like crafting it with stuff you find from said dungons (rover schematic, shield controller, volcanic pick)
n/a
n/a

## Expected Behavior
 One would expect to find it after 2-3 dungeons. I have been through 30. 
 Adding a recipe at least gives you the feeling of progression and somehow mitigates the frustration. 

## Context
 Trying to progress
 cannot go further in the pack as rocket cannot be crafted

## Client Information

* Modpack Version: 3.0.6
* Java Version: 1.8.0.161
* Launcher Used: JAR
 8GB
* Memory Allocated:

* Server/LAN/Single Player: Server
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by MJRLegends** [comment]
Wrong planet, there is two tier 3 planets, mercury is the one you want to be going to not venus for the tier 4 rocket

**Comment by Noxtralis** [comment]
The wiki for extra planets says its venus. that`s why I got a bit confused. 

Sorry for the trouble.

https://ftbwiki.org/Tier_4_Rocket_Schematic_(Extra_Planets)

**Comment by MJRLegends** [comment]
thats not a official wiki and probably for the mc 1.7.10 version

**Comment by Hazmatik** [comment]
Sorry for necro posting on this old thread but I would just like to point out that the tooltip for the tier 4 schematic does say that it can be found on Venus. I just spent a few hours searching Venus dungeons before finding this post telling me I've been looking in the wrong place. Might want to think about fixing the tooltip to be accurate.
[![https://gyazo.com/b59af76057d42d537394d7ed127599aa](https://i.gyazo.com/b59af76057d42d537394d7ed127599aa.png)](https://gyazo.com/b59af76057d42d537394d7ed127599aa)

**Comment by MJRLegends** [comment]
GG great way to confuse people

**Comment by Jandakast** [comment]
So is there official documentation or official wiki somewhere?

**Comment by MJRLegends** [comment]
@Jandakast the tool tip above is added by sev tech, should be Mercury not Venus

**Comment by Jandakast** [comment]
I know, and I will fix it. I'm asking you if there is an official place for information on your mod.

**Comment by MJRLegends** [comment]
No as all information is in game
