### ISSUE TITLE
Decontamination chamber crash loop

### ISSUE THREAD

**Issue by Xetard** [Darkosto/SevTech-Ages#1909]
I crafted a decontamination chamber to help me reduce my radiation.
It took me forever to fill it up with power but when i was halfway done i shift + rightclick on it and it crashed me and sent me into a crash loop. I've tried about 5 times now and i never get into the world before crashing.

Soartex textures
3.0.6
No optifine

https://pastebin.com/vBufSaQF

**Comment by MJRLegends** [comment]
@Xetard You can always remove the Hwyla while this is still a issue to get in to your world, but it will be fixed very soon

**Comment by Xetard** [comment]
@MJRLegends Glad to hear it will be fixed, i will just wait until resolved

Thank you for the information tho!

**Comment by MJRLegends** [comment]
ExtraPlanets updates have been upload to CurseForge :D and fixes this issue

**Comment by artdude543** [comment]
This is updated in dev and will be included in 3.0.7
