### ISSUE TITLE
[3.0.6] Load-Loop or Exit-to-Menu (Internal Server Shutdown) on Game/Dimension loads

### ISSUE THREAD

**Issue by Targren** [Darkosto/SevTech-Ages#1911]
## Issue / Bug

This one's going to be tricky to explain, much less debug. 

Ever since the 3.0.6 update, I've been having an issue where the game will either hang on loading from save, then "gracefully" exit to the menu, or will simply loop the loading screen until killed/closed.  

When loading from the save, the auto-shutdown generally only happens on the first load after starting the game. After that, it will either load successfully on the next load, or it will fall into the "loading loop". What determines whether it's successful or not seems to hinge on whether the logout was in the overworld: if yes, then the second load attempt usually works. (I suspect it may have to do with staging timing, because the second load attempt in the overworld sometimes (about 4/10 times so far) the second load will start with "You dropped the Unfamiliar Item" and my Dog Pelt Boots disappear until my character syncs up.)

If not the overworld, then loop. 

In the attached logs, the "other dimension" in question is the Abyssal Wasteland, but I've experienced the same thing with The Nether and the Betweenlands, as well. I have not had any problems with it going to/from the Hunting Dimension or TF. 

The log files below contain both behaviors: the first load shuts down and returns to the menu. Second attempted load results in the loop described.

## Expected Behavior

Not that. 

## Possible Solution

I couldn't even guess. Are the dimensions themselves staged, or just the methods of travelling between them?

## Steps to Reproduce (for bugs)

1. Cross over to the Nether/Betweenlands/Abyssal wasteland
2. Be unlucky. 

## Context
In my actual game world, loading back in has resulted in spawning in some horrible places (40 blocks up over the lava ocean in the Nether, buried in 60 blocks of stone in AW, etc..), usually near the origin of the world and nowhere near the portal. (Luckily, quick cheat activation has prevented too many horrible losses so far). Shutting down/crashing in the portal seems to lose location data. 

The "test world" that was used to create the logs appears to be permanently stuck. It hasn't loaded successfully since the issue manifested in it. 

## Logs

* Client Log: [latest.log](https://gist.github.com/Targren/bcc28fd20c50d08e2b7388dd7a1e6ee2) 
* Debug Log: [debug.log](https://gist.github.com/Targren/d9625cbed953abda4e29b9519a645524)

## Client Information
* Modpack Version: 3.0.6
* Java Version: 1.81_161
* Launcher Used: MultiMC 5 0.6.2
* Memory Allocated: 6GB
* Server/LAN/Single Player: SSP
* Resourcepack Enabled?: No
* Optifine Installed?: No
* Mods Disabled: SmoothFont, BetterFoliage, Mo'Bends, Fancy Block Particles

**Comment by SphynxLoL** [comment]
Having this same issue as well. I have been informed that they are currently working on fixing it. You just have to try to deal with it the best you can until they release a patch. It is quite annoying since the pack revolves mostly on traveling to different dimensions to collect materials. But hey, on the bright side, at least it is a crash-to-menu (most of the time) instead of a full crash-to-desktop.

**Comment by CSTufts** [comment]
I consistently get a similar crash on login (just once each time, I have attached my logs)

admins tell me if this is a differnt issue I will open in a new bug if you would like
also can back up my world file if you want to try it

on a mac, just updated

$ java -version
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

can try updating java if you would like

thanks!

[servercrashlog.txt](https://github.com/Darkosto/SevTech-Ages/files/1933492/servercrashlog.txt)

**Comment by Targren** [comment]
> also, I am attempting to log in locally, and it crashes out to the multiplayer screen, if that helps at all...

Mine does that too. I totally forgot to include that part...

**Comment by artdude543** [comment]
This should be resolved in 3.0.7 however if the issue persists please make a new issue with new logs/data for us to further look into the issue. Sorry about this one guys; it's been a fun one to track down and/or get fixes for.

But get back to us when the update lands if you still get the same problem!

**Comment by Targren** [comment]
Mind if I ask what it turned out to be?
