### ISSUE TITLE
No way to craft Midori blocks

### ISSUE THREAD

**Issue by JSMosby** [Darkosto/SevTech-Ages#1912]
Per JEI,

Midori blocks(quark) are crafted with Popped Midori(better with addons).
Popped Midori is crafted with Midori.
There is no way to obtain Midori in the game that I can find.

The SevTech recipe is a 2x2 of Popped Midori to make 1 Midori Block.
I believe the quark recipe is a 2x2 of Cactus Green.

Fix:
This is a Stage One recipe.
Possibly add a 2x2 of Cactus Green as a way to craft this block?

**Comment by DaedalusGame** [comment]
Midori drops from thorny vines (craftable in a cauldron)
this replacement is configurable in the BWA config Quark section, i merely wanted it to be more in line with Chorus/Purpur blocks

**Comment by JSMosby** [comment]
Very good.  Thank you for the info.

**Comment by artdude543** [comment]
Recipe/Gathering for this resource is as intended.
