### ISSUE TITLE
Parsing Errors.

### ISSUE THREAD

**Issue by HorrisEllis** [Darkosto/SevTech-Ages#1913]
I'm trying to start a server using mcmyadmin but anytime I attempt to add sponge it gives me a ton of parsing errors as shown below, Any insight would be appreciated. 

[McMyAdmin-20180417-105432.log](https://github.com/Darkosto/SevTech-Ages/files/1921068/McMyAdmin-20180417-105432.log)

* Java Version:  Java 8 Update 172 x64
* Operating System: Windows 10 x64
* Sponge version: 1.12.2-2611-7.1.0-BETA-3002.jar
* Forge version: forge-1.12.2-14.23.2.2611-universal.jar

**Comment by artdude543** [comment]
Your using Sponge this voids support unless you can reproduce bugs/issues in Vanilla Forge. Parsing error is also fine to ignore this is known/not an issue. So you'll be fine. But if you find any bugs or whatnot; don't report them unless you have Sponge removed.
