### ISSUE TITLE
Liquid Coralium spread

### ISSUE THREAD

**Issue by M3wM3w** [Darkosto/SevTech-Ages#1915]
## Issue / Bug
On a server i play, someone poured a bucket of liquid coralium from abyssalcraft into our river. It spread extremely fast over a giant area, all water became liquid coralium and eventually almost broke the server because of performance drain. Later there were thousands of dead fish floating everywhere and continuosly appearing. Admin is trying worldedit to fix now...

## Possible Solution
Suggestion, set default abyssalcraft config:
"Liquid Coralium transmutation"=false

## Steps to Reproduce (for bugs)
Put a bucket of liquid coralium into a sea, river, water.

**Comment by FiveEYZ** [comment]
we installed WorldEdit -> selected the effected area -> did `//replace abyssalcraft:cwater:0 water`
