### ISSUE TITLE
Digital miner nether interraction

### ISSUE THREAD

**Issue by Noxtralis** [Darkosto/SevTech-Ages#1916]
## Issue / Bug
 Digital miner does not mine ardite or cobalt. Instead of getting those blocks, it gives you low grade charcoal. 

## Expected Behavior
 should give the actual block instead of charcoal

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:  3.0.6
* Java Version:
* Launcher Used:

* Memory Allocated:

* Server/LAN/Single Player:
* Resourcepack Enabled?:
* Optifine Installed?:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Soultion:
* Sponge (Non-Vanilla Forge) Server?:

* Additional Content Installed?:

**Comment by SphynxLoL** [comment]
#1452 

Quarries and Miners ONLY work in space.
