### ISSUE TITLE
Liquid Starlight improves tools placed in it, but NOT the basic Rock Crystals

### ISSUE THREAD

**Issue by Sorbe** [Darkosto/SevTech-Ages#1918]
## Issue / Bug
Astral Sorcery Liquid starlight (a full bucket in a hole in the ground) will correctly improve Crystal Tools crystal size but does nothing to the basic Rock Crystals.  I've left the Rock Crystals in liquid starlight for IRL days in a loaded chunk with no change (the LS is not consumed).  If I instead for a Crystal tool in the same LS filled hole, it will consume

## Expected Behavior
Per the Astral Tome, this is primarily supposed to work on individual Rock Crystals AND Crystal tools. 

## Possible Solution
No workarounds are known.

## Steps to Reproduce (for bugs)
1. Collect Rock Crystals by mining down to bedrock under surface markers (or Creative cheat some in).
2. Craft a Lightwell and put a Rock Crystal on top of it.
3. Wait for Lightwell to fill at night from starlight, add more Rock Crystals until at least 1/2 full of LS.
4. Use a bucket to obtain a full 1000mb of Liquid Starlight.
5. Dig a 1x1x1 hole and pour the LS bucket into the hole.
6. Make sure any magnetic item player effects are not enabled.
7. Observe and record the size, purity and cut values for a sample Rock Crystal.
8. Toss the Rock Crystal into the hole, making sure it goes in and that you aren't too close.
9. Let the Rock Crystal sit in the hole for an indefinite period of time -- nothing happens.
10. Repeat steps 7-9 with a Crystal tool, and observe results in about a minute. 
11. The Crystal tool will improve in size and the cut will go to zero.

## Context
You need to improve Rock Crystals and Grind them for non-tool uses as well. eg.  Mirrors and Lens.

## Logs
Not a crashing bug -- no log info available.

## Client Information
Sevtech Ages 3.0.6
Java 8 Update 162 (64-bit)
Jar Launcher selected
6GB Max VM Heap Size
Recommend Java VM help options
Client + SMP Server (also 3.0.6)
SoarTex Fan Version
No Optifine installed

**Comment by Dutchs** [comment]
I cannot reproduce this issue and am able to grow Rock Crystals and Celestial Crystals as well as double them if left in a pool of Liquid Starlight when they are max size to improve purity.

Do you get the white sparkly particles when you drop them into the pool? (this is different from the normal rays)

Tested it in my 3.0.4 created world and a new 3.0.6 world, same results

**Comment by SteseDav** [comment]
@Sorbe - Did you check the Java verison the modpack is actually using. by default Twitch uses the packaged version (1.8.0.25) and not the locally installed one. 

https://docs.google.com/document/d/e/2PACX-1vR5muyi1m7Zy_qSwrzeb9e3tbbRlksguNUb_Pvm3pn9eDpsIkUj5qQUq6WFPPdEoVWZq91WvvH57KzC/pub

**Comment by Sorbe** [comment]
<img width="687" alt="twitchjava" src="https://user-images.githubusercontent.com/7958470/38926325-1de642f8-42b7-11e8-9c3a-d9ae8a54dbe8.png">

**Comment by Sorbe** [comment]
I retested it and the bug does NOT repro. :/  Closing until it happens again.

**Comment by SteseDav** [comment]
OK, thanks for checking the Java version, its something that is coming up fairly often
