### ISSUE TITLE
World crashes upon entering

### ISSUE THREAD

**Issue by skye006** [Darkosto/SevTech-Ages#1919]
## Issue / Bug

Whenever I attempt to enter my world, it loads up for a second and then crashes.

## Steps to Reproduce (for bugs)

1. log into world
2. world loads for a split second
3. crashes

## Context

I am trying to simply play my world but for some reason, it keeps crashing. I have made no changes since last night where I played without any issue.

## Logs

* Client/Server Log: https://docs.google.com/document/d/1N3m3nSyf_aUY93mcVnBvvtAWTGovgsd8iWLJnn3LXXM/edit?usp=sharing
* Crash Log: there appears to be none

## Client Information

* Modpack Version: 3.0,6
* Java Version: 8
* Launcher Used: Twitch

* Memory Allocated: 6.6 gb

* Server/LAN/Single Player: single player
* Resourcepack Enabled?: no
* Optifine Installed?: no

**Comment by SteseDav** [comment]
Hi,

You seem to be using the packaged Java version for Minecraft. You can try updating to the latest version of java (1.8.0.162) from Java.com, and then forcing minecraft to use it.

Instructions : https://docs.google.com/document/d/e/2PACX-1vR5muyi1m7Zy_qSwrzeb9e3tbbRlksguNUb_Pvm3pn9eDpsIkUj5qQUq6WFPPdEoVWZq91WvvH57KzC/pub

REgards

**Comment by skye006** [comment]
@SteseDav I get this message when entering a world now: 

> Connection Lost     Internal Exception:java.nio.channels.ClosedChannelException

**Comment by SteseDav** [comment]
Can you get the client/server log and debug log, if possible... 

Also, you could try and disable your firewall (temporarily) while starting the modpack... its possible it is blocking something it shuoldn't be.

**Comment by skye006** [comment]
Here are the debug and latest logs after the first and second attempts.

The first attempt gives the error I stated before:
https://www.dropbox.com/sh/kfja0i274cvhdcc/AADdY703DZhIGua6jPLAgmFya?dl=0

The second attempt results in a crash after showing my toolbar in game (not yet loading the world to see) and no crash log:
https://www.dropbox.com/sh/bid3m4ikz564mlu/AAAdvhp3zZw2uxFACDAy6uE1a?dl=0

**Comment by artdude543** [comment]
These issues should/are resolved in 3.0.7
