### ISSUE TITLE
New worlds - Low mob spawning in Age 0 and Low darklands biome generating.

### ISSUE THREAD

**Issue by Shinystar10967** [Darkosto/SevTech-Ages#1921]
## Issue / Bug
I understand the mob stages to cause more mobs to spawn as you advance but should start spawning more mobs when you are wearing armor, and weapons.

## Possible Solution
 Have options or configs to increase spawning as it is right now doesn't feel like minecraft to wander about the night only to worry about wolves.
 add in configs or harder mob spawning. otherwise there is night mobs spawn but to far and in between. A way to increase darklands biome generating as well!

## Steps to Reproduce (for bugs)
 Create new worlds advance yourself and wander during the night. travel around search for darklands. If you do tradionally you would have to travel entire world to find them
1.
2.

## Context
 Takes to long to get out of Age 0

**Comment by artdude543** [comment]
Darkland biome spawns enough from out testing and in some cases too much. So we're not going to change anything in that regards. Mobs spawn enough also; if you need mobs visit the hunting dimension that's what it is there for.

We have custom spawning rates for most things which have been tested a lot and are balanced to how we want it at. This would be an RNG issue at the end of the day for both questions. Harder mobs do spawn however but you may have reached a limit on spawns for an area but I can defo state that they spawn harder as you progress through the stages.

**Comment by Shinystar10967** [comment]
there is no hunting dimension craftable in age 0, that unlocks in age 1
