### ISSUE TITLE
Unable to find Horologium/AS Solar Eclipses not occuring

### ISSUE THREAD

**Issue by LycanBlackpaw** [Darkosto/SevTech-Ages#1923]
## Issue / Bug
So this is more of a question than anything. While testing on a server trying to discover Astral Sorcery constellations, me and a friend were unable after several attempts to get a solar eclipse, nor find Horologium. 
According to the FTB Gamepedia wiki, solar eclipses occur once every 36 days based on local difficulty days (as a side node, the InfoAccessories calendar is 1 day off; it showed December 27 (361st day of a year) to be day 360 according to /time query day). We tried at day 324 and day 360 on the server with no eclipse occuring, nor Horologium showing up in the sky.
I can find nothing in the config that would explain this save that Astral Sorcery's custom sky effects are disabled in the overworld. Whether or not this affects the eclipse, I don't know, but I suspect it anyway just as a precaution.

## Expected Behavior
Solar eclipse every 36 days

## Possible Solution
Maybe re-enable Astral's sky effects? Dunno if this would actually stop the eclipse but...

## Steps to Reproduce (for bugs)
1. Skip nights (using /time set, a BM ritual, or any other method) until Day 36 or another multiple of 36
2. Wait and see no eclipse occur

## Context
Horologium, as one of Astral Sorcery's constellations, is useful for several things. The ritual effect is a tick speed increaser, using it for a Mantle of the Stars effect causes mobs to be frozen in place on occasion when they hit you, and it gives quite a few good enchantments in the Stellar Refraction Table. Not having access to these is a pretty big setback if you plan on using Astral to it's fullest.

## Logs
* Client/Server Log:
* Crash Log:

## Client Information
* Modpack Version: 3.0.6
* Java Version: Java 8 Update 1.6.1
* Launcher Used: MultiMC
* Memory Allocated: 5 GB
* Server/LAN/Single Player: Server
* Resourcepack Enabled?: No
* Optifine Installed?: No

## Server Information
* Java Version: Java 8 Update 1.6.1
* Operating System: Windows 10
* Hoster/Hosting Soultion: Custom box (I don't know the exact specs
* Sponge (Non-Vanilla Forge) Server?: No
* Additional Content Installed?: FTB Utilities

**Comment by Numorphan** [comment]
It's been working for us for Horologium. We used /time query day (just like you) to find the next day that was a multiple of 36, then blood magic ritual + bed to get to that night and it's up there. For what it's worth, I'm not sure if the eclipse was visible or not, but using the telescope I could definitely find the constellation.

**Comment by artdude543** [comment]
Yeah, I tested this and it's fine; these are supposed to be rare/RNG type to get the correct night to find them. That as the pack can't do anything as this is all done in the mod. If you really can't find it you'll need to log an issue with the mod and chat to the developer.
