### ISSUE TITLE
Death loop on planets

### ISSUE THREAD

**Issue by Noxtralis** [Darkosto/SevTech-Ages#1924]
## Issue / Bug
 I died on saturn and now i'm stuck in a death loop. 
 make it so you would respawn in the overworld

## Expected Behavior
 i respawn on the planet in some sort of acid water, and it takes some time for the game to load (as if minecraft is not responding) and i cant type the command to go home because i`m dead by the time the game decides to load. 
 best way would be to respawn back in the overworld. 

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:3.0.6
* Java Version: 1.8.0.161
* Launcher Used: JAR

* Memory Allocated: 8192MB

* Server/LAN/Single Player: Server
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by SteseDav** [comment]
This isn't really a pack problem, but an issue with the player position IMHO.

Try moving yourself with one of the tools here :- https://www.reddit.com/r/Minecraft/comments/28lno5/moving_a_player_with_mcedit/

**Comment by MJRLegends** [comment]
Yeah this is probably going to happen 1 in 10000 times, and the fact it takes you long to respawn is also related to facts like your computer hardware, etc. Which Planet is it @Noxtralis ?

**Comment by MJRLegends** [comment]
(Message for Issue tracker managers) please mark this as a bug and reported to dev :D as i want to fix this. It will be fixed in today's ExtraPlanets update anyways)

**Comment by Noxtralis** [comment]
it was on saturn. It does not give me enough time between loading and dying to type in any commands

anyone who would die, would suffer the same issue

**Comment by MJRLegends** [comment]
ExtraPlanets updates have been upload to CurseForge :D and fixes this issue
