### ISSUE TITLE
Abyssalcraft Darkstone overwrites Geolysis Hematite and Coal.

### ISSUE THREAD

**Issue by Etheras** [Darkosto/SevTech-Ages#1927]
## Issue / Bug
Geolysis veins have darkstone cutting through the vein, possibly minimizing ore generated.
[Picture](https://imgur.com/b0cVyPb)
Picture taken after i've cut through darkstone to find extra ore behind it.

## Expected Behavior
Geolysis veins have discreet shape, should retain that.

## Steps to Reproduce (for bugs)
1. Create world.
2. Find an ore vein in Darklands.
3. Notice that Darkstone is cutting right throught the vein.

## Context
World was created with 3.0.3 version (i think).

## Client Information
* Modpack Version: 3.0.6
* Java Version:8.0.1620.12
* Launcher Used: MultiMC
* Memory Allocated: 6144
* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: Soartex Modded
* Optifine Installed?: Yes

Should be noted, this is a realy minor issue.

**Comment by artdude543** [comment]
Yeah, this is something which will happen. From time to time when the generator is running. This happens in general and Vanilla with the new stones spawning and taking over Vanilla Ores. It's just the case of bad luck when a mod gets its generator code running and another runs on top. Nothing we can do really apart from switching it off, but that won't happen 😉
