### ISSUE TITLE
Question about disabling specific mods

### ISSUE THREAD

**Issue by FlorianSilbereisen** [Darkosto/SevTech-Ages#1930]
Hey guys,

one of my friends can only start the modpack if he disables the following mods: smooth font, immersive craft and rf tools. We actually tried alot to fix this but we kinda gave up now.

My question is if I disable those 3 mods on my server, will this affect the progression in a bad way for exmaple; missing recipes to progress in the next age

 Thanks for considering my request

FlorianSilbereisen

**Comment by artdude543** [comment]
- Smooth Font you are fine to disable.
- RFTools **you need to keep in.**
- ImmersiveCraft **you need to keep in**.

Disabling the last two mods will break both progression and recipes. These are designed to work with the pack; not sure why you'd want to disable them. But nevertheless you can't turn them off 😄 (Unless you want to re-do all the scripts)
