### ISSUE TITLE
Achievment "Time to even the scales"

### ISSUE THREAD

**Issue by Burzi86** [Darkosto/SevTech-Ages#1934]
## Issue / Bug
I found a "Naga Scale" in a chest inside a hollow hill.
By picking it up I got the achievment even without killing the naga. 
I don't know if this is a bug or if this is even the right place to bring it up, because I think darkosto said the achievments from the twilight forest are from the maker of that mod.

## Possible Solution
If this achievment is from darkosto then I would suggest that the item would be change to the trophy instead of the scale.

## Client Information

* Modpack Version: 3.0.6

**Comment by Targren** [comment]
That's Twilight Forest.

**Comment by Burzi86** [comment]
Ok then never mind. *closed*
