### ISSUE TITLE
Nether Quartz Black Texture

### ISSUE THREAD

**Issue by iffonox** [Darkosto/SevTech-Ages#1937]
Vanilla Nether Quartz related blocks and items show up with a black texture instead of a white one.
As seen on the screenshot, this is not just a inverted version of the texture as the netherrack part of the ore is still red.

The NetherEx quartz ores are showing the expected white quartz streaks.

The screenshot was taken in a fresh install of the pack.
![2018-04-18_22 15 09](https://user-images.githubusercontent.com/4130675/38956191-2f57c57a-4357-11e8-9afb-fa27b59849b5.png)

## Issue / Bug
Nether Quartz is black.

## Expected Behavior
Nether Quartz being white.

## Steps to Reproduce (for bugs)
1. Install via Twitch client
2. Start the pack
3. Create a new world
4. Get to stage three
5. Wonder why Nether Quartz is black

## Client Information
* Modpack Version: 3.0.6
* Java Version: Java 8 update 161 64bit
* Launcher Used: jar laucher via Twitch app with cpw's java arguments from reddit
* Memory Allocated: 6 GB
* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by SphynxLoL** [comment]
I have the same "problem" too. Was thinking it happened when I messed around with optifine but I see you don't have optifine installed and it still happened. Now I'm starting to think it's a Mjoang late April Fool's Day joke (since they had me bugging out on the last texture change).

**Comment by BigAl607** [comment]
If I remember correctly, the visual change to nether quartz was done intentionally.

**Comment by DaedalusGame** [comment]
Better With Mods config option

**Comment by iffonox** [comment]
As Nether Quartz based items from other mods are still white, turning off the "DarkQuartz" option would give the pack a more consistent look.

**Comment by SephirothWS** [comment]
That's funny, when I was playing through the pack, all of my nether quartz was correctly rendered white.
