### ISSUE TITLE
Cyan Tech modpack on Curseforge, based on and uses sevtech files.

### ISSUE THREAD

**Issue by MrNinja93** [Darkosto/SevTech-Ages#1939]
There's a pack on Curseforge called [Cyan Tech](https://minecraft.curseforge.com/projects/sevtech-ages-cyan-edition#) which is a modified version of Sevtech Ages, As the pack is "All Rights Reserved" and no indication of rights being given I thought you guys should know, configs etc. appear identical in most if not all instances.

**Comment by artdude543** [comment]
The pack has been removed. Thanks for reporting ❤️
