### ISSUE TITLE
The "paper" needed for the Astral Sorcery Journal requires Stage 2

### ISSUE THREAD

**Issue by MongoTheElder** [Darkosto/SevTech-Ages#194]
The page needed to craft the Astral Sorcery Journal requires Stage 2 but the Journal is needed for Stage 1

![2017-11-20_20 10 21](https://user-images.githubusercontent.com/29290246/33049591-ddfab676-ce2e-11e7-8912-f208fd66588a.png)

![2017-11-20_20 11 42](https://user-images.githubusercontent.com/29290246/33049633-0d5792d6-ce2f-11e7-8826-5d05a87219e3.png)

Strangely, I was able to craft the "paper" even though it is restricted and I was able to use it to craft the Journal.

Alpha 8, Twitch build

**Comment by justinrusso** [comment]
Is the Aquamarine also restricted?

**Comment by Darkosto** [comment]
Got it fixed up, thanks!
