### ISSUE TITLE
Can't download instances. Java.net.SocketException

### ISSUE THREAD

**Issue by reno11** [Darkosto/SevTech-Ages#1947]
So I'm trying to launch/install SevtechAges 3.0.6 using AtLauncher, and every time I get a download error where the download just stops, or the download bar/size keeps increasing and then ultimately crashing.

## Logs
* Crash Log: http://paste.atlauncher.com/view/86155685
I'm not sure whether this is the log I need to upload or not, but I don't know if there are any other logs. (or where to find them)
## Client Information
* Modpack Version: 3.0.6
* Java Version: 8 (64-bit 1.8.0_161)
* Launcher Used: ATLauncher
* Memory Allocated: 10gb

**Comment by artdude543** [comment]
Yeah, this is not a pack issue; seems the CDN servers you were trying to download from was down for a short period of time. If the issue persists, you'll need to log an issue with ATLauncher (Or use another launcher which has fallback support _I.E. Twitch_ or hit up your ISP (If it comes to that)
