### ISSUE TITLE
Ironwood thin slab not tagged as thinWood

### ISSUE THREAD

**Issue by MrGundum** [Darkosto/SevTech-Ages#1948]
## Issue / Bug
Can't use ironwood thin slab to create a gear box.

## Expected Behavior
useable to create gearbox

## Possible Solution
Tag ironwood thing slab as  a thinWood

## Steps to Reproduce (for bugs)

1. try to create gearbox with ironwood thin slab

## Context
Couldn't create gear box
## Client Information

* Modpack Version: 3.0.6
* Java Version:1.8_106
* Launcher Used:
Twitch
* Memory Allocated:
10GB
* Server/LAN/Single Player:
Server
* Optifine Installed?:
Yes

**Comment by An-Sar** [comment]
fixed in PrimalCore dev, next release 0.6.47
