### ISSUE TITLE
Astral Sorcery Ages Reset.

### ISSUE THREAD

**Issue by Tophenator** [Darkosto/SevTech-Ages#1949]
I was sorting my base and I placed my astral sorcery book in the Bibliocraft & Immersivecraft bookshelves now my book has reset back to the first time I have crafted it. I am currently in age 2. 

Optifine - Yes
Version - 3.0.6
Shaders - No

**Comment by justinrusso** [comment]
Nothing seems to really connect here. The knowledge data is stored externally and has no relation to the book.

**Comment by ifschwartz** [comment]
The same thing has happened to me.  Something reset my progress in Astral Sorcery, it has nothing to do with the book other than the book is what basically shows your progress.  The only selection in my book is Discovery.  My iridescent altar, starlight infuser and gateways still work but I am no longer able to use my attunement altar and my attunement is gone.  Unfortunately I cannot tell when I lost this but my guess would be yesterday.  I have backups and could try to restore the Astral Sorcery files if I knew which to restore.
I am not using Optifine or Shaders and am on version 3.06.
I am in the age 5 creative age.

**Comment by ifschwartz** [comment]
UPDATE:  I did some investigating and it appears that my Astral Sorcery player data ([UUID].astral) file had become corrupt.  I was able to grab mine from a backup and that fixed the issue for now.  Unfortunately I have no idea what caused the corruption and I am unable to find anything in logs to tell when or what caused it.  Unfortunately Tophenator this may not help you unless you have a backup and the know-how to restore an Astral Sorcery playerdata file.  I don't want to recommend doing it as you could end up ruining your MC playerdata file if you don't know exactly what you are doing.

**Comment by Tophenator** [comment]
I wasn't too far along so I just reset but now I've found more issues :( thanks Schwartz
