### ISSUE TITLE
Add Stage Info to Tooltips of Prospecting Rods

### ISSUE THREAD

**Issue by Darkosto** [Darkosto/SevTech-Ages#195]
^^^^

**Comment by justinrusso** [comment]
What would you want the text to say? Just "Stage X"?
Also, I was thinking yellow or green text, or should it stay red?

**Comment by Darkosto** [comment]
Yellow Text works

"This tool may only be used 
for Stage _ and below ore"

with the line break so the tooltip doesn't make the box too long.

**Comment by justinrusso** [comment]
How do you add line breaks? :P

**Comment by Darkosto** [comment]
All you need to do is add another tooltip directly below it: 

```
<jarm:oak_raft>.addTooltip(format.red("This is the top line"));
<jarm:spruce_raft>.addTooltip(format.red("This is the bottom line"));
```

**Comment by Darkosto** [comment]
https://github.com/Darkosto/SevTechAgesConfigs/commit/0181bdcbb4905d720418189facbefcdb207f25ac
