### ISSUE TITLE
Progression in the guide doesnt teach how to cast your first Ingots

### ISSUE THREAD

**Issue by Shoulon** [Darkosto/SevTech-Ages#1952]
I just melted up my first copper clusters but the book/guide doesn't tell me how to remove the melted copper from the Melter and how to cast it into a block. had to google that i needed the casting basin

**Comment by BonaireDreams** [comment]
Well block in basin, or ingot in an ingot cast on table. You can use a mud brick (or a seared brick) as your mold to make the ingot cast. That's standard Tinkers functionality and not unique to SevTech so wouldn't expect it to be in the tooltip.

**Comment by justinrusso** [comment]
The advancements are really just a general concept of how to get somewhere. The rest is on you to figure out. We are not looking to provide a hand-holding experience.
