### ISSUE TITLE
Modular Machinery Mixer MK2 and MK3 duplicate recipe (unable to craft MK2)

### ISSUE THREAD

**Issue by gbattleson** [Darkosto/SevTech-Ages#1957]
## Issue / Bug
The MK2 and MK3 mixer blueprints have the same recipe
![mm mixer mk2](https://user-images.githubusercontent.com/16946836/39024525-1b67d036-4407-11e8-9c17-b414ea40bebf.JPG)
![mm mixer mk3](https://user-images.githubusercontent.com/16946836/39024526-1b78a370-4407-11e8-9802-d890f9519087.JPG)

## Expected Behavior
It appears to be impossible to craft the MK2 Mixer MM blueprint

## Possible Solution
Add 3rd piece of paper needed for the MK3 and leave the MK2 recipe alone

## Steps to Reproduce (for bugs)
Try to craft a MK2 Mixer blueprint

## Client Information
3.0.6

**Comment by justinrusso** [comment]
https://github.com/Darkosto/SevTech-Ages/issues/1680

**Comment by gbattleson** [comment]
Dangit I even did a search of modular machinery , didn't search of mixer though
