### ISSUE TITLE
Configure "Armoreable Mobs" to remove All Armor / Weapons / Tools from Zombies, Villager Zombies

### ISSUE THREAD

**Issue by Darkosto** [Darkosto/SevTech-Ages#196]
Since this can't be done via inControl we need to remove these items via Amoreable Mobs so players cannot get certain items early.

Iron Armor
Gold Armor
Chainmail
Diamond

**Comment by ALongStringOfNumbers** [comment]
Iron Sword from https://github.com/Darkosto/SevTech-Ages/issues/157 ?

**Comment by justinrusso** [comment]
The mod has support for game stages, maybe add it in over time to make mobs more difficult?

**Comment by Darkosto** [comment]
Yep, he added it for us specifically. Armor/item stages can definitely be used to unlock as the player progresses.

**Comment by justinrusso** [comment]
Will this work to remove though? I'd imagine the idea would be to create an empty ArmorGroup, but to guarantee that they will be an empty mob, itd have to be 100% chance, which then breaks the chance for other variations later as stages unlock.

**Comment by Darkosto** [comment]
We can also just replace with useless items like sticks if pure removal isn't working. For armor, that might not work as easily?

**Comment by Darkosto** [comment]
@buuz135 May have some ideas, too!

**Comment by justinrusso** [comment]
Id love to see what his idea on this is. I'd love to be able to say "This is what we want our mobs to be", then "This is what we want as a chance". Theres no way to set a default, just unique things on top of the default mob that already exists

**Comment by Buuz135** [comment]
You should be able to put anything everywhere does CrT have empty itemstacks, that should clear mobs stuff too

**Comment by Buuz135** [comment]
BTW ArmoreableMobs is `lightly` tested and just tested with simple stuff. I will make everything work by trial and error! 😛

**Comment by justinrusso** [comment]
Is there a way to default a mob to blank, and then be able to build on the mob from there? The only way to remove all items would be to clear the mob out and give it a 100% chance to spawn. If thats 100%, you then cant get any other variants to spawn.

**Comment by Buuz135** [comment]
Yes all the groups will be triggered in order if they have the chance to get used.

**Comment by justinrusso** [comment]
Hey @Buuz135 , Just got around to trying this out.

I'm trying to make it so the entity's armor is cleared from its default, then add the chances on top of it.

```
import mods.armoreablemobs.ArmorHandler;
import mods.armoreablemobs.ArmorEntity;
import mods.armoreablemobs.ArmorSlot;
import mods.armoreablemobs.ArmorGroup;

var entity = ArmorHandler.createArmorEntity("minecraft:zombie");

var group1 = ArmorHandler.createArmorGroup("Blank", 1.0);

group1.addArmor(ArmorHandler.createArmorSlot("head", null, 1, 0));
group1.addArmor(ArmorHandler.createArmorSlot("chest", null, 1, 0));
group1.addArmor(ArmorHandler.createArmorSlot("legs", null, 1, 0));
group1.addArmor(ArmorHandler.createArmorSlot("feet", null, 1, 0));
group1.addArmor(ArmorHandler.createArmorSlot("mainhand", null, 1, 0));
group1.addArmor(ArmorHandler.createArmorSlot("offhand", null, 1, 0));

group1.addGameStage("one");


var group2 = ArmorHandler.createArmorGroup("Iron", 0.9);

group2.addArmor(ArmorHandler.createArmorSlot("head", <minecraft:iron_helmet>, 1, 0));
group2.addArmor(ArmorHandler.createArmorSlot("chest", <minecraft:iron_chestplate>, 1, 0));
group2.addArmor(ArmorHandler.createArmorSlot("legs", <minecraft:iron_leggings>, 1, 0));
group2.addArmor(ArmorHandler.createArmorSlot("feet", <minecraft:iron_boots>, 1, 0));
group2.addArmor(ArmorHandler.createArmorSlot("mainhand", null, 1, 0));
group2.addArmor(ArmorHandler.createArmorSlot("offhand", null, 1, 0));

group2.addGameStage("one");
```

This just results in every zombie being armor-less. I've flown around for a while in a flat world in night time and I have not found any zombies with the Iron group.

**Comment by Buuz135** [comment]
You don't add the entity to the groups

**Comment by justinrusso** [comment]
*facepalm*

**Comment by justinrusso** [comment]
Had a crash after adding the entity to the group: https://gist.github.com/justinrusso/c49e4f4c81ce0e6f167f38a77e2ed68c

**Comment by Buuz135** [comment]
I will look into it tomorrow

**Comment by Buuz135** [comment]
After spending some time wondering why I didn't get the crash I realized that GameStages was a thing and I didn't the needed stage. Try this version, it is fixed, test it out too and if it works, I will put it on curse. @justinrusso 
[armoreablemobs-1.1.3.jar.zip](https://github.com/Darkosto/SevTech-Ages/files/1547631/armoreablemobs-1.1.3.jar.zip)

**Comment by justinrusso** [comment]
Seems good! Thanks for the help 👍

**Comment by justinrusso** [comment]
Still having troubles... I'm finding mobs spawns like this still, when I shouldn't be.

Heres my code for armoreable: https://gist.github.com/justinrusso/82cb3689187eb38536b0f308385ae22c

defaultArmorDropChance (in case you were curious) `global defaultArmorDropChance as double = 0.15;`

![image](https://user-images.githubusercontent.com/25138621/33844819-8166889e-de6f-11e7-87aa-1d8d5279fe22.png)

**Comment by Buuz135** [comment]
Are they the ones from before that they were already spawned?

**Comment by justinrusso** [comment]
I was already in the stage before I turned it to night, and I flew pretty far looking for a bunch of spawns to see how the spawn rate was. I dont think this would have been an already-spawned mob

**Comment by Buuz135** [comment]
I meant from the script before where they had iron armor, as MC rules, they won't despawn like named entities don't despawn. `I think`

**Comment by justinrusso** [comment]
Ahh right! I made a new world.. it appears to be working. Will need to give it more testing though, but so far so good

**Comment by justinrusso** [comment]
@Buuz135 Not sure if you had noticed my edit, just wanted to check in.. I've still found mobs with shovels, I did not see any with armor.

Not sure if that's just related to a 'luck' factor or if the mod had actually prevented them from spawning. Any idea on this?

**Comment by Buuz135** [comment]
Try adding all the game stages to the blank group.

**Comment by justinrusso** [comment]
I can give that a try, but I only have that single stage added to my player in the test world

**Comment by Buuz135** [comment]
Okay I think I have found the issue, the spawn event is triggered before the entity is fully "dressed", when it is "dressed" it wont replace existing items. Thats why it works to add items but not remove them.

**Comment by Buuz135** [comment]
This version should work, I delayed the mob equip logic to the server tick so it is fully MC dressed.
[armoreablemobs-1.1.4.jar.zip](https://github.com/Darkosto/SevTech-Ages/files/1561024/armoreablemobs-1.1.4.jar.zip)

**Comment by justinrusso** [comment]
It *appears* to be working now.. but now my zombies are alternating between armor after spawned.

https://gyazo.com/51a923529197fb553541668c1f05c09b

**Comment by Buuz135** [comment]
Looks perfect 10/10

**Comment by Buuz135** [comment]
This should be better 
[armoreablemobs-1.1.4.jar.zip](https://github.com/Darkosto/SevTech-Ages/files/1561081/armoreablemobs-1.1.4.jar.zip)

**Comment by justinrusso** [comment]
Froze up on world load

**Comment by Buuz135** [comment]
Maybe not my fault?

**Comment by justinrusso** [comment]
```
var mobEntities = [
	ArmorHandler.createArmorEntity("minecraft:zombie").withNBTCheck("IsBaby", 0, "EQUALS"),
	ArmorHandler.createArmorEntity("minecraft:zombie_pigman").withNBTCheck("IsBaby", 0, "EQUALS"),
	ArmorHandler.createArmorEntity("minecraft:zombie_villager")
] as ArmorEntity[];
```
Hm.. I added the withNBTCheck and that broke it. Reverting (removing the nbt checks) made it work.

**Comment by justinrusso** [comment]
The amazing feature is now gone, so aside from this issue everything appears to be good!

**Comment by Buuz135** [comment]
It seems that the zombie doesnt have the isBaby tag:

`{HurtByTimestamp:0,Attributes:[{Base:20.0d,Name:"generic.maxHealth"},{Base:0.0d,Modifiers:[{UUIDMost:7804891240799356800L,UUIDLeast:-7649485099609233547L,Amount:0.028689321412280793d,Operation:0,Name:"Random spawn bonus"}],Name:"generic.knockbackResistance"},{Base:0.23000000417232513d,Name:"generic.movementSpeed"},{Base:2.0d,Name:"generic.armor"},{Base:0.0d,Name:"generic.armorToughness"},{Base:35.0d,Modifiers:[{UUIDMost:-4890599170483010833L,UUIDLeast:-4613595255894749909L,Amount:0.06689967138264268d,Operation:1,Name:"Random spawn bonus"}],Name:"generic.followRange"},{Base:3.0d,Name:"generic.attackDamage"},{Base:0.0018056055897331504d,Name:"zombie.spawnReinforcements"}],Invulnerable:0b,FallFlying:0b,PortalCooldown:0,AbsorptionAmount:0.0f,FallDistance:0.0f,DeathTime:0s,HandDropChances:[0.085f,0.085f],PersistenceRequired:0b,Motion:[-3.4664525447018957E-18d,-0.0784000015258789d,0.0d],Leashed:0b,UUIDLeast:-5124218800456303025L,Health:20.0f,LeftHanded:0b,Air:300s,OnGround:1b,Dimension:0,Rotation:[180.00536f,1.2282938f],UpdateBlocked:0b,HandItems:[{},{}],ArmorDropChances:[0.085f,0.085f,0.085f,0.085f],UUIDMost:3207395414534737626L,Pos:[-247.5000751570831d,5.0d,579.3000000119209d],CanBreakDoors:0b,Fire:-1s,ArmorItems:[{},{},{},{}],CanPickUpLoot:0b,HurtTime:0s}`

**Comment by justinrusso** [comment]
`/summon zombie ~ ~ ~ {IsBaby:1}` does summon a baby zombie.. Maybe when its an adult, it just doesnt have the tag? How would I be able to add a criteria in that case? Is there an "If tag exists" type thing?

**Comment by Buuz135** [comment]
Soooooooooooo... also the mode is "EQUAL". I added TAG_EXISTS and TAG_MISSING , you can use a random value like "" as its not used
[armoreablemobs-1.1.4.jar.zip](https://github.com/Darkosto/SevTech-Ages/files/1561173/armoreablemobs-1.1.4.jar.zip)

**Comment by justinrusso** [comment]
Will have to test it in a bit, but would it be .withNBTCheck("IsBaby", "", "TAG_MISSING"),

**Comment by Buuz135** [comment]
Use .withNBTCheck("IsBaby", 0, "TAG_MISSING") because I found a typo in the one with string value

**Comment by Buuz135** [comment]
Do I assume that it works decently? So I can push it to curse

**Comment by justinrusso** [comment]
Didn't get to try it last night sorry. It seems to be good, thanks!
