### ISSUE TITLE
Exception in World Tick Loop, Server crashes as soon as anyone logs in.

### ISSUE THREAD

**Issue by Nightcaste** [Darkosto/SevTech-Ages#1960]
## Issue / Bug
Server crashes as soon as anyone tries to log in.
Server Log:  https://pastebin.com/fZkG75qn

## Expected Behavior
I would expect players to be able to log in and the server to stay running.

## Possible Solution
I think an automated backup would be a great idea to give people an option when they run into something like this.  Seems weird that the pack doesn't include one.

## Steps to Reproduce (for bugs)
1.  Start server through CreeperHost control panel
2.  Launch pack through Twitch (jar) launcher
3.  Attempt to join server
4.  Server crashes
5.  cry.

## Context
My... tribe and I are in Age 3.  I was trying to make a gadget that would make creating obsidian easier.  I placed a piston pointing down on the underside of a block of cobble, placed a lever on the cobble, and when I flipped the lever the server crashed.  Another of our members said he was making a waypoint in his Atlas at the time.

## Logs
* Client/Server Log:  Too big for Pastebin.  Tell me what to cut and I'll throw it up here.
* Crash Log:  https://pastebin.com/fZkG75qn

## Client Information
* Modpack Version: 3.0.6
* Java Version:  161
* Launcher Used:  Jar launcher through Twitch
* Memory Allocated:  6gb
* Server/LAN/Single Player:  SMP
* Resourcepack Enabled?:  No
* Optifine Installed?:  No

## Server Information
I have no idea how to get this information
* Java Version:
* Operating System:
* Hoster/Hosting Soultion:
* Sponge (Non-Vanilla Forge) Server?:

* Additional Content Installed?:

**Comment by Phantum** [comment]
you should be able to set backups through your host.  I know you can with Nodecraft!

**Comment by Nightcaste** [comment]
> you should be able to set backups through your host. I know you can with Nodecraft!

This is the first pack I've played that didn't have a backup mod in the pack.  I am not seeing a way to do that in Creeper Panel.

**Comment by Nightcaste** [comment]
Saw this line in the log, seems relevant:

22:50:12  [Debug] [BnBGamingCore]: Caught Exception while attempting to get class extensions for net.minecraftforge.fml.common.eventhandler.ASMEventHandler_770_HardcorePackingHandler_hardcorePackingCompress_WorldTickEvent

After that every line starts with [ERROR], then the "unloading dimensions" stuff.

**Comment by artdude543** [comment]
I believe this one was fixed? @DaedalusGame am I correct on this?

I know I see Primal Core here but they also fixed some stuff but this log relates to the packer.

**Comment by DaedalusGame** [comment]
yep already got it, i fixed the other erronous getBlockFaceShape call too

**Comment by artdude543** [comment]
Ahh okay sweet so this will be in an upcoming update or the one we have? `0.37`

**Comment by DaedalusGame** [comment]
upcoming in 0.39

**Comment by Nightcaste** [comment]
So what does all this mean for us?

**Comment by artdude543** [comment]
You wait for the update! Or update yourself but you'll void support from us until the update is included in the actual pack.

**Comment by Nightcaste** [comment]
Any ETA?

**Comment by artdude543** [comment]
No, the only ETA is _When it's done_

**Comment by DaedalusGame** [comment]
as i said, for now you can turn off HCPacking in the BWA config and it will stop crashing

**Comment by Nightcaste** [comment]
That's the first time anyone actually *said* what the solution was.  I'll
see what happens.

**Comment by DaedalusGame** [comment]
![reallymademethink](https://user-images.githubusercontent.com/9559216/39061988-72ad85ba-44c6-11e8-8676-bea9fef93fda.png)

**Comment by Nightcaste** [comment]
That edit wasn't in when I asked.

**Comment by artdude543** [comment]
Mod was/is updated in 3.0.7 so this issue will be resolved then.
