### ISSUE TITLE
Picking up Abyssal Craft Ritual Pedestal creates phantom duplicates.

### ISSUE THREAD

**Issue by FrostyJTD** [Darkosto/SevTech-Ages#1961]
## Issue / Bug
Shift + Right Clicking a Abyssal Craft Ritual Pedestal (I only tested the side ones, not the central one) allows you to pick it up. If there's something on it, a duplicate of the item on it will go into your inventory. However, it seems to be a phantom item and goes away if you try and do anything with it. 

## Expected Behavior
Picking up the pedestal with something on it shouldn't produce a duplicate, phantom or not. As a side note, picking up the pedestal and putting it back in place did NOT break the altar for any Abyssal Craft rituals, although I imagine putting it out of place would do that.

## Possible Solution
Easiest way to handle this in my opinion is to just prevent the pedestal from being picked up. Frankly I'm surprised it can be in the first place. Must have missed putting them in a blacklist somewhere.

## Steps to Reproduce (for bugs)
https://youtu.be/UMPnlP9gO_8

## Context
For a moment there I thought they were genuine dupes. won't lie that I was a little disappointed to find out they weren't.

## Logs
Not going to include a log because there's nothing in the log file related to this. The last couple of hours in my log file are just generic "saving/backing up world" messages.

## Client Information
* Modpack Version: 3.0.6
* Java Version: 1.8.0_161 64bit
* Launcher Used: MultiMC 5 v0.6.2-12222
* Memory Allocated: Min 7GB/Max 8GB

**Comment by artdude543** [comment]
We have added all these to the blacklist on the next version :)
