### ISSUE TITLE
Precision sawmill bug? 

### ISSUE THREAD

**Issue by Noxtralis** [Darkosto/SevTech-Ages#1963]
## Issue / Bug
 Precision sawmill from Mekanism is making chopping blocks from wood logs. Not sure if intended.
 Should make planks instead

**Comment by Fatthunder** [comment]
This is slated for 3.0.7 release.  I was unable to find the actual issue that stated that this was fixed.

**Comment by justinrusso** [comment]
I've covered most of this at this point. There a few left over that are from logs that dont have a plank, so those will be removed or handled in some way in https://github.com/Darkosto/SevTech-Ages/issues/2045
