### ISSUE TITLE
Eucalyptus wood doors/fences/gates

### ISSUE THREAD

**Issue by Sngglbear600** [Darkosto/SevTech-Ages#1964]
Hi, Before the recent update (3.0.6) it was possible to craft fences/gates/doors out of the exotic woods like eucalyptus. Now I’m not able to craft them. Hoping that these recipes will be added back in :)

**Comment by artdude543** [comment]
Recipes appear to be working fine in 3.0.7 so going to assume this will be resolved in that update. If this is still an issue open a new one when the update lands 🙂

**Comment by Sngglbear600** [comment]
Awesome! Thanks!
