### ISSUE TITLE
My game keep crashing

### ISSUE THREAD

**Issue by Ath1la** [Darkosto/SevTech-Ages#1976]
it crash every 5m or so

[hs_err_pid11848.log](https://github.com/Darkosto/SevTech-Ages/files/1933736/hs_err_pid11848.log)

**Comment by artdude543** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critial information we can't help you. So if you would like to report the issue again please re-create a issue using the provided template.

Thanks again for reporting, and we hope you enjoy the pack!
