### ISSUE TITLE
Game keep crashing

### ISSUE THREAD

**Issue by Ath1la** [Darkosto/SevTech-Ages#1977]
* Crash Log: https://pastebin.com/1kuBkmXd

## Client Information

* Modpack Version: 3.0.6
* Java Version: 8 Update 161
* Launcher Used: Twtich
* Memory Allocated: 9,472MB
* CPU: I7 4770

**Comment by justinrusso** [comment]
The java you specified is not the Java that is running. Make sure to use the JAR Launcher in the minecraft settings of the Twitch launcher.
