### ISSUE TITLE
Diamonds and Emeralds Only Accessible Via Bedrock Ores

### ISSUE THREAD

**Issue by Darkosto** [Darkosto/SevTech-Ages#198]
Need to find out if Geolosys Diamond and Emerald ore clusters drop anything else. If not, these ores should be removed and the can only be mined via "Bedrock Ores"

**Comment by justinrusso** [comment]
Kimberlite = Diamond and only Diamond, I dont see one for Emerald from Geolosys.

**Comment by Darkosto** [comment]
Closing this since I haven't heard back about Gamestages considering support for machines/blocks individually.

Bedrock ores has been removed since it cannot mine it's own ores because it is not staged.
