### ISSUE TITLE
How to change Forge Version to Fix Dragon Spawn : Suggestion / Comment

### ISSUE THREAD

**Issue by Rixxaw** [Darkosto/SevTech-Ages#1981]
I'm rather technical person, but I have never changed my forge version on a modpack.

I understand that backing down the forge version from forge-14.23.2.2651 to forge-14.23.2.2650 will fix the problem with the Ender Dragon spawning.  So I went to the closed issue and read through the entire thread and no where does it explain how to downgrade Forge.

My suggestion would be to explain the procedure to fix the problem before closing and locking the thread I would have posted it in that thread if it wasn't locked.

Proceedure to fix Dragon Spawning issue for Twitch Launcher :grin: 

1.  Close out of SevTech.

2.  In Twitch Launcher click SevTech and press the ... button at the top right bringing up the menu.

3.  Select Profile Options

4.  It should say Current ModLoader Versions and have 2651 selected.  Click the dropdown and change it to 2650.  Hit Okay.

Wait for it to download and your good to go.

**Comment by justinrusso** [comment]
I hate to be blunt... but people have to ask for server files when the server files are literally the same as the client files.

Those that know how to will do it, and those that don't are welcome to learn how if they really do incline to (or ask in many other forms) or wait for an update which is coming soon.

**Comment by Sizii** [comment]
But how do you change the forge version on ATLauncher?
