### ISSUE TITLE
Dims do not load

### ISSUE THREAD

**Issue by LightsDawn** [Darkosto/SevTech-Ages#1984]
Issue / Bug
While loading into any dimension players get past loading terrain and then it looks like nothing but void, can see players arm but thats it can also eat and issue commands without problem.
Expected Behavior
expected to arrive to continue playing in another dimension.
Possible Solution
prepare to laugh at me, MCMA make sure "enable nether" is on.
Steps to Reproduce (for bugs)
fresh install of 3.0.6
Context
Logs
only proof of issue is visually seeing it, no logs say anything.
Client/Server Log:
Crash Log:
Client Information
Modpack Version:
3.0.6
Java Version:
8 
Launcher Used:
twitch
Memory Allocated:
5g
Server/LAN/Single Player:
server
Resourcepack Enabled?:
no
Optifine Installed?:
some players yes
Server Information
Java Version:
8
Operating System:
ubuntu
Hoster/Hosting Soultion:
OVH
Sponge (Non-Vanilla Forge) Server?:
no
Additional Content Installed?:
fresh install
## Server Information
* Java Version:
8
* Operating System:
ubuntu
* Hoster/Hosting Soultion:
* Sponge (Non-Vanilla Forge) Server?:
no

**Comment by aMannus** [comment]
Some additional information. When you stay in the bugged dimension, after a while you just time out. 

Also, here's a gif showing the stuff in action: https://gfycat.com/SparseSimpleAlbacoretuna

Ignore the green flashes, that's my gif recording software being bad at compression.

**Comment by justinrusso** [comment]
From OP: 
>when i made the server i enabled everything through MCMA all the mobs difficulty and whatnot but the only thing that wasnt enabled was the nether/dims
