### ISSUE TITLE
Crash issue can't get past Minecraft Launcher 

### ISSUE THREAD

**Issue by Bigwaveb115** [Darkosto/SevTech-Ages#1985]
## Issue / Bug

On the Minecraft Launcher I press play it disappears for a few seconds and comes back and says "An unexpected issue occurred and the game has crashed. We're sorry for the inconvenience."

https://pastebin.com/xbQj0BwX

## Client Information

*Modpack Version: 3.0.6
*Java Version: Java 8 Update 101
*Launcher Used: Twitch

* Memory Allocated: 7,936

* Server/LAN/Single Player: I am going to playing Single Player
* Resourcepack Enabled?: I will be using Shpax 1.12.2
* Optifine Installed?: No

**Comment by artdude543** [comment]
That's not the crash log; in the instance folder there will be a folder called `crash-reports` can you pastebin the latest one for me please, thanks!

**Comment by SteseDav** [comment]
Few basic things to check. - upi have updated to the latest version of Java and forced your launcher to use it? https://docs.google.com/document/d/e/2PACX-1vR5muyi1m7Zy_qSwrzeb9e3tbbRlksguNUb_Pvm3pn9eDpsIkUj5qQUq6WFPPdEoVWZq91WvvH57KzC/pub

Check that you are not allocating more than half of the RAM available on the PC to Minecraft.

**Comment by artdude543** [comment]
If you are still getting this issue when 3.0.7 lands please re-file a new issue with the correct information/logs so we can help you. Thanks!
