### ISSUE TITLE
PrimalCore Blocks Showing up as Nether Lanterns

### ISSUE THREAD

**Issue by Squ1zzl3** [Darkosto/SevTech-Ages#1986]
## Issue / Bug
All PrimalCore mod blocks turned into nether lanterns. 

## Expected Behavior
Everything should not switch to Nether Lanterns

## Possible Solution
-None

## Steps to Reproduce (for bugs)
Haven't been able to duplicate bug but server crashed because I was throwing Hemp String on a Better with Mods Spindle. I probably threw 48 on the spinner and my world crashed. On Relog the world was broken.
## Context
Could not restore world all PrimalCore blocks remain lanterns.

## Logs
* Client/Server Log:
https://gist.github.com/Squ1zzl3/0571fe56521ee82c53b3815038869109
https://imgur.com/a/qhwAsX5
## Client Information

* Modpack Version: 3.0.6
* Java Version:1.8.0.111
* Server/LAN/Single Player: Server
* Resourcepack Enabled?:No
* Optifine Installed?:No

## Server Information
* Java Version:1.8.0.111
* Operating System: Mint/Linux

**Comment by artdude543** [comment]
It seems like your ID either shifted or something broke when saving the mapping to disk. Unfortunately, there is nothing that the pack can do to resolve this issue as it's world related. We are looking into providing a backup mod for the next version to help combat issues like this so you can revert to backups.

But these type of issues are sadly way out of control from the pack side of things.
