### ISSUE TITLE
Attuning Aevitas creates ores that should be hidden by GameStages, but are not.

### ISSUE THREAD

**Issue by talonos2** [Darkosto/SevTech-Ages#1988]
## Issue / Bug
If you attune Aevitas and select the "Mineral Enrichment" perk, then standing near smooth stone will cause that stone to turn into ores from Galacticraft Planets. All these ores will be visible, even as early as age 3, and appear in WAILA as "Unfamiliar Item."

## Expected Behavior
I would expect that only ores available to your stage would spawn. Knowing that is a lot to ask for, I would _at least_ expect that any ores I'm not allowed to mine at this stage would be hidden and look like smooth stone, the same way the Geolosys ores are.

## Possible Solution

In the astral sorcery config, line 161, you can control what ores spawn from this perk.

## Steps to Reproduce (for bugs)

1. Attune Aevitas
2. Level it up by standing in a farm until you reach level 3
3. Select the "Mineral enrichment" perk
4. Go to a cave, and stand surrounded with smooth stone.
5. AFK while preparing and eating your snack of choice.
6. Return, and look around at the bewildering variety of unobtainable ores in the walls around you.

## Context
I was sitting in my friends base, and he accused me of griefing him. It's the first time I've messed with AS! I swear I didn't know! :(

## Logs
No crash associated with this bug.

## Client Information
* Modpack Version: 3.0.6
* Java Version: 8
* Launcher Used: Twitch
* Memory Allocated: 6 GB
* Server/LAN/Single Player: Server
* Resourcepack Enabled?: Nay
* Optifine Installed?: Nay

## Server Information
* Java Version: Also 8
* Operating System: MineOS (No seriously: https://minecraft.codeemo.com/mineoswiki/index.php?title=Main_Page )
* Hoster/Hosting Soultion: My living room.
* Sponge (Non-Vanilla Forge) Server?: No.
* Additional Content Installed?: None.

## Is this too many questions?
Probably, but I can see why you'd want people to be thorough, so I'll play along. :)

##Screenshots:
![2018-04-20_23 49 31](https://user-images.githubusercontent.com/3359830/39080938-7fde4c04-44f5-11e8-936d-3dba03be5876.png)

**Comment by justinrusso** [comment]
https://github.com/Darkosto/SevTech-Ages/issues/1240
