### ISSUE TITLE
Revamp all Ingots -> Blocks -> Nuggets (and backwards) recipes to not only need horse presser/grinder

### ISSUE THREAD

**Issue by Darkosto** [Darkosto/SevTech-Ages#199]
This becomes insanely tedious, instead breaking down should require a powerful saw item in a crafting table and can ALSO be done via a machine / Smeltery.

**Comment by justinrusso** [comment]
This should be put into a loop. Once you can get an idea of what you want to do for it, I'll get that made

**Comment by ALongStringOfNumbers** [comment]
I assume this should also be stage based. In the earlier stages you have to use horse power but in later stages other methods become available?

**Comment by justinrusso** [comment]
This should be good to go with the merge referenced.
