### ISSUE TITLE
Adventurer advancement tab missing

### ISSUE THREAD

**Issue by nolaw70** [Darkosto/SevTech-Ages#1993]
Client Information

* Modpack Version: 3.0.6
* Java Version: 1.8.0_25 and 1.8.0.162
* Launcher Used: Twitch (both native and jar)
* Memory Allocated: 7039MB
* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: No
* Optifine Installed?: No

Issue: On a Hardcore world started probably in 3.0.3/3.0.4, the Adventurer advancement tab is missing. I have completed all Stage 0 advancements and most Age 1 advancements, including the progression chain except for the last one (Link to the Stars). 

It would be helpful to know what would trigger it. I have started a new hardcore world in 3.0.6 and have gone through a few of the first day advancements, without triggering the tab.

**Comment by justinrusso** [comment]
The adventurer should be triggered when going to the Betweenlands

**Comment by nolaw70** [comment]
Really? I have seen in Direwolf20's playthrough where he is on 3.0.4, in early Age 1, and he has the Adventurer tab. Other youtubers have extra adventurer tabs once they enter the Betweenlands, but the initial one is present before they go.

**Comment by justinrusso** [comment]
Possibly was a bug? Reviewing the tab currently none if it is relevant until you are ready for the betweenlands. Submit an issue if you do not get it after creating the swamp talisman and entering the betweenlands.
