### ISSUE TITLE
Cyclic baubles items stage/recipes need to be reviewed

### ISSUE THREAD

**Issue by justinrusso** [Darkosto/SevTech-Ages#1994]
Some have diamonds and other conflicting items, and all appear to be in stage 2 currently.

**Comment by artdude543** [comment]
The fire charm I did already fix. By switching the diamond to an AS Aqua Gem (may switch it to the use the Resonating one) could do the same for the others.

- Climbing Gloves: Recipe matches the stage its in.
- Fire Gem: Fixed already.
- Sailor Gem: S5 and recipe are fine.
- Water Charm: Needs the recipe changing and/or re-staged. We could get away with it being in S1 with a decent recipe as you could do a lot of water exploring. So could be a nice reward for players.
- Antidote Charm: I'd say this needs changing to S3 (For the Nether) and the diamond swapped out for the Resonating Gem (AS)?
- Wing Charm: Defo a stage S3 item but the recipe needs changing, I guess we could do the same as above?
- Automatic Torch: I feel the recipe needs to be more expensive as it's free torches. S3 seems fine but I can work on a hard recipe. As Coal Blocks / Iron Bars are too "cheap" in my eyes for ~ torches.
- Speed Charm: This recipe is a mess of stages >.> I guess switch the recipe to use the Gem as mentioned. A block of something and change the nether wart for two potions of swift.

I feel like the Gem would be ideal as it still ties with our feelings of using other mods.
