### ISSUE TITLE
Duplicating Machine Blueprint : Chemical Mixer : Modular Machinery #2

### ISSUE THREAD

**Issue by TheLemein** [Darkosto/SevTech-Ages#1997]
**Only Optifine installed**
 

**Used search feature did not see this previously  reported other than my previous post that was closed and titled  "invalid"** 

## Issue / Bug

**While using the Modular Machinery, in this case, Plastic Molder set up. When holding the CTRL key, and clicking on the Machine Blueprint, it ends up sending 15 duplicated Machine Blueprints to my inventory, this can be repeated with other Blueprints also.

## Expected Behavior

**I would assume nothing should happen, I just happened to click CTRL for discord while removing the blue print

## Possible Solution

**N/A**

## Steps to Reproduce (for bugs)

1. Build Modular Machine, plastic Molder (18 blocks total)
2. Right click control panel to open machine 
3. Place Plastic Molder Machine Blueprint on to normal location
4. Hold CTRL key
5. Right click Plastic Molder Machine Blueprint
6. Fill inventory, holding CTRL and SHIFT also changes amount recieved

## Context

**Did not affect me, other than the quick laugh at throwing 300 blueprints at my friends feet while he was AFK... giving him multiple stacks of them. My friends are also able to complete this duplication event.

## Logs

* Client/Server Log:
* Crash Log:
**n/a**

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:

* Memory Allocated:

* Server/LAN/Single Player:
* Resourcepack Enabled?:
* Optifine Installed?:
**Most recent version of modpack / Java 1.8.0 161 64bit / Twitch Launcher / Roughly 7g of memory allocated / Server through MC Pro Hosting / Using Soartex texture pack / Optifine is installed

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Soultion:
* Sponge (Non-Vanilla Forge) Server?:

* Additional Content Installed?:

**Comment by justinrusso** [comment]
https://github.com/Darkosto/SevTech-Ages/issues/1680
