### ISSUE TITLE
Blood Magic Fluid Filter has no recipe and an localized tooltip:

### ISSUE THREAD

**Issue by talonos2** [Darkosto/SevTech-Ages#2003]
## Issue / Bug
The Blood Magic fluid filter has no recipe, and it's tooltip displays as an unlocalized string. It works fine if you op one up, though.

WayofTime seemed confused by this when I asked him about it, so it might be a problem on your end, not his. If this is a bug on his end, could you pass it onto him? EDIT: Nevermind, he found and fixed the issue,

## Expected Behavior
I expect for the tooltip to have a natural language string instead of a localization key. Also to be able to craft the thing.

## Possible Solution
 - Wait for WayOfTime to release a new Blood Magic build. (The issue is now fixed on his end, see chat log below)
 - Update Blood magic once the build is released.

## Steps to Reproduce (for bugs)
1. Do a JEI search for "Fluid Filter" in age 3.
2. Hover over the item in JEI.
3. Click the item to find it's recipe.

## Context
So... I'm kinda trying to break progression by getting fluid transport without a redstone engine...

Either let me do it or crush my hopes and dreams entirely, please. : D (If it has no recipe by design, hide the item. I'm used to "hidden" items being a player signal for "Good thinking, but I can't let you do that.")

## Client Information
* Modpack Version: 3.0.6
* Java Version: 8
* Launcher Used: Twitch
* Memory Allocated: 6GB
## Server Information
* Server/LAN/Single Player: Server
* Resourcepack Enabled?: Nope
* Optifine Installed?: Nope
* Java Version: 8 again.
* Operating System: MineOS Turnkey
* Hoster/Hosting Soultion: Livingroom
* Sponge (Non-Vanilla Forge) Server?: Nope
* Additional Content Installed?: Nope

![2018-04-21_17 29 47](https://user-images.githubusercontent.com/3359830/39089720-da9a536e-458a-11e8-8524-cee67d6c7a35.png)

**Comment by talonos2** [comment]
Turn's out it was on way's end.

![image](https://user-images.githubusercontent.com/3359830/39089764-ad70c4b2-458b-11e8-8fe0-c3a588a6f6fb.png)

I'll leave the issue open but change the suggested resolution to "Update Blood Magic".

**Comment by justinrusso** [comment]
Thank you for going ahead and reporting this issue to the mod dev. We'll look out for that update 👍

**Comment by artdude543** [comment]
This is resolved in 3.0.7 🙂
