### ISSUE TITLE
Excavator not mining some veins

### ISSUE THREAD

**Issue by Quezler** [Darkosto/SevTech-Ages#2008]
## Issue / Bug

Excavator not mining vein found in chunk.

![2018-04-22_14 55 31](https://user-images.githubusercontent.com/3179271/39095276-1e230050-463e-11e8-8518-d7ba27124a5d.png)

(yes, it has sufficient power, is rotating & ground under it is dirt/stone)

## Expected Behavior

Excavator ~not~ mining vein found in chunk.

## Possible Solution

Is this intended behavior to force players to find geolysis veins?

## Steps to Reproduce (for bugs)

1. find certus quartzite vein
2. place rotating excavator

## Context

Trying to mine quartz for AE2.

## Logs

* Client/Server Log:
* Crash Log:

Nothing relevant found in log.

## Client Information

* Modpack Version: 3.0.6
* Java Version: 8
* Launcher Used: Twitch

* Memory Allocated: 9 GB

* Server/LAN/Single Player: over hamachi
* Resourcepack Enabled?: no
* Optifine Installed?: no

## Server Information
* Java Version: 8
* Operating System: windows
* Hoster/Hosting Soultion: friend
* Sponge (Non-Vanilla Forge) Server?: sevtech server 3.0.6 download

* Additional Content Installed?:

**Comment by Quezler** [comment]
# edit

When running the `/ie mineral get` command you can see that the depletion does increase, so the miner is working, yet there is nothing in the buckets or items that are dropping out the backside.

![screen shot 2018-04-22 at 15 39 21](https://user-images.githubusercontent.com/3179271/39095595-7daa6176-4643-11e8-9827-a51d61f84482.png)

**Comment by Quezler** [comment]
@justinrusso let me know if additional info is required in order to debug this issue, other commands to run, files from the server, world stuff, etc

**Comment by Tapeman83** [comment]
I have also experienced this same issue, with Certus Quartzite, Osmium, and Limonite veins. Furthermore, it also sometimes just decides that it doesn't want to excavate Hematite or Autunite, and then randomly starts working again at some point in the future.

**Comment by Jandakast** [comment]
CraftTweaker and Immersive Engineering Excavator custom mineralMixes appear to broken or documented incorrectly.  

Reported to mod. https://github.com/BluSunrize/ImmersiveEngineering/issues/2975

**Comment by Jandakast** [comment]
This is fixed in dev.
