### ISSUE TITLE
Crash!

### ISSUE THREAD

**Issue by Yxlotl** [Darkosto/SevTech-Ages#2010]
Hello!
On startup, my Minecraft crashes when it is done loading all of the mods.
I have 8G of memory allocated.
No resource packs or modifications to the pack have been made.
The mod pack is on the latest version.
Log: https://pastebin.com/Xuwm27Qt

Thanks!

**Comment by justinrusso** [comment]
Please try re-downloading the pack

**Comment by djnifos** [comment]
Forge is pretty old on that crash log (mid February)

**Comment by artdude543** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critial information we can't help you. So if you would like to report the issue again please re-create a issue using the provided template.

Thanks again for reporting, and we hope you enjoy the pack!

**Comment by djnifos** [comment]
Just for posterity, updating forge is the fix for this.  The method it can't find was modded after that version. 

https://github.com/MinecraftForge/MinecraftForge/pull/4753/files/3a3df675d23d8ed5388158e4b71274cc34545768

**Comment by Yxlotl** [comment]
Ok, I apologize for not using the format. I didn't intend to harm anyone or ignore anything. Thank you for the fix!
