### ISSUE TITLE
Sugestion to a problem

### ISSUE THREAD

**Issue by DragonmasterDJ** [Darkosto/SevTech-Ages#2011]
This is more asking of something that could help alot of people. 
I recently started the pack and now have spent two real life days wasting my time looking for a darklands biome. and many others are as well.

I was thinking. what if a darklands biome in the north and south. spawned not too far from the players spawn? but obviously enough that it doesn't have to make them go the distance of a million blocks.

**Comment by justinrusso** [comment]
The location of a darklands biome is predictable. They are in a specific temperature band. The entire generation is using a heatmap. Find the right one by going north or south, then east and west for different biomes in the temperature.

**Comment by DragonmasterDJ** [comment]
@justinrusso I am aware of this. but to me it hasn't mattered. I have headed in south to north directions to find none. again I've been doing this for two days spending a hour each on a new world to try and find them. I cant find any.
