### ISSUE TITLE
(Minor) Rustic crushing and wild dog pelt boots

### ISSUE THREAD

**Issue by mkire** [Darkosto/SevTech-Ages#2013]
Expected behavior: One jump is one whatever turned into juice.

Actual behavior: lots of jumps (i was at ten before i stopped counting) crushed one thing.

Originally I thought it was a problem with the crushing bin, and was going to report that, then i thought maybe my boots of awesome jumping and running were doing something funky and took them off and the problem stopped.

**Comment by kragnoth** [comment]
Also keeps the vanilla elytra to not trigger for me.

**Comment by vadis365** [comment]
Also makes me want to delete both of these for ignoring any sort of template and adding more than one issue here :(

The dog pelt boots just simply listen to the entities' jump event and add a bit to them - what may be causing the crusher to not function as expected could be the negation of fall damage. I'm not sure if such a weird edge case is going to matter really - you can just take the boots off.
As for the Elytra thing, this is the 1st time I've heard of it and as it's not posted as an issue I'll ignore it.

**Comment by artdude543** [comment]
Okay in regards to the boots, just take them off I don't see a need for this to be fixed as it's such an "edge case" issue. I don't see the need to put time into this as the boots do their job for negating fall damage so just remove them when you want to process items. As I feel like the boots will cause more of an inconvenience than anything when using the crusher.

In regards to the Elytra issue @mkire please report a new issue following the template with detailed information so we can look into it. Thanks!
