### ISSUE TITLE
IronWood - On the chopping block milestone- doesn't count

### ISSUE THREAD

**Issue by Kiley169** [Darkosto/SevTech-Ages#2016]
## Issue / Bug

The "On the Chopping Block" milestone doesn't update when using ironwood

## Expected Behavior

Getting the achievement with ironwood 

## Steps to Reproduce (for bugs)

1. Create new world
2. Get flint hatchet
3. Chop down iron wood tree
4. Use ironwood to create a chopping block in crafting grid

## Context

Just started playing the pack. I had iron wood and made the chopping block and then the work stump. 
I did not get the advancement until creating a 2nd chopping block, this time with Oak. 

## Logs

* Client/Server Log: [Minecraft log](https://github.com/Darkosto/SevTech-Ages/files/1935928/Minecraft.log)
* Crash Log: N/A

## Client Information

* Modpack Version:3.06
* Java Version:1.8.0-172
* Launcher Used:MultiMC 5
* Forge: 14.23.2.2651

* Memory Allocated: 4 Gbib

* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: No
* Optifine Installed?: no

**Comment by justinrusso** [comment]
I can't reproduce this. I put an Ironwood log in my inventory, click on the item output. When placed in my inventory, it triggers the advancement.

**Comment by justinrusso** [comment]
Can you screenshot your advancement screen?
