### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Tayba3** [Darkosto/SevTech-Ages#2020]
The server crashes when I leave the area, I just recently set up a weirding gadget and some liquid hoppers hooked up to immersive engineering machines.

## Logs
* Crash Log: https://pastebin.com/0C07Rhtu

## Server Information
 3.0.6
* Java Version: 8 171
* Operating System: Windows 10
* Hoster/Hosting Soultion: Private/me
* Sponge (Non-Vanilla Forge) Server?: what

* Additional Content Installed?: mtqfix just so using the slimesling doesnt teleport us back, it gets rid of the moving too quick message and effect from servers, its been working great the whole time

**Comment by justinrusso** [comment]
https://github.com/Darkosto/SevTech-Ages/issues/1250
