### ISSUE TITLE
Major galacticraft progression bug

### ISSUE THREAD

**Issue by SplitJugular** [Darkosto/SevTech-Ages#2021]
recently reached galacticraft stage and encountered a serious issue with progression.
after doing the quest to reach mars the quest progression jumps to getting to Saturn to start getting the inferium essence.

so i have made the tier 3 rocket and travelled to the asteroid dimension to harvest titanium for higher level galacticraft gear.

however, mining ilmenite ore gives you titanium shards and iron shards. these items have no use shown in JEI and cannot be smelted or ground down to dust.
silk touching the ore lets you then grind the ore block and you then get titanium grit and iron grit which is  a work around but you should have it made possible to process the titanium and iron shards.

also a few extra quest nodes to guide progression through galacticraft would be appreciated

**Comment by justinrusso** [comment]
https://github.com/Darkosto/SevTech-Ages/issues/1411
