### ISSUE TITLE
Crashing When Joining Servers

### ISSUE THREAD

**Issue by fishynuts** [Darkosto/SevTech-Ages#2022]
If I join any server I will load onto it and then be able to move around a bit before being disconnected to the title screen.
I am using a mac and I have 6GB of memory allocated. My log is attached
[latest.log](https://github.com/Darkosto/SevTech-Ages/files/1936086/latest.log)

This is extremely annoying, please reply as soon as possible. Thanks

**Comment by justinrusso** [comment]
Thank you for reporting an issue! But as stated in the issue template (which you have ignored and deleted) any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critial information we can't help you. So if you would like to report the issue again please re-create a issue using the provided template.

Thanks again for reporting, and we hope you enjoy the pack!
