### ISSUE TITLE
Your progression could not be found

### ISSUE THREAD

**Issue by Sakrifized** [Darkosto/SevTech-Ages#2023]
I logged into my save and all my progression on the tab (L) reset.. nothing that I crafted or had reset though

**Comment by justinrusso** [comment]
Thank you for reporting an issue! But as stated in the issue template (which you have ignored and deleted) any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critial information we can't help you. So if you would like to report the issue again please re-create a issue using the provided template.

Thanks again for reporting, and we hope you enjoy the pack!
