### ISSUE TITLE
The modpack won't open and crashes every time

### ISSUE THREAD

**Issue by KingOfZpadez** [Darkosto/SevTech-Ages#2025]
I'm really intrigued with this mod pack, but all that happens when I try to open it is it crashes.
Here is the crash report.
[crash-2018-04-22_15.54.26-client.txt](https://github.com/Darkosto/SevTech-Ages/files/1936111/crash-2018-04-22_15.54.26-client.txt)

**Comment by justinrusso** [comment]
Thank you for reporting an issue! But as stated in the issue template (which you have ignored and deleted) any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critial information we can't help you. So if you would like to report the issue again please re-create a issue using the provided template.

Thanks again for reporting, and we hope you enjoy the pack!
