### ISSUE TITLE
Can't Download

### ISSUE THREAD

**Issue by SAlex925** [Darkosto/SevTech-Ages#2027]
I'm using the twitch launcher to download SevTech Ages, but every time I try to, one of the mods fails to download, usually the shadowlands (or a mod with a similar name), and it cancels the entire download. I've reinstalled twitch, and have completely reinstalled minecraft but it still won't work. But, I tried to download the same version on my grandma's laptop, and it downloaded first time. 
I can transfer the files from her laptop to my PC, but I was wondering if anyone else had the same problem.

**Comment by justinrusso** [comment]
You can ask the community in https://discord.gg/darkosto

As well, if you would like help with the twitch launcher I would suggest you contacting their support.
