### ISSUE TITLE
Unable to find / see coal in stage 1

### ISSUE THREAD

**Issue by JheregJAB** [Darkosto/SevTech-Ages#2030]
## Issue / Bug

I have a world generated with 3.0.6 that does not appear to have coal in it. I've run around quite a bit with the diving rod and can not find coal. Also can't seem to find any surface samples for coal.

## Expected Behavior

I expected to be able to find coal, and at the least for the coal which oredistribution finds to also be able to be found by the diving rod and mined.

## Steps to Reproduce (for bugs)

1. download 3.0.6 server from
2. start new game with defaults
3. progress to stage 1
4. unlock prospecting
5. be unable to get coal.

## Context

I was able to find the tin/copper veins without issue.

I got frustrated and ran /oredistribution, which shows 'GeolosysCoal', but its only appearing at Y 8,9,10. I kept running oredistribution until I zeroed in on where it should be, dug down, and the diving rod does not show anything there. All I can see is stone. Nonetheless, /oredistribution 1 8 10 seems to show that I am currently standing in a bunch of coal.

## Client Information

* Modpack Version: 3.0.6
* Java Version: (client) Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
* Launcher Used: (client) twitch

* Memory Allocated: (client) 6GB

* Server/LAN/Single Player: Server
* Resourcepack Enabled?: none
* Optifine Installed?: no

## Server Information
* Java Version:  OpenJDK build 1.8.0_162-8u162-b12-0ubuntu0.16.04.2-b12
* Operating System: Ubuntu 16.04.3 LTS
* Hoster/Hosting Soultion: none
* Sponge (Non-Vanilla Forge) Server?: no

* Additional Content Installed?:

**Comment by JheregJAB** [comment]
restarting client to check now.

Is there some other way to check for the location of ores using OP commands if /oredistribution doesn't work?

**Comment by SphynxLoL** [comment]
Have you restarted your client since you hit Age 1? I was having some issues where ores wouldn't appear in a new Age until I restarted my client. Not sure if it will work but worth asking/trying.

**Comment by JheregJAB** [comment]
We have found coal.

Not sure what was going on, we looked for literally hours before finding it. In any case, this issue isn't quite right and can be closed.

Too bad the oredistribution command is bugged. Would be nice if that could just be removed if it really doesn't work.
