### ISSUE TITLE
Shadow creatures not spawning in stage 0

### ISSUE THREAD

**Issue by Paul17041993** [Darkosto/SevTech-Ages#2032]
Currently at a progression block where I need to craft the flame-grilled-wopper, however despite being in the darklands for more than 4 nights, searching all biome variants and underground, not a single hostile mob has spawned other than steppe wolves and animals everywhere...

Is there a particular thing that needs to be done before shadow creatures can spawn...? my current tree is as follows;
<img width="354" alt="screenshot_169" src="https://user-images.githubusercontent.com/3912867/39106985-6e753a40-4702-11e8-8f7c-3c3a175deee1.png">

**Comment by neuronoise** [comment]
> not a single hostile mob has spawned

Are you on a peaceful?

**Comment by Paul17041993** [comment]
oh I should've mentioned that the usual hostiles spawned elsewhere, albeit rarely...

As of late however I've done a couple more objectives and hostiles spawn much more commonly, of which I then returned to the darklands for a couple nights and encountered some dark spawns, one of which was the 100hp shadow beast (which wasn't even a threat btw) that dropped two gems.

tree difference;
<img width="396" alt="screenshot_170" src="https://user-images.githubusercontent.com/3912867/39122755-385db95a-4739-11e8-8d3d-152bf1004d1c.png">

From what I can gander, it was a combination of a handicapped spawn rate by the tree, and excessive animal spawns in the darklands, as the areas that hostiles could spawn only had a small amount of passive mobs present...

**Comment by Jandakast** [comment]
The Shadow Creatures will spawn at any stage provided your world spawn cap hasn't been met. This is not an issue with mob staging or any type of gating. As long as you aren't on peaceful and your world can still spawn mobs you will get them.

**Comment by Paul17041993** [comment]
this could be attributed to the fish actually, as they can push the entity count to 200 and over, but I don't know if they're actually in the spawn limiter or not...

**Comment by AMR2586** [comment]
I'm having the same issue with them not spawning. I sat around in the darklands for about 7 hours while I did other work around the house. Not a single hostile mob spawned. Is there a way to check the entity count or to force the current entities to de-spawn?
Thanks,
A

**Comment by Paul17041993** [comment]
The F3 debug will still show entity count, of which needs to be below 80-ish for mobs to spawn. Look around for passive mobs and fish, and ideally try to find a place away from rivers, changing the view distance may also help.
