### ISSUE TITLE
Sheering a mooshroom results in 2 vanilla cows (server)

### ISSUE THREAD

**Issue by Jemsuper** [Darkosto/SevTech-Ages#2036]
Current behavior: Using a bone shear (didnt try other shears) results in dropping mushrooms and 2 vanilla cows spawned. This happend on a server
Expected behavior: mushrooms and 1 cow

Version 3.06, server

I currently do not have acces to my computer to show a pic but can later if requested

**Comment by Jandakast** [comment]
This is reproducible in single player as well, I also noticed that it is dropping 10 mushrooms instead of the normal 5. This appears to be a bug with the Better With Addons hardcore Shearing functionality. Reported to mod dev.

https://github.com/DaedalusGame/BetterWithAddons/issues/110

**Comment by justinrusso** [comment]
Mod fix is available. Will need to look over the changes and ensure nothing breaks.

**Comment by artdude543** [comment]
Fixed for 3.0.7
