### ISSUE TITLE
Age 0 and 1 fishing villager sells automatic fisher that requires fishing rod that can't be crafted yet

### ISSUE THREAD

**Issue by Jemsuper** [Darkosto/SevTech-Ages#2037]
Current behavior: Fisher villager sells automatic fisher, says that it requires a fishing pole but that cannot be accessed yet. 

Possible solutions: 
1. Remove automatic fisher from selling pool
2. Unlock fishing poles in age 0

pack version 3.06, server

**Comment by Jandakast** [comment]
This has been removed from the trade table in dev. Automatic fisher doesn't work anyway as the fishing loot table has been cleared. 

However, Fisherman in an existing world will still have the trade.
