### ISSUE TITLE
Age 2 Astral sorcery grind stone allows grinding ores into unsmeltable dusts

### ISSUE THREAD

**Issue by Jemsuper** [Darkosto/SevTech-Ages#2038]
Current behavior: Age 2 unlocks the Astral sorcery grindstone that allows you to grind ore clusters into dusts, but you cannot smelt these until you obtain the IE Arc furnace

Possible solutions:
1. Remove recipes from grindstone
2. Change output of recipes
3. Allow other smelting devices on dusts

Version: 3.06, server

**Comment by Jandakast** [comment]
Only being able to process ore dust into ingots via the Arc Furnace is intended. This prevents you from doubling ores without power and infrastructure. Ore dusts are also used for alloying and some recipes in later stages. I don't think this needs changed.

**Comment by MissPotato** [comment]
Would marking the items as unknown solve this issues from a player perspective?
