### ISSUE TITLE
Suggestion: Turning off betweenlands advancements

### ISSUE THREAD

**Issue by Jemsuper** [Darkosto/SevTech-Ages#2039]
Betweenlands add a lot of clutter to the advancements tab. And unlike the twilight forest it isnt really usefull to follow them. Suggesting turning them off

**Comment by vadis365** [comment]
Hello,
The pack is designed so people can explore and learn new mods on their own. Progression is a HUGE part of the pack and moves you through the mods. If you are just racing through the advancements to get to the end then I can see why you would request this. The pack has no rules as far as how much you want to do in each mod past the basic progression through the ages but just following a back to get to the 'end' means you miss out on SO much stuff to discover. Having the advancements for the BL allows players to explore the mod and learn new things - Sevadus himself (of whom the pack is made for) has been exploring the Betweenlands mod and the advancements have been key to his playthrough.
Cheers,
Me.
