### ISSUE TITLE
Astral Sorcery Celestial Gateway server crash

### ISSUE THREAD

**Issue by Lewdicolo** [Darkosto/SevTech-Ages#2041]
I named a gateway, placed it down on Venus, was making a obsidian roof over the gateway and when I covered the gateway, it crashed the server trying to remove the gateway from the constellation map (it needs either nothing or a transparent block above the gateway)

https://pastebin.com/DYhQnYTf

SevTech Ages: v3.0.6
Forge: v14.23.2.2654  
Astral Sorcery: v1.8.5
Extra Planets: v0.3.2
Galacticraft-Planets: v4.0.1.170
Galacticraft-Core: v4.0.1.170
GalacticraftTweaker: v1.0.1

**Comment by Jandakast** [comment]
This looks like it will be fixed in the next Astral Sorcery release. 

https://github.com/HellFirePvP/AstralSorcery/issues/583

**Comment by artdude543** [comment]
Fixed for next version!
