### ISSUE TITLE
Crash 3.0.4 - 3.0.6

### ISSUE THREAD

**Issue by Nitess** [Darkosto/SevTech-Ages#2047]
Crash the server when upgrading the server part from 3.0.4 to 3.0.6.
small

java.lang.ClassCastException: betterwithmods.common.blocks.BlockBDispenser cannot be cast to betterwithmods.common.blocks.mechanical.BlockMechMachines
	at betterwithmods.common.blocks.mechanical.tile.TileEntityMill.getBlock(TileEntityMill.java:57)
	at betterwithmods.common.blocks.mechanical.tile.TileEntityMill.func_73660_a(TileEntityMill.java:81)
	at net.minecraft.world.World.func_72939_s(World.java:1832)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)

[crash-2018-04-23_19.55.41-server.txt](https://github.com/Darkosto/SevTech-Ages/files/1939259/crash-2018-04-23_19.55.41-server.txt)

**Comment by Nitess** [comment]
Nothing, he just works in the world

**Comment by primetoxinz** [comment]
Hmm, well this crash is the incredibly bizzare. Having the tile entity for a millstone load on to a block dispenser really should never happen. The best thing I can think of that your world's ids got shifted on one of the updates. 

Did you remove any mods?

**Comment by Nitess** [comment]
Yes deleted 2 not necessary, rollback to 3.0.4 happens without crash, I so understand it occurs with mill stone from bwm?

**Comment by Nitess** [comment]
maybe I'll try to remove it from the world, but it's silly to update the server in this way

**Comment by primetoxinz** [comment]
I would like to know what mods specifically you removed.

**Comment by Nitess** [comment]
better fps and foliage

**Comment by primetoxinz** [comment]
Ok, that debunks my theory. This crash is not due to the millstone or the block dispenser specifically, it is due to the world trying to assign the wrong information to the wrong block, which should not be possible unless your world got corrupted by OTHER means. 
Did you have to revert your save files as well when you went back to 3.0.4?

**Comment by Nitess** [comment]
although it's possible that the update and the rollback I make with my hands and kind of like I moved all the files at once with the world's saves

**Comment by Nitess** [comment]
although it's possible that the update and the rollback I make with my hands and kind of like I moved all the files at once with the world's saves

**Comment by Nitess** [comment]
in the accident there are coordinates of the block from which the accident occurred, according to these coordinates there is a filtered hopper

**Comment by Jandakast** [comment]
The crashlog shows that forge was loaded from source craftbukkit.jar and that you are only running with 3GB of ram. Are you running any plugins or was anything about the server files modified outside of removing the 2 mods you already mentioned? Does this crash happen if you load the world on a server with no modifications? I don't believe this is a pack issue. As @primetoxinz  mentioned, this shouldn't be possible unless there is some sort of world corruption.

**Comment by Nitess** [comment]
No, I work on myarena.ru hosting, in order to run my build, I need to rename forge to craftbukkit, ram 7168 is available, OS Linux server. And no, I just deleted these 2 files from mods

**Comment by Nitess** [comment]
In the same world, the server runs without changes, but crashes when you log on to the server

**Comment by Jandakast** [comment]
I'm assuming it loads the chunk containing the corrupt block when you login. Remove the corrupt block at 680,32,223 using MCEdit or by reverting to 3.0.4 and removing the block before upgrading thew world. Unfortunately, corruption happens sometimes.

**Comment by Nitess** [comment]
@Jandakast I already did it, now I will try again to upgrade to 3.0.6, at this point there is a "mill stone" from bwm, blocked, although in another place there is also a "mill stone" that is not locked, maybe it was cause of an accident blocked by a mill stone.

**Comment by Nitess** [comment]
@Jandakast Hello! I managed to go to him, could you help me a little more. When I enter the server, I see a strange picture, all the blocks in the world are changed


![2018-04-24_14 50 41](https://user-images.githubusercontent.com/30369743/39185665-a3ccb424-47d0-11e8-95eb-997d0ba0aa69.png)


![2018-04-24_14 50 51](https://user-images.githubusercontent.com/30369743/39185656-9bd08e80-47d0-11e8-9ad5-28fb4785fa11.png)
