### ISSUE TITLE
Random Death

### ISSUE THREAD

**Issue by Snookville** [Darkosto/SevTech-Ages#2048]
## Issue / Bug
 After about 20 minutes of play, I will die, but because my nutrition gives me full gold hearts, I don't die. Not sure why I am randomly being killed. Character model is stuck in death position with flashing red. Health can be restored and I don't actually die unless I had no gold hearts.

## Steps to Reproduce (for bugs)

1. Literally just casually play for x amount of time.
2.

## Context
 I am wasting food, and my character model is continually messed up, under circumstances where I lose my gold hearts, I actually die. Losing levels needed for enchanting, etc.

## Client Information
* Modpack Version: 3.0.6
* Java Version:  8 Update 161
* Launcher Used: Twitch
* Memory Allocated: 8GB
* Server/LAN/Single Player: Server
* Resourcepack Enabled?: No
* Optifine Installed?: Yes

**Comment by Dutchs** [comment]
I believe this to be a desync issue where the client thinks it died but the (internal)server disagrees is my guess.
After 7 days ingame playtime had it happen twice.
Relogging fixes the issue.

**Comment by Snookville** [comment]
I had it happen last night, and again today. If it happens again, I will comment further on this post.

**Comment by Snookville** [comment]
Okay, happened again. Seems to be at least once an hour. Relogging not helping.
![2018-04-23_16 15 04](https://user-images.githubusercontent.com/38667858/39150884-ae4fb456-4711-11e8-851c-849318d5dd36.png)

**Comment by Jandakast** [comment]
You mentioned in the OP that if you don't have gold hearts you actually die? I need to know what that death message states. Are you doing something different every time it happens? Are you actually losing any health when this happens? I cannot reproduce this and without logs or something to point my troubleshooting efforts at I cannot help. ☹️

**Comment by Snookville** [comment]
So, I took off my good armor, hurt myself below gold, and starved myself so if it did happen naturally, I would be able to send a log. For some reason, I have a feeling it has to do with the mantle of stars I was wearing from Astral Sorcery. I don't know why it would be killing me, but not having it on has kept me alive for 3 hours.

**Comment by MrBirk** [comment]
I have had this happen to. I want to say it's normally right after I eat and when I drop my nutrition of say fruit below 90%. It kills me and a few gold hearts drop off the bar after I click respawn. I too like everyone else stay in the same location with no actual death. I haven't tried to specifically replicate it I just seemed to notice that it seems to happen then. So might be something to do with nutrition but I am not sure and could be something else.. Anyone else also eating right before this happened?

**Comment by technolem** [comment]
I just had something like that happen when I drank a milk bucket. If its the same problem, it's probably the nutrition buff being canceled out. That removes 10 hearts and triggers a death, but you don't actually die since you still have health left.

**Comment by Jandakast** [comment]
If you get more information on the death or damage type and this ends up being a nutrition or astral sorcery bug then this needs to be reported to those mod devs. We cannot reproduce this issue so we cannot confirm or work with the devs if they need more information.

**Comment by Numorphan** [comment]
This seems to pretty consistently happen to me when I hit 90% of one of the nutrition categories. I then lose all my gold hearts, get the death message, and then go up to 7.5 gold hearts (since it's generally my fruit going to 90%). Seems to be something with Nutrition.

**Comment by Xandaros** [comment]
Me and my friend also have this happen. Last time this happened to me, my fruit nutrition did indeed drop to 90% and I am playing on a server.
Every time this happened to either one of us, the other person was also online. When it happens, we lose all our yellow hearts and get a "You died" screen as described. The paper doll in the inventory screen is displayed sideways, but otherwise the game seems to be able to continue unaffected once you click "Respawn".
Just like @Numorphan I use Hearty Stew as food and neglect the "Fruit" nutrition stat.
