### ISSUE TITLE
[Suggestion] Stardust craftable?

### ISSUE THREAD

**Issue by Serolar** [Darkosto/SevTech-Ages#205]
Seeing as there are 1-3 samples for AS Rock Crystal Ore, which each give 1 stardust, you'd need to cover many, and I mean "many", Chunks just to get the needed stardust to make certain progress points, reaching stage 3. It may be my bad sight, or my safety net, but I have only found 2 rock crystal deposits in the overworld, and 1 in the Twilight Forest. 

Would it be possible, or worth the time saving, to make a recipe for stardust? 

it could use the Starlight Infuser, the Celestial Altar, or some other station, providing elements of the night and starlight, along with, say, platinum, maybe a dust of some sort. It could use a rare mob's drop, maybe Ender Dust, or some other drop? It's really up to you, if it's craftable, and how.

Thank you for your time,
Serolar

**Comment by Darkosto** [comment]
Added a millstone BWM recipe for stardust.

**Comment by Darkosto** [comment]
Actually, I need to add something else in here. But I need to find out the name of the Infusion Altar Structure so I can spawn it in from @HellFirePvP

**Comment by Darkosto** [comment]
Also added a method of converting quartz dust to stardust.
