### ISSUE TITLE
Game Crashed

### ISSUE THREAD

**Issue by oOMrFarrellOo** [Darkosto/SevTech-Ages#2050]
My PC shut down itself while I am playing this modpack. The game achievement got crashed or lost when I restart the game after my pc restart. If there anyway I can go back to my stage? I was just enterd the age 1 and the achievement too.

**Comment by artdude543** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

Thanks again for reporting, and we hope you enjoy the pack!
