### ISSUE TITLE
Can only see R-Click 3x3 crafting table recipes, not L-Click

### ISSUE THREAD

**Issue by DerpityDoo** [Darkosto/SevTech-Ages#2053]
## Issue / Bug
I just logged in and now have no 3x3 crafting grid L-Click recipes visible. I can still view the uses of all items. I can see all processing recipes, regardless of left or right click. The crafting table option is still present in the crafting method options at the top of the window, but there are no recipes in the tab

## Expected Behavior
Left click an item in JEI to see the 3x3 crafting recipe

## Logs
I tried to paste my full log into PasteBin but it was too large, so please tell me how to attach it and I will do it ASAP

## Note
I'm not sure where to even start troubleshooting this, please just ask for any information you need to help me

## Client Information
* Modpack Version: 3.0.6
* Java Version: jdk1.8.0_144
* Launcher Used: Twitch
* Memory Allocated: 12G
* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: Default
* Optifine Installed?: Yes

**Comment by artdude543** [comment]
I can't seem to reproduce your issue here. Have you tried to see if your game derped and rebooted the pack and tried again? Or wait a few seconds after joining for things to sync correctly?

**Comment by DerpityDoo** [comment]
@artdude543 Yeah, I have rebooted the pack and also waited for sync but still no recipes

**Comment by DerpityDoo** [comment]
@artdude543 here is a dropbox link for the text file of the log

**Comment by Rixxaw** [comment]
Sounds like your JEI is in cheat mode but you are not in creative so you can't pull the recipes up in cheat mode.  Check your JEI settings by pressing the gear next to the JEI search bar and verify it is not in Cheat mode.  Correct JEI settings : 

![image](https://user-images.githubusercontent.com/17864718/39362133-de74071e-49ea-11e8-9339-daa6f51ecae0.png)
