### ISSUE TITLE
Mekanism Saw Mill Cuts wood into chopping blocks

### ISSUE THREAD

**Issue by Syltann** [Darkosto/SevTech-Ages#2054]
When using the precision saw mill from mekanism in age 5 to cut wood blocks, it's just drops ALOT of chopping blocks. I REALLY hope that this is not intended, as there should be an easier way to cut wood end game besides horsepower and BWM saw which is really annoying.

**Comment by justinrusso** [comment]
https://github.com/Darkosto/SevTech-Ages/issues/1963
