### ISSUE TITLE
Block bug

### ISSUE THREAD

**Issue by Nitess** [Darkosto/SevTech-Ages#2055]
After upgrading to 3.0.6, most of the blocks in the world have changed. What is the reason for this?
I tried to restore the world from a saved copy, the result is the same
I will add logs if necessary

Before
![2018-04-17_16 05 46](https://user-images.githubusercontent.com/30369743/39189929-28123c12-47dc-11e8-9abd-62a4d30ce36c.png)

After
![2018-04-24_14 51 04](https://user-images.githubusercontent.com/30369743/39189932-2a854eee-47dc-11e8-9657-e4d05145fdf0.png)

**Comment by Jandakast** [comment]
This looks to be an ID shift. This shouldn't happen but when it does it is often related to some sort of world corruption that isn't apparent until an upgrade or mod update. Unfortunately, In my experience there isn't anything we can do about this. I am closing the issue as it is not a pack specific issue.
