### ISSUE TITLE
Paper Recipe with wooden basin doesn't make sense

### ISSUE THREAD

**Issue by Lilbair** [Darkosto/SevTech-Ages#2056]
Paper recipe for the paper recipe is 3 sawdust 1 glue and 1 water gives 3 plant fiber pulp.
Well the Manuel crafting requires 1 sawdust 1 glue 1 water gives 3 plant fiber pulp. 
No point in using the wooden basin for the recipe is that intended?

**Comment by artdude543** [comment]
Please see https://github.com/Darkosto/SevTech-Ages/issues/1339#issuecomment-378963973 this won't change. It's another recipe to help it'a QOL enhancement.
