### ISSUE TITLE
Bronze Ingot on Stone Anvil gives Bronze Rod

### ISSUE THREAD

**Issue by Miyuyami** [Darkosto/SevTech-Ages#2057]
## Issue / Bug
The game showed that I can make Bronze Plates using the Stone Anvil from Bronze Ingots, I tried to do so but I get Bronze Rod (or something similar, the item says it's available in age 3 but I'm in age 1).
**This does not happen in Single Player on my windows machine.**

## Expected Behavior
I should get Bronze Plate instead of Bronze Rod.
I have no other ways of getting Bronze Plates to further advance in age 1.

## Possible Solution
Maybe the mapped IDs are wrong... no clue

## Steps to Reproduce (for bugs)
1. Connect to a Linux server
2. Get Bronze Ingots, a Stone Anvil, a Mallet for the anvil
3. Place the Bronze Ingot on the Stone Anvil
4. Hit the Stone Anvil with the Mallet
5. You get a Bronze Rod instead of Bronze Plate

## Context
I tried to follow the recipe from JEI/NEI and the same it works with other ingots that I used, like Copper and Tin.

## Logs
I don't think this needs any logs but I can add any logs if needed

## Client Information
* Modpack Version: 3.0.6
* Java Version: 1.8.0_171
* Launcher Used: Twitch
* Memory Allocated: 8GB
* Server/LAN/Single Player: Server
* Resourcepack Enabled?: don't think so, everything is default
* Optifine Installed?: no

## Server Information
* Java Version: 1.8.0_161
* Operating System: Amazon Linux AMI
* Hoster/Hosting Soultion: Amazon AWS
* Sponge (Non-Vanilla Forge) Server?: no
* Additional Content Installed?: no

**Comment by justinrusso** [comment]
What version did you create this server on?

**Comment by Miyuyami** [comment]
I created it on 3.0.6
I've read about the 3.0.1 issues but I don't think that's it, I created this server on 17th of April using the server files from https://minecraft.curseforge.com/projects/sevtech-ages

**Comment by justinrusso** [comment]
This appears to be the same issue, just may not be the same cause for it to happen.

Can you upload your crafttweaker.log file? My only guess is that the config files did not copy correctly...

**Comment by Miyuyami** [comment]
Server: [crafttweaker.log](https://github.com/Darkosto/SevTech-Ages/files/1943542/crafttweaker.log)
Client: [crafttweaker.log](https://github.com/Darkosto/SevTech-Ages/files/1943548/crafttweaker.log)

**Comment by Miyuyami** [comment]
Also if I try to get the Bronze Plates by cheating (give command) they will not work in any recipe, even though NEI shows that I can make Armor and Gearbox with them

**Comment by Miyuyami** [comment]
The same issue with Tin Ingot, instead of Tin Plate I get some kind of Age 4 Gear...
Probably there are even more messed up items in the config.
Is there any way I can fix this in the configs? (I don't know anything about how these work)

**Comment by justinrusso** [comment]
It sounds to me like the config for contenttweaker was either corrupted or not copied over when doing the initial install of the server.

You can get the files from the download again, but there will be a few blocks in world that may change and be incorrect blocks

**Comment by Miyuyami** [comment]
I re-downloaded the server files and extracted and installed them again in a fresh location then I copied the "world" folder.
The issue still remains.
I also tried this with a fresh install and new world.

Maybe I'm doing something wrong when installing?
This is exactly what I'm doing:
1. Download the server files zip
2. Transfer them via SFTP to the Linux machine
3. Unzip in a new directory
4. Run Install.sh with sudo
5. Edit settings.sh with 2G min and 6G max
6. Run StartServer.sh with sudo
7. Wait until it closes because EULA
8. Edit eula.txt
9. StartServer.sh again
10. Connect to the server
11. Get a mallet, a stone anvil and a bronze ingot
12. Try to craft the bronze ingot on the stone anvil using the stone mallet
13. Get some kind of Rod (Bronze Rod?)

Log from the fresh server with the fresh world: [crafttweaker.log](https://github.com/Darkosto/SevTech-Ages/files/1944955/crafttweaker.log)
Also a screenshot: https://puu.sh/A9Mm1.png

Is this issue not reproducible on your end?

**Comment by justinrusso** [comment]
Can you go into the `config/acronym/saved/` and provide `material_parts_contenttweaker.json`

**Comment by justinrusso** [comment]
Just to confirm.. (Sorry I forgot to specify) is this the server file?

**Comment by Miyuyami** [comment]
Yes, it's the one from the server, it seems to be completely identical to the one from the zip on curseforge.
Is it supposed to get modified?

**Comment by Miyuyami** [comment]
I reinstalled the modpack (also minecraft since twitch was glitching) and it works now, I connected to the initial server files and world and the items that showed up wrong now show up all right.
I have no clue what happened to the client files, I re-installed the same way I installed it at first.

Thank you for the help. :)
