### ISSUE TITLE
Recipe - Modularium incorrect in JEI

### ISSUE THREAD

**Issue by PsyberMind** [Darkosto/SevTech-Ages#2062]
in JEI, Modularium calls for Redstone, Iron and Aluminum I just crafted a bunch with only Redstone and Iron

Not sure which is wrong, Tinkers config or JEI

**Comment by artdude543** [comment]
Tested this in a world just now and with just iron and redstone melted down. They do not mix _(as intended)_ are you sure the smeltery was empty?

**Comment by PsyberMind** [comment]
Yea, it was completely empty - I have a BC Pipe pumping out to a Tinker Tank, and I switched off the engine in order to allow the alloy before I pushed it into the tank

**Comment by artdude543** [comment]
Tested the same setup as you mentioned and still noting

![image](https://user-images.githubusercontent.com/1885466/39219461-811193d0-4822-11e8-8110-a8707bc21cb8.png)

**Comment by PsyberMind** [comment]
That's weird.. I don't know then.. can go ahead and close if you can't reproduce.. if I run into it again, I'll make sure to SS it, or grab a clip of my stream. (and what resource pack is that? That's clean looking)

**Comment by artdude543** [comment]
Soartex Fanver :) And yeah unless you can give me video proof of it working again, and again then I can try to debug it more. So if you could close aye.
