### ISSUE TITLE
Blood Magic Sigils Wiped

### ISSUE THREAD

**Issue by Phantum** [Darkosto/SevTech-Ages#2063]
## Issue / Bug
One of my subs and I are using a sigil of holding for our different sigils, in blood magic, (sigil of bloodlamp, sigil of infinite water, etc etc.   Upon the 3.0.7 update it wiped them out Edit:[(as in sigil of holding dissapeared).]  Not sure if it's just from sigils being in the sigil of holding, or something else.  

## Expected Behavior
On update the sigils should have remained as they are!

## Possible Solution
Remove sigils from sigil of holding before updating?

## Steps to Reproduce (for bugs)
1. update server to 3.0.7
2.Check for Sigil of Holding

## Context
It's not really that big of a deal for me and my buddy as they're not that expensive to make at this age, (Age 4) but for earlier ages when just starting out, they are kinda pricey!

## Client Information
* Modpack Version: SevTech 3.0.7
* Java Version: 8U161
* Launcher Used: Twitchapp -  10GB

* Memory Allocated:
* Server/LAN/Single Player: Server
* Resourcepack Enabled?: No
* Optifine Installed?: No

## Server Information
* Java Version: 8u161
* Operating System:Linux
* Hoster/Hosting Soultion:Nodecraft
* Sponge (Non-Vanilla Forge) Server?: No

* Additional Content Installed?: MCLink

**Comment by Phantum** [comment]
I can't seem to reproduce it either, even from loading backups to backups.
I did the exact same process I did as last time, and I cannot get it to delete the sigils, so not sure why it happened. o.0

**Comment by artdude543** [comment]
Yeah, multiple people have tried this one and can't get it work. If this is an issue again you can re-open a new issue with additional information or exact steps on what you did to cause the said issue. Then hopefully we can find the cause if any 🙂
