### ISSUE TITLE
Fire issues and No visible solution.

### ISSUE THREAD

**Issue by SeaGoingJet** [Darkosto/SevTech-Ages#2064]
I've seen this issue written about in a couple other areas but none of them have, from what I can see, an acctual solution just a vague question then a "thank you" message that provides no help. I'm in age 0 and have done nothing to edit the pack itself. I can't get this to work right and the lack of answers is really frustrating. Please send Help.

 
## Issue / Bug

I've seen this issue written about in a couple other areas but none of them have, from what I can see, an actual solution just a vague question then a "thank you" message that provides no help. I'm in age 0 and have done nothing to edit the pack itself. When ever attempt to use fire sticks to light a fire, the fire goes out automatically. I'll atach a link to a thread with a video but while I found a possible idea whats going on, I have found a solution. I can't get this to work right and the lack of answers is really frustrating. Please send Help.

https://github.com/Darkosto/SevTech-Ages/issues/947
## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:

* Memory Allocated:

* Server/LAN/Single Player:
* Resourcepack Enabled?:
* Optifine Installed?:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Soultion:
* Sponge (Non-Vanilla Forge) Server?:

* Additional Content Installed?:

**Comment by artdude543** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

Thanks again for reporting, and we hope you enjoy the pack!

**Comment by vadis365** [comment]
Click once with the sticks and wait. You are putting the fire out by punching it.
Do not post the issue again. Thank you.
