### ISSUE TITLE
Mekanism Gas Tanks don't interact with Inductive logistics pipes

### ISSUE THREAD

**Issue by Dystilled** [Darkosto/SevTech-Ages#2067]
#1818 

Some feedback for Artdude. 
Don't close an item and say the template hasn't been followed correctly without first checking if the information is relevant. 
Also, most of the reporting system you are referring to didn't exist when I filed the initial report, only 4 or 5 basic items, I deleted 2 which weren't relevant or were optional. 

It's not my problem you took 2 weeks to read the report and things have changed since then (additional items added to report template). And the condescending way you responded to the thread was in no way appreciated. 

 
## Issue / Bug
Mekanism gas tanks do not interact with inductive logistics pipes, despite them treating items such as O2 gas as a gas. 

## Expected Behavior
Would connect and interact. 

## Possible Solution
Check functionality. 

## Steps to Reproduce (for bugs)
Connect mekanism gas tank to logistics pipes (including extractor/injector). 

## Context
Pack is limited in transfer options, this unecessarily reduces further your option. 

## Client Information

* Modpack Version: all up until current. (0.6)
* Java Version: Latest
* Launcher Used: Twitch Java

* Memory Allocated:12 gb

* Server/LAN/Single Player: SP
* Resourcepack Enabled?: Soartex
* Optifine Installed?: Y

**Comment by codewarrior0** [comment]
Since "all up until current" is ambiguous, especially if a new version has been released since the issue was reported, may I suggest writing an explicit modpack version such as "3.0.3" instead of saying "current" or "latest"?

**Comment by Dystilled** [comment]
It's not vague at all. The issue has been present in every iteration of the mod pack up until present. 

Quite the opposite of ambiguous.

**Comment by Rixxaw** [comment]
Mekanism Gas tanks are part of the Mekanism Gas piping system and as such likely only talk to their own pipes to make sure you don't cheat around the fact that you need a "Gas" pipe instead of a "Liquid" pipe.

No wonder Artdude is snarky with so many issues that are just no relevant to what actually needs to be worked on.

If you want to move Gas here is your recipe my dude : 
![image](https://user-images.githubusercontent.com/17864718/39361820-afec2a76-49e9-11e8-8a1a-652efc648283.png)

**Comment by justinrusso** [comment]
>  Don't close an item and say the template hasn't been followed correctly without first checking if the information is relevant.

The information is relevant. Versions can affect the validity of your issue for starters.

As @Rixxaw stated, this is intended.
