### ISSUE TITLE
Sponge and SevTech 3.0.6

### ISSUE THREAD

**Issue by Vlado753** [Darkosto/SevTech-Ages#2069]
Please don't kill me.

## Issue / Bug
Server is starting very slow... sometimes it takes 15 minutes to start the server.
While playing, when you destroy block, block above it (for example: torch) just breaks and don't drop.
Even TPS is worse.

## Possible Solution
I am looking for advice.

## Context
Server perfomace is poor.

## Logs
This takes the longest time. (found in debug.log)
"Sent event FMLPostInitializationEvent to mod"

## Client Information
* Modpack Version: 3.0.6
* Launcher Used: Twitch
* Memory Allocated: 10GB
* Server/LAN/Single Player: Server for 2 people

## Server Information
* Java Version: Not known
* Operating System: Linux
* Hoster/Hosting Soultion: ScalaCube
* Sponge (Non-Vanilla Forge) Server?: Yes
* Additional Content Installed?: Not  yet

**Comment by artdude543** [comment]
Sponge is not supported at all with this modpack. Due how much Sponge breaks things. You'll need to try and get help from the Sponge support team on this matter. But we don't offer any support to anything relating to Sponge.
