### ISSUE TITLE
Liquid Starlight in Fluid Vessel visual error

### ISSUE THREAD

**Issue by Serolar** [Darkosto/SevTech-Ages#207]
Astral Sorcery's Liquid Starlight, when placed into an Embers Fluid Vessel, appears to have some extra texture around the liquid(At very specific view points), rather than, for example, Immersive Engineering Creosote, which the surface of the creosote fills the area of the tank's inside.

Does not happen with Tinker's Compliments Porcelain Tank
likely a visual bug only.

Sevtech Version 8
Changed HChunger in BWM config to false.

**Comment by Darkosto** [comment]
Can you post a screenshot so I may see what you're referring to?

**Comment by Serolar** [comment]
I seem to be unable to reproduce this issue in a Flat world. I have a LOT of snapshots testing to see where it  happens, but I think it'd be a sort of waste, as my world has been in A5, A7, and A8. Here's at least one
![2017-11-26_13 02 50](https://user-images.githubusercontent.com/16960400/33243448-1035596c-d2ac-11e7-8f9e-97fe4b6cd7db.png)

**Comment by Darkosto** [comment]
Found the issue. When Liquid starlight is placed into the vessel all other vessels show this texture map glitch. It has something to do with the liquid starlight texture being too high res and Embers not handling height/width correctly. 

The issue seems to be on the side of Embers to fix.

**Comment by Darkosto** [comment]
Sorry, but everyone isn't allowed to make textures greater than 16x or else you're wrong. Closing the issue because it's not getting fixed.
