### ISSUE TITLE
Porcilain Heater advancement not trigering

### ISSUE THREAD

**Issue by MagicCrystal** [Darkosto/SevTech-Ages#2070]
## Issue / Bug
 I made the heater and the advancement is not going

## Steps to Reproduce (for bugs)

1.
2.

## Client Information

* Modpack Version: 3.0.6
* Java Version: Latest
* Launcher Used:Twitch

* Memory Allocated: 6G

* Server/LAN/Single Player:Server
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by MagicCrystal** [comment]
I also have all the other advancements up until this point besides the boss that you have to kill

**Comment by artdude543** [comment]
I've just done this fine. You stated you are on a server? Got any information about the server? As it does ask to supply that information... But I've just tested this now both on SMP and MP and it's fine. So either your missing one of the steps and/or your server is broken (or using Sponge) which is breaking the tracking.

**Comment by MagicCrystal** [comment]
So far I have the Grill Hopper thing that comes before the Heater, But when I make the heater nothing happens. And the Server is not using Sponge, But if its broken how could you tell. But is there a way to force the progression or would I have to start a new world?

**Comment by SphynxLoL** [comment]
iirc that advancement requires both Heater AND Melter.

**Comment by artdude543** [comment]
Yeah, this seems like a user error not completing the advancement correctly. And/Or broken server install but if you progressed this far it's not that. So ensure you completed all the needed items/steps for advancements.
