### ISSUE TITLE
BUG Fluid Bladder Emptying Occasionally

### ISSUE THREAD

**Issue by VyxiFaye** [Darkosto/SevTech-Ages#2075]
There is an occasional occurrence where you will fill the fluid bladder with water and go to craft with it and it will be empty. I have been able to capture it on video, link is below. It only happens every so often, so it's nothing of super importance, but it is a little annoying. I am on version 3.0.6. 

https://youtu.be/EqLcJuvXQyU

**Comment by artdude543** [comment]
Looks like when you picked up the water it was from a bit away and caused the glitch/issue. The mod had some major changes which are in 3.0.7 so it _may_ is fixed. But if not can you file an issue with PrimalCore and let them know :)

But I have a hunch that's it cos you picked up from a bit away. Which I have seen this with Vanilla buckets before.

**Comment by VyxiFaye** [comment]
Gotcha! I'll keep an eye on it after the update and if it keeps happening I'll let the PrimalCore mod know. Thanks for your help. 😀
