### ISSUE TITLE
Dupe bug

### ISSUE THREAD

**Issue by masonpinder** [Darkosto/SevTech-Ages#2076]
You can swap a bag out of your hand, while it is open, and dupe the contents. Press F on it, while inside and then press F on a different slot to place it back in your inventory while it is open. Throw it on the ground, and you can dupe items from it...
This works with all the iron backpacks, and I'M pretty sure a few of the other bags also work with it.

**Comment by artdude543** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

Thanks again for reporting, and we hope you enjoy the pack!
