### ISSUE TITLE
Using sigil of blood lamp inside a sigil of holding crashes the game

### ISSUE THREAD

**Issue by LordHellscream** [Darkosto/SevTech-Ages#2077]
## Issue / Bug

using the sigil of blood lamp inside a sigil of holding crashes the game

## Steps to Reproduce (for bugs)
have 2 sigils in sigils of holding.
1st slot: sigil of divination
2nd slot: sigil of blood lamp

Activate the sigil of holding on the ground (sand block).

Age2.

Use it on the ground (sand block)

## Logs
https://pastebin.com/ExfmHn50

## Client Information

* Modpack Version:
* Java Version: 8 117
* Launcher Used: 

* Memory Allocated:

* Server/LAN/Single Player: Single
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by EhGneissGuy** [comment]
See #2071

**Comment by LordHellscream** [comment]
It looks like using the blood lamp sigil on its own still crash the game. is there anyway to avoid the crash for the time being while waiting for the new release?

**Comment by artdude543** [comment]
You're going to have to wait for the update or manually update BloodMagic yourself.
