### ISSUE TITLE
what is the point in makeing a moduler machinery industriul mill?

### ISSUE THREAD

**Issue by csg1995** [Darkosto/SevTech-Ages#2078]
less of a bug and more of a question, but the industrial mill has less recipes than the normal one, as it is unable to create dyes, rice/barley flower, ground resin, or ground meat, and it has no improvement in output, so it just seams like a waste of recourses to build one unless I am missing something.

**Comment by artdude543** [comment]
It's designed to allow better automation when you reach higher tech tiers. It will have more recipes in time but for now, it has the main ones which people wanted to allow for the automation w/o having to make a mess of pipes/hoppers etc.. So you're getting a fairly easy machine to add automation too.

It's not always about lack of recipes use your mind and get creative on what you can build with some the custom machines we've added. The pack is aimed to make you explore options for builds and not stick to the same meta when it comes to packs with tech mods. I hope this answers your question.

**Comment by tjsd** [comment]
Hello!
Here are some recipes you can include in next update that I found.
File: scripts\mod_integrations\modular_machinery\industrial_mill.zs

`mods.modularmachinery.RecipeBuilder.newBuilder(createRecipeName(machineName, "sugar"), machineName, 128)
	.addEnergyPerTickInput(4)
	.addItemOutput(<minecraft:sugar> *2)
	.addItemInput(<minecraft:reeds>)
	.build();
	
mods.modularmachinery.RecipeBuilder.newBuilder(createRecipeName(machineName, "fibreHemp"), machineName, 128)
	.addEnergyPerTickInput(4)
	.addItemOutput(<betterwithmods:material:3> *3)
	.addItemInput(<betterwithmods:material:2>)
	.build();	
	
mods.modularmachinery.RecipeBuilder.newBuilder(createRecipeName(machineName, "blue_dye_powder"), machineName, 128)
	.addEnergyPerTickInput(4)
	.addItemOutput(<pickletweaks:dye_powder:11> *2)
	.addItemInput(<minecraft:dye:4>)
	.build();
	
mods.modularmachinery.RecipeBuilder.newBuilder(createRecipeName(machineName, "black_dye_powder"), machineName, 128)
	.addEnergyPerTickInput(4)
	.addItemOutput(<pickletweaks:dye_powder:15> *2)
	.addItemInput(<minecraft:dye>)
	.build();

mods.modularmachinery.RecipeBuilder.newBuilder(createRecipeName(machineName, "black_dye_powder"), machineName, 128)
	.addEnergyPerTickInput(4)
	.addItemOutput(<pickletweaks:dye_powder:15> *2)
	.addItemInput(<actuallyadditions:block_black_lotus>)
	.build();

mods.modularmachinery.RecipeBuilder.newBuilder(createRecipeName(machineName, "green_dye_powder"), machineName, 128)
	.addEnergyPerTickInput(4)
	.addItemOutput(<pickletweaks:dye_powder:13> *2)
	.addItemInput(<minecraft:dye:2>)
	.build();	

mods.modularmachinery.RecipeBuilder.newBuilder(createRecipeName(machineName, "brown_dye_powder"), machineName, 128)
	.addEnergyPerTickInput(4)
	.addItemOutput(<pickletweaks:dye_powder:12> *2)
	.addItemInput(<minecraft:dye:3>)
	.build();	
	
mods.modularmachinery.RecipeBuilder.newBuilder(createRecipeName(machineName, "rice flour"), machineName, 128)
	.addEnergyPerTickInput(4)
	.addItemOutput(<betterwithaddons:japanmat:4>)
	.addItemInput(<actuallyadditions:item_food:16>)
	.build();	
	
mods.modularmachinery.RecipeBuilder.newBuilder(createRecipeName(machineName, "ground_resin"), machineName, 128)
	.addEnergyPerTickInput(4)
	.addItemOutput(<primal:tannin_ground> *2)
	.addItemInput(<ore:barkWood>)
	.build();	


mods.modularmachinery.RecipeBuilder.newBuilder(createRecipeName(machineName, "unfired_poecelain"), machineName, 128)
	.addEnergyPerTickInput(4)
	.addItemOutput(<ceramics:unfired_clay:4> *2)
	.addItemInput(<minecraft:dye:15>)
	.addItemInput(<minecraft:clay_ball>)
	.addItemInput(<minecraft:flint>)
	.build();`
