### ISSUE TITLE
Less Blood Lamp Reagent Will Requirement

### ISSUE THREAD

**Issue by Darkosto** [Darkosto/SevTech-Ages#2079]
Lower will amount of Blood Lamp reagent to less than 64 to allow possibility in stage 1

**Comment by Darkosto** [comment]
OR, move the sentient sword into Stage 1 and allow it to be crafted using Black Quartz instead of iron and a petty gem.

**Comment by justinrusso** [comment]
Closed in https://github.com/Darkosto/SevTechAgesConfigs/commit/e0019697edf49ffadb36fe9792b5fc2e1bb816f1
