### ISSUE TITLE
Copper gear recipe is broken, and not all copper plates are supported

### ISSUE THREAD

**Issue by justinrusso** [Darkosto/SevTech-Ages#208]
Copper gear stage one recipe is broken. I'm assuming its related to the same recipe appearing in stage three creating Copper Sheetmetal x4

Also, not all plates are supported. Contenttweaker's copper plate is not ore-dict, though I've noticed other plates from contenttweaker are.

![image](https://user-images.githubusercontent.com/25138621/33176642-c2af3c7e-d02d-11e7-825d-23b7ccd08542.png)
(Screenshot thanks to Shoji22)

**Comment by Darkosto** [comment]
Should be all fixed up!
