### ISSUE TITLE
Rustic brewing barrel turns syrmorite buckets into weedwood bucket

### ISSUE THREAD

**Issue by billybricker** [Darkosto/SevTech-Ages#2080]
## Issue / Bug

The brewing barrel from Rustic takes syrmorite buckets but returns weedwood buckets.

Edit: should probably note I only tested with grape juice but I would assume it happens with any fluid that the barrel accepts.

## Expected Behavior

I'd expect a syrmorite bucket if that's what I put in there.

## Possible Solution

The buckets use the same item id with different metadata so maybe ask the rustic dev to implement a check in the keg?

## Steps to Reproduce (for bugs)

1. Place syrmorite bucket with juice into the barrel
2.  Receive weedwood bucket in output slot

## Context

Was trying to brew wine and lost my good buckets!

## Logs

* Client/Server Log: 
* Crash Log: N/A

## Client Information
* Modpack Version: 3.0.6
* Java Version: 1.8.0_161
* Launcher Used: MultiMC imported from a Curse .zip
* Memory Allocated: 5461 MB
* Server/LAN/Single Player: SSP
* Resourcepack Enabled?: No
* Optifine Installed?: No

This originally happened in a slightly modified instance but I tested with a fresh stock one to be sure.

**Comment by justinrusso** [comment]
Not sure what fixes this, but I cannot replicate this in our dev environment. Going to close this and if you still have an issue in 3.0.7, please report the issue again.

**Comment by TheAtomicOption** [comment]
Just had this issue using 3.0.8. 

Recreate: 
1. Place Brewing Barrel. 
2. Add some seed wine from a glass bottle.  
3. Stomp 4 grapes in crushing tub and collect juice with syrmorite bucket
4. re-open barrel interface and shift-click grape juice bucket in your inventory. syrmorite bucket will dump grape juice in but return as a weedwood bucket.

This may be related to another bug where syrmorite buckets acquire a "burn time: 75000" attribute (visible while holding shift), and will no longer stack with other syrmorite buckets unless they both have it. They acquire the attribute after holding liquids from the infuser and lose it again if used to transport swamp water.

**Comment by TheAtomicOption** [comment]
if it will matter, this occured in Age 2
