### ISSUE TITLE
crash after fixing dragon not spawning

### ISSUE THREAD

**Issue by PaternoX** [Darkosto/SevTech-Ages#2081]
## Issue
 We had a problem with the dragon not spawning in the end, and inmplemented the temporary fix of editing the level.dat so that dragon/previouslykilled = 0, and deleting the DIM1 file. this worked, spawned the dragon,which we kilkled, creating a poretal to return back to base.

However, upon returning to the overworld, the server crashes, stating the 'Exception in server tick loop' in the description. We downloaded the world and attempted to open in single player to identify the problem, and recieved the following crash report.

## Expected Behavior
Upon entering the portal from the end, expect to spawn back at base/bed

## Possible Solution
unknown, hence the report and help requested.

## Context
eager to progress with ender alloys and flying to the moon

*server crash log: https://pastebin.com/fpXQr9bq (from server)
* client Crash Log: https://pastebin.com/fiaeqnAu  (after attempting as spw)

## Client Information

* Modpack Version: 3.0.6
* Java Version: latest version
* Launcher Used: twitch launcher - latest  version
* Memory Allocated: 9102MB
* Server/LAN/Single Player: server and single player
* Resourcepack Enabled?: no
* Optifine Installed?: no

**Comment by Quezler** [comment]
I forgot the issue #, but we/i had this problem to, delete the end folder, and in the launcher change the forge version from suffix `51` to the version below it, `50`, which does not have the enderdragon bug.

**Comment by PaternoX** [comment]
client side launcher or on the server?

**Comment by Quezler** [comment]
in the server and all people's clients connecting to it.

**Comment by PaternoX** [comment]
how/where do i find that to change it? (thx for your help btw)

**Comment by Quezler** [comment]
In order of where to click:

<img width="169" alt="screen shot 2018-04-26 at 11 07 07" src="https://user-images.githubusercontent.com/3179271/39296766-0c3baff2-4942-11e8-833c-3ff0ac2cecfd.png">
<img width="860" alt="screen shot 2018-04-26 at 11 07 19" src="https://user-images.githubusercontent.com/3179271/39296776-13665b60-4942-11e8-82b6-0d4b945a60d3.png">
<img width="423" alt="screen shot 2018-04-26 at 11 07 30" src="https://user-images.githubusercontent.com/3179271/39296780-151e86a8-4942-11e8-9b27-080dcadc7e33.png">

**Comment by PaternoX** [comment]
k thanks, so thats client side, do i need to/how do i do that server side?

**Comment by Quezler** [comment]
- Copy the forge jar from client to server when you update the client
or
- [download from forge website](http://adfoc.us/serve/sitelinks/?id=271228&url=https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.2.2650/forge-1.12.2-14.23.2.2650-universal.jar)

**Comment by PaternoX** [comment]
is that twitch_SevTechAges_3.0.6.jar (we use the twitch launcher)

**Comment by artdude543** [comment]
The crash your getting is related to about three mods which are fixed for the next version 3.0.7, fixing Dragons was easier to downgrade Forge which meant all clients/server had to be shifted down. If you're running a large server it's not really viable. 

3.0.7 is not that far off now. So I would highly recommend to not mess around with versions in the possibility of making something worse and/or corrupting your world due to the amount of version of changing w/o correct testing.

**Comment by PaternoX** [comment]
sorry for needing it spoon-fed quezler, but once ive copied the forge jar from client, what folder do i find it in on the server

**Comment by artdude543** [comment]
If it's not that large then to _fix_ the dragon spawning all you need to do is drop the Forge version. On Twitch it's easy by changing the profile options. Then on the drop-down select the `2650` version.

For the server download: [Here](http://adfoc.us/serve/sitelinks/?id=271228&url=https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.2.2650/forge-1.12.2-14.23.2.2650-installer.jar)  _(The ad link is Forges own)_ Run the installer, use the server download option it will download/create all the files needed and then you upoad them to the server.

Obvs change the startup command to use the now _new_ version of Forge then boot the server delete dim 1 and your good to go. This a tested method with the pack and works fine. _(We only have two hard crashes so far but that's unrelated to the ones you've had)_

But it's purley up to you on what you want. I would wait for 3.0.7 but if you need the dragon now I have listed on how to get it sorted 😄

**Comment by PaternoX** [comment]
righty-ho, if 3.0.7 isnt that far off, think we can wait before attempting the end :)

**Comment by Quezler** [comment]
I do not mind spoon feeding people, as long as it helps them om their way ;)

**Comment by artdude543** [comment]
Sweet! Glad we got this one resolved. Cudos to Quezler for helping out on this one!

I would say 3.0.7 is probs tops a week before release if not sooner 🙂
