### ISSUE TITLE
Backups??

### ISSUE THREAD

**Issue by DragonmasterDJ** [Darkosto/SevTech-Ages#2082]
So the time I'm writing this my laptop has overheated. when I went back onto the world. my entire advancement progress is set back to zero. after searching through the files I cant seem to find backups. is there any way to get them back. or manually set my progress back to where it was?

**Comment by Quezler** [comment]
Not sure about how to restore them, but ti manually set them you can use the vanilla [`/advancement`](https://minecraft.gamepedia.com/Commands/advancement) command, be careful so you do not accidentally grant yourself everything though.

**Comment by artdude543** [comment]
We don't offer a backup mod currently. It's not a need or a must for modpacks. You are free to install your own ones.

However, you can use the command mentioned above to give yourself the advancements.
