### ISSUE TITLE
Astral sorcery - collector crystal don't work with Iridescent Altar

### ISSUE THREAD

**Issue by Nedvokis** [Darkosto/SevTech-Ages#2083]
So, I upgrade my Celestial Altar to Iridescent Altar and go thrue Astral Tome to make it work. When I link any type of collector crystal to new Altara, it dosn't boost astral sorsery power at all. Just type in chat that it linked to altar.

 I think this a bug becose Celestial Altar works fine with collector crystal, that's make me think that this is not intedet. Screenshots bellow show that altar dosn't react at crystal.

 I don't add any mods or some thing else and use fresh java.

With linked crystal to altar:
![2018-04-26_13 43 28](https://user-images.githubusercontent.com/13510314/39302104-2ffa6bfa-495a-11e8-907f-9c7a5eef0959.png)

Unlinked altar:
![2018-04-26_13 43 42](https://user-images.githubusercontent.com/13510314/39302109-345b6cee-495a-11e8-8abf-833cd95d4e47.png)

**Comment by djnifos** [comment]
Make sure that none of the starlight boosting structures are within 16 blocks of each other.  Not just separate chunks, but 16 real blocks.  Also, this question belongs on the Astral Sorcery issue tracker, and not here.

**Comment by Nedvokis** [comment]
I don't have more boosting structures at this moment, so it can't be an issue. And I find this bug only on this mod pack. I will try it in vanila minecraft and if it dos't work there, then I type this issue for Astral Sorcery issue tracker and close it here, if it will work, so that mean problem in setings of mod pack.

**Comment by Nedvokis** [comment]
So I check it. I use same minecraft -v and forge like in sevtech and mods I use JEI, Astral sorcery and baubles(astral sorcery astral sorcery not work with out it). And it's work fine.

Unliked:
![2018-04-26_15 31 31](https://user-images.githubusercontent.com/13510314/39305956-80ada384-4967-11e8-80bf-c37cba778e08.png)
![2018-04-26_15 31 34](https://user-images.githubusercontent.com/13510314/39305957-80ccfa0e-4967-11e8-9c54-5610664db990.png)

And with link:
![2018-04-26_15 31 41](https://user-images.githubusercontent.com/13510314/39305984-8d5fc0f8-4967-11e8-8cef-388696106deb.png)
![2018-04-26_15 31 47](https://user-images.githubusercontent.com/13510314/39305985-8d804b3e-4967-11e8-9928-abe841211b22.png)

**Comment by Nedvokis** [comment]
So after I done this and go back to sevtech and (that's funny) it's work fine. So mb I just need try to turn it off and on again. But before I left sevtech I remove all spectral relay that boost altar and collector crystal that I use for lightwell(it dosnt remove bug before I left mod pack). Now I return it back and it work fine.
