### ISSUE TITLE
Barrels not craftable with specific planks

### ISSUE THREAD

**Issue by KewaiiGamer** [Darkosto/SevTech-Ages#2085]
## Issue / Bug
There seems to be not much options in terms of barrel crafting!
I've found three types of wood since I started the game: IronWood, Olive and Yew. 
I first tried to use Olive to craft a barrel to find out that there is no option, then I went to check which typse of wood I could use. IronWood and Yew were two of them so I tried to use IronWood since it was night time and I didn't had any Yew Planks. It seemed that the IronWood I had was from Rustic and the required for crafting was from PrimalCore so it wouldn't let me craft it.
The Yew Barrel was the only one that I was able to craft!

## Expected Behavior
Barrels should be craftable with any type of wood.

## Possible Solution
Perhaps make it so that when you use an unknown type of wood (such as Rustic IronWood or Olive) it turns into an Oak Barrel

## Client Information

* Modpack Version: 3.0.6
* Java Version: Java 8 171
* Launcher Used: MultiMC latest Dev Version on Linux
* Memory Allocated: 6GB

* Server/LAN/Single Player: SP
* Resourcepack Enabled?: Default
* Optifine Installed?: Yes (doesn't really matter tho)

**Comment by Rixxaw** [comment]
Its pretty common that Modded woods aren't ore dictionary, most players would realize they just need to use vanilla woods.  Especially if the recipes are for Oak barrel / birch barrel etc.  Why would you expect Ironwood to make an Oak barrel?

**Comment by KewaiiGamer** [comment]
Unless you want to make barrel textures for every single wood I think it's better to use a default type of Wood for this kind of things
