### ISSUE TITLE
Osmium Mineral not minable (problem with the IE excavator)

### ISSUE THREAD

**Issue by SaculRennorb** [Darkosto/SevTech-Ages#2086]
## Issue / Bug
I'm unable to get the Immersive Engineering excavator to mine the Osmium Mineral that i found using the IE core drill. In addition, the IE manual doesn't show the geolosys osmium cluster, only the ore block unlike with every other ore (might hint at some registration problem).

Just as a side-note, the `/ie mineral get` number isn't changing

## Expected Behavior
The IE excavator should mine osmium Minerals as clusters. 

## Possible Solution
Check for registration problems, I read somewhere in the issues on my way here that you made a custom ore for something, not sure if it was Osmium.
## Workaround 
Search for an Osmium ore vein

## Steps to Reproduce (for bugs)
**we are running a server, but the problem is reproducible in SP**

1. Find an Osmium core Mineral
2. Try to mine it
3. ?
4. sadness (certainly not profit)

## Client Information
* Modpack Version: 3.0.6
* Java Version: 1.8.0_25 64bit
* Launcher Used: Twich
* Memory Allocated: 4 gigs
* Server/LAN/Single Player: Server

## Server Information
* Java Version: 1.8 64bit
* Operating System: No clue tbh, don't think its important
* Hoster/Hosting Soultion: Nitrado
* Sponge (Non-Vanilla Forge) Server?: forge default

**Comment by 3jlowes** [comment]
https://github.com/Darkosto/SevTech-Ages/issues/2008

**Comment by SaculRennorb** [comment]
its not that i cant mine at all with the excavator, limonite for example works just fine, its just osmium

**Comment by SaculRennorb** [comment]
I thought this wasnt a duplicate for the following reasons: 
* Just as a side-note, the /ie mineral get number isn't changing
* the manual doesnt show the cluster, unlike with quarz, wich is mentioned in #2008 

but np if it is ^^
