### ISSUE TITLE
Minor OreDictionary oversight which should work, but doesn't - tin dust from PrimalCore vs Mekanism. Possibly more, general issue.

### ISSUE THREAD

**Issue by EhGneissGuy** [Darkosto/SevTech-Ages#2087]
## Issue / Bug

Grinding tin clusters [Geolosys] in quartz grindstone [AE2] produces tin dust [PrimalCore] which cannot be used with three copper grit [IE] in Alloy Kiln [IE] to create bronze ingot [Mekanism]. Bronze ingot [Mekanism] utilizes tin dust [Mekanism] instead.

## Expected Behavior

I'd expect tin to be tin no matter the mod and to have the same results.

## Possible Solution

I understand that it likely takes some time, but I'd like to see greater compatibility across mod ores. However, I'd be just as satisfied if this difference was justified by saying that a crude grinder produces "Crude Tin Dust" or something like that - maybe a path to refine it with a sifter or mesh. Just some way to distinguish the two dusts meaningfully or make them work the same.

## Steps to Reproduce (for bugs)

1. Grind tin clusters [Geolosys] in quartz grindstone [AE2] 
2. Produces tin dust [PrimalCore] 
3. Grind copper cluster [Geolosys] to produce copper grit [IE]
4. Attempt to combine in Alloy Kiln [IE]

## Context

I was trying to double my ore output at this early stage so that I wouldn't need to mine as much before getting to Ore Excavator or automated methods. Instead of needing three copper ingots and one tin ingot, this method only requires 1.5 copper ingots and .5 tin ingots (3 copper grit [IE] and 1 tin dust [PrimalCore/Mekanism]).

## Client Information

* Modpack Version: 3.0.6
* Java Version: 8.171
* Launcher Used: ATLauncer

* Memory Allocated: 4GB (Default)

* Server/LAN/Single Player: Server
* Resourcepack Enabled?: No
* Optifine Installed?: Yes

## Server Information
* Java Version: N/A
* Operating System: N/A
* Hoster/Hosting Soultion: CubedHost, 4GB, Premium
* Sponge (Non-Vanilla Forge) Server?: N/A

* Additional Content Installed?: No

**Comment by justinrusso** [comment]
The entire goal is to make it so only 1 dust exists, rather than 4 dusts exist and they all just act the same. The issue here is that AE grindstone is currently not cleared and corrected for this.

**Comment by EhGneissGuy** [comment]
justinrusso, I agree.
