### ISSUE TITLE
Astral sorcery cloak flight

### ISSUE THREAD

**Issue by LightsDawn** [Darkosto/SevTech-Ages#2091]
## Issue / Bug

flight does not work

## Expected Behavior

flight equal to elytra

## Steps to Reproduce (for bugs)

1.default server files + MCMA + host sever

## Context

this has forced player to go a different route of flight instead of astral sorcery.

## Logs

* Client/Server Log:
* Crash Log:
nothing popped up in any logs

## Client Information

* Modpack Version:3.0.6
* Java Version:8.171
* Launcher Used:twitch

* Memory Allocated:5600

* Server/LAN/Single Player:server
* Resourcepack Enabled?:no
* Optifine Installed?:yes

## Server Information
* Java Version:8
* Operating System:ubuntu
* Hoster/Hosting Soultion:OVH
* Sponge (Non-Vanilla Forge) Server?:no

* Additional Content Installed?:
ftbutils, laggoggles, worldedit

**Comment by LightsDawn** [comment]
https://imgur.com/CnB69vw

**Comment by LuQ3** [comment]
I have the same problem, and here the view from behind the character's back: https://imgur.com/gQh12lK

**Comment by artdude543** [comment]
This is an AS issue, not a modpack issue. Can you post it over on their tracker, please! Make sure to include versions of the mod and what your imgur links. Also, make sure on the server side that `allow-flight` is enabled. As you could be kicked from the server if it thinks you flying (non-creative)
