### ISSUE TITLE
My Starlight Alter Won't Work

### ISSUE THREAD

**Issue by bobbnu** [Darkosto/SevTech-Ages#2093]
I know this may not be the best place to put this but I also know no other place to put it. I made a 7x7 of Sooty Marble, on the next ring I put 3 marble at each corner and 5 blocks of marble between each corner, I also surrounded each corner with 5 more bricks. At the corner of each "marble corner," I placed a pillar (blocks listed top-down) of Runed Marble, 2 Marble Pillars, and a Chiseled Marble on top. (Please see attached Image.) I also would like to say, this pack is very hard but that makes it fun, you did a good job to prevent lag and other issues, even for my PC, Good Job!
![2018-04-26_16 44 22](https://user-images.githubusercontent.com/38771336/39337793-c71402bc-4973-11e8-9663-62b693e20bc4.png)

**Comment by billybricker** [comment]
Like like the marble in the corners is wrong. Use the chisel to turn it into Astral Sorcery marble and it'll work.

**Comment by artdude543** [comment]
Yeah, the marble is wrong. Also please follow the issue template. Next time it will be auto-closed.
