### ISSUE TITLE
minor issue at stage 1 with slime boots

### ISSUE THREAD

**Issue by croftyraider** [Darkosto/SevTech-Ages#2094]
## Issue / Bug
During game start while wearing slime boots, the *first* load of the word indicates "You dropped the unfamiliar item" (the boots). Looking at my inventory after loading I cannot see my boots, though they do show up when the game shows you armor (off to the right of the other HUD bits and bobs), and as it turns out while checking all this while writing the bug report that if I grab the empty boot slot low and behold there are boots there. If I save&quit and then reload the boots are back without any warnings and no invisibility shenanigans.

I am at stage 1 wearing bronze armor except for the slime boots.

**Comment by justinrusso** [comment]
This is mostly related to https://github.com/Darkosto/SevTech-Ages/issues/1671

Should be fixed in the next update, and more improvements down the road to hopefully prevent this further.
