### ISSUE TITLE
TPS issues: too many eggs and feathers. Possible mod suggestion to add a Killall command

### ISSUE THREAD

**Issue by djcosmic2** [Darkosto/SevTech-Ages#2095]
I seem to be having some tps issues on a server I manage due to chickens dropping an excess of feathers and eggs. Is there a mod already in the pack that can do the COFH killall command so I can implement an item clear routine? If not is there a possible mod that could be added to do so?

**Comment by artdude543** [comment]
You can use the following: `/kill @e[type=Item]` _(Item being the name of thing you want to kill off)_ That's a Vanilla built in command 🙂
