### ISSUE TITLE
Astral Sorcery Sky Wave Resonator now named Fosic Resonator

### ISSUE THREAD

**Issue by MongoTheElder** [Darkosto/SevTech-Ages#210]
In the current version of Astral Sorcery, the Sky Wave Resonator has changed it's name to Fosic Resonator. Also, there is a crafting table recipe that probably needs to be removed.

![2017-11-23_13 56 49](https://user-images.githubusercontent.com/29290246/33186280-4c73c9ca-d056-11e7-8396-bb4a0e1415be.png)

![2017-11-23_13 57 43](https://user-images.githubusercontent.com/29290246/33186282-5005acca-d056-11e7-8624-c23900a56451.png)

This recipe needs to be removed:
![2017-11-23_13 58 24](https://user-images.githubusercontent.com/29290246/33186302-718966e8-d056-11e7-86b8-59eff53fa110.png)

Alpha 8, Twitch build

**Comment by Darkosto** [comment]
Fixed up! Thanks!
