### ISSUE TITLE
Exception in server tick loop on singleplayer

### ISSUE THREAD

**Issue by Undren** [Darkosto/SevTech-Ages#2100]
## Issue / Bug
Every time I load a world it crashes at loading terrain.
[Crash video.zip](https://github.com/Darkosto/SevTech-Ages/files/1954376/Crash.video.zip)

## Expected Behavior
Instead of loading up properly, it just crashes.

## Steps to Reproduce (for bugs)
I really don't know what happened to cause it. I just got the Well of Suffering running and a few minutes later my game crashed.

## Context
I was working in Blood Magic and grabbed a mob spawner, used an agitator on it, then put it under a Well of Suffering. It crashed a few minutes after and won't load now.

## Logs

* Crash Log: https://pastebin.com/JudBXskc

## Client Information
* Modpack Version: This was a fresh install of 3.0.6, as I read that reinstalling might fix the tick loop.
* Java Version: jre1.8.0_161
* Launcher Used: Twitch Launcher

* Memory Allocated: 6GB

**Comment by Dutchs** [comment]
#1841
