### ISSUE TITLE
Server Crashing when exploring Galaticraft Planets

### ISSUE THREAD

**Issue by Tidalsniper** [Darkosto/SevTech-Ages#2102]
## Issue / Bug
Whenever anyone on my server does exploration on GC planets the server crashes

## Expected Behavior
For the server not to crash

## Possible Solution
no idea

## Steps to Reproduce (for bugs)
1.Land on a Planet
2.Start Exploring
3.Crash after loading new chuncks

## Context
The issue has made it extremely challenging to do anything on GC Planets due the constant crashing

## Logs
* Client/Server Log:
* Crash Log: https://pastebin.com/GzfG6UJy

## Client Information
* Modpack Version:3.0.6
* Java Version: 
* Launcher Used: Twitch
* Memory Allocated: 8GB
* Server/LAN/Single Player: Server
* Resourcepack Enabled?: no
* Optifine Installed?: no

## Server Information
* Java Version: V8 update 161
* Operating System: Win 10
* Hoster/Hosting Soultion: n/a
* Sponge (Non-Vanilla Forge) Server?:

Log:
[2018-04-27-4.log.gz](https://github.com/Darkosto/SevTech-Ages/files/1954592/2018-04-27-4.log.gz)

* Additional Content Installed?:no

**Comment by artdude543** [comment]
This is fixed in 3.0.7 (with an update to AS)
