### ISSUE TITLE
Sevtech Ages 3.0.6 install.bat

### ISSUE THREAD

**Issue by KatharineRosewood** [Darkosto/SevTech-Ages#2103]
whenever i click on install.bat it opens, creates the minecraft_server.jar and after a while it closes and deletes that jar again. The forge universal jar file is never created.

**Comment by artdude543** [comment]
The `Install.bat/sh` runs the forge installer to download the Minecraft jar/libs and forge server jar. If any of the connections to the servers failed it will exit. This is intended behavior of the installer. 

The fact the jar is "deleting" as you say this is not an issue with the scripts but your setup. We don't delete anything nor does the installer. Please check you don't have any AV false triggering with files. But you still have issues open a support thread on the Forge Forums as this goes over as an installer issue which we don't control.
