### ISSUE TITLE
Enchancement (Mekanism Generators) Age 5 (missing mod mechanics)

### ISSUE THREAD

**Issue by gbattleson** [Darkosto/SevTech-Ages#2104]
Mekanism has split into multiple mod's and while the main core is installed in Sevtech, the Mekanism Generators portion is missing.

[https://minecraft.curseforge.com/projects/mekanism-generators](url)

Specifically I can make all the fuels required to run and start a reactor, Brine, Heavy Water, Lithium Dutirium, Tritium, D-T fuel. They are located in JEI along with the machines
But the blocks to create the reactor are located within the Mekanism Generators mod. This means that even in Age 5 where I can make creative items I still can't make a reactor.

## Possible Solution
Install Mekanism Generators mod to fix the missing components.

## Context
I can make the system to create reactor fuel and started powering a laser to jumpstart the reactor but the blocks to make the reactor do not exist. 

Unknown if this was intended or if the separation of Mekanism into multiple mods means it was accidentally left out.

## Client Information
3.0.6

**Comment by justinrusso** [comment]
The generators mod was intentionally left out. Will investigate removing items/recipes as needed.

**Comment by SOL3675** [comment]
I need some lithium dust for making Induction Matrix, but Thermal Evaporation Tower does not work with Advanced Solar Panels from Mekanism Generators.
If you won't add Mekanism Generators, we need some other recipes for induction cells and providers.

**Comment by gbattleson** [comment]
@SOL3675 I believe the advanced solar panels do work with the Thermal Evaporation tower, you just need to make sure they are on the corner of the tower and have blocks beside them. The advanced solar panels can't sit on top of the thermal evaporation tower they must sit inside the structure.

**Comment by kpress15** [comment]
I also have an issue with this. The problem is not that advanced solar panels don't work, it's the fact that they're not in the pack entirely... Due to the fact that the mekanism generators mod was left out.

**Comment by SOL3675** [comment]
@gbattleson @kpress15 Thank you for your information. I didn't know about it can form multiblock without solar. Placing Thermal evaporation block on top corners and it works.

**Comment by artdude543** [comment]
This mod is not required for the modpack. As we have other mods which add missing components/tools which the latter did. Heaters replace the need for the solar on the brine tower.
