### ISSUE TITLE
Cyclic Shearing Block breaking the need for modular machines for wool by making sheep drop wool blocks.

### ISSUE THREAD

**Issue by SystemCollapse** [Darkosto/SevTech-Ages#2106]
## Issue / Bug
See title.

## Expected Behavior
Not to drop blocks of wool.

## Possible Solution
Remove the shearing block or make it age 6.

## Steps to Reproduce (for bugs)
Wake up,
Make a coffee,
Log in,
Make a shearing block,
Make your sheep minions touch the side of the block,
Profit?

## Context
I am both disgusted and aroused by this blocks behavior.

## Logs
Are still made of wood.

**Comment by artdude543** [comment]
Fixed in https://github.com/Darkosto/SevTechAgesConfigs/commit/121c4a73f12b1a2570cd5fbe692e1191f20b9551
