### ISSUE TITLE
BC Pipes with Hopping Bonsai Pot

### ISSUE THREAD

**Issue by nicolas2701** [Darkosto/SevTech-Ages#2108]
## Issue / Bug
Server crash after placing a BC Item Transport Pipe below a Hopping Bonsai Pot from the mod Bonsai Trees. Repeated crashing of the server after starting.

## Expected Behavior
No Crash

## Possible Solution
MCEdit the pipe out of the world.

## Steps to Reproduce (for bugs)

1. Hopping Bonsai Pot
2. Place a Stone pipe below the Pot to extract

## Logs

* Client/Server Log: https://pastebin.com/Etk27U7e
* Crash Log: https://pastebin.com/Qw3QXWyA

## Client Information

* Modpack Version: 3.0.6
* Java Version: 1.8.0_161-b12
* Launcher Used: ATL

* Memory Allocated: Server: 16G

* Server/LAN/Single Player: Server
* Resourcepack Enabled?: No
* Optifine Installed?: Yes

## Server Information
* Java Version: 1.8.0_161-b12
* Operating System: Window Server 2016 Standard
* Hoster/Hosting Soultion: Private
* Sponge (Non-Vanilla Forge) Server?: Vanilla Forge

* Additional Content Installed?: No

**Comment by Dutchs** [comment]
#1846

**Comment by nicolas2701** [comment]
Sorry didn't find the post
