### ISSUE TITLE
Crash Loop while using Blood Magic's Sigil of the phantom bridge

### ISSUE THREAD

**Issue by pulseUK** [Darkosto/SevTech-Ages#2109]
## Issue / Bug
Activated the sigil of the phantom bridge while in sigil of holding walked a few steps then my game crashed, ever since I'm in a crash loop that I cannot fix, because as soon as the game loads it crashes immediately.

## Expected Behavior
phantom bridge sigil works without crashing the game (lol)

## Possible Solution
the visuals of the sigil did clip into my immersive engineering distiller, so maybe the crash is caused by that interaction.
# Steps to Reproduce (for bugs)
activate the sigil of the phantom bridge while it is in a sigil of holding and walk next to a immersive engineering distiller.

## Context
I cannot play my world at all

## Logs

* Client/Server Log:
* Crash Log: https://pastebin.com/4KhPwnrQ

## Client Information

* Modpack Version: 3.0.6
* Java Version: version 8 update 171
* Launcher Used: twitch app

* Memory Allocated: 10Gb

* Server/LAN/Single Player: N/A
* Resourcepack Enabled?: N/A
* Optifine Installed?: N/A
[crash-2018-04-27_18.16.54-server.txt](https://github.com/Darkosto/SevTech-Ages/files/1956009/crash-2018-04-27_18.16.54-server.txt)

**Comment by artdude543** [comment]
This _should_ be fixed in 3.0.7 if not please re-report.
