### ISSUE TITLE
I can't make a hopper???

### ISSUE THREAD

**Issue by Jocke06** [Darkosto/SevTech-Ages#2111]
## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:

* Memory Allocated:

* Server/LAN/Single Player:
* Resourcepack Enabled?:
* Optifine Installed?:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Soultion:
* Sponge (Non-Vanilla Forge) Server?:

* Additional Content Installed?:

**Comment by Hillgrove** [comment]
seeing how you managed to completely fail to read how to create this issue, I'm not sure it's a problem with the modpack, but more a personal one.

**Comment by DerpityDoo** [comment]
Not to hate on the younguns among us, but just look at the "06" in his name and you probably know all you need to know

**Comment by vadis365** [comment]
Good grief. I would close this - but I want it left as an example of how not to report issues.

**Comment by artdude543** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

Thanks again for reporting, and we hope you enjoy the pack!
