### ISSUE TITLE
Game Tip: Mornay Sauce

### ISSUE THREAD

**Issue by MostImpressive** [Darkosto/SevTech-Ages#2116]
## Issue / Bug
In the game tip recipe for mornay sauce, it instructs you to remove the sachet after adding the roux and cheese.

## Expected Behavior
The sachet would have extracted all of its flavor during the scalding of the milk.

## Possible Solution
Reorder the steps, reflecting the removal of the sachet during the scalding of the milk, OR lengthen the time of heating the milk by instructing to steep the milk instead of scald.

## Steps to Reproduce (for bugs)
1. Try to remove a sachet from a pot of sticky cheese sauce without busting it open or losing a bunch of sauce unnecessarily. 

## Context
No effect to me; I just like to teach people how to cook.

Hope all is well! Love the pack! Thanks for your hard work!

**Comment by Darkosto** [comment]
Changed to 

"Morney cheese sauce (makes 1 gal); 2qt whole milk; 2 qts heavy cream; roux (250g butter/250g flour); sachet (bay, peppercorns, thyme); dijon (to taste); shredded comte cheese (lots/to taste); bring milk/cream/sachet to a boil (remove sachet) then reduce heat to simmer add roux (should be blonde) and whisk until absorbed add dijon and shredded cheese to taste" 

Does that work better? :)
