### ISSUE TITLE
Crash while starting the modpack

### ISSUE THREAD

**Issue by Gambino0113** [Darkosto/SevTech-Ages#2117]
I have tried many ways people have said and my problem is still occurring, it is loading 2/7 and once it finishes the mods it crashes
Im using 6,144mb of ram, and i am on the twitch browser.
steps to recreate
1. hit play on old jar launcher
crash report
[crash-2018-04-27_21.27.51-client.txt](https://github.com/Darkosto/SevTech-Ages/files/1957142/crash-2018-04-27_21.27.51-client.txt)

**Comment by artdude543** [comment]
You need to re-install the pack and try again. You're somehow missing the Code Chicken Lib mods which are **needed** this is a client issue and nothing to do with the modpack. Either your doing something weird with the install or something is deleting mods. Like an AV or Malware scanners.
