### ISSUE TITLE
Modular machinery doesn't require blueprint

### ISSUE THREAD

**Issue by AquaXV** [Darkosto/SevTech-Ages#2121]
## Issue / Bug
Modular machinery machines do not need a blueprint to function. You can craft the structure of the machine and it will be recognized as valid and work without blueprint
![image](https://user-images.githubusercontent.com/1627290/39395024-47daa750-4ad9-11e8-8e6f-33859628a029.png)

## Expected Behavior
I would expect the machine to require the blueprint to function.

## Possible Solution
N/A

## Steps to Reproduce (for bugs)
1. Craft Modular machine (any machine)
2. Put in items to process

## Context
The item is called blueprint, so I would not expect it to be required for the machine to operate correctly, but the machine has a slot for it which (in my opinion) indicates it is required.

## Logs
N/A

## Client Information
* Modpack Version: 3.0.6
* Java Version: 1.8.0_162
* Launcher Used: Curse Jar launcher
* Memory Allocated: 6G
* Server/LAN/Single Player: Server
* Resourcepack Enabled?: No
* Optifine Installed?: Yes (N/A)

## Server Information
* Java Version: 
openjdk version "1.8.0_161"
OpenJDK Runtime Environment (build 1.8.0_161-b14)
OpenJDK 64-Bit Server VM (build 25.161-b14, mixed mode)
* Operating System: 
Linux CentOS-73-64-minimal 3.10.0-514.26.1.el7.x86_64 # 1 SMP Thu Jun 29 16:05:25 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux 
* Hoster/Hosting Soultion: Dedicated server of a friend (Not from a hosting company)
* Sponge (Non-Vanilla Forge) Server?: No
* Additional Content Installed?: No

**Comment by AquaXV** [comment]
After posting I noticed the server information section linked to issue1, this was not intended.

**Comment by Rixxaw** [comment]
Some of the modular machines like the Mixer and Industrial Dryer can be upgraded by just changing the corner blocks.  I assume it is intended that you would be able to do this without having to also make a new blue print.  I prefer the way it currently works.

**Comment by artdude543** [comment]
This is the intention of the mod to allow storage of the blueprint so you can "keep" it when you need to move it if you forget how to build the machine and/or when machines are similar in structure and you need to use the print to define what machine is that you want to have. It's like an override for the structure.
