### ISSUE TITLE
Dying in Twilight Forest Swamp Maze leads to respawning without death compass, but with first inventory slot and armor equiped.

### ISSUE THREAD

**Issue by EhGneissGuy** [Darkosto/SevTech-Ages#2126]
## Issue / Bug
Dying in a Twilight Forest swamp maze resulted in respawning with the first item equipped on hotbar (Tinkers Pickaxe), armor (Hydra Set, Slime Boots), and nothing else - no death compass. Died to TNT explosion, cannot reproduce through other means.

## Expected Behavior

Respawn with TMG death compass and nothing else.

## Possible Solution

Not sure.

## Steps to Reproduce (for bugs)

1. Die to TNT trap in swamp maze.
2. Respawn.

## Context

Unable to find grave, ended up using /tmg_restore to get it back.
## Logs

* Client/Server Log: N/A
* Crash Log: N/A

## Client Information

* Modpack Version: 3.0.6
* Java Version: 8.171
* Launcher Used: ATLauncher

* Memory Allocated: 4GB

* Server/LAN/Single Player: Server
* Resourcepack Enabled?: No
* Optifine Installed?: Yes

## Server Information
* Java Version: N/A
* Operating System: N/A
* Hoster/Hosting Soultion: CubedHost, 4GB, Premium
* Sponge (Non-Vanilla Forge) Server?: N/A

* Additional Content Installed?: No

**Comment by lordtrickster** [comment]
Probably had a Charm of Keeping on you when you died.  Disrupts the death compass mechanism.

**Comment by EhGneissGuy** [comment]
That's probably it. Thanks.
