### ISSUE TITLE
Mekanism's precision Sawmill gives chopping blocks instead of planks.

### ISSUE THREAD

**Issue by CapitainV** [Darkosto/SevTech-Ages#2127]
## Issue / Bug
Mekanism's precision sawmill gives Chopping blocks from Horse power mod.

## Expected Behavior
It should give planks from the according wood logs.

## Possible Solution
Change the output

## Context
I'm trying to automate wooden planks production Via the precision Sawmill.

## Client Information
* Modpack Version: 3.0.6
* Java Version: 1.8.0.161 ( 64 bits)
* Launcher Used: Twitch launcher
* Memory Allocated: 8.192 MB
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by artdude543** [comment]
Fixed in 3.0.7
