### ISSUE TITLE
trouble finding shadow lands.

### ISSUE THREAD

**Issue by Wipperwill** [Darkosto/SevTech-Ages#2128]
Are the shadowlands always visible? Or do they just come into being after you unlock them in the quest books? 

I have a lot of trouble finding them in my games.  Villages too.  I made a bunch of different worlds and looked around for shadowlands and can never find them. Those are two show stoppers for progression.

**Comment by artdude543** [comment]
RNG Issue you can find information here: https://borg286.github.io/sevtech/
