### ISSUE TITLE
strainer base unable to place in river

### ISSUE THREAD

**Issue by Wipperwill** [Darkosto/SevTech-Ages#2130]
## Issue / Bug
Trying to place a strainer base in a river but it wont go lower  than 1 block. This means the survivalists strainer (dense) is sticking in the air. no good

## Expected Behavior
Being able to place the strainer base 2 blocks down.

## Possible Solution
 
?

## Steps to Reproduce (for bugs)

1. Find river biome that flows
2. Attempt to put down base

## Context
Unable to get the strainer to work.
I think its something to do with the flowing water, which is silly because a strainer should NEED flowing water.  I placed it in a different Biome and it worked fine, 2 squares below the surface for base, 1 for the strainer

## Logs
NA

## Client Information

* Modpack Version: 3.0.6 (newest)
* Java Version:1.8.0_161-b12
* Launcher Used: Twitch (10 GB)

**Comment by deltadstroyer** [comment]
Somewhat Solution:
Dig a hole next to the river you want it placed at, so the water flows in this hole. place the strainer here.
Its a roundabout way, but it works.
![2018-04-29_16 22 25](https://user-images.githubusercontent.com/38836647/39407671-c8fd1c28-4bc9-11e8-9029-825f782d3de5.png)

**Comment by Wipperwill** [comment]
Thank you

**Comment by artdude543** [comment]
The issue is not an issue and is. It's basically caused by the changes we do to water and biomes. As the water is technically not a "source" in some cases. But the solution mentioned is the one we generally tell people.
