### ISSUE TITLE
Game Crash When Loading World

### ISSUE THREAD

**Issue by kpress15** [Darkosto/SevTech-Ages#2133]
# Issue / Bug
The game crashes on world load.

**Expected Behavior**
Not to crash.

**Possible Solution**
Not a clue.

# Steps to Reproduce (for bugs)
Just start up game and select my single player world.

# Context
Everything was working fine and I went to open my "me crafting terminal" and my game crashed. Tried to open a few times now and the game just crashes after loading world. I have used the terminal many times before without crashes.
*note* I have tried different things from other issue posts about world crashing but none have worked. Also, I do not have a single idea what the crash logs mean to attempt to fixes.

# Logs
https://pastebin.com/WCYDbmsF - the initial crash
https://pastebin.com/diV604An - crash of every time since (don't know if different)
https://pastebin.com/AvucgBGG (hs_err)

# Client Information

Modpack Version: 3.0.6
Java Version: 1.8.0_171 (64 Bit) (updated after a few crashes to see if it would work)
Launcher Used: Jar Launcher
Memory Allocated: 6.1 GB
Server/LAN/Single Player: Single Player
Resourcepack Enabled?: none
Optifine Installed?: yes

**Comment by Fatthunder** [comment]
Do you have any Spawner agitators active?

at me.desht.pneumaticcraft.common.semiblock.SemiBlockSpawnerAgitator.update(SemiBlockSpawnerAgitator.java:50)

Looks like that might be causing issues if you do.

**Comment by kpress15** [comment]
I do actually. Sorry I'm a super noob. How would I be able to deactivate that or delete it from my world?

**Comment by Fatthunder** [comment]
Would need to open your world in MCEdit or something similar and go to where it is located and then select and delete it. Make sure to BACKUP your world before making any changes though

**Comment by artdude543** [comment]
You can either do that or wait for the next update. 3.0.7
