### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by baeganxo** [Darkosto/SevTech-Ages#2136]
Server will not start and I can't seem to find anything on how to fix the issue. 

Here is the log: https://pastebin.com/asY80Bu1

Thanks in advance.

**Comment by Fatthunder** [comment]
Did you accept the EULA?

**Comment by artdude543** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

Thanks again for reporting, and we hope you enjoy the pack!
