### ISSUE TITLE
Seemingly random crashes (I solved it myself)

### ISSUE THREAD

**Issue by Confluxes** [Darkosto/SevTech-Ages#2138]
## Issue / Bug
My game will just crash randomly if I ever go away from my base and once I load back in if I don't go back in the direction of my base it will just crash again for seemingly no reason

Edit: Scanning through the crash logs seems it doesn't have to do with where I am and seems may be my oil set up and/or the BC fluid pipes so I'm actively working on figuring it out

Edit 2: Yeah I figured it out it's when you pump water with buildcraft pipes into the boiler from Immersive engineering tho not sure why it's happening now because I've been running the boiler all night like that and it's been fine but that's definitely the issue  

## Expected Behavior
Game closes instead of not crashing like it should be

## Possible Solution
 1. No idea honestly 
## Steps to Reproduce (for bugs)

1. pump water with buidcraft pipes into an Immersive Engineering boiler for a few hours apparently.
2.

## Context
I'd imagine it's rather obvious how this problem affects me 

## Logs

* Client/Server Log:
* Crash Log: https://pastebin.com/1guDChh1

## Client Information

* Modpack Version: 3.0.6
* Java Version: 8
* Launcher Used: Twitch

* Memory Allocated: 9.5GBs

* Server/LAN/Single Player: Singleplayer
* Resourcepack Enabled?: No
* Optifine Installed?: Have tried with and without

**Comment by vadis365** [comment]
We can't do anything without the information to act on.
If there are no log files then it doesn't happen in basic terms.

**Comment by Confluxes** [comment]
Where would I find those?

**Comment by Confluxes** [comment]
So I'm an idiot and i found the crash report 
https://pastebin.com/1guDChh1

**Comment by artdude543** [comment]
This crash is fixed in 3.0.7
