### ISSUE TITLE
Tinker's construct bug?

### ISSUE THREAD

**Issue by lliinnkk10** [Darkosto/SevTech-Ages#2139]
## Issue / Bug
The issue I'm having is that the tool forge says there is a crossbow and bolts. However when I tried to make the bolt, I noticed that there is no patterns for the bolt core. I made a new world and gave myself all advancements and still nothing. Is it disabled or have I messed up somehow?

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 3.0.6
* Java Version: 1.8.0_161
* Launcher Used: Twitch

* Memory Allocated: 6144 MB

* Server/LAN/Single Player: Single
* Resourcepack Enabled?: Yes, Faithful
* Optifine Installed?: No

**Comment by Ozzymud** [comment]
Use an arrow shaft, pour metal over it. The how to is written about in the tinkers book.

**Comment by artdude543** [comment]
Fixed in 3.0.7
