### ISSUE TITLE
Storage Drawers Storage 1 Upgrade default recipe not removed

### ISSUE THREAD

**Issue by justinrusso** [Darkosto/SevTech-Ages#214]
Initial recipe for Storage Drawers' Stage 1 Upgrade has both the default recipe and the one created with crafttweaker. Is this intended?

![image](https://user-images.githubusercontent.com/25138621/33230446-6da7fc18-d1b1-11e7-8c8f-0090d6220052.png)

**Comment by Darkosto** [comment]
Fixed!
