### ISSUE TITLE
Darklands where art Thou

### ISSUE THREAD

**Issue by Wipperwill** [Darkosto/SevTech-Ages#2142]
## Issue / Bug
Darklands spawn

## Expected Behavior
Find some darklands

## Context
Hard to progress

I've been trying to play this mod for a while, but after a couple of starts, I've noticed darklands missing from all my playthroughs. I made 3 different games, went into creative and flew in all directions but found 0 darklands. I'm talking flying for 2 days in each direction. I see shoggoth lairs and villages but no deserts or darklands. Someone told me to go  north for darklands and south for deserts, but I havent seen either. I did have one very good start with darklands, swamp, shoggs, and a village close-by but I restarted for some reason, not realizing how lucky that was.

Is there any setting to world-gen that would make it more likely for darklands to spawn? I" dont have infinite time to get halfway through Age 0 before realizing there are no darklands close by.

Tanks in advance, i hope it doesnt sound like I'm whining. I really like this mod.

**Comment by djnifos** [comment]
Flying endlessly in a cardinal direction isn't the best way to find the darklands.  You want to head north or south until you find cold biomes, and then travel east or west to find them.  This advice is only applicable with default gen in 3.0.6 or higher.

**Comment by artdude543** [comment]
RNG issue you can follow this to help you https://borg286.github.io/sevtech/#climate
