### ISSUE TITLE
After going through any portal exp is temporarily at 0

### ISSUE THREAD

**Issue by MrGundum** [Darkosto/SevTech-Ages#2143]
## Issue / Bug

Anytime anyone on my server goes through a dimension the the game considers them to have 0  xp
until they relog or gain xp and it will then  'catch up', until they do that they can not do anything that requires xp.

## Expected Behavior

for this not to happen

## Possible Solution

gaining xp or relogging fixes issue.

## Steps to Reproduce (for bugs)

1.Have levels
2.go through dimension
3. exp bar is now at 0

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 3.0.6
* Java Version:1.8..0.161
* Launcher Used:Twitch

* Memory Allocated: 10GB

* Server/LAN/Single Player:Server
* Resourcepack Enabled?:No
* Optifine Installed?:Yes

## Server Information
* Java Version: 1.8.1.0.161
* Operating System:Windows 10
* Hoster/Hosting Soultion:  Own Pc
* Sponge (Non-Vanilla Forge) Server?:?

* Additional Content Installed?:

**Comment by vadis365** [comment]
Hello,
This is a bug that has been around in MC for as long as I can remember - I don't think there is anything we can do to fix this. As long as your levels remain it's not really an issue for the pack to solve, and topping up your xp will reveal the number gain.
Cheers,
Me.
