### ISSUE TITLE
Server crashes (killed) at the end of loading

### ISSUE THREAD

**Issue by Attila1337** [Darkosto/SevTech-Ages#2145]
No other mods installed. Multiple times reinstalled. (root and new user)

 Already tried
I searched for it. But I havent found something like that
 Also tried
 Also tried
Also tried
 
## Issue / Bug
 
The server starts normal. At the end I can see ingame that the server is close to have finished starting (Ingame the server is online but "old") But it's getting killed at the very end. Screenshot uploaded on lightshot: http://prntscr.com/jborv3
This happens only on my debian server. On my windows 10 PC, the server works...

latest log: https://pastebin.com/JHCXs2rp

Screenshot uploaded on lightshot: http://prntscr.com/jborv3

## Possible Solution
 The error depends on the OS, because on my windows PC it works great and on my debian server it's getting killed. (On both systems is Java 8 installed)

## Logs
https://pastebin.com/JHCXs2rp

## Client Information

* Modpack Version: The newest that was currently avaible (29. April 2018)
* Java Version: java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)

* Memory Allocated: 4096m

* Server/LAN/Single Player: Server
* Resourcepack Enabled?: No
* Optifine Installed?: No

## Server Information
* Java Version: java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)
* Operating System: Debian 8 - 64 Bit (Open VZ)
* Hoster/Hosting Soultion: deinserverhost.de/
* Sponge (Non-Vanilla Forge) Server?: Normal server pack

* Additional Content Installed?:

**Comment by artdude543** [comment]
I need the logs, not screenshots.

**Comment by artdude543** [comment]
This seems like a host issue either with RAM or Memory. The pack is massive when running in terms of memory overhead and storage space. Is the host your using got enough resources for the server? I.E. Your package capable of running it?

I only say this as your stating the works fine on your Windows machine. So this is the server hosts fault, not the packs.

**Comment by Attila1337** [comment]
How much Ram do I need for it? I have 6gb on my server. I think this should be enough

**Comment by artdude543** [comment]
6bg is plenty. But you already stated.

>  windows PC it works great and on my debian server it's getting killed. 

So this is an issue with your server and not the pack. We don't offer server install/support. For the complexity of what could be causing issues.
