### ISSUE TITLE
Cannot figure out how to get Redstone Ore Block

### ISSUE THREAD

**Issue by Pyrothunder** [Darkosto/SevTech-Ages#2146]
So we accidentally set off the carminite reactor in the Ur-Ghast tower and broke it so we can't pick it up. You can make a new one with a redstone ore block but you need a silktouch pickaxe for that. As far as Tinker's says i can't access silktouch until Age 3 so i'm very confused as to how I make the coal engine to advance! Any help would be greatly appreciated!

**Comment by DenisMasterHerobrine** [comment]
You have 2 ways.
First way: You can go far away and look for a new Ur-Ghast dungeon and loot it with a new carminite reactor.
Second Way: Go to Astral Sorcery, learn Bootes and get a Stellar Refraction Table and enchant a book with Bootes and get Silk Touch. Then, enchant it in Anvil (Minecraft) and get a Redstone Ore near the Hydra (or where you can find it).

**Comment by Pyrothunder** [comment]
Forgive me, I'm new to Astral Sorcery but how do I get the Bootes Constellation?

**Comment by DenisMasterHerobrine** [comment]
Open an Astral Tome, you can find all information about this mod in-game.
There's some info from wiki, if you interested:
To discover constellations, the appropriate Constellation paper must be acquired by the player first; this will display the constellation's image in the "Constellations" tab in the player's Astral Tome. Then, they must be discovered by looking through a Looking Glass or Telescope at night—the former is limited to only seeing bright constellations. Using the paper as a reference the player must trace the constellation out on either device using the mouse. Once a constellation has been discovered it will permanently be displayed in the night sky when it is in view and extra information is added to the "Constellations" tab in the Tome.
Source: https://ftb.gamepedia.com/Constellations

**Comment by artdude543** [comment]
This is not a pack issue as there are methods in the stages to get Ore. Following AS is your route to get Ore :)

Otherwise, this issue is closable but feel free to continue talking to each other about how to do what.
