### ISSUE TITLE
No recipe for the Starmetal Ore

### ISSUE THREAD

**Issue by CapitainV** [Darkosto/SevTech-Ages#2148]
## Issue / Bug
The recipe for the Starmetal Ore isn't showing up in JEI anymore. 

## Expected Behavior
The recipe for Starmetal Ore Should show up in JEI (when clicking the starmetal Ore)

## Steps to Reproduce (for bugs)
Be in age 5 and craft the Iridescent Altar
Recipe isn't showing up anymore.
## Context
trying to craft the starmetal ingot to make the mantle of stars.

## Client Information

* Modpack Version: 3.0.6
* Java Version: 1.8.0.161
* Launcher Used: Twitch Launcher
* Memory Allocated: 8.192 Mb
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by Legatonin** [comment]
sometimes, as for me, when there are no items or recipes showing in JEI, i just restart the pack. It happened some of the times for me... but I suggest you can try that.

**Comment by artdude543** [comment]
Yeah, recipes derping out require a pack restart. We also enabled some other methods for the ore in the next update. But in general and recipes start vanishing it's time to restart the pack.
