### ISSUE TITLE
Internal Server Crash (repost cuz there was no reply)

### ISSUE THREAD

**Issue by Legatonin** [Darkosto/SevTech-Ages#2149]
## Issue / Bug
Every time i load in the world or go through dimension to dimension. It keeps on crashing and goes to the multiplayer screen.

## Expected Behavior
As what the issue does, i load in the world and it crashes. The same goes whenever i go through portals, it crashes as I get into the dimension.

## Possible Solution
That I do not know.

## Steps to Reproduce (for bugs)

1.Load in the world
2.Wait for a few seconds
3.Crashes
![screenshot_65](https://user-images.githubusercontent.com/28191018/39260400-f697dabe-48eb-11e8-8297-dc14616f97bc.png)

## Context
It's very annoying, especially when I'm recording for a video.

## Logs

* Client/Server Log:
* Crash Log: https://gist.github.com/Legatonin/a6c4619ed05cc6c2ae871178333774ea
Here should be the latest crash log i have in my folder.

## Client Information

* Modpack Version: Latest
* Java Version: jre1.8.0_161
* Launcher Used: Twitch

* Memory Allocated: 7680MB in Twitch Launcher settings

* Server/LAN/Single Player: single
* Resourcepack Enabled?: Cubic
* Optifine Installed?: yes

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Soultion:
* Sponge (Non-Vanilla Forge) Server?:

* Additional Content Installed?:

**Comment by artdude543** [comment]
You was replied too as it's fixed already in the upcoming update... stop re-posting
