### ISSUE TITLE
Server crashed after placing a spawner agitator

### ISSUE THREAD

**Issue by Mattzebue** [Darkosto/SevTech-Ages#2151]
After placing a spawner agitator on a Spawner, the server crashed and keeps crashing on restart.

[crash-2018-04-29_22.14.11-server.txt](https://github.com/Darkosto/SevTech-Ages/files/1959196/crash-2018-04-29_22.14.11-server.txt)

Pack Version is 3.0.6
Windows 10
Java version "1.8.0_172"

**Comment by artdude543** [comment]
Fixed in 3.0.7.

Also, check for other issues beforehand it will save you and my life time.
