### ISSUE TITLE
Server Not working.. Crashes when I die, or just crashes randomly.

### ISSUE THREAD

**Issue by dazahwow** [Darkosto/SevTech-Ages#2152]
Hello,

It seems that I have this issue. I have updated all my java, I have allocated 4096gb of ram, and also for the sever, for 64 bit I have enabled 4G, and Still I am having this issue with the server, very confused, Thanks.
[debug.log](https://github.com/Darkosto/SevTech-Ages/files/1959214/debug.log)

[29/4/2018 13:44:51 PM] [main/INFO] [foamfix]: This may be due to a world leak, or there is little memory pressure.
[29/4/2018 13:44:51 PM] [main/INFO] [foamfix]: Use the relevant FoamFix options to adjust the wait time.

Thanks,

Jacob

**Comment by dazahwow** [comment]
Debug Log: https://pastebin.com/HUzXySS1

**Comment by artdude543** [comment]
4GB is not enough for this pack bare min is 6GB. World leaking bugs are common in large modpacks and can be ignored for the most part. 

Servers "randomly" crashing as 9/10 ran out of memory. And if you crashed you would have supplied the relevant crash report as instructed on the template. But you did not so. Based on that this seems like a memory allocation issue based on the limited data.
