### ISSUE TITLE
trying to start server on linux-unable to access jarfile error

### ISSUE THREAD

**Issue by derpinirish** [Darkosto/SevTech-Ages#2154]
## Issue / Bug
I am unable to start a minecraft server on linux ubuntu... It is giving me a unable to access jar file error log is below....

mikey@Work-gaming-pc:~$ '/home/mikey/Desktop/Atlauncher-2018/Servers/SevTechAges_306/LaunchServer.sh' 
Error: Unable to access jarfile forge-1.12.2-14.23.2.2654-universal.jar
mikey@Work-gaming-pc:~$ '/home/mikey/Desktop/Atlauncher-2018/Servers/SevTechAges_306/LaunchServer.sh' 
Error: Unable to access jarfile /home/mikey/Desktop/Atlauncher-2018/Servers/Sevtechages_306/forge-1.12.2-14.23.2.2654-universal.jar
mikey@Work-gaming-pc:~$ '/home/mikey/Desktop/Atlauncher-2018/Servers/SevTechAges_306/LaunchServer.sh' 
Error: Unable to access jarfile /home/mikey/Desktop/Atlauncher-2018/Servers/Sevtechages_306/forge-1.12.2-14.23.2.2654-universal.jar
mikey@Work-gaming-pc:~$ '/home/mikey/Desktop/Atlauncher-2018/Servers/SevTechAges_306/LaunchServer.sh' 
Error: Unable to access jarfile /home/mikey/Desktop/Atlauncher-2018/Servers/Sevtechages_306/forge-1.12.2-14.23.2.2654-universal.jar

This is what I did any solutions to this?

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:

* Memory Allocated:

* Server/LAN/Single Player:
* Resourcepack Enabled?:
* Optifine Installed?:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Soultion:
* Sponge (Non-Vanilla Forge) Server?:

* Additional Content Installed?:

**Comment by artdude543** [comment]
So clearly you can't read `forge-1.12.2-14.23.2.2654-universal.jar` can't find pretty self-explanatory if you tell me. Also, don't use the servers ATLauncher builds we don't test them at all. And more people report bugs from when using them...

Visit CurseForge and download the server files from the latest version of the pack and follow the README this is a built server file by us and after tested to ensure they fine out of the box. (When you run the Install scripts)
