### ISSUE TITLE
Crafting the Biomaelyzer for What's My Biome in Stage 2 grants credit for Speedrunner

### ISSUE THREAD

**Issue by MongoTheElder** [Darkosto/SevTech-Ages#216]
Crafting the Biomealyzer grants both "What's My Biome" and "Speedrunner" advancements in Stage 2 even though I have not crafted the Stopwatch

Alpha 8, Twitch build

**Comment by justinrusso** [comment]
Could this be similar to the issue in #124?

**Comment by MongoTheElder** [comment]
The Biomealyzer criteria is:
`criteria.setItem("infoaccessories:info_accessory", 6)`
and the Stopwatch criteria is:
`criteria.setItem("infoaccessories:info_accessory")`

Is not having metadata specified for the Stopwatch one being treated as a wildcard and accepting the Biomealyzer?
