### ISSUE TITLE
Rock Crystals still hidden in twilight forest even in age 4

### ISSUE THREAD

**Issue by Geilolo** [Darkosto/SevTech-Ages#2161]
## Issue / Bug

I'm in Age 4 and I was looking for rock crystals in the twilight forest. I found at least 3 different chunks with samples but with **no ore** below. I found some water pockets (hidden rock crystal ores?), 
I hope someone can reproduce this.

## Expected Behavior

Should find ore.

 ## Steps to Reproduce (for bugs)  

I'll try to reproduce in a new world if I get the time.

## Client Information

* Modpack Version: 3.0.6.
* Java Version: 1.8.0.161
* Launcher Used: Twitch

* Memory Allocated: 8Gigs

**Comment by artdude543** [comment]
This is a rare issue when you unlock new stages. Re-launch the entire pack and/or relog into the world. It's not an easy thing to fix either. So it's a work with the situation kinda issue.

However, if they are showing on the surface they  **are** underground but we have found in 50% of cases the actual ore is in the next chunk on the SE corner of the chunk. So you have to dig around. But they are there and we have confirmed this over and over in other issues. It's just part of the worldgen and RNG.
