### ISSUE TITLE
Animalium Mobs not spawning in the world

### ISSUE THREAD

**Issue by Legatonin** [Darkosto/SevTech-Ages#2163]
## Issue / Bug

Just as the titles says, whatever or whichever world I load in, there's not even one animalium mob that ever spawns.

## Expected Behavior

I don't know what is causing this, but it might have to do with the mod itself as to also how the bear claws are not showing any texture whenever I kill Brown Bears.

## Steps to Reproduce (for bugs)

1. 
2.

## Context

Though it doesn't affect me that much, but it does take away that feeling you get, an incomplete modpack where not all of the mobs are present to be killed.
## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 3.0.6
* Java Version:  1.8.0.171
* Launcher Used: Twitch

* Memory Allocated: 7680

* Server/LAN/Single Player: Single
* Resourcepack Enabled?: Cubic
* Optifine Installed?: Yes

**Comment by vadis365** [comment]
Hello,
Animalium land based mobs will spawn in any Biome registered in the forge Biome Dictionary that is non-water (and not end or nether). They are classed as hostiles and will spawn at ALL light levels as we need them to spawn during the day. I made the mod and Darkosto is 100% aware of it's implementation and settings as it was originally made for one of his packs. I'm not sure why the issue of the mob's RNG has been reported a few times as the majority of people are not experiencing any major spawning issues. The Bear claw texture issue has been sorted in the pack now and should all be OK for the 0.3.7 update when it's pushed.
Cheers,
Me.
