### ISSUE TITLE
Cloches cannot grow tier 6 mysticaggradditions seeds

### ISSUE THREAD

**Issue by cpw** [Darkosto/SevTech-Ages#2165]
Cloches don't accept tier 6 mysticaggradditions seeds.

There is a mod to remedy this, recommended by the mod author here: https://github.com/BlakeBr0/MysticalAgradditions/issues/26

The mod: https://minecraft.curseforge.com/projects/mystagrad-cloche-compat?gameCategorySlug=mc-mods&projectID=288959

Looks like a small change but would help quality of life perhaps?

**Comment by justinrusso** [comment]
Closed in https://github.com/Darkosto/SevTechAgesConfigs/commit/079d7b7a3e8856892013473c7d0984e1f1f128cf
