### ISSUE TITLE
[Suggestion] Add Recipe for Transformation Powder

### ISSUE THREAD

**Issue by iffonox** [Darkosto/SevTech-Ages#2167]
Transormation Powder is indirectly required to make the AbyssalCraft Gateway Key, but acquiring the Powder is heavily dependend on RNG. Bad RNG can basically completly stop progression in AbyssalCraft.

## Possible Solution
Add a recipe for Transformation Powder to lessen the impact of bad RNG.

## Context
I visited every Twilight Forest dungeon at least once and turned them inside out and only found one Powder. RNG doesn't like me.

## Client Information
* Modpack Version: 3.0.6
* Java Version: Java 8 update 161 64bit
* Launcher Used: jar laucher via Twitch app with cpw's java arguments from reddit
* Memory Allocated: 6 GB
* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by Dutchs** [comment]
Skeleton Druids drop Transformation Powder also the chests in (large)Hollow Hill's have plenty generally.

**Comment by artdude543** [comment]
This is an RNG drop no recipe will be added to it.
