### ISSUE TITLE
Vicio Mantle of Stars not working

### ISSUE THREAD

**Issue by Aamanus** [Darkosto/SevTech-Ages#2168]
## Issue / Bug

Mantle of Starts form Astral Sorcery pack should allow you to fly.  It appears not to do so in MP servers (I have not tried in SP, but discussion on discord suggests that SP is fine).

## Expected Behavior

Eqiup Mantle of Stars attuned to Vicio and fly around with much glee.

## Possible Solution

No idea, sorry!

## Steps to Reproduce (for bugs)

1. Craft Mantle of Stars with Vicio
2. Jump off high place expecting to fly and die.
3. Repeat a few times incase you're doing something wrong.  
4. Collect corpses.

## Context

Died a few times trying to get it to work.  Looking for alternatives to travel since this isn't working.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 3.0.6
* Java Version: 1.8.0_161-b12
* Launcher Used: Twitch

* Memory Allocated: 8GB

* Server/LAN/Single Player: LAN server
* Resourcepack Enabled?: No
* Optifine Installed?: No

## Server Information
* Java Version: 1.8.0_161-b12
* Operating System: Windows 10 64bit
* Hoster/Hosting Soultion: On my PC.
* Sponge (Non-Vanilla Forge) Server?: no

* Additional Content Installed?: None

**Comment by bbqx** [comment]
Wait...doesn't it say it glides..not gives flight..

**Comment by tyranno66** [comment]
You need a wand attuned to vicio as well. Right clicking the wand propels you in a direction.

**Comment by ravenboilinux** [comment]
It does not give you creative flight. It give the ability to glide.

**Comment by Aamanus** [comment]
Well, sure, gliding. Which is a form of flight.  And isn't "drop like a stone" either.  I have the vicio wand, and can fly around with that, but the Mantle of Stars for Vicio used in conjunction with the wand is supposed to let you zip around.  Instead, if I fire off my wand, the behaviour is the same with or without the mantle on.

Other Mantles I've got seem to work fine, so it's not a general issue with mantles, just this one I can't get working.

**Comment by ravenboilinux** [comment]
That mantle is basically a elytra. You have to jump while in the air to activate(just like the elytra)
