### ISSUE TITLE
Kiln orientation gets reset on chunk (re)load.

### ISSUE THREAD

**Issue by scootz** [Darkosto/SevTech-Ages#217]
Place a kiln which ever direction.  Leave the area so chunk gets unloaded, come back and find the kiln ends up facing east.
![2017-11-25_11 20 31](https://user-images.githubusercontent.com/574344/33242976-10b30e1c-d2ab-11e7-935b-3b28ffce03e7.png)
![2017-11-25_11 31 12](https://user-images.githubusercontent.com/574344/33242978-16d10204-d2ab-11e7-9426-ee1eb8ca2d76.png)

**Comment by Darkosto** [comment]
Yep, this happens regardless of the firepit on bottom. Tested with Netherrack and fire underneath. Kilns still rotate.

**Comment by vadis365** [comment]
should be fixed in 0.2.95
