### ISSUE TITLE
Sigil of Winters Breath - Unable to reconnect to server

### ISSUE THREAD

**Issue by Gingey231** [Darkosto/SevTech-Ages#2170]
## Issue / Bug
Games disconnects user from the server and will not allow reconnection.

## Expected Behavior
I created the Sigil of Winters Breath and popped it straight into the Sigil of Holding. Upon activation of the sigil that is within the sigil of holding, game disconnects with an "internal server error".

What should happen is the water blocks around me in a 3x3 area turn to ice, however my client is now stuck in a loop of crashing and not being able to join the server. The actual MC client still works fine. Did restart the client a couple of times with no luck.

When trying to reconnect, all i get is 'Internal server error occurred', and after multiple times, 'An Established connection was aborted by the software in your host machine' Cannot load back into the multiplayer server.

Had to download the .dat for my player, edit to remove the sigil from the holding sigil, and then was able to load back into the server fine.

## Possible Solution
Sadly, no idea how it caused the crash.

## Steps to Reproduce (for bugs)
1. Create Sigil of Holding
2. Create Sigil of Winters Breath
3. Put Sigil of Winters Breath in Sigil of Holding
4. Activate Sigil of Winter Breah in the Sigil of Holding near water.
5. Get disconnected from world.
6. Attempt to join back and get stuck in a disconnection loop.

## Context
Unable to join into a multiplayer world with 3 other people that there is a lot of progress that has been done (Currently on Age 2, completed all advancements apart from Advanced Mapping, Coal Engine and Carmine Reactor to go.

## Logs
* Client/Server Log: No crash log found for this, as wasnt a full client crash
* Crash Log: No crash log found for this, as wasnt a full client crash

## Client Information
In an Beaches biome, on the coast. Bug was experienced while standing on a Stone platform, 1 block away from the water.

* Modpack Version: 3.0.6
* Java Version: Java V8 U161
* Launcher Used: Twitch App
* Memory Allocated: 8GB
* Server/LAN/Single Player: Server
* Resourcepack Enabled?: Yes - Sphax base pack + Sphax SevTech Patch - http://bdcraft.net/community/pbdc-patches-rel-packs/sevtech-ages-t6438.html
* Optifine Installed?: Yes

Did not affect anyone else on the server, only myself.

**Comment by artdude543** [comment]
I believe _most_ Sigil issues are fixed in the next update of the pack. You could try updating BloodMagic yourself to see if this resolves the issue. Also, I still need the client log (even for none crashes, which you have a client log we all do it's always made period)

**Comment by Gingey231** [comment]
Hey artdude543,

Many thank for the response, i will give it a try and fingers crossed should all be good :)

Ill pop the client log here:  https://dumptext.com/9FlXbwJW - Was too large for PasteBin
