### ISSUE TITLE
QOL Suggestion: Add trash slot mod for help manage inventory clutter

### ISSUE THREAD

**Issue by LordHellscream** [Darkosto/SevTech-Ages#2171]
Loving this modpack, having unreal amount of fun.
One thing that can really make life easier is may be add the trash slot mod to help manage inventory cluttering, which is a problem with large modpack like this.

Thank you and keep up the fantastic work!

**Comment by artdude543** [comment]
This won't be added. You can use a hole or lava or cactus or throw in a stream and watch it flow away. You also unlock a trash can in stage 5!

**Comment by Jandakast** [comment]
![trashcan](https://user-images.githubusercontent.com/19498789/39458908-2e71dc22-4cc6-11e8-819a-b3a1f2f4a143.gif)

**Comment by billybricker** [comment]
In addition to the suggestions above Quark has a feature that allows you to delete items in your inventory by moving your cursor over them and pressing CTRL + Delete.
