### ISSUE TITLE
Glitch crafting multiple items

### ISSUE THREAD

**Issue by charissa-larsen** [Darkosto/SevTech-Ages#2172]
## Issue / Bug
Occasional bug when trying to craft multiple copies of an item. The crafting grid shows the correct recipe, but the item slot is blank. Sometimes I can craft one of an item before having to clear the table and start again, sometimes it will craft multiple items just fine, sometimes the item slot is empty from the start.

## Expected Behavior
When a recipe is selected and shift+ is clicked, the crafting table should populate and the item slot show the crafted item. 

## Steps to Reproduce (for bugs)
1. Open crafting table GUI
2. Search for recipe in JEI
3. Click on recipe.
4. Click shift+ to transfer items to crafting table
5. Crafting grid populates, but item slot is empty.
5a. Sometimes can pull down items from item slot one at a time, but at some point before crafting all items from available items in crafting grid, the item slot blanks out.

Confirmed that it's not just a visual glitch--clicking on the empty item slot does not pick up a crafted item.

Workaround: exit crafting grid GUI and start over with recipe.

Shift-clicking to craft all from the items in the grid seems to work just fine, it's when starting to craft or crafting one at a time (if you're not sure you want to craft all of them) that is the issue.

## Context
Slows down crafting when trying to craft multiple items of the same recipe.

## Logs

Not a crash, but here is a screen shot:
![2018-04-30_21 06 58](https://user-images.githubusercontent.com/36979185/39458632-b4c9c56a-4cbb-11e8-9f6b-cc225041d237.png)

## Client Information
* Modpack Version: 3.0.6
* Java Version: 1.8.0 171 64 bit
* Launcher Used:
MultiMC
* Memory Allocated: 8GB
* Resourcepack Enabled?: Soartex Fanver (occurred with no texture, pack, as well).
* Optifine Installed?: No.

**Comment by artdude543** [comment]
This is something we are still working on as it causes the same issue as recipes derping with stairs/slabs. We've not found the mod causing this as it's an interaction issue. But you want to help out debugging you can try toggling some mods which change crafting mechanics to find the fault one :) 

But regardless this is a known issue and may be for a while. Sorry.
