### ISSUE TITLE
[3.0.6] The Betweenlands: Can't plant flowers

### ISSUE THREAD

**Issue by obuw** [Darkosto/SevTech-Ages#2177]
## Issue / Bug
When I right-click on the various dug composted swamp dirts with flowers, nothing happens.

## Expected Behavior
The betweenlands wiki states that flowers can be planted on dug composted swamp dirt.

## Context
Trying to get the "Flower Power" advancement in betweenlands - farmer advancements.
(Not sure if this is a betweenlands bug or sevtech bug. Or maybe I'm doing something wrong.)

## Client Information
* Modpack Version: Sevtech 3.0.6 (Unmodified)
* Java Version: Java 1.8.0.161
* Launcher Used: Twitch Launcher
* Memory Allocated: 12GB
* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: No
* Optifine Installed?: No

![2018-05-01_13 51 48](https://user-images.githubusercontent.com/7712098/39475189-00f6675a-4d60-11e8-8cfc-b7d582017ce5.png)
![2018-05-01_13 52 47](https://user-images.githubusercontent.com/7712098/39475190-011d0338-4d60-11e8-855a-65dc02a7a553.png)
![2018-05-01_16 44 59](https://user-images.githubusercontent.com/7712098/39475191-014273fc-4d60-11e8-82ac-470ff0fbaff5.png)

**Comment by obuw** [comment]
The first two screenshots show the "Marsh Marigold" flower that you get using the sickle. I heard that this version might not be plantable, so I got some other flowers using the Syrmorite Shears. None of those were plantable either. I've tried both regular and purified versions of undug, dug and composted swamp dirt, in both the overworld and the betweenlands.

**Comment by TheCyberBrick** [comment]
Those are water plants. They must be planted one block under the water, just like they generate naturally.

**Comment by obuw** [comment]
![2018-05-01_20 59 02](https://user-images.githubusercontent.com/7712098/39486138-c9c2b8b4-4d83-11e8-9133-a7d8345270a7.png)
![2018-05-01_21 04 00](https://user-images.githubusercontent.com/7712098/39486139-c9ec2546-4d83-11e8-8360-1a73694a1bbb.png)

Okay so I tried planting them underwater, and that didn't work either.

I'm not sure if there are actually any non-water flowers in betweenlands? I don't think I've seen any. Unless cattails count...

**Comment by TheCyberBrick** [comment]
They must be planted **one** block under the water.
Also forgot to mention that they must be planted in swamp water.
There are tons of other plants and flowers in the Betweenlands, and any plant can be planted on composted dirt.

**Comment by obuw** [comment]
Ah, finally! So my overworld test was under regular water, and my betweenlands test was 2 blocks down. So frustrating.

So I finally managed to plant the flowers, but the achievement didn't even advance. Anyway I found some actual non-water flowers now, I'm sure the achievement will advance when I plant those. 

Thanks for the help!
