### ISSUE TITLE
XP is lost when traveling between dimensions

### ISSUE THREAD

**Issue by ImTheStigHonest** [Darkosto/SevTech-Ages#2178]
## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:

* Memory Allocated:

* Server/LAN/Single Player:
* Resourcepack Enabled?:
* Optifine Installed?:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Soultion:
* Sponge (Non-Vanilla Forge) Server?:

* Additional Content Installed?:

**Comment by vadis365** [comment]
duplicates #2143
