### ISSUE TITLE
Texture issues with kiln

### ISSUE THREAD

**Issue by scootz** [Darkosto/SevTech-Ages#218]
A kiln that has been "cooked/fired" (soartex is redish) shows unfired when picked up (shift-right-clicked)
![2017-11-26_13 16 52](https://user-images.githubusercontent.com/574344/33243038-1e56b1bc-d2ac-11e7-9b01-9be27c1ce0e9.png)
![2017-11-26_13 17 05](https://user-images.githubusercontent.com/574344/33243041-27d62088-d2ac-11e7-8be8-2890e150dc68.png)

**Comment by Darkosto** [comment]
Fixed!
