### ISSUE TITLE
Horse chopping block recipe don't work in 307.6 ?

### ISSUE THREAD

**Issue by OldManCraft** [Darkosto/SevTech-Ages#2180]
forge 2676
None of the recipes work for any of them.

**Comment by artdude543** [comment]
Just tested this and both the recipe for the chopping blocks are working as intended, along with the blocks own recipes.

Commenced Canned Response:

Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

Thanks again for reporting, and we hope you enjoy the pack!
