### ISSUE TITLE
Connection Lost on loading a singleplayer world?

### ISSUE THREAD

**Issue by ThePlagueDoctor** [Darkosto/SevTech-Ages#2182]
## Issue / Bug
Loading a world and one I get to the part where the blocks load around me, it shuts off and shows me this
Connection Lost
internal exception: java.nio.channels.closedchannelexception

## Expected Behavior
For the world to load around me.

## Possible Solution
No idea.

## Steps to Reproduce (for bugs)
Load a world up?

## Context
I can't play the game.

## Logs
I understand not wanting to download them but, everytime I paste them on Gist or Pastebin I have an error of it crashing.
I actually am unable to upload the debug log here even. About 196178 KB
## Client Information
* Modpack Version: 3.0.6
* Java Version: 1.8.0.172 64 bit
* Launcher Used: Twitch
* Memory Allocated: 12288 MB (Have tried with 6k ish as well so isn't RAM I believe.)

**Comment by artdude543** [comment]
Resolved in 3.0.7 looked for closed issues before making a dupe.
