### ISSUE TITLE
Duplicate Iron Ingots

### ISSUE THREAD

**Issue by kremfloete** [Darkosto/SevTech-Ages#2187]
## Issue / Bug
Iron can be duplicated by crafting and melting iron bars back into ingots.

## Possible Solution
Tweak some recipes.

## Steps to Reproduce (for bugs)
1. Obtain **3** Iron Ingots.
2. Craft them into 6 Iron Rods using the Metal Press from Immersive Engineering.
3. Craft them into 16 Iron Bars in a Crafting Table.
4. Melt them into **6** Iron Ingots in a Crucible from Better With Mods.

## Client Information
* Modpack Version: 3.0.6

**Comment by kragnoth** [comment]
Might I suggest just having the recipe give less iron bars, as they are less useful than the iron rods.  Having the press make 2 iron rods is very useful for some IE recipes.  Whereas iron bars are hardly used by anything.

**Comment by Jandakast** [comment]
Removed Iron Bars to iron Ingot Stoked Crucible recipe in 3.0.7
