### ISSUE TITLE
Carry on + embers crash

### ISSUE THREAD

**Issue by justinrusso** [Darkosto/SevTech-Ages#219]
Wanted to document so this wouldnt be missed in case it is not known.
From discord:
Scootz - Today at 9:34 PM
wee! carry on mod and embers == crash.
also item dupes.
mixer centrifuge is multipart.  use carryon to attempt to move it. It takes the block you want to move, but discards the other one in its original place.  The new location has both blocks like it should.
pick up the block left behind and replace it, it creates the missing block so now you got two centrifuges.
its a 1x2 multiblock.. so if anyone of the blocks overwrites the previous one, it crashes.

**Comment by scootz** [comment]
Ah thank you Justin! Forgot to post the bug.

**Comment by Darkosto** [comment]
Removed from carryon
