### ISSUE TITLE
Items don't drop, animals don't move/can't be damaged.

### ISSUE THREAD

**Issue by viiper02** [Darkosto/SevTech-Ages#2191]
## Issue / Bug
After 5 minutes of playing, items no longer drop at all. I can break blocks but nothing at all drops or shows up. Animals don't move and can't be damaged. The day no longer progresses.

## Expected Behavior
 Items should drop when I break grass/flowers for example. Instead nothing is able to drop. When I break dirt nothing drops. Animals cannot be damaged at all and they stay completely stationary.

## Steps to Reproduce (for bugs)

https://www.youtube.com/watch?v=S4jKPhmVvnI&feature=youtu.be
## Context
This issue has affected me as I am unable to play the game and progress at all.

## Logs
* Client/Server Log: https://paste.ee/p/xZQaC

## Client Information
* Modpack Version: 3.0.6
* Java Version: Version 8: Update 121.
* Launcher Used: Twitch Launcher.
* Memory Allocated: 8 GB.
* Server/LAN/Single Player: Single Player.
* Resourcepack Enabled?: No.
* Optifine Installed?: Tried it with and without. Both lead to the same issue.

**Comment by Jandakast** [comment]
This hasn't happened to me. Your client log looks normal up until you exit the world. It isn't doing the Unregistering and saving of the dimensions when you "Save and Quit". Can you play any other pack? Are you running out of disk space?
