### ISSUE TITLE
Crash game when loading world

### ISSUE THREAD

**Issue by Kpoy101** [Darkosto/SevTech-Ages#2194]
## Issue / Bug
The game flew out after I put the spawner agitator(from pneumatic: repressurized) on the blaze spawn.

## Possible Solution

Cut?
## Steps to Reproduce (for bugs)

1. Transfer spawner to the base.
2. Paste spawner agitator
3. Go to the distance of work stoppage. (u know in normal mine spawner stop working when u far away)

## Logs

* Client/Server Log: https://paste.ubuntu.com/p/VPrJr2SBmC/

## Client Information

* Modpack Version: 3.0.6
* Java Version: (build 1.8.0_171-b11)
* Launcher Used: Twitch app

* Memory Allocated: max10g min2g

* Server/LAN/Single Player: SP
* Resourcepack Enabled?: no
* Optifine Installed?: no

**Comment by Jandakast** [comment]
This has been reported several times and is fixed in 3.0.7

Disable Despawning Spawners to get back into your world. 

https://github.com/Darkosto/SevTech-Ages/issues/1841

**Comment by Kpoy101** [comment]
Sorry for the duplicate. I tried to look, but did not find this error. Thx for solution!
