### ISSUE TITLE
Firesticks crash for Investigation

### ISSUE THREAD

**Issue by vadis365** [Darkosto/SevTech-Ages#2195]
Firesticks crashed - no need for bumph I know, I know. Putting this here as a personal reminder with the crash report.
https://pastebin.com/jQPx491N

**Comment by justinrusso** [comment]
Someone pointed out that it seems to be the stick they are given from the reward. This item given was never tweaked with that adjustment and thus is causing the same crash we had before.

**Comment by justinrusso** [comment]
Though a cheated in stick from JEI gives an nbt tag of `{}` and doesnt cause a crash when I've tested...

**Comment by vadis365** [comment]
Closing due to the fact the original crash report now seems invalid.
@justinrusso dm me (discord or twitch) if you need the tags to add to the reward (pretty sure we did have them before)
