### ISSUE TITLE
Hemp uprooting

### ISSUE THREAD

**Issue by tofof** [Darkosto/SevTech-Ages#2197]
## Issue / Bug
Hemp uproots immediately when planted adjacent to one another. Hemp spread out with a tile in between uproots after a random amount of time.

Block is in sunlight and in a plains-type biome, with at least two blocks of dirt below. Hydration doesn't matter - still happens adjacent to a water block. Seems to require being near to a full block.

Eyekantspel's post in #1472 applies exactly, the rest seem unrelated. I'm nowhere near tumbleweeds or hot biomes, those are roughly 800 blocks away.

## Expected Behavior
Hemp stays planted.

## Steps to Reproduce (for bugs)
1. Plant hemp adjacent to a wall (e.g. stone brick block, not the 'wall' fence-like blocks).
2. Plant hemp adjacent to that hemp, also adjacent to the wall.
3. Hemp uproots.

Unfortunately, location seems to matter. Against some walls (stone brick blocks) it's 100% repeatable, even a full block out from the wall. On tests I've made trying to reliably reproduce elsewhere, though, hemp still uproots after a random delay, but not when placed adjacent. In still other places it doesn't uproot at all.

Uprooting against wall:
[![Uprooting hemp](https://thumbs.gfycat.com/FrequentDeliciousAmericanalligator-size_restricted.gif)](https://gfycat.com/FrequentDeliciousAmericanalligator)

Uprooting not against wall:
[![No uprooting](https://thumbs.gfycat.com/DeterminedDimpledArmednylonshrimp-size_restricted.gif)](https://gfycat.com/DeterminedDimpledArmednylonshrimp)

Not uprooting:
[![Uprooting hemp](https://thumbs.gfycat.com/RevolvingUnimportantIbex-size_restricted.gif)](https://gfycat.com/RevolvingUnimportantIbex)

## Context
Hemp is required for the only saw to chop wood into planks. 

## Logs
Not a crash.

## Client Information
* Modpack Version: 3.0.6
* Java Version: 1.8.0_161
* Launcher Used: Titan
* Memory Allocated: 12GB
* Server/LAN/Single Player: Lan
* Resourcepack Enabled?: No
* Optifine Installed?: Yes

**Comment by Jandakast** [comment]
I cannot reproduce this. Post a screenshot of your farm.

**Comment by tahg** [comment]
There is no ceiling where you're placing the hemp? It needs direct sunlight and a lightlevel of at least 12.

**Comment by tofof** [comment]
In all three videos above there is a transparent (afaik) ceiling, including
the one in which hemp doesn't uproot - so that doesn't seem to be
correlated at all.

I will install a mod to let me check light levels.

**Comment by tofof** [comment]
In all three videos above there is in fact a transparent (afaik) ceiling, **including
the one in which hemp doesn't uproot** - so that doesn't seem to be
correlated at all.

I will install a mod to let me check light levels.
