### ISSUE TITLE
Can't Turn Off Step Assist

### ISSUE THREAD

**Issue by el0c** [Darkosto/SevTech-Ages#2199]
## Issue / Bug
 
 This issue has been brought up and closed a few times, always with the answer "This is enabled because reasons, closed." (Issue #892)
The only real answer that was given was that you'd have to walk quite a bit for some of the ages and "you'll be annoyed by all the jumping" (Issue #827)
But, in reality I'm annoyed I have less control when I get closer to other blocks. Especially in the early game when I'm trying to jump around and run from things in mines and stuff. This feature has needlessly killed me more times than it has helped and turned me off from progressing to the point I can disable it due to these frustrations.

All the previous answers seem to indicate that it's purely a QOL feature for the mod pack. 
I don't understand why, then, that can't be an OPTION for players.   (*Cough* Auto-Jump is, in vanilla *Cough*)

## Expected Behavior

 The player would have the choice between step-assist or none from the start of the game.

## Possible Solution

 Remove it from progression. 

## Context
 It's caused my death in multiple situations, like climbing trees and running from mobs to landing precise jumps. 

## Logs

* Client/Server Log: N/A
* Crash Log: N/A

## Client Information

* Modpack Version: 3.0.6 
* Java Version: 1.8.0_171
* Launcher Used: Twitch

* Memory Allocated:6212

* Server/LAN/Single Player: SP
* Resourcepack Enabled?: No
* Optifine Installed?: Yes

**Comment by SteseDav** [comment]
just as a comment step-assist != to autojump.

**Comment by TheEaglez** [comment]
Why don't you just cheat in the item if you really want it off? Like I don't get it what's the point in asking here if you already know the reason why they put it in and they clearly want you to progress to turn it off. 

At first I didn't like it but after a day or 2 I became to appreciate that they put it in and the only reason that actually happened is that we can't disable it first thing in the pack. So I for one really like that they put it behind progression. And from what I understand a lot of people are with me on that.

**Comment by el0c** [comment]
SteseDav, that isn’t the point. The point is both are changes purely for perceived quality of life and perform a similar function; neither of which I do or want to use.

Eaglez; if you go actually read what they said in the issues I linked and described, they said “it’s enabled for X reasons” that’s a quote. What reasons? 
The only “real” reason they provide is they think it makes it easier to progress through the ages because of all the walking involved. 

That’s well and good, but as I said; that’s a matter of preference. I don’t want to walk up my one block walls on my rooftops when peering over. brush the blocks next to me and suddenly be up a level on the side of a mountain, etc. 
I also don’t want to have to enable cheats on my world or OP myself on my server when playing with friends just to turn off something that should be an optional setting, unrestricted by progression.
If there was a concrete answer other than “well this personally makes it easier for me because I don’t like pressing space all the time,” then maybe I’ll see they’re reasons. But right now, I haven’t seen or thought of any good ones.

**Comment by SteseDav** [comment]
el0c - I completely understand your points and agree. Having it as a QOL that is enforced doesn't improve the QOL for those that don't want it. 

Maybe have it as an item to be carried, like the early stage map... the effect of said item could then be staged out later as needed.

My comment was simply to highlight that the two features are different as some may not be aware.

**Comment by justinrusso** [comment]
This is not getting changed. There is an item in the game to disable it. Cheat it in for all we care. You have the option to disable it eventually and it was a design choice. This has been stated endless amounts of times.

**Comment by el0c** [comment]
“Design choice.” 
Alright, then. 

https://imgflip.com/i/29l3p9

**Comment by justinrusso** [comment]
Or... you can just play the game and you can see there is an advancement that tells you the item and the purpose of it.
