### ISSUE TITLE
[A8] Suggestion Ember Dial

### ISSUE THREAD

**Issue by Dawenzel** [Darkosto/SevTech-Ages#220]
## Suggestion
Changing the tin plates in the recipe for the Ember Dial `<embers:ember_gauge>` in stage1.recipes.zs to copper plates instead and the copper ingot to a tin ingot. This would, in my opinion, make it so the recipe more accurately represents the item itself.

## Versions
- Minecraft 1.12.2
- Forge 14.23.0.2544
- Java x64 8u144
- Sevtech-Ages Alpha 8

**Comment by Darkosto** [comment]
Added!
