### ISSUE TITLE
I've lost my quest two times now and i can't find any other report on here about this, my first save i was at the end of age 3 and i logged in to find out my quest was reseted and had to do everything all over again but my progress was saved. Also i tried doing the next step of the quest to see if it would work and it didn't. Sorry if it was already discussed i couldn't find it. 

### ISSUE THREAD

**Issue by Detrostic** [Darkosto/SevTech-Ages#2200]
## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:

* Memory Allocated:

* Server/LAN/Single Player:
* Resourcepack Enabled?:
* Optifine Installed?:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Soultion:
* Sponge (Non-Vanilla Forge) Server?:

* Additional Content Installed?:

**Comment by artdude543** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

Thanks again for reporting, and we hope you enjoy the pack!
