### ISSUE TITLE
Server crash while loading

### ISSUE THREAD

**Issue by Cinciullain** [Darkosto/SevTech-Ages#2203]
## Issue / Bug
The server crashes when loading, no crashlog created. 

## Expected Behavior
It should just start and works, as the past days :)

## Possible Solution
idk

## Steps to Reproduce (for bugs)
Reach Age 1

## Logs
* Client/Server Log: https://pastebin.com/zjMCkUU5 <---latest.log
* Crash Log: No Crash Log created by the server

## Client Information
* Modpack Version: 3.0.6
* Java Version: Java 8 Update 171
* Launcher Used: Jar
* Memory Allocated: 6144

* Server/LAN/Single Player: Server
* Resourcepack Enabled?: N
* Optifine Installed?: N

## Server Information
* Java Version: Java 8 Update 171
* Operating System: Windows 10 Pro
* Hoster/Hosting Soultion: Hoster
* Sponge (Non-Vanilla Forge) Server?: N
* Additional Content Installed?: N

**Comment by justinrusso** [comment]
The exception was: java.net.BindException: Cannot assign requested address: bind

Change the port the server is assigned to

**Comment by Cinciullain** [comment]
I read the log and changed the port, but nothing changed. The problem still persists @justinrusso
