### ISSUE TITLE
Stuck at Galacticraft Planet selection screen

### ISSUE THREAD

**Issue by timmit99** [Darkosto/SevTech-Ages#2204]
## Issue / Bug
Sometimes, when playing the pack, hitting my "Mute Audio" button (F2/Volume down with a function toggle key) on my Lenovo P50 will cause the Planet Selection Screen to pop up with NO way to close it. At the beginning of the pack i went through and removed all the key-binds and redid them so i only had the key-binds that i currently used and added the new key-binds as the mods were unlocked.

## Expected Behavior
I have literally hit EVERY key on my keyboard with and without shift/ctrl/alt/Fn and NOTHING will let me escape the screen. i MUST close the game and reboot to continue playing. 

## Possible Solution
Not sure how to fix, possibly disable the planet selections screen until the age it is unlocked?

## Steps to Reproduce (for bugs)

1. Come to my apartment
2. Randomly hit F2 at the WORST possible time

## Context

I CANNOT continue playing when this message pops up, I will have to assign it to a num-pad or another key to try to get out.

## Client Information
* Modpack Version: 3.0.6
* Java Version: 8.0.25.18
* Launcher Used: Twitch Launcher
* Memory Allocated: 4096 MB
* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by artdude543** [comment]
We have updated the mod which includes a possible fix for this issue. If this is still a new issue however please make a new issue with all the data 🙂
