### ISSUE TITLE
crash in the nether

### ISSUE THREAD

**Issue by salanga** [Darkosto/SevTech-Ages#2206]
i am using sevtech version 3.0.6 in the twitch launcher and the maximum amount of memory allocated is 8000mb.
i have not added anything to the modpack and am playing it in the same way as it is downloadable in the twitch launcher.
this is my crash report.
https://pastebin.com/2NSuZ8Vk
my crash happened when i was moving back from my blaze spawner towards my portal a route i have already taking for about 10 times. i am in age 4 now and have entered it a while ago. i was using the astral sorcery impulsion wand while wearing iron armor and coagulated blood boots.
while in motion my game crashed and when i tried to restart the modpack and after that my world i crashed again without being able to enter.
if i can fix it by changing something in my world file i would like it if there is an explanation here or available somewhere else.
i am playing in my single player world without a resourcepack.
at first notice it looked the same as the crash which happens when you are reading the Immersive engineering manual.
![image](https://user-images.githubusercontent.com/38591606/39599062-d5e45862-4f1a-11e8-9789-5ee07e1da572.png)
this is the screen i get when i try to enter my world.
the language is dutch
a free translation of it is: there has been an unexpected problem and your game has crashed. our apologies for the trouble.

**Comment by artdude543** [comment]
Fixed in 3.0.7 should be out soon no eta tho.
