### ISSUE TITLE
Early Air sigil access

### ISSUE THREAD

**Issue by lawl281** [Darkosto/SevTech-Ages#2207]
## Issue / Bug
obtaining and using an air sigil is possible before it is unlocked.

## Expected Behavior
No access to Air sigil

## Possible Solution
Move sigil of holding to same age as air sigil

## Steps to Reproduce (for bugs)
1. Make Air sigil regent
2. Put it in hopper feeding into ashes
3.Finish with slate
4.Put into sigil of holding
5.FLY!!!

## Context
Air sigil is unknowen until age 4 I believe.  Since the arcane ash is considered an inventory you can put ingredients in with a hopper allowing crafting of unobtainable sigils.  You can then use any unkown sigils inside of sigil of holding without dropping them.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 3.0.6
* Java Version:
* Launcher Used: Twitch

**Comment by justinrusso** [comment]
Moving the sigil of holding stage would make it so players who currently have it and use it wouuld not be able to even get their sigils out of it. Will need to look into options.

**Comment by lawl281** [comment]
Is this actually fixable without moving the sigil of holding on this end?  Wouldn't it require Way to make it so it can't be input into.

**Comment by Jandakast** [comment]
The Air Reagent used to make the Air Sigil requires Elytra which can now only be obtained in age 4. This should resolve the issue of you being able to make the Air Sigil early.
