### ISSUE TITLE
Immediate loss of connection on attempt to join server

### ISSUE THREAD

**Issue by EhGneissGuy** [Darkosto/SevTech-Ages#2208]
## Issue / Bug

![image](https://user-images.githubusercontent.com/17113297/39606210-31ad2ac0-4f02-11e8-8cda-60b4f487826e.png)
Immediate loss of connection upon attempt to join server for all players. Kick exists past initial loss of connection experienced in 3.0.6. Disconnect experienced by all players. Restarting server/clients does not solve issue. I personally noticed mention of astral sorcery in the log, but am not familiar enough to discern cause of issue.

Log available below.
[latest.log](https://github.com/Darkosto/SevTech-Ages/files/1972887/latest.log)

New to Gist, hope this works as an alternative. https://gist.github.com/EhGneissGuy/057f2de03aa0b53dfc9546234c306bc1

Edit: Seems to be related to whether or not a single player is wearing a mantle of stars. Removing his cloak and him relogging, then hard stopping and starting the server results in others being able to join. Hard stop and start by itself doesn't.

Edit: Success is mixed. Above might have been coincidental.

## Expected Behavior

Successful connection to server.

## Possible Solution

N/A

## Steps to Reproduce (for bugs)

1. Log into server.
2. Experience initial disconnect.
3. Reconnect.
4. Disconnect and repeat.

## Context

Unable to load connection to server.

## Logs

* Client/Server Log: [latest.log](https://github.com/Darkosto/SevTech-Ages/files/1972891/latest.log)
* Crash Log: Client/Server do not crash, just kick/disconnect player

## Client Information

* Modpack Version: 3.0.6
* Java Version: 8.171
* Launcher Used: ATLauncher

* Memory Allocated: 4GB

* Server/LAN/Single Player: Server
* Resourcepack Enabled?: No
* Optifine Installed?: Yes

## Server Information
* Java Version: N/A
* Operating System: N/A
* Hoster/Hosting Soultion: CubedHost 4GB Premium 
* Sponge (Non-Vanilla Forge) Server?: N/A

* Additional Content Installed?: No

**Comment by artdude543** [comment]
Resolved in 3.0.7
