### ISSUE TITLE
Age 4 Advancement "Ender Crafter" triggers without Ender Alternator

### ISSUE THREAD

**Issue by Targren** [Darkosto/SevTech-Ages#2209]
## Issue / Bug

Advancement description says "Craft the Ender Crafter and Ender Alternator for Advanced Crafting", but the Advancement triggered 2/2 on crafting only the Ender Crafter block. 

## Expected Behavior

Advancement triggers after both machines are obtained.

## Possible Solution

Either the text is in error, or the advancement logic

## Steps to Reproduce (for bugs)
1. Advance to stage 4 "Enhanced Ender Alloy"
2. Craft "Ender Crafter" block

## Context

Minor issue

## Client Information

* Modpack Version: 3.0.6
* Java Version: 1.8
* Launcher Used: MultiMC 5 0.6.2

* Memory Allocated: 6GB

* Server/LAN/Single Player: SSP
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by Jandakast** [comment]
Fixed for 3.0.7
