### ISSUE TITLE
[A8] Suggestion Tinkers Hammer

### ISSUE THREAD

**Issue by Dawenzel** [Darkosto/SevTech-Ages#221]
## Suggestion
Give the Tinker's Hammer as a reward for completing the Ember's Emitter/Receiver advancement like is done with the Stone mallet when the Stone Anvil advancement is completed. Also, add a tooltip to the Tinker's Hammer explaining how to use it even though this is clearly explained in the book/guide.

## Versions
- Minecraft 1.12.2
- Forge 14.23.0.2544
- Java x64 8u144
- Sevtech-Ages Alpha 8

**Comment by Darkosto** [comment]
Added! Thanks!
