### ISSUE TITLE
every movement wigs out game. impossible to play

### ISSUE THREAD

**Issue by d1kong2** [Darkosto/SevTech-Ages#2210]
every time i move my chcaracter the screen wigs out and fades to black or the sky and i think i travel through blocks. also character is constantly flailing arms.
 i am using v2 and world worked fine until closed now i cant load it without being unplayable. never made it past stone age
using twich as launcher & 4 gigs of ram
![2018-05-03_22 22 17_3](https://user-images.githubusercontent.com/19600734/39611938-e34f99f2-4f20-11e8-8059-a032b84d616f.png)
![2018-05-03_22 22 02](https://user-images.githubusercontent.com/19600734/39611939-e365ee3c-4f20-11e8-818f-5075b2a34559.png)
![2018-05-03_22 22 02_2](https://user-images.githubusercontent.com/19600734/39611940-e37c5172-4f20-11e8-93eb-b059e84eff67.png)
![2018-05-03_22 22 03](https://user-images.githubusercontent.com/19600734/39611941-e3937618-4f20-11e8-9d7c-e2dfc8592736.png)
![2018-05-03_22 22 03_2](https://user-images.githubusercontent.com/19600734/39611942-e3abfff8-4f20-11e8-87d7-c94e705393e4.png)
![2018-05-03_22 22 14](https://user-images.githubusercontent.com/19600734/39611943-e3c44252-4f20-11e8-9c93-43ea3ad9481b.png)
![2018-05-03_22 22 17_2](https://user-images.githubusercontent.com/19600734/39611945-e3e8a0f2-4f20-11e8-896e-37185ad3aef2.png)

**Comment by professorkintosh** [comment]
I deleted the Mo'bends mod from the pack, and my similar issues went away. Give it a try, perhaps only move the file out of the mods folder and reload.

**Comment by Espergium** [comment]
This isn't helpful. If you took the time to fill out the template on the new issue button instead of blanking it then we could have more info on your system.

This is an issue with your computer and not the pack.
What are your system specs? Are you using optifine? Did you mess with any buttons in the betterFPS screen?

**Comment by d1kong2** [comment]
i am sorry i didnt follow the outline for submission. I never thought me messing with the betterFPS sceen could cause problems. i can check latter if needed but pretty sure i changed the big button. something about different peoples algorithms. didnt even think about that. What is the default? I will try changing and restarting and will close this tab if it fixes it

**Comment by Espergium** [comment]
Riven's half algorithm should be default.

Messing with that math button can cause limbs and mobs to fly all over the place, and cause texture issues.
In 99% of cases you don't need to touch the button.

**Comment by d1kong2** [comment]
thank you
