### ISSUE TITLE
Upper Item deletion glitch

### ISSUE THREAD

**Issue by syrun97** [Darkosto/SevTech-Ages#2213]
## Issue / Bug

upper deletes items when get redstone and draw item in world same times.
## Expected Behavior

upper get item and get locked by redstone
## Possible Solution

IDK
## Steps to Reproduce (for bugs)

1. lock upper with redstone signal and throw items.
2. spam flick lever.
3. ???
4. Item deleted! 

## Context

[bandicam 2018-05-04 16-14-08-168.zip](https://github.com/Darkosto/SevTech-Ages/files/1973529/bandicam.2018-05-04.16-14-08-168.zip)
<--- why github doesnt support vedio file --->

 
## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:3.0.6 / better foilage, betterFPS,Fancyblockparticle,smoothfont disabled
* Java Version:1.8.0_171
* Launcher Used:vanilla(Twich sucks)

* Memory Allocated:5G

* Server/LAN/Single Player:single player
* Resourcepack Enabled?:nope
* Optifine Installed?:nope

* Additional Content Installed?:blood magic:2.2.11-96

**Comment by Targren** [comment]
I've been trying to figure out what's been eating my ore from my smeltery loader... it's the upper + trapped chest!

**Comment by vadis365** [comment]
Hello,
Just pushed an update to uppers (0.0.6) which should fix this little derp.
Should be fixed in SevTech 3.0.7 - but needs to be tested in the pack to be sure.
Cheers,
Me.

**Comment by vadis365** [comment]
seems good - closing
