### ISSUE TITLE
simple storage network problem retreiving certain items.

### ISSUE THREAD

**Issue by JEKleine** [Darkosto/SevTech-Ages#2215]
## Issue / Bug
I am not able to retrieve certain items from a simple storage network connect to a  drawer controller using its storage request table. Items that currently are affected are swords and engineer's blueprints. 

## Expected Behavior

items are able to be pulled out of the connected drawer controller. 

## Possible Solution
No idea.

## Steps to Reproduce (for bugs)

1.  make a simple storage network (request table, network master, link cable)
2. connect a drawer controller with 2x2 framed drawers attached to it. 
3. insert a damaged iron sword into the request table.
4. try to pull the sword from the network.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 3.0.6
* Java Version:
* Launcher Used:

* Memory Allocated:

* Server/LAN/Single Player:
* Resourcepack Enabled?:
* Optifine Installed?:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Soultion:
* Sponge (Non-Vanilla Forge) Server?:

* Additional Content Installed?:

**Comment by Jandakast** [comment]
I am unable to reproduce this. Please report this again if it is still happening in 3.0.7
