### ISSUE TITLE
[A8] Suggestion Barrel Extension Advancement

### ISSUE THREAD

**Issue by Dawenzel** [Darkosto/SevTech-Ages#222]
## Suggestion
Changing the barrel extension advancement in stage 1 to trigger when the extension is placed instead of crafted as this is already done to craft the Porcelain Heater in stage 0.

## Versions
- Minecraft 1.12.2
- Forge 14.23.0.2544
- Java x64 8u144
- Sevtech-Ages Alpha 8

**Comment by Darkosto** [comment]
Changed!
