### ISSUE TITLE
Suggestion: Add books to Bibliocraft bookshelf whitelist

### ISSUE THREAD

**Issue by professorkintosh** [Darkosto/SevTech-Ages#2223]
## Issue / Bug
This is just my suggestion to add a couple items to the white list for the Biobliocraft bookshelf (line 84 of the bibliocraft.cfg).

## Expected Behavior
The following two books (I've only gotten to Age 3 so far) are not able to be placed in the Bibliocraft bookshelf:
- Totempedia (Totemic)
- Field Manual (Geolosys)

## Possible Solution
Change line 84 of the  _bibliocraft.cfg_ to read:

> S:AllowedBooks=book, map, journal, plan, thaumonomicon, necronomicon, lexicon, print, notes, spell, library, tome, encyclopedia, field, manual, totempedia

## Context
I just hate to not be able to add books to the bookshelf when it is in the pack.

## Client Information

* Modpack Version: 3.0.6
* Java Version: 8.171
* Launcher Used: Twitch

* Memory Allocated: 4Gb

* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: No
* Optifine Installed?: Negatory

**Comment by artdude543** [comment]
This was already completed and in a closed issue. Please check prior to making issues!
