### ISSUE TITLE
Immersive petroleum motorboat

### ISSUE THREAD

**Issue by kaberial** [Darkosto/SevTech-Ages#2224]
## Issue / Bug

Immersive petroleum motorboat seem to crash my game back to log in
## Expected Behavior

Me travling via boat without problems.

## Steps to Reproduce (for bugs)

1.Make motorboat
2.Fuel motorboat with gasoline
3.Hop on and ride to crashdom.

## Context

I never made a motorboat so I made one to try it out, but to only find that I crash as soon  took off. Now I cant log in without crashing back to sign in screen .

## Logs

* Client/Server Log:
* Crash Log :https://pastebin.com/tb2iQW5R

## Client Information

* Modpack Version: 3.0.6
* Java Version:
* Launcher Used: twitch

* Memory Allocated: 6400mb

**Comment by artdude543** [comment]
This is resolved in 3.0.7
