### ISSUE TITLE
Coal/Quartz Dupe w/ combiner

### ISSUE THREAD

**Issue by syrun97** [Darkosto/SevTech-Ages#2225]
## Issue / Bug

coal and quartz is dupable in combiner and other machine
## Expected Behavior

no dupe
## Possible Solution

change combiner recipe to 7 coals per coal ore/ 6 quartz per quartz ore?
## Steps to Reproduce (for bugs)

Coal:
1.Crush coal in Integrated dynamics mechanical sqeezer
2.combine coal in combiner
3.???
4.Profit!
Quartz:
1.Enrich ore to quartz
2.Combine them on netherrack
3.???
4.Profit!

## Context

![2018-05-05_16 28 05](https://user-images.githubusercontent.com/19798397/39660846-4cb5be6e-5082-11e8-9ab4-71cd08f154ec.png)
![2018-05-05_16 28 08](https://user-images.githubusercontent.com/19798397/39660848-52e64e3e-5082-11e8-97ae-2b9b02842944.png)
![2018-05-05_16 28 27](https://user-images.githubusercontent.com/19798397/39660850-57778260-5082-11e8-9021-00ac7419a742.png)
![2018-05-05_16 28 15](https://user-images.githubusercontent.com/19798397/39660851-5a8805a6-5082-11e8-899f-b33795cae890.png)

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:3.0.6/ disabled AESTHETIC mods
* Java Version:
* Launcher Used:

* Memory Allocated:5G

* Server/LAN/Single Player:single
* Resourcepack Enabled?:vanilla
* Optifine Installed?:nope

* Additional Content Installed?:nope

**Comment by artdude543** [comment]
- Integrated dynamics machines have had a tonne of recipes removed for 3.0.7 including the ore mentioned in this issue.
- Quartz is now 1 to 6 with the 3.0.7 update.
- Combiner now has most recipes removed as it's not the style of the pack. But it may come back at some other stage in the pack.
