### ISSUE TITLE
Arc Furnace Invar Recipe Not Correct

### ISSUE THREAD

**Issue by PsyberMind** [Darkosto/SevTech-Ages#2226]
## Issue / Bug
Arc Furnace JEI Recipe for Invar not working, Ingots not accepted on Right side of GUI

## Expected Behavior
According to JEI - 2 Iron Grit + 1 Nickel Grit = 3 Invar in the Arc Furnace, or 2 Iron Grit, and 1 Nickel Ingot

## Possible Solution
Ensure Invar Recipe is correct for Arc Furnace

## Steps to Reproduce (for bugs)

Add 2 Iron Grit on the left side of the GUI, 1 Nickel Grit on the right, Iron Smelts back into Ingots, Nickel isn't touched.

Nickel Ingots are not accepted on the right side of the Arc Furnace

Add 2 Iron, One Nickel to left side, both smelt to individual ingots

## Context

Just trying to build the Oxygen Collector for My Moon Mission

## Client Information

* Modpack Version: 3.0.6
* Java Version: 1.8
* Launcher Used: Twitch Pack ported to MultiMC

* Memory Allocated: 8GB

* Server/LAN/Single Player: SSP
* Resourcepack Enabled?: Faithful32
* Optifine Installed?: Yes, No Shaders

**Comment by artdude543** [comment]
This has been changed in 3.0.7 to using ingots as it's a recipe conflict which we can't easily resolve due to the mod compat.
