### ISSUE TITLE
Duplicating oil with BC Factory Tank and distillery

### ISSUE THREAD

**Issue by ShadowTheAge** [Darkosto/SevTech-Ages#2228]
## Issue / Bug
You can fill BC factory tank with oil, break it to get oil shards, and then use these shards to fill the distillation tower. Distillation tower will be filled with more oil than there is in a shard. 
Video: https://youtu.be/Dl4PCHtlP9c

## Expected Behavior
You don't get more oil than before

## Possible Solution
Let BC tank keep fluids instead of dropping shards? Or just void the fluid?

## Steps to Reproduce (for bugs)
1. Craft a BC factory tank, get a bit of oil in it
2. Break the tank, get fragile oil shards (works fine on 165mB and 500mB, does NOT work on 15 mB as distillery does not accept them)
3. Put a shard in the distillery. You may need to reopen the screen.

## Logs
* Server Log: https://gist.githubusercontent.com/ShadowTheAge/4b76a0d77bba55eb4c8ea4e2f9f46593/raw/0eb41b192e3fdbf03fa504325c02a46f1b3f5791/log

## Client Information

* Modpack Version: 3.0.6
* Java Version: 1.8.0.172 (64 bit)
* Launcher Used: Twitch
* Memory Allocated: 12 GB
* Server/LAN/Single Player: LAN (127.0.0.1)
* Resourcepack Enabled?: No
* Optifine Installed?: No

## Server Information
* Java Version: 1.8.0.172 (64 bit)
* Operating System: Windows 10 64bit
* Memory Allocated: 8 GB
* Hoster/Hosting Soultion: Local (127.0.0.1)
* Sponge (Non-Vanilla Forge) Server?: No
* Additional Content Installed?: No

**Comment by justinrusso** [comment]
https://github.com/Darkosto/SevTech-Ages/issues/1602
