### ISSUE TITLE
Ghost ember shard/crystals

### ISSUE THREAD

**Issue by scootz** [Darkosto/SevTech-Ages#223]
Ghost Ember shards/crystals are left behind after the real items are picked up both with mechanical means (hopper) or person.  Quit to main menu/single player menu and re-enter the game, those same ghost shards/crystals are gone.
![2017-11-27_13 00 08](https://user-images.githubusercontent.com/574344/33281516-83cfa194-d373-11e7-9ac5-9e6866db9fdf.png)

**Comment by Shoji22** [comment]
they came from the dung pipe it happens with other items too

**Comment by scootz** [comment]
This bug appears to be 'fixed' as I've not seen any ghost shards in 1/2 hour or so of watching what happens.
