### ISSUE TITLE
Quark Suggestion: invert inventory chest button

### ISSUE THREAD

**Issue by MissPotato** [Darkosto/SevTech-Ages#2231]
Quark adds a button similar to the Terraia button to deposit to a chest. However, this deposits everything in your inventory to the nearest chests. However, there is a config option to invert this button so that by default it will only merge items that already exist in the chest.

While this can be achieved by holding shift and pressing the button, I find merge is used vastly more often than direct depositing.

**Comment by Jandakast** [comment]
Updated for 3.0.7
