### ISSUE TITLE
Clay Kiln Visual Bug with Dung Pipe

### ISSUE THREAD

**Issue by TheMingo888** [Darkosto/SevTech-Ages#2232]
## Issue / Bug

When automating the clay kiln [Primal Tech] with a dung pipe (to avoid using the flame grilled wopper), the last item cooked inside drops out of the dung pipe as expected, but the output visually appears to still be inside the clay kiln. However, this is purely visual and cannot be taken out, and one can easily insert a new item to remedy the problem until it too finishes and the dung pipe pulls it out.

## Expected Behavior

The clay kiln should appear empty after it has finished processing all inputs, and after the dung pipe has emptied it.

## Steps to Reproduce (for bugs)

1. Place a clay kiln over a permanent fire, and attach a dung pipe to the rear (my setup has it dropping into a hopper that leads to a chest).
2. Place any cookable item into the kiln (e.g. cobblestone) and wait.
3. Notice that the result (e.g. stone) drops out of the dung pipe, but the result still appears to be inside of the kiln. Notice that you cannot take this out as it is not actually there.

## Context

Not a major issue, just an aesthetic annoyance.

## Client Information

* Modpack Version:
* Java Version: 1.8.0_161
* Launcher Used: Jar (through Twitch)

* Memory Allocated: 7 GB

* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by Targren** [comment]
I've seen the same behavior with the flame hopper as well.

**Comment by Jandakast** [comment]
I have reported this to the mod dev. Since this is only a visual bug I am closing the issue. If/when this is fixed in the PrimalTech mod it will be added to a future release of SevTech.  

https://github.com/vadis365/PrimalTech/issues/20
