### ISSUE TITLE
Gamemode reset to survival.

### ISSUE THREAD

**Issue by TractoBoy** [Darkosto/SevTech-Ages#2234]
## Issue / Bug
Upon login, game mode keep resetting to survival. I'd like to keep the creative mode if that was my last mode before disconnection. 

I'm guessing it isn't a bug, but rather a config option because of the difference between single/multiplayer.

## Expected Behavior

Keep the previous mode upon re-login.

## Steps to Reproduce (for bugs)
It looks like it only work with a dedicated server. Opening a SP to LAN doesn't revert the gamemode back to survival.

1. Go into creative.
2. Optional : fly 50-100 blocks up
3. Delog (or get D/C, if your connection is playing tricks as mine likes to do)
4. Relog, you lose creative
5. Optional, if you flew upward : enjoy the free fall and death.

## Context

I sometimes pop into creative in my world to explore / quickly go back to my grave.
Today I was creating ingame map (the vanilla map) to create an array of map on a wall. 

## Client Information

* Modpack Version: 3.0.6
* Java Version: 1.8, u121
* Launcher Used: MultiMC

* Memory Allocated: 6 GB.

* Server/LAN/Single Player: Server (on a dedicated server, but even with a fresh server on my own computer)
* Resourcepack Enabled?: no
* Optifine Installed?: no

## Server Information
* Java Version: 1.8
* Operating System: Linux on the dedicated server, Windows 10 on my own computer.
* Hoster/Hosting Soultion: OMGServ
* Sponge (Non-Vanilla Forge) Server?: the 3.0.6 server pack from CurseForge.

* Additional Content Installed?: no.

**Comment by Jandakast** [comment]
Just created 5 different worlds in Survival, changed to creative, flew up in the air, left the worlds and then reentered the world and I was still in creative. I also rebooted the game  before reentering the last 2 worlds. I don't think this is a pack issue.

**Comment by TractoBoy** [comment]
Have you done it using an "external" server ? (as in, not the internal one when playing solo)

Because the problem doesn't appear in single player. 
Here's a video demonstrating the 3 tests I've made yesterday (video recorded today) : https://youtu.be/uwi4CqGZTSg

1. fresh SP world, no problem. 
2. same SP world, open to lan, no problem
3. fresh MP world, problem

Server is hosted on my computer (and was booting when I created the SP world, hence the long time).

**Comment by sylvermist** [comment]
basic vanilla minecraft server properties has both a gamemode config and a force-gamemode config.  if the gamemode config is set to "0" (survival), you will always connect as survival......

**Comment by TractoBoy** [comment]
That was it : in server.properties, the option "force-gamemode=true" is set. It's the first time I've seen it set by default. 

Turning it off allow me to stay in creative after disconnection. Thanks sylvermist !

**Comment by sylvermist** [comment]
you're welcome

**Comment by artdude543** [comment]
The setting is set to true by default is intentional design, and won't be changed. You are free to modify the settings after the fact.
