### ISSUE TITLE
Steel Nuggets and Hoppers

### ISSUE THREAD

**Issue by tapegreen** [Darkosto/SevTech-Ages#2238]
Issue / Bug
Putting Steel Nuggets into a metal press with the 3X3 via hopper doesn't work. ( I'm using the syrormite Hopper BTW, works with all other recipes so far)

Expected Behavior
The recipe works fine if i drop the nuggets onto the conveyor belts but not when I use a hopper

Steps to Reproduce (for bugs)
Put a syrormite hopper connected to metal press with a 3x3 Compressor

**Comment by ferrium42** [comment]
The hopper don´t work with recipe with multiple items cause he drop one item at time, you need add one more conveyor belt , then it works

**Comment by artdude543** [comment]
You need to use more than one input for it to work or use a dropper.
