### ISSUE TITLE
Dyeing wool was removed from cauldron in 3.0.7

### ISSUE THREAD

**Issue by Muddr** [Darkosto/SevTech-Ages#2239]
## Issue / Bug

Being able to dye wool in the cauldron was removed making the only way to get dyed wool is to dye a sheep and shearing it for fleece.

I believe this is what was changed.
```
minecraft\config\betterwithaddons.cfg line 579
        # Wool can be dyed in batches of 8 in a cauldron and bleached with potash.
        B:DyeInCauldron=false
```

## Expected Behavior

An easier way to dye wool.

## Context

Being able to dye wool should be easier in later ages. 

![javaw_2018-05-06_05-21-09](https://user-images.githubusercontent.com/1361860/39672094-b861ace4-50f1-11e8-9577-11bbaaccd669.png)

## Client Information

* Modpack Version: 3.0.7.6 & 3.0.7.12
* Java Version: 1.80 171 64bit
* Launcher Used: MultiMC using zip

* Memory Allocated: 8gb

**Comment by Jandakast** [comment]
I unintentionally turned that option off when disabling the new Dyed Terracotta, Glass, and Fleece recipes. Re-enabled in dev.
