### ISSUE TITLE
Internal Exception when loading world

### ISSUE THREAD

**Issue by cookies934** [Darkosto/SevTech-Ages#2241]
## Issue / Bug
Anytime i load the pack for the first time and join the server i get "Internal Exception: java.io.IO.exception: an existing connection was forcibly closed by the remote host" . I can click back to server list and load it up again and it works. No crash log is created to give you.

## Client Information
* Modpack Version: 3.0.6
* Java Version:  8 update 171
* Launcher Used: Twitch

* Memory Allocated: 6GB

* Server/LAN/Single Player: Server
* Resourcepack Enabled?: What comes standard
* Optifine Installed?: No

**Comment by man-of-stone50** [comment]
On the changelog for sevtech server pack (https://minecraft.curseforge.com/projects/sevtech-ages/files/2549553#additional-files) it says that there is a known bug with being kicked back to the title or server screen after loading into your first world.
Apparently they are looking into it. You should be able to join the world back with no issues after first try.

**Comment by artdude543** [comment]
This is resolved in 3.0.7

**Comment by Zeskerr** [comment]
When is 3.0.7 going to be available?
