### ISSUE TITLE
Baykok bow

### ISSUE THREAD

**Issue by flamingram** [Darkosto/SevTech-Ages#2243]
## Steps to Reproduce (for bugs)

1.
![2018-05-06_13 57 03](https://user-images.githubusercontent.com/34726796/39677770-73e8153c-5135-11e8-9fa3-2c75f7d89f08.png)

2.so the bow i killed baykok and i cant use the bow

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:

* Memory Allocated:

* Server/LAN/Single Player:
* Resourcepack Enabled?:
* Optifine Installed?:

**Comment by flamingram** [comment]
btw im using latest version of pack

**Comment by PsyberMind** [comment]
Curious.. Did you kill Baykok, or did someone else? I seem to remember another issue here, or on the Totemic tracker where someone else killed him, and was able to use it, however the other person on the server wasn't able to. Did you get the advancement? If you did, you may have to revoke and re-grant the advancement for yourself (assuming you or someone else has server mod)

**Comment by Jandakast** [comment]
https://github.com/Darkosto/SevTech-Ages/issues/2179

**Comment by flamingram** [comment]
yes we both ahve it

**Comment by flamingram** [comment]
killed it 3 times
