### ISSUE TITLE
Game Breaking bug. Needs an immediate hot fix!

### ISSUE THREAD

**Issue by Arkene** [Darkosto/SevTech-Ages#2244]
## Issue / Bug
This huge game breaking bug is resulting in the nutritional values not leveling as they should do. One of the fruits in the game is not increasing the fruit bar. 

## Expected Behavior
When eating tomatos or tomato based foods, i expect the fruit bar to increase, instead the vegetable bar is increasing.

## Possible Solution
reclassify tomatos as a fruit instead of the wrong classification as a vegetable. 

## Steps to Reproduce (for bugs)
Consume a tomato food item

## Context
The issue itself, not as much as you would think by the fact i've just spent 5 minutes writing this , its existance though means i have to put up with someone moaning about how tomatos are fruits not vegetables over discord.

## Logs
No crash log produced

## Client Information
* Modpack Version: 3.0.6
* Java Version: jre1.8.0_171
* Launcher Used: Twitch

* Memory Allocated: 8 gb

* Server/LAN/Single Player: Server
* Resourcepack Enabled?: no
* Optifine Installed?: no

**Comment by Espergium** [comment]
This isn't funny. Only use this github for actual bugs.
