### ISSUE TITLE
Issue when loading into Betweenlands  (1st time going into the dimension)

### ISSUE THREAD

**Issue by jestesared** [Darkosto/SevTech-Ages#2248]
## Issue / Bug
Upon going through the betweenlands portal the first time, the game crashed to desktop. When I reloaded the world, I was still in the overworld, inside the portal tree. When I tried to use the portal again, it gave me the betweenlands advancement, I saw the 'wilderness' text briefly and the corruption bar appear over my food/saturation, then it hard crashed back to desktop. When I tried loading a third time, it once again showed a blank screen, just the flash of text and the different GUI of the betweenlands before another crash. I'm not sure where I go from here...

## Expected Behavior
Since it seems needed for progression I hope there is a fix, or at least a way to get back to the overworld?

## Steps to Reproduce (for bugs)
Create the betweenlands portal and attempt going through it.

## Context
If nothing else I want to be able to get back to the overworld, and maybe there is a way to bypass using the betweenlands? Ideally I just want it to work as intended.

## Logs
* Client/Server Log: https://gist.github.com/jestesared/4873003e7da9bd83a6f5ca2e6afdf1b9
* Crash Log: There was no crash report generated that I could find. The last one was from almost 3 weeks ago.

## Client Information
* Modpack Version: 3.0.6
* Java Version: 1.8.0.171
* Launcher Used: Twitch Launcher
* Memory Allocated: 5Gb
* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by artdude543** [comment]
If there are no crash logs it's not a crash.

Also, your logs are not the full one. You'll need to use Gist to paste the entire file.
Please upload the entire log before this issue will be looked further into.
