### ISSUE TITLE
Issue with sticky pistons interacting with water blocks.

### ISSUE THREAD

**Issue by iamtheplatypus14** [Darkosto/SevTech-Ages#2249]
## Issue / Bug
Placing a sticky piston face down into moving water corrupted a save file.

## Expected Behavior
Building a mushroom farm using sticky pistons and water resulted in a game breaking bug when said pistons moved downwards and interacted with the water blocks. The idea was to have the pistons block the water streams, (used to transport mushrooms to a hopper) using a redstone signal. Dirt blocks would be moved by sticky pistons to allow a stream of water to move the uprooted mushrooms. I had one sticky piston placed without a dirt block underneath, when the piston moved downwards into the empty air block it resulted in the crash. When i tried to reload the save file it resulted in repeated CTD's. After using MCedit to remove said water blocks as well as reverting to level.dat.old i was able to restore my world and inventory.
I have not been able to reproduce this bug as of yet so hopefully it was a very rare occurrence.
"Looks like it could be an issue with PrimalCore or Forge, (hopefully not)?"

## Possible Solution
Using MCedit to remove said water blocks

## Context
About an hour or two trying to restore my world.

## Logs
https://pastebin.com/Sjtx2SMR

## Client Information

* Modpack Version: 3.0.6
* Java Version: Version 8 Update 171 
* Launcher Used: Curse / Twitch

* Memory Allocated: 8gb

* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: N/A
* Optifine Installed?: N/A

**Comment by iamtheplatypus14** [comment]
Just noticed that this issue might have been brought a couple weeks ago. If you dont plan on updating the pack soon a warning would be nice as i almost lost a couple weeks of work.

**Comment by artdude543** [comment]
This issue is resolved in 3.0.7
