### ISSUE TITLE
Loading TheBetweenLands for the first time on server

### ISSUE THREAD

**Issue by fufu87** [Darkosto/SevTech-Ages#2253]
Yes I have seen the threads written regarding this, but this is affecting one player only in the server (Not all the players)

## Issue / Bug

Player disconnected from the game and kicked to desktop when entering the portal 

## Expected Behavior
My friend tries to enter the portal, they get the on-screen message "Wilderness" and then the game boots her out and is stuck loading while switching dimensions. 

## Possible Solution
None known. 

## Steps to Reproduce (for bugs)

1.simply enter the portal

## Context
Trying to complete advancements for age 2 

## Logs

* Client/Server Log: 
After disconnection : https://pastebin.com/1YxkLr1Q
Latest: https://paste.ubuntu.com/p/tYx7NMB5gV/

* Crash Log: No crash log 

## Client Information

* Modpack Version: 3.0.6
* Java Version: 8.0.1710.11
* Launcher Used: Native 

* Memory Allocated: 4029

* Server/LAN/Single Player: Server
* Resourcepack Enabled?: No
* Optifine Installed?:No

**Comment by TheCyberBrick** [comment]
Try updating to Betweenlands v3.3.7 or update your graphics card driver. Some Intel graphics cards were crashing due to broken drivers and as of v3.3.7 there's a workaround.

**Comment by artdude543** [comment]
Yeah you can manually update the mod or this issue will be resolved in 3.0.7 but that's your only options currently.
