### ISSUE TITLE
Server v3.0.6 throws error(s) on start

### ISSUE THREAD

**Issue by VideoGamesUSA** [Darkosto/SevTech-Ages#2254]
## Issue / Bug
When I try to run the server I get this error in the console:

**Starting SevTech Ages Server...
A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:62)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:31)
Caused by: java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        ... 6 more**

## Expected Behavior
Runs ServerStart.bat after using the included custom installer (I opted to turn GUI back on since it wasn't working correctly).  Gets the previously stated message in the console.

## Possible Solution
Unaware of one.  I have tried everything I could think of.  I tried running it on a different computer (same error message).  I tried updating Java, and Windows, and the Forge version being used.  Nothing has worked.

## Steps to Reproduce (for bugs)

1. After extraction of the server v3.0.6 zip file, install the server using the custom .bat installer.
2. After taking the eula.txt file from another server, attempt to run the server with nogui still enabled.
3. If that doesn't seem to cause an issue, try removing "noguiexit" from ServerStart.bat
4. If that still doesn't seem to cause an issue, then I don't know.

## Context
Just ran the server and it wouldn't work correctly...

## Logs
**_I tried looking everywhere in the server folder, but couldn't find a server log nor a crash log.  Probably because the error occurred before the server could create one for the first time?_**

## Client Information
* Modpack Version: Server v3.0.6
* Java Version: 10.0.1
* Launcher Used: N/A

* Memory Allocated: between 512MB and 2048MB

* Server/LAN/Single Player: Server
* Resourcepack Enabled?: no
* Optifine Installed?: no

## Server Information
* Java Version: 10.0.1
* Operating System: Windows 10 Pro (10.0.17112 Build 17112)
* Hoster/Hosting Solution: From home PC
* Sponge (Non-Vanilla Forge) Server?: no

**Comment by TheCyberBrick** [comment]
Try updating to Betweenlands v3.3.7 or update your graphics card driver. Some Intel graphics cards were crashing due to broken drivers and as of v3.3.7 there's a workaround.

**Comment by artdude543** [comment]
Did you run the installer first? As that error is commonly known as missing libs. 

Also, make sure you're not over-allocating memory which you don't have on the system. Did you modify any other settings? If so make sure the min is lower than the max and are not going over the available memory.

This is not a server/pack issue tho. This is a system issue with the configs and how much Java can use on your system.

**Comment by VideoGamesUSA** [comment]
I have 32GBs of RAM on my system, I did not mess with the default memory numbers specified in the settings.bat file, and I did run the Install.bat file first.

**Comment by artdude543** [comment]
Change the values in the `settings.(bat/sh)` to the following and try again.

`1024M and 4096M` for both min and max.

**Comment by VideoGamesUSA** [comment]
Just did.  Same error message(s).

**Comment by artdude543** [comment]
Wait, your on Java 10?! You can't be using that at all. Drop back to the latest version of 8.

**Comment by VideoGamesUSA** [comment]
It was the latest version according to the updater...well that's odd (it's even what you download off of the website)

**Comment by VideoGamesUSA** [comment]
I'll drop back though

**Comment by VideoGamesUSA** [comment]
@artdude543 Problem solved.  Thank you so much!  I didn't even know that was a thing until now.

**Comment by artdude543** [comment]
Sorted! Thanks for checking/performing the changes :) Hope you have fun with the pack!

**Comment by exs1084** [comment]
same issue, I tried installing java 8 in addition to 10 and the bat can't find it, tried with 10 uninstalled and it still couldn't find the java 8.
