### ISSUE TITLE
Containment Chalice allows for Obsidian in Age 2

### ISSUE THREAD

**Issue by judicius** [Darkosto/SevTech-Ages#2256]
## Issue / Bug
Containment Chalice is used for Cobble Gen and allows for Obsidian in age 2.

## Expected Behavior
Not making Obsidian in age 2

## Possible Solution
Remove Obsidian as a possibility in age 2 or push the chalice to age 3

## Steps to Reproduce (for bugs)

1. two containment chalices, one with water one with lava
2. activate

## Client Information

* Modpack Version: 3.0.6
* Java Version: 1.8.0.171
* Launcher Used: Twitch

**Comment by LordHellscream** [comment]
You cannot use the obsidian until Age3, not sure why this is an issue.

**Comment by judicius** [comment]
just a heads up didn't see this in changelog
