### ISSUE TITLE
Astral Sorcery Enchanting is in Age 2

### ISSUE THREAD

**Issue by judicius** [Darkosto/SevTech-Ages#2257]
## Issue / Bug
Astral Sorcery enchanting plates allow you to enchant in Age 2

## Expected Behavior
Enchanting isn't available till Age 3

## Possible Solution
Make crafting this a prestige advancement or push it back an age

## Context
Astral Sorcery also allows you to enchant things normally unenchantable

## Client Information

* Modpack Version: 3.0.6
* Java Version: 1.0.8.171
* Launcher Used: Twitch

**Comment by artdude543** [comment]
This is intended for the pack.
