### ISSUE TITLE
Heatscar Spider Jockey attacking itself

### ISSUE THREAD

**Issue by Stifling-Bossness** [Darkosto/SevTech-Ages#2261]
## Issue / Bug
Heatscar spider jockey hitbox is a little wonky, and when the skeleton tries to shoot, it will hit the heatscar spider and they'll try to attack each other.

## Expected Behavior
To work like a regular spider jockey

## Possible Solution
Spawn skeleton higher on the spider, or lower heatscar spider hitbox.

## Steps to Reproduce (for bugs)
Spawn a heatscar spider jockey and aggro it.

## Context
Not a big deal, and kinda funny when it happens.

## Logs
* Client/Server Log: https://gist.github.com/Stifling-Bossness/8a5bfbeb26539e090f5b21eefa783dbd

## Client Information
* Modpack Version: 3.0.6
* Java Version: 1.8.172
* Launcher Used: Twitch
* Memory Allocated: 8GB
* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: Yes, Faithful 32 Modded Edition
* Optifine Installed?: No

**Comment by Stifling-Bossness** [comment]
Also took some screenshots, not sure how useful they'll be: https://imgur.com/a/704Nu6i

**Comment by artdude543** [comment]
This is just a quirk with the mod and how it's set up the entities. If anything this can be reported directly to the mod author for the mod. It does not affect the modpack gameplay or creates a bug. Just a funny bug. So if you feel the need you can create an issue on the mods own tracker for them too look into it! 🙂
