### ISSUE TITLE
Unable to repair Manyullyn armor

### ISSUE THREAD

**Issue by Stifling-Bossness** [Darkosto/SevTech-Ages#2262]
## Issue / Bug
Unable to repair Manyullyn Armor in an anvil.
[https://imgur.com/a/FcwH72I](url)
## Expected Behavior
Be able to repair Manyullyn Armor.

## Possible Solution
It seems to be missing the recipe to increase the durability when combined with a manyullyn ingot, so add that and we're golden.

## Steps to Reproduce (for bugs)
Damage some Manyullyn armor, attempt to repair in anvil with a manyullyn ingot.

## Context
I had enchanted my Manyullyn armor, and went to repair it only to find that I couldn't. This is pretty bad for me, as I have invested pretty heavily into this armor under the assumption that I could repair it.

## Client Information
* Modpack Version: 3.0.6
* Java Version: 1.8.172
* Launcher Used: Twitch
* Memory Allocated: 8GB
* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: Yes, Faithful 32 Modded Edition
* Optifine Installed?: No

**Comment by artdude543** [comment]
![image](https://user-images.githubusercontent.com/1885466/39791018-09b06dba-5331-11e8-8a5c-c8ded42bf3ad.png)

This is resolved in 3.0.7
