### ISSUE TITLE
Takes Too Long To Load Or Doesn't At All

### ISSUE THREAD

**Issue by YaBoi132** [Darkosto/SevTech-Ages#2264]
## Issue / Bug
   
      Takes about 1.5 hours to go through the loading screen, and, so far, I've waited for 4 hours for a new world to start up but still nothing. 

## Expected Behavior

     During the world startup, the game doesn't crash or anything, it just keeps loading. I've checked the processes and it registers that it is doing something, but nothing appears to be happening. The part of the loading screen that takes the most is the uploading of mipmap textures.

## Possible Solution
  Possibly find, and fix/optimize the mods that are causing the most problems.

## Steps to Reproduce (for bugs)

1.   Startup the MineCraft Instance
2.   Wait

## Context
    The issue affected me because I cannot actually play the modpack if the world never loads. I also would not want to have to startup the modpack the day before to be able to play it, if that is what is necessary. 
    If people can't play the game, the wont recommend the game to others, reducing plays and feedback.

## Logs

* Client/Server Log:  (Not sure which one, so i picked the most recent one)  https://pastebin.com/XqXg1pn2
* Crash Log:   https://pastebin.com/Q7zJee2V

## Client Information

* Modpack Version:   3.06
* Java Version:    1.12.2
* Launcher Used:     Twitch
  
* Memory Allocated:     7,936 MB

* Server/LAN/Single Player: Singleplayer
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by justinrusso** [comment]
3.0.7 should save some performance improvements that should help with this. If it is still an issue, please resubmit the issue.
