### ISSUE TITLE
Shift-Clicking Propene into the Modular Machines Liquid Processor freezes game.

### ISSUE THREAD

**Issue by dalsio** [Darkosto/SevTech-Ages#2266]
## Issue / Bug

Attempting to shift-click a bucket of Propene into the Liquid Processor caused my game to hang. Waited for around 30 minutes and it did not unfreeze, so I had to terminate. I think I tried to shift click a bucket of naphtha into the Chemical Mixer earlier and it was fine (ie. nothing happened and no crash). I can't remember if I tried to put it in the liquid input or liquid output (both are tiny versions), but I feel like it was output because I remember it being to the left of the controller. I also don't know for sure if it crashes trying it in other slots or other Modular Machines.

## Steps to Reproduce (for bugs)

1. Create the Liquid Processor multiblock
2. Get a bucket of propene
3. Open the GUI of the liquid processor's Liquid Input/output
4. Shift-click the bucket of propene into it

## Context
Was/am trying to speed through the main advancements.

## Logs

* Client/Server Log: https://gist.github.com/dalsio/f5627365a79b5eea46e56f9592b7db66
* Crash Log: Didn't produce one, afaik

## Client Information

* Modpack Version: 3.0.6
* Java Version: 1.8.0.171
* Launcher Used: Twitch launcher, modified to use the latest version of Java

* Memory Allocated: 4gb

* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by artdude543** [comment]
Fixed in 3.0.7
