### ISSUE TITLE
Kicked out whenever world first loads/ whenever going between dimesnions

### ISSUE THREAD

**Issue by jestesared** [Darkosto/SevTech-Ages#2268]
## Issue / Bug
Whenever I start my world, or whenever I go between dimensions (Twilight/Betweenlands) it always gives a 'Internal Exception: java.nio.channels.ClosedChannelException'

## Expected Behavior
Besides the world shutting down every time this happens, if I'm able to finally get in, sometimes after many instances of the shutdown, I'm very far away from the portals. I've been in the top of the twilight canopy when I come back, and in the bottom of the Betweenlands Caverns. Then the problem is since it happens every single time I cross dimensions, it just happens more when I return to the overworld, usually sticking me in a wall, again, and it still can take 5 or 6 times trying to log in.

## Possible Solution
Before I updated my version of the Betweenlands to the latest, I couldn't even get there at all. So now the problem is specifically when starting the world, and when crossing dimensions. I haven't gotten to that point yet, but I assume it will also happen with the Nether and End.

## Steps to Reproduce (for bugs)
? I'm not sure? Like I said, its when I start the pack and go through dimensions, things which are kind of essential, so I'm not sure if something is just wrong for me.

## Context
It's basically impossible to progress. Having to spend upwards of 20-30 minutes and 4-6 attempts every dimension crossing, it gets really discouraging.

## Logs
* Client/Server Log: https://gist.github.com/jestesared/906b9b28341da6597a3f3026483f3a14
* Crash Log: No crash log, since the world shuts itself down each time. Near the end of the latest.log it says  "The state engine was in incorrect state ERRORED and forced into state SERVER_STOPPED. Errors may have been discarded."

## Client Information
* Modpack Version: 3.0.6
* Java Version: Version 8 Update 171
* Launcher Used: Twitch Launcher
* Memory Allocated: 5Gb
* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by justinrusso** [comment]
https://github.com/Darkosto/SevTech-Ages/issues/1671
