### ISSUE TITLE
[A8] Primal Tech Stone Mallet

### ISSUE THREAD

**Issue by Dawenzel** [Darkosto/SevTech-Ages#227]
## Bug/Issue
When the Stone Mallet breaks it gives off the default particles(black and pink squares). This also happens when only Primal Core and Primal Tech are in an instance. 

## Versions
- Minecraft 1.12.2
- Forge 14.23.0.2544
- PrimalTech 0.2.93
- Java x64 8u144
- Sevtech-Ages Alpha 8

**Comment by Darkosto** [comment]
I'll see if @vadis365 can take a look. Thanks

**Comment by vadis365** [comment]
should be fixed in 0.2.96
