### ISSUE TITLE
(Suggestion) Luminous crafting rework

### ISSUE THREAD

**Issue by PrimeEi8ht** [Darkosto/SevTech-Ages#2270]
Astral Sorcercy's luminous crafting table is currently accessible by a ritual in Abyssal Craft. Seeing as how Abyssal is based on a darker theme, Astral Sorcery seems out of place to me. 

Instead, Astral Sorcery and its components would be find able out in the world, but located under oceans, simulating a lost city of Atlantis feel. Signs of a ruin should appear like an ore sample, in that it would not unlock until Age 2.

Before worrying if players can mine, the Totemic mod gives the ability to mine and breathe underwater normally.

**Comment by artdude543** [comment]
All recipes were done with thought behind them. In regards to AS Dark wanted people to explore other mods in the pack and to force a progression tree. To which Abyssal Craft fit the needs for crafting items to progress.

The pack already has a tonne of RNG and we don't want to add more which could put players off. But the recipes won't be changed as this it the intention from the get-go for the modpack.

But thanks for making an issue and explaining your thoughts on the issue.
