### ISSUE TITLE
Keep crashing randomly since last Java update

### ISSUE THREAD

**Issue by Vavousaphir** [Darkosto/SevTech-Ages#2271]
I have no clue what is happening, since couple of days i'm crashing randomly in the world, since I started the pack I had no issue and never crashed. The only think I think of is since I updated Java to the build 1.8.0_171 but ingame it says 1.8.0_25, with Java launcher with the twitch launcher i'm at latest update "1.8.0_171". I tried using the native launcher but same result with less crash. It's just 

Java who stop working at all

There is also another bug minor it's when i'm using Java launcher and when i'm connecting to a server i'm always disconnected once after charging a first time, with the native launcher it never happend. Never bothered me so I don't really care about that x).

I have no graphic card update.

Intel Core I7-6700 CPU 3.40 GHz, 16 go RAM

If you want anything tell me :/

**Comment by Vavousaphir** [comment]
Not sure if I Fixed it but I reinstalled the correct java update, if someone else has this issue try it ! don't update java ha !

**Comment by Vavousaphir** [comment]
Still happening :/ less but still, seems to be more happening when my friend is not around in the world, I dunno maybe my CPU is dying :/

**Comment by artdude543** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

Thanks again for reporting, and we hope you enjoy the pack!
