### ISSUE TITLE
Betweenlands mobs not spawning in Hunting Dimension after changing biome

### ISSUE THREAD

**Issue by ParadoxBomb** [Darkosto/SevTech-Ages#2275]
## Issue / Bug

Changing a chunk in the Hunting Dimension to `betweenlands:coarse_islands` using Creeping Moss will not allow Betweenlands mobs to spawn; instead Abyssalcraft mobs will spawn, including Shoggoths (!)

## Expected Behavior

Betweenlands mobs should spawn in the Betweenlands biome

## Possible Solution

I see two options: 
1) Blacklist Betweenlands biomes from Creeping Moss
2) Whitelist the Hunting Dimension as a dimension where Betweenlands mobs are allowed to spawn (assuming this is possible)

## Steps to Reproduce (for bugs)

1. Go to Betweenlands with Creeping Moss in hand, use it to set the Creeping Moss to `betweenlands:coarse_islands`
2. Change one or more chunks in the Hunting Dimension using the Creeping Moss and observe Coralium Zonbies, Ghouls, and Shoggoths start to naturally spawn

## Context

I was attempting to set up a farm in the Hunting Dimension to collect Wight Hearts for the Animator.

## Logs

No logs are available for this kind of issue, as it has to deal more with configuration and mod interactions

## Client Information

* Modpack Version: 3.0.6
* Java Version: 1.8.0.171
* Launcher Used: Twitch

* Memory Allocated: 7168 MB

* Server/LAN/Single Player: Server
* Resourcepack Enabled?: no
* Optifine Installed?: no

## Server Information
* Java Version: 1.8.0.171
* Operating System: unknown
* Hoster/Hosting Soultion: HavocHost
* Sponge (Non-Vanilla Forge) Server?: no

* Additional Content Installed?: n/a

**Comment by ParadoxBomb** [comment]
Further testing has shown this to also occur with other Betweenlands biomes.

**Comment by Jandakast** [comment]
The Betweenlands mobs can only spawn in the Betweenlands dimension. This is intentional.
