### ISSUE TITLE
Astral Sorcery Internal Progression

### ISSUE THREAD

**Issue by Azeranth** [Darkosto/SevTech-Ages#2276]
I am trying to advance through Astral Sorcery in age 2 right now. I've completed "Filling in the Gaps" and am trying to craft my light well. I have enough starlight, over half full, and a resonating wand but the recipe won't even display in the table. I have no way to use the luminous crafting table at all, can't even make marble in it. It just simply isn't working. There is no crash and I don't know what caused it, but I suspect it's linked to the internal progression. I'd rather not cheat in knowledge scrolls, so please help me. 

Single player
Clean Install
Windows 10

**Comment by PsyberMind** [comment]
Make sure you are using Astral Sorcery Marble for the recipe - I ran into this earlier. You can just chisel it into AS Marble

**Comment by Delerium** [comment]
also make sure it has line of sight to the sky, nothing above it.

**Comment by Azeranth** [comment]
It does have line of sight, I tried it at both sea level in a plane and 2 blocks below the build height

**Comment by ChipmunkCraft** [comment]
Are you sure you are using Astral Sorcery marble and not "Raw Marble" from chisel? Raw Marble from Chisel will not work. You have to use the chisel to create Astral Sorcery marble.

**Comment by Delerium** [comment]
You don't actually need to "create" any of the marble anyway, as chisel has conversions for every type of astral sorcery marble.  The only one you need to create is sooty marble, and that recipe will accept non-AC "raw marble" as well as any other marble.

**Comment by theblackscreen** [comment]
Type "/astralsorcery progress" and see what is your progress tier. If it's still discovery, you need to progress until you're able to craft the recipe.

**Comment by Azeranth** [comment]
It is still Discovery, how do I solve this? Did I make a mistake in my progression?

**Comment by theblackscreen** [comment]
Type this: 
"/astralsorcery research playername BASIC_CRAFT" , where playername is your player name XP.

I have no idea why this is happening, this is probably a bug. If it continues to happen, then you can type 
"/astralsorcery research playername all", 
or
"/astralsorcery research playername reaserch_enum" where research_enum is on of the following:
-DISCOVERY
- BASIC_CRAFT
- ATTUNEMENT
- CONSTELLATION
- RADIANCE

this is from AS source code, found here: https://github.com/HellFirePvP/AstralSorcery/blob/master/src/main/java/hellfirepvp/astralsorcery/common/data/research/ResearchProgression.java

**Comment by artdude543** [comment]
Closing this as it's not a pack issue but user side. This is also **NOT** a bug with the mod either it's all been tested vigorously. You only need to miss one part of the progression for it to all not work.

So go back over the book and ensure you have completed all the progression. But feel free to continue talking in the issue.

**Comment by Azeranth** [comment]
@artdude543 Can you make sure the "Closed" is marked "Solved" so that others with this issue can find it
