### ISSUE TITLE
Saw issues

### ISSUE THREAD

**Issue by simonjc72** [Darkosto/SevTech-Ages#2277]
I might be stupid, but I can not get the saw to build. Im at the stage where I need parchment. I added all the proper items in. Nothing shows up.

**Comment by technolem** [comment]
The BWM one with 3 types of gears? The bronze and copper gears look similar, you didn't confuse them did you?

**Comment by artdude543** [comment]
JEI will tell you what you need to craft to make the saw. Also, the saw needs to be on the ground somewhere with the shaft attached to a gearbox.

If you need further help you can view the BWM Wiki.
