### ISSUE TITLE
minecraft ore generation in the twilight fores

### ISSUE THREAD

**Issue by Shoji22** [Darkosto/SevTech-Ages#228]
i found in the twilight forest in the big caves minecraft ore see on the screenshot.
![2017-11-28_16 02 07](https://user-images.githubusercontent.com/33992639/33326713-f57f1b7a-d455-11e7-9db5-180e977db095.png)

im in the sevtech version alpha 8

**Comment by ALongStringOfNumbers** [comment]
That is default generation for the Twilight Forest. I am unsure if geolosis support was added for the Twilight Forest so maybe this default generation is intended, at least until some form of integration with geolosis is achieved.

**Comment by Darkosto** [comment]
That's intended. Thank you! :)
