### ISSUE TITLE
Starlight Infuser recipe missing

### ISSUE THREAD

**Issue by KilroyOfD00m** [Darkosto/SevTech-Ages#2281]
**Issue / Bug (TODO)**

Searched as a madman if anyone else had this issue but cant find anyhting. Ive tried to cheat my way to get all the things but doesnt help either. Im all out of ideas on how to get the starlight infuser recipe in my tome to show up, or progress at all.

**Expected Behavior**

Recipe to craft starlight infuser and astral sorcery progress

**Possible Solution**

no idea

**Steps to Reproduce (for bugs)**

Search like a madman for infuser and craft everything twice

Cry

**Context**

Trying to progress through sevtech

**Client Information**

    Modpack Version: 3.0.6
    Java Version: 1.8.0_161
    Launcher Used: Twitch Launcher (manual forced newer Java)

    Memory Allocated: 12 Gb

    Server/LAN/Single Player:Single
    Resourcepack Enabled?:Yes
    Optifine Installed?:Yes

**Comment by Jemsuper** [comment]
Have you looked in JEI? I've got the recipe there

**Comment by KilroyOfD00m** [comment]
@Jemsuper Ye its there but not in my astral tome and when i put all the correct items into the altar to craft it, it doesnt show up.

**Comment by KilroyOfD00m** [comment]
Its full, got 3 lenses working on it. It doesnt even show the required starlight needed. Cant even find it in my astral tome.

**Comment by elmatador316** [comment]
Have you unlocked the right chapter?  It's in the constellation chapter.

**Comment by artdude543** [comment]
You need to make sure you have progressed through AS correctly. Also, don't trust the books all the time as some recipes are hardcoded yet we have changed recipes so please refer to JEI most of the time.

The fact it's not showing you the required starlight suggests the recipe is wrong as the book could be wrong in comparison to the one in JEI, or your missing progression from the mod.

Please follow the steps above and this will resolve the issue. But the recipe works fine when you have followed AS correctly.
