### ISSUE TITLE
[Crash]Placing a bonsai tree ontop a wooden transport pipe crashs the game

### ISSUE THREAD

**Issue by TheCheif** [Darkosto/SevTech-Ages#2283]
## Issue / Bug
So today, i thought it was a smart idea, to put a bonsai tree onto a wooden transport pipe which is connected to a chest. Well I thought wrong. The Server now crashes everytime I try to restart it.

## Steps to Reproduce (for bugs)
1. Place a Chest
2. Connect it to a wooden transport pipe
3. Place a hopped bonsai thingie on top
4. Crash

## Logs
* Crash Log: https://pastebin.com/Dt80E9QN

**Comment by TheCheif** [comment]
Also i can't load my World any longer FeelsBadMan

**Comment by artdude543** [comment]
Fixed in 3.0.7
