### ISSUE TITLE
[A8] Skillable Road "Jump"

### ISSUE THREAD

**Issue by Dawenzel** [Darkosto/SevTech-Ages#229]
## Bug/Issue
After unlocking the trait Roadwalk from Skillable when walking/running on a grasspath blocks the player starts to automatically jump and even damage the player when landing. This also happens when only autoreglib and skillable are in the instance.

## Versions
- Minecraft 1.12.2
- Forge 14.23.0.2544
- Skillable beta 8
- Java x64 8u151
- Sevtech-Ages Alpha 8
This issue is persistent across Forge 14.23.1.2555 and Skillable beta 9 as well.

**Comment by Darkosto** [comment]
Removed from Skillable, thanks!

**Comment by Darkosto** [comment]
Leaving open to send to Vazkii.

**Comment by Dawenzel** [comment]
The issue is fixed with the release of `skillable-beta-10`, Thank you Vazkii.
