### ISSUE TITLE
IE Metal Press produces plates that are not oreDict with equivelent plates

### ISSUE THREAD

**Issue by MongoTheElder** [Darkosto/SevTech-Ages#230]
Tin ingots press into Vulpes Library tin plates
![2017-11-28_20 20 05](https://user-images.githubusercontent.com/29290246/33353147-591549ec-d47a-11e7-9ec6-f8b82634315e.png)

Bronze ingots press into another plate type that is restricted to Stage 4
![2017-11-28_20 20 07](https://user-images.githubusercontent.com/29290246/33353151-5c52ac3a-d47a-11e7-8d29-e2018f5561ae.png)

Other ingots produce either IE or ContentTweaker (platnum) plates as expected

Alpha 8, Twitch build

**Comment by Darkosto** [comment]
I'm going to give this one to @justinrusso since he's been working on OreDict edits. I'm fairly certain this will fall under his current project.

**Comment by justinrusso** [comment]
Shouldnt UniDict already be fixing this sort of issue?

**Comment by Darkosto** [comment]
Checked and good!
