### ISSUE TITLE
PrimalCore/Tech structure are most often incomplete in the world.

### ISSUE THREAD

**Issue by scootz** [Darkosto/SevTech-Ages#231]
PrimalCore/Tech structure are most often incomplete in the world.

![2017-11-28_17 44 50](https://user-images.githubusercontent.com/574344/33355122-1c68e684-d484-11e7-838f-0e11bf36ab30.png)

**Comment by Dawenzel** [comment]
I'm certain this is because the changes to the naming used for blocks. The structure used in Alpha 7 used `<primal:mud_brick_dry> <primal:mud_block_dry>` for it's walls, but these blocks are now referred to as  `<primal:mud_dried:metadata>`.

**Comment by Darkosto** [comment]
Yeah, that's exactly the issue. The mod made some big changes and it's still being fixed as we find the bugs.

**Comment by Darkosto** [comment]
Should be all fixed up. I went and looked at all the mud hut type structures and edited.
