### ISSUE TITLE
[A8] BWM axle recipe stage 2

### ISSUE THREAD

**Issue by Dawenzel** [Darkosto/SevTech-Ages#232]
## Bug/Issue
The recipe for the BWM axle is the same as in stage 1.

## Versions
- Minecraft 1.12.2
- Forge 14.23.0.2544
- Java x64 8u144
- Sevtech-Ages Alpha 8

**Comment by Darkosto** [comment]
Yes, that reminds me to edit the recipe to be a bit easier in stage 2. Thanks!
