### ISSUE TITLE
food can be eat when hunger is full

### ISSUE THREAD

**Issue by Shoji22** [Darkosto/SevTech-Ages#239]
you can eat thease items when your hunger is full. Is this a bug or a feature?

actuallyadditions:item_food:17
actuallyadditions:item_food:16
primal:wolf_meat_cooked
primal:horse_meat_cooked
primal:pigman_meat_cooked
primal:ovis_meat_cooked
primal:bear_meat_cooked
primal:llama_meat_cooked
primal:bat_meat_cooked

**Comment by Darkosto** [comment]
Yeah, this is actually not a big deal but thank you for letting me know! :)
