### ISSUE TITLE
Shoggoth Spawns / Den Generation

### ISSUE THREAD

**Issue by CrossMyDNA** [Darkosto/SevTech-Ages#24]
Lesser shoggoths don't seem to have a spawn cap. I was in a den for about a minute and they kept spawning, causing a ton of lag.

Their dens also seem to generate awkwardly on occasion, like in the middle of the water.

![2017-08-31_21 49 32](https://user-images.githubusercontent.com/31498349/29953617-cd1432b6-8e9f-11e7-9b4d-a55ef106eab1.png)
![2017-08-31_21 52 30](https://user-images.githubusercontent.com/31498349/29953618-cd149a3a-8e9f-11e7-91b9-99cc86040632.png)

**Comment by Darkosto** [comment]
Shinoow said it was fixed! The spawn thing, not the in the middle of the river thing :P
