### ISSUE TITLE
Astral Tome Recipe

### ISSUE THREAD

**Issue by Dr-Beanz** [Darkosto/SevTech-Ages#242]
When trying to craft the Astral Tome (which is required in advancement) the current recipe in Alpha 9 requires a book which is showing up as a restricted item in stage 1.

![astral tome](https://user-images.githubusercontent.com/34172797/33503736-bff66b46-d6dc-11e7-8225-deab81e3e626.png)

![astral tome 2](https://user-images.githubusercontent.com/34172797/33503773-e7acd2c4-d6dc-11e7-9194-3f75bfac437b.png)

**Comment by justinrusso** [comment]
This has to do with the Astral Sorcery mod still fully being staged to "two" inside `stage2.recipes.add.shaped.zs`. We'll need to remove that and ensure everything is staged properly in the mod afterwards.

**Comment by Darkosto** [comment]
Checked this out and it's now all staged correctly.
