### ISSUE TITLE
Copper plate to Copper Rod

### ISSUE THREAD

**Issue by scootz** [Darkosto/SevTech-Ages#243]
SevTech - Ages - Alpha 9

The stone anvil only accepts Immersive Engineering copper plate when attempting to make copper rods.  It doesn't accept any other form of copper plates.

![applicationframehost_2017-12-01_21-19-37](https://user-images.githubusercontent.com/574344/33510731-d8c754fe-d6dd-11e7-820d-1d7d5bdf176b.png)

**Comment by justinrusso** [comment]
May have been spawned in.. Just going to close this. From the looks of it (and tested) there shouldn't be a way of obtaining plates from embers
