### ISSUE TITLE
Chest shows restricted items when you are at the progression to craft it

### ISSUE THREAD

**Issue by ZeldoKavira** [Darkosto/SevTech-Ages#245]
## Instruction on how to do issues like your boy darkosto
Start new world, get to chest achievement, look at recipe
 ### Issue / bug
Recipe shows the wood as restricted items

**Comment by justinrusso** [comment]
Not all wood are restricted - Seems to be only chisel planks that are. Any other plank should work

TODO: What to do with the following in stage1.items
```
	<chisel:planks-acacia:*>,
	<chisel:planks-birch:*>,
	<chisel:planks-dark-oak:*>,
	<chisel:planks-jungle:*>,
	<chisel:planks-oak:*>,
	<chisel:planks-spruce:*>,
```
