### ISSUE TITLE
Ore Cluster visible on surface in Stage 0

### ISSUE THREAD

**Issue by MongoTheElder** [Darkosto/SevTech-Ages#246]
When wandering around in Stage 0, found an ore cluster visible on the surface
![2017-12-02_14 10 34](https://user-images.githubusercontent.com/29290246/33518883-bafcd9c0-d76a-11e7-8f15-bf4626dd5e60.png)

Alpha 9

**Comment by justinrusso** [comment]
Awesome. This seems like a new ore that was added, so great find :)

Will need to compare with the version in Alpha 8 to see what has been added since. [Geolosys changelogs](https://minecraft.curseforge.com/projects/geolosys/files)

**Comment by Darkosto** [comment]
Removed Zinc for the time being as it wasn't added into the pack or planned for.
