### ISSUE TITLE
Gear up is not behind Shake rattle roll

### ISSUE THREAD

**Issue by ZeldoKavira** [Darkosto/SevTech-Ages#248]
### Issue / bug
The achievement for gear up is not behind the achievement for Shake Rattle Roll even though you cannot created the stump needed for the buffalo needed for the gear until you do that achivement

**Comment by Darkosto** [comment]
![image](https://user-images.githubusercontent.com/10309699/33529118-0be02ca0-d83a-11e7-8616-da0363046259.png)

**Comment by Darkosto** [comment]
I think I understand what you are saying now.

Basically, the pack cannot have 1 line of progression and will have multiple "dead ends" and only allowed 1 parent. The way it's setup is for you to try another line of advancements if you cannot progress.

The way it's setup is intended and works well.
