### ISSUE TITLE
Drops in Early Game

### ISSUE THREAD

**Issue by CrossMyDNA** [Darkosto/SevTech-Ages#25]
I found a few drops that seemed like they shouldn't be available in the first stage. Not sure if these are intentional.

Magma Monsters:
- Magma cream (lava form)
- Obsidian (obsidian form, when touching/in water)

Faint Amaranth Plant:
- Glowstone

**Comment by Darkosto** [comment]
Notes for later:

add charcoal to drops


for the meantime: Drops are turned off and glowstone flowers are disabled.
