### ISSUE TITLE
Check all wood works in machines: Horse Power, BWM Saw, etc. Then add all to water power saw

### ISSUE THREAD

**Issue by Darkosto** [Darkosto/SevTech-Ages#251]

**Comment by justinrusso** [comment]
Just when I was going to suggest making this easy... only one of the three support CrT :(

**Comment by justinrusso** [comment]
Here's the list I tested in the Horse Chopping Block

The blank ones are ones that did not have a plank recipe.

Primal core has 2 logs, one of which gave a broken item as its result (`<primal:logs:1>`). There are 4 planks, but only 2 have matching logs. I noticed they're not all ore dicted either.

We currently ore dict just `<primal:planks:6>` which does not exist anymore. This would be a good replacement I think

```
//Primal Core
<ore:plankWood>.add(<primal:planks>);
<ore:plankWood>.add(<primal:planks:1>);
<ore:plankWood>.add(<primal:planks:3>);
<ore:plankWood>.add(<primal:planks:2>);
<ore:logWood>.add(<primal:logs>);
<ore:logWood>.add(<primal:logs:1>);
```

Log | Plank
-- | --
<minecraft:log> | <minecraft:planks>
<minecraft:log:1> | <minecraft:planks:1>
<minecraft:log:2> | <minecraft:planks:2>
<minecraft:log:3> | <minecraft:planks:3>
<minecraft:log2> | <minecraft:planks:4>
<minecraft:log2:1> | <minecraft:planks:5>
<abyssalcraft:dltlog> | <abyssalcraft:dltplank>
<abyssalcraft:dreadlog> | <abyssalcraft:dreadplanks>
<betterwithaddons:log_mulberry> | <betterwithaddons:planks_mulberry>
<betterwithaddons:log_sakura> | <betterwithaddons:planks_sakura>
<betterwithmods:blood_log> | <minecraft:planks:3>
<natura:nether_logs> | <natura:nether_planks>
<natura:nether_logs:1> | <natura:nether_planks:2>
<natura:nether_logs:2> | <natura:nether_planks:3>
<natura:nether_logs2> | <natura:nether_planks:1>
<natura:nether_logs2:15> | <natura:nether_planks:1>
<natura:overworld_logs> | <natura:overworld_planks>
<natura:overworld_logs:1> | <natura:overworld_planks:1>
<natura:overworld_logs:2> | <natura:overworld_planks:2>
<natura:overworld_logs:3> | <natura:overworld_planks:3>
<natura:overworld_logs2> | <natura:overworld_planks:4>
<natura:overworld_logs2:1> | <natura:overworld_planks:5>
<natura:overworld_logs2:2> | <natura:overworld_planks:6>
<natura:overworld_logs2:3> | <natura:overworld_planks:7>
<natura:redwood_logs> |  
<natura:redwood_logs:1> | <natura:overworld_planks:8>
<natura:redwood_logs:2> |  
<primal:logs> |  
<primal:logs:1> |  
<rustic:log> | <rustic:planks>
<rustic:log:1> | <rustic:planks:1>
<totemic:cedar_log> | <totemic:cedar_plank>
<totemic:stripped_cedar_log> | <totemic:cedar_plank>
<traverse:fir_log> | <traverse:fir_planks>
<twilightforest:magic_log> |  
<twilightforest:magic_log:1> |  
<twilightforest:magic_log:2> |  
<twilightforest:magic_log:3> |  
<twilightforest:twilight_log> | <minecraft:planks>
<twilightforest:twilight_log:1> | <minecraft:planks:1>
<twilightforest:twilight_log:2> | <minecraft:planks:2>
<twilightforest:twilight_log:3> | <minecraft:planks:1>
