### ISSUE TITLE
Looking at a fairy crashes game by casting a BlockPos value to a Boolean value.

### ISSUE THREAD

**Issue by OscarXcore** [Darkosto/SevTech-Ages#256]
- Look at a fairy. I'll wait. While in Stage 0 and in Creative. (Hint: It crashes the game to desktop, only every once and awhile)
- SevTech Alpha 9
- Uhhhh, look at a fairy? At night, stage 0, and in Creative.
- [Crash Logerino](https://pastebin.com/PEC1AdFy)
- I mean. I can record a video of the game crashing...

**Comment by Darkosto** [comment]
Just to be sure, this only happens in creative?

**Comment by OscarXcore** [comment]
Not too sure. I was in creative at the time.

**Comment by Darkosto** [comment]
Ahh, okay. I'll look into it some more and see what I can find out. Thanks!

**Comment by OscarXcore** [comment]
Darko, did I mention I love you? You take this so seriously. <3

**Comment by Darkosto** [comment]
It's an addiction.. I can't stop xD

**Comment by OscarXcore** [comment]
LUL Understandable. Have a great day.
