### ISSUE TITLE
Tree Stump Mining Speed

### ISSUE THREAD

**Issue by CrossMyDNA** [Darkosto/SevTech-Ages#26]
Several trees do not have a slower mining speed for the bottom log:

- Silverball
- Spruce
- Sakura 5495:3
- Maple
- Darklands oak
- Yew (Technically this one works since the very bottom log [underground] has a slower mining speed, but the one in line with the ground does not.)
- Eucalyptus
- Dark oak
- Amaranth wood
- Jungle
- Willow
- Robust twilight oak
- Tigerwood
- Dreadlands wood
- Ghostwood
- Twilight mangrove
- Darkwood
- Fusewood
- The slime trees, which may be an exception

**Comment by Darkosto** [comment]
I think I might just disable the stump thing because it seems to be more trouble than it's worth to add every modded log, especially since there isn't a whitelist to do so.

**Comment by Darkosto** [comment]
Disabled this for now. Thank you!
