### ISSUE TITLE
Planks Can't Fuel Fire Pit

### ISSUE THREAD

**Issue by CrossMyDNA** [Darkosto/SevTech-Ages#27]
Several planks can't be used as fuel in the fire pit:
- Sakura planks 5498:7
- Sakura planks 5903
- Redwood planks
- Sugi wood planks
- Ghostwood planks
- Olive wood planks
- Red cedar planks
- Darkwood planks
- Ironwood planks

**Comment by Darkosto** [comment]
All have been added to the list! Thank you!
