### ISSUE TITLE
Stone gear recipe conflict/confusion

### ISSUE THREAD

**Issue by MongoTheElder** [Darkosto/SevTech-Ages#270]
The stone gear used in the copper gear recipe in Stage 1 has two recipes, one using cobblestone (Buildcraft) and one using other stone variants (Tesla Core Lib). Only the Tesla Core Lib gear using non-cobblestone is valid for the copper gear recipe but both show up in JEI

Buildcraft Stone Gear
![2017-12-06_20 03 55](https://user-images.githubusercontent.com/29290246/33693392-a29bad58-dac0-11e7-9fac-b65485ff5adf.png)
![2017-12-06_20 03 57](https://user-images.githubusercontent.com/29290246/33693420-dba590b4-dac0-11e7-8bc1-20b41d81e810.png)

Tesla Core Lib Stone Gear
![2017-12-06_20 03 47](https://user-images.githubusercontent.com/29290246/33693400-ae8f0948-dac0-11e7-8703-21330a34b8ec.png)
![2017-12-06_20 04 02](https://user-images.githubusercontent.com/29290246/33693448-fe99a2cc-dac0-11e7-8e2a-ce5220aeaa75.png)

Alpha 9

**Comment by justinrusso** [comment]
Thanks! Buildcraft just got added in and I don't think has been touched at all, so that explains the second gear appearing..

**Comment by Darkosto** [comment]
All fixed up! Thank you!
