### ISSUE TITLE
[Potential Issue]Procelain Tank doesn't count toward the Smelter Tank advancement

### ISSUE THREAD

**Issue by MongoTheElder** [Darkosto/SevTech-Ages#274]
Don't know if this is something specific to my instance of Alpha 9:

Crafting the porcelain tank didn't trigger the Stage 2 advancement for Smelter Tank. Cheating in a Seared Tank satisfied the requirement. I have been seeing some odd behaviors in other places (the AS Journal has no crafting recipe) where the configs and scripts look correct. For example, the advancement script for Smelter Tank appears to correctly accept either item.
```
criteria = addCriteria("hasRock", "minecraft:inventory_changed")
criteria2 = addCriteria("hasRock", "minecraft:inventory_changed")
criteria.setItem("tcomplement:porcelain_tank")
criteria2.setItem("tconstruct:seared_tank")

setRequirements("any")
```

Alpha 9, Twitch build

**Comment by justinrusso** [comment]
The AS Journal is known, and should be fixed in dev. I think once youre in stage 2 the recipe should appear (not intended, but was the issue)

Are there any other odd behaviors?

**Comment by MongoTheElder** [comment]
The Porcelain Tank was the only other one I have found. Still progressing through Stage 2

**Comment by Dawenzel** [comment]
We found the issue. I didn't rename the second criteria to hasRock2 and the first criteria got overwritten by this mistake. This caused the advancement not to trigger when the porcelain tank was made.
