### ISSUE TITLE
Client crash 

### ISSUE THREAD

**Issue by DingoX3** [Darkosto/SevTech-Ages#28]
I cannot narrow it down to one single action or tool or click. Its just randomly crashing.  
Full crash report: https://pastebin.com/Kvb10Bzz

**Comment by DingoX3** [comment]
Screenshot of my inventory contents
![2017-09-01_01 48 23](https://user-images.githubusercontent.com/16032841/29956828-ae41734a-8eb7-11e7-9056-112e79d053c4.png)

**Comment by DingoX3** [comment]
Ive actually crashed 4 more times now. 
This crash makes no sense to me. Im doing completely different things each time. But each time i have chiseled some stone bricks in-world with a chisel and its not immediate but just randomly afterwards it crashes. Im beginning to think its an entity not an action.

**Comment by ZeldoKavira** [comment]
This is happening in the 'betterwithmods' mob drop lookup. Do you have a mobfarm? @Darkosto are you modifying mob drops?

**Comment by Darkosto** [comment]
I have changed mob drops and cleared a number of loot tables. I'll see if @primetoxinz knows a way to stop the crash if the tables are empty.

**Comment by primetoxinz** [comment]
should be fixed in BWM 2.0.9

**Comment by Darkosto** [comment]
Should be fixed, report back if you get it again :)
