### ISSUE TITLE
Add "Craftable" Tooltip To Every Chisel Block That is THE Block You Can Actually Craft

### ISSUE THREAD

**Issue by Darkosto** [Darkosto/SevTech-Ages#282]
Because SOME people can't do that or make the craftable one show up first xD

Right @Drullkus ?

**Comment by Drullkus** [comment]
:thonk: You didn’t submit this onto the Chisel bugtracker?

**Comment by Darkosto** [comment]
Nope! I wanted to give you a hard time about it 🌮

**Comment by Drullkus** [comment]
🐧

**Comment by justinrusso** [comment]
Could also make a way to add recipes to those items. The recipe will be under those that require chiseling, but when crafted, it returns the "base" block that would have normally have been crafted. May cause some confusion of "Wait, I got a different block from this craft!" though...

**Comment by Darkosto** [comment]
FIXED!
