### ISSUE TITLE
Some Vulpes library (libvulpes) metal recipes not properly removed

### ISSUE THREAD

**Issue by Jandakast** [Darkosto/SevTech-Ages#284]
Recipes for the following Vulpes library metals are not are not properly removed. The items are hidden from JEI but can be seen when looking at the uses of the correct ingots and blocks and cannot actually be crafted. 

<libvulpes:metal0:9> (Aluminum Block) 
<libvulpes:productingot:9> (Aluminum Ingot) 
<libvulpes:productnugget:9> (Aluminum Nugget) 

<libvulpes:metal0:4> (Copper Block) 
<libvulpes:productingot:4> (Copper Ingot) 
<libvulpes:productnugget:4> (Copper Nugget) 

<libvulpes:metal0:6> (Steel Block) 
<libvulpes:productingot:6> (Steel Ingot) 
<libvulpes:productnugget:6> (Steel Nugget) 

<libvulpes:metal0:5> (Tin Block) 
<libvulpes:productingot:5> (Tin Ingot) 
<libvulpes:productnugget:5> (Tin Nugget) 

![image](https://user-images.githubusercontent.com/19498789/33798666-d060d61a-dcea-11e7-8a6f-ee1dcdb1485f.png)

**Comment by justinrusso** [comment]
Yeah I dont know right now.. Clearly the lib is doing things when its not ideal to.

This extends to gears and basically everything they add crafting recipes for.

**Comment by Darkosto** [comment]
I'm going to tag @dmodoomsirius on this one as he may be able to help out.

**Comment by dmodoomsirius** [comment]
Zmaster, [10.12.17 16:55]
There might be a load order issue

Zmaster, [10.12.17 16:56]
AR registers a lot of it's material recipes on post init because I need to have collected all the forge ore registrations

**Comment by Darkosto** [comment]
Well, that's going to be a bit of an issue then. It's the one mod that can't be tweaked in terms of recipes then.

**Comment by zmaster587** [comment]
I can look into changing the load order or forcing it to load before whatever recipe tweaker you're using, or alternatively I could just dump normal recipes to an XML file like the machines.

**Comment by Darkosto** [comment]
We're using Craftweaker currently. Every other mod in the pack is currently being tweaked through a set of global scripts to handle oredictionary for recipes and machines. XML wouldn't be too much help for us as it would be the one mod to need to be handled uniquely.

**Comment by zmaster587** [comment]
I'll make sure it loads before Craftweaker then

**Comment by zmaster587** [comment]
Any luck with the new build?

**Comment by justinrusso** [comment]
Seems like recipes are being removed now. Thank you!

**Comment by zmaster587** [comment]
No problem!
