### ISSUE TITLE
Crash when picking up items in Ug-Ghast tower when near an Anti-Builder field

### ISSUE THREAD

**Issue by MongoTheElder** [Darkosto/SevTech-Ages#286]
When you are near an Anti-Builder field any items picked up cause the game to crash (logs attached). Other areas of the Ug-Ghast tower do not have any issues with item pick up.

[latest.log](https://github.com/Darkosto/SevTech-Ages/files/1546351/latest.log)
[crash-2017-12-10_21.02.12-server.txt](https://github.com/Darkosto/SevTech-Ages/files/1546352/crash-2017-12-10_21.02.12-server.txt)

Alpha 9, Twitch build
Minecraft 1.12.2
Forge-14.23.1.2555

**Comment by justinrusso** [comment]
Looks like this might be fixed in a new version of the mod: https://minecraft.curseforge.com/projects/the-twilight-forest/files/2505472 `Fixed a serious crash involving the Anti-Builder.`

**Comment by Darkosto** [comment]
Grabbed the version that fixes this and is in dev. Thank you!
