### ISSUE TITLE
Charcoal in the firepit

### ISSUE THREAD

**Issue by sindacrof** [Darkosto/SevTech-Ages#29]
Was trying to cook up some pork in a fire pit, when I added a spruce log on accident. It went into the slot you normally put the food. It then popped out a charcoal.

**Comment by davqvist** [comment]
Isn't this intended? It uses the normal furnace recipes. That is how i make charcoal all the time.

**Comment by sindacrof** [comment]
Not sure, but since coal itself is blocked, i'd imagine getting charcoal this early wasn't intended.

**Comment by Darkosto** [comment]
I haven't cleaned out the recipes for Charcoal from everywhere just yet.

**Comment by Darkosto** [comment]
Removed the ability to make charcoal in the firepit to unify the way that was intended.
