### ISSUE TITLE
Add Nuggets - Ingots, Ingots - Blocks in the Pneumaticraft Compression Chamber

### ISSUE THREAD

**Issue by Darkosto** [Darkosto/SevTech-Ages#293]
Provides Alternative Method for creating these items if players choose to do it.

**Comment by justinrusso** [comment]
We'll see how this ends up but.. should be working.

![image](https://user-images.githubusercontent.com/25138621/34073375-82684ef8-e266-11e7-8663-24cef2bc51fd.png)
![image](https://user-images.githubusercontent.com/25138621/34073378-8bde78cc-e266-11e7-85c4-8716f49e12fa.png)
