### ISSUE TITLE
Picking up a fire pit

### ISSUE THREAD

**Issue by Banage** [Darkosto/SevTech-Ages#296]
If you have a placed fire pit  with low grade charcoal in it and you shift-click to pick it up it shows you're holding an air block in your hand.  Stage 0

### Issue / bug
 - Explain the issue / bug as understandably as possible.
 - If possible add minecraft, forge, java and modpack version numbers for debugging (mod authors might need these).
 - If the issue/bug is recurring explain how it can be recreated (helps darkosto!).
 - If possible add error/crash log to [Pastebin](https://pastebin.com/) and link it here (if you dislike pastebin any other similar site is fine too).
 - If possible add a video/gif of the issue/bug (makes it easier for darkosto to understand you).

**Comment by justinrusso** [comment]
Probably best to just remove this from carryable?

**Comment by Darkosto** [comment]
Yeah, just add this to the Carry-on blacklist and it will be all fixed up!
