### ISSUE TITLE
Adjust recipes for AE/RS for Stage 4

### ISSUE THREAD

**Issue by justinrusso** [Darkosto/SevTech-Ages#298]
Check the recipes over if you'd like to ensure I listed everything, but I believe this is all that would need changing
- [x] Add recipes for AE presses since they are not obtainable (meteors dont exist)
- [x] Adjust AE Security Terminal recipe to not use diamond, storage cell, or ME chest
- [x] Adjust AE Biometric Card to not use engineer processor
- [x] Adjust RS recipes that use a diamond (Security Card, Network Card, Crafting Grid - They all use Adv Processor that has diamond, and Controller)
- [x] See if RS and AE silicon / printed silicon & silicon press should stay or can be removed and hidden

---
- [x] Modify enriched quartz iron 3 iron + 1 certus quartz
- [x] Shulker pearls instead of diamond
- [x] Remove silicons that exist, use raw silicon
- [x] Inscriber and solderer use fluix instead, make it like the inscribers, with quartz enriched (one mirrors other)
- [x] Remove RS solderer and processors, use all AE ones - same for cores
- [x] Anything that uses solderer uses AE inscriber or recipes
- [x] Do upgrades in inscriber
- [x] Quartz glass in arc furnace

**Comment by Darkosto** [comment]
Are all recipes converted to the new system yet?
