### ISSUE TITLE
Some Antique Atlas biome textures are very misleading.

### ISSUE THREAD

**Issue by RTHauke** [Darkosto/SevTech-Ages#301]
This is probably a mod issue.  I've found 2 biomes that are represented by textures in the Antique Atlas that are way off.

Crag (barren-rock, cold, extremely high mountain) appears to be a forest.
What I think is a highland mega-spruce forest appears to be a desert.

MC:  1.12.2
Forge: 2556
Java: 1.8.0-151
Pack:  Alpha 9 with fresh world

If someone can tell me how to get the biome id's I'd be glad to add them.

![crag](https://user-images.githubusercontent.com/15672554/34077684-bc1afe54-e2d7-11e7-8c12-30e0a11bd121.png)
![megaspruce](https://user-images.githubusercontent.com/15672554/34077686-bf18c622-e2d7-11e7-8851-540c5dbadeeb.png)

**Comment by Darkosto** [comment]
Yeah, that's because Antique Atlas does not cover modded biomes by default, so we'll have to add these manually. 

Tagging @jandakast since he's been working on this :)

**Comment by Jandakast** [comment]
Every time a new modded biome is added (or changes ID) in the pack the Antique Atlas config has to be updated. I'll need to run a data dump from NEI on the newest build to get the current list of biomes and biome IDs so I can update them again. Expect this to be a reoccurring issue until the mod list is more formalized. I will do my best to keep on top of it though. :)

If @Darkosto gives me the data dump it will ensure I have the biome ID's for the most up-to-date pack build.

**Comment by Darkosto** [comment]
https://pastebin.com/j1MYPmVz

**Comment by justinrusso** [comment]
The biome IDs are shifting when new mods are added, so things are always getting mixed around on a new world vs old.  Requested to use Biome Registry name instead of the ID: https://github.com/AntiqueAtlasTeam/AntiqueAtlas/issues/159
