### ISSUE TITLE
Complete the Iron Chests recipes

### ISSUE THREAD

**Issue by Darkosto** [Darkosto/SevTech-Ages#303]
Should be using the same format as the already finished chests but with the correct mats for the items.

**Comment by Solaxi** [comment]
I'm guessing this task includes changing the required amount of molten metal to cast Iron/Copper/Gold/Silver chests with DirtChest since current amount of 300mB is a weird one. Just making sure. <3

**Comment by Darkosto** [comment]
Should be fixed in dev.
