### ISSUE TITLE
Missing textures in particles when breaking Traverse walls

### ISSUE THREAD

**Issue by RTHauke** [Darkosto/SevTech-Ages#307]
When breaking the following blocks there are missing textures in the Fancy Block Particles smaller particles.  This only happens with the walls from Traverse, all of the other Traverse blocks are fine.

traverse:blue_rock_cobblestone_wall
traverse:red_rock_cobblestone_wall

Tested all of the other "wall" blocks in the pack with a test world and didn't find the issue with any other walls.  Haven't found it in other blocks either, but got bored of placing/breaking blocks!

MC: 1.12.2
Forge: 2556
Java: 1.8.0-151
Pack: Alpha 9 with fresh world and A9 flat, creative world with all unlocks.

![traverse_break_texture-a9](https://user-images.githubusercontent.com/15672554/34091053-3c22954c-e389-11e7-8d57-206cbff8ac7f.png)

**Comment by Darkosto** [comment]
Hey @TheCodedOne any chance this is something you could take a look at?

**Comment by TheCodedOne** [comment]
i believe this is fixed in my dev env, i will double check before i release the new version though

**Comment by TheCodedOne** [comment]
This is still an issue afaik, but as it wasnt reported on the traverse tracker i forgot about it
