### ISSUE TITLE
Remove All Pneumaticraft Fuels Besides:

### ISSUE THREAD

**Issue by Darkosto** [Darkosto/SevTech-Ages#309]
There doesn't need to be 50 "molten metal" fuels that are worthless compared to the actual fuels intended to be used. It just clutters up everything. Keep the following and remove all the rest:

Gasoline
Kerosene
Diesel

Yeah, LPG is currently unobtainable and should be removed.

**Comment by justinrusso** [comment]
Easiest & future-proof way would to just remove all fuels and re-add the ones we want

**Comment by Darkosto** [comment]
I also just looked and see the Refinery isn't completely removed? I swear I had cancelled out all of its recipes and removed it from the game?
