### ISSUE TITLE
Trash Slot Item Persists

### ISSUE THREAD

**Issue by CrossMyDNA** [Darkosto/SevTech-Ages#31]
Items placed in the trash slot in the inventory persist through deaths and when changing worlds. Not sure if this is intentional.

**Comment by Darkosto** [comment]
This mod probably won't make it past testing, I included it because I needed a place to dump items while developing. In the meantime, I'll let the dev know just in case this is unintended behavior.

**Comment by Darkosto** [comment]
https://github.com/blay09/TrashSlot/issues/41

**Comment by Darkosto** [comment]
Should be all fixed up thanks to Blay!
