### ISSUE TITLE
Clay Barrel glitch

### ISSUE THREAD

**Issue by Kaelthalon** [Darkosto/SevTech-Ages#318]
You can fill a clay barrel with the extension up, then move the bottom barrel. It continues to hold the full amount.
![2017-12-18_17 22 41](https://user-images.githubusercontent.com/18230612/34133030-50c774e2-e418-11e7-8ac3-b86336a6bd64.png)
![2017-12-18_17 22 53](https://user-images.githubusercontent.com/18230612/34133032-50dd5fb4-e418-11e7-9513-3d1169cc981b.png)
![2017-12-18_17 24 02](https://user-images.githubusercontent.com/18230612/34133033-50f0a1f0-e418-11e7-909e-22f845174b6e.png)

**Comment by Darkosto** [comment]
Wow, what an unfortunate bug. This is the only way to move mass quantities of liquid in the beginning stages. Oh well!

**Comment by justinrusso** [comment]
I feel like this used to work "ok" - as in youd only move the liquid of what that handled. Must have changed or I'm just crazy.
