### ISSUE TITLE
Roadwalk is still available in Alpha9

### ISSUE THREAD

**Issue by Kaelthalon** [Darkosto/SevTech-Ages#324]
Still there.

I didn't know this issue before hand, now my highway is a deathtrap for me.

**Comment by Kaelthalon** [comment]
When you get the perk "Roadwalk," while walking or running on grass path, your character will jump as if you're glitched or something. The faster you move, the more likely you take fall damage... without falling

**Comment by justinrusso** [comment]
Should be fixed with #229
