### ISSUE TITLE
Pedestalling for Time Tooltip

### ISSUE THREAD

**Issue by Kaelthalon** [Darkosto/SevTech-Ages#325]
"Make sure the statues are 2 blocks from the Pedestal."

The Necronomicon says 3 blocks. Also, do the statues have to be on pillars? They didn't work for me unless I did.

**Comment by Darkosto** [comment]
Statues do not have to be on pillars, mine are on the ground and work.

**Comment by Kaelthalon** [comment]
Ok, So I think mine weren't working then because I didn't have them on the same level as the Energy Pedestal
