### ISSUE TITLE
Unify Hemp from Cultivated Tech to Better With Mods

### ISSUE THREAD

**Issue by Darkosto** [Darkosto/SevTech-Ages#327]
There's no reason to use Cultivated Tech's hemp since we already have our own.

**Comment by justinrusso** [comment]
This drops from grass so will need to be removed in grass.zs, then unify the hemp using the unify.zs script

**Comment by justinrusso** [comment]
Looks like these are not used in anything.. just going to remove the Cultivated Tech hemp completely
