### ISSUE TITLE
Unstage and remove upgrades & Upgrade-emphasis backpacks from Iron Backpacks

### ISSUE THREAD

**Issue by justinrusso** [Darkosto/SevTech-Ages#332]
Unsure where this fits - so making an issue.

![image](https://user-images.githubusercontent.com/25138621/34196329-ae465350-e52f-11e7-9d50-2f62e3af7529.png)

**Comment by Darkosto** [comment]
This issue needs to be altered, all upgrades and upgrade focus bags just need to be hidden for now until that functionality is given back to the mod.

**Comment by Darkosto** [comment]
NETX!
