### ISSUE TITLE
Wooden Slab unification

### ISSUE THREAD

**Issue by davqvist** [Darkosto/SevTech-Ages#34]
I think the intended way to get slabs is 3 slabs in stage 0 and then 6 in stage 1 with the normal recipe. But for some kind of wood, you can't make any slabs while for other you get 6 slabs in stage 0 already.

**Comment by Dawenzel** [comment]
Gave it a try. Not every slab is included but it should solve the issue for some part.
A long version
[slabs.zs](https://gist.github.com/Dawenzel/f191cb18ef56425e024d081ef67226b4)
A short version
[slabs.zs](https://gist.github.com/Dawenzel/2e495ecad98c7380f2d54758229c702f)

**Comment by justinrusso** [comment]
Closing this. Continue discussion in #60.
