### ISSUE TITLE
NetherEx Quartz Ore is not mineable with a Tinker's Steel Pickaxe

### ISSUE THREAD

**Issue by MongoTheElder** [Darkosto/SevTech-Ages#345]
Although the tooltip shows that the mining level is OK, you are unable to break Lively/Icy/Gloomy Quartz Ore with a Tinker's Steel Pickaxe. The Tinker's Pickaxe breaks vanilla Nether Quartz as expected and a PrimalCore Obsidian Pickaxe (uncraftable) is able to break the Lively/Icy/Gloomy Quartz Ore blocks.

Tooltip showing mining level is OK with Tinker's Steel Pick
![2017-12-22_18 48 04](https://user-images.githubusercontent.com/29290246/34315096-bc613542-e749-11e7-8cb0-7006a1fbcbf2.png)

Tinker's Steel Pickaxe
![2017-12-22_18 58 56](https://user-images.githubusercontent.com/29290246/34315136-3454de3c-e74a-11e7-940e-4646cba2e87a.png)

PrimalCore Obsidian Pickaxe
![2017-12-22_18 59 03](https://user-images.githubusercontent.com/29290246/34315139-37615092-e74a-11e7-8e28-ec243319fec5.png)

Alpha 9, Stage 3, Twitch Build

**Comment by Darkosto** [comment]
I've managed to "sort-of" fix the issue. For some reason, adding a mining level via pickletweaks makes tcon tools unusable for this block. I've removed them for the time being so you should be able to mine them now!
