### ISSUE TITLE
Unusual Aqueduct behavior

### ISSUE THREAD

**Issue by MongoTheElder** [Darkosto/SevTech-Ages#346]
If you place a bucket of water on an aqueduct block and then remove it, the entire aqueduct empties and refills from the source

Normal aqueduct
![2017-12-24_16 48 01](https://user-images.githubusercontent.com/29290246/34329356-d430eb90-e8ca-11e7-814b-4ea10e1bbf30.png)

Bucket of water added on aqueduct block
![2017-12-24_16 48 04](https://user-images.githubusercontent.com/29290246/34329357-d9d4a1fe-e8ca-11e7-8759-9ffe96709a46.png)

Water block removed from aqueduct
![2017-12-24_16 48 08](https://user-images.githubusercontent.com/29290246/34329358-dbed0fa8-e8ca-11e7-9b54-5651c7617348.png)

Aqueduct emptying
![2017-12-24_16 48 10](https://user-images.githubusercontent.com/29290246/34329359-df6e813e-e8ca-11e7-8fef-996a2f625e12.png)

Aqueduct empty
![2017-12-24_16 54 29](https://user-images.githubusercontent.com/29290246/34329365-29977c84-e8cb-11e7-9cc6-b7dab9c28a87.png)

Aqueduct refilling from source block
![2017-12-24_16 54 34](https://user-images.githubusercontent.com/29290246/34329366-2e0811c0-e8cb-11e7-8f07-2836dde9e342.png)

**Comment by justinrusso** [comment]
Going to close this. Its pretty minor I suppose, and not sure if it can really be changed.
