### ISSUE TITLE
[Suggestion] Remove Primal Core Rushes

### ISSUE THREAD

**Issue by davqvist** [Darkosto/SevTech-Ages#35]
The Primal Core Rushes are really annoying in several ways:
1.) They have a very tiny hitbox, making them hard to break
2.) If you break them, a tiny rest of it stays in the ground that will make it regrow. The only to get rid of it is to remove the block below it, at least I don't know of another way.
3.) But if you don't get rid of them, they spread like crazy, it seems like. They are like everywhere and keep expanding.
4.) That they slow you down when walking through them and you can see barely anything when walking though them, make them very annoying in a combat. If you are surrounded by them and something attacks you, you are basically dead as you can't flee and can't target. The only real option is trying to break the rushes, but then we are back at 1.) 

I haven't checked configs and I also don't know if they will be important to progression, but I wonder if it wouldn't be better to remove them from world gen.

**Comment by Darkosto** [comment]
I do not agree with removing them, I prefer the additions they make to the world including the causing the player to react differently when in combat. 

I can, however, ask for the hitboxes to be edited so they encompass more of the block.

**Comment by Darkosto** [comment]
Forgot to mention this:

They do not spread and this has been confirmed by the mod author.

**Comment by An-Sar** [comment]
I did end up adding a config hook for the amount of movement modification. Also it should be noted it's only the upper block of the fully grown rush that slows you down. So with the proper tools should make it easier to deal with getting jumped by a rush-creeper...

**Comment by Darkosto** [comment]
I've turned to speed of walking through rushes from .6 to .45 (which I believe is slower) so it should be easier to navigate. There are larger hitboxes to help with breaking. Using a workblade will instantly break them so you should be all set!
