### ISSUE TITLE
Mob drops in NEI/JEI

### ISSUE THREAD

**Issue by btbenedi** [Darkosto/SevTech-Ages#352]
Not sure if versions of the mod support this yet but if possible can we get a mob drop tab like a lot of the 1.10 packs had?

One example of usefulness early on, I didn't realize shearing sheep dropped fleece so I never tried cause the only recipe that showed was Wool -> Fleece in mill stone which I couldn't use yet.

**Comment by justinrusso** [comment]
Not sure how well this would work. I see the reason for it and makes sense, but theres also the issue that certain mobs have drops based on the stage you are in

**Comment by btbenedi** [comment]
I'm guessing that those would show since you're also not able to remove machine's recipes based on stages correct? That could definitely be confusing, mostly just something to think about, maybe we'd get lucky and it would look at the active loot tables for the current stage.

**Comment by Darkosto** [comment]
This functionality does not exist for the purposes of what we need it to so we're unable to make this happen.
