### ISSUE TITLE
Hopping Bonsai Pot not Hopping...

### ISSUE THREAD

**Issue by Kaelthalon** [Darkosto/SevTech-Ages#354]
The Hopping Bonsai Pot does not "Automatically exports drops to inventories below." I tried with chests and a (vanilla) hopper. Instead of "Hopping" it down, it acts like the normal Bonsai Pot and the drops fall on the ground around it. If anything, it costs 4 bronze and 5 iron to give it a black colored base.

**Comment by Darkosto** [comment]
Yep, this functionality was disabled in the config and due to the way the mod works it did not remove the item and caused confusion. It's fixed in dev.
