### ISSUE TITLE
Stone Grill Dupe

### ISSUE THREAD

**Issue by Toktha** [Darkosto/SevTech-Ages#360]
If you cook something on the grill and have a full inv and you try to retrieve the "cooked" item and don't have that item in your inv it will just constantly spit out that cooked item on the ground and give you exp.

Alpha 10
MC: 1.12.2
Forge: 14.23.1.2575

**Comment by btbenedi** [comment]
Also reproducible on Alpha 9, Forget 2556

**Comment by vadis365** [comment]
should be fixed in 0.2.95
