### ISSUE TITLE
Items/Blocks are not hidden when resource packs are changed.

### ISSUE THREAD

**Issue by scootz** [Darkosto/SevTech-Ages#363]
Obsidian blocks are not hidden in stage 0.
![applicationframehost_2017-12-29_01-14-25](https://user-images.githubusercontent.com/574344/34430730-0e0e3098-ec36-11e7-85a9-cb3455c81b7e.png)

**Comment by justinrusso** [comment]
Probably the same thing as #365 . Is this still an issue, or is it now hidden?

**Comment by scootz** [comment]
Yup, indeed it is related.

**Comment by justinrusso** [comment]
This causes JEI to show all the hidden items that should not be shown for the stage, as well as everything in the world is not hidden as they should be.

**Comment by darkhax** [comment]
JEI thing should be reported as a separate issue on the ItemStages tracker.

**Comment by justinrusso** [comment]
Darkhax-Minecraft/ItemStages/issues/5
JarHax/Ore-Stages/issues/4
