### ISSUE TITLE
PrimalCore barrel on BetterFoliage grass turns grass invisible

### ISSUE THREAD

**Issue by LightningAvenger** [Darkosto/SevTech-Ages#364]
Placing a PrimalCore barrel on grass with BetterFoliage enabled turns all grass surfaces the barrel is touching invisible. Disabling BetterFoliage immediately resolves the issue. Submitted an issue on BetterFoliage's github at https://github.com/octarine-noise/BetterFoliage/issues/163

Currently using A10's pack, which includes BetterFoliage 2.1.10, Minecraft 1.12.2, Forge 14.23.1.2575 and Java 1.8.0_151 64-bit.

![image](https://user-images.githubusercontent.com/24767249/34431204-151ee0e4-ec3b-11e7-9609-48265078d602.png)

**Comment by An-Sar** [comment]
this has been fixed

**Comment by justinrusso** [comment]
See An-Sar/PrimalCore/issues/125
