### ISSUE TITLE
A10 - Ore samples showing in stage 0

### ISSUE THREAD

**Issue by scootz** [Darkosto/SevTech-Ages#365]
Windows 10/64bit Java 1.8.0-151
On starting the game and venturing out, Ore samples (all of them?) were visible. I saw gold, bauxite, iron, cinnabar samples.  Took a screenshot yesterday of one of them.   Today, The same ore samples are now back to rocks.   The included picture is within minutes of playing the game fresh.   The ore sample below was autunite. (Zinc)

![javaw_2017-12-29_04-15-34](https://user-images.githubusercontent.com/574344/34440296-470a52ea-ec82-11e7-936f-cb2c5c1cc2a4.png)

**Comment by justinrusso** [comment]
Same issue as #363, closing
