### ISSUE TITLE
A10 - Stage 0 - Astral sorcery? crystal samples give off light while hidden.

### ISSUE THREAD

**Issue by scootz** [Darkosto/SevTech-Ages#366]
Win10-Java 1.8.0-151

I'm guessing this is an astral sorcery crystal sample being hidden or trying to be hidden as a rock, but still gives off light.
![2017-12-29_10 27 31](https://user-images.githubusercontent.com/574344/34440462-5b27160e-ec83-11e7-9cf7-fc3f3ac7c6a7.png)

**Comment by Darkosto** [comment]
Hey @hellfirePVP is there any way you could remove the lighting on this block?

**Comment by HellFirePvP** [comment]
Light removed for next version.
