### ISSUE TITLE
Crash drawing water from PrimalCore barrels

### ISSUE THREAD

**Issue by LightningAvenger** [Darkosto/SevTech-Ages#367]
Dumping water into a PrimalCore barrel functions properly, however when you try to withdraw said water using a bucket or fluid bladder, you get a crash. The crash occurs even when PrimalCore is the only mod installed.

Minecraft version 1.12.2, Forge 14.23.1.2575, PrimalCore 0.6.9, Java 1.8.0_151, Pack version A10

Crashlog: https://paste.ee/p/Ph2D0
Gif: https://i.imgur.com/16ly93a.mp4

Reported to mod author at https://github.com/An-Sar/PrimalCore/issues/124

**Comment by An-Sar** [comment]
the barrel has seen a number of changes in the most recent version of primal, 0.6.11

**Comment by LightningAvenger** [comment]
Moved up to 0.6.11 PrimalCore and the issue is resolved. While I was at it, checked to see if https://github.com/Darkosto/SevTech-Ages/issues/364 was resolved, but it was not.
