### ISSUE TITLE
How to make constant fire?

### ISSUE THREAD

**Issue by davqvist** [Darkosto/SevTech-Ages#37]
I have made the Kilns a while back, but haven't used them yet as they say they require fire under them. But I don't know of a way to keep fire lit under them. I can't think of a material that burns forever that I have access to. I must be missing something probably, sorry if I'm stupid.

**Comment by CrossMyDNA** [comment]
A regular fiber torch underneath works.

**Comment by Tawling** [comment]
Put a torch under it. Think of it like the crucible in Ex Nihilo

**Comment by davqvist** [comment]
Oh yeah, someone told me. I guess I can close this now.
