### ISSUE TITLE
A10 - "Barrel of vadis" still have placeholder achievment text

### ISSUE THREAD

**Issue by SteamDragon** [Darkosto/SevTech-Ages#372]
Check achievment text for Barrel of Vadis (stage 0)
 
 ### Issue / bug
![2017-12-30_04 05 18](https://user-images.githubusercontent.com/2781806/34450303-b2e08824-ed16-11e7-9453-966c0bbd33bd.png)

**Comment by btbenedi** [comment]
Additionally, this Advancement does not seem to be trigger when crafting item, I tried crafting on work stump and normal crafting table, oak and birch barrels, neither triggered the advancement.

![image](https://user-images.githubusercontent.com/9112994/34457491-b0109756-ed7f-11e7-94f7-f6b51075df74.png)
![image](https://user-images.githubusercontent.com/9112994/34457492-bbdec418-ed7f-11e7-8981-0f1754468e7e.png)

**Comment by justinrusso** [comment]
Just tried this on a normal crafting table and cannot reproduce. I've unlocked everything until  the fluid bladder, then crafted the barrel in a minecraft crafting table.

**Comment by btbenedi** [comment]
Maybe it's cause the advancement was added after I finished Stage 0? just tried a bunch of times and nothing.

**Comment by Darkosto** [comment]
Thanks for the report, but I'm already aware of issues regarding the "Lorem Ipsum" text. It is not a high priority currently to fix so I will get to it when all other tasks are completed.
