### ISSUE TITLE
A10 Tin Plate no longer avaliable from stone anvil

### ISSUE THREAD

**Issue by Charles12875** [Darkosto/SevTech-Ages#376]
When hammering Tin Ingots on the Stone Anvil to make Tin Plates for the Ember Bore (Stage 1) the tin ingots turn into tin nuggets. Only the Metal Press and Stamper (Embers) are able to make the Tin Plates.

The copper ingots work as intended turning into copper plates just FYI.

Thank you,
Charles12875

**Comment by btbenedi** [comment]
This is occurring for bronze ingots as well, not sure if intentional.

**Comment by justinrusso** [comment]
A bit of an oversight ... I've written the script to have both a nugget recipe and plate recipe for the stone anvil, which both use the iron ingot as an output. Since the nuggets are the 2nd one of the 2 to get added, it appears to be taking priority.

**Comment by Serolar** [comment]
There could be a recipe using an Immersive Craft Rock for to make the nugget cast. This would possibly be a placeholder recipe until a better way is found.

**Comment by ALongStringOfNumbers** [comment]
What stage is the IE multiblock crusher/grinder in. You could add recipes for throwing in an ingot and getting some nuggets back.
