### ISSUE TITLE
Bear claw missing texture

### ISSUE THREAD

**Issue by btbenedi** [Darkosto/SevTech-Ages#378]
Stage 1, had some bear claws in chest from Alpha 9, icon and texture is gone for them.

Alpha 10
Forge 2575

**Comment by justinrusso** [comment]
There is also a villager trade using these. Probably a change in IDs. The trade "reward" for the villager trade is empty.

https://cdn.discordapp.com/attachments/329447198452482049/396812798086086658/2017-12-30_18.51.43.png

**Comment by Fireztonez** [comment]
Also, the bear claw is invisible on inventory (I use Soartex Fanver).

**Comment by Toktha** [comment]
Same using no texturepack and i see a invisible item for the bear claw.

**Comment by vadis365** [comment]
Fixed a while back. Closing.
