### ISSUE TITLE
A10 Crash when clicking Barrel with a Fluid Bladder

### ISSUE THREAD

**Issue by Solaxi** [Darkosto/SevTech-Ages#379]
Right clicking PrimalCore barrel with an empty Fluid Bladder crashes the game.

Crash report: https://pastebin.com/pYmQK85H

![2017-12-30_22 35 51](https://user-images.githubusercontent.com/13619922/34457248-c68c61d4-edb3-11e7-90a8-343e9d5b2516.png)

**Comment by btbenedi** [comment]
Crash also occurs when clicking barrel with bucket
