### ISSUE TITLE
[Suggestion] Disable Quark Enderman Teleporting

### ISSUE THREAD

**Issue by davqvist** [Darkosto/SevTech-Ages#38]
I don't think I am the only one disliking this option. While I can see the point in leaving it in and making Enderman much harder to kill in the early game without armor and you could cheese them if you disable the option, this option still leads to a lot of frustration, especially if you die due to this without even looking at one Enderman, see https://clips.twitch.tv/FantasticPuzzledTaroBIRB

**Comment by davqvist** [comment]
Sorry I just noticed that this is not clear. I did mean the option of Enderman teleporting the player to themselves, not the Enderman teleporting themselves obviously.

**Comment by Darkosto** [comment]
It was set to normal, vanilla behavior since the pack was first built. But, the modular disable option does not work in the config. This seems to be a bug within Quark.

**Comment by Darkosto** [comment]
Should be fixed up by disabling the option in PrimalCore! Thank you :D
