### ISSUE TITLE
Clay bucket Restricted?

### ISSUE THREAD

**Issue by btbenedi** [Darkosto/SevTech-Ages#380]
Not sure if this is intended, figured I'd report and you can close if it is.

![image](https://user-images.githubusercontent.com/9112994/34457403-a3f5f9ea-ed7d-11e7-80d8-eab76b103240.png)
![image](https://user-images.githubusercontent.com/9112994/34457404-a9753188-ed7d-11e7-9319-c2428925e5fb.png)

Clay bucket crafting is allowed/done as a Stage 1 advancement, but the actual clay bucket is restricted to stage four? And it seems since the bucket cast allows me to use stone bucket I can at least keep moving forward toward that to get a real iron bucket.

If this is intended, why have a Stage 1 advancement for it? Have the user make a different item on the turntable instead.

Versions:

Alpha 10
Forge 2575

**Comment by justinrusso** [comment]
It is intended to be in stage 1.

Something weird is happening in the `metals.zs` script during the liquid container staging process. Not entirely sure why its happening, as other ceramic metal buckets are staged properly, but the default/empty bucket is for some reason being staged in the loop in stage 4.

**Comment by btbenedi** [comment]
Thinking this might be completely preventing all progress in Stage 2. First glass is unobtainable as you can't use clay bucket to pickup lava to put in porcelain tank to smelt sand in melter.

**Comment by btbenedi** [comment]
Whoops wrong button, meant to just cancel the comment I had typed and accidentally closed, so now it's back to New

**Comment by Kaelthalon** [comment]
You can turn sand into piles of sand and smelt it into glass without the need for a lava tank. However, once you get iron and gold, you will need the lava tank to advance.
