### ISSUE TITLE
Use of the Better With Mods Mill Stone is blocked in Stage 0 even when prereq advancement has been completed

### ISSUE THREAD

**Issue by MongoTheElder** [Darkosto/SevTech-Ages#381]
In Stage 0, the Mill Stone shows "Blocked" in the GUI even though the prerequisite advancement "Geared Up for Ratios" has been completed therefore blocking progression to Stage 1

![2017-12-30_20 36 17](https://user-images.githubusercontent.com/29290246/34458442-29b2c612-eda1-11e7-870e-378d6835c3dc.png)

![2017-12-30_20 36 29](https://user-images.githubusercontent.com/29290246/34458443-2ebb20d2-eda1-11e7-9978-b49bcfa4c4b2.png)

![2017-12-30_20 39 45](https://user-images.githubusercontent.com/29290246/34458452-97554b36-eda1-11e7-8769-b967f394dce5.png)

**Comment by btbenedi** [comment]
Side note, the "Blocked" is part of this mod's mechanics, something with this changed from Alpha 9 to Alpha 10. It's strange, if you float it on it's own in the air, it says "Blocked"

This is working in my world though
![image](https://user-images.githubusercontent.com/9112994/34458515-7bc28530-eda3-11e7-859c-e9cf54b7e5ff.png)

**Comment by MongoTheElder** [comment]
Surrounding the Mill Stone with blocks solves the problem. If this is the expected behavior, the Book of Single entry should be updated.

![2017-12-30_20 57 06](https://user-images.githubusercontent.com/29290246/34458538-041a0c82-eda4-11e7-887d-19a17fefbf3c.png)

**Comment by Darkosto** [comment]
This is being cleared up with more text in the tooltip and information in the BWM book.
