### ISSUE TITLE
Stone bricks turn into cobblestone when placed in stage 1

### ISSUE THREAD

**Issue by Solaxi** [Darkosto/SevTech-Ages#382]
Stone bricks are available in stage 1, but turn into cobblestone when placed. Alpha 10.

Edit: Stone brick slabs work.

![2017-12-31_16 17 20](https://user-images.githubusercontent.com/13619922/34462188-c8790626-ee46-11e7-96e2-187caa67ab34.png)

**Comment by Darkosto** [comment]
Stone bricks are in fact in the recipe set for stage 2 but the recipes are not being staged for the minecraft:stonebrick:0 block.
