### ISSUE TITLE
villager names reversed

### ISSUE THREAD

**Issue by Lintfree** [Darkosto/SevTech-Ages#383]
Sevtech 1.12.2 A10  forge 2575

 Fletcher sells farmer items, farmer sells fletcher items 

![2017-12-31_09 59 04](https://user-images.githubusercontent.com/34984989/34462566-b530b2bc-ee14-11e7-9afc-bacc916c5045.png)

![2017-12-31_09 59 06](https://user-images.githubusercontent.com/34984989/34462568-b99d1278-ee14-11e7-8787-9d0092190c4a.png)

**Comment by Darkosto** [comment]
Yes, this has already been reported and marked as resolved on the issue of the Neat mod.
