### ISSUE TITLE
Betweenlands Gem Recipes Need Staging / Removal

### ISSUE THREAD

**Issue by Serolar** [Darkosto/SevTech-Ages#387]
I found that the Piggybackpack is visible from stage 1, but not craftable.
It's likely unstaged for the hiding of it, but staged for the recipe.

Thanks for your time,
Serolar

Sevtech Alpha 10
Forge 2575
Only change:
"Removed nugget creation at the stone anvil, in order to make tin plates"

**Comment by Darkosto** [comment]
This is actually not because it's unstaged but due to needing to remove the Betweenlands gem recipes @justinrusso was going to work on this I believe.

**Comment by justinrusso** [comment]
Gory is having issues getting this to work well. Hes reported it to RecipeStages to request some support

**Comment by Darkosto** [comment]
This should be fixed, correct?

**Comment by justinrusso** [comment]
No, see https://github.com/jaredlll08/RecipeStages/issues/7#issuecomment-366933081

**Comment by justinrusso** [comment]
I think `B:show_non_bl_gem_recipes=false` disabled it. Best we can do.
