### ISSUE TITLE
Stage 0 Farming glitch

### ISSUE THREAD

**Issue by Toktha** [Darkosto/SevTech-Ages#389]
When you try to do farm stuff like plant cotton or food in the tilled ground it says restricted item.  But if you do it enough times it will actually plant the item.   At the same time the item has a slight chance to get glitched and be in your inventory but not actually show.  

Alpha 10
MC: 1.12.2
Forge: 14.23.1.2575

**Comment by Darkosto** [comment]
This sounds like a visual bug:. Does the planted item persist when you close and reopen the world?

**Comment by Toktha** [comment]
Yes.  The plant still stays there and it continued to grow and provide me a item.  In which case i was using it for cotton cause i needed it but couldn't farm yet.   

I was even able to recreate it as well as close the game completely and reopen it and it still stayed as it was at the stage when i left and continued to start growing again when i got back into my world.

**Comment by scootz** [comment]
Restricted items can be used if when the restricted item is dropped , but then picked up and current hotbar selection ends up being where the picked item lands, can be repeatedly clicked on to attempt to place into the world.  It will eventually work.  I've never gotten a ghost item though in inventory when this happened.  I've done it once with a trap door in stage 0.

**Comment by justinrusso** [comment]
@scootz Just showed me a video of this. He did not show that spam right-clicking worked, but he was able to just hold down shift and right click. No spam needed, first try, he was able to just plant the crop that was just restricted by skillable.

**Comment by scootz** [comment]
Here is the link  https://www.dropbox.com/s/mwrpma9an7a5yzi/Minecraft%201.12.2%201_4_2018%2012_39_32%20PM.mp4?dl=0

**Comment by Darkosto** [comment]
This is an issue with Skillable, which we have removed from the pack due to multiplayer issues. This should be okay for now.

**Comment by Lanse505** [comment]
Quick Note:
So We've looked into this for Reskillable @Darkosto per request of @justinrusso .
Turns out that this is less an issue with Skillable and more a cross compat issue.
If/once we can boil down the culprit mod, we can hopefully look at their source code and figure out what they are doing, and then we can implement a fix for it.
