### ISSUE TITLE
Placing down Primacore barrels creates an X-ray-like effect in the world on the block placed.

### ISSUE THREAD

**Issue by Rhyanlugo** [Darkosto/SevTech-Ages#390]
## Issue

- Placing down the primal core barrels in the world causes an X-ray like effect that allows you to see-through the world. 

- It seems to occur both with and without a resource pack as well. I restarted my game without any resource pack just in case and the issue seemed to persist.

- Sevtech Alpha 10 / Forge 2575

![2018-01-01_00 39 34](https://user-images.githubusercontent.com/8825952/34465793-3bf7b354-ee8d-11e7-8a5f-de3228ae11b1.png)
![2018-01-01_00 39 52](https://user-images.githubusercontent.com/8825952/34465794-3c036bd6-ee8d-11e7-9970-ae48301f5ea6.png)
![2018-01-01_00 39 54](https://user-images.githubusercontent.com/8825952/34465795-3c0edd2c-ee8d-11e7-9e8c-3f91027be85f.png)
![2018-01-01_00 40 14](https://user-images.githubusercontent.com/8825952/34465796-3c1a4c7a-ee8d-11e7-9f21-076176883e88.png)
![2018-01-01_00 42 35](https://user-images.githubusercontent.com/8825952/34465797-3c2575b4-ee8d-11e7-9e66-bf8204771434.png)
![2018-01-01_00 42 38](https://user-images.githubusercontent.com/8825952/34465798-3c3121fc-ee8d-11e7-8cbf-294fdb56435a.png)
![2018-01-01_00 42 41](https://user-images.githubusercontent.com/8825952/34465799-3c3eb6f0-ee8d-11e7-9955-a0bc2d0f1284.png)

**Comment by ALongStringOfNumbers** [comment]
This has been fixed, you probably will just have to deal with it for this version of the alpha.

**Comment by justinrusso** [comment]
Dupe #364
