### ISSUE TITLE
A10 - Mushroom growth stops tinkers smeltery from working.

### ISSUE THREAD

**Issue by scootz** [Darkosto/SevTech-Ages#393]
While using the tinkers smeltery, it stopped responding. No flames on the controller, yet the faucets worked for last selected liquid.  Breaking open the smeltery reveals a mooncap mushroom that grew.  Removing the mushroom and replacing seared bricks makes smeltery work again.

![2018-01-01_23 23 39](https://user-images.githubusercontent.com/574344/34474300-37c01b50-ef4b-11e7-8b34-36891a86eed2.png)

**Comment by Darkosto** [comment]
Yeah, that's how the smeltery works. Same thing happens with torches or any other incorrect block within the smeltery.

The fix would be to build your smeltery in a location that does not have mushroom growth.
