### ISSUE TITLE
"Tutorial" Stage

### ISSUE THREAD

**Issue by Darkosto** [Darkosto/SevTech-Ages#396]
The first stage the player begins the pack in should be a "tutorial" stage where ONLY the items needed to progress into 

First tool
First Weapon
First Crafting Table
First Furnace/firepit

This will eliminate excess items and players shouldn't be confused, especially if they don't pay attention to the advancements.

**Comment by justinrusso** [comment]
*Side note* This will also mean that the "zero" stage now needs a stage.

**Comment by Darkosto** [comment]
https://pastebin.com/mPrjhdfD list of tutorial items

**Comment by Darkosto** [comment]
Should be good.
