### ISSUE TITLE
A10/Stage2 - Fiery Ingot not craftable.

### ISSUE THREAD

**Issue by scootz** [Darkosto/SevTech-Ages#398]
Fiery ingots are not craftable in stage 2 to melt down into molten fiery for the coal engine gears to be casted.
 
@justinrusso "Thenecron: If youd like, remind me to check for other ingots that are intended to have a crafting recipe :stuck_out_tongue:"

**Comment by justinrusso** [comment]
Should review other metals and see if any of them also have crafting recipes to create the ingots that should be kept in.
