### ISSUE TITLE
A10/Stage 0 Smoke Particles with nothing on fire, after trying to light torch

### ISSUE THREAD

**Issue by StephJ2Fan** [Darkosto/SevTech-Ages#400]
When trying to light a torch(maybe irrelevant) with the fire bow, I noticed that after being set on fire, the particle effects are still there even when nothing is lit. Also, items mined seem to float up to the top with the particle effects.
![2018-01-03_11 58 53](https://user-images.githubusercontent.com/13186975/34535178-6dddda5e-f07e-11e7-99cf-7ec8e9743425.png)
![2018-01-03_11 59 02](https://user-images.githubusercontent.com/13186975/34535182-70ee331a-f07e-11e7-89d6-6885bf59d72c.png)
![2018-01-03_11 59 48](https://user-images.githubusercontent.com/13186975/34535187-73266d00-f07e-11e7-85f2-7598753c0e03.png)

**Comment by Darkosto** [comment]
The fire bow is just going to be removed since the torches it lights are not available in the game.
