### ISSUE TITLE
Mining Cinnabar while hidden grants the stage 1 coal advancement

### ISSUE THREAD

**Issue by LightningAvenger** [Darkosto/SevTech-Ages#402]
Mining cinnabar while in stage 1 grants the stage 1 advancement "Locate and mine coal"

Alpha10 pack, 1.12.2 Minecraft, 14.23.1.2575 Forge, 1.8.0_151 Java

Screenshot showing the advancement was taken standing where the cinnabar showed up after I granted all advancements to myself
![javaw_2018-01-03_22-50-31](https://user-images.githubusercontent.com/24767249/34549913-711b0d98-f0da-11e7-9bac-2713d844d3ba.png)
![javaw_2018-01-03_22-13-40](https://user-images.githubusercontent.com/24767249/34549914-712721be-f0da-11e7-8196-1df496daa676.png)

**Comment by justinrusso** [comment]
After looking at this briefly, my only guess is that maybe the criteria needs to specify the metadata value of 0? Unlike common behavior, maybe it acts as wildcard if no meta is specified
