### ISSUE TITLE
Alpha10 - Bug when I light a torch with a Fire pit,

### ISSUE THREAD

**Issue by Fireztonez** [Darkosto/SevTech-Ages#407]
Hello Darkosto,
I just starty a new game on the latest version of Sevtech, so I make a Fire pit, put a wood plank inside for make a fire and right click with multiple unlit torch in my hand (a stack of 8 on that case) and after multiple right-click for turn on all my torch I look on my inventory and I have only 4 lit torch.

The first time I try, I have 3 torch unlit and, after  I have only 2, so is appen twice in a row.

Is look like the firepit heat the torch, but doesn't put in the "cooking slot".

Minecraft 1.12.2
Alpha 10
Forge 14.23.1.2575

**Comment by Darkosto** [comment]
I can't replicate this issue, maybe there were server tps issues?
