### ISSUE TITLE
Keep deathnote on death

### ISSUE THREAD

**Issue by Fireztonez** [Darkosto/SevTech-Ages#408]
When I try to go find my tomb, is appen frequently how I die on the road, so I have my death Note for the last die, I go find my tomb, but I getb only the stuff I have on that time (Pratically nothing) but doesn't have the death note ofg my previousa death. I know is possibly noty a bug, but is realy annoying and is some time pratically impossible to find our first tomb, whitout cheat the death note by the command...

Can you make it so that we can recover our death note in our previous grave.

Thank's

Minecraft 1.12.2
Alpha 10
Forge 14.23.1.2575

**Comment by justinrusso** [comment]
- Keep death note on death
- Atlas is supposed to add a death location, but does not

**Comment by Fireztonez** [comment]
Ok, but when you die, you loose your Atlas book, so that would not help...
