### ISSUE TITLE
Porcelin Melter doesn't recognize when the heater is swapped for a tank (repeat of issue 191?)

### ISSUE THREAD

**Issue by MongoTheElder** [Darkosto/SevTech-Ages#414]
In Stage 2, the advancement Smelter Tank has the player change the heater block for a tank. After swapping the blocks and adding lava, the Melter doesn't recognize the new fuel source. Breaking the Melter and replacing fixes the issue. Is this a similar issue as 191?

**Comment by justinrusso** [comment]
From my understanding, this was left as a known thing, and was being left as is. @Darkosto ?

**Comment by justinrusso** [comment]
Clarified in Darkosto/SevTechAgesConfigs@c873c22441cabca0554ca9f43e95e4228e504fab
