### ISSUE TITLE
BC pipes show as restricted item when not

### ISSUE THREAD

**Issue by Syltann** [Darkosto/SevTech-Ages#415]
BC pipes, (when placed in the world) show as "restricted item" on waila tooltip.
Currently on stage 3 running A10.
![2018-01-07_04 22 35](https://user-images.githubusercontent.com/30686588/34658213-0c34b9be-f3e2-11e7-9025-36956fd7f717.png)

**Comment by Syltann** [comment]
Just updated to A11 and now they all say "Diamond... Pipe"

![2018-01-08_08 54 05](https://user-images.githubusercontent.com/30686588/34904499-1c1c4464-f7fc-11e7-9bf8-4c0a23c140b7.png)

**Comment by justinrusso** [comment]
Reported https://github.com/Darkhax-Minecraft/WailaStages/issues/1

I don't think its related to this mod, and is likely the fault of the mod providing WAILA the information. In this case.. Buildcraft.

**Comment by justinrusso** [comment]
Reported to BC https://github.com/BuildCraft/BuildCraft/issues/4060

**Comment by artdude543** [comment]
This was resolved with a few mods updates so no longer an issue \o/ (Unless it's still broken but their fine in my test world)
