### ISSUE TITLE
Primal tech stone anvil and tinker tool bug

### ISSUE THREAD

**Issue by Syltann** [Darkosto/SevTech-Ages#418]
When placing a tinkers tool on a primal tech stone anvil by accident it changed my mattock into an unusable tool with zero durability. The tool is changed permanently even after relog it stays.

**Comment by Syltann** [comment]
The tool is changed to have zero durability, stone mining level and 1 attack. No matter what material was originally used on the tool.

**Comment by justinrusso** [comment]
Dupe of https://github.com/Darkosto/SevTech-Ages/issues/234
