### ISSUE TITLE
Betweenlands items to be added to CarryOn blacklist

### ISSUE THREAD

**Issue by LightningAvenger** [Darkosto/SevTech-Ages#426]
Both the Betweenlands mob spawner from the druid circles and the altar need to be added to CarryOn blacklist. 
Mob spawner blockname: thebetweenlands:mob_spawner 
Altar blockname: thebetweenlands:druid_altar

Otherwise you get to play with the altar and it's pretty funny
![javaw_2018-01-11_21-12-32](https://user-images.githubusercontent.com/24767249/34856860-92b04234-f715-11e7-94b1-b39813f2f5a3.png)

**Comment by Darkosto** [comment]
Fixed!
