### ISSUE TITLE
Some Logs cannot be used in Primal Tech Kiln to make Low-Grade Charcoal

### ISSUE THREAD

**Issue by justinrusso** [Darkosto/SevTech-Ages#427]
Some logs work, others dont. 

### Note:
The ones that appear to not work are ones that "rotate over a few items" in JEI, similar to what you would see from an oredict in a recipe. Any that have an individual entry work fine.

I'm currently looking into the cause, but this appears mod related. Not sure if its the crafttweaker integration or the block's handling of recipes.

**Comment by Kaelthalon** [comment]
The script was changed from A10 to A11, the following code is not in A11:
`<primal_tech:charcoal_block>: [
		<minecraft:log2:1>,
		<minecraft:log2>,
		<minecraft:log:1>,
		<minecraft:log:2>,
		<minecraft:log:3>,
		<minecraft:log>,
		<natura:overworld_logs2:1>,
		<natura:overworld_logs2:3>,
		<rustic:log>
	],`

**Comment by justinrusso** [comment]
Requested wildcard / oredict support https://github.com/vadis365/PrimalTech/issues/5
