### ISSUE TITLE
A11 | Using shears with fleece to make string dupes the shears

### ISSUE THREAD

**Issue by LightningAvenger** [Darkosto/SevTech-Ages#429]
When crafting fleece and shears to turn the fleece into string, each string output seems to come with a shears output as well. Only happens with PrimalCore flint shears and PrimalCore quartz shears
https://clips.twitch.tv/BrightAlertWrenchPeteZarollTie

**Comment by justinrusso** [comment]
I believe this is caused by these shears having hadnling for taking damage by default, so this causes the issue. Will either add to unique, or rename unique to "indestructible" or something, and another for unique which handles ones that already have handling.
