### ISSUE TITLE
Craft wooden planks

### ISSUE THREAD

**Issue by darkhax** [Darkosto/SevTech-Ages#43]
This message popped up after picking up a rock. It could be set to a timer though. 

![image](https://user-images.githubusercontent.com/2250798/29992676-a5e697aa-8f5e-11e7-82aa-c0c482747734.png)

**Comment by Darkosto** [comment]
Hmmmmm, I'll look into it. It seems like Vanilla does not like advancements being removed and every so often they pop up.

**Comment by Blargerist** [comment]
That is not an advancement, it is a tutorial toast. The tutorial toasts should always show up the first time Minecraft is run in 1.12+.

**Comment by Darkosto** [comment]
Installed the Toast Control mod to disable this. Thank you!
