### ISSUE TITLE
Recipe for Spindle is shown incorrectly

### ISSUE THREAD

**Issue by Solaxi** [Darkosto/SevTech-Ages#432]
In A11, JEI shows the Spindle recipe like
![2018-01-14_20 55 47](https://user-images.githubusercontent.com/13619922/34919486-ba611a42-f96d-11e7-9f18-2c4aee2cb5fc.png)

But that doesn't work and it actually is like
![2018-01-14_20 55 57](https://user-images.githubusercontent.com/13619922/34919497-ceee1bc2-f96d-11e7-969e-6581c9b366fc.png)

**Comment by justinrusso** [comment]
Mentioned in a closed issue, may open a new one eventually. 
https://github.com/jaredlll08/RecipeStages/issues/6

Fixed in Darkosto/SevTechAgesConfigs@03be8488dc367c84f70dccd2a68f968bb8ee2b96 by removing the original recipe and manually making a new one.
