### ISSUE TITLE
In stage 2 placed stone bricks end up being cobblestone.

### ISSUE THREAD

**Issue by gbg-disusov** [Darkosto/SevTech-Ages#433]
Hello,

Please take a look at the attached screenshot.

![2018-01-14_22 23 23](https://user-images.githubusercontent.com/29656512/34920322-c3da79fe-f979-11e7-80ce-6df1b3dc4354.png)

**Comment by justinrusso** [comment]
What pack version is this?

**Comment by justinrusso** [comment]
Seems fine in dev.
