### ISSUE TITLE
Unlock Quantum Storage Items During Stage 4 to match up with I.F.

### ISSUE THREAD

**Issue by Darkosto** [Darkosto/SevTech-Ages#437]
Doesn't make sense to have similar functionality unlock later.

**Comment by justinrusso** [comment]
Going to move infinite storage in IF to 5 instead.

**Comment by justinrusso** [comment]
Fixed in Darkosto/SevTechAgesConfigs@5033c1e9a854cf26d0f1b0cff1f22236290cf6fd
