### ISSUE TITLE
A11 | Using Ceramics Clay Bucket to make a bucket cast tries to fill the bucket with gold

### ISSUE THREAD

**Issue by LightningAvenger** [Darkosto/SevTech-Ages#439]
Either stone bucket or unfired clay bucket currently has to be used to make the cast instead of being able to use your current clay bucket. Trying to use the clay bucket results in 288/1000mb for recipe Molten Gold Clay Bucket.
![image](https://user-images.githubusercontent.com/24767249/34972560-4c076388-fa50-11e7-8f13-9e7f61314a33.png)

**Comment by justinrusso** [comment]
Tinkers by default has recipes that fill containers with fluids. Im not sure if that can even be disabled/removed.

**Comment by justinrusso** [comment]
Fixed by Darkosto/SevTechAgesConfigs@5813e68850dff8ca4b489b4ec547a36c3105ff0b
