### ISSUE TITLE
A11 Stage 1 clay bucket/aqueduct issue

### ISSUE THREAD

**Issue by GregsGirl04** [Darkosto/SevTech-Ages#440]
When picking up water with a clay bucket, that is flowing over an aqueduct, it becomes an iron water bucket and gets thrown out of your inventory.  I tested it a bit and it only happens when taking water from the aqueduct.  Also, not sure if intended, but you cannot get water from the PrimalCore barrel with the clay bucket either.

**Comment by justinrusso** [comment]
Reported Aqueduct https://github.com/DaedalusGame/BetterWithAddons/issues/68

**Comment by justinrusso** [comment]
Not sure what has changed, but this is working as expected now.
