### ISSUE TITLE
Create New Modular Machine To Upgrade From Better With Mods Millstone

### ISSUE THREAD

**Issue by Darkosto** [Darkosto/SevTech-Ages#442]
We don't currently have a powered, automat-able machine that can take over in the powered stages (3 or 4) allowing multiple inputs to 1 output.

i.e. Grout Recipe

**Comment by justinrusso** [comment]
Added industrial mill in Darkosto/SevTechAgesConfigs@f875421a824e365e3672519417c5a98e0b4d864f
