### ISSUE TITLE
A11 Move Coralium Plagued Flesh on the Bone to Stage 0

### ISSUE THREAD

**Issue by MongoTheElder** [Darkosto/SevTech-Ages#448]
Items likely to be gathered in Stage 0 should not be restricted to later stages. For example, Coralium Plagued Flesh on the Bone is staged in Stage 1 and there is no way to put it into storage for later necessitating keeping it in inventory. Likewise, Arcane Scrolls and Swamp Talisman Pieces are also staged later clogging up inventory slots.

**Comment by MongoTheElder** [comment]
Never mind. Forces the player to make a primal chest earlier

**Comment by justinrusso** [comment]
I'm going to re-open this. It's worth reading, and I do agree that if you can obtain it, then we need to have considered that.

**Comment by MongoTheElder** [comment]
The charcoal block that results from compressing 9 charcoal for the Stage 0 advancement Pressing Your Luck is staged in Stage 1

**Comment by justinrusso** [comment]
I think this is good. The initial request was satisfied as well as the charcoal block.
