### ISSUE TITLE
Several mods are not server ready.

### ISSUE THREAD

**Issue by darkhax** [Darkosto/SevTech-Ages#45]
Note: If an issue exists on this repo it's because I couldn't find the issue tracker for that mod. 

~~AutoRun - https://github.com/Darkosto/SevTech-Ages/issues/39~~
~~Better Foliage - https://github.com/octarine-noise/BetterFoliage/issues/148~~
~~Pickle Tweaks - https://github.com/Darkosto/SevTech-Ages/issues/40~~
~~Ore Stages - https://github.com/JarHax/Ore-Stages/issues/2~~
~~Primal Chests - https://github.com/jaredlll08/PrimalChests/issues/2~~
~~Ferdinand's Flowers - https://github.com/Darkosto/SevTech-Ages/issues/41~~
FiniteWaterControl - https://github.com/Darkosto/SevTech-Ages/issues/42
~~In Control - https://github.com/McJty/InControl/issues/31~~

**Comment by Darkosto** [comment]
All mods on this list should be reported to the correct devs. Just waiting on responses/fixes.

**Comment by Darkosto** [comment]
All are now server ready as far as I'm aware.
