### ISSUE TITLE
Create New Armor Types

### ISSUE THREAD

**Issue by Darkosto** [Darkosto/SevTech-Ages#459]
Copper
Bronze

Needs Plates for recipes

**Comment by justinrusso** [comment]
Will need these stats for each as well

Name | Value | Required?
-- | -- | --
durability | An “Integer” (e.g. “10”) | No
enchantability | An “Integer” (e.g. “10”) | No
reduction | Four “Integers” (e.g. “2,3,4,5”) | No
toughness | A “float” (e.g. “2.4”) | No

**Comment by Darkosto** [comment]
Ehhhhhh, I don't really care that much about this anymore.
