### ISSUE TITLE
Can't Strip Bark From Horizontal Logs

### ISSUE THREAD

**Issue by CrossMyDNA** [Darkosto/SevTech-Ages#46]
Bark can't be stripped off of horizontal logs. Not a huge deal, since you can just chop it and place it vertically, but kind of annoying in the already time-consuming leather process.

**Comment by Darkosto** [comment]
Hey @An-Sar any news on this one? :)

**Comment by An-Sar** [comment]
I am going to look at this as part of the 0.6.x update, dev builds are already available but I will update here once this is included.

**Comment by Darkosto** [comment]
I'm going to assume this will never happen, unfortunately. I'm going to close this.
