### ISSUE TITLE
Fire Pit Cook Speed Faster Because of Grill

### ISSUE THREAD

**Issue by CrossMyDNA** [Darkosto/SevTech-Ages#47]
After cooking something on a grill above a fire pit, anything cooked in the fire pit itself will cook almost instantly, with or without the grill still above it.

**Comment by Darkosto** [comment]
After some testing, I couldn't replicate but maybe when @turkey2349 takes a look this weekend he can check the code to make sure everything is good :)

**Comment by justinrusso** [comment]
My guess would be this is related to #123 - possibly more fuel was added to the fire pit to "provide fuel" to the grill, and using the grill part was unrelated.

I cant replicate either, and the issue in #123 seems fixed as well.
