### ISSUE TITLE
Unable to place blocks on obsidian before it is unlocked in Stage 3

### ISSUE THREAD

**Issue by MongoTheElder** [Darkosto/SevTech-Ages#470]
You get a staging warning when placing a block on obsidian prior to it getting unlocked in Stage 3

![2018-01-22_18 02 53](https://user-images.githubusercontent.com/29290246/35249063-8946e162-ff9e-11e7-99e5-c19bc9884658.png)

**Comment by ALongStringOfNumbers** [comment]
When seen on stream, it looked like there was an inventory desync until a block was actually placed.
https://clips.twitch.tv/VivaciousMushyJamNinjaGrumpy
