### ISSUE TITLE
Advancements needing description edits

### ISSUE THREAD

**Issue by Sparky1492** [Darkosto/SevTech-Ages#474]
Please comment below with any additional Advancements descriptions that need to be edited.  Please provide the Stage and Advancement name. (i.e. Stg 2 - Cinder Plinth).

**Stage 0**
- [ ]  Barrel of Vadis

**Stage 1**
- [ ]  Lorem ipsum

**Stage 2**
- [ ] Alchemy Pedestal
- [ ] Aspectus
- [ ] Cinder Plinth 
- [ ] MEME Cannon.
- [ ]  The Market

**Stage 3**
- [ ]  Lorem ipsum

**Stage 4**
- [ ]  Lorem ipsum

**Stage 5**
- [ ]  Lorem ipsum

----------------------------------------------------------------------------------------------------------

![image](https://user-images.githubusercontent.com/945772/35252918-a4aa3fdc-ffb0-11e7-8b6e-c79f11b7b44b.png)
Courtesy of @GregsGirl04

**Comment by justinrusso** [comment]
We appreciate the help with this, but I think it would be a lot more work than it is worth to maintain this. We can get a list of all the achievements pretty quickly through the achievement folders.
