### ISSUE TITLE
Disable Blaze Spawning that isn't from a spawner

### ISSUE THREAD

**Issue by Darkosto** [Darkosto/SevTech-Ages#477]
I think Quark has this feature.

**Comment by GirafiStudios** [comment]
Can be disabled in the Quark config, under "world" in the config option called "Blazes spawn naturally in the nether".

**Comment by justinrusso** [comment]
@GirafiStudios that is already set to false

**Comment by justinrusso** [comment]
@Darkosto Has this been fixed with the removal of the allowed spawn blocks? https://github.com/Darkosto/SevTechAgesConfigs/commit/8a0e2a9257e85e935721ca71edccb65e95780497#diff-668102476796bb4c0f19c30a7cd74891
