### ISSUE TITLE
Auto Step on Path Blocks

### ISSUE THREAD

**Issue by CrossMyDNA** [Darkosto/SevTech-Ages#48]
The auto step doesn't work if you're stepping up to a full block from a path block.

**Comment by Darkosto** [comment]
This is actually due to that distance being greater than 1 block, technically farmland or grass paths are 15/16ths of a block and step-up only does 1 block or less.

I'll speak with Lothrazer and maybe he can up the tolerance a bit.

**Comment by CrossMyDNA** [comment]
I figured. Still, it was like, "I have to jump?" *blinking guy meme*

**Comment by Darkosto** [comment]
@princeofamber is this a possibility?

**Comment by PrinceOfAmber** [comment]
Looks like github doesnt send me emails when someone does an @ to me.  Feel free to DM me on twitter or make github issue tickets anytime, i check those constantly.

Anyway, this will be updated soon in the next version so Cyclic 1.8.2

**Comment by Darkosto** [comment]
Yep! added in and works! Thanks!
