### ISSUE TITLE
Remove all Traces of Embers and Roots

### ISSUE THREAD

**Issue by Darkosto** [Darkosto/SevTech-Ages#484]
I can't wait to literally have to spend HOURS of our lives removing 2 mods. 

G
FREAKING
G

**Comment by Darkosto** [comment]
That also means Soot is gone.

**Comment by justinrusso** [comment]
### Related commits:
Darkosto/SevTechAgesConfigs@e169d5a387accc4568e6c24e50e7a1f73277e16c
