### ISSUE TITLE
World crash on startup

### ISSUE THREAD

**Issue by Deselous** [Darkosto/SevTech-Ages#485]
After a recent crash, that I don't know what could of caused it, I cannot load back into said world without it crashing outright. The only thing I can say what i was doing before the crash was crafting firestarter sticks while i had one in hand, I tried it in a separate test world and that's not an issue.
SevTech Alpha 11/w MultiMC, 

Crash log:   https://gist.github.com/anonymous/56253b429425caa2a7eb23cb5515aa5c

**Comment by justinrusso** [comment]
To note, you posted yesterday about this issue and discord with https://paste.ee/p/DyJgI which has a different stack trace
