### ISSUE TITLE
Oak Door craftable in Stage 0

### ISSUE THREAD

**Issue by djnifos** [Darkosto/SevTech-Ages#487]
Playing latest version from Discord.  I can craft the door on the work stump, and pick it up, but when I try to place it, it falls from my inventory with the message, "You dropped the Oak Door!  Further progression is required. " Then it loots, and drops with the message again.  I was able to break out of the loop by looting it from the floor while eating.

**Comment by justinrusso** [comment]
This should be staged in one. In dev things look fine - might have been an issue where you found recipes for a door that was not staged. These were fixed with a recipe stages update.
