### ISSUE TITLE
Items Counting as Horse Saddle

### ISSUE THREAD

**Issue by CrossMyDNA** [Darkosto/SevTech-Ages#49]
Clicking the "Deposit" button in a tamed horse's inventory will grab two random items from your inventory and count them as a saddle so the horse can be ridden.

**Comment by Darkosto** [comment]
Reported to Vazkii.

https://github.com/Vazkii/Quark/issues/608

**Comment by Darkosto** [comment]
Fixed in the latest Quark update, thank you!
