### ISSUE TITLE
Move Immersive Engineering Alloy Kiln to Stage 1

### ISSUE THREAD

**Issue by Darkosto** [Darkosto/SevTech-Ages#490]
Fix up recipes for ingots so they are the correct mod ingots.

**Comment by justinrusso** [comment]
Needs the IE hammer, which needs to be pushed back as well

- [ ] Stage IE hammer to stage 1
- [ ] Move multi-block stage for IE alloy kiln to 1
- [x] Fix recipes in smelter
- [ ] Adjust IE hammer recipe (uses iron which is not available) - @Darkosto input needed

**Comment by justinrusso** [comment]
Used copper for Iron replacement for IE hammer tool
