### ISSUE TITLE
Remove Actually Additions Crushed Coal + Charcoal

### ISSUE THREAD

**Issue by Darkosto** [Darkosto/SevTech-Ages#498]
Better With Addons Crushed Coal + Charcoal can be the items we use primarily.

**Comment by justinrusso** [comment]
Closed in Darkosto/SevTechAgesConfigs@53cfd105467c659d8c52cf94d332fd71bfb55584 & Darkosto/SevTechAgesConfigs@fd35b59b4187ca1d2b169927b24454dc38bf184c
