### ISSUE TITLE
Ironwood not choppable

### ISSUE THREAD

**Issue by CrossMyDNA** [Darkosto/SevTech-Ages#5]
Ironwood can't be placed on a chopping block.

**Comment by Darkosto** [comment]
Looks like this one needs to be added manually, thanks!

**Comment by CrossMyDNA** [comment]
Here are the other logs that can't be placed on a chopping block, though many of these will likely not be available until after the player is done using the chopping block:
- Sugi wood
- Olive wood
- Bloodwood 5529
- Bloodwood 5529:15
- Bloody wood
- Canopy tree wood
- Darkwood wood 6944:3
- Transwood
- Minewood
- Sortingwood
- Darkwood 5528:1
- Mulberry wood
- Ghostwood
- Sakura wood 5902
- Twilight oak wood
- Mangrove wood
- Alicio wood visage 5895
- Alicio wood 5894
- Timewood
- Fusewood
- Spruce stripped log
- Birch stripped log
- Jungle stripped log
- Acacia stripped log
- tile.logs_stripped_dark_oak.name
- Ironwood stripped log
- Yew stripped log
- tile.CinderLog.0.name 7000

**Comment by Darkosto** [comment]
Should all be added minus the ones that do not have plank variants.
