### ISSUE TITLE
Gear Advancement Too Soon

### ISSUE THREAD

**Issue by CrossMyDNA** [Darkosto/SevTech-Ages#50]
I got the Gear Up For Ratios advancement after getting The Wheels on the Bus, but I haven't made a gear yet.

**Comment by davqvist** [comment]
Oh yeah, true, happened to me as well.

**Comment by Dawenzel** [comment]
The advancement sets the required item to betterwithmods:material but under this code name also falls hemp as a example. Adding the metadata to the required item fixed it for me after some testing.
![example](http://puu.sh/xrdso/700e7cfefe.png)

**Comment by Darkosto** [comment]
Should be fixed up in the next version, thanks!
