### ISSUE TITLE
Disable Galacticraft Refinery Machines

### ISSUE THREAD

**Issue by Darkosto** [Darkosto/SevTech-Ages#505]
There might be extras from the extra planet mod. The fuel creation is done through IE now.

**Comment by justinrusso** [comment]
Hiding these will require staging all of extra planets manually, otherwise the item will still appear in JEI.

**Comment by justinrusso** [comment]
Darkosto cheated. Hidden with JEI's hide in game in Darkosto/SevTechAgesConfigs@566e2f37e365a690e51d0e84dc41ce859ed058f6
