### ISSUE TITLE
Buffaloes not dropping Teeth despite dropping other drops

### ISSUE THREAD

**Issue by Drullkus** [Darkosto/SevTech-Ages#51]
Buffaloes seem to not be dropping teeth at all. I've killed around 20 and then several more in creative with various weapons with and without looting.

**Comment by davqvist** [comment]
I never had any problems with them so far. I have killed 5 of them, one dropped none, one dropped two.

**Comment by Darkosto** [comment]
Shut up drull

**Comment by Drullkus** [comment]
Might retry in future. Might be bad RNG as per what Darko said

**Comment by Darkosto** [comment]
Tested and looks like you have bad RNG @Drullkus
