### ISSUE TITLE
Remove Left Over Vanilla Dyes

### ISSUE THREAD

**Issue by Darkosto** [Darkosto/SevTech-Ages#518]
All of the combined colors: Purple, etc. go to vanilla when crafted. We need to prioritize the Pickle Tweaks Dyes.

**Comment by NeosGhost** [comment]
There was a spelling error in the oredict.base script and it looks like the vanilla dyes need to be removed from their own separate oredicts, this should fit it. :)
[oredict.base.txt](https://github.com/Darkosto/SevTech-Ages/files/1777119/oredict.base.txt)

**Comment by NeosGhost** [comment]
Do all the recipes that use vanilla dyes need to be recoded to use the pickle tweaks dye powders or can the dye item be changed globally? If so possibly change the dye plant from mystical agriculture to give pickle tweaks powders instead of the minecraft dyes.
