### ISSUE TITLE
I changed one item recipe in RFTools and now the entire mod has to be staged by Item ID's

### ISSUE THREAD

**Issue by Darkosto** [Darkosto/SevTech-Ages#537]

**Comment by justinrusso** [comment]
WHY U DO DIS

**Comment by justinrusso** [comment]
This may have just been a mistake, and fixed by Darkosto/SevTechAgesConfigs@fe225de7b6142d01e85b2391adbd683436e11a2f and Darkosto/SevTechAgesConfigs@26fc1c0d66042014540a7ffd53cc35923730de74
