### ISSUE TITLE
Clicking the input of a Kiln JEI doesn't work

### ISSUE THREAD

**Issue by davqvist** [Darkosto/SevTech-Ages#54]
If I click the input of the Clay Barrel Extension recipe of the Kiln in JEI, I get no response/results but if I click that item in JEI itself it works. I will test later if all items in the input of the Kiln are affected.

**Comment by davqvist** [comment]
Okay, I tested a bit more. Right clicking the unfired Clay Barrel Extension also doesn't show the Kiln recipe. I think this is because the recipe itself doesn't seem to registered correctly as I put the unfired one in the Kiln and nothing happened, even after waiting for several minutes while making Charcoal for example worked just fine.

**Comment by Darkosto** [comment]
Should be all good, I had bad ID names in the Primal_Tech config
