### ISSUE TITLE
Item Stage Minecraft Arrow

### ISSUE THREAD

**Issue by Darkosto** [Darkosto/SevTech-Ages#546]
Stage 2

**Comment by justinrusso** [comment]
`<minecraft:tipped_arrow>` is still showing.. not sure what to do for those. `recipes.removeAll()` does not even remove it. Working with Jared for a fix hopefully.

**Comment by justinrusso** [comment]
Looks like nothing can be done I guess, so tipped arrows will stay un-recipe staged.
