### ISSUE TITLE
Bark Recipe not Working in Inventory Crafting Area

### ISSUE THREAD

**Issue by IceRogue** [Darkosto/SevTech-Ages#559]
### Issue / bug
 - SevTech Beta 1 loaded from the Twitch App export
- Bark not crafting in inventory crafting area with a flint blade and log (will try to attach screen shots)

![2018-03-06_18-59-18](https://user-images.githubusercontent.com/6313755/37065816-85ad6636-2170-11e8-9f43-53aa082bb29a.png)

**Comment by IceRogue** [comment]
Side note: The advancement on the flint blade still mentions Shift Clicking. Just a reminder when you are looking at this issue.

**Comment by justinrusso** [comment]
Debugging the recipe. May be related to .giveBack() as the oredict is OK for this recipe, and shows to work with other recipes the tool is used for. Consulting devs.

**Comment by justinrusso** [comment]
Fixed in Darkosto/SevTechAgesConfigs@aef90ffc30177d3932dde79a756c093887f8c2b2
