### ISSUE TITLE
Duplicate recipe Wet Tanned Hide

### ISSUE THREAD

**Issue by Dawenzel** [Darkosto/SevTech-Ages#56]
The recipe for Wet Tanned hide is declared twice in shapedrecipemaster.zs on line 315 and 317
![recipe](http://puu.sh/xqv4G/b99cad94d3.png)

**Comment by Dawenzel** [comment]
This is also the only duplicate recipe I could find in this file.

**Comment by Darkosto** [comment]
Removed the extra line, thanks!
