### ISSUE TITLE
[Beta 1-Fixed] 17 Missing Registry Items

### ISSUE THREAD

**Issue by primetoxinz** [Darkosto/SevTech-Ages#560]
Attempting to connect to the sub-server with a clean MultiMC install with Beta-1(Fixed)

https://gist.github.com/primetoxinz/1cdbf0bff667d9b7bd15d9a37628b048

**Comment by justinrusso** [comment]
I believe this is just like darkphan's issue - statics are broken in crafttweaker in linux environments.

**Comment by justinrusso** [comment]
Might be the same as #595?

**Comment by justinrusso** [comment]
Should be fixed. See https://github.com/Darkosto/SevTech-Ages/issues/595
