### ISSUE TITLE
[Beta1] Broken weapon smith trade Bear claw to blank

### ISSUE THREAD

**Issue by Marioluigi7896** [Darkosto/SevTech-Ages#562]
![2018-03-06_17 20 17](https://user-images.githubusercontent.com/30518749/37066700-dad5820e-2163-11e8-99f5-27604bd36a68.png)

Found this on the sub server

**Comment by Darkosto** [comment]
@vadis365 any idea why the item icon is broken? the ID is correct, I just checked it out.

**Comment by Darkosto** [comment]
Nevermind, Vadis.

**Comment by Darkosto** [comment]
Fixed in dev.
