### ISSUE TITLE
[Beta1] crash possibly a karate zombie from better with addons

### ISSUE THREAD

**Issue by Marioluigi7896** [Darkosto/SevTech-Ages#563]
Version of Pack: Beta1

 Was in another window, waiting for day on the sub server in a hole when this happened.
  looks like better with addons karate zombies by looking at the top of the report.

 Forge version 14.23.2.2624
 Better With Addons-0.31

Crash Report:
  https://gist.github.com/Marioluigi7896/f7d6121b5f6e82166dc3845e3ee443a5

**Comment by Darkosto** [comment]
Should be good, fixed by Bord.
