### ISSUE TITLE
[Beta1] Oil pockets are spawning

### ISSUE THREAD

**Issue by Marioluigi7896** [Darkosto/SevTech-Ages#564]
![2018-03-06_18 28 33](https://user-images.githubusercontent.com/30518749/37068550-8a2dfad0-216c-11e8-8099-a1b86e4f8feb.png)

 Found a pneumaticraft oil pocket on the sub server

**Comment by justinrusso** [comment]
This may not be pneumaticcraft. Will have to investigate this more before just submitted an issue with them...

**Comment by Darkosto** [comment]
That's not oil. It's Bitumen from PrimalCore.
