### ISSUE TITLE
Weapon Repairs

### ISSUE THREAD

**Issue by BryanBoru** [Darkosto/SevTech-Ages#569]
* Use a few weapons in the work table with no result 

 ### Issue / bug
* Regardless of what I use with the weapons/tools, the flint hatchet, nor the spear will give me a repaired weapon back.
* The other weapons and tools do so far
* Flint Hatchet does not have a repair recipe, but the spear does.

**Comment by Darkosto** [comment]
Because those tools cannot be repaired due to bugs.
