### ISSUE TITLE
[Beta1] Cant put Menrill drops in storage

### ISSUE THREAD

**Issue by tjsd** [Darkosto/SevTech-Ages#570]
You can cut down Menrill trees with the flint hatchet, but you cant place the items in storage since you need to rightclick items into the chest/Shelves.

**Comment by BryanBoru** [comment]
FYI - once you get to the stage where you can craft primal chests, you will be able to put restricted items in there for later use.

**Comment by Darkosto** [comment]
Going to keep this in the pack. Not all items will be usable right away and you'll have to leave them and go back later to properly use them. Thanks for the report :)
