### ISSUE TITLE
Fibre Torch Crafting in Inventory

### ISSUE THREAD

**Issue by IceRogue** [Darkosto/SevTech-Ages#572]
### Issue / bug
 - Fibre Torches don't want to craft in the inventory space. Though when I first logged into the server to get the screen shots for this it did work but as soon as I moved things around I could not get it to work again.
 - The recipe does work in the crafting table.
 - Version is Beta 1 Fixed, Twitch App Export
![fibre torch 1](https://user-images.githubusercontent.com/6313755/37099884-843bddbc-21ef-11e8-8f9c-e6da2601b505.png)
![fibre torch 2](https://user-images.githubusercontent.com/6313755/37099889-8762e30a-21ef-11e8-88cf-5f85f29142f6.png)
![fibre torch 3](https://user-images.githubusercontent.com/6313755/37099891-893914b0-21ef-11e8-8f02-49777bb3d7a3.png)

**Comment by BryanBoru** [comment]
Check in advancements and JEI and craft a work table. 
It's best to assume recipes shown in a 3x3 are meant for on there, as most do.

**Comment by Darkosto** [comment]
I can't replicate this. Anyone else?

**Comment by IceRogue** [comment]
For replication, try crafting something first then see if that changes your ability to do it. When I first log in and the first thing I put in the crafting area is the the stick and fibre on the left it will sometimes work. I did create a new single player world and had the same issue, so it could be an issue with my install if no one else can replicate.

**Comment by IceRogue** [comment]
Playing around with a new(er) single player world, I figured out how to break it. If you only place the materials in the left squares it will work. Once you try place them in the right squares (which clicking the + in JEI will do) it will no longer work no matter which side you use.

**Comment by Darkosto** [comment]
I'm still trying to replicate and can't:

https://i.artdude.uk/darkosto/IPnlU8ja.mp4

**Comment by Darkosto** [comment]
Nevermind, I got it "working"

**Comment by Darkosto** [comment]
Should be fixed in dev.
