### ISSUE TITLE
Fire Sticks not Crafting in Inventory

### ISSUE THREAD

**Issue by IceRogue** [Darkosto/SevTech-Ages#574]
### Issue / bug
 - Not able to craft in player inventory 2x2 grid
 - I seem to remember this working in the original release of Beta 1 but in Beta 1 Fix it is not
 - Version is Beta 1 Fix: Twitch App Export
![fire stick0](https://user-images.githubusercontent.com/6313755/37103111-7bd0f7d6-21f7-11e8-947a-a210e6b9fd15.png)
![fire stick 2](https://user-images.githubusercontent.com/6313755/37103117-7e1eb500-21f7-11e8-8a57-c7c3676e0ec9.png)
![fire stick1](https://user-images.githubusercontent.com/6313755/37103122-7fd7c454-21f7-11e8-8fa9-6ffced8a731a.png)

**Comment by BryanBoru** [comment]
I had this working and then not working and then working again depending on which stage I was in.

**Comment by Darkosto** [comment]
I'm also unable to replicate this issue:

![image](https://user-images.githubusercontent.com/10309699/37106065-cd50957e-21fe-11e8-8676-5b3991c3151f.png)

**Comment by IceRogue** [comment]
This might be due to issue 572 and not due to anything with the firesticks at all. If I attempt to craft these before I try craft a torch they seem to work fine,
