### ISSUE TITLE
'I HAVE CREATED FIRE' advancement not unlocking

### ISSUE THREAD

**Issue by tomudding** [Darkosto/SevTech-Ages#58]
Using two Fire Sticks (a.k.a. Whittled Fire Sticks) to make a fire does not grant the advancement 'I HAVE CREATED FIRE'. I have made a short [video](https://www.youtube.com/watch?v=1yzWRbiHg2E) to demonstrate what I mean.

**Comment by CrossMyDNA** [comment]
You can make the fire sticks right in your inventory crafting grid—maybe try that instead of using the stump?

**Comment by tomudding** [comment]
That does indeed work, but then the description of the advancement should be changed... It should be 'craft' instead of 'use' (and you only have to craft 1).

**Comment by Darkosto** [comment]
Fixed the advancement type and description to allow the player more options on how to acquire them whilst still getting the advancement.
