### ISSUE TITLE
[Beta1] Charcoal Block is in Stage 1

### ISSUE THREAD

**Issue by Marioluigi7896** [Darkosto/SevTech-Ages#592]
![2018-03-08_12 24 01](https://user-images.githubusercontent.com/30518749/37171643-bc9bc5dc-22cb-11e8-874e-4525fb3d02f9.png)

 ### Issue / bug
 You need the charcoal block for the horse press quest in stage 0 but it is staged in stage one

**Comment by Darkosto** [comment]
Fixed in dev.
