### ISSUE TITLE
Salted Leather issue

### ISSUE THREAD

**Issue by BryanBoru** [Darkosto/SevTech-Ages#594]
###Tinkers' Drying racks are no longer converting salted hide into dried hide.
Single Player Survival.

* I have made leather from start to finished previously

* Placing the salted hide into Tinkers' Drying Racks does not convert the hide into dried hide
    * even after large amounts of time, and in various locations. 

* I am at the current advancement levels:
![2018-03-08_14 33 07](https://user-images.githubusercontent.com/9432488/37173202-f0792b14-22e0-11e8-8c93-b259525ff14a.png)

* When I go into JEI Tinker's drying racks are no longer an option for conversion
![2018-03-08_14 37 26](https://user-images.githubusercontent.com/9432488/37173225-fc55f908-22e0-11e8-8a7a-80490c805c7f.png)

**Comment by Darkosto** [comment]
Looks like it can't be reproduced, might have been a one time bug.

**Comment by txpeters** [comment]
I am also getting this, but seems only to effect crafted drying racks. If I cheat in the drying rack, it works fine.  Also noting a ID difference 4691/0 (broken) vs 4691/1 (works)

**Comment by Darkosto** [comment]
Are you sure you're not using an Item Display Rack instead of a Drying Rack?

**Comment by Pabloelmundo** [comment]
I've also just come across this problem, doesn't seem to be a one off problem

**Comment by Pabloelmundo** [comment]
Nevermind, i restarted my client and it works now, not sure what was going on tbh

**Comment by Pentro** [comment]
Same issue, drying rack doesn't even show salted leather -> leather as a possibility.

**Comment by Jhrek** [comment]
I also seem to be having this issue regarding leather. I made both the drying rack and display rack and none of them seem to be affecting the leather process.

**Comment by txpeters** [comment]
Apologies - You are correct I was crafting an item rack instead of drying rack
