### ISSUE TITLE
[BETA2] CraftTweaker/ContentTweaker errors on world load 

### ISSUE THREAD

**Issue by 0xb00b** [Darkosto/SevTech-Ages#595]
I downloaded the latest SevTech-Beta2MultiMC.zip, replaced the crafttweaker jar in the mods folder after importing it into multiMC and started a new world. I'm getting these errors in chat, im pretty sure this did not happen with the previous beta / alpha versions.

Relevant part of the log: https://pastebin.com/3cAXkbra 
Full log: https://gist.github.com/0xb00b/3490c2a28eeb8c36588437c3e2fca04b 

Sorry for the lack of further info.. i have no idea how to describe this / know what further info to supply.

**Comment by Darkosto** [comment]
@jaredlll08 @justinrusso would you mind taking a look just in case? When you're able. Thank you!

**Comment by jaredlll08** [comment]
Please try this version and give us the crafttweaker log file and the fml log

http://i.blamejared.com/CraftTweaker2-1.12-4.1.5_prerelease.jar

**Comment by 0xb00b** [comment]
CraftTweaker2-1.12-4.1.5_prerelease.jar seems to be working without any errors! 

Here are the requested logs: 
crafttweaker: https://gist.github.com/0xb00b/80ebbe902d50f57fe2eaf135cc81e24f
fml-latest: https://gist.github.com/0xb00b/6520deaffde153239bb3453686da8159
