### ISSUE TITLE
Alot of Ancient Golems spawning

### ISSUE THREAD

**Issue by DingoX3** [Darkosto/SevTech-Ages#6]
![2017-08-31_01 03 18](https://user-images.githubusercontent.com/16032841/29912582-2045c88c-8e00-11e7-9f3d-df9278baa2cd.png)

**Comment by Tawling** [comment]
Confirming that it's not only in desert biomes. It's everywhere. 
![2017-08-31_01 47 44](https://user-images.githubusercontent.com/7520947/29914736-75f460fc-8dee-11e7-8f65-5d58caa3b4c8.png)

**Comment by Darkosto** [comment]
In Control uses the term "weight" in its configs, and these along with horses are set to 1 and 2. Apparently, it's not actually using weight and seems to be a 1 out of x method instead.

**Comment by DingoX3** [comment]
Same issue referenced here https://github.com/Darkosto/SevTech-Ages/issues/8
