### ISSUE TITLE
Priority of duplicate recipes of different ages

### ISSUE THREAD

**Issue by davqvist** [Darkosto/SevTech-Ages#60]
So I like that some recipes give different amounts in different stages. But the priority doesn't seem to work right. For example in stage 1, Stone slabs still give 3 instead of 6 which means it prioritizes the worse recipe.

**Comment by Darkosto** [comment]
@jaredlll08

**Comment by jaredlll08** [comment]
@davqvist is it always like this? or only for some recipes?

**Comment by davqvist** [comment]
I haven't tested them all of course, I just noticed Stone Slabs working that way and assumed that there is nothing prioritizing the recipes.

**Comment by justinrusso** [comment]
We can make a temporary stage that gets removed when a stage ends. We have the plan to do this for mobs as well, so might as well put it to more uses if possible

Completion of this also closes #34.
