### ISSUE TITLE
[BETA2] Chest recipe is not staged

### ISSUE THREAD

**Issue by Buuz135** [Darkosto/SevTech-Ages#601]
![HAPPY BIRTHDAY DARKOSTO](https://i.imgur.com/IFztFdU.png)

**Comment by Darkosto** [comment]
@justinrusso I'm not sure why there is a 4th chest recipe, but can we look into removing the extra. Thanks!

**Comment by justinrusso** [comment]
This appears to be the same issue as https://github.com/Darkosto/SevTech-Ages/issues/612

**Comment by Darkosto** [comment]
Fixed in dev.
