### ISSUE TITLE
[Beta2] Tooltips don't show when looking in backpack

### ISSUE THREAD

**Issue by Marioluigi7896** [Darkosto/SevTech-Ages#604]
### Issue / bug
![2018-03-09_11 48 32](https://user-images.githubusercontent.com/30518749/37224137-d234843c-238f-11e8-9a93-d422fb6a88c4.png)
This tooltip isn't showing while looking in the backpack but does in the player's normal inventory

**Comment by Marioluigi7896** [comment]
only happens to items in the inventory window not in JEI

**Comment by Darkosto** [comment]
This is a mod bug, not a pack bug. These issues need to be reported to the mod dev. 

https://minecraft.curseforge.com/projects/improvedbackpacks/issues/3

And hopefully, the mod dev looks at their issues once every 10 years to fix it.

**Comment by Darkosto** [comment]
Guaranteed not getting fixed since this issue was reported to the dev in October and has never been responded to.
