### ISSUE TITLE
[Beta2] Baby skeletons spawn in stage zero with gold armor

### ISSUE THREAD

**Issue by Marioluigi7896** [Darkosto/SevTech-Ages#607]
### Issue / bug
Baby skeletons also have bows, but the gold armor is the bigger issue

**Comment by Marioluigi7896** [comment]
Depths Ghouls also spawn with gold armor in stage zero

**Comment by justinrusso** [comment]
Baby Skeletons disabled in Darkosto/SevTechAgesConfigs@e7bb54ecebaf3c5fafbc2814fc2a6533e9ca5016
