### ISSUE TITLE
Digging Under placed Melon crashes game.

### ISSUE THREAD

**Issue by BryanBoru** [Darkosto/SevTech-Ages#609]
### Dig under block/ gravity - crash

* MPS on SevTek subserver
* using a stone shovel I dug the dirt out from under a placed melon resulting in a crash.
* earlier on @Darkosto's stream he had a similar crash with a pumpkin

* Log: https://gist.github.com/BryanBoru/5e2c835911a7616137817c50aecb385a

**Comment by Darkosto** [comment]
Should be fixed in dev.
