### ISSUE TITLE
[BETA2] Stone anvil has a staged recipe and a not staged one

### ISSUE THREAD

**Issue by Buuz135** [Darkosto/SevTech-Ages#612]
![HAPPY BIRTHDAY](https://i.imgur.com/icMG1fq.png)

**Comment by justinrusso** [comment]
@jaredlll08 Any ideas on this? Is the mod adding the recipe late...?

```
recipes.remove(<primal_tech:stone_anvil>);
recipes.addShaped(<primal_tech:stone_anvil>, [[stone, stone, stone], [null, stone, null], [<minecraft:stone_slab>, <minecraft:stone_slab>, <minecraft:stone_slab>]]);

mods.ItemStages.addItemStage("one", <primal_tech:stone_anvil>);
mods.recipestages.Recipes.setRecipeStage("one", <primal_tech:stone_anvil>);
```

**Comment by justinrusso** [comment]
@vadis365 you doing anything weird here?

**Comment by kindlich** [comment]
@justinrusso 
Why don't you just use
```
mods.recipestages.Recipes.addShaped("one", <primal_tech:stone_anvil>, [[stone, stone, stone], [null, stone, null], [<minecraft:stone_slab>, <minecraft:stone_slab>, <minecraft:stone_slab>]]);
```
?

**Comment by justinrusso** [comment]
Just old code I suppose. Just curious why its breaking

**Comment by justinrusso** [comment]
So `shaped_recipe_master.zs` and `shapeless_recipe_master` should essentially go away. Will need to move any recipe for an item that is recipe staged into the proper stage's recipe additions.

**Comment by vadis365** [comment]
The mod recipe is completely different than the SevTech one, those recipes are the modpack's recipe added for the pack.

**Comment by justinrusso** [comment]
@vadis365 yeah, I think we've found the reason

**Comment by Darkosto** [comment]
I've fixed this particular issue in dev.
