### ISSUE TITLE
[BETA2] Coralium plagued flesh recipe in JEI doesnt have the workblade and it gets used when crafting

### ISSUE THREAD

**Issue by Buuz135** [Darkosto/SevTech-Ages#613]
![HAPPY BIRTHDAY](https://i.imgur.com/6JJm7iI.png)

**Comment by justinrusso** [comment]
![image](https://user-images.githubusercontent.com/25138621/37237163-ffb09ec0-23dd-11e8-9275-acbf50e3325b.png)
🤔

**Comment by MongoTheElder** [comment]
If you place more than one Plagued Flesh on a Bone in the grafting grid you only get one one Plagued Flesh and one Bone back

**Comment by justinrusso** [comment]
@MongoTheElder I see, nice find. Were you able to replicate the initial issue though?

**Comment by MongoTheElder** [comment]
The recipe in NEI is correct for me but it does consume the workblade during crafting.

**Comment by justinrusso** [comment]
Should be fixed. Let me know if theres any more issues on this in the next version.
