### ISSUE TITLE
[BETA2] Necronomicon GUI is wierdly offset to the top

### ISSUE THREAD

**Issue by Buuz135** [Darkosto/SevTech-Ages#614]
![HAPPY BIRTHDAY](https://i.imgur.com/2uOGKwf.png)

**Comment by BryanBoru** [comment]
@Buuz135  the Smooth Font mod affects this text too, and can be adjusted to improve appearance of the guidebook, but would also affect the rest of game text.

Purista: 
![d7a1b719f2e15808d9bb18b202e770f4](https://user-images.githubusercontent.com/9432488/37317914-ea19cad4-263d-11e8-8192-0f4841bee6d2.png)

Oden Round: 
![a7debe5f3bbaa1b38a3599b2b8cb5cca](https://user-images.githubusercontent.com/9432488/37317929-012308b2-263e-11e8-89fa-21c22b3bbb2e.png)
