### ISSUE TITLE
[BETA2] After dieing to a shadow creature and spawning the game crashed

### ISSUE THREAD

**Issue by darkphan** [Darkosto/SevTech-Ages#617]
Crashlog here: https://pste.me/#/CIOIl

**Comment by vadis365** [comment]
https://github.com/BetterWithMods/BetterWithMods/blob/1.12/src/main/java/betterwithmods/client/model/TESRFurnaceContent.java#L19

this.

**Comment by Darkosto** [comment]
Should be fixed up in BWA. Just need to confirm its all good.
