### ISSUE TITLE
Stone Bricks hiding

### ISSUE THREAD

**Issue by davqvist** [Darkosto/SevTech-Ages#62]
So you can craft Stone Bricks in stage 0, but they are still hidden with Cobblestone even in stage 1. Which means either the recipe needs to be gated or they need to be unhidden.

**Comment by Darkosto** [comment]
Yep, I haven't been able to finish every recipe yet so many of them, like this, probably exist. Thanks for the report!

**Comment by Darkosto** [comment]
Stone bricks and mossy stone bricks are now entered into Stage 2. Thanks!
