### ISSUE TITLE
[BETA2] Coralium ore cant be broken with stone tools

### ISSUE THREAD

**Issue by Buuz135** [Darkosto/SevTech-Ages#620]
At stage 1 the only pickaxe that can break coralium ore is the coralium pick itself and the Black Quartz Pickaxe that is gated behing coralium. It needs mining level diamond.

![HAPPY BIRTHDAY](https://imgur.com/XzpSlJr.gifv)

**Comment by MongoTheElder** [comment]
Same for Aquamarine Ore

**Comment by Darkosto** [comment]
@justinrusso can you change the mining levels to Iron level.
