### ISSUE TITLE
[Suggestion] Add advancement for the Sanguine Scientiem before the Blood Altar

### ISSUE THREAD

**Issue by MongoTheElder** [Darkosto/SevTech-Ages#622]
Since the Sanguine Scientiem is not a Blood Magic item (comes from Guide-API), it doesn't show up in the @BloodMagic filter. Adding an advancement to create the guide would bridge the gap to help the player getting started with Blood Magic.

Beta 2

**Comment by Darkosto** [comment]
This should be good, I've added the book into the advancement for the player to receive automatically.
