### ISSUE TITLE
Aquamarine Ore Texture

### ISSUE THREAD

**Issue by MongoTheElder** [Darkosto/SevTech-Ages#624]
The Aquamarine Ore block is transparent with blue speckles

![2018-03-10_13 30 03](https://user-images.githubusercontent.com/29290246/37245525-514152d2-2467-11e8-84f6-69f57dc700a8.png)

Beta 2
Twitch Version
No texture pack/shaders

**Comment by justinrusso** [comment]
Oh no... :( I thought it was just me. No one else seemed to run across this.

**Comment by MongoTheElder** [comment]
![2018-03-10_13 37 48](https://user-images.githubusercontent.com/29290246/37245584-40a96314-2468-11e8-9c05-3b44e0a283e9.png)
