### ISSUE TITLE
Abyssalcraft mobs dropping whatever this item is when killed.

### ISSUE THREAD

**Issue by JackRuby1** [Darkosto/SevTech-Ages#627]
https://gyazo.com/0afa76b543dffd3ab41a6f8f72f75c22
I'm getting this item when killing Abyssalcraft mobs during stage 0 and FirstNecron says this is a nono :P

**Comment by justinrusso** [comment]
https://github.com/Darkosto/SevTech-Ages/issues/625

**Comment by Darkosto** [comment]
Moved back into stage 0.
