### ISSUE TITLE
Copper Block doesn't render in Tinkers Complement Basin

### ISSUE THREAD

**Issue by davqvist** [Darkosto/SevTech-Ages#63]
When pouring Copper into the Tinkers Complement Basin, it creates a Copper Block and it renders correctly until it hardens when it suddenly disappers. You can of course still retrieve it by right clicking, so it's in there, just not rendering correctly.

(On a side note, you also get a Chisel version of the Copper Block, but you are probably already aware of that)

**Comment by Darkosto** [comment]
I'm aware of the chisel block being the one that shows up, and I'm not too concerned since I've worked this into recipes in the meantime. 

I'll speak with KnightMiner about the disappearing blocks.

**Comment by Darkosto** [comment]
Okay, so: This is actually a chisel and Tcon bug. In the meantime, the issue is on the Tcon tracker and I spoke to KnightMiner. I have also removed Chisel blocks from being pourable, so it should take care of this.
