### ISSUE TITLE
Arcane Rune from Squid kill

### ISSUE THREAD

**Issue by JackRuby1** [Darkosto/SevTech-Ages#630]
I'm in stage 0 and I just killed a squid, and it dropped an Arcane Rune from stage 3.

**Comment by JackRuby1** [comment]
BTW another mob dropped one as well, don't know which one, because it was on the ground when the mobs burned during the day

**Comment by Darkosto** [comment]
Yeah, that's fine. Just hold on to it until you've unlocked it or delete it.
