### ISSUE TITLE
Advancement 'Wolly Blankets' in Stage 2 has confusing instructions

### ISSUE THREAD

**Issue by MongoTheElder** [Darkosto/SevTech-Ages#632]
The text of the achievement says you can make wool with fleece and string but there is no recipe for this. The recipe that is intended (I believe) uses fleece and wicker (made with sugar cane)

![2018-03-10_19 10 53](https://user-images.githubusercontent.com/29290246/37248107-cc0a401c-2496-11e8-9ccc-eb28e70a1249.png)

![2018-03-10_19 11 03](https://user-images.githubusercontent.com/29290246/37248109-cfb47566-2496-11e8-8f8b-8ff9ff318aeb.png)

**Comment by Darkosto** [comment]
Changed up in dev!
