### ISSUE TITLE
[Beta 2] If tipi is destroyed by creeper (or TNT) it cannot replaced in the same spot.

### ISSUE THREAD

**Issue by RTHauke** [Darkosto/SevTech-Ages#633]
## If a creeper destroys your tipi, you cannot place a new one in the same spot.

Reproducible:

New world, give game stage zero.
Place tipi, sleep in it.
Note where tipi is sitting.
Give game stage one.
Place TNT next to tipi, set it off.
Repair hole.  I placed cobble one level below grade, followed by dirt at grade.
Try to place a new tipi.  Right-clicking in the same spot as the old one does nothing.
Nothing is logged, it just won't place the tipi.
You CAN place a tipi outside of the 5x5 are where the old one was but nowhere within the old 5x5.

Note:  Spawn is reset as well, just like a broken bed.

Launcher:  MMC
Version:   BETA 2, with Crafttweaker fix and the posted recipe fixes.
                   (scripts.zip from Thenecron 3/8)
OS:  Linux, OpenSUSE Leap 42
Java: openjdk version "1.8.0_151"
Logs:  Nothing unusual is logged, but here they are anyway.
           https://paste.ee/p/PQDws

**Comment by RTHauke** [comment]
A full game restart does not fix the issue.

**Comment by Darkosto** [comment]
https://github.com/TeamTotemic/Totemic/issues/63

**Comment by artdude543** [comment]
This was fixed in 3.0.5
