### ISSUE TITLE
Horse power chopping block has second recipe

### ISSUE THREAD

**Issue by Serolar** [Darkosto/SevTech-Ages#634]
![2018-03-10_21 04 09](https://user-images.githubusercontent.com/16960400/37249182-344aaaa2-24a8-11e8-9dda-0ab1f7452b75.png)
 ### Issue / bug
Issue:
The horse powered chopping block has a second recipe.  I assume it needs only the one made for the pack. 
Screenshot should explain.

**Comment by Darkosto** [comment]
Yep, already reviewed and left it in on purpose.
