### ISSUE TITLE
(Beta 2) Waila doesn't display fish tank block name

### ISSUE THREAD

**Issue by Syltann** [Darkosto/SevTech-Ages#636]
When looking at fish tank from "Just a Few Fish" waila doesn't display block name.

![2018-03-10_23 05 44](https://user-images.githubusercontent.com/30686588/37250740-aafe895c-24b7-11e8-9b69-745bbf4fc71a.png)

**Comment by Darkosto** [comment]
Yep, there's a few blocks that do this. This is for the JAFF devs to fix, not us.

**Comment by Darkosto** [comment]
https://minecraft.curseforge.com/projects/just-a-few-fish/issues/7
