### ISSUE TITLE
Copper advancement unlocked immediately

### ISSUE THREAD

**Issue by davqvist** [Darkosto/SevTech-Ages#64]
The Copper advancement unlocked right when I unlocked the previous advancement without ever having mined a single ore.

**Comment by Dawenzel** [comment]
Through a little bit of testing, I found out that breaking a rock triggers the second requirement for this advancement. Changing the blocks required from "geolosys:geolosys:ore" to "geolosys:ore" fixed the trigger when breaking a rock. (More testing is needed to check if other blocks trigger the same advancement)

**Comment by Darkosto** [comment]
Should be all fixed up, good catch @Dawenzel
