### ISSUE TITLE
[BETA2] The Stage 2 Tough Dowsing rod is picking up Platinum

### ISSUE THREAD

**Issue by MongoTheElder** [Darkosto/SevTech-Ages#640]
![2018-03-11_16 30 01](https://user-images.githubusercontent.com/29290246/37258142-79beebf6-2549-11e8-8380-b0830b1293c8.png)

![2018-03-11_16 30 06](https://user-images.githubusercontent.com/29290246/37258143-7cd2fc38-2549-11e8-8f84-908171d5918f.png)

**Comment by Darkosto** [comment]
All incorrect ores being picked up should be fixed now.
