### ISSUE TITLE
Conflicting Melon Recipes

### ISSUE THREAD

**Issue by BryanBoru** [Darkosto/SevTech-Ages#645]
Beta2

JEI whos two recipes for a single melon in a crafting grid alone: 
Cyclic's recipe receiving 9 slices of melon
and a BWM recipe showing a broken Melon texture and giving 5 Slices.

**Comment by PrinceOfAmber** [comment]
Recipes config section in line 1014 of cyclicmagic.cfg

 B:"Melon Block Slices"=true

**Comment by Darkosto** [comment]
@justinrusso Can you please remove the BetterWithMods recipe by name to fix this up, when you're able.
