### ISSUE TITLE
Add Mekanism Salt to Wooden Basin Recipes

### ISSUE THREAD

**Issue by BryanBoru** [Darkosto/SevTech-Ages#646]
Beta2

Mekanism Salt works with manually making Salted Hide, however it does not work in Wood Basin Recipes to make the same. 

dough as well.

**Comment by Darkosto** [comment]
https://github.com/Darkosto/SevTech-Ages/issues/608

Already reported and also fixed in dev.

**Comment by Darkosto** [comment]
https://github.com/Darkosto/SevTech-Ages/issues/600
