### ISSUE TITLE
Nutrition Info Missing UPDATED

### ISSUE THREAD

**Issue by BryanBoru** [Darkosto/SevTech-Ages#648]
# Beta 2

The following food items are missing Nutrition Information:

## Fruit
* "galacticraftcore:basic_item:15 Dehydrated Apples",
* "galacticraftcore:basic_item:16 Dehydrated Carrots",
* "galacticraftcore:basic_item:17 Dehydrated Melons",

## Grains
* "actuallyadditions:item_food:10",    Toast
* "actuallyadditions:item_food:11",    Submarine Sandwhich
* "actuallyadditions:item_food:18",    Doughnut
* "actuallyadditions:item_food:19",    Toast O Chocolate
* "betterwithmods:donut",

## Protein
* "actuallyadditions:item_food:11",    Submarine Sandwhich
* "actuallyadditions:item_food:13",    Hamburger
* "actuallyadditions:item_food:20",    Bacon
* "actuallyadditions:item_food:3",    Fish N Chips
* "extraplanets:canned_food",    Canned Pork
* "extraplanets:canned_food:1",    Canned Fish
* "extraplanets:canned_food:2",    Canned Salmon
* "extraplanets:canned_food:3",    Canned Chicken
* "extraplanets:canned_food:4",    Canned Beef
* "nex:food_meat_ghast_raw",
* "nex:food_meat_ghast_cooked",

## Vegetables
* "actuallyadditions:item_food:1",    Pumpkin Stew
* "actuallyadditions:item_food:2",    Carrot Juice
* "actuallyadditions:item_food:3",    Fish N Chips
* "galacticraftcore:basic_item:18",    Dehydrated Potatoes
* "nex:food_mushroom_enoki",
* "primal:daucus_murn_fronds_withered",    Cooked Daucus Murn Root
* "primal:aconite_root",
* "primal:corn_cob",
* "primal:corn_cob_cooked",
* "primal:aconite_petal",
* "primal:aconite_sprig",
* "primal:void_grass_root",
* "primal:nether_seed",
* "primal:nether_root",
* "primal:mushroom_cooked",
* "primal:pumpkin_piece",
* "primal:daucus_murn_root",

**Comment by BryanBoru** [comment]
I tried to get cute and help with the item names. Hope this makes it easier and not harder.

**Comment by Darkosto** [comment]
Should all be added. Do note, some of the foods you listed already had nutrition values.

**Comment by daddy77gaming** [comment]
All galacticraft foods in 3.06 do not have any nutrition value
