### ISSUE TITLE
Hunting Dimension Portal Frame in Stage 1, arrows are Stage 2

### ISSUE THREAD

**Issue by JackRuby1** [Darkosto/SevTech-Ages#651]
I noticed that arrows are Stage 2, but are required to build the Hunting Dimension portal frame, which is Stage 1.

**Comment by Darkosto** [comment]
Ahhh, ya. We should change that. LuL

**Comment by Darkosto** [comment]
Fixed in dev.

**Comment by JackRuby1** [comment]
@Darkosto So.. the Hunting Dimension is for Stage 2 access only(Prevents it in Stage 1), so why is it able to be made and able to light in Stage 1?

**Comment by Darkosto** [comment]
Looks like I got it confused. It should be stage 2 then.
