### ISSUE TITLE
[Beta 2] Can't smelt vanilla nethererack into nether bricks

### ISSUE THREAD

**Issue by Syltann** [Darkosto/SevTech-Ages#652]
Nether X netherrack can smelt into nether bricks, but vanilla netherrack can't.

**Comment by Darkosto** [comment]
Hey @justinrusso can we remove these furnace recipes? All the netherbrick should be on the same route as vanilla netherrack.

**Comment by Darkosto** [comment]
Actually, I fixed the Blast Brick recipe to only use the Vanilla nether bricks instead.
