### ISSUE TITLE
[Beta 2] Can't place vanilla torches while in off-hand

### ISSUE THREAD

**Issue by Syltann** [Darkosto/SevTech-Ages#653]
Can't place vanilla torches while in off-hand while a variety of tools (vanilla, tinkers, and others). While Galacticraft glowstone torches and other torches from other mods can be placed while in off-hand and tool in main hand.

**Comment by Darkosto** [comment]
This is a simple config somewhere, I just need to find it. Then add all torch variants.

**Comment by Darkosto** [comment]
Should be good to go on this one.
