### ISSUE TITLE
Totempedia Does Not Alert Players to Shift-Click and Causes Confusion

### ISSUE THREAD

**Issue by Darkosto** [Darkosto/SevTech-Ages#654]
The players I've seen testing do not always figure out shift-click is the way to start a ritual, and this information is except from anywhere. I've made an issue at the Totemic tracker but at the very least we can create an advancement to supplement this information.

https://github.com/TeamTotemic/Totemic/issues/64

**Comment by Darkosto** [comment]
Edit, it has "Sneaking" in the book but this still isn't picked up by many players.

**Comment by artdude543** [comment]
This was fixed/changed in the mod to include formatting on the text to help make it stand out more. (We ship with the version which has the changes)
