### ISSUE TITLE
[Beta 3] Farming restriction broken

### ISSUE THREAD

**Issue by RTHauke** [Darkosto/SevTech-Ages#656]
It looks like the farming restriction has been removed.  In the tutorial and stage 0 planting and the ability to handle seeds and create farmland work before earning the farming achievement.
 
Able to pickup and carry, without the auto-drop and missing advancement messages the following:  seeds, sugar cane,  beet root seeds, rice seeds (and rice difference from Beta2)
Able to plant all of the above in world-gen farmland (cane of course in sand/dirt).
Able to create and use farmland.

Version:  Beta 3, new installation, new world.
OS:  Linux
Java:  java -version
          openjdk version "1.8.0_151"
          OpenJDK Runtime Environment (IcedTea 3.6.0) (build 1.8.0_151-b12 suse-18.1-x86_64)
          OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)

**Comment by Buuz135** [comment]
Thats because skillable was removed and it handled that stuff

**Comment by Darkosto** [comment]
That's correct, it has no restriction because that mod was removed.
