### ISSUE TITLE
Limited fire sources for lighting fiber torches

### ISSUE THREAD

**Issue by TheValliant** [Darkosto/SevTech-Ages#657]
### Issue / bug
 - In Beta3, you can't light a fiber torch with either a totem torch or lava.

**Comment by Darkosto** [comment]
Will add. Thanks!

**Comment by Darkosto** [comment]
Just following up, I added Totem Torch but Lava is not possible to add since you would place the block/item where the lava exists and delete what liquid was in the spot.
