### ISSUE TITLE
Horse Press will delete any block above it when placed.

### ISSUE THREAD

**Issue by TheValliant** [Darkosto/SevTech-Ages#658]
### Issue / bug
In Beta 3:

Take a horse press. Place it in a 1 high spot. See whatever was directly above it cease to exist.

**Comment by Darkosto** [comment]
Hey @GoryMoon have you seen this before?

**Comment by GoryMoon** [comment]
Haven't seen it, will have a look at it

**Comment by GoryMoon** [comment]
Can verify that this is an issue that haven't been found until now, will fix this soon

**Comment by GoryMoon** [comment]
1.12.2-2.5.12.58 is uploaded to curse, awaiting approval

**Comment by GoryMoon** [comment]
Woops, misread the issue and thought it was for the chopping block, realized the issue was for the press and fixed for that in 1.12.2-2.5.12.59
