### ISSUE TITLE
Input must be a block

### ISSUE THREAD

**Issue by ZeldoKavira** [Darkosto/SevTech-Ages#66]
Tabbed out after clicking create new world, game was paused due to auto pause and chat spit out two "ERROR: Input must be a block".

![image](https://user-images.githubusercontent.com/1683434/30094358-b067f7bc-9280-11e7-8e75-9e449761456a.png)

**Comment by Darkosto** [comment]
Yep, I know about this one as it seems to be false positive regarding Better With Mods/Addons and ModTweaker. I'll check in with the mod author and see where we're at.

I'll also check with @jaredlll08 to see if anything can be done on his side since all inputs are placeable blocks.

**Comment by jaredlll08** [comment]
I'm gonna blame @primetoxinz on this one >.>
https://github.com/jaredlll08/ModTweaker/commit/02cbd3a90a3df90c31068b8682812689eb3ef0bb

**Comment by primetoxinz** [comment]
Whoops

**Comment by ZeldoKavira** [comment]
👍

**Comment by jaredlll08** [comment]
https://minecraft.curseforge.com/projects/modtweaker/files/2476999
