### ISSUE TITLE
Carry On Dupe Glitch in Multiplayer

### ISSUE THREAD

**Issue by JakeOTwitch** [Darkosto/SevTech-Ages#667]
SevTech Beta3 / Forge version 14.23.2.2627

The Carry On mod has has this dupe glitch ever since it was made and has not been fixed.
If you are playing SevTech Multiplayer, one person can open the inventory of a block (example: Advanced Primal Chest) and the other player can pick up the chest. When the chest is in the players hand, the other player can remove all items and when the inventory is placed back down, all items will still be in the chest.

**Comment by Darkosto** [comment]
Well, it's not as simple as "has not been fixed". As this issue states:

https://github.com/Tschipp/CarryOn/issues/58

The issue actually lies on the side of every mod that does their tile entities incorrectly. So, technically the fix would lie in the mods not closing their GUI's. Carry-on could make a fix if they chose but it's honestly not really their problem and are well within their rights to refuse a fix. 

Having said that, I added something to the issue and hopefully we can change their mind on whether or not they would like to add code to fix this.

**Comment by pennyvise1** [comment]
In addition to this if you pick up an animal with CarryOn with a lead attached to it, you will dupe the lead.

**Comment by Tschipp** [comment]
The lead issue is new to me. Thanks for letting me know.

**Comment by pennyvise1** [comment]
Im having trouble recreating that today, let me go over the vod from yesterday and see what I was doing, I was actually trying to replicate it so I could start a new issue for you
