### ISSUE TITLE
[Beta 3] Staging: tomato seeds need crop stakes

### ISSUE THREAD

**Issue by TheValliant** [Darkosto/SevTech-Ages#675]
Tomato seeds can be acquired from farmers in stage 0 and aren't marked as stage-excluded, but the crop stakes can't be made until later.

**Comment by Darkosto** [comment]
Yep, they can be obtained because seed drops cannot be staged. Having said that, farming in general is stage one which would not work for crop sticks. I'm going to leave this how it is because not everything will perfectly fit into the stage mold.
