### ISSUE TITLE
Magma Monsters issue

### ISSUE THREAD

**Issue by OldManCraft** [Darkosto/SevTech-Ages#678]
The amount of fire is causing issues. Is very bad for servers. I have DoFireTick = false and still getting this. 

![2018-03-15_11 15 08](https://user-images.githubusercontent.com/10180530/37483855-1d335856-2844-11e8-807d-c1d27599593f.png)
![2018-03-15_11 06 07](https://user-images.githubusercontent.com/10180530/37483859-1f672ca6-2844-11e8-977b-20d303041807.png)
![2018-03-15_10 58 39](https://user-images.githubusercontent.com/10180530/37483864-20be6ccc-2844-11e8-964a-77b25638c831.png)

**Comment by OldManCraft** [comment]
It's called DoFireTick = false  and this happened under my base. It happened to another player as well. Do fire tick does not stop them from wondering around lighting every block they step on like a snowman.

**Comment by Darkosto** [comment]
Hey @vadis365 this looks like broken.

**Comment by Darkosto** [comment]
I'll take a look later on and turn it off or remove the mod if it causes more serious issues.

**Comment by vadis365** [comment]
Magma monsters has a config to turn the block lighting off - probably better for situations like this.
I'm not sure what can be done to fix this for a long term solution, I guess I could add a blacklist to the mod to exempt the MMs from laying fire on certain blocks.

**Comment by vadis365** [comment]
NOT A BUG! BTW. :P

**Comment by BryanBoru** [comment]
I like the challenge of the MM in the pack, the fire starting, however, does have that consequence of server load. In my personal use, i have turned off the firestarting via config.

**Comment by Darkosto** [comment]
Fire spread is off in config in dev.
