### ISSUE TITLE
[Beta 3] Killing Baykok and issues

### ISSUE THREAD

**Issue by MrHrulgin** [Darkosto/SevTech-Ages#679]
There's a couple of different issues that have arisen around Baykok.

1. Killing Baykok didn't unlock Baykok's bow for me, possibly because I killed him for the first time before I killed a buffalo, so I got both achievements at once.

2. Baykok drops arrows that require age 2 to hold. I don't know if that prevents them from being used, as I can't equip the bow, but even if so it seems inconvenient to not be able to hold them.

**Comment by Darkosto** [comment]
Vanilla arrows need to be removed and replaced with the stage 0 variant via inControl.
Need to double check Baykok's bow is still correctly staged.

**Comment by justinrusso** [comment]
The baykok stage was never actually added to the advancement to trigger. I've added that in Darkosto/SevTechAgesConfigs@8d1754e8bee8b99fa973d97d4bb781767b9d9184

**Comment by TheValliant** [comment]
Having forced the baykok unlock, the regular arrows are used just fine despite being stagelocked from my perspective in stage 1. I can't hold them in my hand, but I can shoot them.

**Comment by justinrusso** [comment]
Still doesnt make sense to keep like that. We have arrows available to craft when you get the baykok stage.

**Comment by justinrusso** [comment]
Drops fixed in Darkosto/SevTechAgesConfigs@3d5ed94f9f410933e86b341905c58fab877e3999
