### ISSUE TITLE
NBT console spam

### ISSUE THREAD

**Issue by darkhax** [Darkosto/SevTech-Ages#681]
I keep finding the following messages in my client. 

`{burnTime:0,x:768,y:68,cookingItem:{},z:147,id:"minecraft:tile_fire_pit_unlit",cookTimeLeft:0}`

and this one has air

`{burnTime:-1,x:267,y:87,cookingItem:{id:"minecraft:air",Count:1b,Damage:0s},z:168,id:"minecraft:tile_fire_pit_unlit",cookTimeLeft:-1}`

**Comment by justinrusso** [comment]
Seems like a dupe of https://github.com/Darkosto/SevTech-Ages/issues/605 ?

**Comment by darkhax** [comment]
Yep, sorry!

**Comment by justinrusso** [comment]
All good, appreciate the report! 👍
