### ISSUE TITLE
Blood Magic sigils and gems not hidden in stage 1

### ISSUE THREAD

**Issue by RTHauke** [Darkosto/SevTech-Ages#682]
In stage 1 the BM Sigil of the Blood Lamp, Sigil of Holding and the Tartaric Gems are visible but cannot be crafted.  All require restricted items or a tier 3 altar.

Pack version: Beta 3

**Comment by Darkosto** [comment]
I'll switch these recipes to be possible in stage 1. Should be ready for Beta4.
