### ISSUE TITLE
[Q.O.L/annoyance] Fluid Bladder changes hotbar slot when filling/emptying

### ISSUE THREAD

**Issue by BryanBoru** [Darkosto/SevTech-Ages#683]
when using the `fluid bladder` to put in/take out liquid of a container, the bladder will move to the leftmost empty hotbar, regardless of original location.
This is not how vanilla buckets perform and it is an annoyance.

**Comment by vadis365** [comment]
I'm going to leave this as it is, I don't see a massive problem and it works as a stop gap until you make a bucket. It's probably more annoying to change to work different at this late stage of development and not a QOL change for me ;)

**Comment by BryanBoru** [comment]
Simply a QOL complaint and an understandable reply. Thanks for the hard work @vadis365

**Comment by justinrusso** [comment]
I agree, I like that its a bit annoying, because it makes you look forward to having buckets
