### ISSUE TITLE
Can I break everything?

### ISSUE THREAD

**Issue by darkhax** [Darkosto/SevTech-Ages#684]
In OreStages, you currently use `mods.OreTiers` in the CraftTweaker scripts to set the ore stage. The correct name is `mods.orestages.OreStages` however the code is still using the old OreTiers name. If I make this change, every reference to `mods.OreTiers` would need to be replaced to `mods.orestages.OreStages`. If I make this change would be be absolutely devastating to the pack? With the release coming up I would like to have it use the right name in the code. 

@justinrusso 
@Darkosto

**Comment by justinrusso** [comment]
Its just scripts. Wouldnt be hard to find and replace if its something simple like that

**Comment by justinrusso** [comment]
Already got it ready to merge :)
