### ISSUE TITLE
[BETA3] Blood Magic runes cant be broken with stage 1 pickaxes

### ISSUE THREAD

**Issue by Buuz135** [Darkosto/SevTech-Ages#686]

**Comment by Darkosto** [comment]
<bloodmagic:blood_rune:10>
<bloodmagic:blood_rune:7>
<bloodmagic:blood_rune>
<bloodmagic:blood_rune:4>
<bloodmagic:blood_rune:3>
<bloodmagic:blood_rune:1>
<bloodmagic:blood_rune:2>
<bloodmagic:blood_rune:6>
<bloodmagic:blood_rune:9>
<bloodmagic:blood_rune:8>
<bloodmagic:blood_rune:5>

Have been changed to Stone Pickaxe level (Iron)
