### ISSUE TITLE
Able to craft the swamp talisman and enter The Betweenlands before Age 2 is unlocked

### ISSUE THREAD

**Issue by darkphan** [Darkosto/SevTech-Ages#687]
You can craft the swamp talisman and enter The Betweenlands before Age 2, and it unlocks a portion of Age 2's tab in Advancements. Also, you can pick up the alter you craft the talisman in with carry on.

**Comment by Darkosto** [comment]
I cannot reproduce entering the dimension before Stage 2. Are you certain your stages were correct at the time?

**Comment by justinrusso** [comment]
The dimension itself is even restricted, so I have a feeling there was a stage miss-match again as well...

**Comment by Darkosto** [comment]
Yeah, I'm standing in the portal with no stages and am not being transported.
