### ISSUE TITLE
Crafting Table on a Stick craftable but not working in S1

### ISSUE THREAD

**Issue by BryanBoru** [Darkosto/SevTech-Ages#688]
Beta3

Stage 1
Craft a crafting table on a stick
Hold in either hand and right click to open
nothing happens

**Comment by Darkosto** [comment]
I've tried this out and can't reproduce:

https://i.artdude.uk/darkosto/gQBcLoGp.mp4

**Comment by Buuz135** [comment]
I does happen to me too https://i.imgur.com/vhjyA4x.gifv but only happens in a server

**Comment by Darkosto** [comment]
https://github.com/Ellpeck/ActuallyAdditions/issues/1051#issuecomment-373816423

**Comment by BryanBoru** [comment]
Apologies, I should have mentioned Multiplayer

**Comment by BryanBoru** [comment]
Fixed in latest release [r133](https://github.com/Ellpeck/ActuallyAdditions/blob/master/update/changelog.md)
