### ISSUE TITLE
Primal Tech Kiln

### ISSUE THREAD

**Issue by pennyvise1** [Darkosto/SevTech-Ages#689]
sevtech beta 3
PrimalTech-0.2.97

Recreate:
Put down kiln with fire source underneath. Place hopper on top. Chest on top of hopper.  Put stack of items in kiln.

Hopper will continue to feed items in after each operation is done and items will disappear. Not sure if this is intended or a bug but using a flame grilled whopper underneath does not destroy items, not having the item automatically extraced does.

**Comment by justinrusso** [comment]
Is this on a server? I cannot replicate

**Comment by Darkosto** [comment]
I'm confused, are you saying you put an entire stack of item into the kiln?

**Comment by vadis365** [comment]
Also what hopper are you using to supply the kiln and extract from the chest?

**Comment by justinrusso** [comment]
I was able to replicate it. Just put a stack in the chest and let a hopper put it into the kiln. The item cooks, then the next one gets fed in

**Comment by vadis365** [comment]
which hopper pls?

**Comment by vadis365** [comment]
yup, will fix now ;)

**Comment by vadis365** [comment]
fixed - good thing this issue wasn't just discovered a week before pack release, because that could have been embarrassing for me :P
