### ISSUE TITLE
Bear Claw Paxel mining issues

### ISSUE THREAD

**Issue by MrHrulgin** [Darkosto/SevTech-Ages#693]
Beta 3

The bear claw paxel won't mine raw Chisel or Rustic stone types. I know it's not supposed to harvest crafted blocks, but there's no exception for the raw stone when excavating.

**Comment by Darkosto** [comment]
I've lowered the mining level, which won't help this particular issue. Unfortunately, we're not able to do much with it as its not supposed to be a tool for everything but rather select blocks with fast mining speed.
