### ISSUE TITLE
Seared Brick Casting Channel doesn't trigger achievement

### ISSUE THREAD

**Issue by MrHrulgin** [Darkosto/SevTech-Ages#695]
In Beta 3, the seared brick channel doesn't qualify for the Follow My Channel Plz achievement. Given that the porcelain and seared brick channels are equivalent and unlocked at the same time, can either one trigger the achievement?

**Comment by Darkosto** [comment]
The Tconstruct channel is now added to the advancement, should be good in dev. Thanks!
