### ISSUE TITLE
Fire Pit Visual Glitch & Meats Not Place-able

### ISSUE THREAD

**Issue by CrossMyDNA** [Darkosto/SevTech-Ages#7]
Items in the fire pit visually disappear while they are being cooked. So far it has happened with mutton and fish.

"Mystery Meat" (dropped from a Butcher) and raw rat meat can't be placed in fire pit.

**Comment by Darkosto** [comment]
Ahhh, this one needs to be added manually. Let me know of anything else you did that doesn't work in the pit. Thanks!

**Comment by CrossMyDNA** [comment]
Here is everything that can't be placed in a fire pit (I realize some of these will only be attainable after you're no longer using the fire pit):

- Raw bear meat
- Raw ghast meat
- Raw venison
- Raw buffalo meat
- Raw meef
- Raw rat meat
- Mystery meat
- Ground meat

**Comment by Darkosto** [comment]
I need to add the remaining items to be cooked, which is on my end to fix. 

@turkey2349 can you work on fixing up the render issue? It's been a confusing bug for many players.

**Comment by Turkey2349** [comment]
I should be able to look into it tomorrow!

**Comment by Darkosto** [comment]
All of these meats should be available in the firepit now. Except for Raw Ghast meat, what the heck is that 0.0

**Comment by darkhax** [comment]
One thing I have noticed in alpha 2 is that the fire pit does not show when it is lit. Right clicking will make the lit sound and light the fire pit, but there is no visual indication that it's lit. It will also burn me if I step on it.

**Comment by justinrusso** [comment]
I was messing with this for another bug yesterday. Tried with mutton and it does stay visible. There is also visual and audio indication when the pit is lit.

**Comment by Turkey2349** [comment]
Should have all been fixed awhile ago.
