### ISSUE TITLE
XRay bug

### ISSUE THREAD

**Issue by Fireztonez** [Darkosto/SevTech-Ages#70]
Hi Darkosto!.
I see a little XRay bug when I look on certain angle the water. 

Is little hard for me to explain what can cause de bug, but is not happen everywhere, but is look like chunk based position. when I go just on the chunk at the front is good, when I go the chunk at the right is different, but whorst...

Other think I see, is always at specific angle... sometime is at 50+, other chunk 60+...

![sevtech-xray-bug](https://user-images.githubusercontent.com/19277301/30193344-8803cd0a-941a-11e7-9421-f104c456b057.jpg)

![sevtech-xray-bug-infos](https://user-images.githubusercontent.com/19277301/30193744-0c281120-941d-11e7-965a-eb219229f95e.jpg)

**Comment by Jandakast** [comment]
From the screenshot it looks like a chunk render error that is not specific to SevTech. It happens sometimes even in Vanilla. You can try holding F3 and hitting A to reload all chunks. If that doesn't fix the problem you will need to exit to main menu and then load back into the world.

**Comment by Darkosto** [comment]
Honestly, this looks to be a bug not fixable by the pack. I've seen it happen in most other packs and sometimes vanilla. I'll close this one due to my inability to fix it up.
