### ISSUE TITLE
Iron Block Light and chisels showing up in Stage 1

### ISSUE THREAD

**Issue by MiniKatalyst** [Darkosto/SevTech-Ages#701]
(In Beta 3)
Hello, I've made it in to stage one. I was curious as to what ores I am now exposed to and typed in Iron, here I came across that the Iron Block Light isn't staged properly then I noticed some other iron related items are visible too. I found it suspicious as iron its self is still restricted.

![image](https://user-images.githubusercontent.com/37491065/37561789-d8d3eb20-2aab-11e8-9e65-16a658a93d89.png)

![image](https://user-images.githubusercontent.com/37491065/37561790-e90985ae-2aab-11e8-9124-37c6100d5109.png)

![image](https://user-images.githubusercontent.com/37491065/37561794-0cf0f768-2aac-11e8-83dc-609c1fe3dafd.png)

**Comment by Darkosto** [comment]
Should be good to go! Fixed in dev.
