### ISSUE TITLE
[Beta 3]Age 3 ores Platnum, Redstone, Lead/Silver, and Limonite still have Lorum ipsum advancement text

### ISSUE THREAD

**Issue by MongoTheElder** [Darkosto/SevTech-Ages#709]
Working as intended?

![2018-03-18_16 15 43](https://user-images.githubusercontent.com/29290246/37570553-a80117fe-2ac7-11e8-8ef4-f4d18cfb6208.png)

**Comment by Darkosto** [comment]
Yep, already fixed in dev :)
