### ISSUE TITLE
[Beta 3] Bone Sword vs Sharp Bone

### ISSUE THREAD

**Issue by SonOfDiablo** [Darkosto/SevTech-Ages#710]
I noticed that a Bone Sword is worse than a Sharp Bone (in damage).

Is this intended?
If it is I don't see the idea in making a Bone Sword, specially when you take into account that the Bone Sword takes a Sharp Bone in it's recipe.

![image](https://user-images.githubusercontent.com/9123250/37570842-46b699aa-2af5-11e8-9a4d-ec6e2441deb1.png)

![image](https://user-images.githubusercontent.com/9123250/37570843-4cf2bcfe-2af5-11e8-979b-84abdf0bf9d6.png)

**Comment by sarcastic6** [comment]
It's worth noting that the sword has a durability of 195 vs the 135 of the sharp bone, so that may be an intended compromise...

**Comment by SonOfDiablo** [comment]
Well you use 2 bones to craft the sword, so it's not that big of an improvement really.
Not in my eyes at least, though I won't argue against the logic if that is the intent :)

**Comment by Darkosto** [comment]
At the end of the day, this is just an issue from having different mods add different items. We don't have the functionality, that I'm aware of, to begin revamping the entire weapon system to make more sense.
