### ISSUE TITLE
Test Creating Side Quest Stages

### ISSUE THREAD

**Issue by Darkosto** [Darkosto/SevTech-Ages#711]
Instead of doing it the way we did for the Baykok stage, what if we created a stage called "Bow and Arrow" and that would unlock via Baykok Or stage 2. That should take care of the "double-staging" issue.

Use this same idea, if it works, to stage other early stuffs.

Like Journey Map.

**Comment by justinrusso** [comment]
Theres no reason this shouldnt work, but the reason we had baykok was the special bow

**Comment by Darkosto** [comment]
Works with journeymap, so good.
