### ISSUE TITLE
Something is amiss in the nether

### ISSUE THREAD

**Issue by MongoTheElder** [Darkosto/SevTech-Ages#713]
My portal spawned in a fortress. I dug through a wall to a blaze spawner and it started generating wither skellies. FPS dropped to below 1.

![2018-03-18_18 19 36](https://user-images.githubusercontent.com/29290246/37571889-44e7663e-2ad9-11e8-99d8-1bdf5b42469f.png)

![2018-03-18_18 20 04](https://user-images.githubusercontent.com/29290246/37571892-4881c69a-2ad9-11e8-8dc4-5a07f4cc2770.png)

**Comment by MongoTheElder** [comment]
![2018-03-18_18 29 28](https://user-images.githubusercontent.com/29290246/37571965-79260eae-2ada-11e8-9d73-729c4db81f58.png)

**Comment by Darkosto** [comment]
Should be fixed in Beta4.
