### ISSUE TITLE
[Beta 3] Weak Dowsing Rod and Aquamarine Ore

### ISSUE THREAD

**Issue by SonOfDiablo** [Darkosto/SevTech-Ages#714]
The Weak Dowsing Rod (and probably also the rest) from Prospectors don't react to Aquamarine Ores from Astral Sorcery

**Comment by Darkosto** [comment]
Aquamarine ore from Content Tweaker has been added in dev.

**Comment by querns** [comment]
The Weak Dowsing Rod (`prospector_lowest`) is still missing `contenttweaker:sub_block_holder_0/0` in its ore whitelist, still. This makes it unable to pick up Aquamarine Ore, despite being available when Aquamarine Ore is possible to get (Age 1.) The Tough Dowsing Rod (`prospector_low`) properly contains this block in its whitelist.
