### ISSUE TITLE
[Beta 3] Netherrack is not mineable with Diamond level tools

### ISSUE THREAD

**Issue by MongoTheElder** [Darkosto/SevTech-Ages#718]
Netherrack is necessary to make the blast furnace for steel. Tired a Tinker's Iron pick and a Steelleaf pick, both diamond level. The Tinker's pick is unable to break the block (but punching it does). The Steelleaf pick can break the block but nothing isdropped. This happens for vanilla netherrack as well as NetherEx versions. Similar to issue 345?

Note: Nether Quartz is OK.

**Comment by Darkosto** [comment]
What? It should be the exact same level as MC Stone. This is really strange.

**Comment by Darkosto** [comment]
Sorry, I take that back. The mining level is set to obsidian level tools and up.

**Comment by Darkosto** [comment]
Should all be down to Diamond level (iron pick).
