### ISSUE TITLE
Alloy kiln extraction issues

### ISSUE THREAD

**Issue by MrHrulgin** [Darkosto/SevTech-Ages#719]
Beta 3:

Neither a hopper nor a dung pipe will extract from an alloy kiln. Is this intended behavior?

**Comment by Darkosto** [comment]
That's just how the mod itself is. If the mod didn't choose to allow the block to be extracted from then there isn't anything that can be done about from the hoppers/dung pipe's side.

This would best brought up in the Immersive Engineering tracker as a feature request.
