### ISSUE TITLE
EFLN tooltip says safe for mining but destroys ores.

### ISSUE THREAD

**Issue by NeosGhost** [Darkosto/SevTech-Ages#721]
EFLN drops cobble when used on a coal ore vein but very little coal.

Recipe doesn't show in jei but is craftable...is it possible it was meant to be removed and never did? If it was intentional would it be possible to change the tooltip to read 'not' safe for mining?

SevTech Beta v3 
forge 2627
![image](https://user-images.githubusercontent.com/16095247/37580011-71b91d84-2b0f-11e8-8644-461fb90b5c89.png)

**Comment by Darkosto** [comment]
To be fair, nothing but the player using a pickaxe can mine ores that were previously hidden due to how orestages work. This item still has use in other dimensions so the tooltip is not 100% incorrect.

**Comment by Darkosto** [comment]
Actually, I can't change the tooltip without the mod changing it. Going to just remove the item then.
