### ISSUE TITLE
Primalcore stone worldgen is overwriting Geolosys

### ISSUE THREAD

**Issue by MrHrulgin** [Darkosto/SevTech-Ages#722]
Beta 3:

There's a PrimalCore/Geolosys conflict, as shown [here](https://imgur.com/a/26ghq). It looks like PC generates after Geolosys, and can overwrite veins of ore. Intentional? Accidental side effect of other choices?

**Comment by Darkosto** [comment]
When it comes to certain mods/generations it can't always be helped.

This is the current list of blocks in dev that can be generated into:

   minecraft:stone:0
        minecraft:stone:1
        minecraft:stone:2
        minecraft:stone:3
        minecraft:dirt:0
        rustic:slate
        chisel:marble2:7
        chisel:limestone2:7
        chisel:basalt2:7
        primal:schist_blue_stone
        primal:ferro_stone
        primal:mud_wet
        primal:terraclay_block

If you have more that need to be added. Outside of that, I'm going to close this since I've added more blocks to the list.
