### ISSUE TITLE
[BETA3] Allow advancement "Defeat the Endermenace!" to be completed by killing enderminis

### ISSUE THREAD

**Issue by Buuz135** [Darkosto/SevTech-Ages#724]
### Issue / bug
 - Explain the issue / bug as understandably as possible.
 - If possible add minecraft, forge, java and modpack version numbers for debugging (mod authors might need these).
 - If the issue/bug is recurring explain how it can be recreated (helps darkosto!).
 - If possible add error/crash log to [Pastebin](https://pastebin.com/) and link it here (if you dislike pastebin any other similar site is fine too).
 - If possible add a video/gif of the issue/bug (makes it easier for darkosto to understand you).

**Comment by Darkosto** [comment]
Added all endermen in dev!
