### ISSUE TITLE
Sandy Brick mats restricted or removed

### ISSUE THREAD

**Issue by BryanBoru** [Darkosto/SevTech-Ages#725]
Beta 3
MP server

At Stage 2, you can make bricks and the variations (Sandy, Lava, Dragon) and can make Stairs, Slabs and other variations of Dragon and Lava bricks, but Sandy is restricted to Cable Facade

**Comment by BryanBoru** [comment]
I believe Quark adds the brick variations? Do not know if that is the version of the mats we are using, but the disparity between them is odd if so.

**Comment by Darkosto** [comment]
Removed from game in dev.
