### ISSUE TITLE
Suggest a use for Shark Fin or it's removal

### ISSUE THREAD

**Issue by BryanBoru** [Darkosto/SevTech-Ages#726]
Beta 3

I checked with all advancements granted and it appears the Sharks Fin has no use throughout the game other than inventory clutter and a useless trophy.  
I might suggest a 'shark's fin soup' as a cauldron recipe, or possibly incorporating it in something else early/mid-game. Otherwise removing it would reduce the clutter and uselessness of it's drop.

**Comment by Darkosto** [comment]
I don't really feel morally okay with having Shark Fin Soup being an item in the game. I will probably remove the item instead.

**Comment by BryanBoru** [comment]
I honestly appreciate everything about this reply, was just trying to find a use for such a drop in the first place. Thanks as always Sir.

**Comment by Darkosto** [comment]
Fixed in dev.
