### ISSUE TITLE
Petty Tartaric Gems Recipe conflicts with introduction

### ISSUE THREAD

**Issue by Serolar** [Darkosto/SevTech-Ages#727]
#Issue/bug
Petty Tartaric Gems, Required part for crafting the reagents of the sigils of stage one, needs "redstone, Gold Ingot, Glass, and Blue Dye" most are found in stage two. 
Solution: Change Recipe to fit stage one. 

Sevtech Beta 3

Thanks for your time!
Serolar

**Comment by Darkosto** [comment]
Already reported and fixed for Beta4.
