### ISSUE TITLE
Blood Lamp Reagent requires later stage gem

### ISSUE THREAD

**Issue by Serolar** [Darkosto/SevTech-Ages#728]
### Issue / bug
the Blood Lamp Reagent(?) needs 300 Will Quality to craft, beyond the maximum capacity of the Available Gems, (256)
Solutions: 1. Change Recipe to be at or below 256, or 2. Change Stage to Two.

Sevtech Beta 3

**Comment by Darkosto** [comment]
Reduced the cost to 200 for the reagent in Dev.
