### ISSUE TITLE
Horse Power Press deletes items

### ISSUE THREAD

**Issue by Dawenzel** [Darkosto/SevTech-Ages#73]
When using the horse power press with a (w)hopper as input it tends to delete items that are being inserted when it's already full(enough items to craft once).

## Bug 
- The press accepts more items than it can use to make 1 (com)pressed item. In doing so it deletes the items that are not being used in the first craft.

## Reproduce
(The recipe used for testing was 4 clay -> 1 clay block.)
Place a press and connect a hopper as input for the press. Place 64 clay into the hopper and sit back to watch 60 clay vanish into thin air. Whoosh.....

## Versions
- Minecraft 1.12.1
- Forge 14.22.0.2464
- Java x64 8u144
- HorsePower  2.5.6.49

I couldn't find any errors in the logs related to this bug.

**Comment by Darkosto** [comment]
Hey @gorymoon have you had this issue or seen a report about it yet?

**Comment by GoryMoon** [comment]
I haven't had this issue or heard about it before, I haven't tested this in 1.12 either, only tested the part of not accepting when working in 1.11.2. 
It should be that when the amount of times for a recipe is inputted it won't accept until work is done and emptied. 
I will look at it

**Comment by GoryMoon** [comment]
This is now fixed in HorsePower 1.12-2.5.7.50 https://minecraft.curseforge.com/projects/horse-power/files/2481444
