### ISSUE TITLE
[Beta 4]Applied Energistics 2 Wooden Crack not craftable

### ISSUE THREAD

**Issue by MongoTheElder** [Darkosto/SevTech-Ages#731]
The Wooden Crank recipe produces a Spindle instead of a Wooden Crank

![2018-03-19_21 18 44](https://user-images.githubusercontent.com/29290246/37630543-8655385c-2bbb-11e8-9542-2ebdbfc71880.png)

![2018-03-19_21 18 49](https://user-images.githubusercontent.com/29290246/37630545-89307c6c-2bbb-11e8-8795-2ab1bb25149c.png)

**Comment by Darkosto** [comment]
Will take a look!

**Comment by Darkosto** [comment]
@MongoTheElder Can you remove FastWorkbench from the mod list and tell me if it still happens, please?

**Comment by MongoTheElder** [comment]
Nope, still crafting a spindle with FastWorkbench disabled

**Comment by Darkosto** [comment]
Fixed up in dev.
