### ISSUE TITLE
Recipe for repairing Gearbox missing

### ISSUE THREAD

**Issue by BryanBoru** [Darkosto/SevTech-Ages#733]
Beta4
SP/MP

BWM gearboxes (`betterwithmods:wooden_gearbox`) are made to break due to weather and wear, etc.
Intended to be repaired by using the broken gearbox (`betterwithmods:wooden_broken_gearbox`) in a recipe to create a new gearbox as a result. 
no recipe exists. 
Unsure if this was intentional.

**Comment by Darkosto** [comment]
Right click the broken gearbox with 2 wooden gears in hand.

**Comment by Darkosto** [comment]
Clarified in dev.

**Comment by BryanBoru** [comment]
Ooops. My only experience with them was in the Nether in Lost Sould, fo r some reason I remembered it as a recipe, either way thanks!
