### ISSUE TITLE
[Beta 4] Unable to extract creosote oil from Coke Oven using the bucket slot

### ISSUE THREAD

**Issue by MongoTheElder** [Darkosto/SevTech-Ages#734]
The bucket slot (upper right corner of GUI) doesn't accept buckets (tried vanilla and weedwood buckets) nor BC tanks to retrieve creosote oil. BC pipes work to extract the oil into a tank but the redstone engine is blocked behind treated wood.

**Comment by darkphan** [comment]
[Workaround](https://i.imgur.com/nvdw11q.png) :D

**Comment by Darkosto** [comment]
Correct, this is an issue with IE and not the pack from what I've seen. The only way to extra is pipes or the faucet like @darkphan did in that picture.

Unfortunately, There's not much I can do about this especially since the dev of IE has slowed down considerably.
