### ISSUE TITLE
[Beta 4] Breaking IE Alloy Kiln or Coke Oven drop a multiblock item

### ISSUE THREAD

**Issue by MongoTheElder** [Darkosto/SevTech-Ages#735]
If you break an IE Alloy Kiln or Coke Oven, you get a block drop that shows as the entire multiblock structure and a duped kiln/oven block.

Placing the block shows the entire multiblock structure although it occupies a single block space.

![2018-03-19_23 46 58](https://user-images.githubusercontent.com/29290246/37635075-d8b30638-2bcf-11e8-9c91-73bc0665deb2.png)
![2018-03-19_23 47 00](https://user-images.githubusercontent.com/29290246/37635077-db37eba8-2bcf-11e8-9776-d6a9e7dd878b.png)
![2018-03-19_23 47 03](https://user-images.githubusercontent.com/29290246/37635078-dcd7a106-2bcf-11e8-92a6-a6ae1e8744ac.png)

**Comment by Buuz135** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/issues/2891

**Comment by Darkosto** [comment]
Fixed!
