### ISSUE TITLE
Weedwood sticks are not craftable - needed for tools/weapons

### ISSUE THREAD

**Issue by RTHauke** [Darkosto/SevTech-Ages#737]
Beta 4, Age 2 + Between Lands base achievements.

Cannot make weedwood tools or weapons as the sticks are not craftable.  No recipe found searching the scripts folder.

**Comment by darkphan** [comment]
There are bushes in The Betweenlands that you have to break and they drop the weedwood sticks.

**Comment by Darkosto** [comment]
Correct, they are not craftable and that is why the advancement gives you the information on where to find them.
