### ISSUE TITLE
Breaking IE Diesel Gen drops generator item.

### ISSUE THREAD

**Issue by Syltann** [Darkosto/SevTech-Ages#738]
So my diesel generator wasn't working after the beta 4 update, so I thought I'd break it down and rebuild it. As i broke the corner generator block it dropped a "Diesel Generator" item. Happened when I broke both my Diesel Gen's.
![2018-03-19_23 49 03](https://user-images.githubusercontent.com/30686588/37640057-1cb89ba8-2bd1-11e8-9813-54e4e7c1e747.png)

**Comment by Buuz135** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/issues/2891

**Comment by justinrusso** [comment]
Same issue in https://github.com/Darkosto/SevTech-Ages/issues/735
