### ISSUE TITLE
work stump mk2 duplicates items when inventory is full

### ISSUE THREAD

**Issue by mmediacentral** [Darkosto/SevTech-Ages#74]
Found a dup bug with the work stump mk2. Place item into a slot, then with my inventory completely full (same Item on stump isn't  in inventory), when I shift-right click the item off, it takes it out without actually removing from the stump.

**Comment by vadis365** [comment]
Wrong mod dev.
I think it is to do with realistic item drops firing the item toss event and causing the dupe.

**Comment by Darkosto** [comment]
Heya @funwayguy

**Comment by Darkosto** [comment]
Looks fixed on my end! Thanks!
