### ISSUE TITLE
Samples Should Not Need Pickaxes

### ISSUE THREAD

**Issue by Darkosto** [Darkosto/SevTech-Ages#740]
The Silicon Samples require a pickaxe as the proper tool. They need to be hand-broken like the vanilla geolosys samples. This causes issues like not allowing the player to harvest them as rocks and probably the reason they drop samples instead of rocks when broken during a hidden stage.

**Comment by justinrusso** [comment]
I've made a PR for this: https://github.com/The-Acronym-Coders/BASE/pull/92

**Comment by justinrusso** [comment]
https://minecraft.curseforge.com/projects/b-a-s-e/files/2544345
