### ISSUE TITLE
Natura Barley and Bluebells spawn in the Betweenlands

### ISSUE THREAD

**Issue by RTHauke** [Darkosto/SevTech-Ages#743]
Not sure if it's intended or not but I have found Barley spawning there.  Definitely looks out of place!

**Comment by RTHauke** [comment]
Created a test world and did more searching, also found the Bluebells spawning.  They aren't too bad and blend in better than the barley.

Beta 4, New world

**Comment by RTHauke** [comment]
![image](https://user-images.githubusercontent.com/15672554/37695754-ec83672e-2ca7-11e8-913d-4f8e1a70aa0e.png)
![image](https://user-images.githubusercontent.com/15672554/37695768-03f13102-2ca8-11e8-82c2-1f2dce2466c4.png)

**Comment by Darkosto** [comment]
The dimension has been added to the Natura blacklist, hopefully the blacklist is actually functioning.
