### ISSUE TITLE
Osmium and Cinnabar in The Between Lands

### ISSUE THREAD

**Issue by RTHauke** [Darkosto/SevTech-Ages#744]
Beta 4, New world, creative
Found ore samples for Osmium and Cinnabar.  Did not have a chance to run world stripper to validate veins.
![image](https://user-images.githubusercontent.com/15672554/37695824-86b825fa-2ca8-11e8-93dc-36134d6ade05.png)
![image](https://user-images.githubusercontent.com/15672554/37695833-9b13d616-2ca8-11e8-9498-5f2176dda9d9.png)

**Comment by justinrusso** [comment]
Did you give yourself all the stages? I assume this report is JUST about the fact that they spawn there, not that you see them?
