### ISSUE TITLE
Backpack recipe is unclear (Beta 4)

### ISSUE THREAD

**Issue by kugamer** [Darkosto/SevTech-Ages#746]
When you search the backpack recipe in JEI, the base backpack does not link strait to the base recipe. It links to the backpack with a color variant. If you click on the base backpack within the color variant recipe it does not take you to the base recipe, nothing happens. You have to scroll through the recipes and find the base recipe. Would be nice if it linked to the base recipe.

**Comment by Darkosto** [comment]
There's not very much we can do about ordering recipes. If they show in this way then you'll have to just use the arrows to look through the recipes.
