### ISSUE TITLE
[Beta4] Shark meat not drying on drying rack

### ISSUE THREAD

**Issue by VallenFrostweaver** [Darkosto/SevTech-Ages#747]
### Issue / bug
 - I placed a slice of raw shark meat on a drying rack from Tinkers' but after many many days it never changed into a dried version. I also tried this with a salmon and it did work.
 - Forge 14.23.2.2629  Java: 1.8.0_161
![sevtech](https://user-images.githubusercontent.com/13642054/37713553-2f865790-2d0f-11e8-9050-d6e3b1234101.png)

**Comment by Darkosto** [comment]
Added to the drying rack list.
