### ISSUE TITLE
Advancements not loading in single player

### ISSUE THREAD

**Issue by calog3no** [Darkosto/SevTech-Ages#75]
Loaded new world and got this screen
![2017-09-19_08 24 48](https://user-images.githubusercontent.com/25380281/30592278-21365bda-9d14-11e7-9c48-dd45aab0a56f.png)
deleted world and made a new world and got same issue
Loaded Modpack with Twitch app and advancements were present. I may have possibly a corrupt MultiMC will delete and reinstall to see if that resolves the issue 
Reinstalled on MultiMC still have the same issue

**Comment by Darkosto** [comment]
There's nothing to show if you haven't done anything yet. The first advancement requires that you break a block, pick something up, etc.

**Comment by Blargerist** [comment]
Would probably be a good idea to add 
addCriteria("location", "minecraft:location")
to the stage0 root, so that it is immediately visible. Cut down on confusion.

**Comment by calog3no** [comment]
Dark I opened advancements on my Twicht app ver before I broke any blocks and it was there. I did break blocks, opened inventory and picked blocks and sticks on all the worlds in my MultiMC instance, but still got that blank screen. Blargerist yeah sorry I'll make sure to log that type of info next time I post.

**Comment by Darkosto** [comment]
Discovered this issue is actually related to a bad import into MultiMC using the twitch export zip. I'll have different zips for each platform on the next alpha version.
