### ISSUE TITLE
[BETA 4] AUTOMATED USER, LIGHTWELL MAJOR DUPE BUG

### ISSUE THREAD

**Issue by Syltann** [Darkosto/SevTech-Ages#757]
While using the automated user from cyclic on the lightwell from astral sorcery I have  discovered a HUGE dupe bug that will dupe a lot of items easily (all the items I've tried anyway). 

To reproduce just face the user against the lightwell and feel it some coal and change the redstone mode to always active. It should start working, now put an item into the input slot of the user and watch the magic happen! (The output should start to fill up)
![2018-03-22_05 26 46](https://user-images.githubusercontent.com/30686588/37770436-a563b124-2d91-11e8-9902-46b69ee8776d.png)

**Comment by PrinceOfAmber** [comment]
Im releasing a fix for this tonight. and probably a blacklist too in case something else comes up

**Comment by Darkosto** [comment]
All fixed!
