### ISSUE TITLE
Cyclic Torch Launcher works in The BetweenLands Dimension

### ISSUE THREAD

**Issue by JackRuby1** [Darkosto/SevTech-Ages#759]
Torches placed with the Torch Launcher from Cyclic don't turn into Damp Torches like normally placing torches do.

**Comment by Darkosto** [comment]
Yeah, I mean, I can remove the item because of this one issue or leave it due to the number of players using it for its convenience purposes.

Not really much of a winning situation.

**Comment by Darkosto** [comment]
Going to keep this one in, it's probably fine :P
