### ISSUE TITLE
ImmersiveCraft Placers and Carry-On Interaction

### ISSUE THREAD

**Issue by Vyraal1** [Darkosto/SevTech-Ages#761]
### Issue / bug
 - Carry-On lets you pick up the 'placers' that ImmersiveCraft uses to hang items on the wall.

**To Reproduce**: Hang an item using ImmersiveCraft by pressing P with it in your hand onto a block. Then shift right click the the same side of the block and instead of picking up the block, it'll pick up the 'placer' item that ImmersiveCraft uses to hang items. Maybe blacklist ImmersiveCraft placers from Carry On?

**Comment by Darkosto** [comment]
Should be: 
immcraft:in_world_vertical_placer
and
immcraft:in_world_placer

Both added to the blacklist will test to make sure.

**Comment by justinrusso** [comment]
👍
