### ISSUE TITLE
Make sure everything is hidden for all players when the pack starts

### ISSUE THREAD

**Issue by Darkosto** [Darkosto/SevTech-Ages#762]
Facades, etc. need to be turned off so the 1/2 page of items in the tutorial are the only things that show up.

**Comment by Darkosto** [comment]
This should be good and was only an issue because players changed resource packs without a client restart.

I'm going to check this once more when I download a fresh version from ATL.

**Comment by justinrusso** [comment]
Only thing left is 2 liquids from GC that cant be done I think, and Mekanism Gasses
