### ISSUE TITLE
YoYo and unique parts are Showing Up for Every Tcon Tool Type Even when not craftable

### ISSUE THREAD

**Issue by Darkosto** [Darkosto/SevTech-Ages#769]
Slime Vine, Feather, Leaf, Slimeleaf, ice, hemp 

These are unique and not available for every tool. They needed to be handled differently so they don't create extra items in JEI. Or just blacklisted in the JEI in-game menu.

**Comment by justinrusso** [comment]
I've been blacklisting these in JEI. I did this not that long ago... could you have reloaded and saw them?
