### ISSUE TITLE
Make wood log (one of the first adv) on inv change not on break

### ISSUE THREAD

**Issue by justinrusso** [Darkosto/SevTech-Ages#770]
Breaking with an empty hand seems to still meet the criteria.

**Comment by Blargerist** [comment]
Looking into fixing this in Triumph.

**Comment by justinrusso** [comment]
Is there documentation on the way we use it? All Ive found if I recall is JSON stuff for Triumph.

**Comment by justinrusso** [comment]
Triumph added a feature for this I believe, but for this situation, we made it an on inventory change.
