### ISSUE TITLE
Linux missing registry entries

### ISSUE THREAD

**Issue by justinrusso** [Darkosto/SevTech-Ages#774]
https://pastebin.ubuntu.com/p/jx38XqdWpd/

**Comment by KryptDev** [comment]
You JUST beat me to this issue :)

**Comment by artdude543** [comment]
Am I assuming you're trying to connect to a server? Could you get a hold of the server logs also? This will help with working out what's going on.

**Comment by TwilightPSN** [comment]
would like to add my server log not sure on server hosts os but im running w10 in case it will help

https://gist.github.com/TwilightPSN/cbce0fb7407d2a99e27e93e4f5dbd2cb

**Comment by jlnarron** [comment]
server log:https://pastebin.com/TWT4GdHC

**Comment by artdude543** [comment]
Caliper needs to be removed from the server. Can you do that and try again @TwilightPSN

**Comment by artdude543** [comment]
This issue can also be linked to broken uploads of files to the server. So can you all/person try a complete wipe of the mods folder and re-upload all the mods. (Also make sure your libs and Forge version are correct and up to date_

**Comment by artdude543** [comment]
@jlnarron that's not a full server log. Pastebin the entire thing please along with your client logs. So we have both to compare/review.

**Comment by TwilightPSN** [comment]
@artdude543 https://gist.github.com/TwilightPSN/178c4c3f6c9fa1eafe9cc6804b2ca2cd removed caliper on the server still same issue ive also reuploaded mods about 3 times

**Comment by KryptDev** [comment]
This is an issue with PNC. I don't think we can do anything until an update is released. This will happen if you use a Windows Client connecting to a Linux server. I believe you can fix this if you run the server on Windows as well.

**Comment by justinrusso** [comment]
I believe this is an issue with Crafttweaker. The zipped file on linux is not properly being handled.

**Comment by artdude543** [comment]
I run all my servers on Linux and their running fine on the new release. So I doubt it's that tbh.

**Comment by justinrusso** [comment]
People unzipped and created a new world and it seems to work...

**Comment by artdude543** [comment]
Okay, I can reproduce on my Rasperian instance but Ubuntu seems fine. There were some changes to ZenScript which according to the code fixed Linux cases. Not sure if the build of CT we are using contains that update to Zen.

**Comment by justinrusso** [comment]
We are using a zip this time, im curious if its related. Can you get me the crafttweaker.log file?

**Comment by justinrusso** [comment]
Crafttweaker.log from an erroring server https://gist.github.com/justinrusso/8d4fe7ff1393fc03a6a249a9aee87cf8

**Comment by Bendder** [comment]
I too am getting, what I believe to be. the same error with my Server install.  
I installed the server via copying my install from my Windows machine to my Linux Server (Ubuntu 16.04).  I then setup forge-1.12.2-14.23.2.2634-universal.jar (I ran the installer for that version).  I then have a script that starts the server (using the additional parameters provided to Sev).  It's like the server loads fine but whenever a user tries to connect, they get the "Fatally missing registry entries" error.  

My latest.log file: 
[latest.log](https://github.com/Darkosto/SevTech-Ages/files/1844680/latest.log)
My debug.log file:
[debug.log](https://github.com/Darkosto/SevTech-Ages/files/1844682/debug.log)

**Comment by DingoX3** [comment]
Has anyone found a fix? I'm trying to run it on a hosted server. Everyone is getting fatally missing registries when they try to connect and sometimes it says authentication servers are down but they arent down.. The full log is so big i cant even put it on paste bin to link it because of all the scripts text.

Is this a possible issue? 

* A broken ore dictionary registration with name dustSalt has occurred. It adds an item (type: class ferro2000.immersivetech.common.items.ItemITBase) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.

**Comment by justinrusso** [comment]
An update is in the works for Twitch App, and the ATLauncher release will work fine.

If youd like to do this manually, go into `minecraft/scripts` and unzip `scripts.zip` into the scripts folder. It should result in something like the following:

![image](https://user-images.githubusercontent.com/25138621/37867920-b6127d44-2f75-11e8-975b-7706fe3643dd.png)

**Comment by DingoX3** [comment]
Thank you @justinrusso  for explaining that and the image. That fixed the issue. We have completed stage -0 "get the server up and running". :)

**Comment by justinrusso** [comment]
There is now a patch out (3.0.1) that fixes this as well.
