### ISSUE TITLE
Items in inventory keep switching spots rapidly

### ISSUE THREAD

**Issue by Gennable** [Darkosto/SevTech-Ages#776]
for some reason every time i open my inventory all the items keep moving around rapidly.... kinda weird..

**Comment by Buuz135** [comment]
Can you post a picture/video/gif of the issue?

**Comment by artdude543** [comment]
Yeah, we're going to need some evidence of the issue; I also can't produce the effect you're talking about in a fresh instance of the pack.

**Comment by Gennable** [comment]
https://twitter.com/twitter/statuses/977606396148682753

**Comment by Buuz135** [comment]
There is a quark featura that allows you to rotate inventory rows. You can disable that.

**Comment by artdude543** [comment]
Yup intended effect from Quark; disabling it will fix your problem :)

**Comment by Gennable** [comment]
I took out quark all together and my inventory is still shifting around constantly..
