### ISSUE TITLE
Mekanism & GC Fluids in JEI on Stage Tutorial. 

### ISSUE THREAD

**Issue by DenisMasterHerobrine** [Darkosto/SevTech-Ages#777]
### Enhancement
 - It's isn't an issue otherwise, but it looking strange to see them unhided, when created a world, it only annoyed me.
 - SevTech Ages: 3.0.0 Release.
 - Create a world and look at JEI.
 - There is no crashlog.
 - If possible add a video/gif of the issue/bug (makes it easier for darkosto to understand you). Here is a picture.
![2018-03-24_22 27 27](https://user-images.githubusercontent.com/27882185/37867009-536ffa56-2fb4-11e8-9806-e09d1cce147f.png)

**Comment by justinrusso** [comment]
This is known, we cant do anything about those currently

**Comment by Darkosto** [comment]
This is intended since it cannot be fixed.
