### ISSUE TITLE
Lag Spike when opening Inventory (NEI related)

### ISSUE THREAD

**Issue by MrTP** [Darkosto/SevTech-Ages#778]
After ~15 minutes into my first world (AGE 0 during the first night) the game started freezing for 2-3 seconds whenever I opened my inventory.
Restarting my world & the entire modpack did not have any effect.
I disabled NEI in the NEI options which completely fixed the issue.
This does not seem to have any negative effect on the game as far as I can tell because the item/recipe display on the right is handled by JEI.

**Comment by artdude543** [comment]
JEI can cause some issues with "client" side rendering lag. Usually, this will self-fix after a while (normally) can you confirm what memory you have allocated to the pack? And if you have customized the install I.E. Additional mods added to the pack.

**Comment by MrTP** [comment]
No additional mods installed.
7 GB of Ram allocated.
JEI is working fine though. 
As I said since I deactived NEI in the NEI options everthing is working as it was before, just without the lag.

**Comment by Posivated** [comment]
I am also having the lag when opening inventory issue in early game. 10GB of ram allocated, with just the pack installed.

**Comment by Neamow** [comment]
I have the same issue. How do you guys disable NEI to fix this? I go to Mod Options, find NEI, click disable, and nothing happens, and the lag continues.

**Comment by MrTP** [comment]
Open your inventory.
In the lower left corner there's an "Options" Button, click that.
Go to "Inventory Options"
Click on "NEI Enabled" to disable NEI

**Comment by Neamow** [comment]
Oh yeah that does fix it. However now I also wonder if this affects the pack progression in any way.

**Comment by justinrusso** [comment]
Maybe the same issue repoted in https://github.com/TheCBProject/NotEnoughItems/issues/153?

**Comment by Kuperus** [comment]
only thing i really mis when disabling NEI is the light overlay and chunk boundaries...

**Comment by Posivated** [comment]
You don't have to disable NEI entirely, just in the bottom right options menu when you bring up your inventory. I just enable/disable whenever I need light overlay or boundaries.

**Comment by artdude543** [comment]
Closing this as it's an old issue. And tbh can't be fixed on the pack side due to way too many factors/variables which could be causing this.

Just ensure your Java/Graphics drivers and up to date and pray to Notch.
