### ISSUE TITLE
[REQUEST] Slow down loading screen animation

### ISSUE THREAD

**Issue by Winrylive** [Darkosto/SevTech-Ages#779]
I adore the loading screen Sev/Darkosto animation but can we maybe low him down? He's a spastic little turd as he is right now.

**Comment by Buuz135** [comment]
What?

**Comment by ZephyrWindSpirit** [comment]
Seconded!
A kindly request for slowing down the animation for the loading screen. It is cute, but the excessive bouncing does give a headache. Headaches make a grumpy playerbase. Please and thank you.
Modpack version 3.0.0

**Comment by artdude543** [comment]
As it's a GIF it would have to be re-made however this would be a question for @Darkosto to answer. You could always minimize the game while it's loading if it bothers you too much 😄 

There was a slow version a while back but it looked a tad off also.

**Comment by Darkosto** [comment]
We've tried this, the animator made it about 10 times with varying frame rates/etc. and were unable to get it working. It may be a limitation of what the game allows us to do.

**Comment by zOwenn** [comment]
Minimising something doesnt kill the resources its wasting :3 - But it was quite iritating to start with, i brought it up (not a troll) and id prefer not getting a pissy response back (we have seen the discord Buuz :3).

Thanks for the response, was just a suggestion, but meh!

**Comment by artdude543** [comment]
Okay as this is a compat issue we can't fix this. 

Alt you could edit the `splash.properties` config to use this value instead.
`forgeTexture=fml\:textures/gui/forge.png`

This will change it back the default one :)
