### ISSUE TITLE
Dye crafting recipes need to be balanced

### ISSUE THREAD

**Issue by MongoTheElder** [Darkosto/SevTech-Ages#781]
Dye grinds to 2 powder in the Horsepower Grindstone but 1 powder is craftable back to 1 dye. Rinse and repeat for infinite dyes
![2018-03-24_14 37 21](https://user-images.githubusercontent.com/29290246/37867565-06cd28a6-2f71-11e8-85fc-3bbfd8d2b5e8.png)
![2018-03-24_14 37 33](https://user-images.githubusercontent.com/29290246/37867566-088404f8-2f71-11e8-95f2-f1da3e4f52a7.png)

Release 3.0.0

**Comment by Darkosto** [comment]
Yeah, honestly this is a temporary addition to allow players to transfer useless dyes into actually usable ones. It's being written out when all Vanilla dye has been fully removed.
