### ISSUE TITLE
Cannot set a keybind to "CTRL" or "SHIFT" - the key by itself not as a modifier

### ISSUE THREAD

**Issue by PrinceOfAmber** [Darkosto/SevTech-Ages#783]
### Issue / bug
Version 3.0.0 of modpack

In controls, go to bind any key to CTRL or SHIFT - for example in vanilla I always use ctrl to open my inventory.  Also in vanilla, you can bind to a single key, or ALSO bind a modifier such as SHIFT-F

What happens in the pack is when you try to bind to CTRL it tries to force you to use it as a modifier, doesnt let you set it up

GIF below of the bug

Ill try to also record one of how it happens in vanilla/other modpacks
![keybind](https://user-images.githubusercontent.com/621529/37868263-bfcef75a-2f60-11e8-8ce9-2335da66f0b6.gif)

EDIT: I think theres a workaround to just edit options.txt and set my keybind there ill report back if it works

**Comment by PrinceOfAmber** [comment]
How it normally works. 

im going to remove some mods and narrow it down to whats causing it

![keybind](https://user-images.githubusercontent.com/621529/37868384-915a5a84-2f62-11e8-9ffd-a852bb30a869.gif)

**Comment by PrinceOfAmber** [comment]
As a workaround, you can edit options.txt

so CTRL is 29

key_key.inventory:29
shift is 

key_key.sneak:42


If you want a combination you could use for example



key_key.sprint:33:CONTROL

where 33 is the regular key, so bind that, and then add in the modifier with :CONTROL at the end

**Comment by PrinceOfAmber** [comment]
I tried all the obvious mods standalone like Controlling and client tweaks,  trying to narrow it down.

Can confirm that with this specific subset of mods the bug does NOT occur.  Sorry i couldnt go further.

My guess is that its a conflict between 'Controlling-3.0.6' plus one or more other mods, but i could be wrong

![does not happen](https://user-images.githubusercontent.com/621529/37868819-1ef5d54c-2f6a-11e8-954a-3ee8d2ccb01c.PNG)

**Comment by justinrusso** [comment]
Not sure when something may have changed, but this appears to be fine now.

**Comment by PrinceOfAmber** [comment]
I can confirm this is fixed in 3.0.6 for me as well so something along the way must have updated :)
