### ISSUE TITLE
Camfire glitch?

### ISSUE THREAD

**Issue by Sharpskii** [Darkosto/SevTech-Ages#784]
i stepped on a camfire then it launched me across the map and i was able to move super fast untill i fell from a huge high due to the speed.

**Comment by PrinceOfAmber** [comment]
Does it happen every time you touch a campfire, or was it just the one fluke time?

**Comment by Sharpskii** [comment]
My game wasn't running to great, it happened the one time and after I allowocated more ram i haven't got it again.


-------- Original message --------
