### ISSUE TITLE
Advancements not populating for players in LAN multiplayer

### ISSUE THREAD

**Issue by Ktanaqui** [Darkosto/SevTech-Ages#787]
Launch 3.0 or 3.0.1 SevTech, Twitch Console. 
Host's Advancements work; Joining players do not populate at all.
Running in LAN multiplayer, cheats enabled.

**Comment by 630R63** [comment]
They populate after setting the stage for all players to tutorial and a restart of the pack.

An issue is already opened on the mod author's issue tracker.
https://github.com/Buuz135/Together-Forever/issues/6

**Comment by Ktanaqui** [comment]
I managed to get mine to populate, although I don't understand why.
![securityproperties](https://user-images.githubusercontent.com/25591540/37870125-1588f930-2f9c-11e8-9cc7-ba8eaf57491a.png)

This is my security tab in properties specifically for my SevTech Ages folder. (Obvious to most.) Two of the listings (Authenticated Users and Users) both lacked "Full Control." Authenticated Users had Modify, Users only had Read & Execute. Setting both to Full Control resolved the issue for me.

**Comment by artdude543** [comment]
This should be fixed in 3.0.3
