### ISSUE TITLE
Inventory issues still

### ISSUE THREAD

**Issue by Gennable** [Darkosto/SevTech-Ages#788]
Items keep rapidly shifting places in my inventory, originally it was thought to be quark, but i disabled and even took quark out of the pack, still having the same issues..
https://twitter.com/twitter/statuses/977606396148682753

though if im in the galacticcraft inventory panel everything stays put..

**Comment by 0xb00b** [comment]
Someone in discord pointed out this is probably Cyclic's row shift functionality.. http://muddrdev.com/webm/7be38f9b.webm

Could you check if you have a keybind for that configured?

**Comment by justinrusso** [comment]
Also try restarting your computer, or try a different keyboard. Possibly a button is "phantom" clicked

**Comment by Gennable** [comment]
ok yea it was cyclic, thanks for the help!
