### ISSUE TITLE
Different Mod Versions per launcher

### ISSUE THREAD

**Issue by Gunsup** [Darkosto/SevTech-Ages#790]
Twitch Launcher - Intergrated Dynamics 1.12.2-0.11.7

ATLauncher - Intergrated Dynamics 1.12.2-0.11.9

Caught it setting a server up for a friend and I to play on and he couldn't join me since the mod versions were different.

**Comment by justinrusso** [comment]
*think* this should be fixed now? Check the ATLauncher files, should be the same as Twitch's

**Comment by Darkosto** [comment]
Yep, fixed on ATL as of a bit ago.
