### ISSUE TITLE
Gears not registering, crafting disabled items

### ISSUE THREAD

**Issue by Turmfalke2** [Darkosto/SevTech-Ages#791]
Hi,
I am trying to get "Geared Up For Ratios", the first gear I crafted (4 sticks) turned into a "This Item is Disabled" from Applied energistics with no texture. The second gear I crafted (4 logs,1 stick) got me 4 gears from Tesla Core Lib, apparently they are not good enough for the quest?

**Comment by justinrusso** [comment]
Im not sure what his recipe is youre talking about. 4 sticks? Seems to be nothing for me. Curious - Are you on linux? What version of the pack as well, please.
![image](https://user-images.githubusercontent.com/25138621/37870280-fc76ed5e-2f9f-11e8-821e-28cbddb4213d.png)

**Comment by Turmfalke2** [comment]
Yes I am on linux and I am using 3.0.0:
![2018-03-25_01 38 36](https://user-images.githubusercontent.com/5174562/37870406-4232db64-2fcd-11e8-8dae-6801fea8228e.png)

**Comment by justinrusso** [comment]
Please update to 3.0.1
