### ISSUE TITLE
Rock creates render glitches/holes in the ground

### ISSUE THREAD

**Issue by Turmfalke2** [Darkosto/SevTech-Ages#792]
Hi,
It seems like sometimes when worldgen generates a rock the surface below it becomes invisible. 

![2018-03-25_00 57 52](https://user-images.githubusercontent.com/5174562/37870200-f949d93e-2fc7-11e8-9295-aec2df83fd91.png)

**Comment by justinrusso** [comment]
Do you have optifine?

**Comment by Turmfalke2** [comment]
No, pure 3.0.0, from curse importzed into MultiMC.

**Comment by justinrusso** [comment]
This is fixed in 3.0.1. https://minecraft.curseforge.com/projects/sevtech-ages

**Comment by justinrusso** [comment]
Not sure what this may be, but we have not had any other reports and I have not been able to see it since.

Since this issue has been quiet for quite some time, I'll be closing this issue. Feel free to create a new issue if this arises again.
