### ISSUE TITLE
Invis mobs

### ISSUE THREAD

**Issue by gatsbyyy** [Darkosto/SevTech-Ages#799]
im not sure how this is happening but it is only happening during the night. invisible mobs (karate zombie and Paranas so far) spawn, you can hear them but cant attack or see them. a fix i have found so far is to exit to main menu and re-enter the world. after that you can see and attack them like normal.

**Comment by PrinceOfAmber** [comment]
Do their neat nametag health bars show up? 

What age are you in when it happened?

Is this in single player or multi? 

Can you get a screenshot or a gif?

**Comment by gatsbyyy** [comment]
Do their neat nametag health bars show up? no nothing is there but you can still hear them, and you still take damage when they attack. if you swing in the location where you got attacked and where the sound is comming from nothing happens even when the mob is right in front of your face.

What age are you in when it happened? age 0 or 1 (the very begging of the pack)

Is this in single player or multi? single player

Can you get a screenshot or a gif? next time is happens i can try and make a gif. im not sure when that will happen as it has happened 2 times in 5 hours randomly. but i will see what i can do

**Comment by darkhax** [comment]
@Darkosto Mob Stages doesn't make mobs invisible or prevent attacking, it only changes where they can spawn.

**Comment by vadis365** [comment]
Optifine sometimes causes invisible mobs - it happened in Invasion for the fish too.

**Comment by gatsbyyy** [comment]
@vadis365 maybe so, i was using optifine with shaders. (im still using optifine with shaders). i have not encountered any more invisable mobs since 3.0.1. i think we can close this issue now. thank you everyone!
