### ISSUE TITLE
[Bug] Horses multiplied overnight

### ISSUE THREAD

**Issue by Tawling** [Darkosto/SevTech-Ages#8]
There were a few horses on the surface when I went underground to a cave system over night. My FPS started to decrease down to <1. I resurfaced to find more than a few horses. A lot more.

[https://i.imgur.com/21M43tf.jpg](url)

**Comment by Darkosto** [comment]
Will look into this, it seems like In Control isn't using the term "weight" properly.

**Comment by Jandakast** [comment]
Replace the contents of the spawn.json file with the below to limit Horse and embers:ancient_golem spawns to 20 instead of endlessly spawning

``` json
[
  {
    "mob": "minecraft:zombie_pigman",
    "helditem": "minecraft:golden_sword",
    "result": "deny"
  },
  {
  "mob": "Horse",
  "mincount":"20,Horse",
  "result":"deny"
  },
  {
  "mob": "embers:ancient_golem",
  "mincount":"20,embers:ancient_golem",
  "result":"deny"
  }
]
```

**Comment by Darkosto** [comment]
This should be all fixed up, @Jandakast was awesome enough to help put a cap on them. We'll have to keep an eye on them and make sure it's under control for the next update.
