### ISSUE TITLE
Few crash reports

### ISSUE THREAD

**Issue by TheLemein** [Darkosto/SevTech-Ages#80]
### Issue / bug
 - Explain the issue / bug as easily understandably as possible.
 - If the issue/bug is recurring explain how it can be recreated (helps darkosto!).
 - Add a error/crash log to [Pastebin](https://pastebin.com/), and link it here, if possible(if you disslike pastebin any other similiar site is fine too)
 - Add a video/gif of the issue/bug if possible (makes it easier for darkosto to understand you).
[crash-2017-09-20_14.18.01-server.txt](https://github.com/Darkosto/SevTech-Ages/files/1318986/crash-2017-09-20_14.18.01-server.txt)
[crash-2017-09-20_14.32.24-server.txt](https://github.com/Darkosto/SevTech-Ages/files/1318987/crash-2017-09-20_14.32.24-server.txt)
[crash-2017-09-19_19.31.35-server.txt](https://github.com/Darkosto/SevTech-Ages/files/1318988/crash-2017-09-19_19.31.35-server.txt)

**Comment by TheLemein** [comment]
Most recent one I knew about, just crashed a few seconds after loading the map.. other two.. not so sure about.

**Comment by Darkosto** [comment]
Should be all good in newer versions :)
