### ISSUE TITLE
[3.0.1] Tier 4 Ore Prospector not showing up in JEI in Age 4

### ISSUE THREAD

**Issue by darkphan** [Darkosto/SevTech-Ages#800]
The Tier 4 Ore Prospector is not showing up in JEI in Age 4.

**Comment by darkphan** [comment]
Seems Age 4 did not trigger correctly, here is a [screenshot ](https://i.imgur.com/VcVxGP9.jpg) of what the in game chat looks like along with /gamestage info @p

**Comment by sharkykh** [comment]
> Seems Age 4 did not trigger correctly, here is a [screenshot ](https://i.imgur.com/VcVxGP9.jpg)of what the in game chat looks like along with `/gamestage info @p`

@Darkosto @justinrusso 
Apparently, you can only have one `setRewardFunction`, as can be seen in this example I found in the Triumph mod documentation.
Also worth noting, it seems only one item (`setRewardItem`) can be awarded (without using a trigger).
```
//Adds a recipe to reward upon completion. Multiple of these can be added.
addRewardRecipe("minecraft:ender_eye")
//Sets the function to fire upon completion. Only one of these can be set.
setRewardFunction("triumph:happy_birthday")
//Sets the experience to reward upon completion. This can only be set once.
setRewardExperience(42)
//Adds a Skillable mod skill level up to be rewarded upon completion. Multiple of these can be added.
addRewardSkillable("mining", 1)
//Adds an item to be rewarded upon completion. Only one of these can be set currently.
//setRewardItem("minecraft:stick")
//setRewardItem("minecraft:stick", 0)
//setRewardItem("minecraft:stick", 0, 1)
setRewardItem("minecraft:stick", 0, 1, {ench:[{lvl:1s,id:51s}],display:{Name:"The Stick of Truth"}})
```

**Comment by Darkosto** [comment]
Multiple functions can now be run within advancements. The mod updated to allow this and should fix this bug.
