### ISSUE TITLE
[3.0.0] Wrong recipe shown for the Totem Whittling Knife in the Totempedia

### ISSUE THREAD

**Issue by Briaker** [Darkosto/SevTech-Ages#801]
Open the Totempedia from the mod Totemic and goto: 
`Totems and Effects > Totem Poles > Page 3`

 The recipe shown is still the original:
[https://i.imgur.com/NVL9bdV.png](url)

I have not check other recipes in the Tokempedia, there may be more.

**Comment by justinrusso** [comment]
We cannot do anything about this. We recommend players use JEI as the "overriding" source of recipe information.
