### ISSUE TITLE
Zinc samples in stage zero

### ISSUE THREAD

**Issue by Syltann** [Darkosto/SevTech-Ages#802]
Zinc samples showing up in stage zero.

![2018-03-24_22 27 15](https://user-images.githubusercontent.com/30686588/37872023-ad2a6fb0-2fb2-11e8-9542-d9bd4e2d1552.png)

**Comment by Syltann** [comment]
Doesn't look like the clusters are stages either.

**Comment by Speedy8g** [comment]
I saw these as well, remember exactly where it was at. Can post a photo if needed.
