### ISSUE TITLE
Industrial Foregoing Plant Interactor issue with Stone half slabs

### ISSUE THREAD

**Issue by tybo96789** [Darkosto/SevTech-Ages#806]
Version: 3.0.1

Issue arise from when the plant interactor has power and stone slabs are adjacent the interactor

Crash Log is attached 

[crash-2018-03-25_00.01.43-server.txt](https://github.com/Darkosto/SevTech-Ages/files/1845177/crash-2018-03-25_00.01.43-server.txt)

EDIT:
Attached pastebin copy for convenience
[log](https://pastebin.com/LeMatF5j)

**Comment by Darkosto** [comment]
@buuz135

**Comment by Buuz135** [comment]
Might be fixed https://github.com/blay09/KleeSlabs/commit/1672bff6103191d5ab8fcd13b7ef9daabd934a0b

**Comment by tybo96789** [comment]
![2018-04-02_15 15 25](https://user-images.githubusercontent.com/6249271/38223839-c59ad328-3688-11e8-9edc-063e47f2cd15.png)

Confirm that this issue with stone half slabs is no longer an issue in pack version 3.0.4
