### ISSUE TITLE
Can only repair a flint axe if it is fully broken

### ISSUE THREAD

**Issue by Lewdicolo** [Darkosto/SevTech-Ages#807]
The flint axe cannot be repaired if it has any durability on the meter. Once the axe fully breaks, you can repair it once, but cannot repair it again to get it to full durability

SevTech Ages v3.0.1
Forge v14.23.3.3634
PrimalCore v0.6.42

**Comment by Turmfalke2** [comment]
How do you even repair your tools? I just always throw them away when they break.

**Comment by 630R63** [comment]
You can repair it almost completely if you use 3 pieces of flaked flint instead of just one.

**Comment by Darkosto** [comment]
Fixed, should be good for 3.0.5.

**Comment by Darkosto** [comment]
Actually, nevermind. It causes a serious dupe bug. I'll have to add a tag that it cannot be repaired and leave it off the list.
