### ISSUE TITLE
Possible confusion with advancement "Pump Up the Jam"

### ISSUE THREAD

**Issue by Crackerhead22** [Darkosto/SevTech-Ages#81]
For stage one, the advancement "Pump Up the Jam"; it might be a good idea to replace the word 'pump' in the description with 'Embers Fluid Extractor' to avoid confusion with the IE Fluid Pump that shows up when searching for pump.

Sorry for the run-on sentence there.

**Comment by Darkosto** [comment]
All fixed up!
