### ISSUE TITLE
/tf forcesync + Advancements not updating

### ISSUE THREAD

**Issue by OfficialyAwsome** [Darkosto/SevTech-Ages#811]
I'm in a small party of 3 and I re-joined the server and my advancements are not updating (im in a /tf party) /tf forcesync command is weird as in once i do it in chat it displays "Usage /tf forcesync" And that's all, either the command is broken or is there some sort of thing I need to add onto the command?

**Comment by justinrusso** [comment]
Are you joined via LAN or a server?

**Comment by OfficialyAwsome** [comment]
Server

**Comment by OfficialyAwsome** [comment]
Update: I relaunched the pack and did /tf forcesync and it worked! However, it still did post this in chat after it worked.
![image](https://user-images.githubusercontent.com/15023792/37877970-20506c9a-305a-11e8-812c-e57c980461ea.png)

**Comment by artdude543** [comment]
This is fixed in 3.0.3 along with other syncing fixes.
