### ISSUE TITLE
Apple of Lofty Stature not registering

### ISSUE THREAD

**Issue by Turmfalke2** [Darkosto/SevTech-Ages#812]
hi
I have crafted 2 Apples of Lofty Stature and even ate one of them without gaining the advancement. Also tried dropping one and picking it up again.

**Comment by Phelnax** [comment]
Having the same issue.

**Comment by CorAxes** [comment]
did this get fixed?

**Comment by mtimyself** [comment]
Can be manually completed via:
/advancement grant @p only triumph:stage1/stepup
