### ISSUE TITLE
Not able to pick up spear

### ISSUE THREAD

**Issue by DurkMC** [Darkosto/SevTech-Ages#816]
Throw spear at fish while underwater
 ### Issue / bug
 I threw the spear while underwater at the fish and am now unable to pick it up.

**Comment by artdude543** [comment]
Did you try to break the block which it dug into? On many occasions this allowed me to get the spear back.

**Comment by Turkey2349** [comment]
This a bug with vanilla minecraft mechanics. The spears behave much like vanilla arrows which is why occasionally they bug and can't be picked up.

**Comment by Turkey2349** [comment]
If you still feel this is a bug feel free to post it [here](https://github.com/Turkey2349/Progression-Tweaks/issues) instead.
