### ISSUE TITLE
Apple advancement

### ISSUE THREAD

**Issue by MyApolloGees** [Darkosto/SevTech-Ages#819]
### Issue / bug
Step assist apple not advancing in the Advancements. I have created 3 apple ate 2 and i have tried dropping and picking them back up and it didn't register. Any idea?
Not Sure if it can be recreated. 
Is there any way i can unlock that advancement and pass by?

**Comment by justinrusso** [comment]
https://github.com/Darkosto/SevTech-Ages/issues/812 Fixed in dev
