### ISSUE TITLE
Astral Sorcery Journal not unlocking a section

### ISSUE THREAD

**Issue by Crackerhead22** [Darkosto/SevTech-Ages#82]
Astral Sorcery Journal does not unlock a section called 'Exploration' when you make the Luminous Crafting Table.  There is a command for it `/astralsorcery research @p BASIC_CRAFT`  I suggest adding that to the stage2trigger.txt file.  It should work, I added it into the file and when I opened the journal the 'Exploration' section was there.

Also, this is needed to be able to craft the Starlight Crafting Table, the second astralsorcery crafting table.

P.S. - Did you mean for the Starlight Crafting Table to take 1 minute and 20 seconds to craft?

**Comment by Darkosto** [comment]
Added in and fixed up! Thanks :)
