### ISSUE TITLE
World Creation Not working.

### ISSUE THREAD

**Issue by SlimeVampire** [Darkosto/SevTech-Ages#820]
Every time i create a new world 0% pops up and nothing happens after this. When i push esc it goes back to main screen.  It creates a world folder but not world data in it, just an AE2 File and nothing else.

**Comment by PerhapsMan22** [comment]
have you had any luck with this yet? I'm having the same problem

**Comment by PerhapsMan22** [comment]
Alright, thanks man. I'll try it out and see if it works

**Comment by PerhapsMan22** [comment]
yup, that fixed it.
