### ISSUE TITLE
Zombie Villagers can spawn in with iron weapons in stage 0

### ISSUE THREAD

**Issue by LightningAvenger** [Darkosto/SevTech-Ages#822]
It's extremely rare, but zombie villagers can spawn with iron weapons even in tutorial stage. Noticed in my sp world when a villager got eaten, but managed to spawn one in just now with an iron sword, too
![image](https://user-images.githubusercontent.com/24767249/37878304-e56231ec-3034-11e8-8143-c1eef3601e34.png)

Pack version 3.0.1

**Comment by justinrusso** [comment]
Apparently may be something that can only be replicated when a zombie is transformed. Might not be something armoreable can manage

**Comment by justinrusso** [comment]
Going to abandon this for now as it has been quite quiet. I have not been able to force this to happen while playing nor as anyone else reported this. If it comes up again, please submit a new issue.
