### ISSUE TITLE
Clay Kiln causes large amounts of updates and causes TPS issues when item left inside.

### ISSUE THREAD

**Issue by Electrofried** [Darkosto/SevTech-Ages#823]
## Instruction on how to do issues like your boy darkosto
Make clay kiln, Apply fire, insert item. 
![b6dbf6236e94bf970476535068daac3f](https://user-images.githubusercontent.com/27886155/37878511-c5e45010-30ad-11e8-9e2f-15ca7e5fdf73.png)
![2d3d89e3e17d1f7492063831baa92453](https://user-images.githubusercontent.com/27886155/37878516-d22d6aa0-30ad-11e8-87ff-33bbed28ee25.png)

Sevtech version: 3.0.1

Minecraft version: Latest non snapshot

Issue reported to mod dev:
https://github.com/vadis365/PrimalTech/issues/10

Hopefully there is a fix for this soon. Not so bad for solo play, but you get a dozen or more players on a server leaving items in the clay kiln and it causes more and more issues.

**Comment by vadis365** [comment]
I'll take a look at list and get it a bit more optimised - it's probably unnecessary block updates in the mod.

**Comment by vadis365** [comment]
Hello,
I've changed a few things with the Kiln and have reduced the amount of block updates along with a few tweaks to the inventory handling. Hopefully this will bring the overhead down to a sane amount.
Let me know if this has helped with the TPS issues you are having.
Cheers,
Me.

**Comment by artdude543** [comment]
This should have been fixed in 3.0.2 if this is still an issue please open a new issue, thanks!
