### ISSUE TITLE
Can't place blocks against staged items in villages

### ISSUE THREAD

**Issue by MrHrulgin** [Darkosto/SevTech-Ages#824]
In release:

In Stage 0, you can't place blocks against things (like the stairs on the roofs of village houses) that look like something else. You also can't light unlit fiber torches on regular torches that are staged to look like lit fiber torches in villages. 

I assume this is an issue with the staging, and might be unfixable, but it leads to really odd behavior around villages where there's lots of stage-hidden items.

Additional weirdness: The hitbox for fences that look like planks is still the fence hitbox. Same with stairs; you sink partly into the "planks" on the roofs of the houses.

**Comment by artdude543** [comment]
This may have been fixed in newer versions of the modpack. But as you said due to how we hide the blocks it's something we/modder can't really fix w/o causing potential other bugs with the pack and tanking the performance.
