### ISSUE TITLE
Cannot get items from grave.

### ISSUE THREAD

**Issue by TheDonz56** [Darkosto/SevTech-Ages#825]
Issue:
I died once by a wild dog.  Respawned to same place and died again by the same dog (but must have been able to kill it because it was gone the next time).
Clicked on a grave and got 2 items out of it.  Went and put them in my chest.  Came back and clicked on 2nd grave and it said items will go into original slot and that it could not move items in inventory.  I move the skull to several different slots and still could not get items.

Sevtech 3.0.1
I use Soartec Modded texture pack.  Optifne is installed but shaders are off because my machine can't handle shaders with this pack (get about 2 FPS).

**Comment by alexandercuna** [comment]
Same happened to me so i decided to SNEAK on top of the grave.
That gave me all the items.

**Comment by TheDonz56** [comment]
Thanks!  That worked.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
