### ISSUE TITLE
Controls showing text where mouse is.

### ISSUE THREAD

**Issue by Mrbysco** [Darkosto/SevTech-Ages#826]
Wherever my mouse is located in the Controls it displays the sections name. Not sure if this is a bug or not. I find it annoying. (I got optifine installed)

Feel free to close if it's not actually an issue.

![afbeelding](https://user-images.githubusercontent.com/9308260/37879044-40f998d2-3072-11e8-84fd-a080021f0976.png)

**Comment by artdude543** [comment]
I don't think this is a bug tbh more of a fun quirk you have :P
