### ISSUE TITLE
Cannot turn off step assist

### ISSUE THREAD

**Issue by mtjohnson47** [Darkosto/SevTech-Ages#827]
### Issue / bug
 - The button to turn off step assist is greyed out.  The "Toggle Disable Step Assist" thing doesn't appear to do anything.
 - Minecraft 1.12.2, forge 14.23.2.2634, Java 8u161 or 162, SevTech: Ages 3.0.1
 - Press Esc > Controls

**Comment by justinrusso** [comment]
Thats the point. You cant yet. Its progression based

**Comment by mtjohnson47** [comment]
That is so dumb.

**Comment by DemonfangArun** [comment]
I have to agree, this is kind of dumb. I could see progression to enable it, but not to disable it. I was going to consider this pack for a server (after time is given for bugs to be worked out), but if this is going to be how the pack operates, then I have zero interest in it.

**Comment by MokahTGS** [comment]
Please change this.  It's very annoying.
