### ISSUE TITLE
Crashing when i hit tab to complete names

### ISSUE THREAD

**Issue by gladlygodot** [Darkosto/SevTech-Ages#830]
when I type /tf invite and then push tab to cycle through names I crash

**Comment by Turkey2349** [comment]
Can you post a crash log?

**Comment by gladlygodot** [comment]
[crash-2018-03-25_15.40.28-server.txt](https://github.com/Darkosto/SevTech-Ages/files/1845722/crash-2018-03-25_15.40.28-server.txt)
there you go

**Comment by Turkey2349** [comment]
mind putting it on pastebin so we don't have to download it?

**Comment by gladlygodot** [comment]
sorry https://pastebin.com/sihtVP9d

**Comment by Turkey2349** [comment]
No worries, we will look into it when we can!

**Comment by gladlygodot** [comment]
also meant to mention i'm hosting via lan not sure if that matters.

**Comment by Turkey2349** [comment]
If you want, you can try the same thing not in LAN and see if it crashes. If not than LAN is most likely your issue. Also, modded tends not to work in LAN anyways so more likely than not, that is your issue.

**Comment by gladlygodot** [comment]
it did it in a single player world as well.

**Comment by Turkey2349** [comment]
Will look into. Keep us updated

**Comment by GunpowderAbe** [comment]
Hey, was having the same troubles on a multiplayer server. Couldn't find the cause and saw this one as a post, and it turns out this is our problem too. In the case of MP, I was tabbing and the host's game crashed, if that helps with anything.

**Comment by justinrusso** [comment]
It appears like this has been fixed. I cannot replicate this as of 3.0.6 and this issue has been inactive for a while now.
