### ISSUE TITLE
Grammar with overview

### ISSUE THREAD

**Issue by BlocksinGeorgia** [Darkosto/SevTech-Ages#833]
When you look at this pack on Twitch launch and click view profile then overview, a sentence says "No map or HWYLA" What is Hwyla? Is it supposed to be Wawla?

**Comment by Turkey2349** [comment]
[HWYLA](https://minecraft.curseforge.com/projects/hwyla) is a mod that is a fork of WAILA, similar to Wawla. This is not a bug.
