### ISSUE TITLE
Shift clicking recipes doesn't trigger advancement

### ISSUE THREAD

**Issue by Muddr** [Darkosto/SevTech-Ages#835]
I know it doesn't trigger with `Furnace` and `Weak Dowsing Rod` in stage 1, probably happens with other recipes.

**Comment by britbriggs** [comment]
I am experiencing this with a couple of recipes as well, I noticed it yesterday but it eventually worked and couldn't figure out why... You are a saint!

**Comment by justinrusso** [comment]
Have you confirmed this works if you DONT shift click?

**Comment by Muddr** [comment]
yes.  I had to craft them again without shift clicking for it to trigger.

**Comment by Darkosto** [comment]
Most advancements using "crafted" now use "inventory changed". This should fix the problem you're having. 

(also FastWorkbench is the cause of why shift-clicking does not work).

Let me know if it happens again after the 3.0.2 update.
