### ISSUE TITLE
Cascading Worldgen

### ISSUE THREAD

**Issue by darkhax** [Darkosto/SevTech-Ages#84]
The following mods have cascading world gen issues. This causes lag with worldgen. There are probably more, but these are the ones I encountered and noticed in the log. 

- Geolosys
- Roots 2
- FuturePack
- PrimalCore

**Comment by justinrusso** [comment]
Streams was another one that caused issues and got removed. With the 1.12 releases the dev has claimed to have done some performance improvements - not sure if its been re-checked if its still something being considered

**Comment by justinrusso** [comment]
Wild Crops appeared to be another one for me causing cascading worldgen lag
