### ISSUE TITLE
Dust Bin is not named

### ISSUE THREAD

**Issue by d7u8d9e** [Darkosto/SevTech-Ages#841]
The dust bin is named "tile.dust_bin.name" on mouseover.
![image](https://user-images.githubusercontent.com/23158681/37880440-f9b71590-304d-11e8-84c7-56d62645c331.png)

**Comment by Turkey2349** [comment]
Try posting it [here](https://github.com/An-Sar/PrimalCore/issues)

**Comment by artdude543** [comment]
Linked Issue: https://github.com/An-Sar/PrimalCore/issues/159

**Comment by artdude543** [comment]
This has been fixed in a newer version of Primal Core but they have been disabled by the modder till they have functionality. We will look into possibly disabling ourselves also until they have a use.
