### ISSUE TITLE
Baykok bow

### ISSUE THREAD

**Issue by chiefklondog** [Darkosto/SevTech-Ages#846]
Unlocked Stage 1. Did a bunch of random achievements (not important I dont think)
Went back to Totemic and did the Stage 0 achievement for the Baykok bow. The bow and arrows say they are restricted by stage and are un-usable.

3.0.1
MC 1.12.2
forge 14.23.2.2634
 
![image](https://user-images.githubusercontent.com/30984107/37880617-555e5146-3040-11e8-9455-8e4e343063eb.png)
![image](https://user-images.githubusercontent.com/30984107/37880608-3e5f3190-3040-11e8-86b6-cdb48e9df043.png)
![image](https://user-images.githubusercontent.com/30984107/37880610-4600aee2-3040-11e8-8d6a-45ee5edc9f00.png)

**Comment by justinrusso** [comment]
Same issue as https://github.com/Darkosto/SevTech-Ages/issues/800
