### ISSUE TITLE
Server advancements not working correctly

### ISSUE THREAD

**Issue by omnirowdy** [Darkosto/SevTech-Ages#848]
When first starting up my SevTech server the Whats New! window doesn't even pop up. Then when pressing L to open the advancement window it says "There doesn't seem to be anything here... :(".

Once I kill a mob of any sort I get a advancement page window but it is not the correct one, it is the adventure one. When I open inventory I see 71 pages of items but they all say restricted item, so somethings are working. I don't see any different world generations either rather then just vanilla generation. I am not running a resource pack and when I run a single player version it all works fine. Not sure if this is some bug or if I am just stupid and can't get the server to work properly.

**Comment by Turkey2349** [comment]
Relog/Restart and make sure that doesn't solve the issue.

**Comment by omnirowdy** [comment]
Still nothing, have restarted the server multiple times, and re logged multiple times.

**Comment by justinrusso** [comment]
Are you LAN or Server?

**Comment by SWATr** [comment]
I had this issue when connecting to my server using 127.0.0.1; using my local ipv4 address fixed it.

**Comment by omnirowdy** [comment]
Found out my server host has not been using the correct files I gave them and this was causing the issue. Sorry for the trouble, but thanks for the responses.

**Comment by Fboyrie** [comment]
Same problem on my LAN server can you explain what did you do to fix your problem plz
Thanks
