### ISSUE TITLE
Caravans ZS issue

### ISSUE THREAD

**Issue by darkhax** [Darkosto/SevTech-Ages#85]
### Issue / bug
Noticed this when closing and rejoining a world. 

```
ERROR: caravans.zs:100: Could not resolve <betterwithaddons : bowl>
```

**Comment by Crackerhead22** [comment]
If I recall, Caravans mod should actually be turned off darkhax .

**Comment by darkhax** [comment]
No clue, I just imported the twitch alpha2 instance. I got a few messages about caravans approaching as well.

**Comment by Darkosto** [comment]
Yep! this is a result of a bad import into MultiMC.
