### ISSUE TITLE
Abyssalcraft dirt block with immersivecraft rock

### ISSUE THREAD

**Issue by garlicinyoureye** [Darkosto/SevTech-Ages#852]
For the Immersivecraft rocks that are in abyssalcraft biomes only the ones with dirt blocks under them, the player cannot run over the block without being stuck and having to avoid the block altogether.  Not sure which mod is to blame, it's not game breaking just annoying.  You're the best.

![image](https://user-images.githubusercontent.com/14200981/37881113-c2ac21c2-3060-11e8-95d2-3f61f9f07ec7.png)

**Comment by B3ice** [comment]
https://photos.app.goo.gl/dcDqZ5lkt3Igl3zX2 Heres a video of it.

**Comment by artdude543** [comment]
I've spent 30 mins flying over biomes to find the ones with dirt underneath and can't find them at all. But I tested placing the rocks on various blocks to see if I can reproduce the issue but I can't. So I could be randomly fixed or it's an issue with how it's generated by the world.

**Comment by garlicinyoureye** [comment]
I think this issue can be closed. Once the server admin updated all of the folders (configs) included for the 3.0.1 update it fixed the getting stuck glitch.

**Comment by artdude543** [comment]
Okay cool if you find the issue again just poke us here :)
