### ISSUE TITLE
Age 1 advancements not being detected after a game reload.

### ISSUE THREAD

**Issue by MrZed411** [Darkosto/SevTech-Ages#853]
I got to age 1 and was very hyped. I crafted a workbench very quickly as I was excited to get to have one and got the advancement for crafting it. I then had to work on other things so I exited Minecraft normally (the save and exit button) and it shut down normally. When I loaded back into the game I started to make some more things in the advancement (chests, furnace, weak dowsing rod) and none of them were detected. I reloaded the game after the dowsing rod and chest wasn't noticed and tried to make them for the first time after a reload and it did not work. 

I am on version 3.0.0.

Anything I can give you to better help?

**Comment by MrZed411** [comment]
Update, I made a clay barrel and it was detected. I have tried throwing the three above items to pick them up and that has not been detected yet either.

**Comment by Dystilled** [comment]
Same for me. Those 3 aren't detected but have been made.

**Comment by Dystilled** [comment]
Seems to be linked to Shift Clicking to craft. 

Recraft but only click rather than shift click

**Comment by MrZed411** [comment]
That was the issue. Once you craft the items without Shift-Clicking it is detected. Thanks!
