### ISSUE TITLE
[3.0.1] Bug - Cant stepup on surfacerock

### ISSUE THREAD

**Issue by tjsd** [Darkosto/SevTech-Ages#855]
https://imgur.com/a/5GiNW

The rocks that spawn on dirt blocks I cant step up on, but the ones that spawn on darklands texture block is no issue. I have also seen this in "normal" biomes but I couldnt locate a spot right now since they look similar to coarse dirt.

**Comment by artdude543** [comment]
The rocks from ImmCraft you don't step up as you kinda walk through them. Unless I'm missing something here? But I have not seen this issue or seen Streamers face this issue.
