### ISSUE TITLE
Crafting/Eating an Apply of Lofty Stature does not grant Advancement

### ISSUE THREAD

**Issue by RyanBerge** [Darkosto/SevTech-Ages#857]
We're on a privately hosted multiplayer server with 3 players on a team.  Crafting the Apply of Lofty Stature with the Blood Altar works, but neither crafting the apple nor eating it gives any of us the "I Don't Want it Anymore!" Advancement.

**Comment by Speedy8g** [comment]
Same issue!

**Comment by CorAxes** [comment]
Same Issue here too

**Comment by Turkey2349** [comment]
See #812
