### ISSUE TITLE
Together Forever not working, Can't share advancements on Lan

### ISSUE THREAD

**Issue by Pyrothunder** [Darkosto/SevTech-Ages#859]
We made a Lan server for us to play on, but using the commands /tf invite or /tf info does nothing. It doesn't come up with an error and it doesn't do anything. We just want to be able to share our progression with each other through the pack, instead of playing separately on the same server.

**Comment by justinrusso** [comment]
There is currently a bug with that mod on LAN servers. LAN servers, to the mod, are technically single player

**Comment by justinrusso** [comment]
https://github.com/Darkosto/SevTech-Ages/issues/787

**Comment by artdude543** [comment]
This should be fixed in 3.0.3 after some testing things was syncing fine.
