### ISSUE TITLE
Unable to craft Wet-Tanned Hide

### ISSUE THREAD

**Issue by imthatjeremyguy** [Darkosto/SevTech-Ages#860]
Got to the point to make Wet-Tanned Hide towards Leather.

Created Dry Hide, Full Bladder, Ground Resin. Put in crafting menu. Nothing generates. 

Use JEI search for Wet Tanned Hide, See recipe, click add items, auto populates items into crafting menu and still generates nothing.
 
Video Link: [https://youtu.be/LslO0Pg4WnU](https://youtu.be/LslO0Pg4WnU)

Minecraft Version 1.12.2
Sevtech Ages Version 3.0.1
Forge Version 14.23.2.2634

**Comment by ChylerBH** [comment]
This should be closed.  I had the same issue but if you watch the video closely the bladder is only part filled (250mb, not 1000mb).  This can happen when a barrel you are using has not got enough water in it, the bladder just looks inflated  Emptying and refilling should work.

**Comment by justinrusso** [comment]
Ah I've watched a player do that before as well. Thanks @ChylerBH

**Comment by imthatjeremyguy** [comment]
Thanks. Didn't even notice the bladder has a fill level system.
