### ISSUE TITLE
Crashing while loading up modpack from twitch launcher -> Minecraft launcher

### ISSUE THREAD

**Issue by SuchReach** [Darkosto/SevTech-Ages#861]
When I want to play the pack from the twitch laucher. (shows the minecraft laucher afterwards. I added 8GB of ram) IT crashes after I click "Play" and says "Sorry for the inconvience"
 - **Most recent version of  Sevtech Ages**
 - If the issue/bug is recurring explain how it can be recreated (helps darkosto!). I dp
 - If possible add error/crash log to [Pastebin](https://pastebin.com/) and link it here (if you dislike pastebin any other similar site is fine too). ERRORS FROM LAUCHER : 

11:46:25 | game | 2018-03-25 18:46:25,747 main WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream   <log4j:Event logger="LaunchWrapper" timestamp="1522028785840" level="INFO" thread="main">     <log4j:Message><![CDATA[Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker]]></log4j:Message>   </log4j:Event>
-- | -- | --
11:46:25 | monitor | expected <
11:46:26 | game | 2018-03-25 18:46:26,139 main WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream 2018-03-25 18:46:26,145 main WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream   <log4j:Event logger="FML" timestamp="1522028786178" level="WARN" thread="main">     <log4j:Message><![CDATA[The coremod AppleCore (squeek.applecore.AppleCore) is not signed!]]></log4j:Message>   </log4j:Event>
11:46:26 | monitor | expected <
18:46:26 | FML | The coremod api.player.forge.PlayerAPIPlugin is requesting minecraft version 1.12.1 and minecraft is 1.12.2. It will be ignored.

 - If possible add a video/gif of the issue/bug (makes it easier for darkosto to understand you).
I cant make a vid or a gif

**Comment by artdude543** [comment]
On the SevTech "Window" On the launcher can you click the `...` button next to `Get More Content` and hit `Repair Minecraft` and try again. After that delete/install the profile again and start that.

**Comment by SuchReach** [comment]
Still doesn't work :(

**Comment by SuchReach** [comment]
I did it and it still crashes

**Comment by artdude543** [comment]
Can you pastebin the entire log for me please?

**Comment by SuchReach** [comment]
https://pastebin.com/7NWay8Qa

**Comment by SuchReach** [comment]
Yo can you please respond

**Comment by artdude543** [comment]
Yo! I'm currently dealing with other issues and life. Please be patient.

**Comment by SuchReach** [comment]
Thought you left

**Comment by SuchReach** [comment]
Can you please help

**Comment by SuchReach** [comment]
NO ONE HELPS

**Comment by artdude543** [comment]
Okay, clearly you don't understand the concept of people having a life. Or being pulled away to work on other things/items. All you have to do is **wait** like all the others who post issues/bugs and you'll get a reply. If this is not fast enough for you; try the Minecraft Forums or Twitch Forums for support.

We all work on this as a hobby and no one is paid. Do you want priority support? Pay one of us and we'll be all yours. (Some of us are pricy)

Due to your immaturity in dealing with this and your rudeness, I'm closing this and locking the issue. Have a good day sir!
