### ISSUE TITLE
Weird Bug

### ISSUE THREAD

**Issue by thejok3er** [Darkosto/SevTech-Ages#862]
Modpack: SevTech 
Version: 3.0.1.
Bug: When u pick up an animal (I was holding a chicken) and then press 'E' while on a horse u will wear random items from your inventory and they will also go into your crafting space. I was able to recreate this bug multiple times. Items don't disappear or get dupped. Just a strange issue.

**Comment by artdude543** [comment]
I don't think this is a bug, to be honest more of a quirk/effect of the pick up mod.

If this somehow causes a bug later down the line or other issue we'll look more into it :)
