### ISSUE TITLE
Grind stone makes duplicates black dye

### ISSUE THREAD

**Issue by Bromthrax** [Darkosto/SevTech-Ages#864]
Grinding an inc sac on a grindstone will give you 2 black dye powder (pickle tweaks). You can craft these black dyes back into inc sacs and repeat f o r e v e r. Not a game breaking bug but it still probably shouldn't be a thing.

**Comment by Bromthrax** [comment]
turns out this is known sorry, i should have read other ones first

**Comment by justinrusso** [comment]
Its okay, appreciate the report!

**Comment by justinrusso** [comment]
Its okay, appreciate the report!
