### ISSUE TITLE
Advancements Showing only Vanilla MC Advancements

### ISSUE THREAD

**Issue by Rhyoliter** [Darkosto/SevTech-Ages#865]
My friend and I just started the SevTech pack and the advancements aren't showing up correctly. We saw a post about TogetherForever for LAN however he and I aren't on LAN together. https://gyazo.com/61dc05479826eb16e35b7cd61b846ee2 The link is a picture of my current advancements tab. This link is a copy of the server settings https://gyazo.com/152461fa28822b2d6890ceec873f68be

**Comment by artdude543** [comment]
Make sure that you have uploaded all the mods/configs/scripts to the server. As your missing the mod which overrides Vanilla Advancements.

**Comment by Rhyoliter** [comment]
We copied over all the scripts/mods/configs from the single player over to the server and it changed nothing. Is there anything in particular you need from us that would help you better understand our issue?
