### ISSUE TITLE
Wooden Basin from Primal_tech showing up in JEI for Age 0, no recipe for it.

### ISSUE THREAD

**Issue by JackRuby1** [Darkosto/SevTech-Ages#866]
The Wooden Basin from Primal_tech is showing up in JEI for Age 0 with no recipe.

**Comment by artdude543** [comment]
This has a recipe in the newer versions of the pack 😄 

![](https://i.artdude.uk/dN5ZfA4c.png)

**Comment by justinrusso** [comment]
@artdude543 the item is staged in zero though. So this is actually a bug
