### ISSUE TITLE
Shelf deletes any items in it if you break it

### ISSUE THREAD

**Issue by Razorfin8** [Darkosto/SevTech-Ages#867]
### Issue / bug
 - Stored Items inside a shelf (I dont know about cupboards, chests, etc) will be deleted from the world when the shelf is broken.
 -Forge: 2634, Minecraft 1.12.2  Java 1.8.162 64bit, Most up to date pack at time of posting
 - Put stuff in shelf, break shelf, ???, unprofit

**Comment by artdude543** [comment]
I can't reproduce this issue; I'm assuming you are talking about the shelf from ImCraft? If so this is not an issue and I tried with other shelves to no avail.
