### ISSUE TITLE
Sevtech 3.0.1 Server Issue with Advancments

### ISSUE THREAD

**Issue by alicheek** [Darkosto/SevTech-Ages#868]
Hey guys so i have a bit of an issue no idea if this has already been covered or not but i have downloaded the server files with the atlauncher and i am in the process of setting up a server for this.

I have everything working but from what i can see there seems to be an issue with progression with the server, single player works fine.

The Issue:
So at the start you need to start collecting fiber and sticks to make some first items bit it will say 

You dropped the Pland Fiber! Futher progression is required.

Any Idea to what would be causing this or if i need a permission node or something for our permissions plugin with sponge?

**Comment by mtjohnson47** [comment]
I couldn't find server files, so just turned the client files into a server.  Works fine.

**Comment by artdude543** [comment]
Sponge is known to cause issues with Advancements could you try using a Vanilla Forge setup and report back if the issue persists. Otherwise, you may have to file an issue with the Sponge Team about the issue and supply logs/details to them as then it would be out of our scope of control.

**Comment by thaimichael** [comment]
I downloaded the Server Pack and on initial join to the server my advancement page said something like "nothing here" and was dropping sticks and fiber saying more progression needed.  This is a non-sponge server.  Upon second connection same non-opped client advancements were there.  Tried deleting the world folder and restarted the server to see if I could recreate the issue but advancements showed correctly with the first connection.

**Comment by justinrusso** [comment]
LAN server?

**Comment by thaimichael** [comment]
No it is a dedicated server I have.

**Comment by thaimichael** [comment]
Just happened again for me logged out and back in corrected seems like achievements are not always syncing when joining server https://imgur.com/LUQAj8k

**Comment by 630R63** [comment]
Have you tried giving yourself the tutorial age?
/gamestage add @p tutorial

**Comment by alicheek** [comment]
Will test this when I get back the issue is this is not feesable when quite a few players will join

**Comment by mtjohnson47** [comment]
I'm not the OP, but my server is only forge and works fine.

**Comment by alicheek** [comment]
So tested using the /gamestage command after doing this i could pick up the string and such, but my issue is there doesn't seem to be detection for progression so if i do part of a quest it seems to stay at 1/2 when for instance its just making the hatchet

**Comment by alicheek** [comment]
Ok tried with just forge and still have the issue with advancements not progressing

**Comment by justinrusso** [comment]
@alicheek are you shift+clicking a recipe? try not doing that.

**Comment by alicheek** [comment]
@justinrusso havent been using the shift click option what mod is it that controls the leveling system and is there a section where the configs are stored as i cant seem to find this

**Comment by alicheek** [comment]
@artdude543 what mod is controlling the progression, also i have updated to the new version of the modpack and it is still not working.

**Comment by ArbitraryHubris** [comment]
@alicheek Triumph is the mod setting conditions for advancements

**Comment by Jandakast** [comment]
There is an occasional issue where the Tutorial stage is not properly given to the player at first login. Usually this can be resolved by restarting the server or by exiting the SP world and opening it back up. Honestly not sure if this is an issue with gamestages or if it is just a client/server desync issue as there is no error generated in the log when the issue occurs. In my testing it only effects the first person that logs in. All other players function correctly.  

Also if the world was created with Sponge installed you need to recreate the world without sponge to ensure the level.dat file is created/updated with your first login events correctly. 

I'm closing this issue. If you have the same issue on the newest version of the pack on a world that has never had Sponge, then please create a new issue.
