### ISSUE TITLE
Unreapairable tools not despawning when broken

### ISSUE THREAD

**Issue by colbyjr** [Darkosto/SevTech-Ages#870]
some tools ie. 

Flint tools that do/do not repair no despawn when broken 

seems to be a hit or a miss witch flint tools can be repaired via flaked flint also no jei recipe that would or would not say that tools can be repaired via flaked flin jei only shows anvil recipes.

**Comment by Turkey2349** [comment]
The tool tips should say whether or not they cannot be repaired due to a bug. To get rid of them, you can combine them with new versions of the tool, just like vanilla mc tools.

**Comment by justinrusso** [comment]
Cant really do anything about this. Its just a broken tool that cant be repaired, you can just throw it out of your inventory and let it go away

**Comment by colbyjr** [comment]
Thank you for kind reply it is no big deal at this point. Found a way around it make a new tool wait for a bit of durability to go down and add in 2x2 crafting grid repairs new tool a bit :).
