### ISSUE TITLE
Bonemeal duplicating

### ISSUE THREAD

**Issue by hjucvyo** [Darkosto/SevTech-Ages#872]
Currently, the grindstone has a recipe to turn 1 bonemeal into 2 white dye powder, and you can convert the dye powder to bonemeal at a 1 to 1 ratio just by putting it into a crafting grid.
It obviously isn't the most game breaking resource, but it is an infinite resource nonetheless.

**Comment by justinrusso** [comment]
https://github.com/Darkosto/SevTech-Ages/issues/856
