### ISSUE TITLE
Can't join server because of different Integrated Dynamics versions

### ISSUE THREAD

**Issue by omnirowdy** [Darkosto/SevTech-Ages#874]
This is the error I get when I try to join my server. I am using the twitch launcher. I am not sure what the correct version should be is this the fault of my client or the server?

Server Mod rejections: Integrated Dynamics:Requires version 0.11.9 but client has 0.11.7

Here is a gyazo- https://gyazo.com/b156533d5195d62965edf0e8ebc0b01c

**Comment by iDarper** [comment]
easy fix, is to copy over the mods folder from the client, to the server, replacing the entire existing mods folder with the mods folder from the client.
