### ISSUE TITLE
Completed achievements not registering as complete.

### ISSUE THREAD

**Issue by iDarper** [Darkosto/SevTech-Ages#875]
When making an item to complete an achievement, the resulting item isn't registering the achievement as done. 
![2018-03-25_22 51 34](https://user-images.githubusercontent.com/23562183/37887545-98c3209e-307f-11e8-8cc7-0d003c22ec52.png) Heres an example. I have the item not registering in my hotbar far right. (2 actually) I have 2 more of the subsequent advancements done as well, and nothing is registering. I've restarted the server, as well as my game, and relogged several times with no fix.

Hope this helps. =)

**Comment by justinrusso** [comment]
Should be fixed in dev. Dont shift+click the item when crafting.

**Comment by iDarper** [comment]
This is a bit different.  The broken achievements are not on a table you can shift click from.  The recipes require hitting the table with a stone to make them.
