### ISSUE TITLE
Two recipes for the unfired clay bowl from progression tweaks

### ISSUE THREAD

**Issue by Ryzelf** [Darkosto/SevTech-Ages#877]
Two recipes for the  **Unfired Clay Bowl**

**original recipe in JEI** 
      (Null, Null, Null,) 
  (clay ball, Null, clay ball)
(Clay ball, clay ball, clay ball)

**2nd recipe That is NOT necessary but doesn't  show in JEI**
   (clay ball, Null, clay ball,) 
   (clay_ball, Null, clay ball)
(Clay ball, clay ball, clay ball)

**Comment by artdude543** [comment]
This was fixed and only has a single recipe now.
