### ISSUE TITLE
Bronze ingot on the stone anvil yields copper plate

### ISSUE THREAD

**Issue by AmishInvader** [Darkosto/SevTech-Ages#879]
When using the stone anvil and stone mallet to crush a bronze ingot into a bronze plate, you get a copper plate instead.

Pack 3.0.1

**Comment by TheAdversary808** [comment]
i can agree this recipe does not work - Pack 3.0.1

**Comment by justinrusso** [comment]
Please see https://github.com/Darkosto/SevTech-Ages/issues/836#issuecomment-376121679
