### ISSUE TITLE
Water wheel from better with mods recipe doesn't work

### ISSUE THREAD

**Issue by AmishInvader** [Darkosto/SevTech-Ages#880]
8 wood blades around a copper gear doesn't produce anything.

Pack 3.0.1

**Comment by TheAdversary808** [comment]
i can agree this recipe does not work - Pack 3.0.1

**Comment by Darkosto** [comment]
![image](https://user-images.githubusercontent.com/10309699/37924735-b99eaa32-3100-11e8-9b40-3a7ae2c4196b.png)
I cannot reproduce this bug.

**Comment by sharkykh** [comment]
@Darkosto 
Perhaps this is related to the copper chest issue players had been experiencing only on servers?

**Comment by artdude543** [comment]
This was fixed a while back now. Closing and if you find this to still be an issue on the latest pack please re-open an issue.
