### ISSUE TITLE
Slat recipe could give more slats

### ISSUE THREAD

**Issue by DasRubberDuck** [Darkosto/SevTech-Ages#881]
The ammount of wood needed to craft one slat is pretty high (6 Slabs and 3 Sticks).

Might be an idea to change the recipe to give more slats, if you want  to encourage the player to actually use thatched roofs.

Cheers!

**Comment by artdude543** [comment]
I have this changed in dev to give 3 which helps with the cost balance. (More thinking about 2 but 3 meets in the middle for still costing a lot but you don't feel as ripped off)
