### ISSUE TITLE
Tomahawk doesnt give achievement

### ISSUE THREAD

**Issue by crocman** [Darkosto/SevTech-Ages#882]
I have tried in 2 new worlds now, when I craft the tomahawk in the inventory it doesnt give me the achievement. This is very frustrating. 

### Issue / bug
 - Explain the issue / bug as understandably as possible.
 - If possible add minecraft, forge, java and modpack version numbers for debugging (mod authors might need these).
 - If the issue/bug is recurring explain how it can be recreated (helps darkosto!).
 - If possible add error/crash log to [Pastebin](https://pastebin.com/) and link it here (if you dislike pastebin any other similar site is fine too).
 - If possible add a video/gif of the issue/bug (makes it easier for darkosto to understand you).

**Comment by Ryzelf** [comment]
Maybe you have not made the sharp bone yet you need to complete the first advancement in the tree for it to unlock the next advancement.

**Comment by Darkosto** [comment]
It does complete, but you need to finish the parent advancement first. That's how every advancement in the pack works. Just because you can see it doesn't mean you completed the one directly before it.
