### ISSUE TITLE
Items show in JEI that should be hidden

### ISSUE THREAD

**Issue by justinrusso** [Darkosto/SevTech-Ages#886]
When a resource reload occurs (Changing Resource Packs, potentially shaders, etc) items that should be hidden in JEI are now showing.

Reference: https://github.com/mezz/JustEnoughItems/issues/1145

Workaround: Restart the pack

(Just creating an issue here for people to reference, and for us to track)

**Comment by mezz** [comment]
This has been fixed in JEI 4.8.6.161
