### ISSUE TITLE
Mud and step-up

### ISSUE THREAD

**Issue by Superslammer** [Darkosto/SevTech-Ages#887]
When walking on mud in to grass i'm not able to step up
I don't know if it is ment to be like that
[Example.zip](https://github.com/Darkosto/SevTech-Ages/files/1848401/Example.zip)

**Comment by iDarper** [comment]
Best guess here,  is that the block size is different between the 2. A good example of this,  is grass and grass paths.  Not a pack issue.  This is a general Minecraft mechanic.

**Comment by artdude543** [comment]
This is intended due to the block size and how it works (as a block) and a general thing with Vanilla Mechanics.
