### ISSUE TITLE
No hostile mobs except wolves spawning (Disregard, Optifine issue?)

### ISSUE THREAD

**Issue by Ewest80** [Darkosto/SevTech-Ages#888]
Version 3.0.1.  The first night after loading the game hostile mobs spawned but since switching it to hard (the first night), from normal but not sure this is releated, via the options menu not a single hostile mob has spawned.  About 8 minecraft days in I made a Tipi and slept in it and upon waking there were a couple creepers and spiders in the area that despawned within a couple seconds of appearing and nothing else since then which has been a couple more minecraft nights.  The only hostile mob I have ran into is wolves.

-- EDIT --
I forgot I installed Optifine after I started the world so removed it and first night there are hostile mob spawns.  Didn't even know that was a possible side-effect but it appears to be.

**Comment by Darkosto** [comment]
Good to know, thanks for the update. Going to close this issue :)
