### ISSUE TITLE
Astral Sorcery Resonating Wand not craftable

### ISSUE THREAD

**Issue by Crackerhead22** [Darkosto/SevTech-Ages#89]
As the title says, it is not craftable in a normal crafting table. 

I had to add `mods.recipestages.Recipes.addShaped("two", <astralsorcery:itemwand>, [[null, <astralsorcery:itemcraftingcomponent>, <minecraft:ender_pearl>], [null, <ore:stoneMarble>, <astralsorcery:itemcraftingcomponent>], [<ore:stoneMarble>, null, null]]);` into the stage2recipe.zs file to be able to craft it in a normal crafting table.

**Comment by Crackerhead22** [comment]
I just realized that without going to the Twilight Forest and getting an Ender Pearl, that crafting this is impossible...

**Comment by Darkosto** [comment]
Got it fixed up! :D
