### ISSUE TITLE
Items restricted for coop player but not restricted?

### ISSUE THREAD

**Issue by Ebullio** [Darkosto/SevTech-Ages#891]
Got the Sevtech working on LAN with the new together forever update from 4 hours ago, worked like a charm, except one seemingly major thing, my wife who is not the host, joins my team so she gets progression which shows up perfectly fine on the tech tree (L) and she can use supposedly non-restricted items but if she hovers over them they are still restricted, and in the inventory screen, none of the new acquired items show up, so she cannot see any recipies.

and lastly i had her create a fiber mesh for the progression, which she could easily do but we did not gain any progression until she dropped the item and i picked it up.

p.s. Sorry if i didnt follow the right format for the post, first time posting here.

**Comment by artdude543** [comment]
This should be fixed in later version. If this still an issue please re-make an issue :) Also make sure you have a team setup correctly with the right player naming etc.. 😄
