### ISSUE TITLE
Auto-Jump issue

### ISSUE THREAD

**Issue by Rasip** [Darkosto/SevTech-Ages#892]
### Issue / bug
 - Explain the issue / bug as understandably as possible.
 - If possible add minecraft, forge, java and modpack version numbers for debugging (mod authors might need these).
 - If the issue/bug is recurring explain how it can be recreated (helps darkosto!).
 - If possible add error/crash log to [Pastebin](https://pastebin.com/) and link it here (if you dislike pastebin any other similar site is fine too).
 - If possible add a video/gif of the issue/bug (makes it easier for darkosto to understand you).

Auto-Jump is turned off (and disabled) in the controls but still active.

**Comment by garlicinyoureye** [comment]
It's not autojump, it's step assist and it's on for a reason.  Auto jump in you MC controls menu is not on.

**Comment by artdude543** [comment]
Step Assist is enabled by default for X reasons and you can edit it later on when you unlock the stages. As this is intended I'm going to close the issue.

**Comment by PaffcioStudio** [comment]
Find a clienttweaks.cfg in the "config" directory and open it.
Change the line 129 (true to false) and 135 (false to true):

    # This option forces auto jump to be disabled and also disables the button for it. Because it should never have been a thing. [default: false]
    B:"Disable Auto Jump"=false

    # This option will disable step assist added by other mods. [default: false]
    B:"Disable Step Assist"=true

or in game...

Click ESCAPE and select MODS OPTIONS button, find a Client Tweaks and click a CONFIG button.
Set "disable auto jump" to false and "disable step assist" to true.


A few seconds of searching :) Sorry for my weak English :C I still do not understand him.
How could you author make life so difficult? You just had to leave it turned on and unlocked!
