### ISSUE TITLE
Recipe conflict with copper gear

### ISSUE THREAD

**Issue by garlicinyoureye** [Darkosto/SevTech-Ages#897]
MC 1.12.2 Forge 14.23.2.2634
pack version 3.0.0
![image](https://user-images.githubusercontent.com/14200981/37928633-72ed890e-310b-11e8-9c2e-ef938f4d2bfe.png)

**Comment by Darkosto** [comment]
That's why there is an update to the pack that specifically fixes this issue. It was released 2 days ago.

**Comment by justinrusso** [comment]
https://github.com/Darkosto/SevTech-Ages/issues/836

**Comment by garlicinyoureye** [comment]
this update is in 3.0.1? Many apologies.
