### ISSUE TITLE
Appeal for Magic Bypass

### ISSUE THREAD

**Issue by Giblejimmy** [Darkosto/SevTech-Ages#898]
The mod SevTech is advertised as a tech oriented mod yet having to learn Abyssal, Blood Magic, Totemic, etc bypasses a lot of the logical progression in favor of wasted time to justify materials that are out of place almost completely.

Requesting a means of bypassing magic and to only go through tech or to fix the Twitch page to mention the modpacks use of magic mods.

**Comment by Darkosto** [comment]
Sorry, but request denied. This pack was made for Sevadus who specifically requested magic mods.

The twitch tags are not infinite, you only have so many tags per pack. There is also a mod list you can see before downloading the pack. At the very least, it does not cost money to download a pack and you can see the modlist once you have it installed.
