### ISSUE TITLE
[Minor] Overlapping Cauldron Recipes - Chicken Soup is made instead of Hearty Stew

### ISSUE THREAD

**Issue by Vyraal1** [Darkosto/SevTech-Ages#899]
### Issue / bug
 - Trying to make Hearty Stew with Cooked Chicken, ends up making Chicken Soup instead, no way to prioritize the recipe due to the overlap it seems.
![image](https://user-images.githubusercontent.com/26587049/37930723-90b01f64-3111-11e8-96f9-19d9f1373aa1.png)

**Comment by artdude543** [comment]
This was fixed in a newer version of the pack 😄
