### ISSUE TITLE
Punching Darklands Oak Wood drops log

### ISSUE THREAD

**Issue by DingoX3** [Darkosto/SevTech-Ages#9]
![2017-08-31_03 47 19](https://user-images.githubusercontent.com/16032841/29912458-bcf1079c-8dff-11e7-8fee-befa413ec999.png)

**Comment by Darkosto** [comment]
Hmmm, seems like the mod isn't catching it properly or abyssalcraft isn't registering them correctly.

**Comment by Darkosto** [comment]
I can't seem to reproduce this.

**Comment by DingoX3** [comment]
Ok ill have a look as soon as i can and give it another try. Is it just disappearing for you?

**Comment by DingoX3** [comment]
Still doing it for me. Did you change some configs between the version i have? I havent messed with any of them myself, fyi.
https://imgur.com/zVHTlcB

**Comment by Darkosto** [comment]
Added the log to the oredict and it now works as intended! Thanks!
