### ISSUE TITLE
Can not obtain Astral Sorcery Rock Cystals from the ore

### ISSUE THREAD

**Issue by Crackerhead22** [Darkosto/SevTech-Ages#90]
Astral Sorcery's 'Rock Crystal Ore' needs either obsidian, diamond, or cobalt level mining in order to obtain the crystals for the ore.

**Comment by Crackerhead22** [comment]
Would Content Tweaker be able to make an Aquamarine pickaxe that could mine the ore proper?

**Comment by Crackerhead22** [comment]
Would it be possible to use ContentTweaker to make an aquamarine pickax that could mine the ore properly? 
From what I can tell, the mining level has to be at least 4. I think...

**Comment by Darkosto** [comment]
Yeah, I can change this. Thanks for the heads up!

**Comment by Darkosto** [comment]
All fixed! :D
