### ISSUE TITLE
Advancement: I Don't Want it Anymore - Item: Apple of Lofty Stature - Not completing

### ISSUE THREAD

**Issue by mtimyself** [Darkosto/SevTech-Ages#900]
v3.0.1 Multiplayer on server.

Bug: Upon crafting the Apple of Lofty Stature in the Blood Altar the Advancement does not complete. Tried by all 3 TF team members.
 
For anyone bothered by this (it is a non-progression breaking issue) use:
/advancement grant @p only triumph:stage1/stepup

**Comment by justinrusso** [comment]
https://github.com/Darkosto/SevTech-Ages/issues/812
