### ISSUE TITLE
Geolosys mining delay on servers.

### ISSUE THREAD

**Issue by primetoxinz** [Darkosto/SevTech-Ages#901]
[Clip of it](https://streamable.com/kpyw0)
My server has been experiencing mining delay with specifically Geolosys ores. As you can see in the clip no other blocks do it. 

I tried to [reproduce it](https://github.com/oitsjustjose/Geolosys/issues/82) with just Geolosys on SSP and Server and did not have it happen. My best guess right now is related to something in SevTech, possibly OreStages?

**Comment by oitsjustjose** [comment]
[Cross reference](https://github.com/oitsjustjose/Geolosys/issues/82)

**Comment by Muddr** [comment]
On a 4gb SevTech server with flint pickaxe. 
[Clip](https://streamable.com/gwed9)

**Comment by oitsjustjose** [comment]
Unable to reproduce on my own SevTech 3.0.1 Server (4gb min, 6gb max ram) on a Mac Mini dedicated server:

[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/-rDTVtpMSuc/0.jpg)](https://www.youtube.com/watch?v=-rDTVtpMSuc)

**Comment by Marioluigi7896** [comment]
Still in 3.0.3
[Clip](https://streamable.com/zw7x0)

**Comment by artdude543** [comment]
Old issue and we've had a lot of updates to the involved mods. And more coming in 3.0.7 if this is still an issue then please re-file with new data for us to look at.
