### ISSUE TITLE
Its getting hot in here won't complete

### ISSUE THREAD

**Issue by Drummerboyno** [Darkosto/SevTech-Ages#903]
### Issue / bug
Mincraft furnace will not activate the achievement
![dark](https://user-images.githubusercontent.com/37815749/37931938-c1550abc-310c-11e8-81df-0845e91ba070.PNG)
 "Its getting hot in here" I have crafted 3 now, cooked a lot of stuff in it, what is required to complete this? 
![ttt](https://user-images.githubusercontent.com/37815749/37932055-1eee3ba8-310d-11e8-8297-841a45fd7cb8.PNG)

**Comment by justinrusso** [comment]
Did you craft with shift+click?

**Comment by Drummerboyno** [comment]
The issue was it couldnt be shit+clicked thanks  Jusinrusso
