### ISSUE TITLE
Recipe for disabled AE2 wooden gear is shown

### ISSUE THREAD

**Issue by Xynain** [Darkosto/SevTech-Ages#904]
In stage 0, the recipe for what I believe to be the AE2 wooden gear is showing up even though the item is disabled. This recipe was found when searching recipes the stick is used in. 

sevtech build: 3.0.1
 
Code name: appliedenergistics2:material

![screenshot 14](https://user-images.githubusercontent.com/37455014/37933446-3c9dd79c-3119-11e8-887d-fca16bb4ec5a.png)

**Comment by artdude543** [comment]
I have this fixed in dev :) Will be removed on the next update.
