### ISSUE TITLE
Suggestion for an advancement for the Resonating Wand

### ISSUE THREAD

**Issue by Crackerhead22** [Darkosto/SevTech-Ages#91]
```
setIcon("astralsorcery:itemwand")

setTitle("")

setDescription(" ")

setParent("triumph:stage2/root")
setRequiresParent(true)

criteria = addCriteria("crafted", "triumph:player_crafted_item")

criteria.setItem("astralsorcery:itemwand")

setRewardItem()
```

I wasn't sure what to name the advancement or the reward. Since you need the Astral Sorcery crystals, I figured it would be good to have it before the Constellation Paper since you need the crystals.  Also since you need it for crafting with the Astral Sorcery crafting tables.

**Comment by Darkosto** [comment]
Got this added into Stage 2.
