### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by jerithsnake** [Darkosto/SevTech-Ages#912]
all my advancement reset to to tutorial but i have all mi inventory, and mi jei have only 1 page with liquid
![2018-03-26_14 48 48](https://user-images.githubusercontent.com/37782803/37935149-5d33258e-3105-11e8-943b-eda7acb970f0.png)
![2018-03-26_14 53 20](https://user-images.githubusercontent.com/37782803/37935189-78bc67c0-3105-11e8-928c-93283c8fde35.png)

**Comment by justinrusso** [comment]
What were you doing?

**Comment by jerithsnake** [comment]
i crafted the portal to find aquamarine and black quarz and i log out and when in this hapen

**Comment by jerithsnake** [comment]
after this hapen i try but idk the command

**Comment by justinrusso** [comment]
Are you on a server? Are you part of a team?

**Comment by jerithsnake** [comment]
single player

**Comment by jerithsnake** [comment]
what is the command to get the stages???

**Comment by justinrusso** [comment]
`/gamestage add @p StageName`
Advancements are `/advancement grant @p ` use tab to see the rest.

Theres really no information on the issue here, so we cant do much more. Going to have to close this
