### ISSUE TITLE
Tough Dowsing Rod does not pick up Gold Ore in Age 2

### ISSUE THREAD

**Issue by djnifos** [Darkosto/SevTech-Ages#914]
### Issue / bug
 - Be in Age 2.  Use Tough Dowsing Rod to find gold
 - 3.0.1 Default Forge, 161 java
![2018-03-26_17 26 01](https://user-images.githubusercontent.com/2243466/37936335-c7e58d26-311a-11e8-99db-ef868824aedd.png)

**Comment by Darkosto** [comment]
Fixed in dev. Thanks!
