### ISSUE TITLE
Weird tool tip for log. 

### ISSUE THREAD

**Issue by TrisanaShadows** [Darkosto/SevTech-Ages#916]
FYI: New to git hub. So excuse weirdness

**Comment by TrisanaShadows** [comment]
![2018-03-27_11 48 56](https://user-images.githubusercontent.com/17152787/37937290-89ba40b4-31b5-11e8-9209-e1f67ffc89ed.png)

**Comment by artdude543** [comment]
Whats the issue/tooltip you're having? Need more information than just a screenshot.

**Comment by justinrusso** [comment]
@artdude543 its displaying the wrong wood in WAILA.

@Darkosto what ever happened with this? Is it even reported to the dev?

**Comment by artdude543** [comment]
I don't even know what Vanilla textures look like so that stumped me xD

**Comment by sharkykh** [comment]
### [Is this the issue in question?](https://github.com/TehNut/HWYLA/issues/88)

**Comment by artdude543** [comment]
OH YEAH, that issue!

**Comment by justinrusso** [comment]
If I recall, this was fixed. If there is still an issue, please create a new issue.
