### ISSUE TITLE
Can't find black quartz ore. 

### ISSUE THREAD

**Issue by cheesealmighty** [Darkosto/SevTech-Ages#917]
It is obvious that I'm missing something, but I just wanted to ask anyway. 

I'm in stage 1 and I've been looking for black quartz all over the land, prospecting over ground as well as underground. After scouring the land (which was more painstaking than TFC, since there you know which rock types to look out for) for thousands and thousand blocks. I upped the prospecting range to 128 blocks, looked around for a bit more, still nothing. I'm able to find coal/tin/copper. 

I ended up changing the recipe for axle. _Why does the axle need a black quartz anyway._ :P

Am I missing something?
Best regards.

**Comment by sharkykh** [comment]
@cheesealmighty Have you checked the advancement for Black Quartz?
> Travel to the **bottom** of the **Beneath dimension** to find Black Quartz

**Comment by cheesealmighty** [comment]
I did not. I've been putting off the magic stuff... 

I thought the ores unlocked with every stage? Are they tied to the achievements individually too? I didn't check the scripts in detail, but I got the impression that it was so. Welp, my bad then.

**Comment by sharkykh** [comment]
@cheesealmighty Ores are unlocked at every age. 
> Are they tied to the achievements individually too? 

If you mean are there ores unlocked by completing an advancement, as far as I'm aware - no.

No need to check the scripts, just the description in the advancements screen, this is basically your "quest log" to help you know what you need to do at every age in order to advance to the next one.

Good luck.

**Comment by cheesealmighty** [comment]
Well, the thing is, unless you progress on the magic advancements, you can't see the 

> Travel to the bottom of the Beneath dimension to find Black Quartz

advancement, that's why I was confused. I think you can only see 2 quests in front of you.

 And the Geolosys mod book was giving the impression that it did spawn on overworld, but just deep down. (I know you can't manipulate the book.) 

May I suggest moving that quest a bit backwards, or exposing it a bit earlier. _Because to me, visiting a shadow dimension is a bit unintuitive, when you were just only banging stones together an hour or so ago_

**Comment by sharkykh** [comment]
Well, sorry for assuming :)
You are correct about seeing only two advancements ahead.
I believe that is intentional. Keeps you wondering about the future, right? ;)

**Comment by Darkosto** [comment]
This looks like the info wasn't read on the advancement. We should be good! Thanks!
