### ISSUE TITLE
Horse Disappearing Act

### ISSUE THREAD

**Issue by JDKinser** [Darkosto/SevTech-Ages#919]
After Dismounting my horse it pulls a Houdini and disappears.
-This has happened on multiple occasions.
-The first time was in a stay-put hole.
-The second time was in the open with nothing around.

I am able to log out and back in and it returns.

Not a huge game changer but figured you may know whats happening.

Great pack!

**Comment by ScaCoyote** [comment]
Also had this happen. I jumped off my horse to sleep the night away on a mat and when I woke up my horse was gone. Found horse back where it had originally spawned into the world. It was annoying but not game breaking. I found my horse when I went back to get a new horse. He still had his saddle and everything. Just odd

**Comment by jrunestone** [comment]
+1 here :) Not a terribly huge deal but it requires me to log out and in again. I can still hear the horse once it disappears.

**Comment by artdude543** [comment]
This is a random thing sadly; we a lot of updates and changes in 3.0.7 which could help. But 9/10 I've watched people find their horse from re-log or searching a wider area. They are free animals so will roam about ^_^
