### ISSUE TITLE
[3.0.1] Right clicking crafting table with stick on the side places stick on top

### ISSUE THREAD

**Issue by Marioluigi7896** [Darkosto/SevTech-Ages#920]
### Issue / bug
Have a stick in your hand, right click the side of a vanilla crafting table, see that you have less one stick in your inventory and one on the table. Break the stick and place it again by mistake. Proceed to scream.

**Comment by Turmfalke2** [comment]
Ah so this explains why there constantly sticks on my crafting table.

**Comment by artdude543** [comment]
Sadly this feature is intended. It can be annoying at times but it's intended and funny to watch streamers lose their mind ^_^
