### ISSUE TITLE
What Editor is being used to edit the scripts?

### ISSUE THREAD

**Issue by vadis365** [Darkosto/SevTech-Ages#923]
kaythnxbye.

**Comment by artdude543** [comment]
Ha ha you troll!

(From Twitch Chat)
To edit his files, Darkosto uses Sublime Text 3 - https://www.sublimetext.com/ , ZenScript- https://github.com/way2muchnoise/ZenScript-Highlighter , & https://packagecontrol.io/packages/Pretty%20JSON for JSON formatting and validating.

Kappa
