### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by BigAl607** [Darkosto/SevTech-Ages#925]
Just a mod I think would be interesting with this pack. It's called Chop Down Updated. It allows the player to chop down the bottom block of a tree and the tree "falls" over. Just thought it would fit in with the early game.

[Chop Down Updated](https://minecraft.curseforge.com/projects/chop-down-updated)

**Comment by Phantum** [comment]
I second this!

**Comment by sharkykh** [comment]
If this is added, take into consideration the fact that players can only get the first wood by using a hatchet. Though, players **can** punch the wood tree, and this mod will probably enable the option to punch a tree and get the logs - minus the tree stomp, or bottom block.

**Comment by Darkosto** [comment]
This mod and others like it were in SevTech a while ago. They were INSANELY laggy when cutting a tree down. It was so bad that getting the entire tree wasn't even worth it.

**Comment by vadis365** [comment]
Sorry 'Al it looks like this is not something that will be implemented - closing for house keeping reasons.
