### ISSUE TITLE
Item name in waila is wrong

### ISSUE THREAD

**Issue by link13254** [Darkosto/SevTech-Ages#926]
In waila the drying rack is named the item rack when in the inventory its called drying rack
 
 Modpack version: 3.0.1
![2018-03-26_16 57 51](https://user-images.githubusercontent.com/37818861/37939373-47509820-3117-11e8-93fc-76ab991c9dba.png)

![2018-03-26_17 01 26](https://user-images.githubusercontent.com/37818861/37939393-58acb5b8-3117-11e8-9994-441324c37304.png)

**Comment by Darkosto** [comment]
This is an issue with HWYLA and how it handles meta data.

**Comment by link13254** [comment]
Okay, i just wanted to let you know about it.

**Comment by artdude543** [comment]
This is fixed in 3.0.3 :)

**Comment by link13254** [comment]
thank you for letting me know
