### ISSUE TITLE
Chopping Block issue

### ISSUE THREAD

**Issue by extrenix** [Darkosto/SevTech-Ages#928]
I'm having issues using the chopping block 
When I place a wood block on it, it takes several tries with the axe to make a plank out of it. the axe is always trying to destroy the chopping block instead. Not sure what causes this. I've watched a streamer transform dozens of wood into plank in a matter of seconds.

**Comment by hresad** [comment]
You need to keep repeatedly clicking the left mouse button while holding an axe and not just hold the button down.

**Comment by Darkosto** [comment]
You need to click multiple times, not hold the mouse button down.
