### ISSUE TITLE
Star Metal Ore issue

### ISSUE THREAD

**Issue by Crackerhead22** [Darkosto/SevTech-Ages#93]
Star Metal Ore does not generate naturally in the world.  It requires Iron Ore blocks to be transmuted via a Crystal Lens from Astral Sorcery.  Which requires a bit of a starlight network thing (I'm still working on figuring out Astral Sorcery).  That basically blocks entering Twilight Forest.

**Comment by Darkosto** [comment]
Correct, that's the aim I was going for. To require the player to work through Astral Sorcery to obtain the Star Metal ore. Are there items you aren't able to acquire to complete that progression?

**Comment by Crackerhead22** [comment]
![2017-09-24_01 31 19](https://user-images.githubusercontent.com/452429/30779791-df893586-a0bf-11e7-876e-94587e955277.png)


Okay, so how you normally start getting Starmetal Ore is by placing it next to a floating crystal in an Astral Sorcery structure.  Then eventually you can make a Collector Crystal.  The Collector Crystal is made using Stardust, which is made in the Celestial Altar (3rd tier crafting table), which needs Stardust to be made.  

The Lens can be made in the Starlight Crafting Altar (2nd tier table), the Glass lens it needs can be made in the Luminous Crafting Table.  The Linking Tool needed is craftable in the Starlight Crafting Table.

So unfortunately without an Astral Sorcery structure with a floating crystal, the Starmetal Ore is impossible to get unless a Collector Crystal, or Celestial Collector Crystal is given as a reward.

**Comment by Darkosto** [comment]
This should be all fixed up by now, I think :P
