### ISSUE TITLE
Baykok staging not working

### ISSUE THREAD

**Issue by FlavallA** [Darkosto/SevTech-Ages#931]
I killed Baykok after progressing to age 1 and the bow and arrows he dropped and still restricted. I've tried restarting and killing him again.

![2018-03-26_17 37 40](https://user-images.githubusercontent.com/12058021/37940250-88dbcd82-311c-11e8-9ea3-170fe0a5f034.png)
![2018-03-26_17 37 44](https://user-images.githubusercontent.com/12058021/37940254-8c5ce734-311c-11e8-891b-d4abba4fc94d.png)
![2018-03-26_17 37 51](https://user-images.githubusercontent.com/12058021/37940255-8e7f470a-311c-11e8-8a92-31cb1a4884b8.png)

**Comment by Saereth** [comment]
can confirm I had the same issue, 3.0.1

**Comment by CrypticDivide** [comment]
Duplicate issue. #846

**Comment by Darkosto** [comment]
Duplicate issue and will be fixed when 3.0.2 goes out.

**Comment by Skullywag** [comment]
This is not working for me, updated from 3.0.1 but after id already killed him and got the bow and passed the achievement, is there a command or something?
