### ISSUE TITLE
Progression achievement not given even with parent achievement before it

### ISSUE THREAD

**Issue by camran131** [Darkosto/SevTech-Ages#932]
So this has happened twice to me now. First upon crafting my first Plumb Line and then I’ve also crafted 4 Apples of Lofty Stature through the Blood Magic Alter. I was able to get the Plumb Line achievement after crafting a second Plumb Line but I cannot get the Apple of Lofty Stature achievement for progression. It still says I need to create the Apple through the Blood Alter.
Im on Minecraft 1.12.2 (forge-14.23.2.2634/fml,forge)

The only extras I use are Optifine, SUES reworked, and a resource pack.

### Issue / bug
 - Explain the issue / bug as understandably as possible.
 - If possible add minecraft, forge, java and modpack version numbers for debugging (mod authors might need these).
 - If the issue/bug is recurring explain how it can be recreated (helps darkosto!).
 - If possible add error/crash log to [Pastebin](https://pastebin.com/) and link it here (if you dislike pastebin any other similar site is fine too).
 - If possible add a video/gif of the issue/bug (makes it easier for darkosto to understand you).

**Comment by Darkosto** [comment]
The Apple adv. issue is a duplicate post. This has been fixed in the current dev version. The plumbline issue should also be fixed when 3.0.2 releases.
