### ISSUE TITLE
Illumination Powder Recipe Not Being Recognized in the Altar

### ISSUE THREAD

**Issue by Vyraal1** [Darkosto/SevTech-Ages#935]
### Issue / bug
 - Illumination powder recipe as shown by JEI: 
![image](https://user-images.githubusercontent.com/26587049/37942224-1ef9f776-3140-11e8-91cb-bd87d67d66f9.png)
- Recipe isn't recognizable as shown:
![image](https://user-images.githubusercontent.com/26587049/37942272-51c92dfc-3140-11e8-9749-37e2af0cbd64.png)

- I checked the script files and noticed the following script in `astral_sorcery.zs` on Line 21:
```
//Attunement
Altar.addAttunmentAltarRecipe(<astralsorcery:itemusabledust> * 8, 80, 600, [
	<betterwithmods:sand_pile>, <astralsorcery:itemcraftingcomponent>, <betterwithmods:sand_pile>,
	null, <minecraft:gunpowder>, null,
	<betterwithmods:sand_pile>, scripts.crafting_utils.getBucketIngredient(<liquid:astralsorcery.liquidstarlight>), <betterwithmods:sand_pile>,
	<quark:glass_shards>, <quark:glass_shards>, <quark:glass_shards>, <quark:glass_shards>
]);
```
- Tried again with a bucket, still no output: 
![image](https://user-images.githubusercontent.com/26587049/37942291-640d7cc0-3140-11e8-92c6-9e6b58c4eb14.png)

- in-game I've ruled out insufficient starlight as the reason, since it only requires 80 starlight and the altar reservoir is full
- also confirmed that the multiblock is complete and functional
Maybe an issue with the function?

**Comment by mtimyself** [comment]
There is also a problem with crafting the Starmetal Ore.
I assume this is the same issue?

**Comment by RyanBerge** [comment]
I am having this same issue, in multiplayer.

**Comment by RyanBerge** [comment]
A quick followup: We noticed that one of the other players on the server was able to craft the dust.  We also noticed that in the GUI, he is able to see an indication of how much more starlight we need for the item, and the other two players cannot see that. All three of us can see that indicator on the Luminous Crafting Table.

**Comment by Firestar99** [comment]
Same issue, noone was able to see it

**Comment by yotabytes** [comment]
In my case, if a friend crafted the luminous crafting table and started the upgrade to starlight crafting altar, he was the only one who had the 'your vision expanded, you learned attunement' message.

I could not see the recipe but crafting the altars myself unlocked that attunement and resolved this issue.

**Comment by artdude543** [comment]
Okay, so this is not an issue with the pack but with users not following the tree of AS correctly. You need to progress through its own advancements/book before the recipe will work for you. We only changed the recipe not how the mod works. Still you still need to follow it :)

**Comment by konradmm** [comment]
@yotabytes can confirm, in most cases that's gonna be a problem. If you show ur friend "oh look, here is how to craft it", u won't be able to craft ie. Illumination Powder, then your friend will need to do so. Or just craft a starlight crafting altar for urself, then u will be able to perform these recipes

**Comment by ladal1** [comment]
Having this problem, but seeing no prerequisite in the astral tome and I have done everything in astral sorcery myself, even getting the atunement message...
