### ISSUE TITLE
Horse Power Advancement

### ISSUE THREAD

**Issue by nashlock** [Darkosto/SevTech-Ages#938]
Horse Power Advancement
 - After crafting and placing the horse grindstone in age 0, I do not unlock the advancement.
 - All other advancements have worked up to this point.
 - I even attached a horse to the stone and ground some items to see if I needed to use it for the 
   advancement to unlock.

**Comment by artdude543** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

Thanks again for reporting, and we hope you enjoy the pack!
