### ISSUE TITLE
Plum Line & Channel quests in Age 1 not completing

### ISSUE THREAD

**Issue by naraxam** [Darkosto/SevTech-Ages#940]
Dirk, the quest where you channel fluids and the quest where you use the plum line do not complete. Have replicated multiple times on new worlds.

**Comment by justinrusso** [comment]
Did you happen to shift+click the output to craft it?

**Comment by naraxam** [comment]
I don't believe so with the channel, but definitely not with the plumb line.

**Comment by naraxam** [comment]
Fixed with 3.0.2
