### ISSUE TITLE
Inventory Tweaks + Mouse Tweaks issue

### ISSUE THREAD

**Issue by Arcanatias** [Darkosto/SevTech-Ages#941]
This isn't really a big issue, more of a small technical convenience thing that I use and I'm sure some others do as well. Inventory Tweaks and Mouse Tweaks conflict each other somehow when using the mouse wheel to take items out of compatible inventories. It is really glitchy and takes things out and puts them back while scrolling the same direction.  Using the mouse wheel to quickly take out the right number of items from an inventory is something I use to speed up early game crafting somewhat because obviously it doesn't work with AE2 or other similar inventory management systems. I've seen this same issue in other packs so I'm not sure if there is a config you can change, I usually just end up removing mouse tweaks and it fixes the issue. There might be some unforeseen reason why you have both mods in the pack, I just thought I would bring it to your attention in case it was a bug or could be fixed without removing one of the mods.

**Comment by blumunch** [comment]
I've noticed when I go to mute my game using my keyboard, my inventory gets shuffled around and will have items "hidden" aka somewhere else. The more I hit my mute key it shuffles around finding items that were not in my inventory.  Does your do that or is it just me?

**Comment by DingoX3** [comment]
@blumunch sounds like cyclic is moving your inventory around. Try looking at your keybinds and chane the inventory moving short-cuts to another key or set them to one if they arent.
@Arcanatias Open your inventory and click on the ... looking symbol in the top right. You can turn shortcuts off there and it will work right.

**Comment by blumunch** [comment]
@DingoX3 that was it, thanks. I've never seen that before and even set to NONE it moved things around so I changed it.

**Comment by Arcanatias** [comment]
After turning the shortcuts off from inventory tweaks it didn't help but what I found works is going into the config for mouse tweaks and changing WheelScrollDirection=0 to WheelScrollDirection=1 and it is alot smoother. Not sure if that is something the devs want to change but that seems to be the solution for me.

**Comment by keidrolis** [comment]
Is there a fix for this issue that still allows mouse wheel down to push items and mouse wheel up to pull?

**Comment by Ncrpts** [comment]
Issue still present in 3.0.7

**Comment by Marcel40625** [comment]
this is a conflict with NEI!

**Comment by Ncrpts** [comment]
> this is a conflict with NEI!

Oh my god thank you, 

by disabling NEI i was finally able to use the mousewheel the correct way, so now if we want to have both NEI and Mousetweak in the same pack the only solution is that NEI implement a config option to either turn off the mouswheel functionality or reverse it (making mouse tweak removable in that case), i'll post on NEI repo about it. hope we can get progress on this.

**Comment by Ncrpts** [comment]
issue fixed in my fork of NEI https://github.com/Ncrpts/NotEnoughItems

**Comment by Marcel40625** [comment]
or you turn of the mousetweak one :)

`WheelTweak=0`

**Comment by Ncrpts** [comment]
When WheelTweak=0 from mousetweak, you still have the tweak from NEI active, and in the incorrect order (wheel up to insert/ down to extract) so you either have to re-learn how to use your mousewheel in the reverse order, or disable NEI entirely. my solution fix the issue and allow you to use both mods without conflict.
