### ISSUE TITLE
Bronze shield available uncraftable in Age 1

### ISSUE THREAD

**Issue by Lewdicolo** [Darkosto/SevTech-Ages#944]
The bronze shield appears in JEI in Age 1. The recipe states that you can pour 4 ingots worth of molten bronze on a crude wooden shield in either a casting basin or casting table. The basin is the only casting block available in age 1, but when I place a wooden shield in the basin and try to pour, the bronze won't pour.

*Copper also does not work. I assume Tin will not work as well

https://i.imgur.com/zHwykTh.png
https://i.imgur.com/9AWcgYh.png
https://i.imgur.com/HpBHIEl.png

SevTech Ages v3.0.1
Forge v14.23.3.3634

**Comment by Skullywag** [comment]
Confirming this is the case. Would be nice to be able to move to copper, tin and bronze shields once I have access to them, casting table is pretty far off from stage 1 what with all the blood/abyssal stuff you have to do.
