### ISSUE TITLE
5 sec delay when you open inventory

### ISSUE THREAD

**Issue by r0n1nn** [Darkosto/SevTech-Ages#945]
I keep getting a 3-4 sec delay when I open my inventory I don't know what is causing it but I got a java error for you
"internal exception: java.nio.channels.closedchannelexeption"

                                                                                                   hope this helps
                                                                                                                r0n1nn

**Comment by Lumyo** [comment]
I have this problem too.
It doesnt happen right after starting the game, and restarting completely minecraft is fixing it for a while.
But the problem always come back

**Comment by Lumyo** [comment]
I managed to find how to solve the issue :

Just update Java to the latest version (It worked also for someone else who had the issue)

**Comment by psymonious** [comment]
I tried disabling NEI like already mentioned in [#778](https://github.com/Darkosto/SevTech-Ages/issues/778) and that immediately stops the lagging issue.
Enabling it againg brings back the waiting, so it is reproducible.

**Comment by vadis365** [comment]
Duplicate of #778
