### ISSUE TITLE
Fire sticks start fire but fire goes away immediately 

### ISSUE THREAD

**Issue by Wozatron256** [Darkosto/SevTech-Ages#947]
I have tried doing this on both low grade charcoal and other various blocks same thing everytime
![fire stick bug](https://user-images.githubusercontent.com/7741923/37948064-f0e28984-3153-11e8-924d-0749b231ceb5.gif)

**Comment by 630R63** [comment]
It looks like an auto left click after using the sticks that extinguishes the fire, am I correct?

**Comment by Wozatron256** [comment]
maybe ill see

**Comment by Wozatron256** [comment]
ty

**Comment by SeaGoingJet** [comment]
How do I fix this?? No where I look provides a solution.
