### ISSUE TITLE
Take a look at how to make Parrots more easily accessible 

### ISSUE THREAD

**Issue by Darkosto** [Darkosto/SevTech-Ages#948]
Maybe allowing them in more biomes? Like Savannah?

**Comment by Dystilled** [comment]
Yes please. I've been wandering for 4 hours trying to find a jungle, the only one Ive found isn't spawning them. 

The spawn locations definitely need to be expanded. Savannah/Plains would make sense.

**Comment by Darkosto** [comment]
Add to Swamps and abyssal swamps.

**Comment by artdude543** [comment]
This has been added in v3.0.3 :)
