### ISSUE TITLE
[Wild Crops] Hydroponic crops

### ISSUE THREAD

**Issue by darkhax** [Darkosto/SevTech-Ages#95]
### Issue / bug
Sometimes crops will spawn/generate under water, and it's weird. 

![image](https://user-images.githubusercontent.com/2250798/30780165-e7268328-a0c1-11e7-9187-7be39834279a.png)

**Comment by Darkosto** [comment]
Yep, I need to speak with Kormic to insert a check for whether or not the wild crops are surrounded or covered by water.

**Comment by Darkosto** [comment]
This should be fixed. Needs testing

**Comment by darkhax** [comment]
Yay
