### ISSUE TITLE
Apple Of Lofty Stature

### ISSUE THREAD

**Issue by Robertprime** [Darkosto/SevTech-Ages#951]
I have made, eaten, thrown, put in a chest etc. for the Apple of lofty stature but I cant get the achievement to go off. 
My save file does not have cheats activated, so it says I cannot use the "/advancement grant @p only triumph:stage1/stepup" command to get it. Any help would be appreciated

**Comment by Dystilled** [comment]
As a work around if you click "Open to Lan" and enable cheats you should be able to use cheat commands.

**Comment by justinrusso** [comment]
https://github.com/Darkosto/SevTech-Ages/issues/812
