### ISSUE TITLE
Unfired Porcelain

### ISSUE THREAD

**Issue by Burzi86** [Darkosto/SevTech-Ages#952]
SevTech 3.0.2

In the new version I can't get the Unfired Porcelain from the Mill Stone any longer.
Evertime try I only the 2 white powder.

I know it still worked in 3.0.1

**Comment by artdude543** [comment]
Yep can confirm this is an issue looking into it now :)

**Comment by artdude543** [comment]
Okay see https://github.com/BetterWithMods/BetterWithMods/issues/816

**Comment by LoryMaster** [comment]
Also, by looking at all the recipes the mill can do, the Bonemeal -> White powder recipe appears twice, once on page 26 / 41, the other on page 37 / 41. Could a double addition cause problems?

**Comment by justinrusso** [comment]
Still is a priority issue on the mods end. Im not sure if this mod was updated as I dont handle that, but either way, it shouldnt be the cause.

Those duped crushing recipes I intend to remove, it just wasnt a major issue.

**Comment by artdude543** [comment]
They have updated the mod which a "temp" fix which should help; a build would need to be tested, however.

**Comment by artdude543** [comment]
This is fixed in v3.0.3 :)
