### ISSUE TITLE
Stone Anvil not working?

### ISSUE THREAD

**Issue by MiniKatalyst** [Darkosto/SevTech-Ages#954]
*Please note, I found out that my game wasnt updated to 3.0.2 when finding this bug.*

So I was working my way to copper ingots and got to the part where I had a block of copper. So I read:
-->Stone anvil = Place items on it. Bash with stone mallet. 
So I placed the copper block on the stone anvil (as according to the recipe) and bashed it with mallet for a good minute or so..... nothing happens... tried it with sneak, holding ctl, aiming differently, even hammered until the anvil broke. Tried replacing the anvil in different spots too, nothing was working.

And I'm confused because I'm doing what the recipe and tool tips are telling me to do.

I don't know whether it was just my game or because this has already been fixed in 3.0.2. But knew I should post the issue anyways so I could find out some info.

**Comment by Dystilled** [comment]
Stupid question but: 

Did you try right clicking?

**Comment by artdude543** [comment]
This is working as intended/fine when you right click with the Mallet. Ensure you have the correct tool and are indeed right-click the anvil.

**Comment by MiniKatalyst** [comment]
Yes I tried right clicking, sorry I didnt add that to the list of attempts. I also tried right clicking while shifting ect.

And yes I was using the stone mallet that I was given when I recieved the advancement.

**Comment by artdude543** [comment]
Okay so from the DM you sent me I tested with the copper block from IE and it converted fine to Ingot
Can you confirm to me what block/mod you were trying to use to get ingots for? This could be related to the ItemStages issue but I can't reproduce what you sent me in my client instance.

![](https://i.artdude.uk/lBC6Vnnp.png)

**Comment by MiniKatalyst** [comment]
It was the IE block, I tried it before updating and it still didnt work. But now it works in 3.0.3, so I don't know what was causing it.
Thank you for your help though.
![c09d286f060720311b29c340efd8336b](https://user-images.githubusercontent.com/37491065/38012013-74f8a908-32ab-11e8-81fd-ef4bb9054076.png)
