### ISSUE TITLE
Crashing client when pickup something that is not yet discovered 3.0.2

### ISSUE THREAD

**Issue by leozanelato** [Darkosto/SevTech-Ages#956]
I'm running the server and the client (3.0.2) on my pc for tests to later get a vps;

Now the issue, when im running with nothing on the hand and i broke a not discovered flower for example and it gets to my hand, the item drops on the floor and i have a internal crash that disconnect me from my own test server;

On 3.0.1 all fine; 

8GB allocated to game 4GB to server;

**Comment by artdude543** [comment]
Yes I have found the issue and reported it to the developer https://github.com/Darkhax-Minecraft/ItemStages/issues/14

**Comment by artdude543** [comment]
Please, can you update to 3.0.3 and confirm is the issue is still persisting thanks!

**Comment by leozanelato** [comment]
working fine now;

**Comment by artdude543** [comment]
Awesome thanks for checking! 😄
