### ISSUE TITLE
ItemStages seem to carry over from SP world to MP server

### ISSUE THREAD

**Issue by davqvist** [Darkosto/SevTech-Ages#957]
Updated the client and server to 3.0.2 and I have no issues but another player had no items in JEI unlocked. I checked his gamestages and he had them all correctly. We are also on the same TF team fyi. He then told me he was messing around in SP earlier before joining the server where he had no gamestage unlocked. He then restarted the client, joined the server immediately and then he had access to everything again.

Let me know if you need more info.

**Comment by artdude543** [comment]
This could be related to https://github.com/Darkhax-Minecraft/ItemStages/issues/14 and I've added a note to crash about ItemStages being broken.

**Comment by artdude543** [comment]
Please, can you update to 3.0.3 and confirm is the issue is still persisting thanks!

**Comment by davqvist** [comment]
Seems to be fixed
