### ISSUE TITLE
Journeymap Death Points on Server without having Journeymap unlocked

### ISSUE THREAD

**Issue by davqvist** [Darkosto/SevTech-Ages#958]
Updated the server to 3.0.2 and now every player sees his/her death beacons of every death before even though we haven't unlocked Journeymap yet. 

Let me know if you need more info.

**Comment by artdude543** [comment]
Please, can you update to 3.0.3 and confirm is the issue is still persisting thanks!

**Comment by TwilightPSN** [comment]
this is fixed on my server with 3.0.3

**Comment by davqvist** [comment]
Yes, seems to be fixed (although we unlocked Journeymap in between so it is not fully confirmable)
