### ISSUE TITLE
Horsepowered Grindstone

### ISSUE THREAD

**Issue by LucieTwi** [Darkosto/SevTech-Ages#959]
I just built my first horsepowered grindstone. I put it in the middle of a 7x7x2 area, but it will show a red text saying, that the area is not valid. I put the horsepowered choppingblock in the exact same spot and there is no problem. So the area should be valid. No idea what the problem is.
Version 3.0.2

**Comment by artdude543** [comment]
Ensure you have it up one block and the surrounding area being clear :)

![](https://i.artdude.uk/gU3S7kP9.jpg)

**Comment by LucieTwi** [comment]
ooh, I didn't get the one-block-up-thing XD Thanks a lot!
