### ISSUE TITLE
One ore to another

### ISSUE THREAD

**Issue by Charles12875** [Darkosto/SevTech-Ages#96]
I found that if one takes copper or tin clusters and puts one type inside the flaming whopper then adds the other type, i.e. if you first put tin now you would add copper, the second type added is made into the first type. So one can take a single tin cluster put it in then add an entire stack of copper cluster and end up with a full stack of tin cluster.

![minecraft 1 12 1 9_24_2017 10_00_01 am](https://user-images.githubusercontent.com/23129604/30784727-97ce56a4-a10f-11e7-9a5a-b3487f3081a7.png)
![minecraft 1 12 1 9_24_2017 10_00_12 am](https://user-images.githubusercontent.com/23129604/30784730-9e1d5f50-a10f-11e7-83ab-c9f4f6769566.png)
![minecraft 1 12 1 9_24_2017 10_00_20 am](https://user-images.githubusercontent.com/23129604/30784731-a22113da-a10f-11e7-9f97-19abdaa8c3b7.png)
![minecraft 1 12 1 9_24_2017 10_00_25 am](https://user-images.githubusercontent.com/23129604/30784734-a507d138-a10f-11e7-8cb5-dab6c4f4ee90.png)

### Issue / bug
 - Explain the issue / bug as understandably as possible.
 - If possible add minecraft, forge, java and modpack version numbers for debugging (mod authors might need these).
 - If the issue/bug is recurring explain how it can be recreated (helps darkosto!).
 - If possible add error/crash log to [Pastebin](https://pastebin.com/) and link it here (if you dislike pastebin any other similar site is fine too).
 - If possible add a video/gif of the issue/bug (makes it easier for darkosto to understand you).

**Comment by Darkosto** [comment]
Good catch! We'll take a look at it :)

**Comment by Darkosto** [comment]
@vadis365 This happens when items with the same ID and different meta data is placed inside the hopper.

**Comment by vadis365** [comment]
Could some one test if this happens on the Whopper Mk.2 as well please? - The Flame Grilled Whopper extends from the Whopper Mk.2 - I don't have time to test in a pack environment atm.
If so, please report and I'll add it to the list of things to fix in the next version.
Cheers,
Me.

**Comment by vadis365** [comment]
Also I'm a little unclear as to the steps, it it when you click on the hopper to add stuff eg. put some copper in and then click the same slot with a different meta stack and it adds to it? - If so I think I may have found the offending line of code and it's an easy fix - if not I can dig deeper O.o
If it is what I asked above - it will be this line of conditions that is missing any sort of check for metadata - whoops :P

**Comment by ALongStringOfNumbers** [comment]
https://clips.twitch.tv/GeniusDoubtfulStinkbugTwitchRPG for a demonstration

**Comment by vadis365** [comment]
fixed
