### ISSUE TITLE
Unable to craft a crafting table in stage one

### ISSUE THREAD

**Issue by Petrel63** [Darkosto/SevTech-Ages#960]
I have just reached stage one and want to craft a crafting table for the advancement "Upgrade your crafting".

When I look in JEI I can see the standard minecraft crafting table but when I click on it to see the recipe nothing happens. Clicking on 'Crafting table on a Stick' does give the recipe, but I can't then click on the required crafting table to see its recipe.

I have tried crafting it using four planlks on the work stump and in my 2x2 inventory crafting grid but neither work.

I am using SevTech 3.0.0. I downloaded the zip file and then used MultiMC to launch minecraft (I use Linux so the TwitchApp is unavailable to me)

Hope this is enough info. Thanks for all your work
Petrel

### Before anything else, use the *search* feature!
 * Maybe someone already reported the issue you're experiencing?
 * Maybe you can find the answer to your question by looking at older or closed issues?
 * Have a go at it and see!
 
 ### Issue / bug
 - Explain the issue / bug as understandably as possible.
 - If possible add minecraft, forge, java and modpack version numbers for debugging (mod authors might need these).
 - If the issue/bug is recurring explain how it can be recreated (helps darkosto!).
 - If possible add error/crash log to [Pastebin](https://pastebin.com/) and link it here (if you dislike pastebin any other similar site is fine too).
 - If possible add a video/gif of the issue/bug (makes it easier for darkosto to understand you).

**Comment by justinrusso** [comment]
Please update. This issue specifically is fixed in 3.0.1.
