### ISSUE TITLE
Cant interact with the world with anything in my hand.

### ISSUE THREAD

**Issue by Ebullio** [Darkosto/SevTech-Ages#961]
got a server running and seemingly it working as intended, i can interact with every thing in the world as long as my hand is **EMPTY**, but if im holding anything(literally anything) and try to break anything, and i mean anything at all, nothing happends. 
Which means i cant progress as im never gonna be able to get wood with the flintaxe, as having that equipped i cant break anything.

**Comment by artdude543** [comment]
Right; you going to have to give more information about this. 

I.E. Version (Client/Server), How you went about making the server.

Also that you're not trying to break things around the spawn chunk as you can't anyway.

**Comment by Ebullio** [comment]
I ended up fixed it my self, had the newest version of the together forever mod .11 on both the pc´s that was connecting to my privat dedicated server, which for some reason created the issue i described, i reverted back to the .10 version of the mod and everything now works as intended.
