### ISSUE TITLE
Advancements not registering (age 1)

### ISSUE THREAD

**Issue by bgaigalas** [Darkosto/SevTech-Ages#962]
I have made it to age one and after three advancements (hoe, crafting table, and basin), my advancements are no longer registering. 

I have crafted channels, anvil, chest, furnace, and weak dowsing rod, all of which are the next advancements in the chain, and they have not registered as being completed. I have restarted my game (going to title menu and completely closing and reopening the game) and tried to recreate the items and throwing them down/picking them back up, but they still aren't registering as completed. 

I have looked through github bug reports, ftb reddit, and general googling but I can't find anybody else facing this issue. 

Let me know if you have any further questions, thanks!

**Comment by bgaigalas** [comment]
Single player, sorry. Version 3.0.1.

**Comment by artdude543** [comment]
Update to 3.0.2 please and try again; you may still have an issue but need to confirm on the latest version.

**Comment by bgaigalas** [comment]
Updating worked. The twitch launcher wasn't registering an update so i didn't think there was one. Thanks much!
