### ISSUE TITLE
Totemic ceremony of death

### ISSUE THREAD

**Issue by Dontfearthereaper25** [Darkosto/SevTech-Ages#963]
Hey all. Been having issues with getting this dance done. I have all the items required for the dance and did what I was told about using multiple items however I cannot seem to get the bar to go up before the timer runs out. I'm using 6 chimes 6 drums imbuer flute Shaker and eagle flute. Still not having any luck summoning the boss. Any tips or pointers. I use every items too scrolling back and forth but still no luck

**Comment by MrScrubTZ** [comment]
The way I did the harder ceremonies is by putting a rattle and 2 imbued flutes in 1,2 and 3 slot.
while standing on 4 drums I start the ceremony and spam 1,2,3 while hitting the drums. works good so far 👍

**Comment by Dontfearthereaper25** [comment]
Thanks alot I'll have to try this later tonight.

**Comment by Dystilled** [comment]
Took me a few goes to complete. 

Did it with: 
Drum, Wind Chime, Bone Flute, Rattle, Flute (Imbued and in off hand), Chime Dress. 

It really is just a race against the second bar for this one, If you're not getting much charge from what you're doing switch to another instrument.
