### ISSUE TITLE
Brief explanation of sticks in Tutorial

### ISSUE THREAD

**Issue by Kmartinator** [Darkosto/SevTech-Ages#967]
I came into this pack blind, and with my particular spawn, I didn't find sticks on the ground until I ventured a little ways out.  I had broken a few leaves and trees and hadn't gotten sticks, so I was at a loss on how to start, since sticks are required for the initial mesh.

Could there maybe be a quick addition of a sentence or so on one of those tutorial advancements? Maybe on Fibrous Diet, just a quick mention of "and sticks from leaves or on the ground."

Thanks!

**Comment by artdude543** [comment]
Would this be on the lines as your thinking @Kmartinator?

`To get started, you'll need to collect Plant Fibers from breaking tall grass. Craft 3 together to get Plant Twine. Sticks can be found on the floor or by trimming some leaves.`

**Comment by Kmartinator** [comment]
Yea that's perfect!

**Comment by artdude543** [comment]
Awesome this will be added in the next version 😄
