### ISSUE TITLE
Error On World Startup/Random Crash

### ISSUE THREAD

**Issue by TieMonkey** [Darkosto/SevTech-Ages#97]
When I started a new world on the new alpha 3 pack I got this error   
"ERROR: mobstages.zs:31 > No such member: MobStages ERROR: [crafttweaker]: Error executing {[0:crafttweaker]: mobstages.zs}: 1"

As seen here https://i.imgur.com/kcerMYt.png. 

Then maybe 3 to 5 minutes afterwards of it just sitting idle on the chat screen the game crashed with this error https://pastebin.com/CgBZx3rq.

Minecraft Version 1.12.1
Forge Version 14.22.1.2485
Java Version 1.8.0_144
Modpack Version Alpha 3

**Comment by Darkosto** [comment]
Weird! I'll look into this. Thanks for the heads up :D

**Comment by Darkosto** [comment]
Should be all fixed up now. Thanks!
