### ISSUE TITLE
Unable to craft Wet Tanned Hide

### ISSUE THREAD

**Issue by lslinnet** [Darkosto/SevTech-Ages#974]
## Issue / Bug
When trying to create `Wet Tanned Hide` using the `Dried Hide` + `Ground Resin` + `Fluid bladder` the recipe do not result in a valid output even when JEI indicates that it would.
Trying in the inventory gives 0 valid crafting results.
![skaermbillede 2018-03-27 kl 20 57 42](https://user-images.githubusercontent.com/155903/37988964-78d6f376-3202-11e8-961a-6e4d48a99b3b.png)
Trying on the Work Stump gives the same result, no valid crafting result.
![skaermbillede 2018-03-27 kl 20 58 47](https://user-images.githubusercontent.com/155903/37989063-b0a811fe-3202-11e8-8170-8baa2d8ffdf2.png)

JEI says:
![skaermbillede 2018-03-27 kl 21 01 24](https://user-images.githubusercontent.com/155903/37989069-b74cf39e-3202-11e8-9bd4-2c584a81b26f.png)

My current progress is:
![skaermbillede 2018-03-27 kl 20 59 07](https://user-images.githubusercontent.com/155903/37989077-bd10d318-3202-11e8-9738-89cf947ec449.png)

## Current Behavior
Not able to craft `Wet Tanned Hide`

## Possible Solution
Guess there is an issue with the recipe.

## Steps to Reproduce (for bugs)
1. Have the 3 items
2. Attempt to craft

## Context
Blocking me from gaining leather and making progress.

## Your Environment
* Modpack Version: 3.0.1
* Java Version: jdk1.8.0_162.jdk (Java 8 IIRC)
* Launcher Used: Twitch
* Resourcepack Enabled?: nope
* Optifine Installed?: nope

**Comment by lslinnet** [comment]
Noticed there was a 3.0.2 version available... will test if I can reproduce in that.

**Comment by billybricker** [comment]
If you filled the fluid bladder from a barrel make sure it had a full 1,000MB of water in it. It can pick up less than a bucket but it won't work for crafting.

**Comment by lslinnet** [comment]
Good point, did check it - but will verify again once the game boots up on the new version.

**Comment by lslinnet** [comment]
Okay seems issue was missing water in the Bladder 👍 thanks for the hint!
