### ISSUE TITLE
Crashes about 3/4 of the way through startup

### ISSUE THREAD

**Issue by StrandedPB** [Darkosto/SevTech-Ages#975]
Downloaded the modpack from the Twitch app. I opened the Minecraft launcher and selected play. The game pops up normally with a loading screen and the dancing blue guy. Then (usually about 1/2 - 3/4 of the way through) the bars and the blue guy start slowing down, coming eventually to a stop. I've looked in task manager and saw it was taking about 95% - 100% of my cpu. And pressing the close button did nothing to the window, the only way to stop it was to either close it in TM or by letting it crash on its own.
Crash report that it gave me:

"The game crashed whilst initializing game
The game crashed whilst initializing game
Error: com.google.common.util.concurrent.ExecutionError: java.lang.OutOfMemoryError: GC overhead limit exceeded"

I've tried downloading the newest version of Java, didn't work

I have windows 10 with a i5 intel processor, 16 gb of ram, and a NVIDIA GeForce GTX 1050 Ti that came overclocked

**Comment by Buuz135** [comment]
Have you tried to allocate more ram to Minecraft

**Comment by artdude543** [comment]
As Buuz has suggested you need to allocate more memory to the game either via the launcher. Buuz has explained how to change the limit on the Twitch App :)
