### ISSUE TITLE
Game crashes when saving and quitting while single player is open to LAN

### ISSUE THREAD

**Issue by jvanollef** [Darkosto/SevTech-Ages#976]
## Issue / Bug

If I open my single player world to LAN, then choose the "Save and Quit to Title" the game crashes. It still seems to save, because when I load back in, I'm in the same place with the same items as when I quit. 

There isn't any crash log, it just gives you a message saying that the game crashed unexpectedly. 

![crash](https://user-images.githubusercontent.com/37848908/37992071-c02b0b88-31d8-11e8-9883-9269f292a92a.PNG)

## Your Environment

* Modpack Version: 3.0.1
* Java Version: 1.8.0_161
* Launcher Used: Twitch
* Resourcepack Enabled?: Soartex Invictus Modded Universal
* Optifine Installed?: Yes

**Comment by artdude543** [comment]
You'll have a client log can you upload that please?

**Comment by jvanollef** [comment]
[2018-03-27-1.log.gz](https://github.com/Darkosto/SevTech-Ages/files/1853710/2018-03-27-1.log.gz)
[2018-03-27-2.log.gz](https://github.com/Darkosto/SevTech-Ages/files/1853711/2018-03-27-2.log.gz)

I believe these are the correct logs. Please let me know if that's not the case.

**Comment by Ryzelf** [comment]
This is a common Vanilla Minecraft bug i believe.
Open to LAN is very buggy.

**Comment by garlicinyoureye** [comment]
^agreed, i've been experiencing this ever since MC went to 1.10

**Comment by gforero12** [comment]
I was unable to replicate this issue. I attempted to on versions 3.0.1 and 3.0.2 to no avail. I have seen other reports of people experiencing this with LAN in general although have personally never encountered this issue. Seeing as this is a bug related to vanilla MC I recommend closing this issue.

**Comment by jvanollef** [comment]
Yea, I haven't been on MC in almost 2.5 years. I didn't know it was a Vanilla issue, I'll close it.
