### ISSUE TITLE
Clay is meltable in the melter with charcoal fuel (200c) although NEI says it requires 500c to melt.

### ISSUE THREAD

**Issue by Electrofried** [Darkosto/SevTech-Ages#977]
## Issue / Bug

Clay can melt in the seared melter with charcoal fuel (200c) although it says it needs higher temperature (500c)

## Current Behavior

Clay melts at low temp...

## Possible Solution

No idea, not sure if bug or intended. Just happy to have bronze tools without lava.

## Steps to Reproduce (for bugs)

1. put clay in melter (tested with seared)
2. use charcoal for fuel
3. melt
4. profit

## Context

Making tools the second I unlocked age 2, nei made me sad, tried anyway. was happy nei was wrong.

## Your Environment

* Modpack Version: 3.0.1 because servers cant be updated yet :(
* Java Version: erm, latest (please dont hurt me)
* Launcher Used: multimc
* Resourcepack Enabled?: n/a
* Optifine Installed?: yes

**Comment by artdude543** [comment]
This does not seem to be an issue

![image](https://user-images.githubusercontent.com/1885466/39225012-00bef45a-4842-11e8-8e9a-5f7793c2cbbb.png)
