### ISSUE TITLE
Can't make unfired porcelain clay with miller to craft a melter. After 3.0.2 update.

### ISSUE THREAD

**Issue by SergeantShadow** [Darkosto/SevTech-Ages#979]
### Before anything else, use the *search* feature!
 * Maybe someone already reported the issue you're experiencing?
 * Maybe you can find the answer to your question by looking at older or closed issues?
 * Have a go at it and see!
 * Please search on the [issue track](../) before creating one.
 
## Steps to Reproduce (for bugs)

1.
2.

## Your Environment

* Modpack Version:
* Java Version:
* Launcher Used:
* Resourcepack Enabled?:
* Optifine Installed?:

**Comment by Aethix1** [comment]
In the Unfired Porcelain recipe, the Mill Stone is only recognizing the bone meal.  The results of putting in 1 bone meal, 1 clay, 1 flint (the unfired porcelain recipe) is to consume only the 1 bone meal and output 2 white dye powder.

**Comment by artdude543** [comment]
Please update to 3.0.3 which fixes the issue! :)
