### ISSUE TITLE
Better with mods manual Bug?

### ISSUE THREAD

**Issue by frogger35** [Darkosto/SevTech-Ages#981]
Four times now I have crafted a different block from the Better With Mods mod I get a new manual. This appears to be random as It doesn't happen on every thing I craft from the mod. It looks to be every time I first craft a new block like the gearbox, turntable, saw, broken gearbox -> fixed gearbox.  I can't reproduce this error but others on the server I play on report the same issue.

## Your Environment

* Modpack Version: 3.0.1
* Java Version: 1.8.0_144
* Launcher Used: twitch
* Resourcepack Enabled?: no
* Optifine Installed?: yes

**Comment by DaedalusGame** [comment]
This is fixed in 3.0.3 isn't it?

**Comment by frogger35** [comment]
I updated to 3.0.3 and haven't got a book as of yet crafting the blocks but can't craft anything new as of yet.

**Comment by artdude543** [comment]
Yep seems this is fixed in 3.0.3
