### ISSUE TITLE
Siding can't be placed against the eastern edge of a block space vertically.

### ISSUE THREAD

**Issue by djnifos** [Darkosto/SevTech-Ages#982]
## Issue / Bug
Before the update to 3.03 they could be placed vertically, I built my house out of them.  Northern side, southern side, and western side of block space still works fine.  To replicate, place a piece of siding against a block that you're targeting, while looking west.  The intended result should be a placed siding. 
For reference, they were placed correctly while I was playing yesterday.
![image](https://user-images.githubusercontent.com/2243466/38003103-9a41f4d6-31fb-11e8-9a4b-5553b9636eb9.png)

## Your Environment

* Modpack Version: 3.03
* Java Version: 161
* Launcher Used: Jar
* Resourcepack Enabled?: Soartex
* Optifine Installed?: Yes

**Comment by primetoxinz** [comment]
Fixed in BWM dev.

**Comment by artdude543** [comment]
This will be fixed in the next version. Thanks for reporting!

**Comment by djnifos** [comment]
Yesterday I noticed that the previews for placement were gone except against vanilla grass.  Odd behavior, but likely the same cause.

**Comment by djnifos** [comment]
Just wanted to add that it's not fixed as of 3.04 still.  Not a super big deal, just wanted to make sure it was still on the radar.

**Comment by djnifos** [comment]
Fixed in 3.0.5
