### ISSUE TITLE
New Versions (0.2, 0.3) don't trigger Twitch Launcher update warning. 

### ISSUE THREAD

**Issue by Dystilled** [Darkosto/SevTech-Ages#984]
Don't know if this is something on Twitch's side or if its a setting in how the updates are being done. 

But I'm not getting alerts there are updates to the pack, I manually have to go into the profile of the pack and tell it to update from the versions tab. 

All other installed modpacks are detecting updates fine and giving alerts there are other versions. 

On the Twitch Launcher, I do not use ATL.

**Comment by Buuz135** [comment]
That's on twitch, it can't be controlled.

**Comment by Darkosto** [comment]
This is not our issue. This is a twitch issue and keep in mind updates don't immediately show, the client has to sync which can take longer for some people.
