### ISSUE TITLE
Tinker's table variants visible when going into age 2.

### ISSUE THREAD

**Issue by Muddr** [Darkosto/SevTech-Ages#986]
All the Tinker's stencil table and parts builder tables are visible in NEI when going from age 1 into 2.  Leaving SP and going back into the world fixes it. 

Also the Kepler 22b variants still show after coming back into the world. 

Wouldn't be so bad if they had recipes but only 1 in that bunch does. 

Part's Builder.
![2018-03-27_22-53-10](https://user-images.githubusercontent.com/1361860/38007259-977df13a-3216-11e8-9fb0-a46ab20a830b.png)

Stencil Table.
![2018-03-27_22-56-28](https://user-images.githubusercontent.com/1361860/38007264-9f261714-3216-11e8-9ed4-b57a00b69a78.png)

Kepler 22b plank versions. 
![2018-03-27_23-30-33](https://user-images.githubusercontent.com/1361860/38007352-0ac21f68-3217-11e8-8a85-272ebb20fe54.png)

**Comment by justinrusso** [comment]
https://github.com/Darkosto/SevTech-Ages/issues/704
