### ISSUE TITLE
"Steak & Potatoes" worse than components

### ISSUE THREAD

**Issue by tofof** [Darkosto/SevTech-Ages#987]
## Issue / Bug
The "steak and potatoes" item is underpowered.

## Current Behavior
Cooked steak: 4 shanks, 6.5 saturation, 4% protein
Baked potato: 2.5 shanks, 3 saturation, 2.5% vegetable
Sum of components: **6.5 shanks, 9.5 saturation, 4% protein, 2.5% vegetable**

Steak and potatoes: 2.5 shanks, 2.5 saturation, 2.1% protein, 2.1% vegetable
Recipe makes two, sum: **5 shanks, 5 saturation, 4.2% protein, 4.2% vegetable**
So that's approximately 75% of the shanks and 50% of the saturation, in exchange for +0.2 protein and +1.7 vegetable. 

## Possible Solution
Make steak & potatoes worth at least **3.5 shanks and 4.5 saturation, and 2.5% protein**, so that the sum would be **7 shanks, 9 saturation, 5% protein, 4.2% vegetable**.
This is still a slight loss in saturation but that's offset by the shank, and then the nutrition benefit is still worthwhile.

If you do this, however, the "Steak Dinner" (and then also "Pork Dinner") needs a little love; domino-effect.
Current sum of its components is **8 shanks, 11 saturation, 4% protein, 4% vegetable**.
Dinner is 3 shanks, 3.5 saturation, 2.5% protein, 2.5% vegetable.
Makes three, sum: **9 shanks, 10.5 saturation, 7.5% protein, 7.5% vegetable**.

So it probably needs to be **3 shanks, 4 saturation**, for a total of **9 shanks, 12 saturation, 7.5% protein, 7.5% vegetable**

## Context
There's no reason to ever make "steak and potatoes" compared to just eating its ingredients, unlike the other combined foods (steak dinner, tasty sandwich, kebab, etc).

## Your Environment
* Modpack Version: 3.0.0
(other details omitted as this isn't a bug)

**Comment by Darkosto** [comment]
Then don't make it. This is on the mod, not the modpack. I have no control over how much food/saturation a food can offer.
