### ISSUE TITLE
Water Wheel Crash

### ISSUE THREAD

**Issue by ArcticWhiteFox** [Darkosto/SevTech-Ages#988]
Attempting to break a Water Wheel from Better with Mods (While running with water) crashes the game client and any others within the chunk.

Crashlog: https://paste.ee/p/e57ZT

**Comment by K3ll06s** [comment]
Shift right click to pick it up also crashes my game.

**Comment by artdude543** [comment]
Reported to the mod developers: https://github.com/BetterWithMods/BetterWithMods/issues/820

**Comment by artdude543** [comment]
This will be fixed in the next version :) Thanks for reporting!

**Comment by Ragestrike** [comment]
just a heads up, if you decide to individually update better with mods, it will erase any placed better with mod objects that are in the world, so make sure they are in your inventory, i lost my whole windmill, axle, gearbox set up i had.  it just vanished.

**Comment by artdude543** [comment]
This is fixed in 3.0.4 please update! 😄
