### ISSUE TITLE
default "carry on" mod keybinds prevents opening the mortar Gui

### ISSUE THREAD

**Issue by OranHexthief** [Darkosto/SevTech-Ages#989]
### Before anything else, use the *search* feature!
 * Maybe someone already reported the issue you're experiencing?
 * Maybe you can find the answer to your question by looking at older or closed issues?
 * Have a go at it and see!
 * Please search on the [issue track](../) before creating one.
 
## Steps to Reproduce (for bugs)

1.
2.

## Your Environment

* Modpack Version:
* Java Version:
* Launcher Used:
* Resourcepack Enabled?:
* Optifine Installed?:

the shift right click is supposed to open the mortar and pestal gui from the betweenlands mod but instead it picks up the mortar to move it. changing the keybind fixed it but that is kinda out of the way for someone not looking too hard

**Comment by mtimyself** [comment]
It is an issue as old as the mod itself.
Standing further away from the target block also helps.

**Comment by Buuz135** [comment]
You can also change the keybind

**Comment by artdude543** [comment]
You will need to change the keybinds yourself. It's as easy as opening up the control menu and re-assigning :)
