### ISSUE TITLE
Terrain Blackened Out

### ISSUE THREAD

**Issue by AMR2586** [Darkosto/SevTech-Ages#990]
Since updating to 3.0.3, whenever I try to enter an existing world or start a new one, the terrain does not load correctly. It is completely blackened out. The only things that are not blackened out are creatures and the sky. This is happening for worlds on and off of servers for me.

Thank you,
Adam

**Comment by artdude543** [comment]
This is an old issue; along with sounding like a client-side issue rather than a pack. I suggest you update Java/Graphics Drivers and try again. If you still get the issue please re-log an issue following the issue template. Thanks!
