### ISSUE TITLE
Nested "Improved Backpack" Crash

### ISSUE THREAD

**Issue by ChipmunkCraft** [Darkosto/SevTech-Ages#992]
## Issue / Bug
When purposely (or accidentally) nesting an "Improved Backpack" the game will freeze and crash upon exiting the backpack menu and trying to "Save and Quit to Title."
Before trying to quit, the player is unable to interact with the world.

## Possible Solution
Implementing a way to prevent "accidental" or even "purposeful" nesting would prevent this issue.

## Steps to Reproduce (for bugs)
1. Create 2 "Improved Backpacks" (unsure if they have to be fully upgraded but mine are)
2. Nest one backpack inside the other and close the menu.
3. Attempt to interact with world (This step not obligatory)
4. Will have to force close game which produces a "Exception in server tick loop" crash report

## Your Environment

* Modpack Version: 3.0.2
* Java Version: Version 8 (Update 161)
* Launcher Used: Twitch Launcher
* Resourcepack Enabled?: Yes, Faithful 32, Faithful Mod and Dramatic Skies
* Optifine Installed?: Yes (I don't imagine optifine would have an effect on this particular issue)

**Comment by artdude543** [comment]
First off thank your using the issue layout your amazing! Second any chance you can pastebin the client log; this will have the information we need to pass this on to the mod developer :) Thanks!

**Comment by ChipmunkCraft** [comment]
Absolutely, you are very welcome. Interestingly enough, it didn't create a client crash log, but created a server crash log after the game finally crashed. I have attached the server crash log in case that helps.

It usually takes a minute to crash after realizing you can't interact with the world anymore. 

[crash-2018-03-27_16.17.37-server.txt](https://github.com/Darkosto/SevTech-Ages/files/1857270/crash-2018-03-27_16.17.37-server.txt)

I have cleared out my "latest.log" so if I do it again, there should be additional info in there I can provide.

**Comment by artdude543** [comment]
This issue will be fixed in 3.0.7. The mod dev is around again and working on fixing things :)
