### ISSUE TITLE
Parrot epidemic

### ISSUE THREAD

**Issue by Xetard** [Darkosto/SevTech-Ages#993]
Since 3.0.3 the parrot spawn was upped and since then i have had a parrot epidemic which makes every chunk lag.
![pic 3](https://user-images.githubusercontent.com/37865195/38018701-ef6d5962-3275-11e8-81cf-50cfe1c9c041.png)
![pic 2](https://user-images.githubusercontent.com/37865195/38018705-f35a1bd2-3275-11e8-852d-07b7b7d01c58.png)

**Comment by DaedalusGame** [comment]
![screenshot_20](https://user-images.githubusercontent.com/9559216/38020912-c4cbce2c-327b-11e8-8777-fcc70986a266.png)

What a party, Mark

**Comment by Xetard** [comment]
Its truely annoying, i need to move my house due to the chunk lags are terrible

**Comment by artdude543** [comment]
Okay we will look into this one.

**Comment by Xetard** [comment]
There are about 10 times the amount of parrots in those chunks now since i printed the pictures.

**Comment by Darkosto** [comment]
People are upset because there are no parrots. People are upset because there are too many parrots. I find it even more hilarious because the weight and group sizes are set to the absolute lowest.

**Comment by Ragestrike** [comment]
Heres a solution,  we need to give the parrots a natural predator to keep their population in check. http://www.whateats.com/what-eats-a-parrot lmao

**Comment by DaedalusGame** [comment]
say no more

**Comment by BonaireDreams** [comment]
Confirming this as well. Server tps dropping to 8-12 tps until we use Kill command to get rid of all the parrots.

**Comment by artdude543** [comment]
We have tweaked the limit in 3.0.4 so please update and try. You may have to murder them all for the setting to take effect, however.
