### ISSUE TITLE
trying to make porcelain

### ISSUE THREAD

**Issue by msrevenge** [Darkosto/SevTech-Ages#997]
hi so I'm trying to make porcelain with the bone meal clay and flint but its giving me white dye power in the mill instead of porcelain last night it was working but now ive updated its not working now so abit confused now

**Comment by msrevenge** [comment]
never mind I just got the update

**Comment by artdude543** [comment]
Yeah make sure you are on 3.0.3 as this fixes the isssue :)

**Comment by msrevenge** [comment]
yh i got the update after i posted this ty :)
