### ISSUE TITLE
Using Lightning Arrow crashes a server

### ISSUE THREAD

**Issue by VoxelVixen** [Darkosto/SevTech-Ages#998]
Issue: Shooting a Lightning arrow with a Greatbow , both from Better with Addons , resulted our server to crash every time its used.

Crashreport: [Pastebin](https://pastebin.com/QTR5SAr2)

This is reproduced with the 3.0.1 and 3.0.3 versions of the pack by different players. 
I tested version 3.0.3 singleplayer but no crash happened.

Might want to inform the moddev about this for a fix.

**Comment by artdude543** [comment]
Report to the mod dev: https://github.com/DaedalusGame/BetterWithAddons/issues/85

**Comment by artdude543** [comment]
This is fixed in 3.0.4 please update! 😄
