### ISSUE TITLE
Certain chunks don't properly render terrain when looking in certain directions (3.0.1 - 3.0.3)

### ISSUE THREAD

**Issue by LoryMaster** [Darkosto/SevTech-Ages#999]
While travelling the world I noticed certain chunks don't properly render terrain (making it possible to see through it and look at underground caves), but this only happens while looking at certain particular directions.

![2018-03-28_12 23 11](https://user-images.githubusercontent.com/15781149/38023514-d11516be-3282-11e8-9d5c-e4474d973f98.png)
 
This bug doesn't seem to really create any problems other than the visual glitch. Changing View Distance sometimes fixes it, but usually exiting and re-entering the faulty chunks results in it reappearing again. Exiting and re-entering the game doesn't change anything.

Here's the seed of the world I'm using:
-1530554473998855636

Unfortunately I don't know how to retrieve the coordinates of some faulty chunks I've found...

I've started playing on version 3.0.1 and the bug has always been there up until the latest 3.0.3.
I'm playing through the Twitch Launcher with the Soartex Fanver Modded Universal. Optifine version HD_D1

**Comment by Possemaster** [comment]
You could set below option to False in the **Forge.cfg** file to possibly fix this issue.

```
# Enable forge to queue all chunk updates to the Chunk Update thread. May increase FPS significantly, but may also cause weird rendering lag. Not recommended for computers without a significant number of cores available.
B:alwaysSetupTerrainOffThread=true
```

**Comment by LoryMaster** [comment]
Doubt its the problem cause the rendering is not lagged. It just doesn't happen properly. Testing this anyway and gonna report back.

**Comment by LoryMaster** [comment]
As I thought changing that config didn't solve the issue.

**Comment by artdude543** [comment]
You're on an old version of Java please changing to using the Jar Launcher. You can follow this guide https://docs.google.com/document/d/e/2PACX-1vR5muyi1m7Zy_qSwrzeb9e3tbbRlksguNUb_Pvm3pn9eDpsIkUj5qQUq6WFPPdEoVWZq91WvvH57KzC/pub also try updating your Graphics Drivers. But this is not a pack issue but client-side and could be perf based on the system.
